# -*- coding: utf-8 -*-
import json

batch_data = {
    "dataset_id": "108-2_medicine-2",
    "batch_id": "108-2_medicine-2_batch-004",
    "items": [
        {
            "question_id": "108-2_medicine-2_046",
            "question_number": 46,
            "correct_answer": "A",
            "category_group": "醫學（二）",
            "category": "公共衛生學",
            "category_confidence": "high",
            "key_point": "掌握職業性肺結核的認定與申報原則。",
            "explanation": "員工入職時的胸部X光檢查可證實其入職前是否已患肺結核，此為判斷是否因職業暴露而感染的關鍵比較資料。肺結核為法定傳染病，與職業病的認定並不衝突，若符合標準仍可申報並獲得勞保職業病給付；醫院中不同部門（如胸腔科與行政室）之感染風險亦不相同；醫護人員感染肺結核須證實有職業接觸史才算職業病。",
            "flashcard_front": "職業性肺結核 / 入職胸部X光 / 勞保給付 / 感染風險判定",
            "flashcard_back": "入職時的X光片是職業病判定的重要基準資料；法定傳染病與職業病不衝突，可同時申報勞保給付。",
            "flashcard_summary": "職業性肺結核認定 -> 入職胸部X光片是判定職業病的重要基準，且與法定傳染病申報不衝突。"
        },
        {
            "question_id": "108-2_medicine-2_047",
            "question_number": 47,
            "correct_answer": "A",
            "category_group": "醫學（二）",
            "category": "公共衛生學",
            "category_confidence": "high",
            "key_point": "區分社會支持（Social support）的不同類型與定義。",
            "explanation": "提供具體的物質資源、場地、資金或勞力協助等，屬於「工具性支持（Instrumental support）」，因此提供家中的桌球室空間供鄰居運動是工具性支持的典型例子。情感性支持指給予關懷與陪伴；資訊性支持指提供建議或資訊；評價性支持指提供回饋以進行自我評估。",
            "flashcard_front": "社會支持類型 / 提供運動場地空間 / 工具性、情感性、資訊性支持 / 區分",
            "flashcard_back": "提供實體的空間、物資、資金或直接服務以協助他人，皆屬於「工具性支持」。",
            "flashcard_summary": "社會支持類型 -> 提供實體場地或資源（如桌球室）屬於「工具性支持」。"
        },
        {
            "question_id": "108-2_medicine-2_048",
            "question_number": 48,
            "correct_answer": "A",
            "category_group": "醫學（二）",
            "category": "公共衛生學",
            "category_confidence": "high",
            "key_point": "區分健康促進計畫評價的類型與定義。",
            "explanation": "過程評價（Process evaluation）著重於計畫執行過程中的資源投入、活動執行度及參與率是否符合預期。結果評價評估計畫結束後的短期成效；衝擊評價評估中長期的健康指標改變；形式評價指計畫規劃初期的需求評估與可行性分析。",
            "flashcard_front": "健康促進 / 計畫評價 / 參與率、資源運用與執行投入 / 過程評價 / 定義",
            "flashcard_back": "評估計畫執行過程中的參與率、資源使用率及工作投入是否符合預期，屬於「過程評價」。",
            "flashcard_summary": "衛生計畫評價 -> 評估參與率與資源投入是否符合預期屬於「過程評價」。"
        },
        {
            "question_id": "108-2_medicine-2_049",
            "question_number": 49,
            "correct_answer": "B",
            "category_group": "醫學（二）",
            "category": "公共衛生學",
            "category_confidence": "high",
            "key_point": "理解醫院策略規劃中的整體策略類型。",
            "explanation": "垂直整合（Vertical integration）是指醫院向照護流程的上游（如整合診所）或下游（如整合長照）進行擴張，這屬於「成長策略」，而非穩定策略。作業流程再造與合理化則常作為穩定策略的一部分；整體策略包含成長、穩定、緊縮與混合策略，其中混合策略允許不同部門採取不同方向的策略。",
            "flashcard_front": "醫院經營管理 / 垂直整合 / 整體策略 / 成長策略、穩定策略 / 區分",
            "flashcard_back": "垂直整合（整合上下游照護機構）屬於「成長策略」，非「穩定策略」；流程再造屬於穩定策略。",
            "flashcard_summary": "醫院策略類型 -> 垂直整合屬於「成長策略」，而非穩定策略。"
        },
        {
            "question_id": "108-2_medicine-2_050",
            "question_number": 50,
            "correct_answer": "B",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "區分新藥臨床試驗的不同階段與受試人數。",
            "explanation": "第三階段（Phase III）臨床試驗為大規模多中心研究，受試者通常在 1000 到 3000 名患者，主要目的是確認藥物的療效與安全性。第一階段通常為數十名健康受試者以評估耐受性與藥動學；第二階段為數百名患者以評估劑量與初步療效；第四階段為藥物上市後的監測。",
            "flashcard_front": "新藥研發 / 臨床試驗 / 受試人數 1000~3000 人 / 階段區分",
            "flashcard_back": "受試人數在1000至3000人之間的大規模多中心試驗，主要確認療效與安全性，屬於「第三階段」臨床試驗。",
            "flashcard_summary": "臨床試驗第三階段 -> 受試者1000至3000名、確認療效與安全性，屬於「第三階段」臨床試驗。"
        },
        {
            "question_id": "108-2_medicine-2_051",
            "question_number": 51,
            "correct_answer": "A",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "選擇旅行者下痢（革蘭氏陰性菌）的首選治療抗生素。",
            "explanation": "旅行者下痢通常是由革蘭氏陰性菌（如 ETEC 等）引起，首選的經驗性治療藥物為氟喹諾酮類（Fluoroquinolones）抗生素，如 levofloxacin。Vancomycin 主要針對革蘭氏陽性菌；sulfacetamide 主要局部用於眼部；trimethoprim 單用效果較弱且抗藥性高。",
            "flashcard_front": "旅行者下痢 / 止瀉藥無效 / 革蘭氏陰性桿菌 / 首選抗生素",
            "flashcard_back": "旅行者因革蘭氏陰性桿菌引起的下痢，首選治療藥物為氟喹諾酮類（如 levofloxacin）。",
            "flashcard_summary": "旅行下痢首選藥物 -> 革蘭氏陰性桿菌感染引起的下痢，首選 fluoroquinolones 類藥物（如 levofloxacin）。"
        },
        {
            "question_id": "108-2_medicine-2_052",
            "question_number": 52,
            "correct_answer": "C",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "掌握防止冠狀動脈支架再狹窄的免疫抑制劑。",
            "explanation": "Sirolimus（又稱 rapamycin）可藉由抑制 mTOR 途徑來阻斷細胞週期，進而抑制血管平滑肌細胞的過度增生，因此常被塗覆在藥物洗脫支架（DES）上以防止術後冠狀動脈再狹窄。Cyclosporine 與 tacrolimus 主要是透過抑制 calcineurin 抑制 T 細胞活化，皆非支架包覆的主流選擇；azathioprine 為抗代謝藥物。",
            "flashcard_front": "冠狀動脈支架塗藥 / 抑制平滑肌細胞增生 / 防治再狹窄 (restenosis) / 免疫抑制劑",
            "flashcard_back": "藥物洗脫支架常使用 sirolimus (rapamycin) 包覆，透過抑制 mTOR 途徑來抑制細胞增生，預防血管再狹窄。",
            "flashcard_summary": "支架包覆藥物 -> sirolimus (rapamycin) 可抑制細胞增生，常用於防止支架置入後血管再狹窄。"
        },
        {
            "question_id": "108-2_medicine-2_053",
            "question_number": 53,
            "correct_answer": "D",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "掌握 Sulfonylureas 類降血糖藥物的作用機轉。",
            "explanation": "Sulfonylureas 類藥物（如 glipizide、glimepiride）的主要作用機轉是結合並關閉胰臟 β 細胞上的 ATP 敏感性鉀離子通道（K_ATP），引起細胞去極化，促使電壓敏感性鈣通道開放，鈣離子流入從而「促進胰島素的分泌」。它們不能增加胰島素受體數目，亦非直接提高胰島素本身敏感性。",
            "flashcard_front": "降血糖藥物 / Sulfonylureas / 作用機轉 / 胰臟 β 細胞",
            "flashcard_back": "Sulfonylureas 藉由關閉 β 細胞的 K_ATP 通道引發去極化，進而促進胰島素的分泌。",
            "flashcard_summary": "Sulfonylureas 機轉 -> 關閉 ATP 敏感性鉀通道，促進胰島素分泌。"
        },
        {
            "question_id": "108-2_medicine-2_054",
            "question_number": 54,
            "correct_answer": "C",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "區分不同利尿劑在腎小管的作用部位與轉運體機轉。",
            "explanation": "Thiazide 類利尿劑主要作用於遠端彎曲小管，藉由抑制 Na+/Cl- 共轉運體（co-transporter）來減少鈉與氯的再吸收，產生利尿作用。Acetazolamide 抑制近端小管的碳酸酐酶；triamterene 抑制集尿管的保鉀鈉通道；bumetanide 抑制亨利氏環粗上升支的 Na+/K+/2Cl- 轉運體。",
            "flashcard_front": "遠端彎曲小管 / 抑制 Na+/Cl- 轉運體 / 利尿劑選擇",
            "flashcard_back": "Thiazide 類利尿劑作用於遠端彎曲小管，抑制 Na+/Cl- 共轉運體而達到利尿效果。",
            "flashcard_summary": "Thiazide利尿劑作用部位 -> Thiazide 類利尿劑作用於遠端彎曲小管，抑制 Na+/Cl- 轉運體。"
        },
        {
            "question_id": "108-2_medicine-2_055",
            "question_number": 55,
            "correct_answer": "D",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "識別僅適用於預防氣喘發作的吸入性藥物。",
            "explanation": "Nedocromil 為肥大細胞穩定劑，主要作用是阻止肥大細胞釋放發炎介質，只適合用於「預防性給藥」，若氣喘已發作，因其不具直接舒張支氣管的作用，故完全無療效。Albuterol 為速效 beta-2 促效劑，適用於急性發作；theophylline 具氣管舒張效果；salmeterol 為長效 beta-2 促效劑，非單純無效，但 nedocromil 是完全不具舒張功能。",
            "flashcard_front": "氣喘急性發作 / 預防性給藥 / 發作時給予無療效 / 肥大細胞穩定劑",
            "flashcard_back": "Nedocromil (肥大細胞穩定劑) 僅能預防發炎介質釋出，不具支氣管舒張作用，故氣喘急性發作時給予無效。",
            "flashcard_summary": "氣喘預防用藥 -> Nedocromil 僅作預防，急性發作時無氣管舒張療效。"
        },
        {
            "question_id": "108-2_medicine-2_056",
            "question_number": 56,
            "correct_answer": "A",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "掌握急性偏頭痛的治療與預防用藥的區分。",
            "explanation": "Buspirone 為 5-HT1A 受體部分促效劑，主要用於治療廣泛性焦慮症，對偏頭痛的急性治療或預防皆無效。Sumatriptan（5-HT1B/1D 促效劑）和 dihydroergotamine 用於急性偏頭痛的緩解治療；propranolol（乙型阻斷劑）則常用於偏頭痛的慢性預防性治療。",
            "flashcard_front": "偏頭痛治療 / 急性與預防 / Buspirone、Sumatriptan、Propranolol / 鑑別選擇",
            "flashcard_back": "Buspirone 用於抗焦慮，無法治療偏頭痛；Sumatriptan、Dihydroergotamine用於急性期，Propranolol 用於預防。",
            "flashcard_summary": "偏頭痛藥物選擇 -> Buspirone 無法預防或治療偏頭痛，Sumatriptan用於急性，Propranolol用於預防。"
        },
        {
            "question_id": "108-2_medicine-2_057",
            "question_number": 57,
            "correct_answer": "D",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "掌握乙醇代謝與病變主要影響器官。",
            "explanation": "乙醇主要在「肝臟」中代謝，其代謝過程中會產生具有強烈毒性的乙醛，並導致 NADH/NAD+ 比例升高，促進脂肪酸合成並抑制脂肪酸氧化，從而引起脂肪肝、酒精性肝炎乃至肝硬化。雖然長期酗酒也會影響胰臟與心臟，但肝臟是受乙醇代謝直接影響且產生病變最顯著且重要的器官。",
            "flashcard_front": "乙醇代謝 / 主要病變器官 / 脂肪肝、肝炎、肝硬化",
            "flashcard_back": "肝臟是乙醇代謝的主要器官，其產生的乙醛毒性與代謝失衡是引起酒精性肝病變的最關鍵因素。",
            "flashcard_summary": "乙醇病變主要器官 -> 肝臟是乙醇引起病變最重要且嚴重的器官。"
        },
        {
            "question_id": "108-2_medicine-2_058",
            "question_number": 58,
            "correct_answer": "B",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "掌握部分促效劑（partial agonist）的藥理學性質定義。",
            "explanation": "部分促效劑（partial agonist）對受體的內在活性（intrinsic efficacy）小於完全促效劑（full agonist），即使在受體全部飽和結合的狀況下，也無法達到完全促效劑所能產生的最大效應。Binding affinity 是指結合親和力，部分促效劑的 affinity 不一定小於完全促效劑；與完全促效劑合用時，部分促效劑會作為競爭性拮抗劑而降低整體的 efficacy，而非加成。",
            "flashcard_front": "部分促效劑 (Partial agonist) / 內在活性 (Intrinsic efficacy) / 與完全促效劑合用",
            "flashcard_back": "部分促效劑的內在活性（efficacy）小於完全促效劑，與完全促效劑合用時會產生拮抗效果。",
            "flashcard_summary": "部分促效劑性質 -> 部分促效劑的內在活性（intrinsic efficacy）小於完全促效劑。"
        },
        {
            "question_id": "108-2_medicine-2_059",
            "question_number": 59,
            "correct_answer": "C",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "記憶抗結核藥 Isoniazid (INH) 的代謝路徑與副作用。",
            "explanation": "Isoniazid 主要在肝臟中透過 N-acetyltransferase 進行乙醯化（acetylation）代謝，臨床上可分為快速乙醯化者與慢速乙醯化者。Isoniazid 的作用機轉是抑制 mycolic acid 的合成（干擾細胞壁生成而非細胞膜）；其給藥途徑主要為口服；視神經病變是 ethambutol 的特徵副作用，而 isoniazid 則易引起周邊神經炎（可用維生素 B6 預防）。",
            "flashcard_front": "結核病藥物 / Isoniazid (INH) / 肝臟乙醯化 / N-acetyltransferase",
            "flashcard_back": "Isoniazid 主要由肝臟中的 N-acetyltransferase 進行乙醯化代謝；其主要毒性為肝毒性與周邊神經炎。",
            "flashcard_summary": "Isoniazid 代謝與副作用 -> Isoniazid主要由肝臟之N-acetyltransferase代謝，易產生周邊神經炎。"
        },
        {
            "question_id": "108-2_medicine-2_060",
            "question_number": 60,
            "correct_answer": "C",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "掌握孕婦抗生素使用的禁忌與新生兒副作用原因。",
            "explanation": "Sulfonamides 類抗生素在懷孕末期或新生兒使用時，會與膽紅素競爭結合白蛋白，容易在缺乏 G6PD 的新生兒中誘發溶血作用，導致游離膽紅素過高而引發核黃疸。A: 影響第八對腦神經是 aminoglycosides（如 streptomycin）的副作用；B: 造成軟骨發育受損是 fluoroquinolones 的副作用；D: 灰嬰症候群是 chloramphenicol 的副作用。",
            "flashcard_front": "孕婦禁用抗生素 / 溶血與核黃疸 / G6PD 缺乏 / 新生兒黃疸",
            "flashcard_back": "Sulfonamides 易與膽紅素競爭白蛋白，且在 G6PD 缺乏新生兒中引發溶血與核黃疸；tetracycline 則是導致牙齒染色及骨骼發育受阻。",
            "flashcard_summary": "孕婦禁用 sulfonamides 原因 -> 易導致 G6PD 缺乏新生兒溶血，釋放膽紅素引起核黃疸。"
        }
    ]
}
