# -*- coding: utf-8 -*-
import json

batch_data = {
    "dataset_id": "108-2_medicine-3",
    "batch_id": "108-2_medicine-3_batch-004",
    "items": [
        {
            "question_id": "108-2_medicine-3_046",
            "question_number": 46,
            "correct_answer": "A",
            "category_group": "醫學（三）",
            "category": "感染科",
            "category_confidence": "high",
            "key_point": "掌握非結核分枝桿菌（NTM）的治療原則。",
            "explanation": "非結核分枝桿菌（NTM）常僅為人體呼吸道的定殖菌（colonization），且其臨床病程通常進展緩慢，故確認培養陽性後需結合臨床與影像學評估，不可「一律立刻治療」。治療通常需多藥聯合以防抗藥性；例如 MAC 常用 macrolide、ethambutol 及 rifamycin 治療；M. kansasii 則常用 INH、rifampin 及 ethambutol 治療。",
            "flashcard_front": "非結核分枝桿菌 (NTM) / 確診培養陽性 / 治療時機 / 定殖與感染 / 多藥治療",
            "flashcard_back": "確認 NTM 感染後不可盲目立刻治療，需評估症狀與影像學以區分定殖或活動性感染；治療需多藥聯合。",
            "flashcard_summary": "NTM 治療時機 -> 發現 NTM 培養陽性不可立刻盲目給藥治療，需結合臨床與影像評估並採多藥療法。"
        },
        {
            "question_id": "108-2_medicine-3_047",
            "question_number": 47,
            "correct_answer": "C",
            "category_group": "醫學（三）",
            "category": "新陳代謝科",
            "category_confidence": "high",
            "key_point": "掌握甲狀腺癌切除及同位素治療後的追蹤生化指標。",
            "explanation": "甲狀腺球蛋白（Thyroglobulin, Tg）僅由甲狀腺組織產生。接受甲狀腺全切除及放射碘-131清除治療後的甲狀腺癌病患，血中 Tg 應測不到；若在隨訪中 Tg 重新升高，則是腫瘤復發或轉移之重要且特異的生化指標。T3、T4、TSH 主要反映甲狀腺功能或藥物補充劑量，不適合作為腫瘤復發的直接追蹤指標。",
            "flashcard_front": "甲狀腺癌切除 / 放射碘-131 治療 / 復發追蹤 / 生化指標 / Thyroglobulin",
            "flashcard_back": "甲狀腺球蛋白（Thyroglobulin, Tg）是全切除及碘-131治療後追蹤甲狀腺癌是否復發的首選指標。",
            "flashcard_summary": "甲狀腺癌復發追蹤 -> 甲狀腺球蛋白（Tg）是全切除及碘-131治療後追蹤甲狀腺癌復發的重要生化指標。"
        },
        {
            "question_id": "108-2_medicine-3_048",
            "question_number": 48,
            "correct_answer": "A",
            "category_group": "醫學（三）",
            "category": "新陳代謝科",
            "category_confidence": "high",
            "key_point": "理解低血糖的臨床病因與流行病學特徵。",
            "explanation": "臨床上低血糖「最常見」的原因是糖尿病藥物（如外源性胰島素、sulfonylureas）使用不當，而非胰島素瘤。雖然胰島素瘤（insulinoma）的典型表現確實是 Whipple's triad（低血糖症狀、血糖低於 50 mg/dL、給糖後症狀改善），但其發病率極低，非常罕見。低血糖有致死風險，表現為心悸、冒冷汗、昏迷等症狀，須及時處理。",
            "flashcard_front": "低血糖 / 最常見原因 / 胰島素瘤 (insulinoma) / Whipple's triad / 降血糖藥",
            "flashcard_back": "低血糖最常見的原因是糖尿病藥物使用不當；胰島素瘤雖以 Whipple's triad 表現但極為罕見。",
            "flashcard_summary": "低血糖病因 -> 低血糖最常見病因為降血糖藥物使用不當，胰島素瘤雖以 Whipple's triad 著稱但極為罕見。"
        },
        {
            "question_id": "108-2_medicine-3_049",
            "question_number": 49,
            "correct_answer": "C",
            "category_group": "醫學（三）",
            "category": "家庭醫學科",
            "category_confidence": "high",
            "key_point": "掌握非自主性體重流失的定義與病因特徵。",
            "explanation": "甲狀腺功能亢進時，由於全身代謝率大幅增加，患者通常會出現「食慾亢進（增加）」但體重依然下降的現象，而非食慾減退。非自主性體重流失定義為 6-12 個月內體重下降大於原先體重的 5% 或超過 4.5 公斤；慢性阻塞性肺病（COPD）因呼吸功增加與發炎反應，也是體重流失的常見病因。",
            "flashcard_front": "非自主性體重流失 / 甲狀腺功能亢進 / 食慾變化 / 體重減輕定義 / COPD",
            "flashcard_back": "甲亢引起的體重流失伴隨「食慾增加」（非減退）；體重流失定義為 6-12 個月內下降 > 5% 或 4.5 公斤。",
            "flashcard_summary": "甲亢與體重流失 -> 甲亢引起體重流失的主因為高代謝，通常伴隨食慾亢進而非減退。"
        },
        {
            "question_id": "108-2_medicine-3_050",
            "question_number": 50,
            "correct_answer": "B",
            "category_group": "醫學（三）",
            "category": "新陳代謝科",
            "category_confidence": "high",
            "key_point": "區分參與脂質代謝的不同脂肪酶之功能與部位。",
            "explanation": "分解「血液中」脂蛋白（如乳糜微粒、VLDL）所含三酸甘油脂的酶是脂蛋白脂肪酶（lipoprotein lipase, LPL）；而荷爾蒙敏感性脂肪酶（hormone-sensitive lipase, HSL）主要作用於「脂肪細胞內」，促使儲存的三酸甘油脂分解為游離脂肪酸釋入血液。腸道脂肪被吸收後會包裝成乳糜微粒進入淋巴管；血液中的 VLDL 會逐步轉化為 LDL；HDL 可與其他脂蛋白進行脂質交換。",
            "flashcard_front": "脂質代謝 / 血液中三酸甘油脂分解 / HSL 與 LPL / 脂肪細胞 / 轉化",
            "flashcard_back": "分解血液中脂蛋白內三酸甘油脂的是 LPL；分解脂肪細胞內儲存三酸甘油脂的則是 HSL。",
            "flashcard_summary": "脂肪酶功能區分 -> 分解血液中三酸甘油脂的是 LPL，而 HSL 則負責分解脂肪細胞內的甘油三酯。"
        },
        {
            "question_id": "108-2_medicine-3_051",
            "question_number": 51,
            "correct_answer": "B",
            "category_group": "醫學（三）",
            "category": "新陳代謝科",
            "category_confidence": "high",
            "key_point": "掌握甲亢心律不整病患的用藥禁忌與原因。",
            "explanation": "Amiodarone 是一種抗心律不整藥，其化學結構富含碘，在體內代謝會釋放出大量無機碘，容易引起碘誘發的甲狀腺功能亢進（Jod-Basedow effect），從而使原本的甲亢惡化。因此，因甲亢造成心律不整的患者，應儘量避免使用 amiodarone，可改用乙型阻斷劑（如 propranolol）等其他藥物治療。",
            "flashcard_front": "甲狀腺功能亢進 / 心律不整 / 禁用抗心律不整藥 / 結構富含碘 / Amiodarone",
            "flashcard_back": "甲亢患者禁用 amiodarone，因其含碘量高，代謝釋碘會引發 Jod-Basedow 效應而惡化甲亢。",
            "flashcard_summary": "甲亢心律不整用藥禁忌 -> 甲亢心律不整病患應避免使用富含碘的 amiodarone，以防誘發甲亢惡化。"
        },
        {
            "question_id": "108-2_medicine-3_052",
            "question_number": 52,
            "correct_answer": "D",
            "category_group": "醫學（三）",
            "category": "新陳代謝科",
            "category_confidence": "high",
            "key_point": "掌握診斷橋本氏甲狀腺炎（Hashimoto's thyroiditis）的特異性自體抗體。",
            "explanation": "橋本氏甲狀腺炎（慢性淋巴球性甲狀腺炎）是由於針對甲狀腺的自體免疫反應所致，患者血中通常可檢測到高濃度的抗甲狀腺過氧化酶抗體（anti-TPO）及抗甲狀腺球蛋白抗體（anti-Tg）。Anti-dsDNA 與紅斑性狼瘡相關；anti-IgG4 與 IgG4 相關疾病相關；anti-TSH 接受體抗體與葛瑞夫茲氏病（Graves' disease）相關。",
            "flashcard_front": "橋本氏甲狀腺炎 / 甲狀腺功能低下 / 診斷自體抗體 / anti-TPO / anti-Tg",
            "flashcard_back": "診斷橋本氏甲狀腺炎最特異的抗體是抗甲狀腺球蛋白抗體 (anti-Tg) 與抗甲狀腺過氧化酶抗體 (anti-TPO)。",
            "flashcard_summary": "橋本氏症診斷抗體 -> 診斷橋本氏甲狀腺炎首選檢測 anti-TPO 與 anti-Tg 抗體。"
        },
        {
            "question_id": "108-2_medicine-3_053",
            "question_number": 53,
            "correct_answer": "A",
            "category_group": "醫學（三）",
            "category": "新陳代謝科",
            "category_confidence": "high",
            "key_point": "掌握急性腎上腺危象（adrenal crisis）的急救與用藥原則。",
            "explanation": "當患者有長期使用外源性類固醇史，在突然停藥後因感染引發休克，高度疑似為急性腎上腺危象（adrenal crisis）。此為致命急症，臨床處置應在「立即抽血送驗 cortisol」後，不需等報告結果，必須「立即注射糖皮質素」進行搶救，延誤治療會引致死亡。等待報告或進行耗時的刺激測試在休克狀態下是不適當且危險的。",
            "flashcard_front": "長期類固醇停藥 / 感染、低血壓休克 / 腎上腺危象 / 急救用藥 / Cortisol 抽血",
            "flashcard_back": "懷疑腎上腺危象休克時，應立即抽血送驗 cortisol，且「不需等待報告」，立刻注射糖皮質素治療。",
            "flashcard_summary": "腎上腺危象處置 -> 懷疑腎上腺危象休克應立即抽血驗 cortisol 並「立刻注射糖皮質素」，不可等報告。"
        },
        {
            "question_id": "108-2_medicine-3_054",
            "question_number": 54,
            "correct_answer": "B",
            "category_group": "醫學（三）",
            "category": "感染科",
            "category_confidence": "high",
            "key_point": "掌握氟喹諾酮類（fluoroquinolones）抗生素的藥理與抗藥性特徵。",
            "explanation": "淋病雙球菌對氟喹諾酮類抗生素的抗藥性已大幅增加，因此目前已不再建議將其作為治療淋病的第一線藥物。Quinolones 屬於「殺菌型」藥物（抑制 DNA 複製）；除 moxifloxacin 外，大多數 quinolones（如 ciprofloxacin、levofloxacin）主要由腎臟排泄，腎衰竭需調劑量；此類藥物對綠膿桿菌具有殺菌活性，可用於中性球低下發燒患者。",
            "flashcard_front": "氟喹諾酮類抗生素 / 殺菌機轉 / 淋病雙球菌抗藥性 / 腎臟排泄 / 綠膿桿菌",
            "flashcard_back": "由於淋病雙球菌對氟喹諾酮類抗藥性高，不建議作一線用藥；此類藥物為殺菌劑且多由腎排泄。",
            "flashcard_summary": "氟喹諾酮類抗生素性質 -> 淋病雙球菌對其抗藥性高而不推薦為一線藥物；該藥為殺菌型且多由腎臟排泄。"
        },
        {
            "question_id": "108-2_medicine-3_055",
            "question_number": 55,
            "correct_answer": "B",
            "category_group": "醫學（三）",
            "category": "感染科",
            "category_confidence": "high",
            "key_point": "掌握類鼻疽（melioidosis）的傳播、診斷與治療原則。",
            "explanation": "類鼻疽病原菌（Burkholderia pseudomallei）主要存在於土壤與水源中，在急性肺炎感染伴隨菌血症時，可以透過血液或痰液培養進行確診。此病主要經接觸泥土或水源感染，極少人傳人；病原菌對第一代頭孢子素（cefazolin）具天然抗藥性，急性期首選為 ceftazidime；治療需分為急性與維持期，總療程需數月，無法在2週內治癒。",
            "flashcard_front": "類鼻疽 (Melioidosis) / 傳播途徑 / 診斷方法 / Cefazolin 抗藥性 / 療程時間",
            "flashcard_back": "類鼻疽在急性肺炎時可藉由血或痰培養診斷；對第一代頭孢子素具抗藥性，且治療需數月而非2週。",
            "flashcard_summary": "類鼻疽特徵 -> 類鼻疽可經血或痰培養確診，病原體對第一代頭孢子素具抗藥性，且需長期治療。"
        },
        {
            "question_id": "108-2_medicine-3_056",
            "question_number": 56,
            "correct_answer": "A",
            "category_group": "醫學（三）",
            "category": "感染科",
            "category_confidence": "high",
            "key_point": "理解中央靜脈導管相關血流感染（CRBSI）的最常見來源。",
            "explanation": "中央靜脈導管相關血流感染（CRBSI）最常見的感染來源是導管置入部位的「皮膚菌叢污染」，細菌沿著導管外壁移行進入血管內。製備藥物或輸液過程中的污染以及遠處血行植入雖然也是可能途徑，但隨著無菌技術的提升，其發生率已遠低於皮膚置入部位的污染。",
            "flashcard_front": "中央靜脈導管 (CVC) / 血流感染 (CRBSI) / 最常見感染來源 / 皮膚菌叢 / 預防",
            "flashcard_back": "導管相關血流感染最常見的感染來源是經由皮膚置入導管部位的皮膚共生菌污染。",
            "flashcard_summary": "導管相關感染源 -> 中央靜脈導管相關血流感染最常見的來源為皮膚置入部位之共生菌污染。"
        },
        {
            "question_id": "108-2_medicine-3_057",
            "question_number": 57,
            "correct_answer": "D",
            "category_group": "醫學（三）",
            "category": "感染科",
            "category_confidence": "high",
            "key_point": "掌握院內感染肺炎（HAP）合併敗血性休克的抗生素選擇原則。",
            "explanation": "患者在接受化療住院第 20 天發生肺炎並出現敗血性休克，屬於院內感染肺炎（HAP）且有中性球低下的風險，其致病菌可能為多重抗藥性菌（如綠膿桿菌），此時給予僅針對革蘭氏陽性菌為主的「第一代頭孢子素（cephalosporin）」是極不恰當且危險的。此時應立即進行培養，並經驗性給予廣效且具抗綠膿桿菌活性的抗生素治療。",
            "flashcard_front": "住院第20天 / 肺炎、敗血性休克 / 化療病患 / 不恰當治療 / 第一代頭孢子素",
            "flashcard_back": "院內肺炎合併休克高度懷疑綠膿桿菌等抗藥菌，不可給予第一代頭孢子素，必須使用廣效性抗生素。",
            "flashcard_summary": "院內肺炎休克用藥 -> 院內肺炎休克患者禁用第一代頭孢子素，應使用具抗綠膿桿菌活性的廣效性抗生素。"
        },
        {
            "question_id": "108-2_medicine-3_058",
            "question_number": 58,
            "correct_answer": "D",
            "category_group": "醫學（三）",
            "category": "感染科",
            "category_confidence": "high",
            "key_point": "掌握牙科處置預防感染性心內膜炎的投藥指引。",
            "explanation": "根據 AHA 及相關感染控制指引，僅有高風險心臟疾病患者（如裝有人工瓣膜、曾患心內膜炎或特定發紺性先天性心臟病者）在進行侵入性牙科處置（如傷及牙齦者）前才需給予預防性抗生素。對於一位 50 歲的「健康男性」進行洗牙（牙結石治療），「不需給與預防性抗生素」，不論其是否有盤尼西林過敏史。",
            "flashcard_front": "洗牙、牙結石治療 / 健康男性 / 預防心內膜炎 / 預防性抗生素 / 指引",
            "flashcard_back": "一般健康男性進行牙科洗牙處置時，不符合高危險心臟病史標準，因此不需給予預防性抗生素。",
            "flashcard_summary": "牙科處置與心內膜炎預防 -> 健康男性進行牙科結石治療，不需給予預防性抗生素以防止心內膜炎。"
        },
        {
            "question_id": "108-2_medicine-3_059",
            "question_number": 59,
            "correct_answer": "B",
            "category_group": "醫學（三）",
            "category": "感染科",
            "category_confidence": "high",
            "key_point": "掌握急性人類免疫不全病毒（HIV）感染的最早偵測指標。",
            "explanation": "在感染 HIV 後，病毒 RNA（透過 HIV viral load 檢測）約在感染後 10-12 天即可在血中偵測到，是目前能最早偵測到急性感染的指標。p24 抗原約在 14-16 天出現；HIV 抗體則需要 3-4 週或更久才產生；西方墨點法（Western blot）則是抗體確認檢驗，出現時間更晚。",
            "flashcard_front": "急性 HIV 感染 / 最早偵測指標 / HIV 病毒量 / p24 抗原 / 抗體篩檢",
            "flashcard_back": "HIV viral load（病毒量測量，即核酸檢測）是感染後最早能偵測到的標誌，早於 p24 抗原及抗體。",
            "flashcard_summary": "急性HIV最早偵測標誌 -> HIV 病毒量（viral load）是急性 HIV 感染中最早能偵測到的診斷指標。"
        },
        {
            "question_id": "108-2_medicine-3_060",
            "question_number": 60,
            "correct_answer": "A",
            "category_group": "醫學（三）",
            "category": "感染科",
            "category_confidence": "high",
            "key_point": "記憶與抗病毒藥 Abacavir 嚴重超敏感反應相關的 HLA 基因。",
            "explanation": "Abacavir 是一種抗 HIV 藥物，其引起的致死性超敏感性反應（HSR）與人體白血球抗原基因 HLA-B*57:01 密切相關。臨床上規定在處方 Abacavir 前必須進行 HLA-B*57:01 基因篩檢，若為陽性者有極高風險發生過敏，因而被列為絕對禁忌症。HLA-B*58:01 與 Allopurinol 引起的 SCAR（如 SJS）相關；HLA-B27 與僵直性脊椎炎相關。",
            "flashcard_front": "Abacavir / 超敏感性反應 (HSR) / 藥物基因學 / 篩檢基因 / 禁忌症",
            "flashcard_back": "Abacavir 引起的致死性超敏感性反應與 HLA-B*57:01 基因相關，陽性者禁用此藥。",
            "flashcard_summary": "Abacavir與基因相關性 -> Abacavir引起的嚴重過敏反應與 HLA-B*57:01 基因密切相關，陽性者禁用。"
        }
    ]
}
