# -*- coding: utf-8 -*-
import os
import json

# Ensure reports/gemini_outputs/ directory exists
os.makedirs("reports/gemini_outputs", exist_ok=True)

# Allowed categories: "小兒科", "皮膚科", "神經科", "精神科", "醫學倫理與醫療決策", "其他"

batch_001_items = [
    {
        "question_id": "111-1_medicine-4_001",
        "question_number": 1,
        "correct_answer": "A",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "流感疫苗的開始接種年齡與兒童接種劑次規定。",
        "explanation": "流感疫苗建議施打的年齡為出生滿6個月以上，而非1歲以上，因此選項A錯誤。對於8歲（含）以下初次接種流感疫苗的兒童，應接種2劑，且兩劑需間隔4週（1個月）以上以獲得足夠保護力。B型流感病患在臨床上可以使用神經胺酸酶抑制劑（如克流感、樂瑞沙）進行治療。此外，病毒感染患者常有白血球偏低或正常的血液學表現。",
        "flashcard_front": "流感疫苗最低施打年齡 / 8歲以下初次施打 / 間隔時間與劑次",
        "flashcard_back": "出生滿6個月以上即可施打流感疫苗；8歲以下初次施打需2劑且間隔1個月以上。",
        "flashcard_summary": "流感疫苗接種年齡與劑次 -> 滿6個月以上可施打，8歲以下初次接種需2劑且間隔1個月。"
    },
    {
        "question_id": "111-1_medicine-4_002",
        "question_number": 2,
        "correct_answer": "A",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "先天性巨細胞病毒感染的臨床表現機率與聽力篩檢關聯。",
        "explanation": "先天性巨細胞病毒（CMV）感染的新生兒中，約有90%在出生時是無臨床症狀的，僅有約10%會出現症狀，故選項A敘述錯誤。母乳是新生兒CMV感染的重要來源，但對於足月健康的嬰兒而言，哺餵母乳的益處遠大於感染風險，故仍可哺餵。其臨床症狀包括肝脾腫大、黃疸、皮膚紫斑或紅疹，且CMV是造成非遺傳性先天性感覺神經性聽力喪失最常見的原因，因此未通過聽力篩檢者須考慮此感染。",
        "flashcard_front": "先天性CMV感染 / 新生兒有症狀比例 / 感覺神經性聽力喪失",
        "flashcard_back": "約90%先天性CMV感染的新生兒出生時無症狀；CMV是先天性感覺神經性聽損最常見病原。",
        "flashcard_summary": "先天性巨細胞病毒症狀比例 -> 約90%出生時無症狀，是先天性感覺神經性聽損最常見原因。"
    },
    {
        "question_id": "111-1_medicine-4_003",
        "question_number": 3,
        "correct_answer": "B",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "學齡兒童細菌性咽喉炎最常見的致病菌。",
        "explanation": "在學齡兒童（5至15歲）中，細菌性急性咽喉炎最常見的致病原為A型鏈球菌（Group A Streptococcus, GAS），約佔所有兒童急性咽炎的15%至30%。個別選項如嗜血桿菌與肺炎鏈球菌雖是常見的呼吸道病原，但較少單獨引起急性咽喉炎。肺炎黴漿菌則多以非典型肺炎或下呼吸道感染為主要表現，而非典型的急性咽喉炎。",
        "flashcard_front": "學齡兒童 / 細菌性咽喉炎 / 最常見病原菌",
        "flashcard_back": "學齡兒童細菌性咽喉炎最常見的致病菌為A型鏈球菌（GAS）。",
        "flashcard_summary": "學齡兒童細菌性咽炎病原 -> 細菌性咽喉炎最常見致病原為A型鏈球菌（GAS）。"
    },
    {
        "question_id": "111-1_medicine-4_004",
        "question_number": 4,
        "correct_answer": "C",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "腸病毒感染的典型臨床表現與非典型表現之區別。",
        "explanation": "腸病毒主要感染黏膜與神經系統，典型表現包括手足口症、疱疹性咽峽炎、無菌性腦膜炎、腦炎、急性肢體無力及心肌炎等。骨髓炎（Osteomyelitis）為細菌感染骨骼所致（如金黃色葡萄球菌），並非腸病毒感染的典型表現，故選項C錯誤。",
        "flashcard_front": "腸病毒典型臨床表現 / 腦炎 / 心肌炎 / 骨髓炎",
        "flashcard_back": "腸病毒典型表現包括手足口症、腦炎與心肌炎，骨髓炎則為細菌性感染而非腸病毒典型表現。",
        "flashcard_summary": "腸病毒典型表現 -> 包含手足口症、腦炎、心肌炎等，不包含細菌性骨髓炎。"
    },
    {
        "question_id": "111-1_medicine-4_005",
        "question_number": 5,
        "correct_answer": "A",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "幼兒感冒最常見的併發症。",
        "explanation": "幼兒因耳咽管較短、寬且平直，感冒等上呼吸道感染後，病原體極易經由耳咽管進入中耳，因此急性中耳炎是幼童感冒最常見的併發症。急性鼻竇炎與細菌性肺炎也是可能的併發症但發生率較低。腦膜炎則是極罕見的併發症。",
        "flashcard_front": "2歲兒童 / 普通感冒 (Common cold) / 最常見併發症",
        "flashcard_back": "幼兒感冒最常見的併發症是急性中耳炎，與幼兒耳咽管發育尚未成熟有關。",
        "flashcard_summary": "幼兒感冒併發症 -> 2歲兒童感冒最常見的併發症為急性中耳炎。"
    },
    {
        "question_id": "111-1_medicine-4_006",
        "question_number": 6,
        "correct_answer": "D",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "結合型（PCV）與多醣體型（PPSV）肺炎鏈球菌疫苗的原理差異。",
        "explanation": "7價、10價及13價肺炎鏈球菌疫苗皆屬於「結合型疫苗」，將莢膜多醣體與蛋白質載體結合，能活化T細胞並產生免疫記憶，適用於2歲以下幼兒。而23價肺炎鏈球菌疫苗則是「莢膜多醣體疫苗」，無法誘發T細胞免疫且免疫記憶較差，對2歲以下幼兒無效。其製程與免疫機轉明顯不同，故答案選D。",
        "flashcard_front": "肺炎鏈球菌疫苗 / 結合型 (PCV) vs. 多醣體型 (PPSV) / 適用年齡",
        "flashcard_back": "7、10、13價為結合型疫苗；23價為莢膜多醣體疫苗，對2歲以下幼兒無法有效誘發免疫反應。",
        "flashcard_summary": "肺炎鏈球菌疫苗機轉 -> 7、10、13價為結合型疫苗，23價為莢膜多醣體疫苗。"
    },
    {
        "question_id": "111-1_medicine-4_007",
        "question_number": 7,
        "correct_answer": "D",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "單基因疾病分子診斷工具的選擇與限制。",
        "explanation": "螢光反原位雜交（FISH）的解析度約在數十萬至數百萬鹼基對（Mb級），適用於偵測染色體結構變異，並不適用於點突變等單基因疾病的分子診斷，故選D。連鎖分析與基於DNA定序的分析是診斷單基因疾病的標準工具。微陣列比較基因體雜交（aCGH）雖然主要用於偵測拷貝數變異（CNV），但對於某些涉及較大基因重排或缺失的單基因疾病仍可提供診斷。",
        "flashcard_front": "單基因疾病 / 分子診斷 / FISH 解析度限制 / aCGH",
        "flashcard_back": "FISH解析度在Mb級，主要用於染色體結構或微缺失診斷，不適於單基因點突變診斷。",
        "flashcard_summary": "單基因疾病診斷工具 -> FISH解析度不足，較不適宜用於單基因疾病的分子診斷。"
    },
    {
        "question_id": "111-1_medicine-4_008",
        "question_number": 8,
        "correct_answer": "B",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "Edwards氏症候群（18號三染色體症）的典型手部外觀。",
        "explanation": "Edwards氏症候群（18號三染色體症）常見的典型肢體外觀為「握拳時手指重疊」，通常是食指重疊在中指上、小指重疊在無名指上，且合併有搖椅樣腳底。Down氏症候群常見斷掌與低張力；Marfan氏症候群表現為蜘蛛指與關節過度伸展；脊髓性肌肉萎縮症則呈現全身性肌肉張力低下。",
        "flashcard_front": "新生兒肢體外觀 / 握拳手指重疊 (食指疊中指、小指疊無名指) / 18三體",
        "flashcard_back": "握拳且手指重疊（食指疊中指、小指疊無名指）是Edwards氏症候群的特徵性肢體表現。",
        "flashcard_summary": "Edwards氏症候群手部外觀 -> 握拳且手指重疊為Edwards氏症候群的特徵。"
    },
    {
        "question_id": "111-1_medicine-4_009",
        "question_number": 9,
        "correct_answer": "A",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "蠶豆症（G-6-PD缺乏症）患者的安全用藥與禁忌物質。",
        "explanation": "葡萄糖-六-磷酸鹽脫氫酵素缺乏症（G-6-PD缺乏症）患者在正常治療劑量下使用乙醯胺酚（Acetaminophen，普拿疼）是安全的，不需要特別避免。然而，龍膽紫、萘丸（樟腦丸）及磺胺類藥物皆為強氧化劑，會誘發紅血球發生嚴重的急性溶血，是G-6-PD患者必須嚴格禁用的物質。",
        "flashcard_front": "G-6-PD缺乏症 (蠶豆症) / 禁用氧化劑 / 磺胺劑 / 乙醯胺酚安全性",
        "flashcard_back": "蠶豆症應禁用強氧化物如龍膽紫、萘丸與磺胺劑；常用退燒藥乙醯胺酚在正常治療劑量下可安全使用。",
        "flashcard_summary": "蠶豆症藥物禁忌 -> 禁用龍膽紫、萘丸與磺胺劑，乙醯胺酚可安全使用。"
    },
    {
        "question_id": "111-1_medicine-4_010",
        "question_number": 10,
        "correct_answer": "C",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "遺傳代謝疾病與異常體味的對應關係。",
        "explanation": "三甲基胺尿症（Trimethylaminuria）俗稱「魚腥症」，是因為體內缺乏 FMO3 酵素，無法將食物代謝產生的三甲基胺（TMA）轉化為無味物質，導致TMA隨汗液、尿液排出而產生刺鼻魚腥味。異戊酸血症典型表現為汗腳酸臭味；苯酮尿症有霉味或鼠尿味；酪胺酸血症則常有高麗菜爛掉的甜臭味。",
        "flashcard_front": "魚腥味體臭 / 吃蛋黃或豬肝後加重 / 異常體味 / 汗腳味 / 霉味",
        "flashcard_back": "進食蛋黃或豬肝後產生魚腥體味為三甲基胺尿症；異戊酸血症為汗腳味；苯酮尿症為霉味。",
        "flashcard_summary": "異常體味與代謝病 -> 蛋黃豬肝誘發魚腥味為三甲基胺尿症；異戊酸血症為汗腳味。"
    },
    {
        "question_id": "111-1_medicine-4_011",
        "question_number": 11,
        "correct_answer": "C",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "新生兒腸道閉鎖在X光上的氣體泡泡表徵診斷。",
        "explanation": "腹部X光片顯示有「三團腸氣（Triple bubble sign）」，代表胃、十二指腸及近端空腸有氣體擴張，而更遠端的腸道無氣體，這是空腸閉鎖（Jejunal atresia）的典型影像特徵。相較之下，胃幽門狹窄多在出生2-3週後出現非膽汁性嘔吐；十二指腸閉鎖呈Double bubble sign（雙泡徵）；而迴腸閉鎖則會呈現多個擴張的腸氣圈。",
        "flashcard_front": "新生兒膽汁性嘔吐 / 腹部X光三泡徵 (Triple bubble sign) / 雙泡徵",
        "flashcard_back": "三泡徵提示空腸閉鎖；雙泡徵提示十二指腸閉鎖；幽門狹窄為非膽汁性單泡。",
        "flashcard_summary": "新生兒腸道閉鎖影像 -> 三泡徵提示空腸閉鎖，雙泡徵提示十二指腸閉鎖。"
    },
    {
        "question_id": "111-1_medicine-4_012",
        "question_number": 12,
        "correct_answer": "C",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "新生兒症狀性低血糖的立即處置原則。",
        "explanation": "該足月兒體重為2,200公克（小於胎齡兒），且在出生2小時內血糖為 20 mg/dL，已出現手腳震顫等症狀。對於有症狀的低血糖新生兒，首要處置是立即給予靜脈推注 10% 葡萄糖，隨後持續以 6-8 mg/kg/min 的葡萄糖輸注率緩慢滴注以維持血糖穩定。單純餵食母乳對於已有低血糖症狀的病童緩不濟急，且不宜僅觀察等待。",
        "flashcard_front": "新生兒低血糖 / 有症狀 (手腳震顫) / 血糖 20 mg/dL / 處置",
        "flashcard_back": "有症狀的低血糖新生兒應立即靜脈推注 10% 葡萄糖一次（2 mL/kg），隨後持續靜脈滴注葡萄糖。",
        "flashcard_summary": "新生兒低血糖處置 -> 有症狀低血糖需立即靜脈推注葡萄糖並接續點滴維持。"
    },
    {
        "question_id": "111-1_medicine-4_013",
        "question_number": 13,
        "correct_answer": "A",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "新巴拉德評估量表（New Ballard Score）推估新生兒週數的評估項目。",
        "explanation": "臨床上常使用新巴拉德評估量表（New Ballard Score）來推估無產檢史新生兒的妊娠週數，評估項目包含「物理成熟度」與「神經肌肉成熟度」。物理成熟度包括皮膚外觀、胎毛稀疏度、腳掌紋路、乳房發育程度、眼睛與耳朵等，但不包括「眼睛到耳朵的距離」，故選項A錯誤。",
        "flashcard_front": "新生兒妊娠週數估算 / 新巴拉德量表 (New Ballard Score) / 物理成熟度項目",
        "flashcard_back": "評估指標包括乳房、胎毛、腳掌紋路、耳廓彈性等，不包含眼耳距離。",
        "flashcard_summary": "新生兒週數估算 -> 新巴拉德量表物理評估項目包括乳頭、胎毛、腳掌紋等，不包含眼耳距離。"
    },
    {
        "question_id": "111-1_medicine-4_014",
        "question_number": 14,
        "correct_answer": "B",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "食道閉鎖合併氣管食道瘻管（TEF）的解剖分類與影像診斷。",
        "explanation": "嘴角冒泡泡且無法順利放入胃管，提示有「食道閉鎖」；而腹部X光能看到胃及腸氣，表示氣體可從氣管經由瘻管進入消化道，這說明存在「下段食道氣管瘻管」。因此，最常見的「上段食道閉鎖合併下段食道氣管瘻管（Gross Type C）」是符合這些臨床表現的最可能診斷。",
        "flashcard_front": "嘴角流涎冒泡 / 胃管受阻無法放入 / 腹部X光有胃腸氣",
        "flashcard_back": "胃管受阻提示食道閉鎖，X光有胃氣提示存在下段食道氣管瘻管，最可能為 Gross Type C。",
        "flashcard_summary": "食道閉鎖伴瘻管診斷 -> 胃管受阻且胃部有氣體，診斷為上段食道閉鎖合併下段食道氣管瘻管。"
    },
    {
        "question_id": "111-1_medicine-4_015",
        "question_number": 15,
        "correct_answer": "A",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "嬰幼兒消化道梗阻位置與膽汁性/非膽汁性嘔吐的分辨。",
        "explanation": "增生性胃幽門狹窄（HPS）的梗阻部位在幽門（胃出口），位於十二指腸壺腹（膽汁注入處）的近端，因此其嘔吐物不會含有膽汁，表現為非膽汁性嘔吐。而十二指腸閉鎖、腸旋轉不良合併扭轉、先天性巨結腸症等，其阻塞點皆在膽汁注入處的遠端，故其嘔吐物皆常含有綠色膽汁。",
        "flashcard_front": "嬰幼兒非膽汁性嘔吐 / 噴射狀嘔吐 / 阻塞部位 / 膽汁性嘔吐",
        "flashcard_back": "阻塞點在膽汁入口近端（如胃幽門狹窄）為非膽汁性嘔吐；膽汁入口遠端阻塞則為膽汁性嘔吐。",
        "flashcard_summary": "嬰幼兒嘔吐鑑別 -> 增生性胃幽門狹窄為非膽汁性嘔吐，其餘中下消化道阻塞多為膽汁性。"
    }
]

batch_002_items = [
    {
        "question_id": "111-1_medicine-4_016",
        "question_number": 16,
        "correct_answer": "A",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "嬰幼兒不同飲食與疾病狀態下容易缺乏的維生素種類。",
        "explanation": "維生素B12主要存在於動物性食物中，吃全素的兒童極易缺乏；且全素飲食若無額外補充也容易缺乏維生素D，故選項A正確。母乳中的維生素D及維生素K含量低於配方奶，因此純母乳哺育的嬰兒更容易缺乏維生素K與維生素D，通常需要額外補充以防出血或佝僂症。膽汁淤積症的病童因為膽汁分泌不足影響脂肪吸收，容易缺乏的是「脂溶性維生素（A、D、E、K）」，而非水溶性維生素。",
        "flashcard_front": "兒童吃全素 / 純母乳哺育 / 膽汁淤積症 / 維生素缺乏",
        "flashcard_back": "吃全素易缺 B12 與 D；純母乳易缺 D 與 K；膽汁淤積易缺脂溶性維生素（A、D、E、K）。",
        "flashcard_summary": "嬰幼兒維生素缺乏原因 -> 吃全素易缺B12與D，純母乳易缺D與K，膽汁淤積易缺脂溶性維生素。"
    },
    {
        "question_id": "111-1_medicine-4_017",
        "question_number": 17,
        "correct_answer": "B",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "嬰幼兒生長遲滯的器質性比例與追趕生長特徵。",
        "explanation": "生長遲滯（FTT）的兒童中，有高達 80% 以上屬於「非器質性生長遲滯」，主要與餵食習慣、環境或社會心理因素增長有關，僅有少數能經檢查找出確切的器質性病因，因此選項B敘述錯誤。營養不良時，體重會最先受到影響而下降，若持續數月則會影響身高發育，最後才影響頭圍。追趕生長期間，病童的熱量與蛋白質需求可達同齡的 1.5 倍，且前兩週的體重增加速度可達同齡兒童的 2 到 3 倍。",
        "flashcard_front": "生長遲滯 (FTT) / 器質性病因比例 / 追趕生長熱量與體重增加速度",
        "flashcard_back": "80%以上生長遲滯為非器質性（非身體疾病引起）；追趕生長熱量需求可達同齡1.5倍。",
        "flashcard_summary": "生長遲滯原因與追趕 -> 大多數FTT為非器質性，追趕生長需達1.5倍熱量。"
    },
    {
        "question_id": "111-1_medicine-4_018",
        "question_number": 18,
        "correct_answer": "D",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "新生兒延長性黃疸的鑑別診斷與直接型高膽紅素血症的處置。",
        "explanation": "當直接膽紅素佔總膽紅素比例大於 20%（或直接膽紅素大於 1.0 mg/dL）時，稱為結合型（直接型）高膽紅素血症，高度懷疑膽道閉鎖或新生兒肝炎，必須儘快住院或轉診檢查，因此選項D正確。延長性黃疸的嬰兒即使大便顏色異常或疑為母乳性黃疸，仍必須檢測膽紅素值以排除病理性原因。此外，非結合型黃疸總膽紅素值 12 mg/dL 在一個月大嬰兒通常不需要住院照光治療，且直接型膽紅素高時，照光治療無效。",
        "flashcard_front": "延長性黃疸 / 直接型高膽紅素血症 / 膽紅素比例 / 膽道閉鎖轉診",
        "flashcard_back": "直接膽紅素/總膽紅素比例 > 20% 提示直接型高膽紅素血症，須立即轉診排除膽道閉鎖；大便顏色異常不可僅觀察。",
        "flashcard_summary": "延長性黃疸評估 -> 直接/總膽紅素比例大於20%為直接型高膽紅素血症，須儘快住院或轉診排除膽道閉鎖。"
    },
    {
        "question_id": "111-1_medicine-4_019",
        "question_number": 19,
        "correct_answer": "D",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "兒童急性腸胃炎脫水評估與「儘早進食」處置原則。",
        "explanation": "該男嬰體重減輕約 6%，哭無淚且尿量減少，屬於中度脫水。最新兒科指引建議在口服點滴或靜脈輸液矯正脫水後，應「儘早恢復進食」，以促進腸道黏膜修復並縮短病程，故選項D最為適當。稀釋運動飲料的電解質不符合口服脫水鹽（ORS）標準，容易引起電解質不平衡。止瀉藥如 Loperamide 在幼兒腸胃炎中因有腸阻塞或毒性巨結腸症等副作用，屬臨床禁忌。",
        "flashcard_front": "幼兒急性腹瀉 / 中度脫水 / 脫水矯正後處置 / ORS vs 運動飲料 / 止瀉藥禁忌",
        "flashcard_back": "中度脫水矯正後應儘快恢復進食；運動飲料不合標準；Loperamide在幼兒為禁忌。",
        "flashcard_summary": "兒童腸胃炎處置 -> 脫水矯正後應儘早恢復進食，運動飲料及 Loperamide 不適用。"
    },
    {
        "question_id": "111-1_medicine-4_020",
        "question_number": 20,
        "correct_answer": "A",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "腎病症候群的高凝血併發症與抽搐的鑑別診斷。",
        "explanation": "腎病變患者因大量蛋白質與抗凝血酶III流失，處於極度「高凝血狀態」，因此容易發生腦部血管栓塞而非顱內出血，故選項A最不可能。此外，腎病變引起的水鈉滯留可能導致低血鈉；且高血壓與使用大量類固醇/免疫抑制劑是誘發可逆性後腦病變症候群（PRES）的常見原因。上述病理狀況皆可引發 Generalized tonic-clonic seizures，需要仔細鑑別。",
        "flashcard_front": "微小腎病變 / 類固醇治療 / 突然抽搐 / 高凝血 / PRES",
        "flashcard_back": "腎病變患者易呈高凝血狀態，抽搐需懷疑腦血管栓塞而非出血；低血鈉與PRES亦是常見原因。",
        "flashcard_summary": "腎病症候群抽搐病因 -> 高凝血狀態易併發腦血管栓塞（CVST）而非出血；PRES與低血鈉亦是可能病因。"
    },
    {
        "question_id": "111-1_medicine-4_021",
        "question_number": 21,
        "correct_answer": "B",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "近端腎小管功能障礙（Fanconi症候群）的臨床與實驗室特徵。",
        "explanation": "患者化療後出現輕微蛋白尿、尿糖、低血鉀及代謝性酸血症，這些多種近端腎小管重吸收功能障礙的表現，是典型的 Fanconi 症候群。Fanconi 症候群的特徵為近端腎小管全面性功能受損，導致葡萄糖、胺基酸、磷酸鹽及重碳酸鹽隨尿液流失。Bartter 與 Gitelman 症候群主要表現為代謝性鹼中毒而非酸中毒；第四型腎小管酸血症則會表現為高血鉀而非低血鉀。",
        "flashcard_front": "化療後 / 尿糖 / 輕微蛋白尿 / 低血鉀 / 代謝性酸中毒",
        "flashcard_back": "出現尿糖、蛋白尿伴隨低鉀酸中毒，為近端腎小管重吸收障礙的 Fanconi 症候群特徵。",
        "flashcard_summary": "Fanconi症候群特徵 -> 尿糖、蛋白尿、低血鉀與酸中毒為近端腎小管受損（Fanconi症候群）特徵。"
    },
    {
        "question_id": "111-1_medicine-4_022",
        "question_number": 22,
        "correct_answer": "D",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "嬰兒受虐性腦傷的三大典型病理特徵。",
        "explanation": "嬰兒受虐性腦傷（舊稱嬰兒搖晃症候群）的三大典型特徵為硬腦膜下出血（SDH）、視網膜出血（RH）以及瀰漫性腦水腫。相較之下，小腦出血在受虐性腦傷中屬於非常罕見的病理表現，故選D。",
        "flashcard_front": "嬰兒受虐性腦傷 / 三大典型特徵 (Classic Triad) / 罕見出血部位",
        "flashcard_back": "三大特徵為硬腦膜下出血、視網膜出血與腦水腫；小腦出血在受虐性腦傷中極罕見。",
        "flashcard_summary": "受虐性腦傷特徵 -> 典型特徵包含硬腦膜下出血、視網膜出血與腦水腫，不包含小腦出血。"
    },
    {
        "question_id": "111-1_medicine-4_023",
        "question_number": 23,
        "correct_answer": "D",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "單純型熱性痙攣的良性預後與檢查、藥物使用原則。",
        "explanation": "單純型熱性痙攣屬於良性臨床病程，發作後通常預後良好，因此不需常規接受腦電波（EEG）檢查，故選項D正確。臨床上不建議為了預防復發而常規給予長期抗癲癇藥物，且長期使用抗癲癇藥並不能降低患者未來轉變為癲癇的機率。此外，雖然退燒藥可以減輕病童發燒的不適，但實證醫學顯示退燒藥並不能降低熱性痙攣再次發作的風險。",
        "flashcard_front": "單純型熱性痙攣 / 退燒藥預防效果 / 腦電波檢查必要性 / 抗癲癇藥預防",
        "flashcard_back": "單純型熱性痙攣不需接受腦電波檢查；退燒藥或抗癲癇藥皆無法預防其復發。",
        "flashcard_summary": "單純型熱性痙攣處置 -> 不需做腦電波檢查，退燒藥與長期抗癲癇藥皆無法預防其復發。"
    },
    {
        "question_id": "111-1_medicine-4_024",
        "question_number": 24,
        "correct_answer": "A",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "兒童甲狀腺功能亢進的臨床代謝表現、數值與藥物治療。",
        "explanation": "甲狀腺功能亢進會使身體代謝率顯著增加，病童通常會出現「食慾大增（多食）」但體重卻減輕的現象，而非食慾減退，因此選項A最不適當。由於甲狀腺素會加速骨骼成熟與生長，患者在發病初期短期內可能會出現生長速度加快的現象。其典型實驗室數據為血中 Free T4 上升、TSH 受到強烈抑制（極低），首選藥物治療通常為 Methimazole。",
        "flashcard_front": "兒童甲狀腺亢進 / 食慾與體重 / 骨骼發育生長 / TSH 數值",
        "flashcard_back": "甲亢呈食慾大增但體重減輕，且生長速度短期加快；TSH呈極低值（受抑制）。",
        "flashcard_summary": "甲狀腺功能亢進特徵 -> 表現為食慾大增但體重減輕，TSH受到強烈抑制，首選藥物為Methimazole。"
    },
    {
        "question_id": "111-1_medicine-4_025",
        "question_number": 25,
        "correct_answer": "C",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "第一型與第二型糖尿病病理機轉與臨床特徵之差異。",
        "explanation": "第一型糖尿病（T1DM）屬於自體免疫疾病，主要是胰臟細胞受到自身免疫抗體破壞所致，因此T1DM患者「較常」合併其他自體免疫疾病（如自體免疫甲狀腺炎等），故選項C敘述錯誤。T1DM病童因缺乏胰島素，體型多偏消瘦，且發病時極易以糖尿病酮酸中毒為首發症狀。臨床上，患者終身需要依賴外源性胰島素治療。",
        "flashcard_front": "兒童第一型糖尿病 (T1DM) / 自體免疫共病 / 體型消瘦 / 首發 DKA",
        "flashcard_back": "T1DM為自體免疫病，較易合併其他自體免疫共病；常體型消瘦且易發 DKA，需胰島素治療。",
        "flashcard_summary": "第一型糖尿病特徵 -> 自體免疫機轉使其較易合併其他自體免疫共病，需終身注射胰島素。"
    },
    {
        "question_id": "111-1_medicine-4_026",
        "question_number": 26,
        "correct_answer": "D",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "川崎氏症急性期與恢復期的阿斯匹林劑量與IVIG治療劑量。",
        "explanation": "川崎氏症在急性發燒期的藥物治療中，阿斯匹林（Aspirin）的劑量為「高劑量」的 80-100 mg/kg/day，直到退燒後才改為低劑量的 3-5 mg/kg/day 作為抗血小板治療。免疫球蛋白的標準劑量為 2 g/kg 單次靜脈滴注，故選項D的 5 mg/kg 劑量錯誤。川崎氏症多發於5歲以下幼童，病因未明但可能與感染後免疫反應有關，其臨床特徵需與猩紅熱、麻疹等鑑別。",
        "flashcard_front": "川崎氏症 / 急性期 Aspirin 劑量 / 恢復期 Aspirin / IVIG 劑量",
        "flashcard_back": "急性期Aspirin使用高劑量（80-100 mg/kg/day）；IVIG單次劑量為 2 g/kg。",
        "flashcard_summary": "川崎氏症藥物劑量 -> 急性期使用高劑量Aspirin（80-100 mg/kg/day），IVIG劑量為 2 g/kg。"
    },
    {
        "question_id": "111-1_medicine-4_027",
        "question_number": 27,
        "correct_answer": "C",
        "category_group": "醫學（四）",
        "category": "皮膚科",
        "category_confidence": "high",
        "key_point": "異位性皮膚炎的好發部位演變與泡澡保濕照護觀念。",
        "explanation": "異位性皮膚炎病童的日常照護非常強調保濕，臨床指引建議可以進行泡澡（每日約10-15分鐘，水溫宜適中），並在泡完後3分鐘內立刻塗抹保濕劑以鎖住水分，並非不建議泡澡，故選項C錯誤。嬰幼兒好發於臉部及四肢伸側，但包尿布區通常因濕度高而較少受累。隨年齡增長，病灶會轉移至四肢關節屈側。",
        "flashcard_front": "兒童異位性皮膚炎 / 泡澡保濕照護 / 尿布區受累情況 / 年長好發部位",
        "flashcard_back": "可以泡澡保濕並於3分鐘內上保濕劑；包尿布區通常不受累；年長好發於四肢關節屈側。",
        "flashcard_summary": "異位性皮膚炎照護與部位 -> 建議適度泡澡保濕，包尿布區少受累，年長兒好發於四肢屈側。"
    },
    {
        "question_id": "111-1_medicine-4_028",
        "question_number": 28,
        "correct_answer": "B",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "嬰幼兒副食品添加時間與過敏預防觀念。",
        "explanation": "現代過敏免疫醫學研究指出，延遲添加副食品並不能預防過敏；相反地，建議於嬰幼兒4至6個月大時開始添加副食品，以建立口服耐受性並降低未來發生過敏的機率，因此選項B敘述不恰當。懷孕期間孕婦不需刻意避免海鮮、花生等高過敏原食物。此外，國際指引目前確實未建議常規使用益生菌來預防嬰幼兒過敏。",
        "flashcard_front": "預防嬰幼兒過敏 / 副食品添加時機 / 孕婦禁食海鮮必要性",
        "flashcard_back": "建議 4-6 個月大開始添加副食品以建立口服耐受，延後添加無預防過敏之效。",
        "flashcard_summary": "嬰幼兒過敏預防 -> 建議於4-6個月大開始添加副食品，延後添加無法預防過敏。"
    },
    {
        "question_id": "111-1_medicine-4_029",
        "question_number": 29,
        "correct_answer": "B",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "兒童後天性再生不良性貧血最常見的病因分類。",
        "explanation": "兒童後天性再生不良性貧血（Acquired aplastic anemia）雖然可能與某些藥物、化學毒物或病毒感染（如肝炎病毒、EBV）有關，但在絕大比例的臨床病例中，其最常見的病因仍然是「特發性」（不明原因）。這類特發性病患佔了所有病例的 70% 以上，因此答案選B。",
        "flashcard_front": "兒童後天性再生不良性貧血 / 最常見病因 / 藥物與毒物比例",
        "flashcard_back": "兒童後天性再生不良性貧血最常見病因為特發性（不明原因），佔 70% 以上。",
        "flashcard_summary": "再生不良性貧血病因 -> 兒童後天性再生不良性貧血最常見的病因是特發性（不明原因）。"
    },
    {
        "question_id": "111-1_medicine-4_030",
        "question_number": 30,
        "correct_answer": "B",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "小球性貧血與正球性貧血的鑑別診斷。",
        "explanation": "再生不良性貧血主要表現為全血球減少，其紅血球通常為正球性正色素性貧血，較不會以小球性貧血來表現，故選B。而缺鐵性貧血、海洋性貧血及鉛中毒，皆是臨床上非常典型的小球性低色素性貧血的病因。",
        "flashcard_front": "小球性貧血原因 / 缺鐵性貧血 / 海洋性貧血 / 再生不良性貧血紅血球大小",
        "flashcard_back": "缺鐵、地中海貧血與鉛中毒為小球性；再生不良性貧血為正球性正色素性貧血。",
        "flashcard_summary": "小球性貧血鑑別 -> 缺鐵、地中海貧血及鉛中毒為小球性，再生不良性貧血則為正球性。"
    }
]

batch_003_items = [
    {
        "question_id": "111-1_medicine-4_031",
        "question_number": 31,
        "correct_answer": "D",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "法洛氏四重症發紺隨年齡惡化的病理生理機轉。",
        "explanation": "法洛氏四重症（TOF）的發紺嚴重度主要取決於右心室出口狹窄（肺動脈狹窄）的程度。隨著嬰兒成長，右心室因長期阻力增加而代償性肥厚，導致右心室流出道狹窄程度隨時間逐漸惡化，使右至左分流增加，因而到了9個月大時才出現明顯的發紺現象。動脈導管與卵圓孔的關閉或持續開放並非此發紺加重的主要進展機轉。",
        "flashcard_front": "法洛氏四重症 (TOF) / 9個月大明顯發紺機轉 / 右心室肥厚與肺動脈狹窄",
        "flashcard_back": "TOF發紺嚴重度取決於肺動脈狹窄；右心室因長期阻力肥厚，流出道狹窄惡化致發紺加重。",
        "flashcard_summary": "TOF晚發發紺機轉 -> 右心室代償性肥厚加重右心室流出道狹窄，使右至左分流惡化。"
    },
    {
        "question_id": "111-1_medicine-4_032",
        "question_number": 32,
        "correct_answer": "C",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "大血管轉位（d-TGA）合併動脈導管引起之反向差異性發紺特徵。",
        "explanation": "在大血管轉位（d-TGA）新生兒中，若合併有開放性動脈導管，因為主動脈發自右心室，而肺動脈發自左心室，在動脈導管水平上，高含氧血會從肺動脈分流至降主動脈，從而供應下肢，使得下肢血氧飽和度反而可能高於上肢，此為「反向差異性發紺」。而單純心室中膈缺損或心內膜墊缺損在出生2天時通常不會表現出此類發紺。",
        "flashcard_front": "新生兒下肢血氧可維持 / 反向差異性發紺 / 大血管轉位 (d-TGA) 併 PDA",
        "flashcard_back": "d-TGA 合併 PDA 時，肺動脈紅血分流至降主動脈，下肢血氧飽和度可維持高於上肢（反向發紺）。",
        "flashcard_summary": "新生兒血氧與大血管轉位 -> d-TGA 合併 PDA 可出現下肢血氧高於上肢之反向差異性發紺。"
    },
    {
        "question_id": "111-1_medicine-4_033",
        "question_number": 33,
        "correct_answer": "B",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "部分肺靜脈回流異常（PAPVR）與心房中隔缺損（ASD）的血流動力學共性。",
        "explanation": "部分肺靜脈回流異常（PAPVR）是指部分肺靜脈沒有回流至左心房，而是異常回流至右心房或體靜脈系統，這會導致富氧血重新回到右心系統，造成右心室及右心房的容量負荷增加（左至右分流）。這種血流動力學改變與心房中隔缺損（ASD）造成的右心房及右心室擴大極為相似。相較之下，VSD與PDA主要造成左心容量負荷增加。",
        "flashcard_front": "部分肺靜脈回流異常 (PAPVR) / 右心容量負荷 / 左至右分流 / ASD 相似",
        "flashcard_back": "PAPVR使肺靜脈血流入右心系統，造成右房右室容量負荷增加，血流動力學與ASD最相似。",
        "flashcard_summary": "PAPVR血流動力學 -> 部分肺靜脈回流異常造成右心容量負荷增加，與心房中隔缺損（ASD）相似。"
    },
    {
        "question_id": "111-1_medicine-4_034",
        "question_number": 34,
        "correct_answer": "C",
        "category_group": "醫學（四）",
        "category": "皮膚科",
        "category_confidence": "high",
        "key_point": "異位性皮膚炎的臨床診斷要件與病理生理學特徵。",
        "explanation": "異位性皮膚炎的診斷主要依據臨床症狀（如反覆發作、劇癢、典型皮疹分布及個人或家族過敏史等），雖然多數患者血中 IgE 會上升，但 IgE 上升「並非」診斷的必須生物標記，故選項C錯誤。患者由於基因缺陷導致皮膚屏障功能受損，且皮膚表面極易被金黃色葡萄球菌定殖，其發作病程與情緒壓力、環境刺激等密切相關。",
        "flashcard_front": "異位性皮膚炎 / 診斷指標 / IgE 上升必要性 / 皮膚屏障 / 金黃色葡萄球菌",
        "flashcard_back": "異位性皮膚炎靠臨床診斷，血中IgE上升非必要條件；皮膚屏障常有缺陷且金黃色葡萄球菌定殖增加。",
        "flashcard_summary": "異位性皮膚炎診斷 -> 診斷依據為臨床表現，血中IgE上升非必要條件。"
    },
    {
        "question_id": "111-1_medicine-4_035",
        "question_number": 35,
        "correct_answer": "A",
        "category_group": "醫學（四）",
        "category": "皮膚科",
        "category_confidence": "high",
        "key_point": "落屑性皮膚炎（紅皮症）的病因與鑑別診斷。",
        "explanation": "落屑性皮膚炎（又稱紅皮症）是一種嚴重的全身性皮膚發紅及脫屑性疾病，常見原因包括乾癬、異位性皮膚炎、藥物過敏以及皮膚T細胞淋巴癌等。而毛囊炎通常為局部的細菌或黴菌感染，臨床上只表現為局部毛囊丘疹或膿疱，並不會引起全身性的落屑性皮膚炎。",
        "flashcard_front": "落屑性皮膚炎 (exfoliative dermatitis) / 紅皮症病因 / 毛囊炎臨床表現",
        "flashcard_back": "乾癬、異位性皮膚炎及皮膚T細胞淋巴癌可引起紅皮症；毛囊炎為局部毛囊感染，不引起紅皮症。",
        "flashcard_summary": "落屑性皮膚炎病因 -> 乾癬、異位性皮膚炎及CTCL可致落屑性皮膚炎，毛囊炎則不會。"
    },
    {
        "question_id": "111-1_medicine-4_036",
        "question_number": 36,
        "correct_answer": "B",
        "category_group": "醫學（四）",
        "category": "皮膚科",
        "category_confidence": "high",
        "key_point": "過敏性接觸性皮膚炎的第四型超敏反應免疫機轉。",
        "explanation": "過敏性接觸性皮膚炎為第四型超敏反應，在致敏過程中，表皮的藍格罕氏細胞擔任主要的抗原呈現細胞，故選項B正確。接觸過敏原多為小分子（分子量小於500 Daltons）的親脂性物質。致敏期通常約需7-10天且此階段並無臨床症狀，再次接觸過敏原時才會引發症狀嚴重的激發期。",
        "flashcard_front": "過敏性接觸性皮膚炎 / 免疫反應類型 / 表皮抗原呈現細胞 / 過敏原分子量",
        "flashcard_back": "屬第四型超敏反應，表皮藍格罕氏細胞為主要APC；過敏原多為小分子（<500 D）親脂物質。",
        "flashcard_summary": "ACD免疫機轉 -> 屬第四型超敏反應，表皮藍格罕氏細胞為主要抗原呈現細胞，過敏原多為小分子親脂半抗原。"
    },
    {
        "question_id": "111-1_medicine-4_037",
        "question_number": 37,
        "correct_answer": "D",
        "category_group": "醫學（四）",
        "category": "皮膚科",
        "category_confidence": "high",
        "key_point": "帶狀疱疹的單側神經節分佈與疼痛特徵。",
        "explanation": "該老年患者的皮疹呈現單側性、沿著特定神經節分佈的紅斑與群聚水疱，並伴隨顯著的晚上神經痛，這是非常典型的帶狀疱疹表現。接觸性皮膚炎通常有接觸史且以劇癢為主；單純性疱疹好發於黏膜交界且較局限、少呈廣泛神經節分布；膿痂疹為細菌感染之蜜黃色結痂皮損、無神經痛。",
        "flashcard_front": "單側紅斑水疱 / 沿神經節分布 (dermatomal) / 老年人劇烈神經痛",
        "flashcard_back": "群聚水疱呈單側神經皮節分佈並伴隨顯著神經痛，為帶狀疱疹的典型診斷特徵。",
        "flashcard_summary": "帶狀疱疹診斷 -> 沿單側神經節分佈的水疱與顯著神經痛為帶狀疱疹特徵。"
    },
    {
        "question_id": "111-1_medicine-4_038",
        "question_number": 38,
        "correct_answer": "A",
        "category_group": "醫學（四）",
        "category": "皮膚科",
        "category_confidence": "high",
        "key_point": "紅癬的致病菌與Wood's lamp螢光診斷特徵。",
        "explanation": "紅癬是由於微細棒狀桿菌感染所致，屬於「細菌」感染，而非黴菌（真菌）感染，故選項A敘述錯誤。此菌會產生紫質，因此在伍氏燈照射下會呈現特徵性的「珊瑚紅」螢光。紅癬好發於潮濕摩擦部位（如腋下、胯下、趾縫），皮損呈紅褐色斑片並伴有輕微脫屑。",
        "flashcard_front": "紅癬 (erythrasma) / 微細棒狀桿菌 / 細菌 vs. 黴菌 / Wood's lamp 螢光",
        "flashcard_back": "紅癬為棒狀桿菌（細菌）感染而非黴菌；在伍氏燈（Wood's lamp）下呈現珊瑚紅螢光。",
        "flashcard_summary": "紅癬特徵 -> 紅癬由棒狀桿菌（細菌）引起，Wood's lamp下呈珊瑚紅螢光，好發於潮濕摺皺處。"
    },
    {
        "question_id": "111-1_medicine-4_039",
        "question_number": 39,
        "correct_answer": "A",
        "category_group": "醫學（四）",
        "category": "皮膚科",
        "category_confidence": "high",
        "key_point": "常見良性皮膚腫瘤（表皮囊腫/粉瘤）的臨床外觀診斷。",
        "explanation": "臨床上軀幹或四肢最常見的良性皮膚囊腫為表皮囊腫（俗稱粉瘤），外觀常呈現中央有一小孔（punctum）的皮下結節，壓迫時可能擠出具異味的角質物。皮脂腺囊腫多為多發性；黏液囊腫常見於口腔黏膜或手指關節處；纖毛囊腫則較小且少見。",
        "flashcard_front": "大腿內側皮膚腫瘤 / 中央小孔 (punctum) / 良性囊腫 / 表皮囊腫 (epidermal cyst)",
        "flashcard_back": "表皮囊腫為最常見的良性皮下囊腫，典型外觀為中央帶黑孔之結節，內含異味角質。",
        "flashcard_summary": "表皮囊腫特徵 -> 最常見的皮膚良性囊腫，呈中央有孔的結節，內含異味角質。"
    },
    {
        "question_id": "111-1_medicine-4_040",
        "question_number": 40,
        "correct_answer": "D",
        "category_group": "醫學（四）",
        "category": "皮膚科",
        "category_confidence": "high",
        "key_point": "Gardner症候群的臨床表徵（多發性表皮囊腫、大腸息肉、骨瘤及甲狀腺癌）關聯。",
        "explanation": "Gardner 症候群是家族性腺瘤性息肉病（FAP）的一種亞型，為體染色體顯性遺傳。其典型特徵包括多發性大腸腺瘤性息肉、骨瘤以及多發性軟組織腫瘤（以表皮囊腫最常見），並有較高的甲狀腺癌風險，故選D。Cowden症候群主要特徵為多發性缺陷瘤及乳癌/甲狀腺癌；Carney複合症表現為黏液瘤與斑狀色素沉著。",
        "flashcard_front": "多發性表皮囊腫 / 大腸息肉 / 甲狀腺癌 / Gardner 症候群",
        "flashcard_back": "Gardner 症候群特徵為多發性表皮囊腫、骨瘤及大腸息肉，屬體染色體顯性遺傳，癌症風險高。",
        "flashcard_summary": "Gardner症候群臨床特徵 -> 表現為多發性表皮囊腫、骨瘤及大腸腺瘤性息肉，易惡化為大腸癌。"
    },
    {
        "question_id": "111-1_medicine-4_041",
        "question_number": 41,
        "correct_answer": "C",
        "category_group": "醫學（四）",
        "category": "皮膚科",
        "category_confidence": "high",
        "key_point": "盤狀紅斑性狼瘡（DLE）的皮膚病理與直接免疫螢光（DIF）特徵。",
        "explanation": "盤狀紅斑性狼瘡（DLE）的典型病理特徵包括表皮萎縮、毛孔角質栓塞、基底細胞液樣變性、以及真皮層淋巴球浸潤。直接免疫螢光（DIF）檢查在表皮與真皮交界處可見IgG和補體的線性沉積（稱為Lupus band test陽性），結合頸部萎縮性脫屑皮損，最符合盤狀紅斑性狼瘡的診斷。",
        "flashcard_front": "頸部萎縮性脫屑皮損 / 表皮萎縮 / 基底細胞液樣變性 / DIF 交界處 IgG 線性沉積",
        "flashcard_back": "毛孔角栓與基底液樣變性，加 DIF 顯示表真交界處 IgG 線性沉積，為盤狀紅斑性狼瘡（DLE）特徵。",
        "flashcard_summary": "DLE病理特徵 -> 表皮萎縮、基底液樣變性與DIF在皮真交界見IgG沉積提示盤狀紅斑性狼瘡。"
    },
    {
        "question_id": "111-1_medicine-4_042",
        "question_number": 42,
        "correct_answer": "A",
        "category_group": "醫學（四）",
        "category": "皮膚科",
        "category_confidence": "high",
        "key_point": "脂漏性角化症的良性特徵與Leser-Trélat sign的臨床意義。",
        "explanation": "脂漏性角化症（俗稱老人斑）是一種完全良性的表皮增生疾病，並非原位癌（原位癌如 Bowen's disease 具有惡性潛能），因此選項A敘述錯誤。它好發於老年人，日曬是常見誘因。若在短時間內突然出現大量伴有搔癢的脂漏性角化症病灶，稱為 Leser-Trélat sign，這被視為一種副腫瘤表徵，需注意是否合併胃癌等內臟惡性疾患。",
        "flashcard_front": "脂漏性角化症 / 良性 vs. 原位癌 / 突發大量病灶 (Leser-Trélat sign) / 胃癌關聯",
        "flashcard_back": "脂漏性角化症是良性表皮增生而非原位癌；突發大量病灶（Leser-Trélat sign）需注意合併胃癌等內臟腫瘤。",
        "flashcard_summary": "脂漏性角化症特徵 -> 屬於完全良性的表皮增生；突發大量病灶（Leser-Trélat sign）提示可能合併內臟癌症。"
    },
    {
        "question_id": "111-1_medicine-4_043",
        "question_number": 43,
        "correct_answer": "C",
        "category_group": "醫學（四）",
        "category": "皮膚科",
        "category_confidence": "high",
        "key_point": "Peutz-Jeghers症候群（PJS）的遺傳方式、息肉分布與惡性腫瘤風險。",
        "explanation": "Peutz-Jeghers症候群（PJS）是一種體染色體顯性遺傳疾病，特徵為皮膚黏膜黑色素斑點（常在幼年即出現在嘴唇及口腔黏膜）及胃腸道錯構瘤性息肉（多發生在小腸，而非大腸）。PJS患者一生中罹患胃腸道癌、乳癌、胰臟癌、生殖系統腫瘤及其他器官惡性腫瘤的風險顯著增高，故選項C敘述正確。",
        "flashcard_front": "嘴唇黑斑 / 胃腸道息肉 / Peutz-Jeghers 症候群 (PJS) / 遺傳方式 / 息肉部位",
        "flashcard_back": "PJS為顯性遺傳，嘴唇黑斑幼年出現，錯構瘤息肉好發於小腸而非大腸，且伴有高癌症風險。",
        "flashcard_summary": "Peutz-Jeghers症候群特徵 -> 顯性遺傳，幼年嘴唇現黑斑，錯構瘤息肉好發於小腸，癌症風險高。"
    },
    {
        "question_id": "111-1_medicine-4_044",
        "question_number": 44,
        "correct_answer": "B",
        "category_group": "醫學（四）",
        "category": "神經科",
        "category_confidence": "high",
        "key_point": "核間性眼肌麻痺（INO）的臨床表現與MLF病灶定位。",
        "explanation": "當病患看向左側時，右眼無法內收，且左眼外展時出現眼球震顫，而向右看及上下看均正常，這是典型的「核間性眼肌麻痺（INO）」。INO的病灶位於眼球無法內收那一側的內側縱向束（MLF）。在此題中，看向左邊時右眼無法內收，故病灶位於右側內側縱向束，答案為B。",
        "flashcard_front": "向左看右眼不能內收 / 左眼外展眼震 / 核間性眼肌麻痺 (INO) / 病灶定位",
        "flashcard_back": "INO的病灶位於無法內收眼同側的內側縱向束（MLF）；向左看時右眼無法內收，病灶在右側MLF。",
        "flashcard_summary": "INO定位診斷 -> 往病灶對側看時同側眼無法內收，對側眼外展且眼震，病灶在無法內收眼同側之MLF。"
    },
    {
        "question_id": "111-1_medicine-4_045",
        "question_number": 45,
        "correct_answer": "D",
        "category_group": "醫學（四）",
        "category": "神經科",
        "category_confidence": "high",
        "key_point": "超急性腦中風影像診斷首選序列與細胞毒性水腫的DWI表現。",
        "explanation": "在急性腦梗塞發生的數分鐘至數小時內，細胞缺氧形成細胞毒性水腫，限制了水分子的隨機擴散。擴散加權影像（DWI）能極其敏感地偵測到這種水分子擴散受限，在超急性期（發病數分鐘內）即呈現高訊號（亮點），因此敏感度最高。相較之下，T1、T2及FLAIR序列通常需要數小時甚至一天後才能顯現病變。",
        "flashcard_front": "急性腦中風 / 梗塞數分鐘後 / 細胞毒性水腫 / MRI 最敏感序列",
        "flashcard_back": "擴散加權影像（DWI）能在超急性腦梗塞發作數分鐘內，敏感地偵測到細胞毒性水腫所致的水分子擴散受限。",
        "flashcard_summary": "超急性腦中風影像 -> 擴散加權影像（DWI）是偵測超急性腦梗塞細胞毒性水腫最敏感的序列。"
    }
]

batch_004_items = [
    {
        "question_id": "111-1_medicine-4_046",
        "question_number": 46,
        "correct_answer": "C",
        "category_group": "醫學（四）",
        "category": "神經科",
        "category_confidence": "high",
        "key_point": "腦中風血管定位（中大腦動脈 MCA 梗塞）與失語症及對側偏癱的對應關係。",
        "explanation": "患者有心律不整與高血壓史，突發右側肢體無力和無法言語，提示優勢大腦半球（左側）受損。中大腦動脈（MCA）供應大腦外側部，包括運動皮質及語言區。左側MCA的大面積梗塞會導致右側偏癱、失語症，且隨著腦水腫加重可能導致意識昏迷，因此最可能發生問題的血管為左側中大腦動脈。",
        "flashcard_front": "突發右側無力 / 無法言語 (失語症) / 左側優勢半球受損 / 中大腦動脈 (MCA)",
        "flashcard_back": "對側偏癱伴隨失語症（優勢半球受損），提示中大腦動脈（MCA）梗塞，病灶多在左側MCA。",
        "flashcard_summary": "MCA梗塞定位 -> 右側無力伴隨失語症提示左側中大腦動脈（MCA）阻塞。"
    },
    {
        "question_id": "111-1_medicine-4_047",
        "question_number": 47,
        "correct_answer": "D",
        "category_group": "醫學（四）",
        "category": "神經科",
        "category_confidence": "high",
        "key_point": "癲癇與痙攣性暈厥、熱痙攣的臨床鑑別診斷原則。",
        "explanation": "暈厥是由於腦部短暫灌流不足引起，常可伴隨短暫的肌肉強直，但其本質非大腦異常放電，故不可據此確診為癲癇，選項D最恰當。大約有 30-50% 的癲癇患者其腦部 MRI 是正常的，故 MRI 正常不能排除癲癇。腦電圖出現棘波僅代表有癲癇樣放電傾向，若無臨床發作史，不能單憑 EEG 確診。",
        "flashcard_front": "癲癇鑑別診斷 / 痙攣性暈厥 (convulsive syncope) / MRI正常 / EEG 棘波意義",
        "flashcard_back": "暈厥伴隨短暫強直（痙攣性暈厥）不可確診為癲癇；MRI正常不能排除癲癇；單憑EEG棘波無發作不能確診。",
        "flashcard_summary": "癲癇與暈厥鑑別 -> 痙攣性暈厥伴隨短暫強直不可確診為癲癇，且MRI正常亦不能排除癲癇。"
    },
    {
        "question_id": "111-1_medicine-4_048",
        "question_number": 48,
        "correct_answer": "C",
        "category_group": "醫學（四）",
        "category": "神經科",
        "category_confidence": "high",
        "key_point": "偏頭痛急性期與預防性治療的藥物選擇與禁忌。",
        "explanation": "用於預防偏頭痛的常用抗癲癇藥物為 Topiramate 與 Valproate，而 Carbamazepine 主要用於治療三叉神經痛，並不常用於預防偏頭痛，故選項C最不恰當。Triptan 類藥物具有收縮血管作用，故缺血性心臟病或嚴重高血壓等心血管疾病患者禁用。偏頭痛若發作頻繁，應考慮啟動預防性治療。",
        "flashcard_front": "偏頭痛預防用藥 / 抗癲癇藥 / Carbamazepine 角色 / Triptan 禁忌",
        "flashcard_back": "偏頭痛預防用 Topiramate 與 Valproate，不用 Carbamazepine；Triptan 類心血管病患禁用。",
        "flashcard_summary": "偏頭痛用藥原則 -> 預防用藥可選Topiramate，不選Carbamazepine；Triptan類心血管疾病者禁用。"
    },
    {
        "question_id": "111-1_medicine-4_049",
        "question_number": 49,
        "correct_answer": "B",
        "category_group": "醫學（四）",
        "category": "神經科",
        "category_confidence": "high",
        "key_point": "青少年肌躍性癲癇（JME）的用藥禁忌與首選藥物。",
        "explanation": "青少年肌躍性癲癇（JME）屬於全面性癲癇。對於全面性癲癇，應避免使用主要針對局部性發作且可能加重肌躍性發作的鈉離子通道阻斷劑，如 Phenytoin，因為這些藥物會顯著惡化 JME 的症狀，故選B。首選藥物通常是廣效性的 Valproate，或者 Levetiracetam、Topiramate 等。",
        "flashcard_front": "青少年肌躍性癲癇 (JME) / 全面性癲癇 / 禁忌抗癲癇藥 / 鈉通道阻斷劑",
        "flashcard_back": "JME（全面性癲癇）應避免使用 Phenytoin 等鈉通道阻斷劑，以免加重肌躍發作；首選為 Valproate。",
        "flashcard_summary": "JME用藥禁忌 -> 青少年肌躍性癲癇（JME）禁用 Phenytoin 等局部性抗癲癇藥，首選為 Valproate。"
    },
    {
        "question_id": "111-1_medicine-4_050",
        "question_number": 50,
        "correct_answer": "C",
        "category_group": "醫學（四）",
        "category": "神經科",
        "category_confidence": "high",
        "key_point": "一氧化碳中毒引發巴金森症候群的解剖病灶位置。",
        "explanation": "一氧化碳（CO）中毒會引起嚴重的細胞缺氧，而大腦基底核中的蒼白球對缺氧特別敏感，是最容易發生雙側壞死與病變的部位。當雙側蒼白球受損後，患者常會繼發出現巴金森症候群的症狀。典型的原發性巴金森氏症則是中腦黑質多巴胺細胞退化。",
        "flashcard_front": "一氧化碳 (CO) 中毒 / 巴金森症候群 / 基底核缺氧病灶 / 雙側蒼白球壞死",
        "flashcard_back": "一氧化碳中毒引起的巴金森症候群，其主要壞死病灶位於基底核的雙側蒼白球（Globus pallidus）。",
        "flashcard_summary": "一氧化碳中毒病灶 -> 一氧化碳中毒引發的巴金森症候群，其典型病灶位於基底核的蒼白球。"
    },
    {
        "question_id": "111-1_medicine-4_051",
        "question_number": 51,
        "correct_answer": "B",
        "category_group": "醫學（四）",
        "category": "神經科",
        "category_confidence": "high",
        "key_point": "原發性巴金森氏病早期與晚期症狀的鑑別診斷。",
        "explanation": "凍僵步態（Freezing of gait）通常是原發性巴金森氏病晚期才會出現的特徵，在發病兩年內最不可能出現，故選B。原發性巴金森氏病的特徵是早期症狀通常呈不對稱性，其顫抖主要為靜止性顫抖（做動作時減輕，動腦或緊張時加重）。",
        "flashcard_front": "巴金森氏病 / 早期症狀 vs 晚期症狀 / 凍僵步態 (freezing of gait) / 靜止性顫抖",
        "flashcard_back": "凍僵步態是巴金森氏病晚期表現，早期罕見；早期多以不對稱之靜止性顫抖為特徵。",
        "flashcard_summary": "巴金森氏病早期症狀 -> 早期以不對稱靜止性顫抖為主，凍僵步態通常在病程晚期才出現。"
    },
    {
        "question_id": "111-1_medicine-4_052",
        "question_number": 52,
        "correct_answer": "A",
        "category_group": "醫學（四）",
        "category": "神經科",
        "category_confidence": "high",
        "key_point": "阿茲海默症的生物標記與影像診斷特徵（CSF數值與PET/MRI表現）。",
        "explanation": "阿茲海默症（AD）的病理特徵是類澱粉蛋白在腦部大量沉積形成斑塊。因此，患者腦脊髓液中的類澱粉蛋白 β-42 會因為大量沉積在腦中而降低而非增加，故選項A錯誤。海馬迴萎縮、類澱粉正子造影陽性，以及 FDG-PET 顯示雙側顳頂葉代謝活性下降，皆是AD支持性的典型檢查結果。",
        "flashcard_front": "阿茲海默症失智 / CSF 類澱粉蛋白 β-42 變化 / 海馬迴 MRI / FDG-PET 顳頂葉",
        "flashcard_back": "AD患者腦脊髓液中的 β-42 呈降低變化（因沉積於腦中）；MRI見海馬迴萎縮，FDG-PET見顳頂葉代謝降低。",
        "flashcard_summary": "阿茲海默症生物標記 -> 腦脊髓液中 β-42 降低而非升高，且海馬迴萎縮及顳頂葉代謝降低支持診斷。"
    },
    {
        "question_id": "111-1_medicine-4_053",
        "question_number": 53,
        "correct_answer": "D",
        "category_group": "醫學（四）",
        "category": "神經科",
        "category_confidence": "high",
        "key_point": "週期性麻痺的離子通道病理生理學與預防藥物。",
        "explanation": "週期性麻痺是一組與骨骼肌離子通道異常相關的體染色體顯性遺傳疾病。低血鉀性週期性麻痺是其中最常見的類型。發作時主要影響肢體近端肌肉，通常不影響吞嚥與呼吸肌。對於反覆發作的患者，可以使用碳酸酐酶抑制劑如 Acetazolamide 來預防發作，故選D。",
        "flashcard_front": "週期性麻痺 / 反復發作肌肉無力 / 最常見血鉀異常 / 預防藥物",
        "flashcard_back": "低血鉀最常見；發作不常累及吞嚥呼吸；可用碳酸酐酶抑制劑（Acetazolamide）預防發作。",
        "flashcard_summary": "週期性麻痺特徵 -> 最常見為低血鉀型，發作時少累及呼吸肌，預防首選碳酸酐酶抑制劑。"
    },
    {
        "question_id": "111-1_medicine-4_054",
        "question_number": 54,
        "correct_answer": "D",
        "category_group": "醫學（四）",
        "category": "神經科",
        "category_confidence": "high",
        "key_point": "脊髓半切症候群（Brown-Séquard syndrome）的定位與感覺、運動交叉解剖特點。",
        "explanation": "患者表現為右側下肢無力（同側運動功能喪失），以及對側肚臍以下痛溫覺喪失（對側痛溫覺喪失）。這種同側運動無力、對側痛溫覺喪失的特徵，是脊髓半切症候群（Brown-Séquard syndrome）的典型表現。由於左側痛溫覺喪失自肚臍（T10）開始，病灶位於胸椎第十節（T10）以上的右側半脊髓損傷，故選D。",
        "flashcard_front": "同側運動無力 / 對側痛溫覺喪失 / 肚臍 (T10) 感覺平面 / 脊髓半切",
        "flashcard_back": "表現為同側運動障礙、對側痛溫覺喪失，診斷為脊髓半切（Brown-Séquard），病灶在無力同側且在感覺平面以上。",
        "flashcard_summary": "脊髓半切症候群定位 -> 同側偏癱伴隨對側痛溫覺喪失，提示病灶側之半脊髓損傷（Brown-Séquard症候群）。"
    },
    {
        "question_id": "111-1_medicine-4_055",
        "question_number": 55,
        "correct_answer": "A",
        "category_group": "醫學（四）",
        "category": "神經科",
        "category_confidence": "high",
        "key_point": "鉛中毒引起之運動神經軸突性病變與去髓鞘病變的鑑別。",
        "explanation": "鉛中毒在成人中主要且優先影響運動神經，引起軸突變性，臨床上常以垂腕或垂足等運動無力症狀為主要表現。相較之下，類澱粉神經病變以感覺和自主神經受累為主；格林–巴利症候群與單株免疫球蛋白增高血症引起的神經病變，其病理特徵主要為去髓鞘病變。",
        "flashcard_front": "成人鉛中毒 / 垂腕 (wrist drop) / 運動神經軸突病變 vs 去髓鞘",
        "flashcard_back": "鉛中毒主要首先影響運動神經，引起軸突性病變，常呈垂腕表現；GBS等以去髓鞘為主。",
        "flashcard_summary": "鉛中毒神經病變 -> 鉛中毒優先影響運動神經軸突，引起軸突性病變；GBS則以去髓鞘為主。"
    },
    {
        "question_id": "111-1_medicine-4_056",
        "question_number": 56,
        "correct_answer": "B",
        "category_group": "醫學（四）",
        "category": "神經科",
        "category_confidence": "high",
        "key_point": "上運動神經元（UMN）與下運動神經元（LMN）受損表徵的區別。",
        "explanation": "肌肉痙攣（即張力增高、折刀樣強直）以及腱反射增強、病理反射（如 Babinski sign 陽性），是上運動神經元（UMN）受損的特徵。下運動神經元（LMN）受損的表徵包括肌肉無力、肌肉萎縮、張力低下、肌纖維顫動（肌電圖可見）以及肉眼可見的肌束顫動。",
        "flashcard_front": "LMN 表徵 vs UMN 表徵 / 肌肉痙攣 (spasticity) / 肌肉萎縮 / 肌束顫動",
        "flashcard_back": "肌肉痙攣為UMN受損特徵；肌肉萎縮、肌束顫動及肌電圖纖維顫動為LMN受損特徵。",
        "flashcard_summary": "上下運動神經元表徵 -> 肌肉痙攣是上運動神經元受損特徵，下運動神經元受損則表現為萎縮與肌束顫動。"
    },
    {
        "question_id": "111-1_medicine-4_057",
        "question_number": 57,
        "correct_answer": "C",
        "category_group": "醫學（四）",
        "category": "神經科",
        "category_confidence": "high",
        "key_point": "軸突缺失與去髓鞘病變的病理特徵與糖尿病神經病變的混合病理。",
        "explanation": "糖尿病神經病變的病理機制包含微血管病變及代謝毒性，因此在病理上可以同時觀察到軸突缺失與去髓鞘的混合變化，故選項C最恰當。去髓鞘病變早期通常不會造成顯著的肌肉萎縮。大多數周邊神經病變以遠端無力為主。急性軸突缺失病變主要是軸突變性，不會在早期觀察到去髓鞘。",
        "flashcard_front": "周邊神經病變 / 早期肌肉萎縮 / 糖尿病病理改變 / 軸突缺失 vs 去髓鞘",
        "flashcard_back": "軸突缺失易致早期肌萎縮，去髓鞘不易；糖尿病神經病變可同時見到軸突缺失與去髓鞘病理。",
        "flashcard_summary": "神經病變病理比較 -> 糖尿病神經病變兼具軸突缺失與去髓鞘；軸突缺失會引起早期肌肉萎縮。"
    },
    {
        "question_id": "111-1_medicine-4_058",
        "question_number": 58,
        "correct_answer": "A",
        "category_group": "醫學（四）",
        "category": "神經科",
        "category_confidence": "high",
        "key_point": "視神經脊髓炎（NMOSD）的特異性自體抗體與其他神經自體抗體。",
        "explanation": "視神經脊髓炎（NMOSD）是一種中樞神經系統自體免疫去髓鞘疾病，其特異性最高的致病性抗體為針對星狀細胞水通道蛋白4的抗AQP4抗體，陽性率高達70-80%，故選A。而抗 GQ1b 抗體與 Miller Fisher 症候群相關；抗 MuSK 抗體與重症肌無力相關；抗 GAD 抗體與僵直人症候群相關。",
        "flashcard_front": "視神經脊髓炎 (NMOSD) / AQP4 抗體 / GQ1b 抗體 / MuSK 抗體",
        "flashcard_back": "抗 AQP4 抗體為 NMOSD 的高度特異性致病自體抗體；抗 GQ1b 則與 Miller Fisher 相關。",
        "flashcard_summary": "NMOSD特異性抗體 -> 視神經脊髓炎（NMOSD）與抗AQP4抗體關係最密切。"
    },
    {
        "question_id": "111-1_medicine-4_059",
        "question_number": 59,
        "correct_answer": "C",
        "category_group": "醫學（四）",
        "category": "精神科",
        "category_confidence": "high",
        "key_point": "思覺失調症（Schizophrenia）歷史定義的 4A 症狀與藥物機制。",
        "explanation": "Eugene Bleuler 提出的思覺失調症原發症狀包括聯想障礙、自閉傾向、情感淡漠及矛盾情緒，即著名的「4A 症狀」，故選項C正確。思覺失調症最主要的長期核心障礙通常是認知功能損害與陰性症狀，而非急性期的幻覺妄想。Haloperidol 是典型（第一代）抗精神病藥物。第二代非典型抗精神病藥物主要與 5-HT2A 受器機轉有關，而非 glutamate。",
        "flashcard_front": "思覺失調症 / Bleuler 原發症狀 (4A) / Haloperidol 藥物分代 / 二代機轉",
        "flashcard_back": "Bleuler 4A 為聯想障礙、自閉、情感淡漠及矛盾情緒；Haloperidol為第一代抗精神病藥。",
        "flashcard_summary": "思覺失調症特徵 -> Bleuler原發症狀為4A（聯想、自閉、情感、矛盾）；Haloperidol為第一代藥物。"
    },
    {
        "question_id": "111-1_medicine-4_060",
        "question_number": 60,
        "correct_answer": "C",
        "category_group": "醫學（四）",
        "category": "精神科",
        "category_confidence": "high",
        "key_point": "思考形式（過程）障礙與思考內容障礙（妄想）的定義區別。",
        "explanation": "思考障礙可分為思考形式（思考過程）障礙與思考內容障礙。思考形式障礙是指思想的組織、連結與表達過程出現障礙，如思考飛躍、語無倫次、新語症等。而妄想或超值觀念則屬於思考內容障礙，兩者在精神醫學定義上是不同的概念，故選項C敘述錯誤。",
        "flashcard_front": "思考形式障礙 / 思考內容障礙 / 新語症 (neologism) / 妄想與超值觀念",
        "flashcard_back": "思考形式障礙指思考組織表達障礙（如新語症）；思考內容障礙指思想內容異常（如妄想）。",
        "flashcard_summary": "思考障礙分類 -> 思考形式障礙為思考組織表達異常（如新語症），而思考內容障礙為妄想等。"
    }
]

batch_005_items = [
    {
        "question_id": "111-1_medicine-4_061",
        "question_number": 61,
        "correct_answer": "A",
        "category_group": "醫學（四）",
        "category": "精神科",
        "category_confidence": "high",
        "key_point": "雙相情緒障礙症的共病率與臨床發作病程特點。",
        "explanation": "雙相情緒障礙症（Bipolar disorder）患者合併物質使用障礙症的比例非常高，實際上比重鬱症更常合併物質使用障礙症，因此選項A敘述錯誤。雙相症在重度躁期或鬱期時，可能伴隨與情緒一致或不一致的精神病症狀（如幻聽或妄想）。由於每次發作皆會增加復發風險，因此長期維持期治療與預防復發至關重要。",
        "flashcard_front": "雙相情緒障礙症 / 物質使用障礙共病率 / 精神病症狀 / 復發風險",
        "flashcard_back": "雙相症合併物質濫用比例高於重鬱症；重度發作可有幻聽妄想；每次發作皆增加未來復發率。",
        "flashcard_summary": "雙相情緒障礙症特徵 -> 物質濫用共病率高於重鬱症，重度發作可有幻聽妄想，每次發作皆增加未來復發風險。"
    },
    {
        "question_id": "111-1_medicine-4_062",
        "question_number": 62,
        "correct_answer": "C",
        "category_group": "醫學（四）",
        "category": "精神科",
        "category_confidence": "high",
        "key_point": "Lamotrigine（維持期預防憂鬱）與急性躁症治療藥物的核准適應症差異。",
        "explanation": "Lamotrigine（樂命達）是一種情緒穩定劑，美國FDA僅核准其用於雙相情緒障礙症的「維持期治療」（特別是預防憂鬱期的復發），並非用於急性躁症的治療，故選C。而 Risperidone、Olanzapine 及 Aripiprazole 等第二代非典型抗精神病藥物，皆已被核准用於急性躁症的治療。",
        "flashcard_front": "雙相症躁期 / FDA核准藥物 / Lamotrigine 角色 / 預防憂鬱復發",
        "flashcard_back": "Lamotrigine僅核准用於維持期預防憂鬱復發，不可用於治療急性躁症；二代藥物可用於急性躁症。",
        "flashcard_summary": "雙相症用藥選擇 -> Lamotrigine僅用於維持期防憂鬱，不適用於急性躁症發作。"
    },
    {
        "question_id": "111-1_medicine-4_063",
        "question_number": 63,
        "correct_answer": "B",
        "category_group": "醫學（四）",
        "category": "精神科",
        "category_confidence": "high",
        "key_point": "人為障礙症（Factitious disorder）與詐病（Malingering）及其他軀體症狀障礙症的鑑別。",
        "explanation": "該個案故意製造生病症狀以獲得病患角色並住院，但不具有明顯的外部利益或物質目的，這符合「人為障礙症」（舊稱孟喬森症候群）的診斷。相較之下，詐病是為了明確的外部利益而裝病；疾病焦慮症是主觀焦慮但無故意製造症狀；轉化症是潛意識衝突轉化為神經學症狀。",
        "flashcard_front": "故意製造血尿血便 / 追求病患角色 (sick role) / 無外在利益 / 詐病 vs 人為障礙",
        "flashcard_back": "故意偽造症狀但無實質外在利益，僅為扮演病患角色，為人為障礙症；有實質外在利益為詐病。",
        "flashcard_summary": "人為障礙症與詐病 -> 故意製造症狀若無外在利益為人為障礙症，若有明確外在實質利益則為詐病。"
    },
    {
        "question_id": "111-1_medicine-4_064",
        "question_number": 64,
        "correct_answer": "B",
        "category_group": "醫學（四）",
        "category": "精神科",
        "category_confidence": "high",
        "key_point": "詐病（Malingering）的明確外部利益動機特徵。",
        "explanation": "個案裝病是出於逃避義務兵役等明確的外部動機與利益，這在精神醫學上被定義為「詐病」（Malingering），而非精神疾病，故選B。人為障礙症裝病是為了獲得病患角色與心理關注，無實質外部利益。轉化症則為潛意識引起的軀體症狀，患者並非故意假裝。",
        "flashcard_front": "逃避兵役 / 裝病 / 明確外部利益 / 詐病 vs 人為障礙症",
        "flashcard_back": "為逃兵役等實質外在利益而故意裝病，定義為詐病；無利益僅求病患角色者為人為障礙症。",
        "flashcard_summary": "詐病定義 -> 為了逃避兵役等明確外在利益而故意裝病，屬於詐病（Malingering）。"
    },
    {
        "question_id": "111-1_medicine-4_065",
        "question_number": 65,
        "correct_answer": "D",
        "category_group": "醫學（四）",
        "category": "精神科",
        "category_confidence": "high",
        "key_point": "轉化症（功能性神經症狀障礙症）的臨床症狀與常見表現。",
        "explanation": "轉化症（功能性神經症狀障礙症）常見的臨床表徵包括運動功能障礙（如癱瘓、肢體無力）和感覺功能障礙（如失明、失聰），故選項D正確。假性發作與真實癲癇在臨床上有高達30%以上的共病率，不易簡單區分。La belle indifférence（對症狀漠不關心）雖然經典，但僅出現在部分患者中，已不再是診斷的主要特徵。",
        "flashcard_front": "轉化症 / 運動與感覺功能異常 / 癱瘓 / 假性發作共病 / La belle indifférence 診斷價值",
        "flashcard_back": "癱瘓與肢體無力為最常見症狀；假性發作與真實癲癇常共病；對症狀淡漠特異性低，非主特徵。",
        "flashcard_summary": "轉化症特徵 -> 癱瘓為最常見症狀之一，假性發作常與癲癇共病，對症狀漠不關心特異性低非主要診斷依據。"
    },
    {
        "question_id": "111-1_medicine-4_066",
        "question_number": 66,
        "correct_answer": "D",
        "category_group": "醫學（四）",
        "category": "精神科",
        "category_confidence": "high",
        "key_point": "苯二氮平類（BZD）戒斷症狀與漸進減量原則。",
        "explanation": "長期使用苯二氮平類（BZDs）的患者，若突然立即停藥，會引發嚴重的戒斷症狀，包括嚴重反彈性失眠、焦慮、震顫，甚至癲癇發作及譫妄。因此，臨床上戒除BZD必須採取「漸進式減量」原則，不可立即停用所有藥物，故選項D錯誤。BZD使用應維持最低有效劑量，且老年人使用易增加跌倒及認知障礙風險。",
        "flashcard_front": "長期使用 BZD / 戒除停藥原則 / 立即停藥風險 / 戒斷症狀",
        "flashcard_back": "長期使用BZD應漸進式減量，立即停藥易引發癲癇與譫妄等嚴重戒斷反應；短效易成癮。",
        "flashcard_summary": "BZD停藥原則 -> 長期使用BZD需漸進式減量，立即停藥會引發嚴重戒斷症狀。"
    },
    {
        "question_id": "111-1_medicine-4_067",
        "question_number": 67,
        "correct_answer": "C",
        "category_group": "醫學（四）",
        "category": "精神科",
        "category_confidence": "high",
        "key_point": "DSM-5 六大認知領域中「執行功能」與「知覺動作功能」的範疇定義。",
        "explanation": "根據 DSM-5，執行功能的認知範疇包含規劃、決策、工作記憶、錯誤修正、抑制干擾以及認知彈性。而操作能力（Praxis）與知覺動作功能屬於另一個獨立的認知領域，不屬於執行功能的範疇，故選C。",
        "flashcard_front": "DSM-5 認知範疇 / 執行功能 / 工作記憶與決策 / 操作能力 (praxis)",
        "flashcard_back": "工作記憶、決策、錯誤修正屬「執行功能」；操作能力（praxis）屬「知覺動作功能」範疇。",
        "flashcard_summary": "執行功能範疇 -> 包含工作記憶、決策及錯誤修正，不包含屬於知覺動作功能的操作能力（praxis）。"
    },
    {
        "question_id": "111-1_medicine-4_068",
        "question_number": 68,
        "correct_answer": "D",
        "category_group": "醫學（四）",
        "category": "精神科",
        "category_confidence": "high",
        "key_point": "HIV感染不同階段的精神與神經系統併發症特徵。",
        "explanation": "HIV/AIDS相關的精神病症狀通常發生在感染的「晚期（免疫系統嚴重受損時）」，而非前、中期，故選項D敘述錯誤。被HIV感染初期約有30%的患者會出現類似流感的急性期症狀。AIDS相關失智症是疾病進展至晚期的表現，提示預後極差，出現失智症狀多在半年內死亡。",
        "flashcard_front": "愛滋病 (AIDS) / 精神病症狀階段 / 愛滋失智症預後 / 初期類流感",
        "flashcard_back": "AIDS精神病症狀及失智症多出現在晚期而非前中期；失智為預後差指標，常於半年內死亡。",
        "flashcard_summary": "愛滋病精神與神經症狀 -> 精神病症狀與失智症主要出現在HIV感染晚期，失智症為預後不良指標。"
    },
    {
        "question_id": "111-1_medicine-4_069",
        "question_number": 69,
        "correct_answer": "B",
        "category_group": "醫學（四）",
        "category": "精神科",
        "category_confidence": "high",
        "key_point": "美沙冬替代療法的藥理特性、劑型優勢與管制級別。",
        "explanation": "美沙冬（Methadone）是一種長效型鴉片受體促效劑，具有口服劑型，可使海洛因成癮者避免因靜脈注射共用針頭而感染HIV的風險，故選項B正確。美沙冬本身仍是強效鴉片類物質，會導致生理與心理依賴。在台灣，美沙冬屬於第二級管制藥品。其半衰期長，藥效可維持24小時以上，每天僅需口服一次即可。",
        "flashcard_front": "美沙冬 (Methadone) / 海洛因替代治療 / 劑型優點 / 管制藥分級 / 半衰期",
        "flashcard_back": "為第二級管制藥；可口服降低共用針頭感染風險；半衰期長，每日口服一次即可；具依賴成癮性。",
        "flashcard_summary": "美沙冬替代療法 -> 美沙冬為二級管制藥，口服能降低注射針頭感染風險，半衰期長每日僅需服用一次。"
    },
    {
        "question_id": "111-1_medicine-4_070",
        "question_number": 70,
        "correct_answer": "C",
        "category_group": "醫學（四）",
        "category": "精神科",
        "category_confidence": "high",
        "key_point": "酒精戒斷症狀、對睡眠結構的影響與我國酒駕法定標準。",
        "explanation": "酒精戒斷是由於中樞神經系統失去酒精的抑制作用而產生過度興奮的狀態。因此，戒斷初期常見的症狀包括失眠、焦慮、手抖、出汗，而非嗜睡，故選項C錯誤。我國酒駕罰責標準確為吐氣酒精濃度 0.15 mg/L。酒精會破壞睡眠結構，顯著降低深層睡眠（第四期）。",
        "flashcard_front": "酒精戒斷症狀 / 嗜睡 vs. 失眠手抖 / 酒精對深層睡眠 / 酒駕法定標準",
        "flashcard_back": "酒精戒斷初期呈失眠、手抖等自律神經亢進症狀而非嗜睡；酒精會減少深層睡眠時間；酒駕為 0.15 mg/L。",
        "flashcard_summary": "酒精戒斷與睡眠 -> 酒精戒斷初期表現為失眠與手抖而非嗜睡，酒精會縮短深層睡眠時間。"
    },
    {
        "question_id": "111-1_medicine-4_071",
        "question_number": 71,
        "correct_answer": "C",
        "category_group": "醫學（四）",
        "category": "精神科",
        "category_confidence": "high",
        "key_point": "社交焦慮症（Social Anxiety Disorder）的臨床診斷、藥物與心理治療原則。",
        "explanation": "小明在公開演講或社交情境下出現極度恐懼與自律神經亢進症狀，甚至採取逃避行為，符合「社交焦慮症」的診斷。認知行為治療（CBT）被廣泛實證研究證實對社交焦慮症具有卓越的療效，故選項C正確。第一線治療藥物為選擇性血清素回收抑制劑（SSRI），而非抗精神病藥。較早發病與合併憂鬱症皆為預後不良的指標。",
        "flashcard_front": "怕上台演說 / 逃避翹課 / 社交焦慮症 / 第一線藥物 / 心理治療",
        "flashcard_back": "符合社交焦慮症；CBT心理治療被證實有效；第一線用藥為SSRI而非抗精神病藥。",
        "flashcard_summary": "社交焦慮症診斷與治療 -> 怕上台且逃避為社交焦慮症，第一線治療為SSRI與認知行為治療（CBT）。"
    },
    {
        "question_id": "111-1_medicine-4_072",
        "question_number": 72,
        "correct_answer": "A",
        "category_group": "醫學（四）",
        "category": "精神科",
        "category_confidence": "high",
        "key_point": "成人 ADHD 的藥物療效與不同核心症狀隨年齡演變的趨勢。",
        "explanation": "許多成人 ADHD 患者在接受藥物（如 Methylphenidate）治療後，其注意力集中度和日常執行功能皆有顯著改善，因此「成人用藥治療效果不佳」的說法是錯誤的，故選A。ADHD 首選藥物包括 Methylphenidate。隨年齡增長進入成年期，過動症狀通常會隨發育成熟而有較明顯的改善，但注意力缺失可能持續存在。",
        "flashcard_front": "成人 ADHD / 藥物療效 / 首選藥物 / 過動症狀隨年齡變化",
        "flashcard_back": "成人ADHD用藥仍具顯著療效；Methylphenidate為首選藥物；成人期過動比注意力不集中改善更明顯。",
        "flashcard_summary": "ADHD藥物與預後 -> 藥物治療對成人ADHD依然高度有效，且過動症狀在成人期比注意力不集中改善更明顯。"
    },
    {
        "question_id": "111-1_medicine-4_073",
        "question_number": 73,
        "correct_answer": "D",
        "category_group": "醫學（四）",
        "category": "精神科",
        "category_confidence": "high",
        "key_point": "自殺/自傷行為的風險評估與分級處置原則。",
        "explanation": "自殺與自傷評估應根據其危險程度進行分級管理，並非所有陳述自殺意念者皆須立即住院。對於斷續存有自殺意念且自傷方式危險性較低（如非致命性割腕）的患者，最合適的處置為門診追蹤搭配心理治療，故選項D最合適。若患者憂鬱嚴重且缺乏社會支持，其自殺風險高，不可僅門診或社工治療，多需住院評估。",
        "flashcard_front": "自殺意念 / 割腕自傷 / 住院指徵 / 自殺風險評估與處置",
        "flashcard_back": "低致命自傷且意念斷續者可門診與心理治療；嚴重憂鬱無望且缺乏支持者需強制住院評估。",
        "flashcard_summary": "自殺風險處置 -> 自殺意念與自傷需依風險評估，斷續意念且低致命自傷可採門診與心理治療。"
    },
    {
        "question_id": "111-1_medicine-4_074",
        "question_number": 74,
        "correct_answer": "D",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "早產兒生長質出血（GMH）的磁振造影T2低訊號（血鐵質沉積）影像特徵。",
        "explanation": "極低體重早產兒（如20週出生）因腦室旁的生長質血管極為脆弱，極易發生生長質出血/腦室內出血。出血後的血鐵質沉積在腦室壁上，在MRI的T2加權影像上會呈現特徵性的低訊號表現，同時出血可導致繼發性腦室擴大，故選D。CMV感染通常表現為腦室周圍鈣化；結節硬化症表現為室管膜下結節，但在T2上常呈高訊號。",
        "flashcard_front": "20週早產兒 / 腦室擴大 / MRI T2 腦室壁低訊號 / 生長質出血 (GMH) / 血鐵質沉積",
        "flashcard_back": "早產兒生長質出血後，血鐵質沉積於腦室壁，於T2加權影像呈現特徵性低訊號線條。",
        "flashcard_summary": "早產兒生長質出血 -> 早產兒生長質出血後，血鐵質沉積在腦室壁，於T2加權影像呈低訊號。"
    },
    {
        "question_id": "111-1_medicine-4_075",
        "question_number": 75,
        "correct_answer": "A",
        "category_group": "醫學（四）",
        "category": "小兒科",
        "category_confidence": "high",
        "key_point": "腹部腫瘤影像定位與肝臟解剖分節判定。",
        "explanation": "根據肝臟分葉的解剖學知識，肝外側以鐮狀韌帶及左肝靜脈為界。腫瘤若位於左側最外緣、鐮狀韌帶的左側，則屬於「肝臟左外節（Segment II/III）」，故答案選A。",
        "flashcard_front": "5歲男童 / 腹部腫瘤 / 肝臟解剖定位 / 左外節 / Segment II/III",
        "flashcard_back": "依據鐮狀韌帶及血管定位，位於最左側外緣之肝臟病灶屬於左外節（Segment II/III）。",
        "flashcard_summary": "肝臟腫瘤定位 -> 依據鐮狀韌帶等解剖地標判定，位於左側最外緣的肝臟腫瘤屬於左外節。"
    }
]

# Write batches to reports/gemini_outputs
batches = [
    ("111-1_medicine-4_batch-001", batch_001_items),
    ("111-1_medicine-4_batch-002", batch_002_items),
    ("111-1_medicine-4_batch-003", batch_003_items),
    ("111-1_medicine-4_batch-004", batch_004_items),
    ("111-1_medicine-4_batch-005", batch_005_items)
]

for batch_id, items in batches:
    output_data = {
        "dataset_id": "111-1_medicine-4",
        "batch_id": batch_id,
        "items": items
    }
    output_path = f"reports/gemini_outputs/{batch_id}.json"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(output_data, f, ensure_ascii=False, indent=2)
    print(f"Successfully generated: {output_path}")

print("All batch output files written.")
