# -*- coding: utf-8 -*-
import json

batch_data = {
    "dataset_id": "108-2_medicine-2",
    "batch_id": "108-2_medicine-2_batch-006",
    "items": [
        {
            "question_id": "108-2_medicine-2_076",
            "question_number": 76,
            "correct_answer": "D",
            "category_group": "醫學（二）",
            "category": "病理學",
            "category_confidence": "high",
            "key_point": "識別骨化性肌炎中的組織病理學適應性變化類型。",
            "explanation": "骨化性肌炎是指受傷的肌肉或其他軟組織內出現了骨組織，這是纖維結締組織轉化為骨組織的過程，屬於間葉組織的化生（metaplasia）。異生為上皮異常增生且有惡變傾向；增生是細胞數目增多；萎縮是細胞或器官體積縮小。",
            "flashcard_front": "骨化性肌炎 / 軟組織內出現骨頭組織 / 化生、異生、增生 / 病理適應",
            "flashcard_back": "骨化性肌炎中軟組織轉化為骨組織，屬於間葉組織的化生（metaplasia）。",
            "flashcard_summary": "骨化性肌炎病理變化 -> 軟組織內出現骨組織，屬於組織的「化生（metaplasia）」。"
        },
        {
            "question_id": "108-2_medicine-2_077",
            "question_number": 77,
            "correct_answer": "A",
            "category_group": "醫學（二）",
            "category": "病理學",
            "category_confidence": "high",
            "key_point": "識別漿細胞內免疫球蛋白堆積所形成的包涵體名稱。",
            "explanation": "Russell bodies 是漿細胞內因內質網擴張且堆積大量新合成之免疫球蛋白所形成的嗜酸性（粉紅色）圓形包涵體。Amyloid 為澱粉樣蛋白，呈細胞外沉積；Mallory-Denk bodies 呈現在酒精性肝炎的肝細胞內，由中間絲組成；psammoma bodies 為沙粒體，呈同心圓鈣化。",
            "flashcard_front": "漿細胞 (plasma cell) / 堆積大量免疫球蛋白 / 嗜酸性粉紅色物質 / Russell body",
            "flashcard_back": "漿細胞內免疫球蛋白過度堆積所形成的嗜酸性胞質內物質稱為 Russell bodies；Mallory-Denk body則常見於酒精性肝病。",
            "flashcard_summary": "漿細胞免疫球蛋白堆積物 -> 漿細胞內堆積大量免疫球蛋白所形成的粉紅色小體稱為 Russell body。"
        },
        {
            "question_id": "108-2_medicine-2_078",
            "question_number": 78,
            "correct_answer": "B",
            "category_group": "醫學（二）",
            "category": "病理學",
            "category_confidence": "high",
            "key_point": "理解服用沙賓活疫苗致癱瘓性脊髓灰質炎的高風險免疫缺陷病。",
            "explanation": "沙賓疫苗（Sabin vaccine）為口服減毒活疫苗，由於主要引起腸道及體液免疫，若患者罹患 Bruton 氏病（性聯丙種免疫球蛋白缺乏血症），則因缺乏體液免疫而無法有效清除病毒，使其有極高風險發生逆轉突變而導致癱瘓性脊髓灰質炎。狄喬治氏症為 T 細胞缺陷；慢性肉芽腫疾病為吞噬細胞功能缺陷；威斯科特-奧爾德里奇症為複合性缺陷。",
            "flashcard_front": "沙賓活疫苗 / 口服減毒 / 癱瘓性脊髓灰質炎風險 / Bruton氏病 / 免疫缺陷",
            "flashcard_back": "Bruton 氏病（體液免疫缺陷）患者口服沙賓減毒活疫苗後，易因無法清除病毒而引致癱瘓性脊髓灰質炎。",
            "flashcard_summary": "沙賓疫苗與Bruton氏病 -> Bruton氏病患者使用口服沙賓活疫苗，有高風險引起癱瘓性脊髓灰質炎。"
        },
        {
            "question_id": "108-2_medicine-2_079",
            "question_number": 79,
            "correct_answer": "D",
            "category_group": "醫學（二）",
            "category": "病理學",
            "category_confidence": "high",
            "key_point": "識別與自體抗體（autoantibody）直接相關的疾病。",
            "explanation": "尋常型天皰瘡是由針對 desmoglein-3 的自體抗體引起，導致表皮細胞間黏附喪失；惡性貧血是由針對胃壁細胞或內在因子的自體抗體引起，阻礙維生素 B12 吸收。多發性結節性動脈炎（PAN）主要是與免疫複合物沉積引起的血管炎有關，非單純自體抗體介導。",
            "flashcard_front": "自體抗體 / 尋常型天皰瘡 / 多發性結節性動脈炎 / 惡性貧血 / 機轉判定",
            "flashcard_back": "尋常型天皰瘡與惡性貧血是由自體抗體介導的疾病；多發性結節性動脈炎主要與免疫複合物沉積有關。",
            "flashcard_summary": "自體抗體媒介疾病 -> 尋常型天皰瘡與惡性貧血之致病機轉主要與自體抗體產生有關。"
        },
        {
            "question_id": "108-2_medicine-2_080",
            "question_number": 80,
            "correct_answer": "D",
            "category_group": "醫學（二）",
            "category": "病理學",
            "category_confidence": "high",
            "key_point": "掌握肺癌合併高血鈣（paraneoplastic syndrome）之最常見病理類型。",
            "explanation": "肺鱗狀細胞癌（Squamous cell carcinoma）常會分泌副甲狀腺素相關胜肽（PTHrP），導致副腫瘤症候群之高血鈣症。小細胞癌常分泌 ACTH 或 ADH；腺癌則較少與高血鈣相關；多形性癌亦非常見病因。",
            "flashcard_front": "肺癌 / 高血鈣 (hypercalcemia) / PTHrP / 鱗狀細胞癌、小細胞癌 / 副腫瘤症候群",
            "flashcard_back": "肺癌患者呈現高血鈣，病理切片最可能為鱗狀細胞癌，因其常分泌 PTHrP；小細胞癌常分泌 ADH/ACTH。",
            "flashcard_summary": "肺癌與高血鈣 -> 肺癌合併高血鈣，其病理切片最可能是分泌 PTHrP 的鱗狀細胞癌。"
        },
        {
            "question_id": "108-2_medicine-2_081",
            "question_number": 81,
            "correct_answer": "B",
            "category_group": "醫學（二）",
            "category": "病理學",
            "category_confidence": "high",
            "key_point": "記憶與 Li-Fraumeni 症候群關係最密切的抑癌基因變異。",
            "explanation": "Li-Fraumeni 症候群是一種罕見的體染色體顯性遺傳癌症易感綜合徵，由抑癌基因 TP53 的生殖細胞（germline）突變所致。RB 變異與視網膜母細胞瘤及骨肉瘤相關；WT-1 與 Wilms 瘤相關；BRCA-1/2 與遺傳性乳癌及卵巢癌相關。",
            "flashcard_front": "Li-Fraumeni 症候群 / 癌症易感性 / 抑癌基因 / TP53、RB",
            "flashcard_back": "Li-Fraumeni 症候群是由 TP53 基因的生殖細胞突變所致，患者極易罹患多種癌症；RB則與視網膜母細胞瘤相關。",
            "flashcard_summary": "Li-Fraumeni基因突變 -> Li-Fraumeni 症候群與 TP53 抑癌基因的變異關係最高。"
        },
        {
            "question_id": "108-2_medicine-2_082",
            "question_number": 82,
            "correct_answer": "C",
            "category_group": "醫學（二）",
            "category": "病理學",
            "category_confidence": "high",
            "key_point": "掌握與吸菸密切相關且早期戒菸可緩解的血管炎。",
            "explanation": "血栓閉塞性血管炎（Buerger's disease，又稱 thromboangiitis obliterans）幾乎僅發生於重度吸菸者，主要累及中、小動靜脈，早期戒菸是唯一能有效阻止病變惡化、避免截肢的手段。Churg-Strauss 症候群與氣喘及嗜伊紅性球增多相關；結節性多動脈炎與 B 肝相關；Henoch-Schönlein 紫斑症常見於兒童且與 IgA 沉積有關。",
            "flashcard_front": "血管炎 / 吸菸密切相關 / 戒菸可緩解 / Buerger's disease / 血栓閉塞性",
            "flashcard_back": "血栓閉塞性血管炎（Buerger's disease）與吸菸密切相關，疾病早期戒菸是緩解惡化的關鍵。",
            "flashcard_summary": "吸菸相關血管炎 -> 血栓閉塞性血管炎（Buerger's disease）與吸菸密切相關，戒菸可緩解惡化。"
        },
        {
            "question_id": "108-2_medicine-2_083",
            "question_number": 83,
            "correct_answer": "D",
            "category_group": "醫學（二）",
            "category": "病理學",
            "category_confidence": "high",
            "key_point": "識別出生後必須依賴開放性動脈導管（PDA）以維持生命的先天性心臟病。",
            "explanation": "主動脈閉鎖（aortic atresia）屬於左心阻塞型病變，體循環灌流完全依賴動脈導管（PDA）提供由右向左的分流，一旦動脈導管關閉，將會導致心輸出量驟減而致命。心室中隔缺損、主動脈縮窄（成人型）與心房中隔缺損通常不需依賴 PDA 維持基本生命跡象。",
            "flashcard_front": "先天性心臟病 / 必須保持 PDA 開放 / 嬰兒出生致命 / 主動脈閉鎖 (aortic atresia)",
            "flashcard_back": "主動脈閉鎖因左心發育不全，體循環灌流完全依賴動脈導管（PDA），PDA關閉會迅速致命。",
            "flashcard_summary": "依賴PDA之先天性心臟病 -> 主動脈閉鎖必須保持開放的動脈導管以維持體循環灌流，否則嬰兒出生後極易致命。"
        },
        {
            "question_id": "108-2_medicine-2_084",
            "question_number": 84,
            "correct_answer": "C",
            "category_group": "醫學（二）",
            "category": "病理學",
            "category_confidence": "high",
            "key_point": "掌握何杰金氏淋巴瘤（Hodgkin lymphoma）的病理與臨床特徵。",
            "explanation": "典型何杰金氏淋巴瘤中，具特徵性的 Reed-Sternberg（RS）巨細胞僅占整個腫瘤組織的 1-5% 左右，其餘多為非腫瘤性的反應性發炎細胞（如淋巴球、組織球）。何杰金氏淋巴瘤主要累及淋巴結且治癒率高，臨床分期比病理亞型更能決定預後。",
            "flashcard_front": "何杰金氏淋巴瘤 / Reed-Sternberg 細胞比例 / 淋巴結病變 / 預後因素",
            "flashcard_back": "典型何杰金氏淋巴瘤中，RS腫瘤細胞僅占極小比例，多數是反應性發炎細胞；臨床分期對預後影響最大。",
            "flashcard_summary": "何杰金氏淋巴瘤特徵 -> 典型病灶中，Reed-Sternberg 腫瘤細胞僅占全體細胞的小部分。"
        },
        {
            "question_id": "108-2_medicine-2_085",
            "question_number": 85,
            "correct_answer": "A",
            "category_group": "醫學（二）",
            "category": "病理學",
            "category_confidence": "high",
            "key_point": "理解單株丙型球蛋白病變（monoclonal gammopathy）的定義與排除。",
            "explanation": "單株丙型球蛋白病變（monoclonal gammopathy）是由單一克隆的漿細胞異常增生所致（表現為 M 蛋白單峰），常見於多發性骨髓瘤、重鏈病或 MGUS，而「急性發炎」通常會引起多株性丙型球蛋白增生（polyclonal gammopathy）。其不一定有 Bence-Jones 蛋白尿，亦不一定伴隨漿細胞瘤或多發性骨髓瘤（如 MGUS 則無症狀）。",
            "flashcard_front": "單株丙型球蛋白病變 / Monoclonal gammopathy / 急性發炎 / Bence-Jones 蛋白 / MGUS",
            "flashcard_back": "單株丙型球蛋白病變源於單一克隆漿細胞增生，非急性發炎（急性發炎為多株性反應）。",
            "flashcard_summary": "單株丙型球蛋白病變 -> 單株丙型球蛋白病變常見於多發性骨髓瘤，而急性發炎病人通常呈多株性反應。"
        },
        {
            "question_id": "108-2_medicine-2_086",
            "question_number": 86,
            "correct_answer": "B",
            "category_group": "醫學（二）",
            "category": "病理學",
            "category_confidence": "high",
            "key_point": "掌握機化性肺炎（organizing pneumonia）的病理特徵與累及部位。",
            "explanation": "機化性肺炎（Organizing pneumonia，昔稱 COP/BOOP）的病理特徵是小支氣管（bronchioles）腔內和肺泡腔內有由纖維母細胞與結締組織構成的栓塞（Masson bodies），因此病變明顯累及小支氣管。此病通常不涉及嚴重的間質性纖維化或蜂巢狀肺變化。",
            "flashcard_front": "機化性肺炎 (Organizing pneumonia) / Masson body / 小支氣管病變 / 肺泡腔栓塞",
            "flashcard_back": "機化性肺炎病理上在小支氣管及肺泡腔內有 Masson body 栓塞，病變確實累及小支氣管。",
            "flashcard_summary": "機化性肺炎特徵 -> 機化性肺炎的纖維化栓塞（Masson body）累及小支氣管與肺泡腔。"
        },
        {
            "question_id": "108-2_medicine-2_087",
            "question_number": 87,
            "correct_answer": "A",
            "category_group": "醫學（二）",
            "category": "病理學",
            "category_confidence": "high",
            "key_point": "掌握急性氣管炎合併瀰漫性間質發炎之常見病原體。",
            "explanation": "病毒感染（如流感病毒、腺病毒、RSV 等）常引起氣管炎並伴隨瀰漫性肺間質發炎（間質性肺炎）。細菌性肺炎（如肺炎雙球菌、金黃色葡萄球菌）則多呈大葉性或小葉性，以肺泡腔內滲出液與化膿性發炎為主；黴菌感染亦非常見表現。",
            "flashcard_front": "急性氣管炎 / 瀰漫性肺間質發炎 / 間質性肺炎 / 病毒感染 / 細菌感染",
            "flashcard_back": "瀰漫性肺間質發炎（間質性肺炎）為病毒感染的特徵，細菌感染則主要引起肺泡內實變與化膿。",
            "flashcard_summary": "肺間質發炎病原 -> 急性氣管炎伴隨瀰漫性肺間質發炎，最常由病毒感染引起。"
        },
        {
            "question_id": "108-2_medicine-2_088",
            "question_number": 88,
            "correct_answer": "D",
            "category_group": "醫學（二）",
            "category": "病理學",
            "category_confidence": "high",
            "key_point": "掌握肺膨脹不全（atelectasis）的分類與病因排除。",
            "explanation": "肺膨脹不全（肺萎陷）主要可分為阻塞性、壓迫性與收縮性等類型。氣道阻塞會導致吸收性肺不全；肋膜腔積水或氣胸會壓迫肺實質導致壓迫性肺不全；肺泡表面張力素不足（如新生兒 RDS）會導致微小肺不全。急性肺炎主要特徵為肺泡實變與炎性細胞浸潤，最少見肺膨脹不全。",
            "flashcard_front": "肺膨脹不全 (Atelectasis) / 氣道阻塞 / 肋膜腔積水 / 表面張力素 / 急性肺炎",
            "flashcard_back": "氣道阻塞、積水與表面張力素不足皆可引發肺不全；急性肺炎主要呈實變病理，少見肺不全。",
            "flashcard_summary": "肺膨脹不全病因 -> 氣道阻塞與胸腔積水常引起肺不全，急性肺炎則少見肺不全。"
        },
        {
            "question_id": "108-2_medicine-2_089",
            "question_number": 89,
            "correct_answer": "C",
            "category_group": "醫學（二）",
            "category": "病理學",
            "category_confidence": "high",
            "key_point": "掌握酒精性肝炎的病理特徵與纖維化起始部位。",
            "explanation": "酒精性肝炎的纖維化通常是從「中心靜脈周圍（perivenular/pericentral, zone 3）」及竇旁開始，呈網狀的「雞籠網狀」纖維化，而非從門脈區（portal area）開始。典型酒精性肝炎可見脂肪變性、Mallory-Denk bodies 及嗜中性球浸潤；血液檢查常呈現 AST/ALT 比值大於 2；女性對酒精的易感性高於男性。",
            "flashcard_front": "酒精性肝炎 / 纖維化起始 / 門脈區與中心靜脈 / AST/ALT比值 / Mallory-Denk",
            "flashcard_back": "酒精性肝炎的纖維化始於中心靜脈周圍（zone 3），而非門脈區；病毒性肝炎才多始於門脈區。",
            "flashcard_summary": "酒精性肝炎纖維化 -> 酒精性肝炎的纖維化由中心靜脈周圍（zone 3）開始，而非 portal area。"
        },
        {
            "question_id": "108-2_medicine-2_090",
            "question_number": 90,
            "correct_answer": "C",
            "category_group": "醫學（二）",
            "category": "病理學",
            "category_confidence": "high",
            "key_point": "掌握良性肝細胞腺瘤（hepatocellular adenoma）的亞型分類與惡性化風險。",
            "explanation": "在所有肝細胞腺瘤（HCA）亞型中，beta-catenin 活化型腺瘤（beta-catenin activated HCA）具有「最高」的惡性化風險，常有高度進展至肝細胞癌（HCC）的傾向，故臨床上需切除。HNF1-alpha 失活型腺瘤與 MODY-3 相關且惡性風險極低；gp130 的突變常見於發炎型腺瘤。",
            "flashcard_front": "肝細胞腺瘤 (HCA) / beta-catenin 活化 / 惡性化風險 / HNF1-alpha / gp130",
            "flashcard_back": "beta-catenin 活化型肝細胞腺瘤具有最高的惡性化風險；HNF1-alpha型則惡性風險最低。",
            "flashcard_summary": "肝細胞腺瘤惡性風險 -> beta-catenin 活化型肝細胞腺瘤具有最高（而非最低）的惡性化風險。"
        }
    ]
}
