# -*- coding: utf-8 -*-
import json

batch_data = {
    "dataset_id": "108-2_medicine-2",
    "batch_id": "108-2_medicine-2_batch-005",
    "items": [
        {
            "question_id": "108-2_medicine-2_061",
            "question_number": 61,
            "correct_answer": "D",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "識別強效細胞色素 P450 (CYP450) 酵素誘導劑物種。",
            "explanation": "Rifampin 為強效的肝臟細胞色素 P450（如 CYP3A4）酵素誘導劑，會顯著加速其他經由肝臟代謝之藥物的清除速率，從而降低其血中濃度與藥效。Chloramphenicol、erythromycin 及 ketoconazole 皆為細胞色素 P450 的「抑制劑」，會減緩其他藥物之代謝，使藥效或毒性升高。",
            "flashcard_front": "藥物交互作用 / CYP450 酵素誘導劑 / 藥效降低 / Rifampin",
            "flashcard_back": "Rifampin 為強效的 CYP450 誘導劑，會加速其他藥物的肝臟代謝並降低其藥效。",
            "flashcard_summary": "強效CYP450誘導劑 -> Rifampin 可抗結核，亦為強效 CYP450 誘導劑，會降其它藥物藥效。"
        },
        {
            "question_id": "108-2_medicine-2_062",
            "question_number": 62,
            "correct_answer": "B",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "掌握 Acyclovir 的活化機制與病毒選擇性毒性特徵。",
            "explanation": "Acyclovir 是一種鳥嘌呤核苷類似物，其選擇性在於必須先被病毒特有的胸苷激酶（thymidine kinase, TK）磷酸化，隨後再被宿主激酶磷酸化成活性三磷酸形式，進而阻斷病毒 DNA 聚合酶。此特性使其僅在受疱疹病毒（HSV/VZV）感染的細胞中被活化，對正常細胞毒性極小。",
            "flashcard_front": "疱疹病毒治療 / Acyclovir / 胸苷激酶 (thymidine kinase) / 選擇性活化",
            "flashcard_back": "Acyclovir 需先被病毒的 thymidine kinase 磷酸化，才能干擾病毒複製，對感染細胞具高度選擇性。",
            "flashcard_summary": "Acyclovir 活化機制 -> Acyclovir 需先經由病毒的 thymidine kinase 磷酸化活化，對感染細胞具選擇性。"
        },
        {
            "question_id": "108-2_medicine-2_063",
            "question_number": 63,
            "correct_answer": "D",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "識別易引起繼發性骨質疏鬆症的長期使用藥物。",
            "explanation": "Prednisone 是一種糖皮質激素，長期慢性使用會抑制成骨細胞活性、減少腸胃道對鈣離子的吸收，並增加尿鈣排出，是引起藥物抗藥性或藥物誘導性骨質疏鬆症最常見的原因。Lovastatin（降血脂）、metformin（降血糖）及 propranolol（乙型阻斷劑）慢性使用皆無導致骨質疏鬆症之副作用。",
            "flashcard_front": "藥物性骨質疏鬆症 / 糖皮質激素 / Prednisone / 長期使用副作用",
            "flashcard_back": "長期慢性使用 prednisone 等糖皮質激素會抑制成骨細胞並妨礙鈣吸收，是藥物性骨質疏鬆的主要原因。",
            "flashcard_summary": "藥物引起骨質疏鬆 -> 長期慢性使用糖皮質激素（如 prednisone）會導致骨質疏鬆症。"
        },
        {
            "question_id": "108-2_medicine-2_064",
            "question_number": 64,
            "correct_answer": "D",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "掌握轉移性攝護腺癌的抗雄性素藥物治療。",
            "explanation": "Flutamide 是一種非類固醇類的雄性素受體拮抗劑（antiandrogen），常用於與 GnRH 促效劑合用，以阻斷雄性素對攝護腺癌細胞的刺激，非常適合用於有骨轉移的攝護腺癌。Anastrozole 為芳香環酶抑制劑，主要用於乳癌；desogestrel 為黃體素；oxandrolone 為合成雄性素，會刺激攝護腺癌生長。",
            "flashcard_front": "轉移性攝護腺癌 / 雄性素受體拮抗劑 / Flutamide / 骨病變與轉移",
            "flashcard_back": "Flutamide 為非類固醇類雄性素受體拮抗劑，適用於阻斷雄性素刺激以治療攝護腺癌。",
            "flashcard_summary": "攝護腺癌藥物治療 -> Flutamide 為雄性素受體拮抗劑，常用於治療轉移性攝護腺癌。"
        },
        {
            "question_id": "108-2_medicine-2_065",
            "question_number": 65,
            "correct_answer": "B",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "選擇適用於隅角開放型青光眼的 beta-1 選擇性阻斷劑藥物。",
            "explanation": "Betaxolol 為選擇性 beta-1 腎上腺素受體阻斷劑，局部滴眼可藉由減少睫狀體產生房水來降低眼壓，適用於隅角開放型青光眼。Atropine 及 tropicamide 為抗膽鹼藥，會引起散瞳並使房水排出受阻，禁用於青光眼；phentolamine 為 alpha 受體阻斷劑，不常用於此處。",
            "flashcard_front": "隅角開放型青光眼 / 房水生成減少 / beta-1 阻斷劑 / Betaxolol",
            "flashcard_back": "Betaxolol 為選擇性 beta-1 拮抗劑，可減少房水生成以治療青光眼；抗膽鹼藥如 atropine 會散瞳，禁用於青光眼。",
            "flashcard_summary": "青光眼用藥選擇 -> Betaxolol 為選擇性 beta-1 拮抗劑，可減少房水生成以治療隅角開放型青光眼。"
        },
        {
            "question_id": "108-2_medicine-2_066",
            "question_number": 66,
            "correct_answer": "B",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "記憶阿斯匹靈與兒童雷氏症候群（Reye syndrome）的關聯。",
            "explanation": "兒童在感染流感或水痘等病毒時，若使用阿斯匹靈（Aspirin）退燒，極易引發雷氏症候群（Reye syndrome），其臨床特徵為急性腦病變與肝臟脂肪變性。因此，對於兒童的病毒感染性發熱，禁用 aspirin，應選用 acetaminophen 等較安全的退燒藥。",
            "flashcard_front": "病毒感染退燒 / 雷氏症候群 (Reye syndrome) / 兒童禁用藥 / Aspirin",
            "flashcard_back": "兒童在病毒感染發燒時使用 aspirin，可能引發致死性雷氏症候群（急性腦病變與肝臟脂肪變性）。",
            "flashcard_summary": "兒童退燒與雷氏症候群 -> 兒童感染病毒發燒時禁用 aspirin，以防引發雷氏症候群。"
        },
        {
            "question_id": "108-2_medicine-2_067",
            "question_number": 67,
            "correct_answer": "B",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "掌握抗帕金森氏症藥物 Rasagiline 的作用機轉與分類。",
            "explanation": "Rasagiline 是一種不可逆的選擇性單胺氧化酶 B（MAO-B）抑制劑，能有效減少黑質紋狀體系統內多巴胺的降解。Carbidopa 是周邊 DOPA 脫羧酶抑制劑；pramipexole 是多巴胺受體促效劑；benztropine 為中樞性抗膽鹼藥，用於調整多巴胺與乙醯膽鹼的平衡。",
            "flashcard_front": "抗帕金森氏症藥物 / MAO-B 抑制劑 / Rasagiline / 多巴胺降解",
            "flashcard_back": "Rasagiline 為選擇性 MAO-B 抑制劑，可抑制多巴胺在腦中的代謝分解；carbidopa 則是周邊 DOPA 脫羧酶抑制劑。",
            "flashcard_summary": "帕金森氏症藥物機轉 -> Rasagiline 藉由抑制 MAO-B 減少多巴胺的代謝。"
        },
        {
            "question_id": "108-2_medicine-2_068",
            "question_number": 68,
            "correct_answer": "B",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "理解乙醇治療甲醇中毒的競爭性抑制與解毒機制。",
            "explanation": "乙醇（酒精）對醇去氫酶（alcohol dehydrogenase, ADH）的親和力顯著高於甲醇。當給予乙醇時，它會與甲醇競爭 ADH，從而有效抑制甲醇代謝成具有高度毒性的甲醛和甲酸，使得未代謝的甲醇能以原形安全地從腎臟與呼吸道排出。",
            "flashcard_front": "甲醇中毒 / 解毒藥物 / 醇去氫酶 (ADH) / 乙醇 / 競爭抑制",
            "flashcard_back": "乙醇與甲醇競爭結合醇去氫酶（ADH），抑制甲醇轉化為有毒代謝物（甲酸），減輕中毒症狀。",
            "flashcard_summary": "乙醇治療甲醇中毒 -> 乙醇競爭性結合醇去氫酶，抑制甲醇代謝為有毒之甲醛與甲酸。"
        },
        {
            "question_id": "108-2_medicine-2_069",
            "question_number": 69,
            "correct_answer": "A",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "識別與排除鴉片類藥物（opioids）的藥理作用。",
            "explanation": "鴉片類藥物（如嗎啡、可待因）的主要藥理作用包括止痛、鎮咳、抑制腸胃蠕動引致便秘、興奮副交感神經使瞳孔縮小等。鴉片類藥物不具有抗痙攣（抗癲癇）作用，在高劑量下甚至可能因抑制 GABA 神經元而誘發痙攣。",
            "flashcard_front": "鴉片類藥物 (Opioids) / 藥理作用與副作用 / 止咳、便秘、縮瞳 / 抗痙攣",
            "flashcard_back": "鴉片類藥物可止痛、止咳、引起便秘與縮瞳，但無抗痙攣作用，過量甚至可能引發痙攣。",
            "flashcard_summary": "鴉片類藥物作用 -> 鴉片類藥物會引起鎮咳、便秘與縮瞳，但無抗痙攣作用。"
        },
        {
            "question_id": "108-2_medicine-2_070",
            "question_number": 70,
            "correct_answer": "D",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "掌握急性無機汞鹽中毒的螯合劑治療選擇與排除。",
            "explanation": "治療急性無機汞鹽中毒的有效螯合劑包括 unithiol（DMPS）、dimercaprol（BAL，二巰基丙醇）以及 succimer（DMSA）。D-dimethylcysteine 即 Penicillamine（青黴胺），主要用於治療銅中毒（威爾森氏症）或慢性重金屬中毒，但在急性無機汞鹽中毒中，因其增加腎臟負擔且效果不佳，非首選藥物且可能有害。",
            "flashcard_front": "急性無機汞鹽中毒 / 螯合解毒劑 / Dimercaprol、Succimer / Penicillamine",
            "flashcard_back": "急性無機汞鹽中毒首選 unithiol、dimercaprol 或 succimer，而 D-dimethylcysteine (penicillamine) 則不適用於此急性情況。",
            "flashcard_summary": "無機汞中毒治療 -> 急性無機汞中毒禁用 D-dimethylcysteine，應使用 dimercaprol 或 succimer 治療。"
        },
        {
            "question_id": "108-2_medicine-2_071",
            "question_number": 71,
            "correct_answer": "C",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "識別抑制 VEGFR 的多靶點酪氨酸激酶抑制劑（TKI）。",
            "explanation": "Sunitinib 是一種小分子的多靶點酪氨酸激酶抑制劑（TKI），能抑制血管內皮生長因子受體（VEGFR-1, -2, -3）的活化，從而抑制腫瘤血管新生與癌細胞轉移。Cetuximab 與 panitumumab 是針對 EGFR 的單株抗體；erlotinib 是針對 EGFR 的小分子抑制劑。",
            "flashcard_front": "抑制 VEGFR / 多靶點小分子藥物 / 阻斷血管新生 / Sunitinib",
            "flashcard_back": "Sunitinib 可抑制血管內皮生長因子受體（VEGFR）以阻斷血管新生；erlotinib 則是針對 EGFR 的小分子抑制劑。",
            "flashcard_summary": "抑制VEGFR藥物 -> Sunitinib 藉由阻斷 VEGFR 活化以抑制腫瘤血管新生。"
        },
        {
            "question_id": "108-2_medicine-2_072",
            "question_number": 72,
            "correct_answer": "C",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "掌握 Plerixafor 的作用機轉與造血幹細胞動員原理。",
            "explanation": "Plerixafor 是一種趨化因子受體 CXCR4 的拮抗劑。它能特異性結合 CXCR4，阻斷其與基質細胞衍生因子-1（SDF-1）的結合，從而使骨髓中的造血幹細胞與骨髓基質分離，釋放到周邊血液中，以利於造血幹細胞的收集與移植。",
            "flashcard_front": "造血幹細胞動員 / 多發性骨髓瘤 / CXCR4 拮抗劑 / Plerixafor",
            "flashcard_back": "Plerixafor 藉由拮抗 CXCR4，阻斷其與 SDF-1 的結合，促使造血幹細胞自骨髓動員至周邊血。",
            "flashcard_summary": "Plerixafor 機轉 -> 拮抗 CXCR4 受體，促使造血幹細胞自骨髓動員至周邊血。"
        },
        {
            "question_id": "108-2_medicine-2_073",
            "question_number": 73,
            "correct_answer": "A",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "掌握針對 PD-L1 靶點的免疫檢查點抑制劑單株抗體。",
            "explanation": "Atezolizumab 是一種人源化單株抗體，能特異性結合腫瘤細胞表面的 PD-L1，阻斷其與 T 細胞表面 PD-1 的結合，從而解除腫瘤對 T 細胞的免疫抑制，活化 T 細胞以攻擊癌細胞。Rituximab 針對 CD20；panitumumab 針對 EGFR；ramucirumab 針對 VEGFR2。",
            "flashcard_front": "免疫檢查點抑制劑 / 單株抗體 / 結合 PD-L1 / Atezolizumab",
            "flashcard_back": "Atezolizumab 阻斷腫瘤細胞上的 PD-L1 與 T 細胞的 PD-1 結合，恢復 T 細胞殺傷癌細胞的能力。",
            "flashcard_summary": "PD-L1單株抗體 -> Atezolizumab 阻斷 PD-L1 與 PD-1 結合以活化 T 細胞。"
        },
        {
            "question_id": "108-2_medicine-2_074",
            "question_number": 74,
            "correct_answer": "C",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "掌握反義寡核苷酸藥物 Mipomersen 的抑制標的。",
            "explanation": "Mipomersen 是一種反義寡核苷酸藥物，能特異性結合編碼載脂蛋白 B-100（ApoB-100）的 mRNA，引發其降解，從而阻斷 ApoB-100 蛋白的轉譯。這能有效減少極低密度脂蛋白（VLDL）及低密度脂蛋白（LDL）的合成，用於治療同型性家族性高膽固醇血症。",
            "flashcard_front": "反義寡核苷酸 / 家族性高膽固醇血症 / 抑制 ApoB-100 / Mipomersen",
            "flashcard_back": "Mipomersen 特異性抑制 ApoB-100 的合成，進而減少 VLDL 與 LDL 的生成，達到降血脂效果。",
            "flashcard_summary": "Mipomersen 標的 -> 阻斷 ApoB-100 的 mRNA 轉譯以減少 VLDL 與 LDL 合成。"
        },
        {
            "question_id": "108-2_medicine-2_075",
            "question_number": 75,
            "correct_answer": "C",
            "category_group": "醫學（二）",
            "category": "藥理學",
            "category_confidence": "high",
            "key_point": "掌握降血脂藥 Ezetimibe 的小腸作用標的。",
            "explanation": "Ezetimibe 的作用標的為小腸絨毛細胞表面的 Niemann-Pick C1-Like 1（NPC1L1）轉運蛋白，藉由特異性阻斷此轉運體，以減少腸道對飲食中及膽汁中膽固醇的吸收。HMG-CoA reductase 為 statins 的作用標的；MTP 則是 lomitapide 的標的。",
            "flashcard_front": "降血脂藥 / 抑制小腸吸收膽固醇 / NPC1L1 轉運蛋白 / Ezetimibe",
            "flashcard_back": "Ezetimibe 藉由抑制小腸上皮細胞的 NPC1L1 轉運蛋白，減少膽固醇的吸收以降低 LDL-C。",
            "flashcard_summary": "Ezetimibe 作用標的 -> 抑制小腸的 NPC1L1 轉運蛋白以阻斷膽固醇吸收。"
        }
    ]
}
