# -*- coding: utf-8 -*-
import json

batch_data = {
    "dataset_id": "108-2_medicine-4",
    "batch_id": "108-2_medicine-4_batch-001",
    "items": [
        {
            "question_id": "108-2_medicine-4_001",
            "question_number": 1,
            "correct_answer": "A",
            "category_group": "醫學（四）",
            "category": "小兒科",
            "category_confidence": "high",
            "key_point": "掌握新生兒毒性紅斑（Erythema toxicum）的臨床病程與特徵。",
            "explanation": "毒性紅斑是新生兒非常常見的良性皮疹，通常在出生後 24 至 72 小時內於軀幹及四肢出現紅色丘疹、水泡或小膿疱，並不侵犯手掌與腳掌，在一週後無治療情況下即可自行消退。鮭魚斑為血管斑塊；先天性梅毒會伴隨其他系統性畸形或嚴重的掌蹠脫皮皮損。",
            "flashcard_front": "3天大新生兒 / 軀幹手腳紅疹丘疹 / 手掌腳掌排除 / 一週後自癒 / 診斷",
            "flashcard_back": "符合新生兒毒性紅斑（Erythema toxicum neonatorum）之特徵，此為良性自癒性皮疹。",
            "flashcard_summary": "新生兒毒性紅斑 -> 新生兒出生數日內軀幹手腳之紅疹且一週內自行消失，診斷為毒性紅斑。"
        },
        {
            "question_id": "108-2_medicine-4_002",
            "question_number": 2,
            "correct_answer": "D",
            "category_group": "醫學（四）",
            "category": "小兒科",
            "category_confidence": "high",
            "key_point": "掌握嬰幼兒砂眼披衣菌肺炎的臨床與實驗室特徵。",
            "explanation": "嬰幼兒感染砂眼披衣菌（Chlamydia trachomatis）引起的肺炎，其特徵為血液中嗜伊紅白血球顯著增加（eosinophils > 400 cells/μL）。受感染母親之新生兒中僅有 10-20% 會發展成披衣菌肺炎；其肺炎多在出生後 2-12 週才發病；且與 RSV 相比，披衣菌肺炎較不易發燒或產生喘鳴音。",
            "flashcard_front": "嬰幼兒 / 砂眼披衣菌肺炎 / 發病時間 / 嗜伊紅白血球增加 / 臨床表現",
            "flashcard_back": "砂眼披衣菌肺炎患者通常不發燒、少有喘鳴，且血液中嗜伊紅白血球常顯著增加（> 400 cells/μL）。",
            "flashcard_summary": "披衣菌肺炎特徵 -> 嬰幼兒砂眼披衣菌肺炎通常不發燒，且常伴隨血液中嗜伊紅白血球增加。"
        },
        {
            "question_id": "108-2_medicine-4_003",
            "question_number": 3,
            "correct_answer": "D",
            "category_group": "醫學（四）",
            "category": "小兒科",
            "category_confidence": "high",
            "key_point": "理解猩紅熱的致病機轉與外毒素的關聯。",
            "explanation": "猩紅熱（Scarlet fever）是由 A 群鏈球菌（GAS）感染所致，其致病機轉是由於該菌產生的「紅斑毒素（Erythrogenic toxin）」，此毒素在分類上屬於「外毒素（Exotoxin）」，而非內毒素（Endotoxin）。其臨床上確實需與川崎氏症、病毒疹做鑑別診斷；皮疹具有粗糙的砂紙感，並伴隨草莓舌及脫屑。",
            "flashcard_front": "猩紅熱 (Scarlet fever) / 紅斑毒素 / 內毒素與外毒素 / A群鏈球菌 / 皮疹粗糙",
            "flashcard_back": "猩紅熱的致病機轉是由 A 群鏈球菌產生的「外毒素」（紅斑毒素）引起，而非內毒素。",
            "flashcard_summary": "猩紅熱毒性機轉 -> 猩紅熱的致病機制與 A 群鏈球菌產生的「外毒素」（紅斑毒素）有關。"
        },
        {
            "question_id": "108-2_medicine-4_004",
            "question_number": 4,
            "correct_answer": "B",
            "category_group": "醫學（四）",
            "category": "小兒科",
            "category_confidence": "high",
            "key_point": "掌握新生兒早期敗血症最常見的革蘭氏陽性致病菌。",
            "explanation": "新生兒早期敗血症（出生後 3 天內）最常見的致病菌為無乳鏈球菌（Streptococcus agalactiae，即 B 群鏈球菌 GBS），該菌為革蘭氏陽性球菌。產婦若未規則產檢且急產，容易使得新生兒因吸入陰道內定殖的 GBS 發生呼吸窘迫及敗血症。大腸桿菌雖也常見，但為革蘭氏陰性桿菌。",
            "flashcard_front": "未規則產檢 / 急產 / 新生兒敗血症 / 血液培養革蘭氏陽性球菌 / 致病菌",
            "flashcard_back": "最常引起未足月或急產新生兒早期敗血症的革蘭氏陽性球菌為 B 群鏈球菌 (Streptococcus agalactiae)。",
            "flashcard_summary": "新生兒早期敗血症致病菌 -> 未規則產檢急產新生兒之早期敗血症，最常見的革蘭氏陽性球菌為 B 群鏈球菌。"
        },
        {
            "question_id": "108-2_medicine-4_005",
            "question_number": 5,
            "correct_answer": "D",
            "category_group": "醫學（四）",
            "category": "小兒科",
            "category_confidence": "high",
            "key_point": "區分 DiGeorge 症候群的臨床表徵與電解質異常。",
            "explanation": "此男嬰表現出右手與下肢血壓顯著差異，高度疑似主動脈縮窄（CoA）或主動脈弓中斷（IAA），這常與 DiGeorge 症候群（22q11.2 缺失）合併出現。DiGeorge 症候群的典型表現包含胸腺發育不良、臉部異常、顎裂與副甲狀腺發育不全，後者會導致頑固性的「低血鈣症（Hypocalcemia）」，而非高血鈣。",
            "flashcard_front": "7天大 / 上下肢血壓差異 / DiGeorge 症候群 / 副甲狀腺發育不良 / 鈣離子異常",
            "flashcard_back": "DiGeorge 症候群因副甲狀腺發育不良，會引致「低血鈣症」，而非高血鈣症。",
            "flashcard_summary": "DiGeorge症候群電解質 -> DiGeorge 症候群常伴有先天左心阻塞，且因副甲狀腺發育不全引起低血鈣症。"
        },
        {
            "question_id": "108-2_medicine-4_006",
            "question_number": 6,
            "correct_answer": "A",
            "category_group": "醫學（四）",
            "category": "小兒科",
            "category_confidence": "high",
            "key_point": "掌握因膽色素結合酵素活性不足引起黃疸的疾病。",
            "explanation": "Gilbert 氏症（Gilbert disease）是由於 UGT1A1 基因突變，導致肝臟的膽色素結合酵素（glucuronyl transferase）活性不足（約正常人的 30%），因而造成間接型高膽色素血症。遺傳性球形紅血球症、G6PD 缺乏症與 ABO 血型不合則是藉由溶血產生過多膽紅素，非此酵素活性不良所致。",
            "flashcard_front": "新生兒黃疸 / 間接型膽紅素 / 膽色素結合酵素 (glucuronyl transferase) / 活性不良 / Gilbert氏症",
            "flashcard_back": "Gilbert 氏症與 Crigler-Najjar 症候群是因膽色素結合酵素（UGT）活性不足導致間接型高膽色素血症。",
            "flashcard_summary": "膽色素結合酵素與黃疸 -> 膽色素結合酵素活性不良引起的間接型高膽色素血症，常見診斷為 Gilbert 氏症。"
        },
        {
            "question_id": "108-2_medicine-4_007",
            "question_number": 7,
            "correct_answer": "A",
            "category_group": "醫學（四）",
            "category": "小兒科",
            "category_confidence": "high",
            "key_point": "區分新生兒臍膨出（omphalocele）與腹裂（gastroschisis）的病理構造。",
            "explanation": "臍膨出（Omphalocele）的特徵是腹壁缺損位於臍環處，脫出的臟器表面有由羊膜與腹膜構成的「薄膜包覆」，且臍帶直接連接於該薄膜囊的頂端。腹裂（Gastroschisis）通常位於臍帶旁（多在右側），且脫出腸道「無薄膜包覆」而直接裸露；臍疝氣則有完整的皮膚覆蓋。",
            "flashcard_front": "新生兒 / 內臟突出 / 臍帶相連 / 薄膜覆蓋 / 臍膨出與腹裂",
            "flashcard_back": "臟器突出且表面有「薄膜覆蓋包住」並與臍帶直接相連，診斷為臍膨出（omphalocele）；腹裂則無薄膜包覆。",
            "flashcard_summary": "臍膨出特徵 -> 臟器突出且有薄膜包覆並直接連接臍帶，最可能的診斷為臍膨出。"
        },
        {
            "question_id": "108-2_medicine-4_008",
            "question_number": 8,
            "correct_answer": "B",
            "category_group": "醫學（四）",
            "category": "小兒科",
            "category_confidence": "high",
            "key_point": "掌握新生兒暫時性呼吸過速（TTNB）的流行病學與病因。",
            "explanation": "新生兒暫時性呼吸過速（TTNB）是由於肺泡內液體清除延遲所致。由於剖腹產嬰兒未經過產道的物理擠壓，其發生 TTNB 的機率顯著「高於自然產嬰兒」，故 B 敘述（自然產較易發生）錯誤。大部分患兒的症狀會在 72 小時內緩解，少數嚴重者可能併發持續性肺高壓（PPHN）。",
            "flashcard_front": "新生兒 / 肺部液體吸收不全 / 暫時性呼吸過速 (TTNB) / 生產方式 / 自然產與剖腹產",
            "flashcard_back": "TTNB 常發生於未受產道擠壓的「剖腹產」嬰兒，其發生率顯著高於自然產嬰兒。",
            "flashcard_summary": "TTNB與生產方式 -> 新生兒暫時性呼吸過速（TTNB）較常發生於剖腹產嬰兒而非自然產嬰兒。"
        },
        {
            "question_id": "108-2_medicine-4_009",
            "question_number": 9,
            "correct_answer": "B",
            "category_group": "醫學（四）",
            "category": "小兒科",
            "category_confidence": "high",
            "key_point": "掌握繼發性膽囊水腫（Hydrops of gallbladder）的常見病因與排除。",
            "explanation": "膽囊水腫在兒童中多為急性全身發炎或感染反應的繼發性表現（如川崎氏症、鏈球菌咽喉炎、過敏性紫斑症等），其因局部淋巴結腫大壓迫膽囊管引起。多脾症（Polysplenia syndrome）屬於先天性臟器發育與異位畸形，通常不與急性或繼發性膽囊水腫有直接病理關聯。",
            "flashcard_front": "兒童 / 膽囊水腫 (Hydrops of gallbladder) / 川崎症 / 鏈球菌咽炎 / 多脾症 / HSP",
            "flashcard_back": "川崎症、鏈球菌感染及 HSP 易併發膽囊水腫；多脾症為先天性臟器發育畸形，最少合併膽囊水腫。",
            "flashcard_summary": "膽囊水腫病因 -> 川崎氏症與鏈球菌感染常引發繼發性膽囊水腫，而先天多脾症則極少合併此症。"
        },
        {
            "question_id": "108-2_medicine-4_010",
            "question_number": 10,
            "correct_answer": "D",
            "category_group": "醫學（四）",
            "category": "小兒科",
            "category_confidence": "high",
            "key_point": "理解新生兒首次胎便排出的正常生理時間限制限制。",
            "explanation": "不論是哺育母乳或配方奶，新生兒出生後正常的第一次胎便排出時間應在「24 小時內」。若延遲至 24 到 48 小時甚至更晚才排出，屬於異常生理現象，須高度警惕是否有腸道畸形或巨結腸症（Hirschsprung's disease）。母乳寶寶在 3 週大後便秘、黃疸持續到 2-3 個月等皆可能為正常生理變異。",
            "flashcard_front": "母乳哺育兒 / 第一次胎便排出 / 正常時間 / 24小時 / 延遲排出",
            "flashcard_back": "新生兒不論餵養方式，首次胎便排出的正常時間為出生後 24 小時內；延遲排出屬異常現象，須注意巨結腸症。",
            "flashcard_summary": "首次胎便排出時間 -> 新生兒出生後 24 小時內排出首次胎便為正常；延遲至 24-48 小時排出則非正常現象。"
        },
        {
            "question_id": "108-2_medicine-4_011",
            "question_number": 11,
            "correct_answer": "C",
            "category_group": "醫學（四）",
            "category": "小兒科",
            "category_confidence": "high",
            "key_point": "掌握威爾森氏症（Wilson disease）的銅沉積部位與特徵。",
            "explanation": "威爾森氏症（Wilson disease）中具特徵性的 K-F 環（Kayser-Fleischer ring）是由於銅離子沉積在眼睛的「角膜後彈性層（Descemet's membrane）」，而非視網膜（Retina）。該病為體染色體隱性遺傳；不明原因肝炎需考慮此診斷；多數患者血清攜銅蛋白（Ceruloplasmin）會降低。",
            "flashcard_front": "威爾森氏症 / Kayser-Fleischer ring / 銅離子沉積 / 角膜後彈性層 / 視網膜",
            "flashcard_back": "Kayser-Fleischer 環是由於銅沉積在眼睛的「角膜」而非視網膜；威爾森氏症為體染色體隱性遺傳。",
            "flashcard_summary": "威爾森氏症與KF環 -> K-F 環是由於銅離子沉積在角膜（而非視網膜），為威爾森氏症的典型特徵。"
        },
        {
            "question_id": "108-2_medicine-4_012",
            "question_number": 12,
            "correct_answer": "B",
            "category_group": "醫學（四）",
            "category": "小兒科",
            "category_confidence": "high",
            "key_point": "掌握 NSAIDs 引起兒童次發性消化性潰瘍的最常見部位。",
            "explanation": "兒童使用非類固醇抗發炎藥（NSAIDs）所引起的次發性消化性潰瘍，其最常發生的病變部位是「胃（stomach）」，而非十二指腸（duodenum）。NSAIDs 主要藉由抑制前列腺素合成削弱胃黏膜屏障；壓力性潰瘍多在事件 24 小時內發生；PPI 為出血期一線治療。",
            "flashcard_front": "兒童 / NSAIDs 藥物 / 次發性消化性潰瘍 / 常見部位 / 胃與十二指腸",
            "flashcard_back": "NSAIDs 引起的兒童次發性消化性潰瘍最常見於「胃」，而非十二指腸；胃黏膜屏障受損為主因。",
            "flashcard_summary": "NSAIDs消化性潰瘍部位 -> 兒童因 NSAIDs 引起的次發性消化性潰瘍，病變最常發生在胃。"
        },
        {
            "question_id": "108-2_medicine-4_013",
            "question_number": 13,
            "correct_answer": "C",
            "category_group": "醫學（四）",
            "category": "小兒科",
            "category_confidence": "high",
            "key_point": "掌握腎小管酸血症（RTA）的陰離子間隙（Anion Gap）類型類型。",
            "explanation": "腎小管酸血症（RTA）是由於腎臟碳酸氫根重吸收或氫離子排出障礙引起，但其血中陰離子間隙（Anion Gap）是正常的，屬於「正常陰離子間隙（高氯性）代謝性酸中毒」。因此，在「高陰離子間隙（High AG）」代謝性酸中毒中，RTA 最為罕見；而 DKA、乳酸中毒及乙二醇中毒皆為 High AG 酸中毒。",
            "flashcard_front": "高陰離子間隙 (High AG) / 代謝性酸中毒 / 腎小管酸血症 (RTA) / DKA、乳酸中毒",
            "flashcard_back": "腎小管酸血症（RTA）表現為「正常陰離子間隙」代謝性酸中毒；DKA與乳酸中毒則為高陰離子間隙型。",
            "flashcard_summary": "腎小管酸血症酸中毒類型 -> 腎小管酸血症（RTA）屬於正常陰離子間隙酸中毒，非高陰離子間隙型。"
        },
        {
            "question_id": "108-2_medicine-4_014",
            "question_number": 14,
            "correct_answer": "A",
            "category_group": "醫學（四）",
            "category": "小兒科",
            "category_confidence": "high",
            "key_point": "區分低血鉀的形成機轉：細胞內位移與全身性流失。",
            "explanation": "注射胰島素（Insulin）會促使鉀離子「移入細胞內」，導致血液中鉀離子濃度降低（低血鉀），但其全身總鉀量並無改變，因此與「鉀離子實質流失」最無關聯。而長期使用利尿劑（經腎流失）、腹瀉（經腸道流失）與腎小管酸血症（經腎流失）皆會造成人體內鉀離子的實質流失。",
            "flashcard_front": "低血鉀 (Hypokalemia) / 鉀離子流失 / 胰島素 (Insulin) / 利尿劑、腹瀉、RTA",
            "flashcard_back": "注射胰島素造成鉀離子「轉移至細胞內」而引起低血鉀，並非鉀離子的實質排出流失。",
            "flashcard_summary": "胰島素與低血鉀 -> 胰島素造成鉀離子轉移至細胞內引致低血鉀，並非引起人體鉀離子的流失。"
        },
        {
            "question_id": "108-2_medicine-4_015",
            "question_number": 15,
            "correct_answer": "D",
            "category_group": "醫學（四）",
            "category": "小兒科",
            "category_confidence": "high",
            "key_point": "掌握過敏性紫斑症腎炎（HSPN）的臨床表現與遠期預後預後。",
            "explanation": "兒童過敏性紫斑症腎炎（HSPN）患者在急性期若有嚴重的腎臟受累，其成年後發展為慢性腎臟病（CKD）及高血壓的機率會顯著大於無腎炎者，故 D 正確。HSPN 臨床表現如血尿常延遲數週出現，不與皮疹同時；其病理與 IgA 腎炎極度相似，主要靠有無關節、腸胃等全身症狀而非切片做臨床鑑別。",
            "flashcard_front": "過敏性紫斑症腎炎 (HSPN) / 血尿蛋白尿出現時間 / IgA 腎炎鑑別 / 遠期預後 / CKD",
            "flashcard_back": "急性期 HSPN 患兒在成年後有較高風險罹患慢性腎臟病（CKD）；其與 IgA 腎炎鑑別依賴臨床全身表現。",
            "flashcard_summary": "HSPN預後與鑑別 -> 急性期過敏性紫斑症腎炎患兒成年後易發生慢性腎臟病，其與 IgA 腎炎主要依據全身症狀區分。"
        }
    ]
}
