# -*- coding: utf-8 -*-
import os
import json

os.makedirs("reports/gemini_outputs", exist_ok=True)

batches_data = {}

# ==================== BATCH 003 ====================
batches_data["109-2_medicine-5_batch-003"] = {
    "dataset_id": "109-2_medicine-5",
    "batch_id": "109-2_medicine-5_batch-003",
    "items": [
        {
            "question_id": "109-2_medicine-5_031",
            "question_number": 31,
            "correct_answer": "B",
            "category_group": "醫學（五）",
            "category": "胸腔外科",
            "category_confidence": "high",
            "key_point": "肺部手術術前肺功能評估與阻塞性肺疾病指標。",
            "explanation": "阻塞性肺疾病（obstructive lung disease）患者由於呼氣受阻，其第一秒用力呼氣容積與用力肺活量比值（FEV1/FVC ratio）會下降，而非上升。其他選項中，FEV1小於60%預估值、一氧化碳擴散能力（DLCO）小於40%~50%，以及最大耗氧量（VO2 max）小於11~15 mL/kg/min，皆是增加肺部手術術後併發症與死亡率的重要危險指標。",
            "flashcard_front": "肺部手術術前評估 / 阻塞性肺病 / FEV1/FVC / DLCO / 術後併發症",
            "flashcard_back": "阻塞性肺病患者的 FEV1/FVC 比值會下降；FEV1 < 60%、DLCO < 40-50% 及 VO2 max < 11-15 則會增加手術風險。",
            "flashcard_summary": "肺部手術評估與FEV1/FVC -> 阻塞性肺病 FEV1/FVC 會下降，FEV1、DLCO 與 VO2 max 偏低皆會增加術後風險。"
        },
        {
            "question_id": "109-2_medicine-5_032",
            "question_number": 32,
            "correct_answer": "A",
            "category_group": "醫學（五）",
            "category": "外科概論",
            "category_confidence": "high",
            "key_point": "腹內壓力上升對人體器官系統的影響與分級。",
            "explanation": "異常的腹內壓力上升（intra-abdominal hypertension）不僅會減慢腹內器官血流並影響心臟回流，對呼吸器官的影響也極為明顯，會使橫膈膜上升進而限制肺部擴張。肥胖是導致慢性腹內壓上升的常見原因。腹內高壓依壓力大小分為四級，第1、2級通常採保守治療，第3、4級（大於20-25 mmHg）伴隨器官功能障礙時則易形成腹內腔室症候群，需要緊急手術減壓。",
            "flashcard_front": "腹內壓力上升 / 呼吸器官影響 / 肥胖 / 腹內高壓分級 / 腹內腔室症候群",
            "flashcard_back": "腹內壓上升會顯著壓迫橫膈限制呼吸；第3、4級腹內高壓（>25 mmHg）易引發腹內腔室症候群，需手術減壓。",
            "flashcard_summary": "腹內壓力與呼吸影響 -> 腹內壓上升會顯著限制呼吸，高於25 mmHg易引發腹內腔室症候群並需要手術減壓。"
        },
        {
            "question_id": "109-2_medicine-5_033",
            "question_number": 33,
            "correct_answer": "B",
            "category_group": "醫學（五）",
            "category": "一般外科",
            "category_confidence": "high",
            "key_point": "病態性肥胖合併第二型糖尿病與嚴重胃食道逆流的手術選擇。",
            "explanation": "對於BMI高達43 kg/m²且合併第二型糖尿病及重度胃食道逆流（LA Grade C）的病患，Roux-en-Y胃繞道手術（RYGB）是最適合的治療選擇。胃繞道手術不僅能顯著減重並改善糖尿病，還能降低胃酸逆流，是此類病患的黃金標準。相較之下，胃袖狀切除術可能加重逆流，而Nissen胃底摺疊術雖能治療逆流但對減重無效。",
            "flashcard_front": "病態性肥胖 / 第二型糖尿病 / 胃食道逆流 / 代謝減重手術 / Roux-en-Y胃繞道",
            "flashcard_back": "Roux-en-Y胃繞道手術是肥胖合併糖尿病與嚴重胃食道逆流患者的首選減重手術。",
            "flashcard_summary": "肥胖合併糖尿病與逆流手術 -> 首選 Roux-en-Y 胃繞道手術，可同時減重、治療糖尿病並有效改善嚴重胃食道逆流。"
        },
        {
            "question_id": "109-2_medicine-5_034",
            "question_number": 34,
            "correct_answer": "A",
            "category_group": "醫學（五）",
            "category": "一般外科",
            "category_confidence": "high",
            "key_point": "早期胃癌（Early Gastric Cancer）的臨床病理定義。",
            "explanation": "早期胃癌的定義是腫瘤侵犯僅限於黏膜層（mucosa）或黏膜下層（submucosa），因此侵犯至黏膜下層仍屬於早期胃癌。此定義與是否有淋巴結轉移無關。大約10%的早期胃癌病患在診斷時已出現淋巴結轉移，且約70%的早期胃癌細胞分化良好。",
            "flashcard_front": "早期胃癌 / 侵犯深度 / 黏膜與黏膜下層 / 淋巴結轉移 / 定義",
            "flashcard_back": "早期胃癌定義為病灶僅侵犯黏膜層或黏膜下層，不論有無淋巴結轉移皆算。",
            "flashcard_summary": "早期胃癌定義 -> 腫瘤侷限於黏膜或黏膜下層即為早期胃癌，與有無淋巴結轉移無關。"
        },
        {
            "question_id": "109-2_medicine-5_035",
            "question_number": 35,
            "correct_answer": "B",
            "category_group": "醫學（五）",
            "category": "一般外科",
            "category_confidence": "high",
            "key_point": "肝臟功能評估 Child-Pugh Score 的計算規則。",
            "explanation": "根據 Child-Pugh 評分標準，總膽紅素（Total Bilirubin）為 2.52 mg/dL（介於 2.0-3.0）得 2 分；血清白蛋白（Albumin）為 4.3 g/dL（>3.5）得 1 分；PT INR 為 1.12（<1.7）得 1 分；無腹水得 1 分；無肝性腦病變得 1 分。將各項分數加總（2 + 1 + 1 + 1 + 1），該患者的 Child-Pugh 總分為 6 分。",
            "flashcard_front": "Child-Pugh / 膽紅素 2.52 / 白蛋白 4.3 / INR 1.12 / 評分計算",
            "flashcard_back": "膽紅素2.52得2分，白蛋白、INR、無腹水及無腦病變各得1分，總分為6分（Class A）。",
            "flashcard_summary": "Child-Pugh評分計算 -> 本題患者評估得分為6分（2分膽紅素+4分其他項目），屬於肝功能 A 級。"
        },
        {
            "question_id": "109-2_medicine-5_036",
            "question_number": 36,
            "correct_answer": "C",
            "category_group": "醫學（五）",
            "category": "一般外科",
            "category_confidence": "high",
            "key_point": "細菌性肝膿瘍最常見的致病來源。",
            "explanation": "現今引發肝內細菌性膿瘍（pyogenic liver abscess）最常見的原因是膽道感染（biliary tract infection），如急性膽囊炎或膽管炎。過去最常見的原因是源自闌尾炎等門靜脈系統的感染，但隨著抗生素普及與早期診斷，目前已退居次要原因。上腸繫膜動脈阻塞與外傷引起的肝膿瘍則相對罕見。",
            "flashcard_front": "細菌性肝膿瘍 / 最常見原因 / 膽道感染 / 門靜脈途徑",
            "flashcard_back": "現代細菌性肝膿瘍最常見的原因是膽道感染；過去則以闌尾炎等門靜脈途徑多見。",
            "flashcard_summary": "細菌性肝膿瘍成因 -> 現代最常見原因為膽道感染，過去則以門靜脈感染（如闌尾炎）為主。"
        },
        {
            "question_id": "109-2_medicine-5_037",
            "question_number": 37,
            "correct_answer": "D",
            "category_group": "醫學（五）",
            "category": "一般外科",
            "category_confidence": "high",
            "key_point": "甲狀腺乳突癌合併遠端轉移的治療原則與預後。",
            "explanation": "對於甲狀腺乳突癌合併多處頸部淋巴結及肺部轉移的患者，治療首選為甲狀腺全切除手術，術後再給予放射性碘（I-131）清除殘餘腫瘤與轉移灶。甲狀腺乳突癌通常生長緩慢，即使發生肺部轉移，其預後仍然良好，十年的存活率相當高，並非一年內死亡。口服 methimazole 為抗甲狀腺藥物，無法抑制腫瘤生長，而化療在此類癌症中非首選。",
            "flashcard_front": "甲狀腺乳突癌 / 頸部淋巴結與肺轉移 / 治療首選 / 預後 / I-131",
            "flashcard_back": "首選治療為甲狀腺全切除合併術後放射性碘（I-131）治療；該癌預後良好，非全身化療或抗甲狀腺藥物。",
            "flashcard_summary": "甲狀腺乳突癌肺轉移治療 -> 採全切除加放射性碘（I-131）治療，即使有遠端轉移其長期預後通常仍良好。"
        },
        {
            "question_id": "109-2_medicine-5_038",
            "question_number": 38,
            "correct_answer": "D",
            "category_group": "醫學（五）",
            "category": "一般外科",
            "category_confidence": "high",
            "key_point": "續發性副甲狀腺功能亢進的手術切除適應症。",
            "explanation": "血液透析患者若出現因鈣鹽沉積引起的缺血性皮膚壞死（calciphylaxis），屬於嚴重的鈣磷代謝異常併發症，是副甲狀腺切除手術的絕對適應症。其他選項如鈣磷乘積 45 mg²/dL²（小於危險閾值 55-70）、副甲狀腺素（PTH）200 pg/mL（未達需手術的 >800 pg/mL），以及維生素D缺乏，通常先以內科藥物治療，並非手術指引之適應症。",
            "flashcard_front": "續發性副甲狀腺專屬 / 血液透析 / 手術適應症 / 鈣化防禦 / 鈣磷乘積 / PTH",
            "flashcard_back": "出現鈣化防禦（calciphylaxis，缺血性皮膚壞死）是手術切除的適應症；輕度PTH上升與鈣磷乘積則以藥物控制。",
            "flashcard_summary": "續發性副甲狀腺防禦 -> 缺血性皮膚壞死（calciphylaxis）是切除手術適應症，其餘輕度指標先以藥物治療。"
        },
        {
            "question_id": "109-2_medicine-5_039",
            "question_number": 39,
            "correct_answer": "C",
            "category_group": "醫學（五）",
            "category": "一般外科",
            "category_confidence": "high",
            "key_point": "原發性高醛固酮症的診斷與腎上腺靜脈取樣（AVS）適應症。",
            "explanation": "原發性高醛固酮症的診斷流程中，初步篩檢測醛固酮/腎素比例（ARR），確診可用生理食鹽水輸注試驗。為了區分單側腺瘤或雙側增生，對於大於35或40歲的患者，因其腎上腺意外瘤較常見，故建議常規接受腎上腺靜脈取樣（AVS）檢查；而小於35或40歲且影像學表現典型者則可直接手術，因此「40歲以下常規接受AVS」的敘述錯誤。術前有低血鉀者，切除分泌腺瘤後血鉀多能迅速恢復。",
            "flashcard_front": "原發性高醛固酮症 / ARR / 靜脈生理食鹽水試驗 / 腎上腺靜脈取樣 (AVS) / 年齡界線",
            "flashcard_back": "區分單雙側時，年齡大於35-40歲才需常規做 AVS 排除無功能瘤；年輕且影像典型者可直接手術。",
            "flashcard_summary": "AVS與原發性高醛固酮症 -> 年齡大於35-40歲者需做AVS區分單雙側，40歲以下典型患者則通常不需常規AVS。"
        },
        {
            "question_id": "109-2_medicine-5_040",
            "question_number": 40,
            "correct_answer": "A",
            "category_group": "醫學（五）",
            "category": "一般外科",
            "category_confidence": "high",
            "key_point": "侵襲性乳管癌（Infiltrating Ductal Carcinoma）的分類與治療。",
            "explanation": "侵襲性乳管癌（IDC）是最常見的乳癌類型，約占所有侵襲性乳癌的50%~70%或更高。未停經女性且荷爾盟受體陽性（ER/PR 90%）者，首選抗荷爾盟藥物為 tamoxifen，芳香環抑制劑（AI）則適用於停經後婦女。本例 HER-2 為 1+（陰性），不需要使用雙標靶治療。若腫瘤為 1.2 公分且無淋巴結與遠端轉移，其術後病理 TNM 分期應為 pT1cN0M0，而非 cT1b。",
            "flashcard_front": "侵襲性乳管癌 (IDC) / ER與PR陽性 / HER-2 1+ / 芳香環抑制劑 / 分期",
            "flashcard_back": "IDC是最常見乳癌（50%-70%）；未停經者首選 Tamoxifen；HER-2陰性不用標靶；1.2公分為T1c。",
            "flashcard_summary": "乳癌分類與治療原則 -> 侵襲性乳管癌最常見，未停經且荷爾盟陽性首選 Tamoxifen，HER-2 陰性不需標靶。"
        },
        {
            "question_id": "109-2_medicine-5_041",
            "question_number": 41,
            "correct_answer": "B",
            "category_group": "醫學（五）",
            "category": "一般外科",
            "category_confidence": "high",
            "key_point": "乳房保留手術與乳房全切除手術的療效比較。",
            "explanation": "臨床研究證實，乳房全切除手術與乳房保留手術加上術後放射線治療，兩者的長期存活率並無顯著差異。接受立即重建手術並不會降低存活率或增加患側局部復發率。乳房保留手術的腫瘤切除安全邊緣（margin）目前共識為「no ink on tumor」即可（不一定要大於 2 mm），且保留手術相對於全切除，同側乳房的局部復發率仍會略高。",
            "flashcard_front": "乳房保留手術 / 乳房全切除 / 長期存活率 / 立即重建 / 安全邊緣 (margin)",
            "flashcard_back": "乳房保留手術加放療與全切除的長期存活率無顯著差異；立即重建不影響存活與復發。",
            "flashcard_summary": "乳房保留與全切除比較 -> 保留手術加放療與全切除長期存活率相當，立即重建不影響預後與局部復發。"
        },
        {
            "question_id": "109-2_medicine-5_042",
            "question_number": 42,
            "correct_answer": "D",
            "category_group": "醫學（五）",
            "category": "小兒外科",
            "category_confidence": "high",
            "key_point": "膽道閉鎖（Biliary Atresia）診斷的黃金標準。",
            "explanation": "診斷新生兒膽道閉鎖的黃金標準是肝臟切片檢查（liver biopsy），其診斷準確率可達90%以上，病理特徵包括膽管增生、膽栓形成及門脈區纖維化。雖然腹部超音波（可見 triangular cord sign）與 HIDA 膽道核醫掃描是常用且重要的篩檢工具，但它們並非黃金標準。病毒血清學檢查主要用於排除其他原因引起的黃疸。",
            "flashcard_front": "新生兒黃疸 / 灰白便 / 膽道閉鎖 / 診斷黃金標準 / HIDA / 超音波",
            "flashcard_back": "肝臟切片檢查是診斷膽道閉鎖的黃金標準；超音波與 HIDA 掃描為重要篩檢工具。",
            "flashcard_summary": "膽道閉鎖黃金標準 -> 診斷膽道閉鎖的黃金標準為肝臟切片檢查，具極高準確度。"
        },
        {
            "question_id": "109-2_medicine-5_043",
            "question_number": 43,
            "correct_answer": "C",
            "category_group": "醫學（五）",
            "category": "小兒外科",
            "category_confidence": "high",
            "key_point": "嬰兒反覆泌尿道感染與水腎的影像學評估。",
            "explanation": "對於有反覆泌尿道感染（UTI）且超音波顯示輕微水腎的嬰兒，最優先進行的檢查是排尿膀胱尿道造影（VCUG），以排除膀胱輸尿管逆流（VUR）的可能。VUR是導致兒童反覆尿路感染的最常見先天異常。電腦斷層、核磁共振及靜脈腎盂造影（IVP）並非診斷VUR的首選或最優先工具。",
            "flashcard_front": "嬰兒 / 反覆泌尿道感染 / 輕微水腎 / 最優先檢查 / 膀胱輸尿管逆流 (VUR)",
            "flashcard_back": "最優先進行排尿膀胱尿道造影（VCUG）以診斷是否合併膀胱輸尿管逆流。",
            "flashcard_summary": "反覆尿路感染評估 -> 嬰兒反覆泌尿道感染與水腎，應優先接受排尿膀胱尿道造影（VCUG）檢測。"
        },
        {
            "question_id": "109-2_medicine-5_044",
            "question_number": 44,
            "correct_answer": "",
            "category_group": "醫學（五）",
            "category": "小兒外科",
            "category_confidence": "high",
            "key_point": "先天性食道閉鎖與氣管食道瘻管的分類與臨床特徵。",
            "explanation": "官方此題答案更正為一律給分（答案欄位保留為空字串）。正常情況下，先天性食道閉鎖患者有高達 90% 會伴隨氣管食道瘻管（TEF），但仍有少數類型（如 Gross Type A）為單純食道閉鎖而無瘻管，因此「必定伴隨」之敘述有爭議。臨床上，此疾病以 Gross Type C 最為常見，且多伴隨其他器官異常（如 VACTERL 症候群），應做全身檢查，無其他緊急狀況下應儘速手術治療。",
            "flashcard_front": "先天性食道閉鎖 / 氣管食道瘻管 / Gross分類 / VACTERL聯合畸形",
            "flashcard_back": "官方此題無正解。食道閉鎖最常見為 Gross Type C；少數類型如 Type A 並無伴隨瘻管。",
            "flashcard_summary": "食道閉鎖與瘻管特徵 -> 官方無公布答案。食道閉鎖最常見為 Gross Type C，多伴隨其他系統異常。"
        },
        {
            "question_id": "109-2_medicine-5_045",
            "question_number": 45,
            "correct_answer": "B",
            "category_group": "醫學（五）",
            "category": "小兒外科",
            "category_confidence": "high",
            "key_point": "臍膨出與腹裂畸形的臨床與解剖特徵鑑別。",
            "explanation": "臍膨出（omphalocele）由於是中線腹壁缺損，突出的臟器表面會有一層由羊膜和腹膜構成的包膜保護；而腹裂畸形（gastroschisis）則沒有包膜。臨床上，臍膨出的病人極常伴隨腸道以外的其他系統畸形（高達50%-70%），而腹裂畸形則較少伴隨腸道外畸形，但因臟器直接暴露於羊水中，更容易出現腸道發育與水腫問題，因此B選項將兩者的特徵敘述顛倒。腹裂畸形缺損處通常在肚臍右側。",
            "flashcard_front": "臍膨出 / 腹裂畸形 / 臟器包膜 / 腸道外異常比例 / 缺損位置",
            "flashcard_back": "臍膨出有包膜且常伴隨腸道外其他器官異常；腹裂無包膜，極少伴隨腸道外異常。",
            "flashcard_summary": "臍膨出與腹裂畸形鑑別 -> 臍膨出有包膜且常合併其他器官畸形；腹裂畸形無包膜，較少合併腸外畸形。"
        }
    ]
}

# ==================== BATCH 004 ====================
batches_data["109-2_medicine-5_batch-004"] = {
    "dataset_id": "109-2_medicine-5",
    "batch_id": "109-2_medicine-5_batch-004",
    "items": [
        {
            "question_id": "109-2_medicine-5_046",
            "question_number": 46,
            "correct_answer": "C",
            "category_group": "醫學（五）",
            "category": "小兒外科",
            "category_confidence": "high",
            "key_point": "兒童手術之預防性抗生素開立指引與植入物影響。",
            "explanation": "在清潔手術（Class I Clean wounds）中，常規不需使用預防性抗生素。然而，漏斗胸矯正板置入手術（Nuss procedure）雖然是清潔手術，但因為體內會置入金屬矯正板（人工植入物），一旦感染後果嚴重，因此是使用預防性抗生素的適應症。腹股溝疝氣手術、睪丸固定手術及頸部淋巴管瘤切除手術若無特殊合併症，皆不需常規開立預防性抗生素。",
            "flashcard_front": "預防性抗生素 / 兒童清潔手術 / Nuss procedure / 人工植入物 / 疝氣手術",
            "flashcard_back": "清潔手術通常不需預防性抗生素，但置入人工金屬板的 Nuss 矯正手術為預防性抗生素指引之適應症。",
            "flashcard_summary": "清潔手術與預防性抗生素 -> 兒童常規清潔手術不需預防性抗生素，但涉及體內金屬植入物的 Nuss 手術則必須使用。"
        },
        {
            "question_id": "109-2_medicine-5_047",
            "question_number": 47,
            "correct_answer": "B",
            "category_group": "醫學（五）",
            "category": "小兒外科",
            "category_confidence": "high",
            "key_point": "兒童頸部淋巴結腫大的評估與手術切片指引。",
            "explanation": "兒童鎖骨上（supraclavicular）淋巴結腫大在臨床上高度懷疑為惡性腫瘤（如淋巴瘤）或活動性結核等嚴重系統性疾病，因此單一且直徑達2公分的鎖骨上淋巴結是最強烈需要進行手術切片檢查的指引。相較之下，前頸部、耳後或枕骨區的微小淋巴結（如0.5至0.8公分）在兒童非常常見，多為感染後的良性反應性淋巴腺炎，通常以觀察或保守治療為主，不需立即切片。",
            "flashcard_front": "兒童 / 頸部淋巴結腫大 / 鎖骨上淋巴結 / 手術切片適應症 / 反應性淋巴結",
            "flashcard_back": "鎖骨上區淋巴結腫大惡性率高，一旦發現（即使無痛）應高度警惕並儘早安排手術切片。",
            "flashcard_summary": "兒童淋巴結切片指引 -> 鎖骨上區淋巴結腫大高度懷疑惡性，是最需要進行手術切片檢查的解剖位置。"
        },
        {
            "question_id": "109-2_medicine-5_048",
            "question_number": 48,
            "correct_answer": "B",
            "category_group": "醫學（五）",
            "category": "大腸直腸科",
            "category_confidence": "high",
            "key_point": "結腸憩室炎（Diverticulitis）的手術適應症。",
            "explanation": "結腸憩室炎的手術適應症包括：憩室破裂導致瀰漫性腹膜炎（free perforation with peritonitis，需緊急手術），以及形成結腸膀胱瘻管（colovesical fistula，需限期或擇期手術切除瘻管與病變段腸道）。而局部小於2公分的膿瘍（localized abscess）通常首選抗生素保守治療；輕度貧血（血紅素9.9）也非憩室炎手術的適應症。",
            "flashcard_front": "結腸憩室炎 / 瀰漫性腹膜炎 / 局部膿瘍 / 結腸膀胱瘻管 / 手術適應症",
            "flashcard_back": "憩室炎破裂腹膜炎與併發結腸膀胱瘻管是手術絕對適應症；局部小膿瘍可先以內科保守治療。",
            "flashcard_summary": "憩室炎手術適應症 -> 憩室破裂腹膜炎與結腸膀胱瘻管為手術適應症，局部小膿瘍與輕度貧血不需立即手術。"
        },
        {
            "question_id": "109-2_medicine-5_049",
            "question_number": 49,
            "correct_answer": "A",
            "category_group": "醫學（五）",
            "category": "大腸直腸科",
            "category_confidence": "high",
            "key_point": "潰瘍性結腸炎與克隆氏症的臨床病理特徵鑑別。",
            "explanation": "克隆氏症（Crohn's disease）表現為全層性發炎（transmural inflammation），因此其大體外觀（gross appearance）常有腸壁變厚（thickened colon wall）與管腔狹窄；而潰瘍性結腸炎（Ulcerative colitis）病變侷限於黏膜層，腸壁通常不變厚。克隆氏症鏡下常可見淋巴泡聚集（lymphoid aggregates）；潰瘍性結腸炎臨床上較常出現明顯血便；由於克隆氏症易在吻合口復發且有瘻管風險，故為迴腸袋肛門吻合術（ileal pouch-anal anastomosis）的禁忌症。",
            "flashcard_front": "潰瘍性結腸炎 / 克隆氏症 / 腸壁變厚 / 淋巴聚集 / 迴腸袋禁忌症 / 血便",
            "flashcard_back": "克隆氏症為全層發炎，腸壁常變厚，且為迴腸袋禁忌症；潰瘍性結腸炎病變局限黏膜，腸壁不厚。",
            "flashcard_summary": "UC與Crohn's病理大體鑑別 -> 克隆氏症為全層發炎且腸壁變厚；潰瘍性結腸炎主要侵犯黏膜層，腸壁不厚。"
        },
        {
            "question_id": "109-2_medicine-5_050",
            "question_number": 50,
            "correct_answer": "A",
            "category_group": "醫學（五）",
            "category": "大腸直腸科",
            "category_confidence": "high",
            "key_point": "骨盆底肌肉群（提肛肌）的解剖構造。",
            "explanation": "骨盆底肌肉群（又稱提肛肌，levator ani）主要由恥骨直腸肌（puborectalis）、恥骨尾骨肌（pubococcygeus）和腸骨尾骨肌（iliococcygeus）組成。梨狀肌（piriformis）屬於後骨盆壁的肌肉，並不屬於提肛肌的組成部分。恥骨直腸肌平時維持張力以保持肛門直腸角，排便時放鬆使角度變直以利糞便排出。",
            "flashcard_front": "骨盆底肌肉群 / 提肛肌 / 恥骨直腸肌 / 梨狀肌 / 肛門直腸角度",
            "flashcard_back": "提肛肌包含恥骨直腸肌、恥骨尾骨肌與腸骨尾骨肌；梨狀肌為骨盆壁肌肉，不屬於提肛肌。",
            "flashcard_summary": "提肛肌組成結構 -> 提肛肌由恥骨直腸肌、恥骨尾骨肌與腸骨尾骨肌組成，梨狀肌不屬於其中。"
        },
        {
            "question_id": "109-2_medicine-5_051",
            "question_number": 51,
            "correct_answer": "A",
            "category_group": "醫學（五）",
            "category": "一般外科",
            "category_confidence": "high",
            "key_point": "總膽管結石的治療首選與 ERCP 應用。",
            "explanation": "內視鏡逆行性膽胰管攝影術（ERCP）是目前治療總膽管結石（CBD stone）的重要且常用方法，能有效取出結石。ERCP 取出膽管結石的成功率非常高，可達 90% 以上，並非只有不到 50%。老年人因為膽道張力變差及膽汁滯留，在手術或處置後復發結石的機率比年輕人高。對於合併膽囊結石與總膽管結石的患者，通常優先考慮 ERCP 取石後再行腹腔鏡膽囊切除。",
            "flashcard_front": "總膽管結石 / ERCP / 成功率 / 年齡與復發率 / 腹腔鏡膽囊切除",
            "flashcard_back": "ERCP是總膽管結石的首選治療，成功率大於90%；老年人術後結石復發率高於年輕人。",
            "flashcard_summary": "總膽管結石治療與ERCP -> ERCP 取石成功率大於90%且為首選；老年人復發率高於年輕人。"
        },
        {
            "question_id": "109-2_medicine-5_052",
            "question_number": 52,
            "correct_answer": "C",
            "category_group": "醫學（五）",
            "category": "外科概論",
            "category_confidence": "high",
            "key_point": "單一件口腹腔鏡手術（SILS）的設備與操作空間優勢。",
            "explanation": "在單一切口腹腔鏡手術（SILS）中，所有的器械和鏡頭都需通過同一個切口，操作空間極為擁擠。因此，使用較小直徑的鏡頭（如 5 mm 鏡頭而非 10 mm 鏡頭）能夠顯著減少通道佔用，釋放更多空間供操作器械移動，對於手術空間極有幫助，所以C敘述錯誤。使用細長器械能避免體內外撞擊，高解析鏡頭則可代償小鏡頭的光線不足以維持清晰視野。",
            "flashcard_front": "單一切口腹腔鏡 (SILS) / 器械撞擊 / 鏡頭直徑 / 操作空間 / 設備特點",
            "flashcard_back": "較小直徑的鏡頭在單一切口手術中能有效釋放通道空間，減少器械與鏡頭的推擠碰撞。",
            "flashcard_summary": "單一切口腹腔鏡鏡頭影響 -> 較小直徑的鏡頭有助於騰出更多操作通道，改善單一切口手術的器械推擠。"
        },
        {
            "question_id": "109-2_medicine-5_053",
            "question_number": 53,
            "correct_answer": "D",
            "category_group": "醫學（五）",
            "category": "外科概論",
            "category_confidence": "high",
            "key_point": "達文西機械手臂手術（Robotic Surgery）的臨床操作特性。",
            "explanation": "達文西機械手臂手術雖然由主刀醫師在控制台操作，但手術過程中仍然「絕對需要」床邊助手（bedside assistant）協助更換機械手臂器械、裝卸縫線、吸引積液及牽引組織等。達文西系統提供符合人體工學的控制台、高清3D立體影像以及能消除人手生理顫抖的去顫功能，這些皆是其主要優點。",
            "flashcard_front": "達文西手臂 / 機械手臂手術 / 3D立體影像 / 影像去顫 / 床邊助手 (bedside assistant)",
            "flashcard_back": "達文西手術仍然絕對需要床邊助手協助更換器械與拉鉤；其優點有3D影像與去顫功能。",
            "flashcard_summary": "達文西手術床邊助手角色 -> 達文西機械手臂手術仍需要床邊助手協助操作，床邊助手無法被機器人取代。"
        },
        {
            "question_id": "109-2_medicine-5_054",
            "question_number": 54,
            "correct_answer": "C",
            "category_group": "醫學（五）",
            "category": "一般外科",
            "category_confidence": "high",
            "key_point": "胰十二指腸切除術（Whipple）術後乳糜漏的診斷。",
            "explanation": "患者在接受胰十二指腸切除手術後，於開始進食時出現引流量劇增（800 ml/day），且引流液從透明轉為乳白色混濁液，且無發燒等感染症狀，此為典型乳糜液滲漏（chyle leak）的表現。乳糜漏是由於手術中損傷了後腹腔的淋巴管或乳糜池所致。胰液滲漏通常呈清澈水樣且會伴隨皮膚刺激，膽汁滲漏呈黃綠色，腹內膿瘍則會伴隨發燒與白血球增高。",
            "flashcard_front": "胰十二指腸切除 (Whipple) / 術後進食 / 乳白色引流液 / 乳糜漏 / chyle leak",
            "flashcard_back": "術後進食後引流量突增且呈乳白色混濁，無感染發燒，高度提示乳糜漏。",
            "flashcard_summary": "術後乳糜漏診斷 -> Whipple 術後進食引流量劇增且呈乳白色乳狀液，為後腹腔淋巴管受損致乳糜漏。"
        },
        {
            "question_id": "109-2_medicine-5_055",
            "question_number": 55,
            "correct_answer": "A",
            "category_group": "醫學（五）",
            "category": "一般外科",
            "category_confidence": "high",
            "key_point": "乳糜漏引流液的實驗室診斷指標。",
            "explanation": "診斷乳糜液滲漏（chyle leak）的指標包括引流液中的三酸甘油脂（triglyceride）濃度高（通常大於110 mg/dL），而膽固醇（cholesterol）濃度低。此外，乳糜液內富含淋巴液，因此細胞分類檢查會顯示淋巴球（lymphocyte）比率極高，而中性白血球（neutrophil）比率低（排除化膿性感染）。乳糜液通常是無菌的，澱粉酶高則為胰漏之指標。",
            "flashcard_front": "乳糜液檢驗 / 三酸甘油脂 / 膽固醇 / 淋巴球比率 / 澱粉酶",
            "flashcard_back": "乳糜液特徵為三酸甘油脂高（>110 mg/dL）、膽固醇低，且細胞分類以淋巴球為主。",
            "flashcard_summary": "乳糜漏檢驗指標 -> 乳糜引流液中三酸甘油脂高（>110 mg/dL）且富含淋巴球，是其關鍵診斷依據。"
        },
        {
            "question_id": "109-2_medicine-5_056",
            "question_number": 56,
            "correct_answer": "C",
            "category_group": "醫學（五）",
            "category": "神經外科",
            "category_confidence": "high",
            "key_point": "高位脊髓損傷引發神經性休克（Neurogenic Shock）的臨床表徵。",
            "explanation": "患者因第五頸椎（C5）折斷導致脊髓損傷，出現四肢癱瘓、低血壓（75/55 mmHg）及相對低心搏率（60次/分，無代償性心跳過速），且四肢溫暖無冰冷，這是典型的神經性休克表現。脊髓損傷阻斷了交感神經傳導，導致血管舒張、外周阻力下降及心跳慢。失血性休克通常會伴隨代償性心跳過速（心跳>100次/分）及皮膚濕冷。",
            "flashcard_front": "頸椎骨折 / 四肢癱瘓 / 低血壓 / 心跳60下 / 皮膚無濕冷 / 神經性休克",
            "flashcard_back": "高位脊髓損傷阻斷交感神經，引發血管舒張與心跳減慢，呈溫暖的低血壓（神經性休克）。",
            "flashcard_summary": "脊髓損傷與神經性休克 -> 頸椎骨折伴隨癱瘓、低血壓、心跳減慢且四肢不冷，為交感阻斷引起之神經性休克。"
        },
        {
            "question_id": "109-2_medicine-5_057",
            "question_number": 57,
            "correct_answer": "B",
            "category_group": "醫學（五）",
            "category": "骨科",
            "category_confidence": "high",
            "key_point": "急性膝關節血腫與前十字韌帶（ACL）斷裂。",
            "explanation": "運動員在落地受傷時聽到膝關節內「啪」的一聲，並在數小時內出現迅速關節鼓脹，且抽出暗紅色血液（hemarthrosis），在臨床上最常見的診斷是前十字韌帶（ACL）斷裂，約占急性關節血腫病例的 70%。股四頭肌腱或髕骨韌帶斷裂通常會導致無法主動伸直膝關節，且多有明顯的局部凹陷；髕骨前滑囊炎腫脹局限於關節囊外，不會在關節腔內抽出大量血液。",
            "flashcard_front": "膝關節外傷 / 啪一聲 / 關節血腫 / 抽出暗紅血液 / 前十字韌帶 (ACL) / 髕骨韌帶",
            "flashcard_back": "運動中膝關節扭傷且有啪聲、伴隨關節內積血，臨床上最常見為前十字韌帶（ACL）斷裂。",
            "flashcard_summary": "膝關節血腫與ACL斷裂 -> 膝外傷伴隨關節內迅速積血及斷裂聲，高度提示前十字韌帶（ACL）斷裂。"
        },
        {
            "question_id": "109-2_medicine-5_058",
            "question_number": 58,
            "correct_answer": "B",
            "category_group": "醫學（五）",
            "category": "骨科",
            "category_confidence": "high",
            "key_point": "佩吉特氏病（Paget's disease of bone）的病理特徵與診斷。",
            "explanation": "佩吉特氏病（骨膨隆症）是一種骨骼轉換率極高的疾病，其病理特徵為骨小樑粗大、排列混亂的編織骨（woven bone）及由於反覆成骨與破骨交替而產生的不規則藍色骨泥線（cement lines，呈鑲嵌狀樣外觀）。該病成骨與破骨均大幅增加，而非成骨增高與破骨降低；骨轉換率高導致尿中 pyridinoline 和 deoxypyridinoline 偏高而非偏低；治療通常給予雙磷酸鹽或降鈣素，不可給予副甲狀腺素（會惡化破骨過程）。",
            "flashcard_front": "佩吉特氏病 (Paget's disease) / 骨泥線 (cement lines) / 尿中 pyridinoline / 雙磷酸鹽 / 骨轉換",
            "flashcard_back": "佩吉特氏病病理可見粗大骨小樑與不規則骨泥線；尿中骨吸收指標上升，治療禁用副甲狀腺素。",
            "flashcard_summary": "佩吉特氏病病理與治療 -> 佩吉特氏病特徵為不規則骨泥線及高骨轉換率，尿中骨指標偏高，禁用副甲狀腺素。"
        },
        {
            "question_id": "109-2_medicine-5_059",
            "question_number": 59,
            "correct_answer": "C",
            "category_group": "醫學（五）",
            "category": "骨科",
            "category_confidence": "high",
            "key_point": "單一性骨軟骨瘤與多發性遺傳性外生骨贅（MHE）的臨床特徵。",
            "explanation": "單一性骨軟骨瘤或多發性遺傳性外生骨贅（MHE）發生在扁平骨（如骨盆、肩胛骨）或軀幹部位時，其惡性化轉型（變為軟骨肉瘤）的機會相較於長骨高很多。MHE 屬於自體顯性遺傳（autosomal dominant），外顯率極高。莖狀骨軟骨瘤的軟骨帽生長方向是「背向」鄰近關節（朝向骨幹生長）。對於無症狀的病灶，一般不主張在發育成熟前預防性手術，以避免傷及生長板。",
            "flashcard_front": "骨軟骨瘤 / 多發性遺傳性外生骨贅 (MHE) / 骨盆肩胛骨 / 惡性轉型 / 軟骨帽生長方向",
            "flashcard_back": "扁平骨骨軟骨瘤惡性轉向軟骨肉瘤機會較高；MHE 屬顯性遺傳；莖狀軟骨帽背向關節生長。",
            "flashcard_summary": "骨軟骨瘤與MHE特徵 -> 發生於軀幹與扁平骨的骨軟骨瘤惡性化機會較高；MHE屬自體顯性遺傳。"
        },
        {
            "question_id": "109-2_medicine-5_060",
            "question_number": 60,
            "correct_answer": "C",
            "category_group": "醫學（五）",
            "category": "骨科",
            "category_confidence": "high",
            "key_point": "踝關節骨折的 X 光影像評估相位選擇。",
            "explanation": "評估踝部骨折時，標準的三相X光檢查包含前後相位（AP view）、側相位（lateral view）及 Mortise 氏相位。Mortise 相位（距骨外旋15度）是評估距骨向外側移位與下脛腓關節間隙的最佳相位；側相位最適合用來評估後踝（posterior malleolus）骨折。然而，前後相位（AP view）並不適合用來診斷跟骨骨折（跟骨骨折需安排跟骨軸位與側位，或直接做電腦斷層），因此C選項最不適當。",
            "flashcard_front": "踝部骨折 / X光三相位 / Mortise view / 後踝骨折 / 跟骨骨折",
            "flashcard_back": "踝關節X光主要評估踝部骨折；診斷跟骨骨折需特定的跟骨照相（Harris view）或CT，AP ankle view幫助有限。",
            "flashcard_summary": "踝關節X光相位選擇 -> 踝關節前後相位主要評估踝骨，跟骨骨折需使用跟骨專用照相或電腦斷層。"
        }
    ]
}

# ==================== BATCH 005 ====================
batches_data["109-2_medicine-5_batch-005"] = {
    "dataset_id": "109-2_medicine-5",
    "batch_id": "109-2_medicine-5_batch-005",
    "items": [
        {
            "question_id": "109-2_medicine-5_061",
            "question_number": 61,
            "correct_answer": "D",
            "category_group": "醫學（五）",
            "category": "骨科",
            "category_confidence": "high",
            "key_point": "黏多醣症（Mucopolysaccharidoses, MPS）的骨骼異常表現。",
            "explanation": "黏多醣症（MPS）病童由於溶小體酵素缺乏，會導致多發性成骨發育不良（dysostosis multiplex），常見病變包括鎖骨變寬、卵圓形或前側呈尖喙狀的脊椎體、以及髖臼發育不良等。在髖部病變方面，MPS病童典型表現為髖外翻（coxa valga，股骨頸角變大），而非髖內翻（coxa vara），因此D選項最少發生。",
            "flashcard_front": "黏多醣症 / 多發性成骨發育不良 / 鎖骨變寬 / 卵圓脊椎體 / 髖臼發育不良 / 髖外翻",
            "flashcard_back": "黏多醣症病童的髖部病變以髖外翻（coxa valga）為主，極少發生髖內翻（coxa vara）。",
            "flashcard_summary": "黏多醣症髖部異常 -> 黏多醣症引起的骨骼發育不良中，髖部表現為髖外翻（coxa valga），極少見髖內翻。"
        },
        {
            "question_id": "109-2_medicine-5_062",
            "question_number": 62,
            "correct_answer": "C",
            "category_group": "醫學（五）",
            "category": "骨科",
            "category_confidence": "high",
            "key_point": "肘隧道症候群（Cubital Tunnel Syndrome）的診斷與症狀。",
            "explanation": "肘隧道症候群是由於肘部尺神經（ulnar nerve）受壓迫所引起。臨床表現為靠近小指和無名指尺側半邊之手掌麻木、無力，晚期會因手內肌萎縮前指爪手（claw hand）畸形。在診斷上，最常用且最核心的檢查是神經傳導速度與肌電圖（NCS/EMG，即電學生理檢查），磁振造影（MRI）並非首選或最常用的檢查工具，故C選項錯誤。",
            "flashcard_front": "肘隧道症候群 / 尺神經壓迫 / 小指麻痺 / 爪手 (claw hand) / 肌電圖 (EMG) / MRI",
            "flashcard_back": "肘隧道症候群是尺神經受壓；最常用且金標準的檢查為神經電氣生理檢查（NCS/EMG），而非MRI。",
            "flashcard_summary": "肘隧道症候群診斷 -> 肘隧道症候群由尺神經受壓引起，診斷以肌電圖與神經傳導檢查為主，非MRI。"
        },
        {
            "question_id": "109-2_medicine-5_063",
            "question_number": 63,
            "correct_answer": "B",
            "category_group": "醫學（五）",
            "category": "骨科",
            "category_confidence": "high",
            "key_point": "青春期自發性脊椎側彎（AIS）的解剖與臨床特徵。",
            "explanation": "青春期自發性脊椎側彎（AIS）中，胸椎側彎的凸側（convex side）通常位於右側（約占90%）；若出現左側凸，需高度警惕有無脊髓空洞症或腫瘤等病變。在輕微側彎（約10度）時，男女發生率相當，但嚴重側彎（>30度）時，女性發生率可達男性的10倍。腸骨脊鈣化中心（Risser sign）是從腸骨前上棘（ASIS）往後向後上棘方向骨化。發病年齡越小，惡化風險越高。",
            "flashcard_front": "青春期自發性脊椎側彎 (AIS) / 右側凸 / Risser sign / 惡化風險 / 發病年齡",
            "flashcard_back": "AIS 胸椎側彎凸側通常在右側；發病年齡越小（如骨骼未發育成熟）側彎角度惡化風險越高。",
            "flashcard_summary": "脊椎側彎凸側與惡化 -> 青春期自發性脊椎側彎多表現為右側凸；患者骨骼發育年齡越小，側彎惡化風險越高。"
        },
        {
            "question_id": "109-2_medicine-5_064",
            "question_number": 64,
            "correct_answer": "B",
            "category_group": "醫學（五）",
            "category": "泌尿科",
            "category_confidence": "high",
            "key_point": "尿液草酸來源的膳食比率。",
            "explanation": "人體尿液中排出的草酸（oxalate），絕大部分（約 80%~90%）是來自於肝臟的內源性代謝合成，主要是由甘胺酸或維生素 C 等物質代謝而來。只有大約 10%~15% 的草酸是直接經由飲食中的草酸鹽吸收後隨尿液排出。因此，對於高草酸尿症或草酸鈣結石患者，單純限制飲食草酸只能部分降低尿草酸濃度。",
            "flashcard_front": "尿液草酸 / 飲食草酸比率 / 內源性代謝 / 草酸鈣結石 / 膳食限制",
            "flashcard_back": "尿液中草酸僅有 10%~15% 來自飲食吸收，其餘 80%~90% 皆由人體內源性代謝產生。",
            "flashcard_summary": "尿液草酸與飲食關係 -> 尿液草酸約 10%~15% 來自食物吸收，其餘多由體內代謝產生。"
        },
        {
            "question_id": "109-2_medicine-5_065",
            "question_number": 65,
            "correct_answer": "C",
            "category_group": "醫學（五）",
            "category": "泌尿科",
            "category_confidence": "high",
            "key_point": "隱睪症與睪丸癌的關係及手術定位。",
            "explanation": "隱睪症是發生睪丸癌的重要危險因子，大約7%-10%的睪丸癌患者有隱睪症病史。雖然將隱睪手術固定於陰囊（orchidopexy）能使睪丸移至易於觸診的位置，方便患者自我檢查與臨床監測以早期發現癌症，但手術本身並不能顯著減少睪丸癌的發病機率（尤其是若在青春期後才開刀）。精原細胞瘤（seminoma）是睪丸原發癌最常見類型；懷孕期間母親使用雌激素會增加胎兒隱睪與睪丸癌的風險。",
            "flashcard_front": "隱睪症 / 睪丸癌 / 睪丸固定術 (orchidopexy) / 降低癌症機率 / 自我檢查",
            "flashcard_back": "睪丸固定術主要能讓睪丸易於觸診監測，但並不能消除或顯著降低隱睪症患者發生睪丸癌的風險。",
            "flashcard_summary": "隱睪症與睪丸固定術 -> 隱睪症行睪丸固定術無法消除睪丸癌風險，但能讓睪丸易於摸到以便早期發現。"
        },
        {
            "question_id": "109-2_medicine-5_066",
            "question_number": 66,
            "correct_answer": "A",
            "category_group": "醫學（五）",
            "category": "泌尿科",
            "category_confidence": "high",
            "key_point": "前列腺癌的轉移評估與血清 PSA 限制。",
            "explanation": "血清前列腺特定抗原（PSA）是一項極佳的血液生化腫瘤指標，其數值高低與前列腺癌的預後密切相關。然而，PSA 作為血清指標，並不能具體定位或顯示淋巴結轉移，評估前列腺癌的局部淋巴結轉移仍然需要依賴電腦斷層（CT）或磁振造影（MRI）等影像學檢查，因此A選項錯誤。前列腺癌極易發生骨轉移，最常累及脊椎及骨盆，高達70%-90%的晚期死者有骨轉移。",
            "flashcard_front": "前列腺癌 / 淋巴轉移 / 血清 PSA / 電腦斷層 (CT) / 骨轉移 / 脊椎骨盆",
            "flashcard_back": "PSA是血清指標，無法直接定位或偵測局部淋巴結轉移，淋巴結轉移評估需依賴 CT/MRI 等影像。",
            "flashcard_summary": "前列腺癌轉移評估 -> 評估前列腺癌局部淋巴結轉移需靠 CT 或 MRI 影像檢查，血清 PSA 無法定位轉移灶。"
        },
        {
            "question_id": "109-2_medicine-5_067",
            "question_number": 67,
            "correct_answer": "D",
            "category_group": "醫學（五）",
            "category": "泌尿科",
            "category_confidence": "high",
            "key_point": "腎臟癌伴生 Stauffer 症候群的致病細胞激素因子。",
            "explanation": "史陶佛氏症候群（Stauffer syndrome）是腎細胞癌（RCC）患者出現的一種副腫瘤症候群，表現為非轉移性的肝功能異常。現代醫學研究普遍認為其主要致病因子為白血球介素-6（IL-6）。然而，在本題國考選項中，官方公布的正確答案為 (D) 粒細胞-巨噬細胞集落刺激因子（GM-CSF），解釋為某些腫瘤可能通過產生過多的 GM-CSF 等細胞激素參與了此一異常肝反應。",
            "flashcard_front": "腎細胞癌 / Stauffer syndrome / 非轉移性肝功能異常 / 核心細胞激素 / GM-CSF / IL-6",
            "flashcard_back": "Stauffer syndrome常由 IL-6 介導；本題官方答案為 (D) GM-CSF，說明腫瘤分泌細胞激素引發肝功能異常。",
            "flashcard_summary": "Stauffer syndrome成因 -> 史陶佛氏症候群由腫瘤分泌細胞激素引起，一般與 IL-6 相關，本題官方給出答案為 GM-CSF。"
        },
        {
            "question_id": "109-2_medicine-5_068",
            "question_number": 68,
            "correct_answer": "D",
            "category_group": "醫學（五）",
            "category": "泌尿科",
            "category_confidence": "high",
            "key_point": "5-alpha 還原酶抑制劑治療良性前列腺肥大的適應症與機轉。",
            "explanation": "5-alpha還原酶抑制劑（5-ARI，如 finasteride）是藉由阻斷睪固酮（testosterone）轉化為雙氫睪固酮（DHT），進而使前列腺上皮細胞凋亡並縮小腺體體積。5-ARI 的療效受前列腺體積影響很大，主要對前列腺體積顯著增大（通常 >30-40 mL）的患者才有明確療效，對於前列腺體積較小的患者效果並不顯著，因此D選項敘述錯誤。5-ARI 需持續使用6個月以上才達最大療效，可使腺體縮小約20%並使血清 PSA 值降低約50%。",
            "flashcard_front": "5-alpha 還原酶抑制劑 / 良性前列腺肥大 (BPH) / 體積縮小 / PSA 減半 / 前列腺初始體積",
            "flashcard_back": "5-ARI 僅對前列腺體積較大（>30-40 mL）者有顯著療效，對小前列腺患者無明顯症狀改善。",
            "flashcard_summary": "5-ARI 治療前列腺肥大 -> 5-ARI 需使用6個月以上，可使體積小20%、PSA減半，但僅對大體積前列腺肥大患者有效。"
        },
        {
            "question_id": "109-2_medicine-5_069",
            "question_number": 69,
            "correct_answer": "B",
            "category_group": "醫學（五）",
            "category": "泌尿科",
            "category_confidence": "high",
            "key_point": "急性細菌性副睪丸炎的發病年齡與相關病因。",
            "explanation": "急性細菌性副睪丸炎在不同年齡層有不同病因。年輕男性的急性副睪丸炎通常是由於不安全性行為傳染的沙眼衣原體（Chlamydia）或淋病雙球菌所致，而非與糖尿病有關；糖尿病相關的尿路感染與副睪丸炎則多見於中老年男性，因此B選項敘述錯誤。小男孩發生急性副睪丸炎時，必須檢查有無伴隨輸尿管異位開口等先天泌尿道異常；若副睪丸炎形成膿瘍，需進行手術引流。",
            "flashcard_front": "急性細菌性副睪丸炎 / 年輕男性 / 性傳染病 / 小男孩先天異常 / 膿瘍引流",
            "flashcard_back": "年輕男性副睪丸炎多由性傳染病（如衣原體）引起；糖尿病引起者多見於中老年人。",
            "flashcard_summary": "細菌性副睪丸炎病因 -> 年輕男性副睪丸炎通常與性傳染病有關，老年人多與尿路梗阻或糖尿病相關。"
        },
        {
            "question_id": "109-2_medicine-5_070",
            "question_number": 70,
            "correct_answer": "B",
            "category_group": "醫學（五）",
            "category": "泌尿科",
            "category_confidence": "high",
            "key_point": "高齡男性低睪固酮（遲發性性腺功能減退症）的臨床表現。",
            "explanation": "高齡男性庫存睪固酮降低（男性更年期）會引發性慾減退、骨質疏鬆及脂肪增加導致肥胖等一系列症狀。然而，海綿體靜脈溢漏（venous leakage）是指陰莖海綿體靜脈閉合機制受損，導致勃起時血液無法留駐，這屬於陰莖血管與組織結構性的病變，並非由低睪固酮直接引起的生理功能症狀，因此B與低睪固酮無關。",
            "flashcard_front": "高齡男性 / 低睪固酮 / 性慾減退 / 骨質疏鬆 / 肥胖 / 海綿體靜脈溢漏 (venous leakage)",
            "flashcard_back": "低睪固酮引起性慾降低、骨鬆及肥胖；海綿體靜脈溢漏屬於陰莖血管結構異常，非低睪固酮直接引起。",
            "flashcard_summary": "低睪固酮症狀與靜脈溢漏 -> 低睪固酮引發性慾減退、骨鬆與肥胖；海綿體靜脈溢漏為勃起血管結構病變，與其無直系關聯。"
        },
        {
            "question_id": "109-2_medicine-5_071",
            "question_number": 71,
            "correct_answer": "C",
            "category_group": "醫學（五）",
            "category": "泌尿科",
            "category_confidence": "high",
            "key_point": "睪丸生理學與激素反饋。",
            "explanation": "睪丸內的 Leydig 細胞（間質細胞）負責產生並分泌睪固酮（testosterone），因此C選項正確。黃體成長激素（LH）是作用於 Leydig 細胞以刺激睪固酮分泌；濾泡刺激素（FSH）則是作用於 Sertoli 細胞（支持細胞）以促進精子生成，選項A與B將作用細胞互換。精液中的果糖（fructose）主要是由精囊（seminal vesicle）產生而非前列腺。",
            "flashcard_front": "睪丸生理 / LH / FSH / Leydig細胞 / Sertoli細胞 / 果糖來源",
            "flashcard_back": "Leydig細胞受LH作用分泌睪固酮；Sertoli細胞受FSH作用促進精子發育；果糖由精囊產生。",
            "flashcard_summary": "睪丸與精液生理 -> 睪固酮由 Leydig 細胞在 LH 刺激下產生；精液中的果糖來自精囊而非前列腺。"
        },
        {
            "question_id": "109-2_medicine-5_072",
            "question_number": 72,
            "correct_answer": "B",
            "category_group": "醫學（五）",
            "category": "一般外科",
            "category_confidence": "high",
            "key_point": "下腸繫膜動脈（IMA）分支解剖與直腸出血。",
            "explanation": "下腸繫膜動脈（IMA）分支包括左結腸動脈、乙狀結腸動脈及終末分支直腸上動脈（superior rectal artery）。在血液透析病人發生下消化道出血休克時，緊急血管攝影顯示下腸繫膜動脈終末支有顯影劑外滲，該出血來源即為直腸上動脈。直腸上動脈是直腸近端的主要供血血管。內陰動脈與臀下動脈源自內髂動脈分支，不屬於 IMA 系統。",
            "flashcard_front": "洗腎病患 / 下消化道出血休克 / 血管攝影 / 下腸繫膜動脈分支 / 直腸上動脈",
            "flashcard_back": "下腸繫膜動脈（IMA）的終末支為直腸上動脈，負責供應直腸血液，是影像上顯示的出血源。",
            "flashcard_summary": "下腸繫膜動脈分支與出血 -> 洗腎病患下消化道出血時，經 IMA 血管攝影證實出血來自其終末支直腸上動脈。"
        },
        {
            "question_id": "109-2_medicine-5_073",
            "question_number": 73,
            "correct_answer": "C",
            "category_group": "醫學（五）",
            "category": "泌尿科",
            "category_confidence": "high",
            "key_point": "腎臟尿路上皮細胞癌（UTUC）的影像學診斷特徵。",
            "explanation": "患者出現肉眼可見血尿，且靜脈注射尿路X光攝影（IVU）顯示腎盂或腎盞內有典型的充盈缺損（filling defect）與腎盞受壓顯影不佳，這符合腎尿路上皮細胞癌（urothelial cell carcinoma, UTUC）的特徵。腎細胞癌（RCC）和血管平滑肌脂肪瘤（AML）屬於腎實質腫瘤，在IVU上多表現為腎外輪廓膨出或實質壓迫，較少早期在腎盞內形成單純充盈缺損。腎淋巴瘤在IVU上較不常見。",
            "flashcard_front": "血尿 / 靜脈注射尿路攝影 (IVU) / 腎盂充盈缺損 / 腎尿路上皮癌 (UTUC) / RCC",
            "flashcard_back": "IVU 顯示腎盂/腎盞內充盈缺損為尿路上皮癌（UTUC）的典型特徵；腎細胞癌（RCC）則多為實質腫瘤。",
            "flashcard_summary": "尿路造影充盈缺損 -> IVU 顯示腎盂或腎盞內的充盈缺損，高度提示腎尿路上皮細胞癌（UTUC）。"
        },
        {
            "question_id": "109-2_medicine-5_074",
            "question_number": 74,
            "correct_answer": "B",
            "category_group": "醫學（五）",
            "category": "一般外科",
            "category_confidence": "high",
            "key_point": "肝細胞癌（HCC）的三相式電腦斷層影像診斷。",
            "explanation": "在三相式電腦斷層掃描中，該肝臟腫瘤在動脈期（arterial phase）出現顯著的顯影劑增強（wash-in），並在靜脈期（venous/delayed phase）迅速消退（wash-out），這是肝細胞癌（HCC）的典型影像特徵。大約30%的肝細胞癌患者在早期或分化良好時其血清胎兒蛋白（AFP）可為正常。相較之下，血管瘤（hemangioma）在動脈期呈邊緣結節狀增強並逐漸向中心填滿，肝囊腫（cyst）無增強，膽管癌（cholangiocarcinoma）則在延遲期呈漸進性向心增強。",
            "flashcard_front": "三相電腦斷層 /動脈期 wash-in / 靜脈期 wash-out / AFP正常 / 肝細胞癌 (HCC) / 血管瘤",
            "flashcard_back": "影像上表現為典型動脈期增強、門脈期消退（wash-in & wash-out），即使AFP正常亦首選診斷HCC。",
            "flashcard_summary": "肝細胞癌三相CT特徵 -> 典型動脈期顯著增強及靜脈期消退（wash-in and wash-out）是診斷肝細胞癌（HCC）的標準。"
        },
        {
            "question_id": "109-2_medicine-5_075",
            "question_number": 75,
            "correct_answer": "D",
            "category_group": "醫學（五）",
            "category": "一般外科",
            "category_confidence": "high",
            "key_point": "減重手術（Roux-en-Y胃繞道）術後併發症與傾食症候群。",
            "explanation": "胃繞道減肥手術（Roux-en-Y gastric bypass）後，由於幽門被繞過，高滲透壓的食物迅速進入小腸，極易引發傾食症候群（dumping syndrome），這常在術後開始進食時產生，因此D選項最正確。如果術後因腸阻塞導致噁心嘔吐，若是發生在共同通道（common channel）或膽胰支（biliopancreatic limb）阻塞，仍會吐出含有膽汁的嘔吐物。術後併發症可能與吻合口縫合等外科技術有一定關係。吻合口潰瘍（stomal ulcer）通常在術後數週至數月內發生，極少在術後3~5天內就形成。",
            "flashcard_front": "胃繞道手術 / 術後進食 / 傾食症候群 (dumping syndrome) / 膽汁嘔吐 / 吻合口潰瘍時間",
            "flashcard_back": "胃繞道術後開始進食最易發生傾食症候群；腸阻塞仍可能吐膽汁；吻合口潰瘍多在數週後發生。",
            "flashcard_summary": "胃繞道減重手術併發症 -> 胃繞道術後進食最常見併發症為傾食症候群；術後腸阻塞仍可吐膽汁。"
        }
    ]
}

# ==================== BATCH 006 ====================
batches_data["109-2_medicine-5_batch-006"] = {
    "dataset_id": "109-2_medicine-5",
    "batch_id": "109-2_medicine-5_batch-006",
    "items": [
        {
            "question_id": "109-2_medicine-5_076",
            "question_number": 76,
            "correct_answer": "A",
            "category_group": "醫學（五）",
            "category": "外科概論",
            "category_confidence": "high",
            "key_point": "孕婦外傷的急救處理與產科併發症診斷。",
            "explanation": "懷孕34週孕婦外傷送醫，主訴下腹痛與出血，陰道分泌物pH值為7（偏鹼性）提示羊水外漏（羊膜破裂，因為正常陰道分泌物呈酸性，羊水呈鹼性），因此A選項正確。懷孕晚期出血患者在未排除前置胎盤前，絕對禁忌進行陰道/骨盆內診檢查以防大出血。孕婦休克時應採取左側臥位或將子宮推向左側（左側子宮移位），避免壓迫下腔靜脈，而非「左側抬高」（左側抬高會把子宮壓向右側的下腔靜脈）。若母體生命受威脅，電腦斷層（CT）的診斷效益大於胎兒輻射風險，不應盲目拒絕檢查。",
            "flashcard_front": "孕婦外傷 / 陰道出血 / 分泌物 pH 7 / 羊膜破裂 / 骨盆內診禁忌 / 左側子宮移位",
            "flashcard_back": "分泌物 pH 7 提示羊水鹼性滲漏（羊膜破裂）；前置胎盤未排除前禁忌內診；休克應採左側子宮移位。",
            "flashcard_summary": "孕婦外傷急救與評估 -> 分泌物 pH 值為 7 提示羊膜破裂；未排除前置胎盤前嚴禁內診，休克採左側子宮移位。"
        },
        {
            "question_id": "109-2_medicine-5_077",
            "question_number": 77,
            "correct_answer": "C",
            "category_group": "醫學（五）",
            "category": "外科概論",
            "category_confidence": "high",
            "key_point": "格拉斯哥昏迷指數（GCS）的臨床評分標準。",
            "explanation": "評估此病人的GCS分數：給予疼痛刺激時能張眼，睜眼反應（E）得 2 分；發出無法理解的聲音（無意義聲音），言語反應（V）得 2 分；運動反應（M）評估時，右手臂無反應，但左手能撥開疼痛刺激物（定位疼痛），運動反應以最佳側為準，定位疼痛得 5 分。將三者相加：E2 + V2 + M5 = 9 分，因此正確答案為 9 分。",
            "flashcard_front": "GCS評分 / 疼痛刺激張眼 / 無意義聲音 / 左手撥開疼痛 / 右手無反應",
            "flashcard_back": "睜眼2分（E2）、無意義言語2分（V2）、最佳運動反應為定位疼痛5分（M5），總分9分。",
            "flashcard_summary": "GCS昏迷指數評分 -> 睜眼E2加言語V2加最佳運動反應M5，此病人GCS總得分為9分。"
        },
        {
            "question_id": "109-2_medicine-5_078",
            "question_number": 78,
            "correct_answer": "C",
            "category_group": "醫學（五）",
            "category": "其他",
            "category_confidence": "high",
            "key_point": "愛滋病確診患者的法定通報、告知義務與法律責任。",
            "explanation": "根據愛滋病防治相關法規，確診愛滋病時，醫師有法定義務向衛生主管機關進行通報（點3）。若病人同意，醫師可以告知其同居女友（點1）；但若病人不同意，醫師不可擅自違反病人隱私權直接告知第三人，應由衛生單位介入輔導，故點2錯誤。若感染者明知自己感染，隱瞞他人並進行危險性行為導致傳染，須負刑事法律責任（點4）。因此正確選項為1, 3, 4。",
            "flashcard_front": "愛滋病確診 / 法定通報 / 病人隱私權 / 告知配偶或同居者 / 故意傳染法律責任",
            "flashcard_back": "醫師有義務向主管機關通報，但無權在病人不同意下直接向女友透露；明知感染而隱瞞傳播有刑責。",
            "flashcard_summary": "愛滋病法律與倫理職責 -> 醫師必須通報主管機關，無權擅自向第三者洩漏感染狀態，患者隱瞞並傳播有刑責。"
        },
        {
            "question_id": "109-2_medicine-5_079",
            "question_number": 79,
            "correct_answer": "C",
            "category_group": "醫學（五）",
            "category": "其他",
            "category_confidence": "high",
            "key_point": "具決定能力之成年病人的醫療自主權與隱私權保護。",
            "explanation": "病人為30歲未婚成年人，具有完全的限制與決定能力，依法享有醫療自主權與隱私權。其接受減重手術不需取得父母的同意，病人的隱私要求（不願意告知父母）應受到尊重。醫師應在與病人充分溝通後尊重其決定，並在病歷上記錄解釋溝通的過程與病人的選擇即可，不可強求通知父母，更不可私下透露。",
            "flashcard_front": "30歲成年人 / 具決定能力 / 減重手術 / 不願告知父母 / 醫療自主權 / 隱私權",
            "flashcard_back": "成年且具決定能力患者享有完整醫療自主權與隱私權，不需父母同意，醫師應尊重其決定並記錄。",
            "flashcard_summary": "成年病人的手術同意權 -> 30歲具決定能力之成年人有權自主決定手術且要求隱私，不需通知或徵得父母同意。"
        },
        {
            "question_id": "109-2_medicine-5_080",
            "question_number": 80,
            "correct_answer": "A",
            "category_group": "醫學（五）",
            "category": "其他",
            "category_confidence": "high",
            "key_point": "醫療糾紛後病歷紀錄修改的法律規範與效力。",
            "explanation": "當醫療糾紛發生後，醫師修改或補充病歷紀錄時，必須在補充處加註當時的年月日時，以免被認定為事後偽造或變造病歷。如果醫師修改或補充的內容與事實不符，在刑法上會構成業務登載不實罪，在民法上則可能因「舉證妨礙」而被判決負擔不利的舉證責任。法官若發現病歷有事後無標註的篡改，可直接認定該病歷紀錄無效並判決醫師過失，因此A選項「法官不能因為補充就認定無效」的說法錯誤。",
            "flashcard_front": "醫療糾紛 / 補充病歷紀錄 / 年月日加註 / 業務登載不實 / 舉證妨礙 / 法院認定",
            "flashcard_back": "補充病歷須加註年月日時，否則易被認定事後偽造無效；補充若非事實會涉及業務登載不實及民事不利。",
            "flashcard_summary": "病歷修改與補充效力 -> 醫療爭議後補充病歷若未加註日期常被法官認定無效，且不實補充會面臨登載不實刑責。"
        }
    ]
}

# ==================== BATCH 001 (MEDICINE 6) ====================
batches_data["109-2_medicine-6_batch-001"] = {
    "dataset_id": "109-2_medicine-6",
    "batch_id": "109-2_medicine-6_batch-001",
    "items": [
        {
            "question_id": "109-2_medicine-6_001",
            "question_number": 1,
            "correct_answer": "A",
            "category_group": "醫學（六）",
            "category": "麻醉科",
            "category_confidence": "high",
            "key_point": "全身麻醉甦醒拔管時期的相關併發症。",
            "explanation": "全身麻醉甦醒拔管期可能發生的呼吸道併發症包括上呼吸道阻塞、吸入性肺炎、支氣管痙攣以及「負壓性肺水腫」（negative pressure pulmonary edema，通常由於喉痙攣時強力吸氣產生胸腔極大負壓所致）。正壓性肺水腫通常不是拔管甦醒期的典型併發症，因此A選項不是相關併發症。",
            "flashcard_front": "全身麻醉甦醒 / 拔管併發症 / 喉痙攣 / 負壓性肺水腫 / 支氣管痙攣",
            "flashcard_back": "拔管期用力吸氣受阻會引發負壓性肺水腫，而非正壓性肺水腫；其餘阻塞與痙攣皆為常見併發症。",
            "flashcard_summary": "全身麻醉拔管併發症 -> 全麻甦醒拔管期若發生氣道阻塞吸氣受阻，會引發負壓性肺水腫而非正壓性肺水腫。"
        },
        {
            "question_id": "109-2_medicine-6_002",
            "question_number": 2,
            "correct_answer": "C",
            "category_group": "醫學（六）",
            "category": "麻醉科",
            "category_confidence": "high",
            "key_point": "術中神經監測儀的應用與藥物對腦波的影響。",
            "explanation": "術中使用神經監測（如SSEP、MEP、EMG）能及時發現脊髓手術中的神經損傷。麻醉中維持生理恆定與適當麻醉深度能提升監測效度。在靜脈藥物中，ketamine會增強腦電圖（EEG）的活性，而巴比妥類（barbiturates）則會顯著抑制腦波活性，兩者對腦波的影響截然相反，因此C選項錯誤。",
            "flashcard_front": "術中神經監測 / SSEP 與 MEP / 麻醉藥物腦波影響 / Ketamine / Barbiturates",
            "flashcard_back": "Ketamine 與 Barbiturates 對腦電圖（EEG）的影響相反，前者興奮腦波，後者抑制腦波。",
            "flashcard_summary": "麻醉藥物對腦波的影響 -> 術中監測時，Ketamine 興奮腦波而 Barbiturates 抑制腦波，兩者對腦電圖的影響並不類似。"
        },
        {
            "question_id": "109-2_medicine-6_003",
            "question_number": 3,
            "correct_answer": "B",
            "category_group": "醫學（六）",
            "category": "麻醉科",
            "category_confidence": "high",
            "key_point": "混合靜脈血氧飽和度（SvO2）的臨床監測意義與影響因素。",
            "explanation": "在大手術中，經由肺動脈導管測得的混合靜脈血氧飽和度（SvO2）反映全身組織氧氣供需的平衡，SvO2 降低代表組織灌流不足或氧需求劇增，與術後後遺症密切相關，因此B選項正確。SpO2 > 90% 不代表組織不缺氧（若伴隨重度貧血或低心輸出量）。發燒和疼痛控制不佳會使身體氧氣消耗量增加，進而導致 SvO2 「降低」而非升高。",
            "flashcard_front": "混合靜脈血氧飽和度 (SvO2) / 組織氧氣供需 / 發燒與疼痛 / SpO2 限制",
            "flashcard_back": "SvO2 是全身氧供需平衡指標，發燒與疼痛因增加氧耗會使其降低；SpO2 正常不保證組織不缺氧。",
            "flashcard_summary": "SvO2 與組織氧供 -> SvO2 反映組織氧氣平衡，發燒及疼痛會因氧耗增加而降低 SvO2，術中 SvO2 降低預後較差。"
        },
        {
            "question_id": "109-2_medicine-6_004",
            "question_number": 4,
            "correct_answer": "C",
            "category_group": "醫學（六）",
            "category": "麻醉科",
            "category_confidence": "high",
            "key_point": "吸入性麻醉劑的理化與生理特性。",
            "explanation": "最低肺泡濃度（MAC）是指在一個大氣壓下，能使 50% 患者在皮膚劃刀刺激下不產生肢體動作的肺泡麻醉劑濃度。Desflurane 在血和組織中溶解度極低，能快速誘導與甦醒，但若迅速增加其吸入濃度會刺激交感神經，常導致暫時性心率加快（tachycardia）和血壓上升，而非心率下降，故C選項錯誤。Sevoflurane 由於氣味溫和且誘導迅速，是吸入誘導的首選。",
            "flashcard_front": "吸入性麻醉 / 最低肺泡濃度 (MAC) / Desflurane / 心率加快 / Sevoflurane 誘導",
            "flashcard_back": "快速增加 desflurane 濃度會刺激交感神經導致心跳加快而非減慢；MAC 預防 50% 劃刀動作。",
            "flashcard_summary": "吸入麻醉劑心血管效應 -> 快速調高 desflurane 濃度會刺激交感神經，引起心跳過速及高血壓。"
        },
        {
            "question_id": "109-2_medicine-6_005",
            "question_number": 5,
            "correct_answer": "C",
            "category_group": "醫學（六）",
            "category": "麻醉科",
            "category_confidence": "high",
            "key_point": "靜脈麻醉劑的受體藥理與生理作用。",
            "explanation": "Benzodiazepine（BZD）類藥物是藉由與 GABAA 受體結合產生作用，flumazenil 為其特異性拮抗劑。BZD 會降低呼吸中樞對 CO2 的敏感性，並且會「降低」腦部血流量與腦耗氧量（CMRO2），因此C選項中「增加腦耗氧量」的敘述錯誤。Ketamine 則為非競爭性 NMDA 受體拮抗劑，能產生分離性麻醉。",
            "flashcard_front": "靜脈麻醉藥 / Benzodiazepine / Flumazenil / 腦耗氧量 / Ketamine / NMDA",
            "flashcard_back": "BZD 類藥物會減少腦部耗氧量（CMRO2）與腦血流量；Ketamine 則是抑制 NMDA 通道。",
            "flashcard_summary": "靜脈麻醉劑與腦代謝 -> Benzodiazepines 會降低腦部的耗氧量與血流量，並降低呼吸對二氧化碳的敏感度。"
        },
        {
            "question_id": "109-2_medicine-6_006",
            "question_number": 6,
            "correct_answer": "D",
            "category_group": "醫學（六）",
            "category": "麻醉科",
            "category_confidence": "high",
            "key_point": "非去極性肌肉鬆弛劑作用恢復的監測指標。",
            "explanation": "評估患者從非去極性肌肉鬆弛劑作用中恢復的最客觀、最精準指標是四聯刺激（Train-of-four, TOF），當 TOF ratio 大於 0.9 時，代表自主呼吸與氣道保護反射已安全恢復。臨床指標如潮氣容積、呼吸速率及吸氣負壓雖然常用，但它們容易受到麻醉劑殘留、疼痛或二氧化碳蓄積等其他因素影響，不夠特異。",
            "flashcard_front": "肌肉鬆弛劑恢復 / 非去極性 / 四聯刺激 (TOF) / TOF ratio 0.9 / 潮氣容積 / 吸氣負壓",
            "flashcard_back": "四聯刺激（TOF）是評估肌鬆劑恢復最精確的指標，TOF ratio >0.9 提示可安全拔管。",
            "flashcard_summary": "肌肉鬆弛劑恢復監測 -> 評估非去極性肌鬆劑恢復的黃金指標是四聯刺激（TOF），比臨床呼吸指標更具特異性。"
        },
        {
            "question_id": "109-2_medicine-6_007",
            "question_number": 7,
            "correct_answer": "C",
            "category_group": "醫學（六）",
            "category": "麻醉科",
            "category_confidence": "high",
            "key_point": "門診手術麻醉（Ambulatory Anesthesia）的術前評估與術後風險。",
            "explanation": "門診手術麻醉中，抽菸（smoking）是術後噁心嘔吐（PONV）的「保護因子」，抽菸患者發生 PONV 的風險反而比不抽菸者低，因此C選項敘述錯誤。門診手術術前評估通常不需常規做無症狀的實驗室檢查；早產兒的術後呼吸暫停風險高，其門診手術可行性需依受孕後週數（通常需大於50-60週）評估；使用多模式止痛（如合併局部阻滯）能有效減少鴉片類藥物使用。",
            "flashcard_front": "門診手術麻醉 / 術前常規檢查 / 早產兒受孕後週數 / 術後噁心嘔吐 (PONV) / 多模式止痛",
            "flashcard_back": "抽菸者發生 PONV 的風險較低（為保護因子）；早產兒是否適合門診手術需看受孕後週數。",
            "flashcard_summary": "門診麻醉與PONV風險 -> 抽菸者發生術後噁心嘔吐的機率較低；嬰幼兒需依受孕後週數評估門診手術安全性。"
        },
        {
            "question_id": "109-2_medicine-6_008",
            "question_number": 8,
            "correct_answer": "C",
            "category_group": "醫學（六）",
            "category": "麻醉科",
            "category_confidence": "high",
            "key_point": "病患自控式止痛（PCA）的藥物使用與反饋機制。",
            "explanation": "病患自控式止痛（PCA）可以提供及時且高效的止痛效果，並且因為其內在的負反饋機制（病人因疼痛按壓，若疼痛緩解或鎮靜則停止按壓），能有效降低止痛藥的總劑量與副作用。PCA 常用的藥物除了嗎啡（morphine）之外，還經常使用芬太尼（fentanyl）、右美托咪啶或加入非類固醇抗炎藥等其他非嗎啡藥物進行配方，因此C選項「不宜使用嗎啡以外藥物」錯誤。",
            "flashcard_front": "病患自控式止痛 (PCA) / 負反饋機制 / 藥物種類 / 嗎啡 / 總劑量降低",
            "flashcard_back": "PCA可混合使用芬太尼等多種非嗎啡類鴉片藥物或輔助劑；其為負反饋機制能減少用藥量。",
            "flashcard_summary": "PCA藥物與機制 -> PCA能降低用藥總劑量並及時止痛，藥物不限於嗎啡，常用芬太尼等其他鴉片類藥物。"
        },
        {
            "question_id": "109-2_medicine-6_009",
            "question_number": 9,
            "correct_answer": "C",
            "category_group": "醫學（六）",
            "category": "其他",
            "category_confidence": "high",
            "key_point": "重症與休克病人的營養支持原則。",
            "explanation": "對於處於敗血性休克（septic shock）等血流動力學不穩定的重症病人，在休克未糾正及循環未穩定前，過早給予營養支持（尤其是腸胃道灌食）會大幅增加非咬合性非缺血性腸壞死（腸缺血）的風險，因此「越早給予預後越好」的敘述是錯誤的。在循環穩定後才開始逐步給藥。對於一般營養良好的術後患者，補充足夠水分與電解質下可容許禁食達7天；胃排空不良者可用十二指腸管餵食以防吸入。",
            "flashcard_front": "重症營養 / 敗血性休克 / 早期灌食 / 腸缺血 / 胃排空不良 / 十二指腸管",
            "flashcard_back": "敗血性休克循環未穩定前，不宜過早給予營養灌食，以防消化道灌注不足引發腸壞死。",
            "flashcard_summary": "敗血性休克與營養支持 -> 敗血性休克患者須等血流動力學穩定後再行營養支持，過早灌食易引發急性腸缺血。"
        },
        {
            "question_id": "109-2_medicine-6_010",
            "question_number": 10,
            "correct_answer": "B",
            "category_group": "醫學（六）",
            "category": "眼科",
            "category_confidence": "high",
            "key_point": "年齡相關黃斑部退化（AMD）的流行病學與危險因子。",
            "explanation": "年齡相關黃斑部退化（AMD）的主要危險因子是年齡，抽菸及遺傳史也顯著增加發病風險。在種族差異方面，白人（Caucasians）的發病率與視力喪失風險明顯高於黑人（Blacks），黑人相對不易發生此病所致的視力喪失，因此B選項敘述錯誤。",
            "flashcard_front": "黃斑部退化 (AMD) / 年齡與抽菸 / 家族遺傳 / 種族差異 / 白人與黑人",
            "flashcard_back": "白人患年齡相關黃斑部退化及發生視力喪失的機率高於黑人；抽菸與年齡為關鍵危險因子。",
            "flashcard_summary": "黃斑部退化危險因子 -> 年齡相關黃斑部退化在白人中的盛行率與視力受損率顯著高於黑人。"
        },
        {
            "question_id": "109-2_medicine-6_011",
            "question_number": 11,
            "correct_answer": "C",
            "category_group": "醫學（六）",
            "category": "眼科",
            "category_confidence": "high",
            "key_point": "高度近視病理性病變與手術侷限性。",
            "explanation": "高度近視（定義為度數大於600度或眼軸長大於26.5 mm）會引發眼軸拉長與視網膜變薄，進而增加格子狀退化、視網膜裂孔及黃斑部病變等風險。角膜雷射手術（如LASIK）僅改變角膜弧度，白內障手術僅置換人工水晶體，兩者皆無法改變高度近視患者眼軸拉長與視網膜退化的解剖本質，因此「利用白內障置換能將風險去除」的說法錯誤。黃斑部視網膜分裂症用抗VEGF注射通常無效，常需手術治療。",
            "flashcard_front": "高度近視 / 雷射近視手術 / 白內障置換 / 視網膜剝離風險 / 眼軸拉長",
            "flashcard_back": "角膜雷射或白內障手術均無法改變高度近視引起的眼軸拉長與視網膜病變風險。",
            "flashcard_summary": "高度近視手術與風險 -> 高度近視引起的眼底病變風險，無法藉由近視雷射或白內障手術來去除。"
        },
        {
            "question_id": "109-2_medicine-6_012",
            "question_number": 12,
            "correct_answer": "D",
            "category_group": "醫學（六）",
            "category": "眼科",
            "category_confidence": "high",
            "key_point": "影響角膜弧度變化的角膜變性與發育異常。",
            "explanation": "圓錐角膜（keratoconus，角膜向前錐狀突起）、球狀角膜（keratoglobus，角膜全局性變薄凸出）與清澈型角膜邊緣變性（pellucid marginal degeneration，角膜下方局部變薄突出）皆屬於非發炎性的角膜變薄性疾病，會導致角膜弧度與散光發生劇烈變化。而角膜內皮細胞失養症（如 Fuchs dystrophy）主要是內皮細胞泵浦功能失調導致角膜水腫混濁，其病變主要與角膜厚度及透光度有關，不以角膜弧度變化為特徵。",
            "flashcard_front": "角膜弧度變化 / 圓錐角膜 / 球狀角膜 / 清澈型角膜邊緣變性 / 內皮細胞失養症",
            "flashcard_back": "圓錐角膜、球狀角膜與清澈邊緣變性均會改變角膜弧度；內皮失養症則主要引發水腫。",
            "flashcard_summary": "角膜病變與弧度變化 -> 圓錐角膜、球狀角膜及 PMD 會導致角膜弧度異常；內皮失養症則主導水腫而非弧度變化。"
        },
        {
            "question_id": "109-2_medicine-6_013",
            "question_number": 13,
            "correct_answer": "D",
            "category_group": "醫學（六）",
            "category": "眼科",
            "category_confidence": "high",
            "key_point": "上鞏膜炎（Episcleritis）的臨床特徵與系統性關聯。",
            "explanation": "上鞏膜炎是一種常見的表淺性鞏膜炎症，多好發於中青年人（而非老年人），雖然它通常具有自限性，但很容易反覆發作。大約 30% 的上鞏膜炎患者可能合併有系統性免疫風濕性疾病（如類風濕性關節炎、紅斑性狼瘡等），因此D選項正確。上鞏膜炎很少會轉變成病變更深、更嚴重的真正鞏膜炎（scleritis）。",
            "flashcard_front": "上鞏膜炎 (episcleritis) / 好發年齡 / 反覆發作 / 鞏膜炎轉變 / 免疫風濕疾病",
            "flashcard_back": "上鞏膜炎好發於中青年人，易復發，極少轉為深層鞏膜炎，約三成患者合併免疫風濕病。",
            "flashcard_summary": "上鞏膜炎特徵與關聯 -> 上鞏膜炎多見於中青年且易復發，部分病例與全身免疫風濕疾病相關。"
        },
        {
            "question_id": "109-2_medicine-6_014",
            "question_number": 14,
            "correct_answer": "A",
            "category_group": "醫學（六）",
            "category": "眼科",
            "category_confidence": "high",
            "key_point": "白內障術後晚期視力模糊的最常見原因。",
            "explanation": "術後一年以上出現無痛性、漸進性的視力模糊，最常見的原因是後發性白內障（posterior capsule opacification, PCO），這是由於殘留的晶體上皮細胞在後囊膜上增生與機化所致，臨床上可以用 Nd:YAG 雷射後囊切開術快速治療。黃斑部水腫、眼內炎及眼瞼下垂多發生在術後早期，或在此情境下較少見。",
            "flashcard_front": "白內障術後一年 / 視力漸漸模糊 / 後發性白內障 (PCO) / 晶體上皮細胞增生 / YAG雷射",
            "flashcard_back": "白內障術後晚期視力下降最常見原因是後發性白內障，臨床上首選 Nd:YAG 雷射治療。",
            "flashcard_summary": "白內障術後晚期模糊原因 -> 白內障手術後一年視力再度模糊，最常見原因為後發性白內障（PCO）。"
        },
        {
            "question_id": "109-2_medicine-6_015",
            "question_number": 15,
            "correct_answer": "B",
            "category_group": "醫學（六）",
            "category": "眼科",
            "category_confidence": "high",
            "key_point": "原發性隅角開放性青光眼（POAG）的治療目標與眼壓控制。",
            "explanation": "隅角開放性青光眼（POAG）的治療目標是維持患者有生之年能有足夠的視覺功能。眼壓波動是青光眼惡化的重要危險因子，而治療失敗常因患者對降眼壓眼藥水的順從性不佳所致。在臨床上，降眼壓目標是個體化的「目標眼壓」（target pressure），對於許多患者（如正常眼壓性青光眼），即使眼壓控制在 21 mmHg 以下，視神經仍可能持續惡化，因此B選項將眼壓一律定在21 mmHg以下是不適當的。",
            "flashcard_front": "隅角開放性青光眼 (POAG) / 目標眼壓 / 21 mmHg 限制 / 眼壓波動 / 藥物順從性",
            "flashcard_back": "青光眼治療眼壓需個體化，不能以單一 21 mmHg 作為不會惡化的標準，需考慮目標眼壓與波動。",
            "flashcard_summary": "青光眼治療眼壓控制 -> 青光眼控制目標為個體化目標眼壓，單純將眼壓維持於 21 mmHg 以下仍有惡化風險。"
        }
    ]
}

# ==================== BATCH 002 (MEDICINE 6) ====================
batches_data["109-2_medicine-6_batch-002"] = {
    "dataset_id": "109-2_medicine-6",
    "batch_id": "109-2_medicine-6_batch-002",
    "items": [
        {
            "question_id": "109-2_medicine-6_016",
            "question_number": 16,
            "correct_answer": "A",
            "category_group": "醫學（六）",
            "category": "眼科",
            "category_confidence": "high",
            "key_point": "兒童弱視成因與調節力及近視遠點的關係。",
            "explanation": "兒童的睫狀肌調節力（accommodation power）非常強（遠高於成人），因此A選項中「小孩子的調節力比成人弱」的解釋是錯誤的。遠視 400 度的兒童由於在任何距離看物都需要強力調節，極易因持續模糊而產生弱視；近視 400 度的兒童其遠點（far point）在眼前 25 公分（100/4 = 25 cm），不戴眼鏡時近距離看物仍可獲得清晰像，故較不易發生弱視。弱視患者常有擁擠現象（crowding phenomenon），因此使用單一視標測得的視力通常比整行視力表好。",
            "flashcard_front": "兒童弱視 / 400度遠視與近視 / 調節力強弱 / 遠點計算 / 擁擠現象 (crowding)",
            "flashcard_back": "兒童調節力遠強於成人；400度近視遠點在25公分，看近清晰因此較不易弱視。",
            "flashcard_summary": "弱視成因與兒童調節力 -> 兒童調節力極強而非比成人弱；近視者因遠點近看近清晰，比遠視者更不易弱視。"
        },
        {
            "question_id": "109-2_medicine-6_017",
            "question_number": 17,
            "correct_answer": "D",
            "category_group": "醫學（六）",
            "category": "眼科",
            "category_confidence": "high",
            "key_point": "兒童與老年人外展神經麻痺（CN VI palsy）的病因評估差異。",
            "explanation": "老年人因糖尿病或高血壓引起的外展神經麻痺多為微血管缺血所致，通常可先觀察三個月等待其自行恢復。然而，兒童外展神經麻痺常是由於顱內腫瘤（如腦幹膠質瘤）、外傷、感染或腦壓升高等嚴重病理原因所致，絕不可「先觀察三個月」，必須立即進行積極的影像學與神經學調查，故D選項錯誤。外展神經受損需檢查聽力、角膜敏感度及鼻咽部以排除聽神經瘤或鼻咽癌壓迫，並檢查視神經乳頭排除腦壓升高。",
            "flashcard_front": "外展神經麻痺 (CN VI) / 兒童與老人差異 / 先觀察三個月 / 聽神經瘤 / 鼻咽癌 / 腦壓升高",
            "flashcard_back": "兒童外展神經麻痺多有嚴重顱內病因，必須立即積極檢查，不可像老年缺血性麻痺般先觀察三個月。",
            "flashcard_summary": "兒童外展神經麻痺評估 -> 兒童 CN VI 麻痺通常提示嚴重腦部病變，不可採老年患者之觀察三個月策略，需立即檢查。"
        },
        {
            "question_id": "109-2_medicine-6_018",
            "question_number": 18,
            "correct_answer": "B",
            "category_group": "醫學（六）",
            "category": "眼科",
            "category_confidence": "high",
            "key_point": "惡性脈絡膜黑色素瘤（Choroidal Melanoma）的遠端轉移部位。",
            "explanation": "惡性脈絡膜黑色素瘤是成人最常見的眼內原發性惡性腫瘤。該腫瘤因為眼內無淋巴管，主要經由血流進行遠端轉移，且具有高度的嗜肝性，最容易轉移到肝臟（liver），高達90%以上的轉移病患會出現肝臟受累。轉移至肺臟、皮膚或胰臟的機率明顯低於肝臟。",
            "flashcard_front": "脈絡膜黑色素瘤 / 眼內惡性腫瘤 / 遠端血流轉移 / 轉移首選部位 / 肝臟",
            "flashcard_back": "脈絡膜黑色素瘤極易經血流轉移，且首選且最常見轉移部位為肝臟（>90%）。",
            "flashcard_summary": "脈絡膜黑色素瘤轉移 -> 脈絡膜黑色素瘤主要通過血流擴散，最常轉移至肝臟。"
        },
        {
            "question_id": "109-2_medicine-6_019",
            "question_number": 19,
            "correct_answer": "C",
            "category_group": "醫學（六）",
            "category": "耳鼻喉科",
            "category_confidence": "high",
            "key_point": "局部晚期牙齦鱗狀上皮癌的治療原則。",
            "explanation": "該 41 歲男性患有左下側牙齦鱗狀上皮癌，腫瘤 3 公分且左側頸部有 3 顆固定、無法移動的腫塊，在無遠端轉移下屬於局部晚期口腔癌。此類病患的最合適治療為先進行廣泛性口內病灶切除及左側頸部淋巴腺廓清手術，術後再根據病理報告中的危險因子（如安全邊緣、淋巴結外侵犯等）給予輔助性放射線治療或同步放化療（CCRT）。直接首選放化療或先化療再手術並非目前標準流程。",
            "flashcard_front": "牙齦鱗狀細胞癌 / 口腔癌 / 頸部淋巴結固定 / 手術加輔助放化療 / 治療順序",
            "flashcard_back": "局部晚期口腔癌首選切除原發灶加頸部淋巴廓清術，術後再評估給予輔助放療或放化療。",
            "flashcard_summary": "局部晚期口腔癌治療流程 -> 口腔鱗狀細胞癌伴頸淋巴轉移，標準治療為先手術切除與淋巴廓清，術後加做輔助放化療。"
        },
        {
            "question_id": "109-2_medicine-6_020",
            "question_number": 20,
            "correct_answer": "A",
            "category_group": "醫學（六）",
            "category": "耳鼻喉科",
            "category_confidence": "high",
            "key_point": "急性病毒性與細菌性鼻竇炎的臨床鑑別指標。",
            "explanation": "區分急性病毒性鼻竇炎與急性細菌性鼻竇炎最重要且最實用的臨床指標是「病程長短」（duration）。急性病毒性鼻竇炎多在 7 到 10 天內自行改善；而細菌性鼻竇炎通常定義為症狀持續超過 10 天且無改善跡象，或者出現「雙重惡化」（double sickening，即感冒好轉後症狀又突然加重）。分泌物濃稠度、發燒與否以及影像學檢查（如X光或CT的黏膜增厚）在兩者中常有重疊，無法有效區分。",
            "flashcard_front": "急性鼻竇炎 / 病毒性與細菌性 / 鑑別診斷 / 病程長短 / 雙重惡化",
            "flashcard_back": "區分病毒與細菌性鼻竇炎首靠病程，細菌性通常症狀持續超過10天或有雙重惡化表現。",
            "flashcard_summary": "鼻竇炎病毒與細菌區分 -> 區分急性病毒與細菌性鼻竇炎最主要依靠病程時間，細菌性常持續大於10天或有二度惡化。"
        },
        {
            "question_id": "109-2_medicine-6_021",
            "question_number": 21,
            "correct_answer": "B",
            "category_group": "醫學（六）",
            "category": "耳鼻喉科",
            "category_confidence": "high",
            "key_point": "鼻閥（Nasal Valve）的解剖結構與生理意義。",
            "explanation": "鼻閥分為內鼻閥和外鼻閥。外鼻閥由鼻小柱、鼻翼邊緣及鼻檻構成；內鼻閥位於鼻前庭後約 1.3 公分處，由鼻中膈、上側鼻軟骨下緣及下鼻甲前頭構成。內鼻閥（internal nasal value，而非外鼻閥）是整個鼻腔通道中最狹窄的地方，佔了鼻氣流阻力的大部分，因此B選項錯誤。Modified Cottle maneuver 可用於評估內鼻閥狹窄引起的鼻塞。",
            "flashcard_front": "鼻閥解剖 / 外鼻閥組成 / 內鼻閥位置 / 氣道最窄處 / Cottle maneuver",
            "flashcard_back": "內鼻閥（而非外鼻閥）是整個鼻道阻力最大、最狹窄的地方；外鼻閥由鼻小柱、鼻翼邊緣與鼻檻構成。",
            "flashcard_summary": "鼻閥解剖最窄處 -> 內鼻閥是整個鼻道最狹窄、阻力最大的部位，外鼻閥並非最窄處。"
        },
        {
            "question_id": "109-2_medicine-6_022",
            "question_number": 22,
            "correct_answer": "A",
            "category_group": "醫學（六）",
            "category": "耳鼻喉科",
            "category_confidence": "high",
            "key_point": "後天性喉氣管狹窄的病因、分類與影像診斷。",
            "explanation": "後天性喉氣管狹窄的常見病因包括氣管內插管壓迫、外傷、氣管切開術及頭頸部放射治療等，因此A選項正確。在狹窄部位中，以聲門下狹窄（subglottic stenosis）最為常見（因環狀軟骨處是氣道最狹窄且為完整環狀結構易受壓迫）。聲門上狹窄主要影響吸氣期，引起吸氣期喘鳴，而非吐氣期。影像學檢查的首選通常是高解析度電腦斷層（CT）而非磁振造影（MRI）。",
            "flashcard_front": "後天性喉氣管狹窄 / 插管與外傷 / 最常見部位 / 聲門下狹窄 / 喘鳴期 / CT與MRI",
            "flashcard_back": "後天性喉氣管狹窄最常見病因為氣管插管壓迫，以聲門下狹窄最常見；影像學首選電腦斷層。",
            "flashcard_summary": "喉氣管狹窄病因與診斷 -> 後天性喉氣管狹窄多由插管或外傷引起，以聲門下區最常見，首選電腦斷層診斷。"
        },
        {
            "question_id": "109-2_medicine-6_023",
            "question_number": 23,
            "correct_answer": "C",
            "category_group": "醫學（六）",
            "category": "耳鼻喉科",
            "category_confidence": "high",
            "key_point": "聲帶結節（Vocal Cord Nodules）的病因與首選治療。",
            "explanation": "喉內視鏡顯示雙側聲帶前三分之一與後三分之二交界處有對稱性的小突起，這是典型的聲帶結節（俗稱歌手結節或教師結節）。這通常是由於發聲方式不當或過度用聲引起的，因此最合適且首選的治療是安排語言治療（voice therapy）以改善說話方式和用聲習慣。常規使用抗生素無效；顯微手術切除僅保留給經語言治療無效且已纖維化的成熟結節。",
            "flashcard_front": "教師 / 聲音品質差 / 喉內視鏡 / 雙側對稱聲帶結節 / 語言治療 / 手術切除",
            "flashcard_back": "聲帶結節（歌手結節）病因發聲不當，首選治療為改善發聲習慣的語言治療，不應直接手術。",
            "flashcard_summary": "聲帶結節治療原則 -> 教師常見的雙側聲帶結節，首選治療為語言治療以改善發聲，手術非首選。"
        },
        {
            "question_id": "109-2_medicine-6_024",
            "question_number": 24,
            "correct_answer": "D",
            "category_group": "醫學（六）",
            "category": "耳鼻喉科",
            "category_confidence": "high",
            "key_point": "下咽部淋巴引流的解剖途徑。",
            "explanation": "下咽部環狀軟骨後區（post-cricoid area）的淋巴引流主要是穿過環甲膜引流至氣管旁淋巴結（Level VI，喉返神經旁），因此D選項正確。梨狀窩內側壁與下端的淋巴引流主要穿過甲狀舌骨膜引流至頸部深淋巴結第II、III、IV區，而非第V區。下咽後壁區的淋巴引流會先流向後咽淋巴結（retropharyngeal nodes），再引流至頸部深淋巴結。",
            "flashcard_front": "下咽部淋巴引流 / 梨狀窩 / 環狀軟骨後區 / 氣管旁淋巴結 (Level VI) / 後咽淋巴結",
            "flashcard_back": "環狀軟骨後區淋巴經環甲膜引流至氣管旁淋巴結（Level VI）；下咽後壁會引流至後咽淋巴結。",
            "flashcard_summary": "下咽淋巴引流路徑 -> 環狀軟骨後區淋巴引流至氣管旁淋巴結；梨狀窩主要引流至第 II-IV 區而非第 V 區。"
        },
        {
            "question_id": "109-2_medicine-6_025",
            "question_number": 25,
            "correct_answer": "C",
            "category_group": "醫學（六）",
            "category": "耳鼻喉科",
            "category_confidence": "high",
            "key_point": "急性中耳炎（AOM）的耳鏡診斷。",
            "explanation": "六歲病童發燒且單耳疼痛悶脹，耳鏡檢查顯示鼓膜充血、膨出且中耳腔積膿，且錘骨柄指向 11 點鐘方向、光錐位於 7-8 點鐘方向，這是左耳鼓膜的特徵，因此最可能的診斷為左側急性中耳炎（C選項）。慢性中耳炎通常以鼓膜穿孔、流膿為主要特徵，而非急性發熱鼓膜充血膨出。",
            "flashcard_front": "兒童發燒耳痛 / 耳鏡檢查 / 鼓膜充血膨出 / 積膿 / 錘骨柄與光錐位置 / 左側急性中耳炎",
            "flashcard_back": "鼓膜充血膨出伴隨發燒耳痛為急性中耳炎；依解剖標誌（光錐在左下）可判定病變位於左耳。",
            "flashcard_summary": "急性中耳炎耳鏡判定 -> 發燒耳痛伴鼓膜充血膨出為急性中耳炎，依光錐與錘骨柄指向判定為左耳病變。"
        },
        {
            "question_id": "109-2_medicine-6_026",
            "question_number": 26,
            "correct_answer": "D",
            "category_group": "醫學（六）",
            "category": "耳鼻喉科",
            "category_confidence": "high",
            "key_point": "正常耳的鼓室圖（Tympanogram）類型。",
            "explanation": "根據上題，病童的病變在左耳（左側急性中耳炎），而右耳是正常的（去年聽力檢查正常，且此次無症狀）。因此，右耳的鼓室圖應該表現為正常的 Type A 曲線（即在正常大氣壓附近有 compliance 尖峰）。選項 D 對應 Type A 鼓室圖。",
            "flashcard_front": "正常耳 / 鼓室圖 (tympanogram) / 鼓膜活動度 / Type A / Type B",
            "flashcard_back": "正常耳朵的鼓室圖應呈現 Type A 曲線，代表中耳壓力正常且鼓膜活動度良好。",
            "flashcard_summary": "正常耳鼓室圖 -> 正常耳朵在中耳無積液或壓力的狀況下，其鼓室圖檢測應呈現 Type A 曲線。"
        },
        {
            "question_id": "109-2_medicine-6_027",
            "question_number": 27,
            "correct_answer": "A",
            "category_group": "醫學（六）",
            "category": "耳鼻喉科",
            "category_confidence": "high",
            "key_point": "急性中耳炎積液的鼓室圖（Tympanogram）類型。",
            "explanation": "病童左耳確診為急性中耳炎且腔內有積膿，這會導致鼓膜活動度嚴重受限，鼓室圖會呈現一條沒有明顯尖峰的扁平曲線，即 Type B 鼓室圖。選項 A 對應 Type B 鼓室圖，是中耳積液（effusion）或鼓膜穿孔的特徵。",
            "flashcard_front": "急性中耳炎 / 中耳積液 / 鼓膜活動受限 / 鼓室圖 / Type B / 扁平曲線",
            "flashcard_back": "中耳炎伴積液時，鼓膜因阻力增加而活動受限，鼓室圖會呈現無峰的扁平 Type B 曲線。",
            "flashcard_summary": "中耳積液鼓室圖 -> 急性中耳炎伴中耳腔積液時，左耳鼓室圖檢測會呈現無尖峰的 Type B 曲線。"
        },
        {
            "question_id": "109-2_medicine-6_028",
            "question_number": 28,
            "correct_answer": "C",
            "category_group": "醫學（六）",
            "category": "婦產科",
            "category_confidence": "high",
            "key_point": "分娩會陰裂傷的分級標準。",
            "explanation": "分娩引起的會陰裂傷分為四度。第一度裂傷僅累及會陰皮膚 and 陰道黏膜；第二度裂傷累及會陰體及會陰肌肉，但未傷及肛門括約肌；第三度裂傷（本題情況）累及了肛門括約肌（anal sphincter）；第四度裂傷則進一步累及直腸黏膜與直腸腔。因此，累及肛門括約肌屬於第三度裂傷。",
            "flashcard_front": "分娩 / 會陰裂傷 / 陰道黏膜與皮膚 / 肛門括約肌 / 裂傷分級",
            "flashcard_back": "裂傷波及肛門括約肌但未傷及直腸黏膜，屬於第三度會陰裂傷；傷及直腸黏膜則為第四度。",
            "flashcard_summary": "會陰裂傷分級 -> 會陰裂傷若累及肛門括約肌但無直腸黏膜破損，臨床上歸類為第三度裂傷。"
        },
        {
            "question_id": "109-2_medicine-6_029",
            "question_number": 29,
            "correct_answer": "B",
            "category_group": "醫學（六）",
            "category": "婦產科",
            "category_confidence": "high",
            "key_point": "重度子癇前症（Preeclampsia with severe features）的臨床診斷標準。",
            "explanation": "重度子癇前症的診斷指標包括血壓持續大於160/110 mmHg、肝功能異常、血小板減少、腎功能受損（如血清肌酸酐升高）及胎兒生長遲滯（FGR）等。在尿蛋白方面，重度子癇前症在舊標準中定義為24小時尿蛋白大於5克（5000 mg）；而24小時尿蛋白僅100 mg 屬於正常範圍（正常孕婦小於300 mg/day），根本不符合子癇前症的診斷，更非重度症狀，因此B選項最合適。",
            "flashcard_front": "重度子癇前症 / 診斷標準 / 血壓 >160/110 / 尿蛋白定量 / 肝功能 / 胎兒生長遲滯",
            "flashcard_back": "24小時尿蛋白 100 mg 屬於正常範圍；重度子癇前症常伴隨高血壓、肝腎異常及大量尿蛋白。",
            "flashcard_summary": "重度子癇前症診斷 -> 24小時尿蛋白 100 mg 屬於正常，重度子癇前症應伴隨大量尿蛋白或器官受損。"
        },
        {
            "question_id": "109-2_medicine-6_030",
            "question_number": 30,
            "correct_answer": "B",
            "category_group": "醫學（六）",
            "category": "婦產科",
            "category_confidence": "high",
            "key_point": "懷孕期間子宮底高度（Fundal Height）與孕週關係。",
            "explanation": "懷孕期間，子宮底高度是評估胎兒發育的常用指標。大約在懷孕20週時，子宮底高度會剛好到達肚臍水平（umbilicus）。在懷孕12週時，子宮底剛好超出恥骨聯合；16週時介於恥骨與肚臍中間；24週時約在肚臍上二指；36週時到達劍突下。",
            "flashcard_front": "孕期檢查 / 子宮底高度 (fundal height) / 肚臍水平 / 正常懷孕週數",
            "flashcard_back": "正常懷孕大約在 20 週時，子宮底高度會剛好上升並到達肚臍（umbilicus）水平。",
            "flashcard_summary": "子宮底高度與孕週 -> 懷孕期間子宮底高度到達肚臍水平時，對應的正常妊娠週數約為 20 週。"
        }
    ]
}

for batch_id, data in batches_data.items():
    output_path = f"reports/gemini_outputs/{batch_id}.json"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Successfully generated {output_path}")
