import os
import json

# Ensure reports/gemini_outputs exists
os.makedirs("reports/gemini_outputs", exist_ok=True)

batches_data = {}

# ----------------- BATCH 001 -----------------
batches_data["111-2_medicine-5_batch-001"] = {
  "dataset_id": "111-2_medicine-5",
  "batch_id": "111-2_medicine-5_batch-001",
  "items": [
    {
      "question_id": "111-2_medicine-5_001",
      "question_number": 1,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "神經外科",
      "category_confidence": "high",
      "key_point": "分辨外傷性顱內出血與自發性高血壓腦中風的特徵。",
      "explanation": "右側頭部著地易因對衝性損傷導致左側腦部受傷，並非僅右側受傷。硬腦膜上出血多由中腦膜動脈破裂引起，而非靜脈。與老人相比，小孩大腦無萎縮且橋靜脈不易拉伸，故較不易發生硬腦膜下出血。若電腦斷層顯示出血位於基底核或小腦等高血壓好發處，應高度懷疑高血壓性腦中風而非外傷引起。",
      "flashcard_front": "跌倒顱內出血 / 基底核與小腦 / 硬腦膜上與下出血 / 衝擊與對衝傷",
      "flashcard_back": "基底核或小腦出血多為高血壓性中風；硬腦膜上出血多為中腦膜動脈破裂；老人比小孩易發生硬腦膜下出血。",
      "flashcard_summary": "跌倒顱內出血 / 基底核與小腦 -> 基底核或小腦出血多為高血壓性中風；硬腦膜上出血多為中腦膜動脈破裂；老人比小孩易發生硬腦膜下出血。"
    },
    {
      "question_id": "111-2_medicine-5_002",
      "question_number": 2,
      "correct_answer": "A",
      "category_group": "醫學（五）",
      "category": "胸腔外科",
      "category_confidence": "high",
      "key_point": "利用呼吸音鑑別張力性氣胸與心包膜積血。",
      "explanation": "張力性氣胸與心包膜積血（心包填塞）都會導致低血壓及頸靜脈鼓脹等休克表徵。張力性氣胸會有單側胸部呼吸音顯著減弱或消失的現象，而心包膜積血患者的雙側呼吸音通常正常，這點最具有鑑別價值。心音遙遠是心包填塞的特徵，但臨床上呼吸音的有無更易於快速判定。",
      "flashcard_front": "頸靜脈鼓脹 / 低血壓 / 張力性氣胸 / 心包膜積血 / 鑑別診斷",
      "flashcard_back": "張力性氣胸伴隨單側呼吸音減弱或消失，而心包膜積血患者雙側呼吸音通常對稱且正常。",
      "flashcard_summary": "頸靜脈鼓脹 / 低血壓 -> 張力性氣胸伴隨單側呼吸音減弱或消失，而心包膜積血患者雙側呼吸音通常對稱且正常。"
    },
    {
      "question_id": "111-2_medicine-5_003",
      "question_number": 3,
      "correct_answer": "A",
      "category_group": "醫學（五）",
      "category": "外科概論",
      "category_confidence": "high",
      "key_point": "掌握常見癌症標靶治療之標的基因與配對。",
      "explanation": "治療多發性骨髓瘤（myeloma）常使用蛋白酶體抑制劑或免疫調節劑，而 Bcr-Abl 基因是慢性骨髓性白血病（CML）的特異性標靶標的（如 imatinib），兩者配對錯誤。大腸直腸癌常針對 EGFR，乳癌針對 HER2，腎細胞癌則針對 VEGF，均為正確的標靶對應。",
      "flashcard_front": "癌症標靶治療 / Bcr-Abl 基因 / 多發性骨髓瘤 / 大腸直腸癌 / 腎細胞癌",
      "flashcard_back": "Bcr-Abl 基因突變與慢性骨髓性白血病（CML）相關，而非多發性骨髓瘤。",
      "flashcard_summary": "癌症標靶治療 / Bcr-Abl 基因 -> Bcr-Abl 基因突變與慢性骨髓性白血病（CML）相關，而非多發性骨髓瘤。"
    },
    {
      "question_id": "111-2_medicine-5_004",
      "question_number": 4,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "一般外科",
      "category_confidence": "high",
      "key_point": "識別胰臟癌的危險因子。",
      "explanation": "抽菸、Peutz-Jeghers 症候群與遺傳性胰臟炎皆是已證實的胰臟癌危險因子。縮胃手術（sleeve gastrectomy）是一種減重手術，可用於改善肥胖及代謝性疾病，並非胰臟癌的危險因子。",
      "flashcard_front": "胰臟癌 / 危險因子 / Peutz-Jeghers症候群 / 遺傳性胰臟炎 / 縮胃手術",
      "flashcard_back": "抽菸、遺傳性胰臟炎與 Peutz-Jeghers 症候群為胰臟癌危險因子；縮胃手術則非危險因子。",
      "flashcard_summary": "胰臟癌 / 危險因子 -> 抽菸、遺傳性胰臟炎與 Peutz-Jeghers 症候群為胰臟癌危險因子；縮胃手術則非危險因子。"
    },
    {
      "question_id": "111-2_medicine-5_005",
      "question_number": 5,
      "correct_answer": "B",
      "category_group": "醫學（五）",
      "category": "外科概論",
      "category_confidence": "high",
      "key_point": "掌握高壓氧治療組織缺氧傷口之先決條件。",
      "explanation": "高壓氧治療是透過提高血液中溶解氧的濃度來改善末梢組織缺氧。若傷口局部沒有暢通的血液循環，高壓氧便無法將氧氣輸送到受損組織發揮作用，因此確認局部血液循環暢通是治療的首要先決條件。控制合併症或細菌感染雖重要，但非主要物理先決條件。",
      "flashcard_front": "高壓氧治療 / 組織缺氧傷口 / 先決條件 / 血液循環",
      "flashcard_back": "高壓氧改善組織缺氧的先決條件是確認局部血液循環暢通，否則高氧血液無法抵達組織。",
      "flashcard_summary": "高壓氧治療 / 組織缺氧傷口 -> 高壓氧改善組織缺氧的先決條件是確認局部血液循環暢通，否則高氧血液無法抵達組織。"
    },
    {
      "question_id": "111-2_medicine-5_006",
      "question_number": 6,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "移植外科",
      "category_confidence": "high",
      "key_point": "辨識腎臟移植後免疫抑制劑副作用與病毒感染的關聯。",
      "explanation": "腎臟移植後淋巴增生性病變（PTLD）主要與愛潑斯坦-巴爾病毒（EBV）的活化密切相關，而非人類乳突病毒（HPV）。術後預防性使用 acyclovir/valgancyclovir 可有效降低巨細胞病毒（CMV）感染率；多瘤病毒相關性腎病（PVAN）是由 BK 病毒引起，會導致移植腎功能喪失，皆為正確描述。",
      "flashcard_front": "腎臟移植 / 免疫抑制劑 / PTLD / HPV / EBV / BKV",
      "flashcard_back": "移植後淋巴增生性病變（PTLD）是由 EBV 活化引起，而非 HPV；BK 病毒與多瘤病毒腎病相關。",
      "flashcard_summary": "腎臟移植 / 免疫抑制劑 / PTLD -> 移植後淋巴增生性病變（PTLD）是由 EBV 活化引起，而非 HPV；BK 病毒與多瘤病毒腎病相關。"
    },
    {
      "question_id": "111-2_medicine-5_007",
      "question_number": 7,
      "correct_answer": "C",
      "category_group": "醫學（五）",
      "category": "一般外科",
      "category_confidence": "high",
      "key_point": "掌握胃癌發生的危險因子。",
      "explanation": "胃癌的風險因子包括幽門螺旋桿菌感染、低社經階層、高鹽與醃漬飲食及吸菸等。低社經階層人士因飲食保存習慣或幽門螺旋桿菌盛行率高，為胃癌的高風險群。高脂高蛋白飲食通常與大腸癌較相關，且女性的胃癌發生率顯著低於男性。",
      "flashcard_front": "胃癌 / 高風險因素 / 社經階層 / 性別比例 / 高鹽飲食",
      "flashcard_back": "低社經階層是胃癌的高風險因素；男性發生率高於女性；高鹽醃漬飲食為危險因子，而高脂高蛋白無直接相關。",
      "flashcard_summary": "胃癌 / 高風險因素 -> 低社經階層是胃癌的高風險因素；男性發生率高於女性；高鹽醃漬飲食為危險因子，而高脂高蛋白無直接相關。"
    },
    {
      "question_id": "111-2_medicine-5_008",
      "question_number": 8,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "神經外科",
      "category_confidence": "high",
      "key_point": "熟記中樞神經生殖細胞瘤（germinoma）的流行病學特徵。",
      "explanation": "生殖細胞瘤占小兒原發性腦瘤約 1~2%，九成以上發生在 20 歲以前，且約有一半長在松果體區（pineal region）。然而，在松果體區的生殖細胞瘤男女發生比例有極大的偏差，男性顯著多於女性（約 10:1），而非 1:1。",
      "flashcard_front": "生殖細胞瘤 / Pineal region / 男女比例 / 好發年齡",
      "flashcard_back": "松果體區的生殖細胞瘤男女比例約為 10:1（男性顯著多於女性），而非 1:1。",
      "flashcard_summary": "生殖細胞瘤 / Pineal region -> 松果體區的生殖細胞瘤男女比例約為 10:1（男性顯著多於女性），而非 1:1。"
    },
    {
      "question_id": "111-2_medicine-5_009",
      "question_number": 9,
      "correct_answer": "B",
      "category_group": "醫學（五）",
      "category": "神經外科",
      "category_confidence": "high",
      "key_point": "區分兒童腦幹膠質瘤不同部位的預後與臨床表現。",
      "explanation": "兒童腦幹膠質瘤中，腦橋膠質瘤（pontine glioma，主要是 diffuse intrinsic pontine glioma, DIPG）具有高度侵犯性，中位存活期極短且預後極差，而中腦（midbrain/tectal）膠質瘤通常生長緩慢，預後較佳。頂蓋膠質瘤易壓迫中腦導水管導致水腦症，腦橋膠質瘤則常因腦橋核受損表現為多發性腦神經麻痺。",
      "flashcard_front": "兒童腦幹膠質瘤 / Pontine glioma / Midbrain glioma / 存活率 / 水腦症",
      "flashcard_back": "中腦（midbrain/tectal）膠質瘤預後較佳；腦橋膠質瘤（pontine glioma）預後極差，存活率顯著低於中腦膠質瘤。",
      "flashcard_summary": "兒童腦幹膠質瘤 / Pontine glioma -> 中腦（midbrain/tectal）膠質瘤預後較佳；腦橋膠質瘤（pontine glioma）預後極差，存活率顯著低於中腦膠質瘤。"
    },
    {
      "question_id": "111-2_medicine-5_010",
      "question_number": 10,
      "correct_answer": "A",
      "category_group": "醫學（五）",
      "category": "神經外科",
      "category_confidence": "high",
      "key_point": "理解自發性顱內出血的急診處理原則與病因。",
      "explanation": "腦部自發性出血的病因包括高血壓、動靜脈畸形、澱粉樣血管病變及轉移瘤出血等。臨床上並非所有顱內出血都需要立即進行手術移除血塊（如出血量小、神經學症狀穩定或有其他手術禁忌者，可採取內科保守觀察與藥物控制）。因此「必須立即手術移除血塊」過於絕對，是本題的錯誤敘述。",
      "flashcard_front": "顱內出血 / 急診處理 / 手術指引 / 澱粉樣血管病變 / 轉移瘤出血",
      "flashcard_back": "顱內血塊並非皆需立即手術，應視出血量、臨床症狀與神經功能決定是否先採取保守治療。",
      "flashcard_summary": "顱內出血 / 急診處理 -> 顱內血塊並非皆需立即手術，應視出血量、臨床症狀與神經功能決定是否先採取保守治療。"
    },
    {
      "question_id": "111-2_medicine-5_011",
      "question_number": 11,
      "correct_answer": "C",
      "category_group": "醫學（五）",
      "category": "骨科",
      "category_confidence": "high",
      "key_point": "掌握退化性頸椎疾病的治療預期與手術風險。",
      "explanation": "急性頸椎神經根病變首選保守治療（休息、藥物、復健），無效時才考慮手術。前位椎間盤切除手術可能傷及喉返神經，導致聲音沙啞、嗆咳或吞嚥困難。手術主要目的為減壓及穩定脊椎以防惡化，但無法保證「全部」症狀都能獲得完全改善。",
      "flashcard_front": "頸椎退化 / 前位手術風險 / 聲音沙啞 / 保守治療 / 手術預期效果",
      "flashcard_back": "前位頸椎手術有喉返神經損傷風險；手術無法保證肩頸與神經症狀能「全部」改善或恢復。",
      "flashcard_summary": "頸椎退化 / 前位手術風險 -> 前位頸椎手術有喉返神經損傷風險；手術無法保證肩頸與神經症狀能「全部」改善或恢復。"
    },
    {
      "question_id": "111-2_medicine-5_012",
      "question_number": 12,
      "correct_answer": "A",
      "category_group": "醫學（五）",
      "category": "神經外科",
      "category_confidence": "high",
      "key_point": "分辨 Chiari I 與 Chiari II 畸形的解剖病理學差異。",
      "explanation": "Chiari I 畸形的特徵是小腦扁桃體（cerebellar tonsils）向下疝出枕骨大孔 5mm 以上，而延髓向下疝出並常合併脊髓膜膨出則是 Chiari II 畸形的特徵。Chiari I 畸形可藉由枕骨下骨切除與第一頸椎椎弓減壓手術治療，且可能合併四肢麻木無力及脊髓空洞症。",
      "flashcard_front": "Chiari I 畸形 / 小腦扁桃體 / 延髓疝出 / 脊髓空洞症 / 枕骨下減壓",
      "flashcard_back": "Chiari I 特徵為小腦扁桃體向下疝出枕骨大孔，而非延髓；延髓下疝主要見於 Chiari II 畸形。",
      "flashcard_summary": "Chiari I 畸形 / 小腦扁桃體 -> Chiari I 特徵為小腦扁桃體向下疝出枕骨大孔，而非延髓；延髓下疝主要見於 Chiari II 畸形。"
    },
    {
      "question_id": "111-2_medicine-5_013",
      "question_number": 13,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "神經外科",
      "category_confidence": "high",
      "key_point": "掌握外傷性頸動脈海綿竇瘻管（CCF）的特徵與治療。",
      "explanation": "外傷後出現眼球突出、泛紅、疼痛及視力減弱，是頸動脈海綿竇瘻管（CCF）的典型表現。外傷性 CCF 通常是由內頸動脈破裂引起的「高流速（high flow）」瘻管。目前臨床首選且最主要的治療方式為血管內介入治療（如血管內栓塞術），往往不需傳統開刀手術。",
      "flashcard_front": "頸動脈海綿竇瘻管 / 外傷性 / 高流速 / 血管介入治療 / 眼球突出",
      "flashcard_back": "外傷性 CCF 通常為高流速瘻管，目前首選血管內介入栓塞治療，大多不需傳統開刀手術。",
      "flashcard_summary": "頸動脈海綿竇瘻管 / 外傷性 -> 外傷性 CCF 通常為高流速瘻管，目前首選血管內介入栓塞治療，大多不需傳統開刀手術。"
    },
    {
      "question_id": "111-2_medicine-5_014",
      "question_number": 14,
      "correct_answer": "A",
      "category_group": "醫學（五）",
      "category": "整形外科",
      "category_confidence": "high",
      "key_point": "熟記顯微皮瓣移植手術後的照護原則與栓塞機理。",
      "explanation": "抗凝血劑（如 heparin）在顯微手術後因會增加局部血腫與出血風險，並非臨床上的常規必用藥物，通常以精密的手術技術與密切監測為關鍵。皮瓣栓塞多發生於術後48小時內，及早發現重探成功率高；血管縫合太鬆導致中膜外露會活化凝血機制，皆為正確描述。",
      "flashcard_front": "顯微自由皮瓣 / 術後栓塞 / 肝素 / 48小時內 / 微血管充盈",
      "flashcard_back": "術後肝素抗凝非顯微皮瓣手術的常規必用藥；大部分栓塞發生在術後48小時內。",
      "flashcard_summary": "顯微自由皮瓣 / 術後栓塞 -> 術後肝素抗凝非顯微皮瓣手術的常規必用藥；大部分栓塞發生在術後48小時內。"
    },
    {
      "question_id": "111-2_medicine-5_015",
      "question_number": 15,
      "correct_answer": "C",
      "category_group": "醫學（五）",
      "category": "整形外科",
      "category_confidence": "high",
      "key_point": "掌握手部屈肌腱的區域劃分與解剖生理特點。",
      "explanation": "手部屈肌腱分為五個區域，其中第一、二、四區的肌腱有滑膜鞘包覆（第二區俗稱無人地帶），腕隧道則屬於第四區。沒有 paratenon 且有滑膜鞘包覆的區域因主要靠內在癒合且血流供應較差，其受傷後的癒合速度較慢，而非較快。",
      "flashcard_front": "屈肌腱損傷 / 區域劃分 / 滑膜鞘 / 腱周組織 / 癒合速度",
      "flashcard_back": "屈肌腱分為五區，無 paratenon 的滑膜鞘區（如第二區）因血供較差，癒合速度較慢。",
      "flashcard_summary": "屈肌腱損傷 / 區域劃分 -> 屈肌腱分為五區，無 paratenon 的滑膜鞘區（如第二區）因血供較差，癒合速度較慢。"
    }
  ]
}

# ----------------- BATCH 002 -----------------
batches_data["111-2_medicine-5_batch-002"] = {
  "dataset_id": "111-2_medicine-5",
  "batch_id": "111-2_medicine-5_batch-002",
  "items": [
    {
      "question_id": "111-2_medicine-5_016",
      "question_number": 16,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "整形外科",
      "category_confidence": "high",
      "key_point": "掌握唇顎裂序列治療與修復手術的時間表。",
      "explanation": "唇顎裂的修復時間表一般為：出生後1~2個月進行唇黏合術，3~6個月進行唇與初步鼻修復術，10~12個月（1歲左右）進行顎修復術以利發育。而二期的唇或鼻修正手術（lip or nose revision）通常在學齡前（約4~5歲）或甚至骨骼發育定型後進行，並非限制必須在5歲前完成。",
      "flashcard_front": "唇顎裂手術 / 唇黏合術 / 顎修復術 / 二次修正時程",
      "flashcard_back": "顎修復術在10~12個月進行；二次唇鼻修正術通常在學齡前或骨骼定型後進行，非限制5歲前。",
      "flashcard_summary": "唇顎裂手術 / 唇黏合術 -> 顎修復術在10~12個月進行；二次唇鼻修正術通常在學齡前或骨骼定型後進行，非限制5歲前。"
    },
    {
      "question_id": "111-2_medicine-5_017",
      "question_number": 17,
      "correct_answer": "C",
      "category_group": "醫學（五）",
      "category": "整形外科",
      "category_confidence": "high",
      "key_point": "選擇葡萄酒色斑（先天性微血管畸形）之最適雷射治療。",
      "explanation": "葡萄酒色斑（port wine stain）屬於先天性微血管畸形，富含氧合血紅素。脈衝式染料雷射（pulsed-dye laser, PDL）的波長（如585-595 nm）能被血紅素特異性吸收，可精準破壞病變微血管，是目前治療葡萄酒色斑的首選雷射。其他如 CO2 或紅寶石雷射較不具此血管選擇性。",
      "flashcard_front": "葡萄酒色斑 / 微血管畸形 / 脈衝式染料雷射 / 氧合血紅素",
      "flashcard_back": "治療葡萄酒色斑首選脈衝式染料雷射（PDL），因其波長能被血紅素特異性吸收以破壞微血管。",
      "flashcard_summary": "葡萄酒色斑 / 微血管畸形 -> 治療葡萄酒色斑首選脈衝式染料雷射（PDL），因其波長能被血紅素特異性吸收以破壞微血管。"
    },
    {
      "question_id": "111-2_medicine-5_018",
      "question_number": 18,
      "correct_answer": "B",
      "category_group": "醫學（五）",
      "category": "整形外科",
      "category_confidence": "high",
      "key_point": "掌握皮膚移植（skin graft）存活的階段與失敗高峰期。",
      "explanation": "皮膚移植存活經歷三個階段：血漿吸收期（imbibition）、血管吻合期（inosculation）與血管再生期（revascularization）。其中「黏合期 / 血管吻合期（inosculation）」是移植皮膚與受區血管開始接通的關鍵，此時若有血腫、剪力或感染，極易中斷微血管重建，是移植失敗最常見的時期。",
      "flashcard_front": "皮膚移植 / 浸潤期 / 黏合期 (inosculation) / 血管再生 / 移植失敗",
      "flashcard_back": "血管吻合期（黏合期）為新生血管對接關鍵，最易受血腫或剪力影響而導致皮膚移植失敗。",
      "flashcard_summary": "皮膚移植 / 浸潤期 -> 血管吻合期（黏合期）為新生血管對接關鍵，最易受血腫或剪力影響而導致皮膚移植失敗。"
    },
    {
      "question_id": "111-2_medicine-5_019",
      "question_number": 19,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "整形外科",
      "category_confidence": "high",
      "key_point": "掌握乳癌切除後乳房重建（breast reconstruction）的時程與原則。",
      "explanation": "乳房重建可分為立即重建與延遲重建（delayed reconstruction）。延遲重建是等乳癌完全切除且後續治療（如化療、放療）結束或病情穩定後進行，但重建時機因人而異（通常在化療或放療後數月即可考慮），並不需要死板地「等 2 年」。義乳重建並不會妨礙局部復發的偵測。",
      "flashcard_front": "乳房重建 / 義乳與復發偵測 / 延遲重建 / 重建時機",
      "flashcard_back": "延遲重建指乳癌控制後再進行，其時程依個案輔助治療計畫而定，不需硬性等待2年。",
      "flashcard_summary": "乳房重建 / 義乳與復發偵測 -> 延遲重建指乳癌控制後再進行，其時程依個案輔助治療計畫而定，不需硬性等待2年。"
    },
    {
      "question_id": "111-2_medicine-5_020",
      "question_number": 20,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "心臟外科",
      "category_confidence": "high",
      "key_point": "掌握主動脈瓣置換手術（AVR）的臨床適應症。",
      "explanation": "主動脈瓣置換的適應症包括有症狀的嚴重狹窄、中度狹窄合併需要進行冠狀動脈繞道手術者，以及無症狀的嚴重狹窄合併左心室收縮功能小於50%者。臨床上，若患者完全無症狀且左心室功能正常，僅為了「預防猝死」而盲目進行置換手術是不適當的，因為手術本身伴隨一定風險。",
      "flashcard_front": "主動脈瓣置換 (AVR) / 適應症 / 無症狀嚴重狹窄 / 左心室收縮功能 / 預防猝死",
      "flashcard_back": "無症狀且左心室功能正常（LVEF>=50%）的嚴重主動脈瓣狹窄患者，不應常規進行 AVR 來預防猝死。",
      "flashcard_summary": "主動脈瓣置換 (AVR) / 適應症 -> 無症狀且左心室功能正常（LVEF>=50%）的嚴重主動脈瓣狹窄患者，不應常規進行 AVR 來預防猝死。"
    },
    {
      "question_id": "111-2_medicine-5_021",
      "question_number": 21,
      "correct_answer": "C",
      "category_group": "醫學（五）",
      "category": "心臟外科",
      "category_confidence": "high",
      "key_point": "掌握主動脈瘤（aortic aneurysm）的分類、病因與脊髓保護。",
      "explanation": "真假動脈瘤因破裂風險大不相同，手術適應症並不相同；感染性動脈瘤（mycotic aneurysm）最常見的感染源是細菌（如 Salmonella 或 Staphylococcus），而非真菌（fungus）。在胸腹主動脈瘤修補手術中，使用腦脊髓液引流（CSF drainage）可以有效降低脊髓內壓，提供脊髓保護效果，降低截癱風險。直徑3公分的主動脈瘤，通常半年至一年追蹤即可，無須每三個月密集追蹤。",
      "flashcard_front": "主動脈瘤 / 假性動脈瘤 / 感染性動脈瘤 / 腦脊髓液引流 / 脊髓保護",
      "flashcard_back": "胸腹主動脈瘤手術中使用腦脊髓液引流能降低脊髓內壓，達到預防脊髓缺血癱瘓的保護作用。",
      "flashcard_summary": "主動脈瘤 / 假性動脈瘤 -> 胸腹主動脈瘤手術中使用腦脊髓液引流能降低脊髓內壓，達到預防脊髓缺血癱瘓的保護作用。"
    },
    {
      "question_id": "111-2_medicine-5_022",
      "question_number": 22,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "心臟外科",
      "category_confidence": "high",
      "key_point": "區分深層靜脈栓塞（DVT）的危險因子與解剖病因。",
      "explanation": "深層靜脈栓塞的危險因子包括高齡、癌症、手術史及遺傳性抗凝血因子（如 protein S 或 antithrombin III）缺乏，成因可用 Virchow's triad 解釋。May-Thurner syndrome（左總髂靜脈受右總髂動脈壓迫）是導致左下肢 DVT 的「重要病因」，而非 DVT 的「併發症」。",
      "flashcard_front": "深層靜脈栓塞 (DVT) / Virchow's triad / 抗凝因子缺乏 / May-Thurner症候群",
      "flashcard_back": "May-Thurner syndrome（左總髂靜脈受右總髂動脈壓迫）是導致下肢血栓的病因，而非 DVT 併發症。",
      "flashcard_summary": "深層靜脈栓塞 (DVT) / Virchow's triad -> May-Thurner syndrome（左總髂靜脈受右總髂動脈壓迫）是導致下肢血栓的病因，而非 DVT 併發症。"
    },
    {
      "question_id": "111-2_medicine-5_023",
      "question_number": 23,
      "correct_answer": "C",
      "category_group": "醫學（五）",
      "category": "心臟外科",
      "category_confidence": "high",
      "key_point": "理解瓣膜狹窄的手術指引與新興介入技術現況。",
      "explanation": "主動脈瓣狹窄（AS）開口小於 1 cm2 且有症狀，或二尖瓣狹窄（MS）開口小於 1.5 cm2 且氣球擴張效果不佳，均是置換瓣膜的指引。相較於主動脈瓣經導管置換（TAVR）技術的成熟與廣泛使用，經導管二尖瓣置換（TMVR）因二尖瓣環不規則且解剖複雜，目前尚未像 TAVR 那樣成熟並作為常規首選，仍多以修補或外科手術為主。",
      "flashcard_front": "主動脈瓣狹窄 / 二尖瓣狹窄 / 瓣膜置換指引 / TAVR / TMVR",
      "flashcard_back": "經導管主動脈瓣置換（TAVR）已非常成熟，但經導管二尖瓣置換（TMVR）技術解剖複雜，尚未如前者成熟。",
      "flashcard_summary": "主動脈瓣狹窄 / 二尖瓣狹窄 -> 經導管主動脈瓣置換（TAVR）已非常成熟，但經導管二尖瓣置換（TMVR）技術解剖複雜，尚未如前者成熟。"
    },
    {
      "question_id": "111-2_medicine-5_024",
      "question_number": 24,
      "correct_answer": "B",
      "category_group": "醫學（五）",
      "category": "心臟外科",
      "category_confidence": "high",
      "key_point": "掌握縮窄性心包膜炎（constrictive pericarditis）的診斷特徵。",
      "explanation": "患者表現為雙心房擴大、收縮功能正常、中心靜脈壓高（22 mmHg）以及心包膜顯著增厚（5 mm，正常<2mm）。心導管壓力曲線出現「square-root sign」（舒張早期急速下降後維持平坦的 dip-and-plateau），是限制性舒張受阻的典型表現，結合心包膜厚度，診斷首選縮窄性心包膜炎。",
      "flashcard_front": "縮窄性心包膜炎 / square-root sign / 心包膜增厚 / 中心靜脈壓升高",
      "flashcard_back": "心包膜增厚（>2mm）伴隨心導管 square-root sign 與中心靜脈壓升高，高度提示縮窄性心包膜炎。",
      "flashcard_summary": "縮窄性心包膜炎 / square-root sign -> 心包膜增厚（>2mm）伴隨心導管 square-root sign 與中心靜脈壓升高，高度提示縮窄性心包膜炎。"
    },
    {
      "question_id": "111-2_medicine-5_025",
      "question_number": 25,
      "correct_answer": "C",
      "category_group": "醫學（五）",
      "category": "胸腔外科",
      "category_confidence": "high",
      "key_point": "掌握食道破裂的外科急診處理原則。",
      "explanation": "食道破裂是高死亡率的急症，核心原則是清除污染、廣泛引流、控制感染源及早期營養支持。若食道破裂發現較晚（延遲性發現），因局部組織發炎壞死嚴重，此時強行手術修補破裂處極易崩裂失敗，此時「置放足夠引流管」與「控制感染」比強行修補食道破裂處更為關鍵與重要。",
      "flashcard_front": "食道破裂 / 延遲性發現 / 處理原則 / 局部修補 / 廣泛引流",
      "flashcard_back": "延遲發現的食道破裂因組織壞死發炎，引流與控制感染比強行修補破裂處更重要，修補非首要。",
      "flashcard_summary": "食道破裂 / 延遲性發現 -> 延遲發現的食道破裂因組織壞死發炎，引流與控制感染比強行修補破裂處更重要，修補非首要。"
    },
    {
      "question_id": "111-2_medicine-5_026",
      "question_number": 26,
      "correct_answer": "C",
      "category_group": "醫學（五）",
      "category": "胸腔外科",
      "category_confidence": "high",
      "key_point": "了解巴瑞特氏食道炎（Barrett's esophagus）的病理生理與治療。",
      "explanation": "巴瑞特氏食道炎是胃食道逆流導致食道下段的鱗狀上皮被「柱狀上記」取代的化生病變，主要是往食道上方（而非胃內）生長，且會增加罹患食道「腺癌」而非鱗狀上皮癌的機會。對於長期藥物治療無效且反覆發作的患者，胃之抗逆流手術（如 Nissen fundoplication）是改善逆流症狀的有效手段。",
      "flashcard_front": "巴瑞特氏食道炎 / 胃食道逆流 / 上皮化生 / 抗逆流手術 / 食道腺癌",
      "flashcard_back": "Barrett's 增加的是食道腺癌風險；長期藥物治療無效的病患可考慮抗逆流手術改善症狀。",
      "flashcard_summary": "巴瑞特氏食道炎 / 胃食道逆流 -> Barrett's 增加的是食道腺癌風險；長期藥物治療無效的病患可考慮抗逆流手術改善症狀。"
    },
    {
      "question_id": "111-2_medicine-5_027",
      "question_number": 27,
      "correct_answer": "B",
      "category_group": "醫學（五）",
      "category": "胸腔外科",
      "category_confidence": "high",
      "key_point": "掌握肺腺癌原位癌（adenocarcinoma in situ, AIS）的病理生長型態。",
      "explanation": "根據世界衛生組織分類，肺腺癌原位癌（AIS）定義為直徑≦3 cm 的侷限性小腫瘤，其病理特徵是癌細胞完全沿著既有的肺泡壁生長，無基質、血管或胸膜侵犯，這種特殊的病理生長型態稱為「伏壁型（lepidic）」。其他如腺泡型、乳頭型或固體型皆屬於侵襲性腺癌的病理型態。",
      "flashcard_front": "肺原位腺癌 (AIS) / 病理診斷 / 伏壁型 (lepidic) / 肺泡壁生長 / 無侵襲性",
      "flashcard_back": "肺腺癌原位癌（AIS）的癌細胞沿肺泡壁生長，不具侵襲性，病理型態稱為伏壁型（lepidic）。",
      "flashcard_summary": "肺原位腺癌 (AIS) / 病理診斷 -> 肺腺癌原位癌（AIS）的癌細胞沿肺泡壁生長，不具侵襲性，病理型態稱為伏壁型（lepidic）。"
    },
    {
      "question_id": "111-2_medicine-5_028",
      "question_number": 28,
      "correct_answer": "A",
      "category_group": "醫學（五）",
      "category": "胸腔外科",
      "category_confidence": "high",
      "key_point": "掌握氣管腺樣囊狀癌（adenoid cystic carcinoma, ACC）的臨床特點。",
      "explanation": "腺樣囊狀癌（ACC）是氣管常見的原發性惡性腫瘤之一。它通常生長緩慢，但具有高度局部侵犯性（常侵犯氣管並沿神經周圍擴散），早期症狀可能不明顯，但常因阻塞氣道而引起喘鳴（stridor）。早期治療以手術切除配合術後放射線治療為主，而非以化學治療為主。",
      "flashcard_front": "腺樣囊狀癌 (ACC) / 氣管腫瘤 / 生長速度 / 喘鳴 / 手術治療",
      "flashcard_back": "氣管腺樣囊狀癌生長緩慢但具局部侵犯性，常累及氣管並造成喘鳴，首選治療為手術切除。",
      "flashcard_summary": "腺樣囊狀癌 (ACC) / 氣管腫瘤 -> 氣管腺樣囊狀癌生長緩慢但具局部侵犯性，常累及氣管並造成喘鳴，首選治療為手術切除。"
    },
    {
      "question_id": "111-2_medicine-5_029",
      "question_number": 29,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "胸腔外科",
      "category_confidence": "high",
      "key_point": "熟悉頸胸部外傷的評估與急診處置原則。",
      "explanation": "頸部穿刺傷即使食道位置偏後，仍有受損可能，必須仔細檢查評估。胸部穿刺物若留在胸壁上，絕不可在送醫前現場移除，以免失去壓迫止血效果引發大出血。胸部鈍傷無外傷痕跡仍可能發生逆發性氣血胸。皮下氣腫及縱隔腔氣腫常為氣體外漏徵象，必須高度警惕氣管或食道受損。",
      "flashcard_front": "頸胸部外傷 / 穿刺物拔除 / 縱隔腔氣腫 / 食道氣管受損 / 皮下氣腫",
      "flashcard_back": "穿刺物不可現場拔除以防大出血；皮下氣腫及縱隔腔氣腫提示可能合併氣管或食道破裂。",
      "flashcard_summary": "頸胸部外傷 / 穿刺物拔除 -> 穿刺物不可現場拔除以防大出血；皮下氣腫及縱隔腔氣腫提示可能合併氣管或食道破裂。"
    },
    {
      "question_id": "111-2_medicine-5_030",
      "question_number": 30,
      "correct_answer": "B",
      "category_group": "醫學（五）",
      "category": "胸腔外科",
      "category_confidence": "high",
      "key_point": "辨識常見縱隔腔囊腫（mediastinal cyst）的病理生理特徵。",
      "explanation": "原發性縱隔腔囊腫多數無症狀。支氣管囊腫（bronchogenic cyst）是最常見的縱隔腔囊腫，通常「不」與支氣管腔直接相通，若相通易反覆繼發感染。心包膜囊腫（pericardial cyst）好發於右側心膈角，腸源性囊腫（enteric cyst）通常生長在食道旁，皆為正確描述。",
      "flashcard_front": "縱隔腔囊腫 / 支氣管囊腫 / 腸源性囊腫 / 心膈角 / 管道相通",
      "flashcard_back": "支氣管囊腫（bronchogenic cyst）為最常見縱隔囊腫，但解剖上通常不與支氣管腔相通。",
      "flashcard_summary": "縱隔腔囊腫 / 支氣管囊腫 -> 支氣管囊腫（bronchogenic cyst）為最常見縱隔囊腫，但解剖上通常不與支氣管腔相通。"
    }
  ]
}

# ----------------- BATCH 003 -----------------
batches_data["111-2_medicine-5_batch-003"] = {
  "dataset_id": "111-2_medicine-5",
  "batch_id": "111-2_medicine-5_batch-003",
  "items": [
    {
      "question_id": "111-2_medicine-5_031",
      "question_number": 31,
      "correct_answer": "A",
      "category_group": "醫學（五）",
      "category": "一般外科",
      "category_confidence": "high",
      "key_point": "掌握脾臟切除術（splenectomy）的適應症與術後風險。",
      "explanation": "嚴重肝硬化患者合併血小板低下是因門脈高壓引起的充血性脾腫大與破壞增加，其根本治療非切除脾臟（手術會增加門靜脈血栓風險，且無法改善肝病預後），因此 A 敘述錯誤。外傷或手術醫源性損傷是脾切除主因；術後因失去巨噬功能，對肺炎鏈球菌等莢膜菌感染風險上升，且兒童發生 OPSI 風險高於成人。",
      "flashcard_front": "脾臟切除 / 肝硬化血小板低下 / 莢膜形細菌 / 猛爆型感染 (OPSI)",
      "flashcard_back": "肝硬化血小板低下不應以切除脾臟為改善預後的常規手段；脾切除後易發生莢膜菌引起的 OPSI。",
      "flashcard_summary": "脾臟切除 / 肝硬化血小板低下 -> 肝硬化血小板低下不應以切除脾臟為改善預後的常規手段；脾切除後易發生莢膜菌引起的 OPSI。"
    },
    {
      "question_id": "111-2_medicine-5_032",
      "question_number": 32,
      "correct_answer": "A",
      "category_group": "醫學（五）",
      "category": "一般外科",
      "category_confidence": "high",
      "key_point": "掌握短腸症候群（short bowel syndrome）的病因與危險因子。",
      "explanation": "正常成人小腸長度約300~600公分，空腸切除200公分後，剩餘的小腸長度仍然足夠，通常不會導致短腸症（一般剩餘小腸少於150~200公分時才容易發生）。而切除迴盲瓣、合併全結腸切除或本身有克隆氏症（反覆發炎需多次切除），都會顯著增加發生短腸症的風險。",
      "flashcard_front": "短腸症候群 / 空腸切除長度 / 迴盲瓣 / 克隆氏症 / 剩餘小腸",
      "flashcard_back": "空腸切除200公分（剩餘長度足夠）一般非短腸症危險因子；切除迴盲瓣或全結腸則會增加風險。",
      "flashcard_summary": "短腸症候群 / 空腸切除長度 -> 空腸切除200公分（剩餘長度足夠）一般非短腸症危險因子；切除迴盲瓣或全結腸則會增加風險。"
    },
    {
      "question_id": "111-2_medicine-5_033",
      "question_number": 33,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "一般外科",
      "category_confidence": "high",
      "key_point": "掌握肝小葉（liver lobule）的顯微結構與細胞功能。",
      "explanation": "肝小葉通常由中央靜脈為中心，周圍有6個 portal triads 圍繞；易缺血壞死的是 Zone 3（離血供最遠）；肝細胞在 Disse腔側具有豐富的微絨毛以利擴散物質。肝臟星狀細胞（Ito cells）存在於 space of Disse，生理功能為儲存維生素 A，病理下會活化產生膠原蛋白導致肝臟分享，故 D 敘述正確。",
      "flashcard_front": "肝小葉結構 / Disse 腔 / 肝臟星狀細胞 (Ito cells) / 維生素 A / 肝纖維化",
      "flashcard_back": "Stellate cells（Ito cells）位於 space of Disse，主要儲存維生素 A，是肝纖維化的關鍵細胞。",
      "flashcard_summary": "肝小葉結構 / Disse 腔 -> Stellate cells（Ito cells）位於 space of Disse，主要儲存維生素 A，是肝纖維化的關鍵細胞。"
    },
    {
      "question_id": "111-2_medicine-5_034",
      "question_number": 34,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "一般外科",
      "category_confidence": "high",
      "key_point": "熟記外科學上的肝臟分葉與分界解剖。",
      "explanation": "解剖學上利用鐮狀韌帶分界，但外科學功能分葉是利用 Cantlie's line；尾葉（Segment 1）具有獨立的血供與膽道引流，不單純屬於右肝或左肝；功能分區主要以肝靜脈與門靜脈分支的走向為界。Cantlie's line 是指膽囊窩至下腔靜脈左側的連線，為外科學劃分左右肝的功能性邊界。",
      "flashcard_front": "肝臟分葉 / Cantlie's line / 鐮狀韌帶 / 尾葉 (caudate lobe)",
      "flashcard_back": "外科學區分左右肝的功能分界線為 Cantlie's line（膽囊窩至下腔靜脈連線），而非鐮狀韌帶。",
      "flashcard_summary": "肝臟分葉 / Cantlie's line -> 外科學區分左右肝的功能分界線為 Cantlie's line（膽囊窩至下腔靜脈連線），而非鐮狀韌帶。"
    },
    {
      "question_id": "111-2_medicine-5_035",
      "question_number": 35,
      "correct_answer": "C",
      "category_group": "醫學（五）",
      "category": "一般外科",
      "category_confidence": "high",
      "key_point": "掌握小腸腫瘤的良惡性分布與臨床特徵。",
      "explanation": "小腸良性腫瘤最常見為腺瘤或平滑肌瘤，而非脂肪瘤；最常見的惡性腫瘤是腺癌，但主要好發於十二指腸及空腸近端，而非迴腸（迴腸好發神經內分泌瘤及淋巴瘤）。類癌（神經內分泌瘤）若有轉移常引起類癌症候群，若能手術應儘量廓清完全以改善預後。基質瘤（GIST）的預後與腫瘤大小及分裂數均有密切關係。",
      "flashcard_front": "小腸腫瘤 / 腺癌好發部位 / 類癌症候群 / 基質瘤 (GIST) 預後",
      "flashcard_back": "小腸腺癌好發於十二指腸及近端空腸；小腸類癌轉移引發類癌症候群時，應盡量手術切除乾淨。",
      "flashcard_summary": "小腸腫瘤 / 腺癌好發部位 -> 小腸腺癌好發於十二指腸及近端空腸；小腸類癌轉移引發類癌症候群時，應盡量手術切除乾淨。"
    },
    {
      "question_id": "111-2_medicine-5_036",
      "question_number": 36,
      "correct_answer": "C",
      "category_group": "醫學（五）",
      "category": "一般外科",
      "category_confidence": "high",
      "key_point": "掌握胃惡性腫瘤的手術規範與分期原則。",
      "explanation": "胃癌手術精確分期需廓清至少16顆淋巴結；AJCC 1997年後將N分期改為依淋巴結轉移顆數決定；胃的 low-grade MALT 淋巴瘤首選根除幽門螺旋桿菌治療。胃基質瘤（GIST）由於極少經淋巴轉移，其標準手術為胃局部切除（安全距離足夠即可），「不需要」進行常規的淋巴結廓清術，故 C 敘述錯誤。",
      "flashcard_front": "胃基質瘤 (GIST) / 淋巴結廓清 / 胃癌N分期 / MALT 淋巴瘤",
      "flashcard_back": "胃 GIST 的標準治療為局部楔形切除，因極少淋巴轉移，故不需要進行常規淋巴結廓清術。",
      "flashcard_summary": "胃基質瘤 (GIST) / 淋巴結廓清 -> 胃 GIST 的標準治療為局部楔形切除，因極少淋巴轉移，故不需要進行常規淋巴結廓清術。"
    },
    {
      "question_id": "111-2_medicine-5_037",
      "question_number": 37,
      "correct_answer": "C",
      "category_group": "醫學（五）",
      "category": "一般外科",
      "category_confidence": "high",
      "key_point": "熟記急性膽結石胰臟炎之 Ranson 預後指標評估項目。",
      "explanation": "膽結石引起急性胰臟炎的 Ranson criteria 包括：入院時的年齡（>70歲）、白血球數（>18000）、血糖值（>220 mg/dL）、LDH 與 AST 等；以及入院48小時內之血比容下降、BUN 上升、血鈣、鹼缺乏與液體蓄積量。其評估項目中「不包含」總膽紅素（total bilirubin level）。",
      "flashcard_front": "膽結石胰臟炎 / Ranson criteria / 評估項目 / 總膽紅素 / 血糖",
      "flashcard_back": "膽結石胰臟炎的 Ranson 評估指標包括年齡、血糖、白血球等，但不包括總膽紅素。",
      "flashcard_summary": "膽結石胰臟炎 / Ranson criteria -> 膽結石胰臟炎的 Ranson 評估指標包括年齡、血糖、白血球等，但不包括總膽紅素。"
    },
    {
      "question_id": "111-2_medicine-5_038",
      "question_number": 38,
      "correct_answer": "B",
      "category_group": "醫學（五）",
      "category": "一般外科",
      "category_confidence": "high",
      "key_point": "認識胃繞道手術後的傾食症候群（Dumping syndrome）與處理。",
      "explanation": "胃繞道手術後出現胃脹、嘔吐、頭暈、心悸與冒汗，為典型的傾食症候群表現。這是因為胃容積變小且幽門被繞過，導致高滲透壓食物過快進入小腸。此症狀主要透過調整飲食習慣（如少量多餐、乾濕分離、減少高糖食物）即可獲得顯著改善，極少需要藥物或手術干擾。",
      "flashcard_front": "胃繞道手術 / 傾食症候群 (Dumping) / 飲食調整 / 乾濕分離",
      "flashcard_back": "胃繞道術後的傾食症候群多可透過調整飲食習慣（如少量多餐、乾濕分離）改善，不需常規手術。",
      "flashcard_summary": "胃繞道手術 / 傾食症候群 (Dumping) -> 胃繞道術後的傾食症候群多可透過調整飲食習慣（如少量多餐、乾濕分離）改善，不需常規手術。"
    },
    {
      "question_id": "111-2_medicine-5_039",
      "question_number": 39,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "一般外科",
      "category_confidence": "high",
      "key_point": "掌握原發性多醛酮症（Conn's syndrome）的定位診斷工具。",
      "explanation": "原發性多醛酮症的定位檢查包括腎上腺薄切電腦斷層（CT）、NP-59 放射性核種掃描，以及區分單雙側病變的黃金標準選擇性腎上腺靜脈採樣（AVS）。而 MIBG 掃描主要是用來定位診斷「嗜鉻細胞瘤（pheochromocytoma）」，不適用於原發性多醛酮症的檢查。",
      "flashcard_front": "原發性多醛酮症 / 腎上腺靜脈採樣 (AVS) / NP-59 掃描 / MIBG 掃描",
      "flashcard_back": "MIBG 掃描適用於嗜鉻細胞瘤的定位診斷，而非用於原發性多醛酮症的醛酮體瘤。",
      "flashcard_summary": "原發性多醛酮症 / 腎上腺靜脈採樣 (AVS) -> MIBG 掃描適用於嗜鉻細胞瘤的定位診斷，而非用於原發性多醛酮症的醛酮體瘤。"
    },
    {
      "question_id": "111-2_medicine-5_040",
      "question_number": 40,
      "correct_answer": "B",
      "category_group": "醫學（五）",
      "category": "一般外科",
      "category_confidence": "high",
      "key_point": "掌握副甲狀腺癌（parathyroid cancer）的臨床診斷線索。",
      "explanation": "患者出現極高血鈣（14.5 mg/dL）與極高 PTH（525 pg/mL），臨床上伴隨頸部腫塊與聲音沙啞（提示腫塊侵犯或壓迫喉返神經），這是惡性副甲狀腺癌（parathyroid cancer）的典型表現。良性的副甲狀腺腺瘤雖然也會引起高血鈣，但極少造成喉返神經壓迫導致聲音沙啞。",
      "flashcard_front": "高血鈣 / 副甲狀腺素升高 / 頸部腫塊 / 聲音沙啞 / 副甲狀腺癌",
      "flashcard_back": "嚴重高血鈣及 PTH 顯著升高，若伴有聲音沙啞（喉返神經受侵犯），最可能診斷為副甲狀腺癌。",
      "flashcard_summary": "高血鈣 / 副甲狀腺素升高 -> 嚴重高血鈣及 PTH 顯著升高，若伴有聲音沙啞（喉返神經受侵犯），最可能診斷為副甲狀腺癌。"
    },
    {
      "question_id": "111-2_medicine-5_041",
      "question_number": 41,
      "correct_answer": "B",
      "category_group": "醫學（五）",
      "category": "一般外科",
      "category_confidence": "high",
      "key_point": "識別甲狀腺乳突癌之局部侵犯影像特徵。",
      "explanation": "甲狀腺乳突癌（PTC）在超音波上常表現為低回音、微小鈣化及邊緣不規則等特徵。當超音波顯示腫瘤包膜不完整或向外突出時，高度提示有甲狀腺外侵犯（extrathyroidal extension, ETE），這會影響手術切除範圍的評估與後續的分期。",
      "flashcard_front": "甲狀腺乳突癌 / 超音波特徵 / 甲狀腺外侵犯 (extrathyroidal extension)",
      "flashcard_back": "甲狀腺乳突癌超音波常評估其包膜完整性，以判斷有無甲狀腺外侵犯（extrathyroidal extension）。",
      "flashcard_summary": "甲狀腺乳突癌 / 超音波特徵 -> 甲狀腺乳突癌超音波常評估其包膜完整性，以判斷有無甲狀腺外侵犯（extrathyroidal extension）。"
    },
    {
      "question_id": "111-2_medicine-5_042",
      "question_number": 42,
      "correct_answer": "B",
      "category_group": "醫學（五）",
      "category": "一般外科",
      "category_confidence": "high",
      "key_point": "辨識常見乳房病變與臨床症狀之病理基礎。",
      "explanation": "乳房影像無腫瘤但有單側腋下淋巴轉移，需排除隱匿性乳癌；乳頭濕疹性變化需排除 Paget's disease；乳癌硬腫塊是因 desmoplastic reaction 所致。而乳房皮膚出現「橘子皮變化（peau d'orange）」是因為皮下「淋巴管被癌細胞阻塞」導致淋巴水腫，Cooper's ligament 受侵犯則會造成皮膚凹陷（skin dimpling），兩者機制不同。",
      "flashcard_front": "乳房橘子皮變化 / Cooper's ligament / 淋巴管阻塞 / 皮膚凹陷",
      "flashcard_back": "橘子皮樣變化是因淋巴管受癌細胞阻塞導致水腫；Cooper's ligament 受侵犯則會導致皮膚凹陷。",
      "flashcard_summary": "乳房橘子皮變化 / Cooper's ligament -> 橘子皮樣變化是因淋巴管受癌細胞阻塞導致水腫；Cooper's ligament 受侵犯則會導致皮膚凹陷。"
    },
    {
      "question_id": "111-2_medicine-5_043",
      "question_number": 43,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "一般外科",
      "category_confidence": "high",
      "key_point": "掌握乳癌術後放射線治療的適應症與原則。",
      "explanation": "乳房保留手術後的乳管原位癌及侵襲性乳癌，均應進行放療以降低復發率，但年大於70歲、腫瘤小、ER陽性且淋巴無轉移者可考慮免除。然而，對於接受保留手術的侵襲性乳癌患者，化學治療主要是全身性治療，絕對「不能取代」局部放療的作用，故 D 敘述最不適當。",
      "flashcard_front": "乳房保留手術 / 放射線治療 / 侵襲性乳癌 / 化學治療取代",
      "flashcard_back": "接受乳房保留手術的侵襲性乳癌患者，放射線治療是標準局部療法，不能以化學治療取代。",
      "flashcard_summary": "乳房保留手術 / 放射線治療 -> 接受乳房保留手術的侵襲性乳癌患者，放射線治療是標準局部療法，不能以化學治療取代。"
    },
    {
      "question_id": "111-2_medicine-5_044",
      "question_number": 44,
      "correct_answer": "C",
      "category_group": "醫學（五）",
      "category": "一般外科",
      "category_confidence": "high",
      "key_point": "掌握乳癌荷爾蒙治療藥物的選擇與時程。",
      "explanation": "停經前婦女因雌激素多源自卵巢，不應單用芳香環酶抑制劑（AI）；阻斷女性荷爾蒙受體 ER 陽性即可使用抗荷爾蒙藥物，即使 PR 陰性；抗荷爾蒙藥物通常在化療結束後才開始使用。而泰莫西芬（Tamoxifen）是停經前與停經後婦女皆可選用的經典一線藥物，並非停經後婦女不應選用。",
      "flashcard_front": "乳癌荷爾蒙治療 / 泰莫西芬 (Tamoxifen) / 停經後婦女 / 芳香環酶抑制劑",
      "flashcard_back": "泰莫西芬在停經前與停經後 ER(+) 乳癌均可選用；停經前不應單用芳香環酶抑制劑（AI）。",
      "flashcard_summary": "乳癌荷爾蒙治療 / 泰莫西芬 (Tamoxifen) -> 泰莫西芬在停經前與停經後 ER(+) 乳癌均可選用；停經前不應單用芳香環酶抑制劑（AI）。"
    },
    {
      "question_id": "111-2_medicine-5_045",
      "question_number": 45,
      "correct_answer": "B",
      "category_group": "醫學（五）",
      "category": "小兒外科",
      "category_confidence": "high",
      "key_point": "掌握新生兒無肛症（anorectal malformation）的急診處置原則。",
      "explanation": "新生兒無肛症送入加護病房後，基本處置包括：若病嬰出現腹脹或嘔吐，應置放胃管（NG tube）以進行胃腸減壓以防吸入性肺炎；由於無肛症常合併 VACTERL 症候群，應常規安排脊柱超音波或 X 光檢查脊椎與脊髓有無異常。高位無肛症大多需要做腸造口，但並非所有類型都需要立即安排手術，應先做影像定位確認高低位。",
      "flashcard_front": "新生兒無肛症 / 胃管減壓 / 脊柱檢查 / VACTERL 症候群 / 腸造口",
      "flashcard_back": "無肛症病兒若腹脹嘔吐應放胃管減壓，並應常規檢查脊柱是否異常（篩檢 VACTERL）；非所有病兒皆須立即造口。",
      "flashcard_summary": "新生兒無肛症 / 胃管減壓 -> 無肛症病兒若腹脹嘔吐應放胃管減壓，並應常規檢查脊柱是否異常（篩檢 VACTERL）；非所有病兒皆須立即造口。"
    }
  ]
}

# ----------------- BATCH 004 -----------------
batches_data["111-2_medicine-5_batch-004"] = {
  "dataset_id": "111-2_medicine-5",
  "batch_id": "111-2_medicine-5_batch-004",
  "items": [
    {
      "question_id": "111-2_medicine-5_046",
      "question_number": 46,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "小兒外科",
      "category_confidence": "high",
      "key_point": "掌握先天性橫膈膜疝氣（CDH）的解剖分類與治療原則。",
      "explanation": "先天性橫膈膜疝氣最常見為後外側缺損（Bochdalek hernia），而非前內側；疝氣會壓迫兩側肺部（同側更嚴重）造成雙側肺發育不良。目前治療策略是出生後先穩定心肺功能、控制肺動脈高壓，待穩定後再進行延遲手術，而非出生後立即修補。因此預防或處置肺動脈高壓是核心治療目標，D 敘述正確。",
      "flashcard_front": "先天性橫膈膜疝氣 (CDH) / Bochdalek / 肺發育不良 / 肺動脈高壓 / 延遲手術",
      "flashcard_back": "CDH 預後關鍵為肺動脈高壓；治療原則是先內科穩定心肺與控制肺高壓，再行延遲手術修補。",
      "flashcard_summary": "先天性橫膈膜疝氣 (CDH) / Bochdalek -> CDH 預後關鍵為肺動脈高壓；治療原則是先內科穩定心肺與控制肺高壓，再行延遲手術修補。"
    },
    {
      "question_id": "111-2_medicine-5_047",
      "question_number": 47,
      "correct_answer": "C",
      "category_group": "醫學（五）",
      "category": "小兒外科",
      "category_confidence": "high",
      "key_point": "掌握隱睪症（cryptorchidism）的病理變化與手術時程。",
      "explanation": "未下降之睪丸在6個月大時即可出現組織學退化（如間質細胞功能受損、精蟲生成障礙）。固定手術（orchidopexy）的目的在於保存生育力並方便日後摸到睪丸以早一步偵測癌變。目前國際共識建議手術的最佳時機是在「6至12個月大（1歲前）」進行，而非2歲之後，故 C 錯誤。",
      "flashcard_front": "隱睪症 / 睪丸固定術 (orchidopexy) / 手術最佳時機 / 組織退化",
      "flashcard_back": "隱睪症睪丸固定手術建議在6至12個月大（1歲前）進行，最遲不應超過18個月，而非2歲後。",
      "flashcard_summary": "隱睪症 / 睪丸固定術 (orchidopexy) -> 隱睪症睪丸固定手術建議在6至12個月大（1歲前）進行，最遲不應超過18個月，而非2歲後。"
    },
    {
      "question_id": "111-2_medicine-5_048",
      "question_number": 48,
      "correct_answer": "A",
      "category_group": "醫學（五）",
      "category": "小兒外科",
      "category_confidence": "high",
      "key_point": "記憶兒童最常見之顱外實質腫瘤。",
      "explanation": "兒童最常見的顱外實質腫瘤（extra-cranial solid tumor）為神經母細胞瘤（neuroblastoma），好發於腎上腺或交感神經鏈。腎母細胞瘤（Wilms' tumor）為第二常見。",
      "flashcard_front": "兒童顱外實質腫瘤 / 神經母細胞瘤 / 腎母細胞瘤 / 腎上腺",
      "flashcard_back": "兒童及嬰幼兒最常見的顱外固態實質腫瘤是神經母細胞瘤，好發於腎上腺或後腹腔交感神經鏈。",
      "flashcard_summary": "兒童顱外實質腫瘤 / 神經母細胞瘤 -> 兒童及嬰幼兒最常見的顱外固態實質腫瘤是神經母細胞瘤，好發於腎上腺或後腹腔交感神經鏈。"
    },
    {
      "question_id": "111-2_medicine-5_049",
      "question_number": 49,
      "correct_answer": "B",
      "category_group": "醫學（五）",
      "category": "小兒外科",
      "category_confidence": "high",
      "key_point": "識別先天性橫膈疝氣（CDH）使用 ECMO 預後不良的危險因子。",
      "explanation": "先天性橫膈疝氣病童在嚴重低氧血症時需使用 ECMO 治療。ECMO 預後不良或相對禁忌的指引包括：出生體重過低（通常小於 2 公斤，本題 1.7 公斤）、妊娠週數小於 34 週或合併嚴重先天畸形。體重 1.7 公斤在插管與維持上難度極高，且顱內出血等併發症機率高，預後最差。",
      "flashcard_front": "CDH / 葉克膜 (ECMO) / 預後不佳因子 / 出生體重 / 妊娠週數",
      "flashcard_back": "CDH 兒使用 ECMO 時，若出生體重小於 2.0 公斤（如1.7公斤）或週數過小，其預後往往極差。",
      "flashcard_summary": "CDH / 葉克膜 (ECMO) -> CDH 兒使用 ECMO 時，若出生體重小於 2.0 公斤（如1.7公斤）或週數過小，其預後往往極差。"
    },
    {
      "question_id": "111-2_medicine-5_050",
      "question_number": 50,
      "correct_answer": "B",
      "category_group": "醫學（五）",
      "category": "大腸直腸科",
      "category_confidence": "high",
      "key_point": "掌握潰瘍性大腸炎（ulcerative colitis）的手術適應症。",
      "explanation": "潰瘍性大腸炎的手術適應症包括：猛爆性大腸炎且內科治療無效、毒性巨結腸症（toxic megacolon）、大出血、穿孔，以及病理切片出現細胞分化不良（dysplasia）或癌變。而每日腹瀉 5 次屬於中度病況，首選應是內科藥物控制，而非手術切除指引。",
      "flashcard_front": "潰瘍性大腸炎 / 手術適應症 / 毒性巨結腸症 / 腹瀉次數 / 細胞分化不良",
      "flashcard_back": "每日腹瀉5次非手術指引，應先以內科藥物治療；毒性巨結腸症及細胞分化不良則是絕對手術適應症。",
      "flashcard_summary": "潰瘍性大腸炎 / 手術適應症 -> 每日腹瀉5次非手術指引，應先以內科藥物治療；毒性巨結腸症及細胞分化不良則是絕對手術適應症。"
    },
    {
      "question_id": "111-2_medicine-5_051",
      "question_number": 51,
      "correct_answer": "C",
      "category_group": "醫學（五）",
      "category": "大腸直腸科",
      "category_confidence": "high",
      "key_point": "熟記大腸與直腸的解剖學腹膜位置。",
      "explanation": "在大腸與直腸的解剖結構中，升結腸、降結腸屬於後腹腔器官（二級後腹腔，固定於後腹壁），直腸中下段亦位於腹膜外。而橫結腸與乙狀結腸具有游離的繫膜（mesocolon）懸吊在腹膜腔內，並未附著於後腹腔。",
      "flashcard_front": "大腸解剖 / 後腹腔附著 / 升結腸 / 降結腸 / 橫結腸 / 繫膜",
      "flashcard_back": "橫結腸和乙狀結腸具有繫膜，屬於腹膜內游離器官，並未固定或附著於後腹腔。",
      "flashcard_summary": "大腸解剖 / 後腹腔附著 -> 橫結腸和乙狀結腸具有繫膜，屬於腹膜內游離器官，並未固定或附著於後腹腔。"
    },
    {
      "question_id": "111-2_medicine-5_052",
      "question_number": 52,
      "correct_answer": "C",
      "category_group": "醫學（五）",
      "category": "大腸直腸科",
      "category_confidence": "high",
      "key_point": "掌握遺傳性非息肉大腸直腸癌（HNPCC / Lynch syndrome）的特徵。",
      "explanation": "Lynch 症候群為自體顯性遺傳，因 MMR 基因（如 MSH2, MLH1, MSH6 等）缺損所致，且 MSH6 缺損與子宮內膜癌有高相關性。其大腸癌多發生在 40-50 歲，一般不需在 20 歲前進行預防性手術（只有家族性腺瘤性息肉症 FAP 才常需在青少年期或20歲前做預防性切除）。",
      "flashcard_front": "HNPCC (Lynch 症候群) / MMR 基因 / 預防性大腸切除 / 子宮內膜癌",
      "flashcard_back": "Lynch 症候群大腸癌好發於中年，不需在20歲前做預防性大腸切除；FAP 則常需在青年期作預防性切除。",
      "flashcard_summary": "HNPCC (Lynch 症候群) / MMR 基因 -> Lynch 症候群大腸癌好發於中年，不需在20歲前做預防性大腸切除；FAP 則常需在青年期作預防性切除。"
    },
    {
      "question_id": "111-2_medicine-5_053",
      "question_number": 53,
      "correct_answer": "C",
      "category_group": "醫學（五）",
      "category": "外科概論",
      "category_confidence": "high",
      "key_point": "比較腹腔鏡疝氣修補術（TEP 與 TAPP）的技術與特點。",
      "explanation": "TEP（完全腹膜外）與 TAPP（經腹腔腹膜前）主要區別在於進入腹膜前間隙的順序，TEP 因不進入腹腔，可將臟器損傷風險降至最低，兩者在大型分析中復發率無顯著差異。然而，相較於 TEP 完全在狹窄的腹膜外間隙操作，TAPP 經由腹腔進入，其手術操作空間較大而非較有限，故 C 錯誤。",
      "flashcard_front": "腹腔鏡疝氣修補 / TEP / TAPP / 操作空間 / 腹膜前間隙",
      "flashcard_back": "TAPP 經由腹腔操作，操作空間大於完全侷限在腹膜外間隙的 TEP 手術。",
      "flashcard_summary": "腹腔鏡疝氣修補 / TEP -> TAPP 經由腹腔操作，操作空間大於完全侷限在腹膜外間隙的 TEP 手術。"
    },
    {
      "question_id": "111-2_medicine-5_054",
      "question_number": 54,
      "correct_answer": "C",
      "category_group": "醫學（五）",
      "category": "一般外科",
      "category_confidence": "high",
      "key_point": "掌握減重手術的機制分類與臨床應用。",
      "explanation": "減重手術中，LSG（袖狀胃切除）主要為限制性手術而非吸收不良；Roux-en-Y（胃繞道）結合限制與吸收不良；BPD（膽胰繞道）則是以吸收不良為主且伴隨輕度限制。BPD 術後 marginal ulcer 的發生與胃酸及吻合口相關，其術後邊緣性潰瘍機率高於 DS 手術。因此，正確的配對僅有 ќѝ，即 C。",
      "flashcard_front": "減重手術 / 袖狀胃切除 (LSG) / 胃繞道 (Roux-en-Y) / 膽胰繞道 (BPD) / 手術機制",
      "flashcard_back": "LSG 為限制性手術；Roux-en-Y 結合限制與吸收不良；BPD 為主要吸收不良及輕度限制手術。",
      "flashcard_summary": "減重手術 / 袖狀胃切除 (LSG) -> LSG 為限制性手術；Roux-en-Y 結合限制與吸收不良；BPD 為主要吸收不良及輕度限制手術。"
    },
    {
      "question_id": "111-2_medicine-5_055",
      "question_number": 55,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "外科概論",
      "category_confidence": "high",
      "key_point": "掌握單一切口腹腔鏡手術（SILS）的技術要點與傷口關閉。",
      "explanation": "SILS 常用多通道套管置於臍部，有時需加額外端口或用縫線牽引協助。由於單一切口（特別是臍部）筋膜層缺損較大且集中，為防止術後切口疝氣，筋膜層必須使用長效可吸收線（如 PDS）或不可吸收線進行牢固關閉，而皮膚與皮下縫合不應使用不可吸收線進行連續或間斷縫合，以避免線頭殘留或增加感染風險。",
      "flashcard_front": "單一切口腹腔鏡 (SILS) / 臍部切口 / 筋膜層關閉 / 切口疝氣 / 線材選擇",
      "flashcard_back": "SILS 為防止切口疝氣，筋膜層應使用長效可吸收線（如PDS）牢固縫合，而非皮膚皮下用不可吸收線連續縫合。",
      "flashcard_summary": "單一切口腹腔鏡 (SILS) / 臍部切口 -> SILS 為防止切口疝氣，筋膜層應使用長效可吸收線（如PDS）牢固縫合，而非皮膚皮下用不可吸收線連續縫合。"
    },
    {
      "question_id": "111-2_medicine-5_056",
      "question_number": 56,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "骨科",
      "category_confidence": "high",
      "key_point": "掌握惡性軟骨肉瘤（chondrosarcoma）的臨床表現與治療。",
      "explanation": "軟骨肉瘤多好發於 40-60 歲中老年人，而非青少年；它對化療及放療極度不敏感，最主要的治療是手術廣泛切除。對於骨軟骨瘤（osteochondroma）患者，若追蹤發現其表面的軟骨帽（cartilage cap）厚度大於 2 公分，應高度警惕惡性轉化為繼發性軟骨肉瘤（secondary chondrosarcoma），D 敘述正確。",
      "flashcard_front": "軟骨肉瘤 (Chondrosarcoma) / 骨軟骨瘤 / 軟骨帽厚度 / 放化療敏感度",
      "flashcard_back": "軟骨肉瘤對放化療不敏感，手術切除為主；骨軟骨瘤的軟骨帽厚度 >2cm 提示有繼發惡變可能。",
      "flashcard_summary": "軟骨肉瘤 (Chondrosarcoma) / 骨軟骨瘤 -> 軟骨肉瘤對放化療不敏感，手術切除為主；骨軟骨瘤的軟骨帽厚度 >2cm 提示有繼發惡變可能。"
    },
    {
      "question_id": "111-2_medicine-5_057",
      "question_number": 57,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "外科概論",
      "category_confidence": "high",
      "key_point": "識別創傷急救中尿道斷裂的臨床禁忌。",
      "explanation": "病患受卡車輾壓，出現生殖器尿道口有血跡與雙下肢不等長，高度提示有骨盆骨折合併尿道斷裂（urethral disruption）。此時盲目立即放置導尿管（Foley） is 絕對禁忌，易加重尿道撕裂，必須先安排逆行性尿道攝影（RUG）確認尿道完整性。",
      "flashcard_front": "骨盆骨折 / 尿道口血跡 / 導尿管禁忌 / 逆行性尿道攝影 (RUG) / 創傷處置",
      "flashcard_back": "嚴重創傷伴隨尿道口血跡時，禁忌立即插導尿管，應先以逆行性尿道攝影排除尿道斷裂。",
      "flashcard_summary": "骨盆骨折 / 尿道口血跡 -> 嚴重創傷伴隨尿道口血跡時，禁忌立即插導尿管，應先以逆行性尿道攝影排除尿道斷裂。"
    },
    {
      "question_id": "111-2_medicine-5_058",
      "question_number": 58,
      "correct_answer": "A",
      "category_group": "醫學（五）",
      "category": "骨科",
      "category_confidence": "high",
      "key_point": "熟悉髖臼的解剖組成與 Judet 骨盆斜位影像。",
      "explanation": "髖臼由髂骨、坐骨、恥骨的三向放射狀軟骨融合而成，並由透明軟骨覆蓋（正確）。骨盆 Judet 斜位照是將患者傾斜 45 度（而非 60 度）拍攝。內斜位照（閉孔位）主要展現前柱與後壁；外斜位照（髂骨位）主要展現後柱與前壁，故其他選項錯誤。",
      "flashcard_front": "髖臼解剖 / 透明軟骨 / 三向放射狀軟骨 / Judet 斜位照 / 骨盆斜位角度",
      "flashcard_back": "髖臼由三向放射狀軟骨融合，表面覆蓋透明軟骨；Judet 攝影角度為傾斜 45 度而非 60 度。",
      "flashcard_summary": "髖臼解剖 / 透明軟骨 -> 髖臼由三向放射狀軟骨融合，表面覆蓋透明軟骨；Judet 攝影角度為傾斜 45 度而非 60 度。"
    },
    {
      "question_id": "111-2_medicine-5_059",
      "question_number": 59,
      "correct_answer": "B",
      "category_group": "醫學（五）",
      "category": "骨科",
      "category_confidence": "high",
      "key_point": "熟記骨盆與髖部肌肉起點與撕除性骨折（avulsion fracture）的關係。",
      "explanation": "髂嵴對應腹部肌肉；坐骨結節對應繩肌；股骨小轉子對應髂腰肌。而股直肌（rectus femoris）的起點為髂前下棘（AIIS），拉扯 ASIS 造成的撕除性骨折多與縫匠肌（sartorius）或股膜張肌拉扯相關，因此 B 組合錯誤。",
      "flashcard_front": "撕除性骨折 / 髂前上棘 (ASIS) / 髂前下棘 (AIIS) / 股直肌 / 縫匠肌",
      "flashcard_back": "股直肌起點為髂前下棘（AIIS），拉扯 ASIS 造成骨折的肌肉是縫匠肌或股膜張肌。",
      "flashcard_summary": "撕除性骨折 / 髂前上棘 (ASIS) -> 股直肌起點為髂前下棘（AIIS），拉扯 ASIS 造成骨折的肌肉是縫匠肌或股膜張肌。"
    },
    {
      "question_id": "111-2_medicine-5_060",
      "question_number": 60,
      "correct_answer": "C",
      "category_group": "醫學（五）",
      "category": "骨科",
      "category_confidence": "high",
      "key_point": "掌握新生兒發展性髖關節發育不良（DDH）的檢查方法。",
      "explanation": "新生兒出現雙側大腿不對稱皺褶需篩檢 DDH。臨床篩檢檢查包括 Galeazzi 徵象（雙腳屈膝看高度）、Barlow（推脫位）與 Ortolani（復位法）檢查。而 Patrick 氏檢查（4字試驗）是用於評估成人薦髂關節或髖關節病變，在新生兒 DDH 篩檢中並不適用且無相關性。",
      "flashcard_front": "新生兒大腿皺褶 / 髖關節發育不良 (DDH) / Barlow與Ortolani / Patrick氏檢查",
      "flashcard_back": "篩檢新生兒 DDH 常用 Barlow、Ortolani 與 Galeazzi 檢查；Patrick 檢查為成人關節炎篩檢工具。",
      "flashcard_summary": "新生兒大腿皺褶 / 髖關節發育不良 (DDH) -> 篩檢新生兒 DDH 常用 Barlow、Ortolani 與 Galeazzi 檢查；Patrick 檢查為成人關節炎篩檢工具。"
    }
  ]
}

# ----------------- BATCH 005 -----------------
batches_data["111-2_medicine-5_batch-005"] = {
  "dataset_id": "111-2_medicine-5",
  "batch_id": "111-2_medicine-5_batch-005",
  "items": [
    {
      "question_id": "111-2_medicine-5_061",
      "question_number": 61,
      "correct_answer": "B",
      "category_group": "醫學（五）",
      "category": "骨科",
      "category_confidence": "high",
      "key_point": "辨別尺神經壓迫（肘隧道症候群）的特徵壓迫位置。",
      "explanation": "患者有無名指尺側及小指麻木，伴隨小指屈指深肌（FDP）無力，這是尺神經在手肘處受壓（肘隧道症候群）的表現。手腕處 Guyon's canal 壓迫通常不會影響 FDP（因該肌分支出現在肘下）。肘部最常見的壓迫點之一是 arcade of Struthers（由內側肌間隔形成的纖維帶），故 B 是正確壓迫位置。",
      "flashcard_front": "尺神經壓迫 / 小指麻木 / 屈指深肌無力 / Guyon tunnel / arcade of Struthers",
      "flashcard_back": "尺神經在肘部受壓會影響小指屈指深肌力，常見壓迫點為 arcade of Struthers；手腕 Guyon 壓迫則不影響此肌。",
      "flashcard_summary": "尺神經壓迫 / 小指麻木 -> 尺神經在肘部受壓會影響小指屈指深肌力，常見壓迫點為 arcade of Struthers；手腕 Guyon 壓迫則不影響此肌。"
    },
    {
      "question_id": "111-2_medicine-5_062",
      "question_number": 62,
      "correct_answer": "B",
      "category_group": "醫學（五）",
      "category": "骨科",
      "category_confidence": "high",
      "key_point": "掌握椎間盤突出症（HIVD）的自然史與治療原則。",
      "explanation": "椎間盤突出可分為 protrusion、extrusion 和 sequestration，以 protrusion 最常見；MRI 是最佳診斷影像；術後併發症包括感染、硬膜撕裂及復發等。臨床上，高達 80-90% 的 HIVD 患者透過保守治療（休息、藥物、復健）即可顯著改善，非通常需要手術進行神經減壓。",
      "flashcard_front": "椎間盤突出 (HIVD) / 保存治療 / 手術指引 / MRI診斷 / 突出類型",
      "flashcard_back": "大多數椎間盤突出患者經保守治療即可改善，僅在保守無效或合併馬尾症候群時才考慮手術。",
      "flashcard_summary": "椎間盤突出 (HIVD) / 保存治療 -> 大多數椎間盤突出患者經保守治療即可改善，僅在保守無效或合併馬尾症候群時才考慮手術。"
    },
    {
      "question_id": "111-2_medicine-5_063",
      "question_number": 63,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "骨科",
      "category_confidence": "high",
      "key_point": "熟記年輕人股骨頸骨折的分類與治療策略。",
      "explanation": "25歲年輕人發生股骨頸骨折，應盡最大可能保留股骨頭，首選復位與內固定手術（ORIF），而非進行人工半髖關節置換術（後者適用於老年人）。Garden classification Stage II 是指完全骨折且無移位，而非不完全骨折。X 光片上 Shenton's line 的不連續，代表骨折移位程度較大，是正確的解剖影像描述。",
      "flashcard_front": "股骨頸骨折 / 年輕人治療 / Garden分類 / Shenton line 不連續 / 內固定",
      "flashcard_back": "年輕人股骨頸骨折首選復位內固定以保留股骨頭；Shenton line 不連續代表骨折有明顯移位。",
      "flashcard_summary": "股骨頸骨折 / 年輕人治療 -> 年輕人股骨頸骨折首選復位內固定以保留股骨頭；Shenton line 不連續代表骨折有明顯移位。"
    },
    {
      "question_id": "111-2_medicine-5_064",
      "question_number": 64,
      "correct_answer": "A",
      "category_group": "醫學（五）",
      "category": "泌尿科",
      "category_confidence": "high",
      "key_point": "掌握體外震波碎石術（ESWL）的禁忌症。",
      "explanation": "ESWL 的絕對禁忌症包括孕婦、未經控制的凝血功能異常、結石附近有主動脈瘤或嚴重骨骼畸形導致無法定位。而肥胖患者因脂肪厚度會衰減震波能量，增加定位與治療難度，但並非「絕對禁忌症」，臨床上可透過調整焦距與能量或改採其他碎石手術來解決。",
      "flashcard_front": "體外震波碎石 (ESWL) / 絕對禁忌症 / 凝血功能異常 / 主動脈瘤 / 肥胖",
      "flashcard_back": "肥胖非 ESWL 的絕對禁忌症，但會增加治療難度；凝血異常與結石旁有動脈瘤為絕對禁忌症。",
      "flashcard_summary": "體外震波碎石 (ESWL) / 絕對禁忌症 -> 肥胖非 ESWL 的絕對禁忌症，但會增加治療難度；凝血異常與結石旁有動脈瘤為絕對禁忌症。"
    },
    {
      "question_id": "111-2_medicine-5_065",
      "question_number": 65,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "泌尿科",
      "category_confidence": "high",
      "key_point": "掌握前列腺特定抗原（PSA）升高的鑑別與處置流程。",
      "explanation": "患者 PSA 偏高（7.2 ng/mL），但尿液檢查顯示有明顯尿路感染（WBC 50-60/HPF）。由於急性尿路感染或發炎會導致 PSA 偽陽性升高，臨床上下一步最適當的處置是「先給予抗生素治療」控制感染，待感染完全消除後再重新複查 PSA，以避免不必要的前列腺切片檢查。",
      "flashcard_front": "PSA 升高 / 尿路感染 / WBC升高 / 抗生素治療 / 前列腺切片",
      "flashcard_back": "尿路感染會導致 PSA 假性升高，應先給予抗生素治療感染，待感染控制後再重新追蹤 PSA。",
      "flashcard_summary": "PSA 升高 / 尿路感染 -> 尿路感染會導致 PSA 假性升高，應先給予抗生素治療感染，待感染控制後再重新追蹤 PSA。"
    },
    {
      "question_id": "111-2_medicine-5_066",
      "question_number": 66,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "泌尿科",
      "category_confidence": "high",
      "key_point": "掌握上尿路移行上皮癌（UTUC）伴腎功能不全之影像評估。",
      "explanation": "塑膠工廠暴露史與無痛性全程血尿，伴有輸尿管鑄型的「條狀血塊」，強烈提示為上尿路移行上皮癌（UTUC）。由於患者肌酸酐高達 3.0 mg/dL（腎功能不全），為含碘顯影劑電腦斷層（CTU）的禁忌，此時最適當且安全的影像評估為進行「逆行性腎盂攝影（retrograde pyelography）」而非 CT 攝影。",
      "flashcard_front": "無痛性血尿 / 條狀血塊 / 腎功能不全 / 逆行性腎盂攝影 / 顯影劑禁忌",
      "flashcard_back": "腎功能不佳（Cr 3.0）且懷疑上尿路腫瘤時，禁忌做含顯影劑的 CTU，應選用逆行性腎盂攝影（RP）。",
      "flashcard_summary": "無痛性血尿 / 條狀血塊 -> 腎功能不佳（Cr 3.0）且懷疑上尿路腫瘤時，禁忌做含顯影劑的 CTU，應選用逆行性腎盂攝影（RP）。"
    },
    {
      "question_id": "111-2_medicine-5_067",
      "question_number": 67,
      "correct_answer": "",
      "category_group": "醫學（五）",
      "category": "泌尿科",
      "category_confidence": "high",
      "key_point": "了解威爾姆氏腫瘤（Wilms' tumor）的臨床與基因特徵及官方更正答案。",
      "explanation": "威爾姆氏腫瘤是小兒最常見的腎臟惡性腫瘤，約佔兒童腫瘤5%，常轉移至肺與肝，約10%合併先天發育異常（如 WAGR）。此題原本考點為 WT2 基因與 Wilms tumor 關係（經典腫瘤與 WT1 突變直接相關，部分合併症候群與 WT2 相關），因選項描述有爭議，官方最後更正為無標準答案（全部給分），答題時維持空值以符合官方答案。",
      "flashcard_front": "威爾姆氏腫瘤 / 兒童腎腫瘤 / WT1 基因 / 肺肝轉移 / 官方答案更正",
      "flashcard_back": "Wilms 腫瘤為兒童常見腎惡性腫瘤，與 WT1 關係密切；此題因選項爭議官方列為無標準答案。",
      "flashcard_summary": "威爾姆氏腫瘤 / 兒童腎腫瘤 -> Wilms 腫瘤為兒童常見腎惡性腫瘤，與 WT1 關係密切；此題因選項爭議官方列為無標準答案。"
    },
    {
      "question_id": "111-2_medicine-5_068",
      "question_number": 68,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "泌尿科",
      "category_confidence": "high",
      "key_point": "熟記支配尿道外括約肌的神經。",
      "explanation": "尿道外括約肌是由骨骼肌組成，受體神經系統支配。其主要支配神經為會陰神經（pudendal nerve / 陰部神經）的會陰分支（源自脊髓 S2-S4）。而下腹神經（交感）與骨盆神經（副交感）主要支配平滑肌組成的尿道內括約肌及膀胱逼尿肌。",
      "flashcard_front": "尿道外括約肌 / 骨骼肌 / 體神經支配 / 陰部神經 (pudendal nerve)",
      "flashcard_back": "尿道外括約肌為骨骼肌，受陰部神經（pudendal nerve，源於 S2-S4）支配；內括約肌則受自主神經支配。",
      "flashcard_summary": "尿道外括約肌 / 骨骼肌 -> 尿道外括約肌為骨骼肌，受陰部神經（pudendal nerve，源於 S2-S4）支配；內括約肌則受自主神經支配。"
    },
    {
      "question_id": "111-2_medicine-5_069",
      "question_number": 69,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "泌尿科",
      "category_confidence": "high",
      "key_point": "掌握精索靜脈曲張（varicocele）的流行病學與治療。",
      "explanation": "精索靜靜脈曲張是男性不孕症中最常見且可手術矯正的病因，約占不孕男性的40%，常導致精子活動力與數量下降。雖然血管攝影與栓塞是可行方式，但臨床上治療成功率最高且併發症最少的黃金標準是顯微結紮手術（microsurgical varicocelectomy），故 D 敘述錯誤。",
      "flashcard_front": "精索靜脈曲張 / 男性不孕 / 精液異常 / 顯微結紮術 / 栓塞治療",
      "flashcard_back": "精索靜脈曲張不孕症的首選黃金治療為顯微結紮手術，其成功率高於經皮血管栓塞治療。",
      "flashcard_summary": "精索靜脈曲張 / 男性不孕 -> 精索靜脈曲張不孕症的首選黃金治療為顯微結紮手術，其成功率高於經皮血管栓塞治療。"
    },
    {
      "question_id": "111-2_medicine-5_070",
      "question_number": 70,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "泌尿科",
      "category_confidence": "high",
      "key_point": "掌握先天性泌尿道異常引起腎積水的機率。",
      "explanation": "後尿道瓣膜與輸尿管腎盂接合處阻塞（UPJO）皆會直接造成尿路梗阻而引起嚴重腎積水；雙套輸尿管常因合併異位開口或輸尿管囊腫引起逆流或阻塞導致腎積水。而尿道下裂（hypospadias）僅是尿道外口位置開口異常，通常不伴隨尿流排出受阻，因此最不會引起腎積水。",
      "flashcard_front": "先天尿路異常 / 腎積水 / 後尿道瓣膜 / 雙套輸尿管 / 尿道下裂",
      "flashcard_back": "後尿道瓣膜與 UPJO 常致尿路梗阻而引起腎積水；尿道下裂一般不造成尿路阻塞，最不易引起腎積水。",
      "flashcard_summary": "先天尿路異常 / 腎積水 -> 後尿道瓣膜與 UPJO 常致尿路梗阻而引起腎積水；尿道下裂一般不造成尿路阻塞，最不易引起腎積水。"
    },
    {
      "question_id": "111-2_medicine-5_071",
      "question_number": 71,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "泌尿科",
      "category_confidence": "high",
      "key_point": "掌握神經源性膀胱合併輕度逆流的處置。",
      "explanation": "脊髓膜膨出常合併神經源性膀胱，導致排尿障礙。治療上以間歇性清潔導尿（CIC）排空膀胱、抗膽鹼藥物降低逼尿肌壓力，以及定期尿路動力學監測為基礎。因病童的膀胱尿道逆流（VUR）僅為輕微的一度，此時不需要儘早施行輸尿管重建手術，應先改善膀胱高壓及排尿功能以防逆流惡化。",
      "flashcard_front": "脊髓膜膨出 / 神經源性膀胱 / 清潔導尿 (CIC) / 膀胱尿道逆流 (VUR) / 輸尿管重建",
      "flashcard_back": "神經源性膀胱合併輕度逆流（一度）應先以清潔導尿與藥物降低膀胱壓，此時不適合儘早安排重建手術。",
      "flashcard_summary": "脊髓膜膨出 / 神經源性膀胱 -> 神經源性膀胱合併輕度逆流（一度）應先以清潔導尿與藥物降低膀胱壓，此時不適合儘早安排重建手術。"
    },
    {
      "question_id": "111-2_medicine-5_072",
      "question_number": 72,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "心臟外科",
      "category_confidence": "high",
      "key_point": "掌握深層靜脈血栓（DVT）的臨床表現、診斷與併發症。",
      "explanation": "單側下肢無熱痛的腫脹是 DVT 的典型症狀，好發於左下肢，診斷首選都卜勒超音波。治療上首選抗凝血藥物，極少需要緊急手術。若不進行適當的抗凝處置，下肢血栓可能脫落並隨血流回流至肺動脈，造成致死性肺栓塞，導致患者出現呼吸困難等重症。",
      "flashcard_front": "深層靜脈血栓 (DVT) / 肺栓塞 (PE) / 呼吸困難 / 超音波診斷 / 抗凝治療",
      "flashcard_back": "DVT 首選都卜勒超音波診斷，治療以抗凝藥物為主；若不處理可能脫落造成肺栓塞，引發呼吸困難。",
      "flashcard_summary": "深層靜脈血栓 (DVT) / 肺栓塞 (PE) -> DVT 首選都卜勒超音波診斷，治療以抗凝藥物為主；若不處理可能脫落造成肺栓塞，引發呼吸困難。"
    },
    {
      "question_id": "111-2_medicine-5_073",
      "question_number": 73,
      "correct_answer": "C",
      "category_group": "醫學（五）",
      "category": "一般外科",
      "category_confidence": "high",
      "key_point": "辨別慢性胰臟炎鈣化在影像學上的表現特徵。",
      "explanation": "慢性胰臟炎典型鈣化呈點狀或斑駁狀分布，因胰臟位置跨越 L1-L2 椎體高度，鈣化常呈水平方向。電腦斷層（CT）相較於平片對微小鈣化的辨識度高得多。在腹部平片（X光）上，慢性胰臟炎的鈣化僅在約 30-40% 左右的病人能被觀察到，並非幾乎都清晰可見，故 C 最不恰當。",
      "flashcard_front": "慢性胰臟炎 / 胰臟鈣化 / 腹部 X 光 (KUB) / 電腦斷層 (CT) / 檢出率",
      "flashcard_back": "慢性胰臟炎鈣化在腹部 X 光上僅有部分人清晰可見（檢出率低）；電腦斷層是較佳的辨識工具。",
      "flashcard_summary": "慢性胰臟炎 / 胰臟鈣化 -> 慢性胰臟炎鈣化在腹部 X 光上僅有部分人清晰可見（檢出率低）；電腦斷層是較佳的辨識工具。"
    },
    {
      "question_id": "111-2_medicine-5_074",
      "question_number": 74,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "胸腔外科",
      "category_confidence": "high",
      "key_point": "掌握胸腔轉移性惡性腫瘤的影像學與轉移特點。",
      "explanation": "轉移至肺部的病灶典型表現為雙側多發性、圓形且邊緣滑順的球型結節（cannonball），而非多角型且不規則；肋膜轉移通常為多發結節且極易合併肋膜積水。而攝護腺癌（prostate cancer）轉移至骨骼（如肋骨、胸椎）時，在放射影像上典型會呈現成骨性病灶（osteoblastic lesion），D 描述正確。",
      "flashcard_front": "轉移性肺腫瘤 / 肋膜轉移 / 攝護腺癌骨轉移 / 成骨性病灶 (osteoblastic)",
      "flashcard_back": "轉移肺腫瘤多為圓形邊緣滑順結節；攝護腺癌骨轉移典型表現為成骨性（osteoblastic）病灶。",
      "flashcard_summary": "轉移性肺腫瘤 / 肋膜轉移 -> 轉移肺腫瘤多為圓形邊緣滑順結節；攝護腺癌骨轉移典型表現為成骨性（osteoblastic）病灶。"
    },
    {
      "question_id": "111-2_medicine-5_075",
      "question_number": 75,
      "correct_answer": "D",
      "category_group": "醫學（五）",
      "category": "外科概論",
      "category_confidence": "high",
      "key_point": "掌握腹腔鏡手術氣腹與穿刺常見併發症。",
      "explanation": "腹腔鏡手術灌注二氧化碳建立氣腹會增加腹壓並刺激迷走神經，可能誘發心律不整或發生二氧化碳氣體栓塞；Trocar 穿刺也有傷及腹內血管與腸道的風險。雖然腹腔鏡手術傷口較小，但若腹壁切口（特別是 >10mm 的套管針處）筋膜層未完全縫合，仍有可能發生腹壁疝氣或切口疝氣（incisional hernia）。",
      "flashcard_front": "腹腔鏡併發症 / 二氧化碳氣腹 / Trocar 穿刺傷 / 切口疝氣 (incisional hernia)",
      "flashcard_back": "氣腹可能引發心律不整與氣體栓塞；腹腔鏡套管針切口若未閉合完全仍有發生切口疝氣的風險。",
      "flashcard_summary": "腹腔鏡併發症 / 二氧化碳氣腹 -> 氣腹可能引發心律不整與氣體栓塞；腹腔鏡套管針切口若未閉合完全仍有發生切口疝氣的風險。"
    }
  ]
}

# Write outputs
for batch_id, data in batches_data.items():
    output_path = f"reports/gemini_outputs/{batch_id}.json"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Successfully wrote {output_path}")

print("All batches processed successfully!")



