import json
from pathlib import Path

# Create reports/gemini_outputs/ if it doesn't exist
Path("reports/gemini_outputs").mkdir(parents=True, exist_ok=True)

# 108-2_medicine-6_batch-002 (Q16 - Q30)
batch_108_2_med6_002 = {
  "dataset_id": "108-2_medicine-6",
  "batch_id": "108-2_medicine-6_batch-002",
  "items": [
    {
      "question_id": "108-2_medicine-6_016",
      "question_number": 16,
      "correct_answer": "A",
      "category_group": "醫學（六）",
      "category": "眼科",
      "category_confidence": "high",
      "key_point": "眼瞼痙攣的臨床特徵、好發群與治療首選。",
      "explanation": "眼瞼痙攣是一種雙側、對稱性發作的不自主眼瞼肌痙攣，因此大多數為雙眼發作，而非單眼，選項A敘述錯誤。此病好發於中老年女性，因症狀與乾眼症有重疊（如乾澀與畏光），臨床上需做鑑別診斷。目前局部注射肉毒桿菌素是改善症狀的首選且最有效之方法。",
      "flashcard_front": "眼瞼痙攣 / 單側與雙側 / 好發群 / 肉毒桿菌素注射",
      "flashcard_back": "眼瞼痙攣多數為雙側對稱性發作，好發於中老年女性，首選治療為局部注射肉毒桿菌素。",
      "flashcard_summary": "眼瞼痙攣 / 單側與雙側 / 好發群 / 肉毒桿菌素注射 -> 眼瞼痙攣多數為雙側對稱性發作，好發於中老年女性，首選治療為局部注射肉毒桿菌素。"
    },
    {
      "question_id": "108-2_medicine-6_017",
      "question_number": 17,
      "correct_answer": "A",
      "category_group": "醫學（六）",
      "category": "眼科",
      "category_confidence": "high",
      "key_point": "裂孔型視網膜剝離的典型臨床與影像學特徵。",
      "explanation": "裂孔型視網膜剝離（RRD）是臨床最常見的視網膜剝離類型，主因為視網膜感觉層產生裂孔，使得液化玻璃體滲入感覺層與色素上皮層之間而引發剝離。影像上可見皺褶、起伏的視網膜網膜片。牽引型與滲漏型（滲出型）則不具備明顯裂孔，臨床機轉不同；出血型以視網膜下大量出血為特徵。",
      "flashcard_front": "裂孔型視網膜剝離 / 玻璃體液化 / 感覺層與色素上皮層分離 / 最常見",
      "flashcard_back": "液化玻璃體經視網膜裂孔滲入感覺層與色素上皮層之間導致剝離，為最常見之裂孔型視網膜剝離（RRD）。",
      "flashcard_summary": "裂孔型視網膜剝離 / 玻璃體液化 / 感覺層與色素上皮層分離 / 最常見 -> 液化玻璃體經視網膜裂孔滲入感覺層與色素上皮層之間導致剝離，為最常見之裂孔型視網膜剝離（RRD）。"
    },
    {
      "question_id": "108-2_medicine-6_018",
      "question_number": 18,
      "correct_answer": "C",
      "category_group": "醫學（六）",
      "category": "眼科",
      "category_confidence": "high",
      "key_point": "已剝離視網膜的處置原則與手術選擇。",
      "explanation": "當視網膜已經發生明顯剝離（感覺層與色素上皮層分離）時，於門診施行的視網膜雷射治療無法有效地使已經剝離的視網膜復位，因此此時雷射為「不適當」的處置，故選C。雷射一般僅用於未剝離的「單純視網膜裂孔」周圍以防剝離。已剝離的患者需要進行手術治療，常用的手術包括視網膜冷凍固定術、鞏膜扣環術或玻璃體切除術等。",
      "flashcard_front": "視網膜已剝離 / 門診雷射治療 / 冷凍固定 / 鞏膜扣環術 / 玻璃體切除",
      "flashcard_back": "視網膜已發生剝離時，門診雷射治療無效，須採用冷凍固定、鞏膜扣環或玻璃體切除術等手術方式進行復位。",
      "flashcard_summary": "視網膜已剝離 / 門診雷射治療 / 冷凍固定 / 鞏膜扣環術 / 玻璃體切除 -> 視網膜已發生剝離時，門診雷射治療無效，須採用冷凍固定、鞏膜扣環或玻璃體切除術等手術方式進行復位。"
    },
    {
      "question_id": "108-2_medicine-6_019",
      "question_number": 19,
      "correct_answer": "C",
      "category_group": "醫學（六）",
      "category": "耳鼻喉科",
      "category_confidence": "high",
      "key_point": "前庭神經分支的支配解剖區域。",
      "explanation": "前庭神經下分支主要支配後半規管（posterior semicircular canal）的壺腹脊以及球囊（saccule）的一部分，故選C。前庭神經上分支則支配上半規管、側（外）半規管的壺腹脊以及橢圓囊（utricle）。",
      "flashcard_front": "前庭神經下分支 / 支配區域 / 後半規管 / 球囊 / 上分支對比",
      "flashcard_back": "前庭神經下分支主要支配後半規管與球囊；上半規管、側半規管與橢圓囊則由前庭神經上分支支配。",
      "flashcard_summary": "前庭神經下分支 / 支配區域 / 後半規管 / 球囊 / 上分支對比 -> 前庭神經下分支主要支配後半規管與球囊；上半規管、側半規管與橢圓囊則由前庭神經上分支支配。"
    },
    {
      "question_id": "108-2_medicine-6_020",
      "question_number": 20,
      "correct_answer": "D",
      "category_group": "醫學（六）",
      "category": "耳鼻喉科",
      "category_confidence": "high",
      "key_point": "耳硬化症的典型耳鏡與臨床表徵。",
      "explanation": "Schwartze徵象（Schwartze sign），又稱為弗拉明哥紅（Flamingo flush），是指耳硬化症（otosclerosis）患者因耳蝸外側骨壁血管增生，在耳鏡下可見鼓膜後方呈現粉紅色或微紅色的斑塊，通常代表疾病處於活動期。聽神經瘤在耳鏡下多無異常；膽脂瘤可見白色碎屑或鼓膜穿孔；膽固醇肉芽腫則可呈現藍色鼓膜。",
      "flashcard_front": "耳鏡檢查 / Schwartze徵象 / 鼓膜後紅斑 / 耳硬化症",
      "flashcard_back": "耳鏡下見鼓膜後方呈現粉紅色斑塊（Schwartze徵象）是耳硬化症活動期的典型特徵。",
      "flashcard_summary": "耳鏡檢查 / Schwartze徵象 / 鼓膜後紅斑 / 耳硬化症 -> 耳鏡下見鼓膜後方呈現粉紅色斑塊（Schwartze徵象）是耳硬化症活動期的典型特徵。"
    },
    {
      "question_id": "108-2_medicine-6_021",
      "question_number": 21,
      "correct_answer": "D",
      "category_group": "醫學（六）",
      "category": "眼科",
      "category_confidence": "high",
      "key_point": "穿過眶上裂與圓孔的顱神經與血管結構。",
      "explanation": "三叉神經第二支即上頜支（maxillary branch, V2）是穿過圓孔（foramen rotundum），而不經過眶上裂（superior orbital fissure），因此選項D為正確答案。穿過眶上裂的構造包括動眼神經（CN III）、滑車神經（CN IV）、外展神經（CN VI）、三叉神經第一支即眼神經（V1），以及眼上靜脈（superior ophthalmic vein）等。",
      "flashcard_front": "眶上裂 / 穿過構造 / 三叉神經上頜支 / 圓孔交通",
      "flashcard_back": "三叉神經上頜支（V2）穿過圓孔而非眶上裂；CN III、IV、V1、VI及眼上靜脈穿過眶上裂。",
      "flashcard_summary": "眶上裂 / 穿過構造 / 三叉神經上頜支 / 圓孔交通 -> 三叉神經上頜支（V2）穿過圓孔而非眶上裂；CN III、IV、V1、VI及眼上靜脈穿過眶上裂。"
    },
    {
      "question_id": "108-2_medicine-6_022",
      "question_number": 22,
      "correct_answer": "A",
      "category_group": "醫學（六）",
      "category": "耳鼻喉科",
      "category_confidence": "high",
      "key_point": "遺傳性出血性血管擴張症（HHT）鼻腔護理與官方一律給分事由。",
      "explanation": "遺傳性出血性血管擴張症（HHT）常引起反覆嚴重的鼻出血。臨床上，使用生理食鹽水進行鼻腔沖洗與護理（選項A）是維持黏膜濕潤以預防出血的常用保養方式，並非不恰當；然而其他選項如內視鏡雷射、中隔黏膜整形術或血管栓塞亦是控制出血的治療手段。本題因選項敘述爭議，官方最後核定「一律給分」，此處依題目保留原答案A。",
      "flashcard_front": "HHT鼻出血 / 黏膜保濕 / 生理食鹽水 / 官方一律給分",
      "flashcard_back": "HHT鼻出血可用生理食鹽水保養黏膜，亦可使用雷射或手術止血；本題因選項爭議官方核定一律給分。",
      "flashcard_summary": "HHT鼻出血 / 黏膜保濕 / 生理食鹽水 / 官方一律給分 -> HHT鼻出血可用生理食鹽水保養黏膜，亦可使用雷射或手術止血；本題因選項爭議官方核定一律給分。"
    },
    {
      "question_id": "108-2_medicine-6_023",
      "question_number": 23,
      "correct_answer": "C",
      "category_group": "醫學（六）",
      "category": "耳鼻喉科",
      "category_confidence": "high",
      "key_point": "急性會厭炎的臨床診斷、X光徵象與急症處置。",
      "explanation": "咽喉內視鏡圖像顯示高度紅腫的會厭，這是急性會厭炎（acute epiglottitis）的典型表現。此病屬於耳鼻喉科急症，隨時可能發生急性呼吸道阻塞而致死，必須密切監控呼吸道，因此選項C正確。急性會厭炎的病原以細菌（如流感嗜血桿菌）最常見而非病毒；箭頭所指為會厭（epiglottis）腫脹而非甲狀軟骨；側頸部X光可見拇指徵象，而尖塔徵象（steeple sign）是哮吼（croup）的表現。",
      "flashcard_front": "急性會厭炎 / 喉部急症 / 急性呼吸道阻塞 / 側頸部X光拇指徵象",
      "flashcard_back": "急性會厭炎可引發急性呼吸道阻塞；側頸部X光呈現「拇指徵象」而非哮吼的「尖塔徵象」。",
      "flashcard_summary": "急性會厭炎 / 喉部急症 / 急性呼吸道阻塞 / 側頸部X光拇指徵象 -> 急性會厭炎可引發急性呼吸道阻塞；側頸部X光呈現「拇指徵象」而非哮吼的「尖塔徵象」。"
    },
    {
      "question_id": "108-2_medicine-6_024",
      "question_number": 24,
      "correct_answer": "C",
      "category_group": "醫學（六）",
      "category": "耳鼻喉科",
      "category_confidence": "high",
      "key_point": "聲帶麻痺的病因、側別分布與臨床特徵。",
      "explanation": "單側聲帶麻痺以左側較為常見，主要因為左側喉返神經的解剖路徑較長，繞過主動脈弓，更容易受到胸腔病變或手術壓迫，故選C。聲帶麻痺的主因為喉返神經受損，而非上喉神經。雙側聲帶麻痺時，聲帶常固定在正中位置，更容易導致呼吸困難與喘鳴；而單側聲帶麻痺因聲帶無法閉合，發聲障礙較為明顯。",
      "flashcard_front": "單側聲帶麻痺 / 喉返神經 / 左側多見 / 雙側與單側症狀",
      "flashcard_back": "聲帶麻痺主因喉返神經受損，左側因路徑長更易受壓；雙側麻痺易呼吸困難，單側麻痺易沙啞。",
      "flashcard_summary": "單側聲帶麻痺 / 喉返神經 / 左側多見 / 雙側與單側症狀 -> 聲帶麻痺主因喉返神經受損，左側因路徑長更易受壓；雙側麻痺易呼吸困難，單側麻痺易沙啞。"
    },
    {
      "question_id": "108-2_medicine-6_025",
      "question_number": 25,
      "correct_answer": "B",
      "category_group": "醫學（六）",
      "category": "耳鼻喉科",
      "category_confidence": "high",
      "key_point": "甲狀舌管囊腫的臨床表現、惡性轉化與手術方式。",
      "explanation": "甲狀舌管囊腫是頸部中線最常見的先天性腫塊。其惡性轉化率極低（小於1%），若發生惡性轉化，最常見的惡性細胞型態是甲狀腺乳突癌，而非鱗狀上皮細胞癌，故選項B錯誤。標準手術治療為 Sistrunk 手術；若先前發生過感染，由於周邊組織纖維化，術後復發率會顯著提高。",
      "flashcard_front": "甲狀舌管囊腫 / Sistrunk手術 / 惡性變乳突癌 / 感染與復發",
      "flashcard_back": "甲狀舌管囊腫惡性化最常見為甲狀腺乳突癌而非鱗狀癌；手術採用Sistrunk術式，有感染史者易復發。",
      "flashcard_summary": "甲狀舌管囊腫 / Sistrunk手術 / 惡性變乳突癌 / 感染與復發 -> 甲狀舌管囊腫惡性化最常見為甲狀腺乳突癌而非鱗狀癌；手術採用Sistrunk術式，有感染史者易復發。"
    },
    {
      "question_id": "108-2_medicine-6_026",
      "question_number": 26,
      "correct_answer": "D",
      "category_group": "醫學（六）",
      "category": "耳鼻喉科",
      "category_confidence": "high",
      "key_point": "人類乳突瘤病毒（HPV）在口咽癌中的病理角色與預後影響。",
      "explanation": "HPV陽性的口咽癌患者對化學治療及放射治療的反應通常較佳，且整體預後及生存率顯著優於HPV陰性的口咽癌，因此選項D的敘述為錯誤。在頭頸癌中，HPV相關性最高的是口咽癌；最密切的亞型為高危險型HPV第16型。致癌機轉上，HPV的E6蛋白質會與p53結合使其降解，E7蛋白質則會結合並抑制pRb的功能，導致細胞週期失控。",
      "flashcard_front": "HPV陽性口咽癌 / 預後較佳 / 放化療反應 / HPV-16 / E6與E7蛋白",
      "flashcard_back": "HPV陽性口咽癌對放化療敏感度高且預後較佳；E6抑制p53，E7抑制pRb。",
      "flashcard_summary": "HPV陽性口咽癌 / 預後較佳 / 放化療反應 / HPV-16 / E6與E7蛋白 -> HPV陽性口咽癌對放化療敏感度高且預後較佳；E6抑制p53，E7抑制pRb。"
    },
    {
      "question_id": "108-2_medicine-6_027",
      "question_number": 27,
      "correct_answer": "C",
      "category_group": "醫學（六）",
      "category": "耳鼻喉科",
      "category_confidence": "high",
      "key_point": "口腔黏膜白斑、紅斑與扁平苔蘚的病理及惡變風險。",
      "explanation": "扁平苔蘚（lichen planus）雖然主要是一種T細胞介導的慢性自體免疫炎性病灶，但目前已被公認具有惡性變化的潛能（癌變率約1%），需定期追蹤，因此選項C正確。口腔白斑主要病理變化是上皮角化過度或增生，而非功能萎縮；口腔紅斑的惡性轉化機率遠高於白斑；口腔黏膜下纖維化屬於癌前狀態，同樣具有高度惡性變化的風險。",
      "flashcard_front": "口腔癌前病變 / 扁平苔蘚惡變潛能 / 紅斑與白斑惡變率 / 黏膜下纖維化",
      "flashcard_back": "扁平苔蘚具惡變潛能；口腔紅斑惡變率高於白斑；黏膜下纖維化屬癌前狀態且有惡變可能。",
      "flashcard_summary": "口腔癌前病變 / 扁平苔蘚惡變潛能 / 紅斑與白斑惡變率 / 黏膜下纖維化 -> 扁平苔蘚具惡變潛能；口腔紅斑惡變率高於白斑；黏膜下纖維化屬癌前狀態且有惡變可能。"
    },
    {
      "question_id": "108-2_medicine-6_028",
      "question_number": 28,
      "correct_answer": "B",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "全素飲食孕婦面臨的營養素缺乏風險與對胎兒的影響。",
      "explanation": "維生素B12主要存在於動物性食物中。全素的妊娠婦女由於完全不攝取動物性食品，最容易面臨維生素B12缺乏，這可能導致孕婦發生巨幼紅血球性貧血，並增加胎兒神經管缺陷或發育遲緩的風險，故選B。維生素A、C、K均可自植物性食物中獲得，較不易因全素而缺乏。",
      "flashcard_front": "全素孕婦 / 維生素B12缺乏 / 巨幼紅血球貧血 / 胎兒發育影響",
      "flashcard_back": "全素孕婦最易缺乏主要來自動物食品的維生素B12，應適當補充以防貧血及胎兒神經發育異常。",
      "flashcard_summary": "全素孕婦 / 維生素B12缺乏 / 巨幼紅血球貧血 / 胎兒發育影響 -> 全素孕婦最易缺乏主要來自動物食品的維生素B12，應適當補充以防貧血及胎兒神經發育異常。"
    },
    {
      "question_id": "108-2_medicine-6_029",
      "question_number": 29,
      "correct_answer": "B",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "真空吸引術助產的適宜負壓設定與併發症預防。",
      "explanation": "在進行真空吸引術助產時，為了避免造成新生兒頭皮撕裂傷、頭皮血腫或顱內出血，抽吸負壓通常建議設定在 0.4 到 0.6 kg/cm² 之間，因此選項B是臨床最適合且安全的負壓上限。壓力過低容易滑脫，壓力過高則會對胎兒頭部造成嚴重機械性損傷。",
      "flashcard_front": "真空吸引術 / 助產負壓限制 / 0.6 kg/cm² / 胎兒頭部併發症",
      "flashcard_back": "真空吸引助產的適當負壓為 0.4-0.6 kg/cm²，過高易引發胎兒頭皮血腫或顱內出血。",
      "flashcard_summary": "真空吸引術 / 助產負壓限制 / 0.6 kg/cm² / 胎兒頭部併發症 -> 真空吸引助產的適當負壓為 0.4-0.6 kg/cm²，過高易引發胎兒頭皮血腫或顱內出血。"
    },
    {
      "question_id": "108-2_medicine-6_030",
      "question_number": 30,
      "correct_answer": "C",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "巴陶氏症候群（Trisomy 13）的典型先天畸形表徵。",
      "explanation": "Trisomy 13（Patau syndrome，巴陶氏症候群）的典型臨床異常包括前腦發育畸形、小頭畸形（microcephaly）而非大頭畸形（macrocephaly，選項C錯誤，為本題答案）。其他常見的特徵性異常包括唇顎裂（cleft lip/palate）、臍膨出（omphalocele）、多指（趾）畸形、橈骨發育不良（radial bone aplasia）、全前腦畸形以及先天性心臟病等。",
      "flashcard_front": "Trisomy 13 / Patau syndrome / 小頭畸形 (非大頭) / 唇顎裂 / 臍膨出",
      "flashcard_back": "Trisomy 13 典型特徵為小頭畸形（非大頭）、全前腦畸形、唇顎裂、多指及臍膨出。",
      "flashcard_summary": "Trisomy 13 / Patau syndrome / 小頭畸形 (非大頭) / 唇顎裂 / 臍膨出 -> Trisomy 13 典型特徵為小頭畸形（非大頭）、全前腦畸形、唇顎裂、多指及臍膨出。"
    }
  ]
}

# 108-2_medicine-6_batch-003 (Q31 - Q45)
batch_108_2_med6_003 = {
  "dataset_id": "108-2_medicine-6",
  "batch_id": "108-2_medicine-6_batch-003",
  "items": [
    {
      "question_id": "108-2_medicine-6_031",
      "question_number": 31,
      "correct_answer": "D",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "母乳缺乏維生素K及新生兒預防注射原則。",
      "explanation": "母乳的營養價值極高，但其所含的維生素K與維生素D含量均偏低。由於人體腸道菌群尚未建立，且胎盤轉運維生素K效率差，初生嬰兒僅吃母乳極易引發維生素K缺乏性出血（晚發性新生兒出血症），因此臨床上常規在新生兒出生時給予維生素K1注射。雖然母乳也缺乏維生素D，但本題官方標準答案為D。",
      "flashcard_front": "母乳缺乏 / 維生素K / 新生兒出血症 / 維生素K1預防注射",
      "flashcard_back": "母乳中維生素K含量低，為預防新生兒出血，出生後常規給予維生素K1注射；官方核定缺乏之維他命為Vit.K。",
      "flashcard_summary": "母乳缺乏 / 維生素K / 新生兒出血症 / 維生素K1預防注射 -> 母乳中維生素K含量低，為預防新生兒出血，出生後常規給予維生素K1注射；官方核定缺乏之維他命為Vit.K。"
    },
    {
      "question_id": "108-2_medicine-6_032",
      "question_number": 32,
      "correct_answer": "C",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "產科超音波雙十字測量的解剖構造。",
      "explanation": "產科超音波影像中，若雙十字標記位於胎兒的長骨兩端，測量的便是股骨長度（Femur Length, FL），常用於評估胎兒的發育與預估體重，故選C。其他指標如 BPD（雙頂徑）是測量頭部寬度，AC（腹圍）是測量腹部橫切面周長，NT（頸部透明帶）是在第一孕期測量胎兒頸部後方的皮下積水厚度。",
      "flashcard_front": "產科超音波 / 股骨長度 (FL) / 長骨測量 / 估計胎兒體重",
      "flashcard_back": "產科超音波雙十字測量長骨兩端為股骨長度（FL），與BPD、AC等指標合用於預估胎兒體重。",
      "flashcard_summary": "產科超音波 / 股骨長度 (FL) / 長骨測量 / 估計胎兒體重 -> 產科超音波雙十字測量長骨兩端為股骨長度（FL），與BPD、AC等指標合用於預估胎兒體重。"
    },
    {
      "question_id": "108-2_medicine-6_033",
      "question_number": 33,
      "correct_answer": "A",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "卵巢腫瘤合併扭轉的臨床診斷與腹腔鏡特徵。",
      "explanation": "患者突發右下腹劇烈疼痛，合併噁心嘔吐，內診與超音波提示右側附屬器有約7-8公分大小的腫塊，且有壓痛。腹腔鏡下可見右側卵巢及輸卵管發生順時針或逆時針的扭轉，並因血液回流受阻呈現發紺、紫黑色（暗黑色），此為典型的卵巢腫瘤合併扭轉，故選A。輸卵管外孕通常呈暗紅色積血或破裂；急性盲腸炎侷限於闌尾紅腫；子宮肌瘤紅色變性多在孕期發生，外觀呈子宮壁腫塊。",
      "flashcard_front": "右下腹急痛 / 附件腫塊 / 腹腔鏡發紺暗黑 / 卵巢腫瘤扭轉",
      "flashcard_back": "附件區大腫塊伴隨急性下腹痛、噁心，且腹腔鏡下見發紺暗黑腫塊，首選診斷為卵巢腫瘤合併扭轉。",
      "flashcard_summary": "右下腹急痛 / 附件腫塊 / 腹腔鏡發紺暗黑 / 卵巢腫瘤扭轉 -> 附件區大腫塊伴隨急性下腹痛、噁心，且腹腔鏡下見發紺暗黑腫塊，首選診斷為卵巢腫瘤合併扭轉。"
    },
    {
      "question_id": "108-2_medicine-6_034",
      "question_number": 34,
      "correct_answer": "C",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "卵巢成熟畸胎瘤的病理組成與雙側發生率。",
      "explanation": "卵巢實質腫瘤內含有骨頭、牙齒及毛髮等結構，是典型的卵巢成熟畸胎瘤（又稱皮樣囊腫）。這是最常見的良性卵巢生殖細胞腫瘤，其在雙側卵巢同時發生的機率約為 10% 到 15%，故選項C正確。小於3%過低，而50%顯著過高。",
      "flashcard_front": "成熟畸胎瘤 / 皮樣囊腫 / 骨頭與牙齒 / 雙側發生率 10%-15%",
      "flashcard_back": "卵巢成熟畸胎瘤含有外胚層成分（如骨頭、牙齒），其雙側發生的機率約為 10%-15%。",
      "flashcard_summary": "成熟畸胎瘤 / 皮樣囊腫 / 骨頭與牙齒 / 雙側發生率 10%-15% -> 卵巢成熟畸胎瘤含有外胚層成分（如骨頭、牙齒），其雙側發生的機率約為 10%-15%。"
    },
    {
      "question_id": "108-2_medicine-6_035",
      "question_number": 35,
      "correct_answer": "B",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "習慣性流產夫妻的染色體異常類型。",
      "explanation": "習慣性流產（反覆流產，定義為連續3次或以上自然流產）患者中，約有 2% 到 5% 是由於夫妻中一方攜帶染色體平衡易位（balanced translocation，選項B正確）。平衡易位攜帶者本身在外觀與生理功能上完全正常，但在減數分裂形成配子時，極易產生染色體不平衡的配子，導致胚胎無法存活而流產。Trisomy 18、Turner 或 Klinefelter 症候群多為非整倍體突變，極少以夫妻一方攜帶者的形式導致反覆流產。",
      "flashcard_front": "習慣性流產 / 夫妻染色體 / 平衡易位 / 配子染色體不平衡",
      "flashcard_back": "夫妻一方若有染色體平衡易位（balanced translocation），極易因配子染色體不平衡而導致反覆流產。",
      "flashcard_summary": "習慣性流產 / 夫妻染色體 / 平衡易位 / 配子染色體不平衡 -> 夫妻一方若有染色體平衡易位（balanced translocation），極易因配子染色體不平衡而導致反覆流產。"
    },
    {
      "question_id": "108-2_medicine-6_036",
      "question_number": 36,
      "correct_answer": "B",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "晚期上皮性卵巢癌的一線化療組合。",
      "explanation": "目前治療晚期上皮性卵巢癌的標準第一線化學治療方案，是靜脈給予鉑類藥物卡鉑（carboplatin）聯合紫杉醇（paclitaxel），即 Paclitaxel + Carboplatin（TC 方案），故選B。此方案相較於舊有的 Cisplatin 組合具有較低的腎毒性與噁心嘔吐副作用，且療效極佳。",
      "flashcard_front": "晚期上皮性卵巢癌 / 第一線化療 / 卡鉑 + 紫杉醇 / TC方案",
      "flashcard_back": "晚期上皮性卵巢癌首選一線化療方案為卡鉑（carboplatin）聯合紫杉醇（paclitaxel）。",
      "flashcard_summary": "晚期上皮性卵巢癌 / 第一線化療 / 卡鉑 + 紫杉醇 / TC方案 -> 晚期上皮性卵巢癌首選一線化療方案為卡鉑（carboplatin）聯合紫杉醇（paclitaxel）。"
    },
    {
      "question_id": "108-2_medicine-6_037",
      "question_number": 37,
      "correct_answer": "C",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "卵巢卵黃囊瘤的保留生育功能手術與術後化療原則。",
      "explanation": "卵巢卵黃囊瘤（yolk sac tumor，又稱內胚竇瘤）是一種惡性程度高但對化療高度敏感的惡性生殖細胞腫瘤。由於多為單側且好發於年輕女性，目前的標準治療是行「保留生育功能手術」（保留子宮及健側卵巢），不論期別或術中是否有囊腫破裂，術後均應儘快給予聯合化學治療（常用 BEP 方案），故選C。",
      "flashcard_front": "卵黃囊瘤 / yolk sac tumor / 保留生育功能手術 / 術後聯合化療",
      "flashcard_back": "卵黃囊瘤對化療極敏感，處置原則為行保留子宮與對側卵巢的手術，術後必須給予聯合化療。",
      "flashcard_summary": "卵黃囊瘤 / yolk sac tumor / 保留生育功能手術 / 術後聯合化療 -> 卵黃囊瘤對化療極敏感，處置原則為行保留子宮與對側卵巢的手術，術後必須給予聯合化療。"
    },
    {
      "question_id": "108-2_medicine-6_038",
      "question_number": 38,
      "correct_answer": "A",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "晚期卵巢癌轉診後的手術減積處置時機。",
      "explanation": "當晚期卵巢癌患者在外院接受剖腹探查且傷口僅簡單關閉並伴隨滲血時，轉診至醫學中心後，最適合的處置是立即送至開刀房重新開腹，一方面能止血並妥善處理傷口，另一方面能直接進行最大程度的腫瘤細胞減積手術（debulking surgery），以改善預後，故選A。暫緩手術進行化療或做影像檢查會耽誤止血時機並增加腹膜炎風險。",
      "flashcard_front": "外院剖腹探查 / 傷口滲血轉診 / 剖腹減積手術 / 立即手術處置",
      "flashcard_back": "外院開腹探查未切除且傷口滲血者，應立即送至手術室止血並完成剖腹減積手術。",
      "flashcard_summary": "外院剖腹探查 / 傷口滲血轉診 / 剖腹減積手術 / 立即手術處置 -> 外院開腹探查未切除且傷口滲血者，應立即送至手術室止血並完成剖腹減積手術。"
    },
    {
      "question_id": "108-2_medicine-6_039",
      "question_number": 39,
      "correct_answer": "D",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "邊緣性卵巢腫瘤與浸潤性癌的病理診斷關鍵。",
      "explanation": "邊緣惡性卵巢腫瘤（borderline tumors）具有惡性腫瘤的部分上皮特徵，如乳突狀結構、偽多層上皮（選項A）、細胞核異型性（選項B）及有絲分裂增加（選項C）。但其與浸潤性癌最關鍵的鑑別點在於「無基質侵犯（absence of stromal invasion）」，一旦出現明顯的基質侵犯（stromal invasion）即診斷為浸潤性癌，故選D為非診斷條件。",
      "flashcard_front": "邊緣惡性卵巢腫瘤 / 診斷條件 / 基質侵犯 / 浸潤性癌鑑別",
      "flashcard_back": "邊緣性卵巢腫瘤可有細胞異型與分裂增加，但「無基質侵犯」；一旦有基質侵犯則診斷為癌。",
      "flashcard_summary": "邊緣惡性卵巢腫瘤 / 診斷條件 / 基質侵犯 / 浸潤性癌鑑別 -> 邊緣性卵巢腫瘤可有細胞異型與分裂增加，但「無基質侵犯」；一旦有基質侵犯則診斷為癌。"
    },
    {
      "question_id": "108-2_medicine-6_040",
      "question_number": 40,
      "correct_answer": "B",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "懷孕10週胎兒的生長發育特徵與CRL大小。",
      "explanation": "在懷孕10週時，胎兒的頭臀徑（CRL）通常大約只有 3 到 4 公分左右，不可能達到 7 公分（7公分通常對應懷孕13週左右），因此選項B最不符合。此時手肘已經可以彎曲（選項A），橫膈膜已經形成（選項C），心臟的基本結構也已經發育完成（選項D）。",
      "flashcard_front": "懷孕10週 / 頭臀徑 (CRL) / 3-4公分 / 手肘彎曲與橫膈膜形成",
      "flashcard_back": "懷孕10週時胎兒CRL約3-4公分，達7公分不合常理；此時四肢關節、橫膈膜與心臟已基本形成。",
      "flashcard_summary": "懷孕10週 / 頭臀徑 (CRL) / 3-4公分 / 手肘彎曲與橫膈膜形成 -> 懷孕10週時胎兒CRL約3-4公分，達7公分不合常理；此時四肢關節、橫膈膜與心臟已基本形成。"
    },
    {
      "question_id": "108-2_medicine-6_041",
      "question_number": 41,
      "correct_answer": "B",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "處理肩難產的 McRoberts 助產手法。",
      "explanation": "圖示手法為McRoberts助產法，其操作為將產婦雙腿過度屈曲，向腹部方向推壓（貼近胸部）。此動作能使骨盆入口傾斜度減小、薦骨平坦化，進而增加骨盆的前後徑，有利於嵌頓的前肩娩出，是肩難產最常用且首選的輔助方法，故選B。Rubin 與 Woods 手法是在陰道內旋轉胎兒肩膀，Fundal pressure（宮底壓迫）在肩難產中屬禁忌。",
      "flashcard_front": "肩難產 / 大腿屈曲貼胸 / McRoberts手法 / 骨盆前後徑增加",
      "flashcard_back": "處理肩難產首選將產婦雙大腿向腹部屈曲貼胸的 McRoberts 助產法，可增加骨盆前後徑。",
      "flashcard_summary": "肩難產 / 大腿屈曲貼胸 / McRoberts手法 / 骨盆前後徑增加 -> 處理肩難產首選將產婦雙大腿向腹部屈曲貼胸的 McRoberts 助產法，可增加骨盆前後徑。"
    },
    {
      "question_id": "108-2_medicine-6_042",
      "question_number": 42,
      "correct_answer": "D",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "生產會陰部第四度裂傷的解剖累及深度。",
      "explanation": "產科會陰裂傷共分四度：一度僅限於陰道黏膜或會陰皮膚；二度延伸至會陰體筋膜及肌肉層，但未波及肛門括約肌；三度裂傷波及部分或全部肛門外/內括約肌；四度裂傷最嚴重，深度穿透肛門括約肌並累及直腸黏膜層（rectal mucosa）或肛門上皮，故選D。",
      "flashcard_front": "會陰裂傷 / 四度分級 / 肛門括約肌 / 直腸黏膜層 (四度)",
      "flashcard_back": "會陰第四度裂傷深度已穿透肛門括約肌並累及直腸黏膜層；三度累及肛門括約肌但未傷及直腸黏膜。",
      "flashcard_summary": "會陰裂傷 / 四度分級 / 肛門括約肌 / 直腸黏膜層 (四度) -> 會陰第四度裂傷深度已穿透肛門括約肌並累及直腸黏膜層；三度累及肛門括約肌但未傷及直腸黏膜。"
    },
    {
      "question_id": "108-2_medicine-6_043",
      "question_number": 43,
      "correct_answer": "A",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "過期妊娠前期且胎兒監測正常的處置原則。",
      "explanation": "產婦目前僅超過預產期2天（40週又2天，未達42週之過期妊娠標準），且胎心音監測呈良性反應（reactive），羊水量正常（最大垂直水深 3.6 cm > 2 cm），預估胎兒體重適中。在無其他母嬰併發症指徵下，此時不需住院引產或剖腹產，最適當的處置是給予衛教並安排門診定期追蹤（如每週2次NST及羊水測量），故選A。",
      "flashcard_front": "妊娠40+2週 / NST反應良好 / 羊水量正常 / 門診追蹤觀察",
      "flashcard_back": "預產期過2天且胎兒監測（NST、羊水量）正常時，無引產指徵，應於門診密切追蹤。",
      "flashcard_summary": "妊娠40+2週 / NST反應良好 / 羊水量正常 / 門診追蹤觀察 -> 預產期過2天且胎兒監測（NST、羊水量）正常時，無引產指徵，應於門診密切追蹤。"
    },
    {
      "question_id": "108-2_medicine-6_044",
      "question_number": 44,
      "correct_answer": "C",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "孕期疫苗接種的活性減毒疫苗禁忌。",
      "explanation": "懷孕期間絕對禁止接種的是「活性減毒疫苗」，例如水痘疫苗和麻疹腮腺炎德國麻疹混合疫苗（MMR），因為減毒病毒有理論上通過胎盤感染胎兒的風險。而滅活疫苗或類毒素如流感疫苗（選項A）、百日咳-白喉-破傷風混合疫苗（Tdap，選項D）在孕期是安全且被推薦接種的。狂犬病疫苗（選項B）為滅活疫苗，若有暴露風險亦可在孕期安全施打。",
      "flashcard_front": "孕期疫苗禁忌 / 活性減毒疫苗 / 水痘疫苗 / 滅活疫苗安全",
      "flashcard_back": "孕期禁用活性減毒疫苗（如水痘、MMR疫苗），以防病毒感染胎兒；流感與Tdap等滅活疫苗可安全施打。",
      "flashcard_summary": "孕期疫苗禁忌 / 活性減毒疫苗 / 水痘疫苗 / 滅活疫苗安全 -> 孕期禁用活性減毒疫苗（如水痘、MMR疫苗），以防病毒感染胎兒；流感與Tdap等滅活疫苗可安全施打。"
    },
    {
      "question_id": "108-2_medicine-6_045",
      "question_number": 45,
      "correct_answer": "A",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "Q-tip test 診斷尿道過度移動的角度界限。",
      "explanation": "棉棒測試（Q-tip test）常用於評估女性應力性尿失禁患者的尿道下垂與過度移動度。測試時將棉棒置入尿道尿道膀胱接合處，測量靜止與用力排尿（straining）時的角度變化。當靜止尿道角度大於30度或最大用力時的偏斜角度大於30度（resting > 30 degrees or straining > 30 degrees）時，即可診斷為尿道過度移動，故選A。",
      "flashcard_front": "Q-tip測試 / 尿道過度移動 / 靜止角度 >30度 / 用力角度 >30度",
      "flashcard_back": "診斷尿道過度移動的角度界限為：靜止尿道角度 > 30度或最大用力角度 > 30度（or關係）。",
      "flashcard_summary": "Q-tip測試 / 尿道過度移動 / 靜止角度 >30度 / 用力角度 >30度 -> 診斷尿道過度移動的角度界限為：靜止尿道角度 > 30度或最大用力角度 > 30度（or關係）。"
    }
  ]
}

# 108-2_medicine-6_batch-004 (Q46 - Q60)
batch_108_2_med6_004 = {
  "dataset_id": "108-2_medicine-6",
  "batch_id": "108-2_medicine-6_batch-004",
  "items": [
    {
      "question_id": "108-2_medicine-6_046",
      "question_number": 46,
      "correct_answer": "B",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "人類乳突病毒（HPV）的高危險與低危險型別與特徵。",
      "explanation": "HPV第6型與第11型屬於「低危險型」病毒，主要引起生殖器疣（尖形濕疣），極少導致癌症，故選項B敘述錯誤。HPV第16型與第18型則屬於「高危險型」，其中第16型是子宮頸癌及癌前病變最常見的型別。病理切片上，凹空細胞（koilocytosis）是HPV感染的特徵性病變。致癌蛋白為E6（抑制p53）與E7（抑制pRb）。",
      "flashcard_front": "HPV型別 / 6與11型 (低危) / 16與18型 (高危) / 凹空細胞",
      "flashcard_back": "HPV 6與11型為低危險型（引起濕疣）；16與18型為高危險型（引起子宮頸癌）；koilocytosis為特徵病理。",
      "flashcard_summary": "HPV型別 / 6與11型 (低危) / 16與18型 (高危) / 凹空細胞 -> HPV 6與11型為低危險型（引起濕疣）；16與18型為高危險型（引起子宮頸癌）；koilocytosis為特徵病理。"
    },
    {
      "question_id": "108-2_medicine-6_047",
      "question_number": 47,
      "correct_answer": "D",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "外陰癌的個體化治療與淋巴結處置原則。",
      "explanation": "現代外陰癌的治療已走向個體化（individualization），「常規」執行廣泛性外陰根除術及雙側腹股溝淋巴結摘除術因會造成嚴重的傷口併發症與下肢淋巴水腫，目前已不再被常規推薦，故選項D為不包括之原則（本題答案）。對於早期、局灶性且無對側轉移跡象的病患，可採取局部廣泛切除及單側或前哨淋巴結切除；而針對腹股溝淋巴結轉移大於1個的患者，術後放射治療是必須的（選項C）。",
      "flashcard_front": "外陰癌手術 / 腹股溝淋巴結切除 / 個體化治療 / 常規根除術避免",
      "flashcard_back": "外陰癌處置強調個體化，不建議常規進行廣泛根除及雙側淋巴結摘除，以減少術後併發症。",
      "flashcard_summary": "外陰癌手術 / 腹股溝淋巴結切除 / 個體化治療 / 常規根除術避免 -> 外陰癌處置強調個體化，不建議常規進行廣泛根除及雙側淋巴結摘除，以減少術後併發症。"
    },
    {
      "question_id": "108-2_medicine-6_048",
      "question_number": 48,
      "correct_answer": "B",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "不同妊娠滋養細胞腫瘤對化療的反應差異。",
      "explanation": "胎盤部位滋養細胞腫瘤（PSTT）是一種罕見的GTN類型，由中間型滋養細胞構成。與絨毛膜癌（choriocarcinoma）等高度對化療敏感的GTN不同，PSTT對化療的反應相對較差（具有原發性抗藥性），因此其首選且最主要的治療方式是手術切除（子宮全切除術），故選B。",
      "flashcard_front": "妊娠滋養細胞腫瘤 / PSTT / 化療反應差 / 手術切除子宮",
      "flashcard_back": "胎盤部位滋養細胞腫瘤（PSTT）對化療敏感度差，臨床上首選以手術切除（子宮全切）為主。",
      "flashcard_summary": "妊娠滋養細胞腫瘤 / PSTT / 化療反應差 / 手術切除子宮 -> 胎盤部位滋養細胞腫瘤（PSTT）對化療敏感度差，臨床上首選以手術切除（子宮全切）為主。"
    },
    {
      "question_id": "108-2_medicine-6_049",
      "question_number": 49,
      "correct_answer": "A",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "雙側卵巢發生惡性生殖細胞瘤的機率特徵。",
      "explanation": "卵巢惡性生殖細胞腫瘤大多為單側生長。但在所有惡性生殖細胞瘤中，無性細胞瘤（dysgerminoma，又稱無性胚胎瘤）是唯一最常發生雙側病變的類型，雙側發生率約為 10% 到 15%，因此在手術中必須特別仔細探查對側卵巢，故選A。而內胚竇瘤（卵黃囊瘤）、多胚瘤等其他類型則幾乎均為單側，極罕見雙側。",
      "flashcard_front": "惡性生殖細胞瘤 / 雙側發生率 / 無性細胞瘤 (dysgerminoma)",
      "flashcard_back": "無性細胞瘤（dysgerminoma）在惡性生殖細胞瘤中雙側發生率最高（10-15%），術中需探查對側。",
      "flashcard_summary": "惡性生殖細胞瘤 / 雙側發生率 / 無性細胞瘤 (dysgerminoma) -> 無性細胞瘤（dysgerminoma）在惡性生殖細胞瘤中雙側發生率最高（10-15%），術中需探查對側。"
    },
    {
      "question_id": "108-2_medicine-6_050",
      "question_number": 50,
      "correct_answer": "A",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "多毛症的抗雄性素藥物治療與孕酮的使用限制。",
      "explanation": "多毛症的藥物治療主要以抑制雄性素產生或阻斷雄性素受體為主。常用的藥物包括雄性素受體拮抗劑：Spironolactone（螺內酯）、Cyproterone acetate（環丙孕酮）以及 Flutamide（氟他胺）。Medroxyprogesterone acetate（MPA）是一種孕激素，本身具有微弱的雄性素活性，不能用作多毛症的標準治療，故選A為錯誤。",
      "flashcard_front": "多毛症 / 抗雄性素藥物 / Spironolactone / MPA不適用",
      "flashcard_back": "多毛症治療使用抗雄性素藥物（Spironolactone、Cyproterone、Flutamide）；MPA因具微弱雄性素作用而不適用。",
      "flashcard_summary": "多毛症 / 抗雄性素藥物 / Spironolactone / MPA不適用 -> 多毛症治療使用抗雄性素藥物（Spironolactone、Cyproterone、Flutamide）；MPA因具微弱雄性素作用而不適用。"
    },
    {
      "question_id": "108-2_medicine-6_051",
      "question_number": 51,
      "correct_answer": "C",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "泌乳激素腺瘤的多巴胺受體促效劑治療與腫瘤縮小效應。",
      "explanation": "多巴胺受體促效劑（Dopamine agonists）如 bromocriptine（溴隱亭）和 cabergoline（卡麥角林）是治療泌乳激素腺瘤的第一線首選藥物，這類藥物「能非常有效地縮小腫瘤體積」，因此選項C敘述「無法有效地縮小腫瘤」為錯誤。Bromocriptine 需每日口服（短效）；Cabergoline 活性高、副作用小且半衰期長（每週僅需服用1-2次）；若治療後血中濃度正常且腫瘤消失達2年以上，可評估停藥。",
      "flashcard_front": "泌乳激素腺瘤 / 多巴胺促效劑 / 縮小腫瘤 / 溴隱亭與卡麥角林",
      "flashcard_back": "多巴胺促效劑（溴隱亭、卡麥角林）能有效抑制泌乳激素分泌並顯著縮小腺瘤體積，為一線治療。",
      "flashcard_summary": "泌乳激素腺瘤 / 多巴胺促效劑 / 縮小腫瘤 / 溴隱亭與卡麥角林 -> 多巴胺促效劑（溴隱亭、卡麥角林）能有效抑制泌乳激素分泌並顯著縮小腺瘤體積，為一線治療。"
    },
    {
      "question_id": "108-2_medicine-6_052",
      "question_number": 52,
      "correct_answer": "C",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "多囊性卵巢症候群（PCOS）的臨床診斷與檢查項目。",
      "explanation": "該患者表現為肥胖、痤瘡（青春痘）、月經稀發，臨床上高度懷疑為多囊性卵巢症候群（PCOS）。診斷 PCOS 需測定血中 E2、FSH、LH 濃度以排除其他內分泌疾病（選項A），做尿液孕試排除懷孕（選項B），並進行婦科超音波檢查觀察是否有卵巢多囊樣改變（選項D）。然而，染色體檢查（選項C）在此類典型高雄性素及排卵障礙病患中並非必要或常規的診斷檢查。",
      "flashcard_front": "PCOS疑似 / 性激素測定 / 超音波檢查 / 染色體檢查非必要",
      "flashcard_back": "PCOS診斷主要依據排卵異常、雄素高及超音波多囊樣變，染色體檢查非必要項目。",
      "flashcard_summary": "PCOS疑似 / 性激素測定 / 超音波檢查 / 染色體檢查非必要 -> PCOS診斷主要依據排卵異常、雄素高及超音波多囊樣變，染色體檢查非必要項目。"
    },
    {
      "question_id": "108-2_medicine-6_053",
      "question_number": 53,
      "correct_answer": "B",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "試管嬰兒超排卵中促濾泡成熟素（FSH）的作用。",
      "explanation": "在自然的月經週期中，隨著濾泡生長，FSH 會下降，導致只有一個優勢濾泡能存活。在試管嬰兒控制性超排卵（COH）療程中，額外給予高劑量的外源性促濾泡成熟素（FSH），能使血液中 FSH 濃度維持在較高的治療窗內，從而克服濾泡閉鎖的機制，支持多個長大中的濾泡同時發育成熟，故選B。",
      "flashcard_front": "試管嬰兒 / 控制性超排卵 / FSH高濃度 / 克服濾泡閉鎖",
      "flashcard_back": "試管嬰兒超排卵主要藉由額外給予高濃度外源性 FSH，支持多顆濾泡同時克服閉鎖發育成熟。",
      "flashcard_summary": "試管嬰兒 / 控制性超排卵 / FSH高濃度 / 克服濾泡閉鎖 -> 試管嬰兒超排卵主要藉由額外給予高濃度外源性 FSH，支持多顆濾泡同時克服閉鎖發育成熟。"
    },
    {
      "question_id": "108-2_medicine-6_054",
      "question_number": 54,
      "correct_answer": "B",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "胚胎植入前基因診斷（PGD/PGT）的臨床特性。",
      "explanation": "PGD 需要與試管嬰兒療程配合（選項A），以篩選並排除染色體異常的胚胎（選項C），進而減少習慣性流產婦女的流產率（選項D）。當檢測結果為正常女性（46, XX）時，這代表胚胎本身染色體正常，並不意味著最有可能是因為母親細胞污染所造成，故選項B的說法是錯誤的（通常有嚴格的切片防污染流程）。",
      "flashcard_front": "PGD/PGT / 習慣性流產 / 46,XX結果正常 / 染色體篩檢",
      "flashcard_back": "PGD可有效排除染色體異常胚胎以降低流產率；檢測結果46,XX為正常的胚胎染色體，非母體污染所致。",
      "flashcard_summary": "PGD/PGT / 習慣性流產 / 46,XX結果正常 / 染色體篩檢 -> PGD可有效排除染色體異常胚胎以降低流產率；檢測結果46,XX為正常的胚胎染色體，非母體污染所致。"
    },
    {
      "question_id": "108-2_medicine-6_055",
      "question_number": 55,
      "correct_answer": "D",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "特納氏症候群的性激素特徵與鑲嵌型自發月經可能性。",
      "explanation": "此患者矮小、無第二性徵、蹼狀頸及先天性心臟病史，結合染色體報告（45, X），診斷為特納氏症候群（Turner syndrome）。45, X患者由於卵巢早衰（呈條索狀性腺），大部分無自發性月經；但若為鑲嵌型（如45, X/46, XX），患者體內仍保留部分正常卵巢組織，約有 10% 到 20% 仍可能有自發性青春期發育與正常月經，故選D。其血中 FSH/LH 會因失去雌激素負回饋而顯著升高，而非三者皆低；若不含Y染色體成分則不需切除性腺；部分患者可有發育不良的幼稚子宮，而非全無子宮。",
      "flashcard_front": "特納氏症候群 / 45,X / 條索狀性腺 / 鑲嵌型自發月經 / FSH升高",
      "flashcard_back": "特納氏症候群血中FSH/LH極高、雌素低；若無Y染色體不需切除性腺；鑲嵌型可能有正常月經。",
      "flashcard_summary": "特納氏症候群 / 45,X / 條索狀性腺 / 鑲嵌型自發月經 / FSH升高 -> 特納氏症候群血中FSH/LH極高、雌素低；若無Y染色體不需切除性腺；鑲嵌型可能有正常月經。"
    },
    {
      "question_id": "108-2_medicine-6_056",
      "question_number": 56,
      "correct_answer": "B",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "預防卵巢過度刺激症候群（OHSS）的臨床措施。",
      "explanation": "OHSS 是促排卵療程的嚴重併發症，其發生高度依賴 hCG 的作用。利用 GnRH agonist 代替 hCG 來進行成熟卵子的誘發（trigger），可大幅減少內源性 LH 樣活性的持續時間；再配合「全胚胎冷凍」避免當週期植入（防止懷孕後胎盤分泌內源性 hCG），可將 OHSS 的發生率降至接近於零，故選B。增加促性腺激素劑量、使用長療程或在黃體期注射 hCG 皆會顯著增加 OHSS 的風險。",
      "flashcard_front": "OHSS預防 / GnRH agonist 破卵 / 全胚胎冷凍 / 避免當期植入 / hCG禁忌",
      "flashcard_back": "預防OHSS首選以 GnRH agonist 代替 hCG 誘發排卵，並行全胚胎冷凍以避免當期懷孕加重症狀。",
      "flashcard_summary": "OHSS預防 / GnRH agonist 破卵 / 全胚胎冷凍 / 避免當期植入 / hCG禁忌 -> 預防OHSS首選以 GnRH agonist 代替 hCG 誘發排卵，並行全胚胎冷凍以避免當期懷孕加重症狀。"
    },
    {
      "question_id": "108-2_medicine-6_057",
      "question_number": 57,
      "correct_answer": "B",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "卵母細胞完成第一次與第二次減數分裂的時機。",
      "explanation": "初級卵母細胞在胚胎時期即停滯在第一次減數分裂前期。在排卵前，由於黃體化激素潮放（LH surge）刺激，初級卵母細胞才會恢復並完成第一次減數分裂，排出第一極體，並隨即進入第二次減數分裂，再次停滯在分裂中期，故選B。精子進入卵子（受精時）才會促使卵子完成第二次減數分裂。",
      "flashcard_front": "第一次減數分裂完成 / LH surge / 第二次減數分裂停滯 / 受精完成減數II",
      "flashcard_back": "初級卵母細胞在 LH surge 時完成第一次減數分裂；次級卵母細胞停在第二次減數分裂中期，受精時才完成。",
      "flashcard_summary": "第一次減數分裂完成 / LH surge / 第二次減數分裂停滯 / 受精完成減數II -> 初級卵母細胞在 LH surge 時完成第一次減數分裂；次級卵母細胞停在第二次減數分裂中期，受精時才完成。"
    },
    {
      "question_id": "108-2_medicine-6_058",
      "question_number": 58,
      "correct_answer": "B",
      "category_group": "醫學（六）",
      "category": "復健科",
      "category_confidence": "high",
      "key_point": "感覺異常性股痛的神經受壓迫部位與臨床表現。",
      "explanation": "股外側皮神經（LFCN）在穿過鼠蹊韌帶下方進入大腿時，容易因為緊身衣物、肥胖或外傷而受到壓迫，導致其支配的大腿前外側皮膚出現麻木、灼熱感或刺痛，臨床上稱為感覺異常性股痛，故選B。股神經支配大腿前側感覺與股四頭肌運動；閉孔神經支配大腿內側感覺與內收肌群；陰部神經支配會陰部感覺。",
      "flashcard_front": "大腿外側麻痛 / 鼠蹊韌帶壓迫 / 股外側皮神經 / LFCN",
      "flashcard_back": "股外側皮神經（LFCN）在穿過鼠蹊韌帶時易受壓迫，引發大腿前外側麻痛（感覺異常性股痛）。",
      "flashcard_summary": "大腿外側麻痛 / 鼠蹊韌帶壓迫 / 股外側皮神經 / LFCN -> 股外側皮神經（LFCN）在穿過鼠蹊韌帶時易受壓迫，引發大腿前外側麻痛（感覺異常性股痛）。"
    },
    {
      "question_id": "108-2_medicine-6_059",
      "question_number": 59,
      "correct_answer": "A",
      "category_group": "醫學（六）",
      "category": "復健科",
      "category_confidence": "high",
      "key_point": "Erb-Duchenne 麻痺（臂神經叢上幹受損）的特徵性姿態。",
      "explanation": "上肢呈現「侍者小費」姿勢（手臂內收、內旋、前臂伸直且旋前），是臂神經叢上幹（C5-C6，又稱 Erb's palsy）受損的典型臨床表現，多見於產傷或肩部重創，故選A。正中神經受損常呈現部誓言手；尺神經受損呈現爪形手；橈神經受損呈現垂腕。",
      "flashcard_front": "侍者小費 / waiter's tip / 臂神經叢上幹受損 / C5-C6 / Erb's palsy",
      "flashcard_back": "臂神經叢上幹（C5-C6）受損會導致 Erb's palsy，上肢呈現內收、內旋、垂腕的「侍者小費」姿勢。",
      "flashcard_summary": "侍者小費 / waiter's tip / 臂神經叢上幹受損 / C5-C6 / Erb's palsy -> 臂神經叢上幹（C5-C6）受損會導致 Erb's palsy，上肢呈現內收、內旋、垂腕的「侍者小費」姿勢。"
    },
    {
      "question_id": "108-2_medicine-6_060",
      "question_number": 60,
      "correct_answer": "C",
      "category_group": "醫學（六）",
      "category": "復健科",
      "category_confidence": "high",
      "key_point": "腦底動脈瘤破裂導致的出血類型與症狀。",
      "explanation": "顱內囊狀動脈瘤主要好發於腦底威利氏環的動脈分叉處。當動脈瘤破裂時，高壓的動脈血會直接噴射入蜘蛛網膜下腔，進而引發急性蜘蛛網膜下腔出血（SAH），臨床上表現為突發劇烈頭痛，故選C。視丘出血、皮質下出血與小腦出血則多屬於高血壓引發的腦實質內出血。",
      "flashcard_front": "腦動脈瘤破裂 / 蜘蛛網膜下腔出血 / SAH / 雷擊般頭痛",
      "flashcard_back": "顱內動脈瘤破裂是引發急性蜘蛛網膜下腔出血（SAH）最常見的原因，典型表現為雷擊般劇烈頭痛。",
      "flashcard_summary": "腦動脈瘤破裂 / 蜘蛛網膜下腔出血 / SAH / 雷擊般頭痛 -> 顱內動脈瘤破裂是引發急性蜘蛛網膜下腔出血（SAH）最常見的原因，典型表現為雷擊般劇烈頭痛。"
    }
  ]
}

# 108-2_medicine-6_batch-005 (Q61 - Q75)
batch_108_2_med6_005 = {
  "dataset_id": "108-2_medicine-6",
  "batch_id": "108-2_medicine-6_batch-005",
  "items": [
    {
      "question_id": "108-2_medicine-6_061",
      "question_number": 61,
      "correct_answer": "C",
      "category_group": "醫學（六）",
      "category": "復健科",
      "category_confidence": "high",
      "key_point": "鎖入症候群（locked-in syndrome）的病損結構與眼動功能保留。",
      "explanation": "鎖入症候群多由兩側橋腦腹側病變引起，導致皮質脊髓徑與皮質延髓徑部分受損，臨床表現為四肢癱瘓及無法發聲。患者意識完全清醒，但全身肌肉僅能依靠「垂直眼球運動」及張閉眼來進行溝通。由於橋腦的外展神經核與旁正中網狀結構（PPRF）受損，其「左右共軛注視功能通常喪失」，而非正常，故選C為明顯錯誤的敘述。",
      "flashcard_front": "鎖入症候群 / 兩側橋腦病變 / 垂直眼動與眨眼 / 水平共軛注視喪失",
      "flashcard_back": "鎖入症候群患者意識清醒但四肢癱瘓，其水平共軛注視功能喪失，僅保留垂直眼動與眨眼。",
      "flashcard_summary": "鎖入症候群 / 兩側橋腦病變 / 垂直眼動與眨眼 / 水平共軛注視喪失 -> 鎖入症候群患者意識清醒但四肢癱瘓，其水平共軛注視功能喪失，僅保留垂直眼動與眨眼。"
    },
    {
      "question_id": "108-2_medicine-6_062",
      "question_number": 62,
      "correct_answer": "C",
      "category_group": "醫學（六）",
      "category": "復健科",
      "category_confidence": "high",
      "key_point": "膝關節退化急性積水發炎期的處置禁忌。",
      "explanation": "張太太在爬山後出現右膝紅腫積水及關節受限，此時右膝正處於急性發炎或大量積水期。在急性發炎且彎曲會劇痛的情況下，進行強行牽拉膝關節至正常角度會加劇關節內壓力並加重發炎與滑膜損傷，是「最不適宜」的處置，故選C。此時合適處置包括投予消炎藥、電療止痛，以及進行不改變關節角度的等長肌力運動（如直腿抬高）。",
      "flashcard_front": "退化性關節炎 / 急性發炎積水 / 牽拉關節禁忌 / 等長運動",
      "flashcard_back": "膝關節急性發炎積水時，禁用強行牽拉關節；此時可做等長收縮運動以防止肌肉萎縮。",
      "flashcard_summary": "退化性關節炎 / 急性發炎積水 / 牽拉關節禁忌 / 等長運動 -> 膝關節急性發炎積水時，禁用強行牽拉關節；此時可做等長收縮運動以防止肌肉萎縮。"
    },
    {
      "question_id": "108-2_medicine-6_063",
      "question_number": 63,
      "correct_answer": "D",
      "category_group": "醫學（六）",
      "category": "復健科",
      "category_confidence": "high",
      "key_point": "肩關節盂唇病變的診斷影像選擇與超音波局限性。",
      "explanation": "肌肉骨骼超音波對淺層軟組織如肌腱、滑液囊具有極佳的分辨率。然而，肩關節的盂唇（labrum）位於關節深處，受到周圍骨骼與增厚關節囊的遮擋，超音波聲波難以穿透，因此臨床上若懷疑盂唇撕裂（如 SLAP 撕裂），必須使用磁振造影（MRI）進行精準診斷，故選D。",
      "flashcard_front": "肩關節盂唇 / labrum / 超音波局限 / 磁振造影 (MRI)",
      "flashcard_back": "肩關節盂唇（labrum）位於深處且受骨骼阻擋，超音波難以評估，診斷盂唇病變首選 MRI。",
      "flashcard_summary": "肩關節盂唇 / labrum / 超音波局限 / 磁振造影 (MRI) -> 肩關節盂唇（labrum）位於深處且受骨骼阻擋，超音波難以評估，診斷盂唇病變首選 MRI。"
    },
    {
      "question_id": "108-2_medicine-6_064",
      "question_number": 64,
      "correct_answer": "C",
      "category_group": "醫學（六）",
      "category": "復健科",
      "category_confidence": "high",
      "key_point": "非發炎性關節液分析的細胞數與黏蛋白特徵。",
      "explanation": "在關節液分析中，非發炎性關節液（如退化性關節炎、外傷）的白血球計數通常低於 2000/mm³（多形核白血球比例小於 25%），且黏蛋白凝固佳（選項A）、黏稠度高（選項D）。若白血球數目高於 2000/mm³，則被定義為發炎性關節液，因此選項C「高於2000/mm³」不是非發炎性關節液的特徵（為本題答案）。",
      "flashcard_front": "非發炎性關節液 / 白血球計數 <2000/mm³ / 黏蛋白凝固佳",
      "flashcard_back": "非發炎性關節液的白血球計數低於 2000/mm³；高於 2000/mm³ 則提示發炎性關節炎。",
      "flashcard_summary": "非發炎性關節液 / 白血球計數 <2000/mm³ / 黏蛋白凝固佳 -> 非發炎性關節液的白血球計數低於 2000/mm³；高於 2000/mm³ 則提示發炎性關節炎。"
    },
    {
      "question_id": "108-2_medicine-6_065",
      "question_number": 65,
      "correct_answer": "C",
      "category_group": "醫學（六）",
      "category": "復健科",
      "category_confidence": "high",
      "key_point": "骨折復健在急性期的物理治療與活動原則。",
      "explanation": "骨折急性期（傷後24-48小時內）局部正處於出血、水腫與急性發炎階段。此時若給予局部「熱療」會使血管擴張，加重局部的腫脹與出血，因此急性期應給予冷療（冰敷）而非熱療，選項C敘述為錯誤（本題答案）。骨折復健原則包括：未被固定的關節應儘早主動運動以防僵硬（選項A）；老年人因平衡差，步態訓練首選助行器（選項B）；適度且循序漸進的負重能刺激骨細胞活性，促進骨折癒合（沃夫法則，選項D）。",
      "flashcard_front": "骨折復健 / 急性期冰敷 / 限制熱療 / 早期活動 / 負重促進癒合",
      "flashcard_back": "骨折急性發炎期禁用熱療（會加重水腫），應予冰敷；適度負重可刺激骨癒合。",
      "flashcard_summary": "骨折復健 / 急性期冰敷 / 限制熱療 / 早期活動 / 負重促進癒合 -> 骨折急性發炎期禁用熱療（會加重水腫），應予冰敷；適度負重可刺激骨癒合。"
    },
    {
      "question_id": "108-2_medicine-6_066",
      "question_number": 66,
      "correct_answer": "B",
      "category_group": "醫學（六）",
      "category": "復健科",
      "category_confidence": "high",
      "key_point": "Milwaukee 背架在脊椎側彎治療中的適用位置。",
      "explanation": "Milwaukee 背架（CTLSO）包含一個頸圈和下頜支架，是唯一適用於高位胸椎側彎（側彎頂點在 T7 或以上，如本題第六胸椎 T6，選項B正確）的硬式背架。一般的 Boston 背架（TLSO）因無上部支撐，僅適用於頂點在 T8 或以下的胸腰椎側彎。頸椎骨折多用費城頸圈或 Halo-vest（選項A）；胸腰椎骨折壓迫常用 Jewett 或 Taylor 背架以限制前屈（選項C、D）。",
      "flashcard_front": "Milwaukee背架 / CTLSO / 脊椎側彎 / 頂點T7以上 (如T6)",
      "flashcard_back": "Milwaukee 背架（CTLSO）適用於側彎頂點在 T7 或以上（如 T6）的高位胸椎側彎。",
      "flashcard_summary": "Milwaukee背架 / CTLSO / 脊椎側彎 / 頂點T7以上 (如T6) -> Milwaukee 背架（CTLSO）適用於側彎頂點在 T7 或以上（如 T6）的高位胸椎側彎。"
    },
    {
      "question_id": "108-2_medicine-6_067",
      "question_number": 67,
      "correct_answer": "C",
      "category_group": "醫學（六）",
      "category": "復健科",
      "category_confidence": "high",
      "key_point": "等長、等張與等角速度運動的生理特性鑑別。",
      "explanation": "等張性運動（如舉啞鈴）是指肌肉收縮時張力保持不變，但肌肉長度改變，關節角度會發生變化；而等角速度運動（又稱等速運動）是指在特製儀器下，不論肌肉出多大力量，關節的運動速度（角速度）始終保持不變，兩者生理機轉不同，故選項C稱兩者相同是明顯錯誤的。阻力訓練常為等長收縮（選項A、B）；由於阻力訓練（特別是Valsalva效應）會使血壓急劇升高，對心臟負荷極大，因此一般不建議心臟病患與虛弱老年人進行（選項D）。",
      "flashcard_front": "等張性運動 / 等角速度 (等速) 運動 / 阻力訓練心臟負荷",
      "flashcard_back": "等張運動（張力恆定，速度可變）不等同於等速運動（速度恆定）；阻力訓練易升血壓，心臟病患縱用時需小心。",
      "flashcard_summary": "等張性運動 / 等角速度 (等速) 運動 / 阻力訓練心臟負荷 -> 等張運動（張力恆定，速度可變）不等同於等速運動（速度恆定）；阻力訓練易升血壓，心臟病患縱用時需小心。"
    },
    {
      "question_id": "108-2_medicine-6_068",
      "question_number": 68,
      "correct_answer": "B",
      "category_group": "醫學（六）",
      "category": "復健科",
      "category_confidence": "high",
      "key_point": "對稱性緊張性頸部反射（STNR）的反射姿態模式。",
      "explanation": "對稱性緊張性頸部反射（STNR）是一種原始發育反射。其反射模式為：當頭部屈曲（flexion）時，會引發上肢屈曲、下肢伸直，故選B；當頭部伸直時，則引發上肢伸直、下肢屈曲。此反射若在幼兒期持續存在會阻礙正常運動發育。",
      "flashcard_front": "原始反射 / STNR反射 / 頭部屈曲 / 上肢屈曲、下肢伸直",
      "flashcard_back": "對稱性緊張性頸部反射（STNR）表現為：頭部屈曲時上肢屈曲、下肢伸直；頭伸直時上肢伸直、下肢屈曲。",
      "flashcard_summary": "原始反射 / STNR反射 / 頭部屈曲 / 上肢屈曲、下肢伸直 -> 對稱性緊張性頸部反射（STNR）表現為：頭部屈曲時上肢屈曲、下肢伸直；頭伸直時上肢伸直、下肢屈曲。"
    },
    {
      "question_id": "108-2_medicine-6_069",
      "question_number": 69,
      "correct_answer": "B",
      "category_group": "醫學（六）",
      "category": "復健科",
      "category_confidence": "high",
      "key_point": "傳導型失語症的臨床特徵與解剖病損。",
      "explanation": "患者的說話流暢度良好且聽理解力尚佳，但其最突出的障礙在於「單詞覆述（repetition）極度困難」，且伴有字詞語誤及聽寫朗誦障礙。這符合傳導型失語症的典型特徵，其病灶通常位於連接 Broca 區與 Wernicke 區的弓狀束（arcuate fasciculus），故選B。Wernicke失語症聽理解極差；經皮質混合型失語症流暢度與理解皆差；運動失調型吶吃為構音障礙而非失語症。",
      "flashcard_front": "傳導型失語症 / 覆述能力極差 / 理解與流暢度佳 / 弓狀束病損",
      "flashcard_back": "傳導型失語症（conduction aphasia）特徵為理解與流暢度好，但覆述能力極差，主因為弓狀束受損。",
      "flashcard_summary": "傳導型失語症 / 覆述能力極差 / 理解與流暢度佳 / 弓狀束病損 -> 傳導型失語症（conduction aphasia）特徵為理解與流暢度好，但覆述能力極差，主因為弓狀束受損。"
    },
    {
      "question_id": "108-2_medicine-6_070",
      "question_number": 70,
      "correct_answer": "C",
      "category_group": "醫學（六）",
      "category": "復健科",
      "category_confidence": "high",
      "key_point": "腹股溝皮膚感覺皮節（dermatome）與脊髓神經定位。",
      "explanation": "兩側腹股溝的皮膚感覺是由第一腰神經根（L1 nerve root）所支配。當患者發生第一腰椎（L1）壓迫性骨折時，容易壓迫或刺激 L1 神經根，進而引發雙側腹股溝區的放射性疼痛，故選C。C7支配中指感覺；T8支配肋骨下緣；L5支配大腿外側及足背。",
      "flashcard_front": "雙側腹股溝痛 / L1皮節 / 第一腰椎骨折 / 感覺神經定位",
      "flashcard_back": "腹股溝（inguinal region）的感覺由 L1 神經根支配，雙側腹股溝疼痛提示第一腰椎（L1）骨折壓迫。",
      "flashcard_summary": "雙側腹股溝痛 / L1皮節 / 第一腰椎骨折 / 感覺神經定位 -> 腹股溝（inguinal region）的感覺由 L1 神經根支配，雙側腹股溝疼痛提示第一腰椎（L1）骨折壓迫。"
    },
    {
      "question_id": "108-2_medicine-6_071",
      "question_number": 71,
      "correct_answer": "C",
      "category_group": "醫學（六）",
      "category": "復健科",
      "category_confidence": "high",
      "key_point": "吞嚥障礙評估的黃金標準檢查法。",
      "explanation": "錄影螢光吞嚥檢查（VFSS，又稱鋇劑吞嚥造影，選項C）是目前臨床上評估吞嚥功能及診斷吸入與無症狀吸入的黃金標準。該檢查能即時、動態地在X光透視下觀察食團在口腔、咽部及食道各階段的流動與肌肉運動。食道壓力測定（選項A）、超音波（選項B）與CT（選項D）皆無法提供動態實時的吞嚥生理評估。",
      "flashcard_front": "吞嚥障礙 / 評估黃金標準 / 錄影螢光吞嚥檢查 / VFSS / 動態吸入評估",
      "flashcard_back": "錄影螢光吞嚥檢查（VFSS）是診斷吞嚥障礙與隱性吸入的黃金標準，可在透視下即時評估。",
      "flashcard_summary": "吞嚥障礙 / 評估黃金標準 / 錄影螢光吞嚥檢查 / VFSS / 動態吸入評估 -> 錄影螢光吞嚥檢查（VFSS）是診斷吞嚥障礙與隱性吸入的黃金標準，可在透視下即時評估。"
    },
    {
      "question_id": "108-2_medicine-6_072",
      "question_number": 72,
      "correct_answer": "B",
      "category_group": "醫學（六）",
      "category": "眼科",
      "category_confidence": "high",
      "key_point": "視神經鞘腦膜瘤（ONSM）的典型 MRI 影像特徵。",
      "explanation": "MRI 影像中若顯示視神經鞘顯著增厚並呈雙軌徵（tram-track sign）或圓環狀強化，而中間的視神經主體不強化，是視神經鞘腦膜瘤（ONSM）的特徵性表現，故選B。視神經膠質瘤（選項A）多表現為視神經本身的梭形膨大與實質強化；視神經炎（選項C）主要表現為視神經實質的斑片狀強化，無明顯外圍包繞的鞘膜瘤體。",
      "flashcard_front": "視神經鞘腦膜瘤 / ONSM / 雙軌徵 (tram-track) / 視力減退 / 壓脂T1強化",
      "flashcard_back": "視神經鞘腦膜瘤（ONSM）在 MRI 上呈現特徵性的視神經鞘強化與中間視神經低信號的雙軌徵。",
      "flashcard_summary": "視神經鞘腦膜瘤 / ONSM / 雙軌徵 (tram-track) / 視力減退 / 壓脂T1強化 -> 視神經鞘腦膜瘤（ONSM）在 MRI 上呈現特徵性的視神經鞘強化與中間視神經低信號 the double track (tram-track sign)。"
    },
    {
      "question_id": "108-2_medicine-6_073",
      "question_number": 73,
      "correct_answer": "B",
      "category_group": "醫學（六）",
      "category": "復健科",
      "category_confidence": "high",
      "key_point": "蜘蛛網膜下腔出血後遲發性腦血管痙攣的高峰時間。",
      "explanation": "SAH 後引發的遲發性腦血管痙攣（vasospasm）通常在出血後的「第 4 到 14 天」最為嚴重（高峰期多在第 7-10 天），在前三天（急性期）血管痙攣相對較少見或不嚴重，因此選項B的敘述為錯誤。出血量大且集中處常可指示動脈瘤的位置（選項A）；CTA 診斷敏感度極高（選項D）；SAH 血液阻塞蛛網膜顆粒會引發交通性水腦（選項D）。",
      "flashcard_front": "SAH / 腦血管痙攣 / 遲發性痙攣天數 / 第4-14天最重",
      "flashcard_back": "SAH後血管痙攣多在出血後第4-14天（第7-10天高峰）最嚴重，前三天非最嚴重期。",
      "flashcard_summary": "SAH / 腦血管痙攣 / 遲發性痙攣天數 / 第4-14天最重 -> SAH後血管痙攣多在出血後第4-14天（第7-10天高峰）最嚴重，前三天非最嚴重期。"
    },
    {
      "question_id": "108-2_medicine-6_074",
      "question_number": 74,
      "correct_answer": "A",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "雙角子宮的 MRI 影像解剖學診斷特徵。",
      "explanation": "磁振造影（MRI）影像中若顯示子宮底部外觀呈凹陷（超過1公分），且內部有兩個分開的子宮腔，但下方共用同一個子宮頸，這是苗勒氏管融合不全導致的典型雙角子宮（bicornuate uterus，選項A正確）表現。雙子宮（選項B）則表現為兩個完全獨立的子宮體及兩個子宮頸；單角子宮（選項D）僅發育單側。",
      "flashcard_front": "子宮畸形 / 雙子宮角 / 單子宮頸 / 子宮底凹陷 >1cm / 雙角子宮",
      "flashcard_back": "雙角子宮（bicornuate uterus）在影像上呈現雙子宮腔、單一子宮頸，且子宮底外觀有明顯凹陷。",
      "flashcard_summary": "子宮畸形 / 雙子宮角 / 單子宮頸 / 子宮底凹陷 >1cm / 雙角子宮 -> 雙角子宮（bicornuate uterus）在影像上呈現雙子宮腔、單一子宮頸，且子宮底外觀有明顯凹陷。"
    },
    {
      "question_id": "108-2_medicine-6_075",
      "question_number": 75,
      "correct_answer": "B",
      "category_group": "醫學（六）",
      "category": "眼科",
      "category_confidence": "high",
      "key_point": "眼眶爆裂骨折（blowout fracture）的解剖損害與臨床體徵。",
      "explanation": "眼眶爆裂骨折（blowout fracture）最常發生於最薄弱的眼眶底（orbital floor，選項C），由於眼眶底下方緊鄰上頜竇（maxillary sinus），骨折後血液與疝出的眼眶脂肪容易落入其中，因此上頜竇極易積血，而非 frontal sinus（額竇），故選B為錯誤敘述。Waters' view X光是評估上頜竇及眶底骨折的經典檢查（選項A）；骨折常導致下直肌嵌頓而引起向上看時的複視（選項D）。",
      "flashcard_front": "眼眶爆裂骨折 / 眶底骨折 / 上頜竇積血 (非額竇) / 複視",
      "flashcard_back": "眼眶爆裂骨折最常發生於眶底，易導致上頜竇（maxillary sinus）積血及下直肌嵌頓引起複視。",
      "flashcard_summary": "眼眶爆裂骨折 / 眶底骨折 / 上頜竇積血 (非額竇) / 複視 -> 眼眶爆裂骨折最常發生於眶底，易導致上頜竇（maxillary sinus）積血及下直肌嵌頓引起複視。"
    }
  ]
}

# 108-2_medicine-6_batch-006 (Q76 - Q80)
batch_108_2_med6_006 = {
  "dataset_id": "108-2_medicine-6",
  "batch_id": "108-2_medicine-6_batch-006",
  "items": [
    {
      "question_id": "108-2_medicine-6_076",
      "question_number": 76,
      "correct_answer": "C",
      "category_group": "醫學（六）",
      "category": "耳鼻喉科",
      "category_confidence": "high",
      "key_point": "突發性耳聾的臨床診斷定義與病因分類。",
      "explanation": "突發性耳聾定義上是指「3天（72小時）內」突然發生的感音神經性聽力喪失，而非一個月內（選項A錯誤）。其好發於中老年人，但也可能發生在年輕人（選項B錯誤）。在臨床上，高達 85% 到 90% 的病患經過詳細檢查後仍無法確立明確病因，故大部分為原發性（idiopathic，選項C正確）。部分已證實的繼發性原因包括病毒感染，例如腮腺炎病毒（mumps virus）是已證實能造成單側聽力喪失的病原體之一（選項D錯誤）。",
      "flashcard_front": "突發性耳聾 / 72小時內聽力喪失 / 原發性 (idiopathic) / 腮腺炎病毒",
      "flashcard_back": "突發性耳聾定義為72小時內發生的感音神經性聽力損失，多數為原發性，腮腺炎病毒為已知病因之一。",
      "flashcard_summary": "突發性耳聾 / 72小時內聽力喪失 / 原發性 (idiopathic) / 腮腺炎病毒 -> 突發性耳聾定義為72小時內發生的感音神經性聽力損失，多數為原發性，腮腺炎病毒為已知病因之一。"
    },
    {
      "question_id": "108-2_medicine-6_077",
      "question_number": 77,
      "correct_answer": "D",
      "category_group": "醫學（六）",
      "category": "婦產科",
      "category_confidence": "high",
      "key_point": "子癇前症與子癇症的臨床診斷區分基準。",
      "explanation": "子癇前症（pre-eclampsia）的診斷標準為孕期出現高血壓（選項A）合併蛋白尿（選項B）或全身性器官受損症狀（如寡尿，選項C）。一旦患者在此基礎上出現無法用其他原因解釋的抽搐或癲癇（seizure，選項D），即代表疾病已進展為子癇症（eclampsia），故癲癇「不是」子癇前症本身的診斷或臨床表現，選D。",
      "flashcard_front": "子癇前症 / 高血壓、蛋白尿 / 癲癇發作 / 子癇症診斷",
      "flashcard_back": "子癇前症特徵為高血壓與蛋白尿，一旦出現癲癇發作（seizure）則診斷進展為子癇症（eclampsia）。",
      "flashcard_summary": "子癇前症 / 高血壓、蛋白尿 / 癲癇發作 / 子癇症診斷 -> 子癇前症特徵為高血壓與蛋白尿，一旦出現癲癇發作（seizure）則診斷進展為子癇症（eclampsia）。"
    },
    {
      "question_id": "108-2_medicine-6_078",
      "question_number": 78,
      "correct_answer": "A",
      "category_group": "醫學（六）",
      "category": "醫學倫理與醫療決策",
      "category_confidence": "high",
      "key_point": "醫療知情同意（informed consent）程序所保障的核心倫理原則。",
      "explanation": "醫療知情同意（informed consent）程序要求醫師在手術前向患者詳細說明治療效益、風險、替代方案，並在患者充分理解下自主做出決定並簽署同意書。這最主要體現並確保了醫療倫理四大原則中的「尊重病人自主原則」，保護患者對自己身體的決定權，故選A。隱私（選項B）、資源（選項C）與公平正義（選項D）並非知情同意直接維護的核心倫理。",
      "flashcard_front": "知情同意 / Informed consent / 病人自主權 / 術前風險說明",
      "flashcard_back": "手術前請患者簽署知情同意書的核心目的，是確保並尊重病人的自主權（autonomy）。",
      "flashcard_summary": "知情同意 / Informed consent / 病人自主權 / 術前風險說明 -> 手術前請患者簽署知情同意書的核心目的，是確保並尊重病人的自主權（autonomy）。"
    },
    {
      "question_id": "108-2_medicine-6_079",
      "question_number": 79,
      "correct_answer": "B",
      "category_group": "醫學（六）",
      "category": "醫學倫理與醫療決策",
      "category_confidence": "high",
      "key_point": "意定醫療委任代理人與法定親屬的優先決定權順位。",
      "explanation": "根據我國《病人自主權利法》及《安寧緩和醫療條例》，意定醫療委任代理人（由病人於神智清楚時以書面指定者）在法律上的效力優先於法定關係人（如配偶或子女）。因此，即使兒子是法定親屬，病人先前書面指定的鄰居作為意定「醫療委任代理人」是唯一的合法代理決定者，其有權代表病人做拔管決定，故選B。",
      "flashcard_front": "醫療委任代理人 / 優先權順位 / 書面指定鄰居 / 法定親屬兒子",
      "flashcard_back": "書面指定的意定醫療委任代理人（鄰居）之代理決定權優先於法定關係人（兒子）。",
      "flashcard_summary": "醫療委任代理人 / 優先權順位 / 書面指定鄰居 / 法定親屬兒子 -> 書面指定的意定醫療委任代理人（鄰居）之代理決定權優先於法定關係人（兒子）。"
    },
    {
      "question_id": "108-2_medicine-6_080",
      "question_number": 80,
      "correct_answer": "A",
      "category_group": "醫學（六）",
      "category": "醫學倫理與醫療決策",
      "category_confidence": "high",
      "key_point": "精神病患暴力傾向處置的法律、倫理與安全規範。",
      "explanation": "在病人不知情且未經診斷同意的情況下，直接開立藥物給家屬並讓家屬暗中混入食物中餵藥，是嚴重違反醫療法規與醫療倫理的行為，且無法確保劑量安全，故選A為最不適當處置。由於病人有明顯暴力傾向、威脅太太人身安全，應考慮依法評估進行強制住院治療（選項B）；並提供家屬社政資源（選項C）及通知社工或警政單位（選項D）以保護受害者。",
      "flashcard_front": "精神暴力患者 / 暗中餵藥禁忌 / 強制住院評估 / 家屬安全防護",
      "flashcard_back": "對於具暴力與妄想的精神病人，絕不可開藥讓家屬暗中下藥；此時應評估強制住院並通報社政警政。",
      "flashcard_summary": "精神暴力患者 / 暗中餵藥禁忌 / 強制住院評估 / 家屬安全防護 -> 对于具暴力與妄想的精神病人，絕不可開藥讓家屬暗中下藥；此時應評估強制住院並通報社政警政。"
    }
  ]
}

# 109-1_medicine-1_batch-001 (Q1 - Q15)
batch_109_1_med1_001 = {
  "dataset_id": "109-1_medicine-1",
  "batch_id": "109-1_medicine-1_batch-001",
  "items": [
    {
      "question_id": "109-1_medicine-1_001",
      "question_number": 1,
      "correct_answer": "D",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "內囊後支的動脈血流供應來源。",
      "explanation": "內囊後支（posterior limb of internal capsule）主要是由前脈絡叢動脈（anterior choroidal artery，為內頸動脈的分支，選項D正確）以及大腦中動脈的豆紋動脈（lenticulostriate arteries）供血。前大腦動脈（選項A）通常供血給內囊前支；後交通動脈（選項B）與丘腦穿通動脈（選項C）主要供血給丘腦與中腦。",
      "flashcard_front": "內囊後支 / 血管供應 / 前脈絡叢動脈 / 豆紋動脈 / 內囊前支",
      "flashcard_back": "內囊後支主要由前脈絡叢動脈及豆紋動脈供血；前大腦動脈（返折支）則主要供應內囊前支。",
      "flashcard_summary": "內囊後支 / 血管供應 / 前脈絡叢動脈 / 豆紋動脈 / 內囊前支 -> 內囊後支主要由前脈絡叢動脈及豆紋動脈供血；前大腦動脈（返折支）則主要供應內囊前支。"
    },
    {
      "question_id": "109-1_medicine-1_002",
      "question_number": 2,
      "correct_answer": "C",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "內側縱束（MLF）在眼球運動與前庭反射（VOR）中的連接功能。",
      "explanation": "內側縱束（Medial Longitudinal Fasciculus, MLF，選項C正確）是連接前庭神經核與控制眼球運動之神經核（CN III、CN IV、CN VI）的關鍵纖維束，主要介導前庭眼反射（VOR）以維持眼球在頭部運動時的穩定。前庭小腦纖維（選項A）連接前庭核與小腦；中央被蓋束（選項B）連接紅核與下橄欖核；內側前腦束（選項D）主要傳導邊緣系統資訊。",
      "flashcard_front": "內側縱束 / MLF / 連接前庭核與眼動核 / 前庭眼反射",
      "flashcard_back": "內側縱束（MLF）連接前庭神經核與眼外肌運動神經核，是介導前庭眼反射（VOR）的關鍵通路。",
      "flashcard_summary": "內側縱束 / MLF / 連接前庭核與眼動核 / 前庭眼反射 -> 內側縱束（MLF）連接前庭神經核與眼外肌運動神經核，是介導前庭眼反射（VOR）的關鍵通路。"
    },
    {
      "question_id": "109-1_medicine-1_003",
      "question_number": 3,
      "correct_answer": "A",
      "category_group": "醫學（一）",
      "category": "胚胎及發育生物學",
      "category_confidence": "high",
      "key_point": "第一對咽弓衍生物及其神經支配起源。",
      "explanation": "胚胎發育中，第一對咽弓會衍生出咀嚼肌、鼓膜張肌、腭帆張肌及二腹肌前腹等構造，其支配神經為三叉神經（CN V）的運動支，其對應的起源神經核為三叉神經運動核，故選項A正確。第二對咽弓衍生出表情肌，由面神經核（選項B）支配；第三對咽弓衍生出莖突咽肌，由舌咽神經支配；第四、六對咽弓衍生出喉部肌肉，由迷走神經支配。",
      "flashcard_front": "第一對咽弓 / 咀嚼肌衍生 / 三叉神經運動核 / 第二對咽弓面神經核",
      "flashcard_back": "第一咽弓衍生物（如咀嚼肌）由三叉神經運動核支配；第二咽弓（表情肌）由面神經核支配。",
      "flashcard_summary": "第一對咽弓 / 咀嚼肌衍生 / 三叉神經運動核 / 第二對咽弓面神經核 -> 第一咽弓衍生物（如咀嚼肌）由三叉神經運動核支配；第二咽弓（表情肌）由面神經核支配。"
    },
    {
      "question_id": "109-1_medicine-1_004",
      "question_number": 4,
      "correct_answer": "B",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "腦硬膜靜脈竇之間的交通管道。",
      "explanation": "上岩竇（superior petrosal sinus，選項B正確）位於顳骨岩部上緣，其解剖路徑直接連接前方海綿竇（cavernous sinus）與後方的橫竇（transverse sinus）。下岩竇（選項C）則將海綿竇連接至內頸靜脈的起點；乙狀竇（選項A）是橫竇向下延伸並流入內頸靜脈的通道；直竇（選項D）連接下矢狀竇與竇匯。",
      "flashcard_front": "上岩竇 / 橫竇 / 海綿竇 / 靜脈竇交通",
      "flashcard_back": "連接海綿竇與橫竇的靜脈竇是上岩竇；而下岩竇則是將海綿竇連至內頸靜脈。",
      "flashcard_summary": "上岩竇 / 橫竇 / 海綿竇 / 靜脈竇交通 -> 連接海綿竇與橫竇的靜脈竇是上岩竇；而下岩竇則是將海綿竇連至內頸靜脈。"
    },
    {
      "question_id": "109-1_medicine-1_005",
      "question_number": 5,
      "correct_answer": "B",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "蝶骨大翼與小翼之間的孔裂解剖。",
      "explanation": "在蝶骨的解剖結構中，眶上裂（superior orbital fissure，選項B正確）是位於蝶骨大翼與小翼之間的一道裂隙，連通中顱窩與眼眶。視神經孔（選項A）完全位於蝶骨小翼的基底部；圓孔（選項C）穿過蝶骨大翼；眶下裂（選項D）則是由蝶骨大翼、上頜骨及腭骨等共同圍成，不處於大翼與小翼之間。",
      "flashcard_front": "蝶骨解剖 / 眶上裂 / 大翼與小翼 / 視神經孔 / 圓孔交通",
      "flashcard_back": "位於蝶骨大翼與小翼之間的骨性通道為眶上裂（SOF），有CN III、IV、V1、VI穿過。",
      "flashcard_summary": "蝶骨解剖 / 眶上裂 / 大翼與小翼 / 視神經孔 / 圓孔交通 -> 位於蝶骨大翼與小翼之間的骨性通道為眶上裂（SOF），有CN III、IV、V1、VI穿過。"
    },
    {
      "question_id": "109-1_medicine-1_006",
      "question_number": 6,
      "correct_answer": "B",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "耳下腺管開口處頰黏膜的痛覺傳導神經。",
      "explanation": "耳下腺管開口於上頜第二大臼齒相對的頰黏膜。該處口腔黏膜的痛覺及一般感覺是由三叉神經下頜支的分支——頰神經（buccal nerve，選項B正確）負責傳導。需要特別鑑別的是，面神經的頰支（選項D）屬於運動神經，支配頰肌等表情肌，不傳導一般感覺；舌神經（選項A）負責舌前三分之二的一般感覺；顴面神經（選項C）支配外側眼眶皮表感覺。",
      "flashcard_front": "耳下腺管開口 / 頰黏膜感覺 / 頰神經 (三叉) / 面神經頰支 (運動)",
      "flashcard_back": "頰部黏膜的一般感覺（痛覺）由三叉神經分支「頰神經」傳導；面神經頰支則支配頰肌的運動。",
      "flashcard_summary": "耳下腺管開口 / 頰黏膜感覺 / 頰神經 (三叉) / 面神經頰支 (運動) -> 頰部黏膜的一般感覺（痛覺）由三叉神經分支「頰神經」傳導；面神經頰支則支配頰肌的運動。"
    },
    {
      "question_id": "109-1_medicine-1_007",
      "question_number": 7,
      "correct_answer": "A",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "心包膜橫竇的解剖解剖邊界與位置。",
      "explanation": "在心包膜腔內，心包膜橫竇（transverse pericardial sinus，選項A正確）形成於心臟底部的動脈端（升主動脈、肺動脈幹）與靜脈端（上腔靜脈、肺靜脈前壁）之間。手術時可將手指或器械穿過此橫竇以阻斷大血管血流。心包膜斜竇（選項B）是一個盲囊，位於左右肺靜脈與下腔靜脈之間的後壁。",
      "flashcard_front": "心包解剖 / 心包膜橫竇 / 動脈群與靜脈群 / 大血管阻斷",
      "flashcard_back": "心包膜橫竇位於升主動脈/肺動脈幹後方，與上腔靜脈/肺靜脈前壁之間，將動靜脈群分開。",
      "flashcard_summary": "心包膜解剖 / 心包膜橫竇 / 動脈群與靜脈群 / 大血管阻斷 -> 心包膜橫竇位於升主動脈/肺動脈幹後方，與上腔靜脈/肺靜脈前壁之間，將動靜脈群分開。"
    },
    {
      "question_id": "109-1_medicine-1_008",
      "question_number": 8,
      "correct_answer": "C",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "膈下動脈在腹腔主動脈的發源起點。",
      "explanation": "膈下動脈（inferior phrenic artery，選項C正確）是一對對稱的壁支動脈，通常直接發源自腹主動脈的前壁，就在主動脈穿過膈肌主動脈裂孔的下方。胸內動脈（選項A）是鎖骨下動脈的分支；腹腔動脈幹（選項B）與腎動脈（選項D）本身是腹主動脈的分支。",
      "flashcard_front": "膈下動脈 / 腹主動脈 / 壁支動脈 / 膈肌供血",
      "flashcard_back": "膈下動脈是直接發源自腹主動脈（abdominal aorta）的第一對壁支（偶可與腹腔幹共幹）。",
      "flashcard_summary": "膈下動脈 / 腹主動脈 / 壁支動脈 / 膈肌供血 -> 膈下動脈是直接發源自腹主動脈（abdominal aorta）的第一對壁支（偶可與腹腔幹共幹）。"
    },
    {
      "question_id": "109-1_medicine-1_009",
      "question_number": 9,
      "correct_answer": "D",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "精索的結構包裝與內容物組成。",
      "explanation": "精索自深環至睪丸，外包三層筋膜（選項A正確）。其內部通道結構包括睪丸動脈及輸精管（選項B）、蔓狀靜脈叢（選項C），以及豐富的淋巴管（負責將睪丸與副睪的淋巴液引流至腰淋巴結），因此選項D稱「內無淋巴管」是錯誤的。",
      "flashcard_front": "精索 / 輸精管 / 睪丸動脈 / 蔓狀靜脈叢 / 淋巴管存在",
      "flashcard_back": "精索內含有睪丸動脈、輸精管、蔓狀靜脈叢、神經以及淋巴管（將淋巴引流至腰淋巴結）。",
      "flashcard_summary": "精索 / 輸精管 / 睪丸動脈 / 蔓狀靜脈叢 / 淋巴管存在 -> 精索內含有睪丸動脈、輸精管、蔓狀靜脈叢、神經以及淋巴管（將淋巴引流至腰淋巴結）。"
    },
    {
      "question_id": "109-1_medicine-1_010",
      "question_number": 10,
      "correct_answer": "C",
      "category_group": "醫學（一）",
      "category": "胚胎及發育生物學",
      "category_confidence": "high",
      "key_point": "男女外生殖器發育的同源器官對應。",
      "explanation": "胚胎發育中，女性的前庭球（bulb of the vestibule）發育自尿道褶周邊的勃起組織，在男性中其同源構造為尿道海綿體（corpus spongiosum，選項C正確，包括陰莖頭與尿道球）。尿道球腺（選項A）同源於女性的大前庭腺；陰莖海綿體（選項B）及陰莖腳（選項D）則同源於女性的陰蒂海綿體及陰蒂腳。",
      "flashcard_front": "前庭球 / 尿道海綿體 / 胚胎同源 / 陰蒂海綿體與陰莖海綿體",
      "flashcard_back": "女性的前庭球與男性的尿道海綿體（corpus spongiosum）互為同源構造；陰蒂海綿體與陰莖海綿體同源。",
      "flashcard_summary": "前庭球 / 尿道海綿體 / 胚胎同源 / 陰蒂海綿體與陰莖海綿體 -> 女性的前庭球與男性的尿道海綿體（corpus spongiosum）互為同源構造；陰蒂海綿體與陰莖海綿體同源。"
    },
    {
      "question_id": "109-1_medicine-1_011",
      "question_number": 11,
      "correct_answer": "A",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "膝反射反射弧的支配神經定位。",
      "explanation": "膝反射（knee jerk reflex）的反射弧是藉由敲擊髕骨韌帶，伸展股四頭肌刺激肌梭，信號經感覺纖維傳入脊髓（L2-L4），再經運動纖維傳出支配股四頭肌收縮，這條通路的一般感覺與運動纖維均由股神經（femoral nerve，選項A正確）傳導。閉孔神經（選項B）支配內收肌群；坐骨神經（選項C）支配大腿後側肌肉；脛神經（選項D）支配小腿後側肌肉。",
      "flashcard_front": "膝反射 / 股神經 / 股四頭肌收縮 / 脊髓L2-L4傳導",
      "flashcard_back": "膝反射主要測試股神經（femoral nerve，L2-L4）的完整性，負責傳入伸展感覺與傳出運動信號。",
      "flashcard_summary": "膝反射 / 股神經 / 股四頭肌收縮 / 脊髓L2-L4傳導 -> 膝反射主要測試股神經（femoral nerve，L2-L4）的完整性，負責傳入伸展感覺與傳出運動信號。"
    },
    {
      "question_id": "109-1_medicine-1_012",
      "question_number": 12,
      "correct_answer": "C",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "脊神經根與脊神經支的感覺與運動纖維類型。",
      "explanation": "脊神經在發出脊髓時，背根（後根）及背根絲（dorsal rootlet，選項C正確）只含有進入脊髓的感覺（傳入）神經纖維。而腹根及腹根絲只含有傳出運動神經纖維。一旦背根與腹根匯合成脊神經後，其分支如背側支及腹側支皆屬於混合神經，同時含有感覺和運動神經纖維。",
      "flashcard_front": "背根絲 / 只含感覺纖維 / 腹根絲只含運動 / 脊神經分支混合",
      "flashcard_back": "背根絲（dorsal rootlet）只含有感覺神經纖維，腹根絲只含運動纖維；分支（ramus）皆為混合纖維。",
      "flashcard_summary": "背根絲 / 只含感覺纖維 / 腹根絲只含運動 / 脊神經分支混合 -> 背根絲（dorsal rootlet）只含有感覺神經纖維，腹根絲只含運動纖維；分支（ramus）皆為混合纖維。"
    },
    {
      "question_id": "109-1_medicine-1_013",
      "question_number": 13,
      "correct_answer": "B",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "跗骨隧道（tarsal tunnel）處的血管觸診定位。",
      "explanation": "跗骨隧道位於內踝後下方，由內踝與屈肌支持帶圍成。通過此隧道的構造包括脛後肌腱、趾長屈肌腱、脛後動靜脈、脛神經及拇長屈肌腱。臨床上可在此處觸摸到脛後動脈（posterior tibial artery，選項B正確）的脈搏以評估下肢血流。脛前動脈（選項A）在足背形成足背動脈；足底內側與外側動脈（選項C、D）是脛後動脈在足底的分支，位置較深，無法直接摸到脈搏。",
      "flashcard_front": "跗骨隧道 / 內踝後下方 / 脛後動脈脈搏 / 下肢循環",
      "flashcard_back": "在繞過內踝的跗骨隧道（tarsal tunnel）處可觸摸到脛後動脈（posterior tibial artery）的脈搏。",
      "flashcard_summary": "跗骨隧道 / 內踝後下方 / 脛後動脈脈搏 / 下肢循環 -> 在繞過內踝的跗骨隧道（tarsal tunnel）處可觸摸到脛後動脈（posterior tibial artery）的脈搏。"
    },
    {
      "question_id": "109-1_medicine-1_014",
      "question_number": 14,
      "correct_answer": "D",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "基底核迴路中多巴胺對直接與間接迴路的調控作用。",
      "explanation": "基底核迴路中，黑質緻密部（SNc）釋放的多巴胺對「直接迴路與間接迴路都有調控作用」：其通過 D1 受體興奮直接迴路（選項C），並通過 D2 受體抑制間接迴路，兩者最終皆傾向於促進運動。因此，選項D稱「間接迴路不受黑質調控」是明顯錯誤的。黑質多巴胺細胞會投射到紋狀體殼部（選項A），直接與間接迴路皆會影響丘腦腹前核（選項B）。",
      "flashcard_front": "基底核 / 直接與間接迴路 / 黑質多巴胺調控 / D1與D2受體",
      "flashcard_back": "黑質釋放的多巴胺同時調控雙迴路：經D1興奮直接迴路，經D2抑制間接迴路，共同促進運動。",
      "flashcard_summary": "基底核 / 直接與間接迴路 / 黑質多巴胺調控 / D1與D2受體 -> 黑質釋放的多巴胺同時調控雙迴路：經D1興奮直接迴路，經D2抑制間接迴路，共同促進運動。"
    },
    {
      "question_id": "109-1_medicine-1_015",
      "question_number": 15,
      "correct_answer": "A",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "丘腦內側膝狀體（MGB）的聽覺傳導大腦皮質投射。",
      "explanation": "丘腦的內側膝狀體（Medial Geniculate Body, MGB，選項A正確）是聽覺傳導通路的重要中繼站，其發出的纖維組成聽輻射，主要投射至大腦皮質的顳橫迴（初級聽覺皮質，Brodmann area 41, 42）。外側膝狀體（LGB）則與視覺相關，投射至枕葉皮質；角迴（選項D）與語言理解相關；島閾（選項C）與嗅覺相關。",
      "flashcard_front": "內側膝狀體 / MGB / 聽覺中繼 / 顳橫迴投射 / 初級聽覺皮質",
      "flashcard_back": "丘腦內側膝狀體（MGB）接收聽覺資訊並投射至顳橫迴（初級聽覺皮質）；外側膝狀體（LGB）與視覺相關。",
      "flashcard_summary": "內側膝狀體 / MGB / 聽覺中繼 / 顳橫迴投射 / 初級聽覺皮質 -> 丘腦內側膝狀體（MGB）接收聽覺資訊並投射至顳橫迴（初級聽覺皮質）；外側膝狀體（LGB）與視覺相關。"
    }
  ]
}

# 109-1_medicine-1_batch-002 (Q16 - Q30)
batch_109_1_med1_002 = {
  "dataset_id": "109-1_medicine-1",
  "batch_id": "109-1_medicine-1_batch-002",
  "items": [
    {
      "question_id": "109-1_medicine-1_016",
      "question_number": 16,
      "correct_answer": "D",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "雙眼顳側偏盲的病損解剖定位。",
      "explanation": "雙眼顳側偏盲（即失去左右兩側的外側視野）是視交叉（optic chiasma，選項D正確）受壓迫（如垂體腺瘤）的典型表現。因為視交叉中僅有來自雙眼鼻側視網膜的纖維（負責接收顳側視野的資訊）進行交叉，此處受損會阻斷交叉纖維，導致雙眼顳側視野缺損。視神經（選項A）受損會導致單眼全盲。",
      "flashcard_front": "雙眼顳側偏盲 / 視交叉壓迫 / 鼻側纖維交叉 / 垂體腺瘤",
      "flashcard_back": "視交叉受壓迫會阻斷交叉的鼻側視網膜纖維，引發雙眼顳側偏盲；常見於垂體腺瘤。",
      "flashcard_summary": "雙眼顳側偏盲 / 視交叉壓迫 / 鼻側纖維交叉 / 垂體腺瘤 -> 視交叉受壓迫會阻斷交叉的鼻側視網膜纖維，引發雙眼顳側偏盲；常見於垂體腺瘤。"
    },
    {
      "question_id": "109-1_medicine-1_017",
      "question_number": 17,
      "correct_answer": "B",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "基底核直接迴路與間接迴路經過的結構差異。",
      "explanation": "基底核的直接迴路路徑為：大腦皮質（選項C）-> 紋狀體 -> 蒼白球內側部（GPi，選項D）/ 黑質網狀部 -> 丘腦（選項A）-> 大腦皮質。在這個迴路中，不經過丘腦下核（subthalamic nucleus, STN，選項B為答案）。丘腦下核是間接迴路中的關鍵興奮性核團，其興奮性投射會激活 GPi 阻斷皮質活動。",
      "flashcard_front": "基底核直接迴路 / 丘腦下核 (STN) / 蒼白球內側 (GPi) / 結構路徑",
      "flashcard_back": "基底核直接迴路不經過丘腦下核（STN）；丘腦下核僅參與間接迴路，具備興奮GPi的功能。",
      "flashcard_summary": "基底核直接迴路 / 丘腦下核 (STN) / 蒼白球內側 (GPi) / 結構路徑 -> 基底核直接迴路不經過丘腦下核（STN）；丘腦下核僅參與間接迴路，具備興奮GPi的功能。"
    },
    {
      "question_id": "109-1_medicine-1_018",
      "question_number": 18,
      "correct_answer": "B",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "耳下腺副交感分泌纖維的走行路徑與受損風險。",
      "explanation": "耳下腺的副交感分泌纖維路徑為：舌咽神經（CN IX）-> 鼓室神經叢 -> 小岩神經 -> 耳神經節（換節後）-> 隨三叉神經 V3 分支「耳顳神經（auriculotemporal nerve）」進入耳下腺支配其分泌。由於耳顳神經緊鄰顳頜關節（TMJ）與外耳道，手術時極易受損而導致分泌功能降低，故選B。顏面神經（選項A）在腺體內穿過但主要支配表情肌運動；舌神經（選項C）支配下頜腺與舌下腺。",
      "flashcard_front": "耳下腺分泌 / 耳顳神經 / 副交感纖維 / TMJ手術受損",
      "flashcard_back": "耳下腺的副交感分泌纖維藉由耳顳神經（auriculotemporal nerve）傳入；TMJ 手術易損傷此神經。",
      "flashcard_summary": "耳下腺分泌 / 耳顳神經 / 副交感纖維 / TMJ手術受損 -> 耳下腺的副交感分泌分泌由耳顳神經傳入，TMJ 手術易損害此神經。"
    },
    {
      "question_id": "109-1_medicine-1_019",
      "question_number": 19,
      "correct_answer": "B",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "動眼神經分支支配睫狀神經節與眼內肌副交感路徑。",
      "explanation": "支配睫狀肌（ciliary muscle）與瞳孔括約肌的副交感節前神經纖維起源於中腦的 E-W 核，隨動眼神經（CN III）走行，並隨其「下分支（inferior branch，選項B正確）」分出副交感根進入睫狀神經節內換節。上分支（選項A）主要支配上直肌與上瞼提肌；鼻睫神經（選項C）為三叉神經 V1 的分支，僅提供一般感覺，穿過但不換節。",
      "flashcard_front": "動眼神經下分支 / 睫狀肌副交感 / 節前纖維 / 睫狀神經節換節",
      "flashcard_back": "支配睫狀肌的副交感節前纖維經由動眼神經下分支進入睫狀神經節換節。",
      "flashcard_summary": "動眼神經下分支 / 睫狀肌副交感 / 節前纖維 / 睫狀神經節換節 -> 支配睫狀肌的副交感節前纖維經由動眼神經下分支進入睫狀神經節換節。"
    },
    {
      "question_id": "109-1_medicine-1_020",
      "question_number": 20,
      "correct_answer": "A",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "動脈韌帶的解剖定位與胚胎血管殘餘關係。",
      "explanation": "動脈韌帶（ligamentum arteriosum，選項A正確）是胚胎時期連接主動脈弓下緣與肺動脈幹（或左肺動脈根部）之間的動脈導管（ductus arteriosus）在出生後閉鎖退化所留下的纖維結締組織索。若出生後未能閉鎖，則臨床上稱為開放性動脈導管（PDA）。它不連接上腔靜脈（選項B、C）或肺靜脈（選項D）。",
      "flashcard_front": "動脈韌帶 / 主動脈與肺動脈 / 胚胎動脈導管 / 出生後閉鎖",
      "flashcard_back": "胚胎期的動脈導管在出生後退化為動脈韌帶，連接於主動脈弓下緣與肺動脈幹之間。",
      "flashcard_summary": "動脈韌帶 / 主動脈與肺動脈 / 胚胎動脈導管 / 出生後閉鎖 -> 胚胎期的動脈導管在出生後退化為動脈韌帶，連接於主動脈弓下緣與肺動脈幹之間。"
    },
    {
      "question_id": "109-1_medicine-1_021",
      "question_number": 21,
      "correct_answer": "C",
      "category_group": "醫學（一）",
      "category": "生理學",
      "category_confidence": "high",
      "key_point": "迷走神經在肺部的生理反射與效應。",
      "explanation": "迷走神經支配肺部的副交感運動與感覺傳導。當其興奮時，會介導支氣管平滑肌收縮（選項D），傳導肺擴張反射（Hering-Breuer 膨脹反射，選項B）以及咳嗽反射（選項A）。然而，肺泡 II 型上皮細胞分泌肺泡表面活性物質主要是受到交感神經刺激或肺泡拉伸的促進，並不受到迷走神經的抑制，故選C與迷走神經無關。",
      "flashcard_front": "迷走神經 / 肺部副交感 / 支氣管收縮 / Hering-Breuer反射 / 表面活性物質",
      "flashcard_back": "迷走神經興奮介導支氣管收縮、咳嗽及肺擴張反射；II型肺泡分泌主要受交感與拉伸調控。",
      "flashcard_summary": "迷走神經 / 肺部副交感 / 支氣管收縮 / Hering-Breuer反射 / 表面活性物質 -> 迷走神經興奮介導支氣管收縮、咳嗽及肺擴張反射；II型肺泡分泌主要受交感與拉伸調控。"
    },
    {
      "question_id": "109-1_medicine-1_022",
      "question_number": 22,
      "correct_answer": "D",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "乳房切除手術清除導致上肢水腫的淋巴結。",
      "explanation": "根除性乳房切除術（radical mastectomy）常需清除同側的腋淋巴結（axillary lymph nodes，選項D正確）以進行癌症分期與局部控制。由於腋淋巴結同時負責引流乳房及同側上肢的淋巴液，清除此處淋巴結及淋巴管會導致上肢淋巴回流受阻，進而引發術後患側上肢水腫。鎖骨上（選項A）或胸骨旁（選項C）淋巴結清除不易直接導致上肢大範圍淋巴水腫。",
      "flashcard_front": "乳房切除術 / 腋淋巴結清除 / 上肢水腫 / 淋巴回流受阻",
      "flashcard_back": "乳癌手術中清除腋淋巴結（axillary nodes）會破壞上肢淋巴引流通道，導致術後上肢水腫。",
      "flashcard_summary": "乳房切除術 / 腋淋巴結清除 / 上肢水腫 / 淋巴回流受阻 -> 乳癌手術中清除腋淋巴結（axillary nodes）會破壞上肢淋巴引流通道，導致術後上肢水腫。"
    },
    {
      "question_id": "109-1_medicine-1_023",
      "question_number": 23,
      "correct_answer": "A",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "胸腺在大腦及胸腔縱隔的分區定位。",
      "explanation": "縱隔以胸骨角至第四胸椎下緣的平面分為上縱隔與下縱隔。胸腺（thymus，在成人多退化為脂肪組織）主要位於上縱隔（選項A正確），並部分向下延伸入下前縱隔（選項B）。心臟位於下中縱隔（選項C），食道與胸主動脈則位於下後縱隔（選項D）。",
      "flashcard_front": "縱隔分區 / 胸腺位置 / 上縱隔 / 下前縱隔延伸",
      "flashcard_back": "胸腺主要定位於上縱隔（superior mediastinum），並可部分延伸入下前縱隔；中縱隔含心臟。",
      "flashcard_summary": "縱隔分區 / 胸腺位置 / 上縱隔 / 下前縱隔延伸 -> 胸腺主要定位於上縱隔（superior mediastinum），並可部分延伸入下前縱隔；中縱隔含心臟。"
    },
    {
      "question_id": "109-1_medicine-1_024",
      "question_number": 24,
      "correct_answer": "B",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "縱隔壓迫（如肺癌）導致聲帶麻痺的神經機制。",
      "explanation": "喉返神經（recurrent laryngeal nerve，選項B正確）是迷走神經的分支，支配除聲帶張肌外的所有喉內肌。左側喉返神經在主動脈弓下緣繞行，右側在右鎖骨下動脈繞行。肺癌（特別是左肺尖癌或縱隔淋巴結轉移）極易壓迫左側喉返神經，導致聲帶麻痺與聲音沙啞。膈神經（選項A）支配膈肌運動；交感神經幹受損會導致 Horner 氏症候群；肋間神經支配胸壁。",
      "flashcard_front": "肺癌壓迫 / 聲帶麻痺 / 聲音沙啞 / 喉返神經 / 左側主動脈弓下",
      "flashcard_back": "喉返神經（特別是左側）因其縱隔路徑長，易受肺癌或腫瘤壓迫，引發聲帶麻痺與沙啞。",
      "flashcard_summary": "肺癌壓迫 / 聲帶麻痺 / 聲音沙啞 / 喉返神經 / 左側主動脈弓下 -> 喉返神經（特別是左側）因其縱隔路徑長，易受肺癌或腫瘤壓迫，引發聲帶麻痺與沙啞。"
    },
    {
      "question_id": "109-1_medicine-1_025",
      "question_number": 25,
      "correct_answer": "D",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "幽門平面（transpyloric plane）上通過的腹腔構造定位。",
      "explanation": "幽門平面是通過第一腰椎（L1）水平的橫斷面。此平面上通過的構造包括：胃幽門、十二指腸空腸曲（選項A）、左右腎門的連線（選項B）、膽囊底、胰臟體以及 L1 體（選項C）。而脾臟位於左上腹，其脾門（splenic hilum，選項D）位置通常較高（約在 T10-T11 水平），不在 L1 的幽門平面上，故選D。",
      "flashcard_front": "幽門平面 / L1水平 / 腎門與十二指腸空腸曲 / 脾門位置較高",
      "flashcard_back": "幽門平面位於L1高度，通過腎門、胰臟及十二指腸空腸曲；脾門位置較高，不在其上。",
      "flashcard_summary": "幽門平面 / L1水平 / 腎門與十二指腸空腸曲 / 脾門位置較高 -> 幽門平面位於L1高度，通過腎門、胰臟及十二指腸空腸曲；脾門位置較高，不在其上。"
    },
    {
      "question_id": "109-1_medicine-1_026",
      "question_number": 26,
      "correct_answer": "A",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "支配腎上腺髓質嗜鉻細胞的交感神經纖維類型。",
      "explanation": "腎上腺髓質的嗜鉻細胞在胚胎發育上相當於特化的交感神經節後神經元。因此，支配髓質的交感神經纖維必須是「節前神經纖維」，它們直接隨內臟大/小神經（其中小內臟神經攜帶部分纖維，選項A正確）穿過交感神經節而不換節，直接與嗜鉻細胞形成突觸。腹腔神經節（選項B）與主動脈腎神經節（選項C）發出的是節後纖維；下腹下叢（選項D）支配盆腔臟器。",
      "flashcard_front": "腎上腺髓質 / 嗜鉻細胞 / 特化節後神經元 / 節前交感纖維 / 小內臟神經",
      "flashcard_back": "支配腎上腺髓質的是交感節前纖維（隨內臟神經傳入），嗜鉻細胞本身相當於特化的節後神經元。",
      "flashcard_summary": "腎上腺髓質 / 嗜鉻細胞 / 特化節後神經元 / 節前交感纖維 / 小內臟神經 -> 支配腎上腺髓質的是交感節前纖維（隨內臟神經傳入），嗜鉻細胞本身相當於特化的節後神經元。"
    },
    {
      "question_id": "109-1_medicine-1_027",
      "question_number": 27,
      "correct_answer": "A",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "骨盆底肌中維持肛直腸彎曲角度與排便禁制的肌肉。",
      "explanation": "肛直腸彎曲（通常約 80 度角）是維持排便控制的重要解剖屏障。該彎曲是由提肛肌的分支——恥直腸肌（puborectalis muscle，選項A正確）呈「U」字形繞過直腸與肛管交界處向前牽拉所形成。當此肌收縮時，角度變銳利以阻止排便；放鬆時，直腸變直以利排便。恥尾肌（選項B）與外括約肌（選項D）不直接維持此夾角。",
      "flashcard_front": "肛直腸彎曲 / 恥直腸肌 / puborectalis / 排便控制",
      "flashcard_back": "恥直腸肌呈U形繞過直腸，向前牽引形成肛直腸彎曲，是維持排便禁制的關鍵。",
      "flashcard_summary": "肛直腸彎曲 / 恥直腸肌 / puborectalis / 排便控制 -> 恥直腸肌呈U形繞過直腸，向前牽引形成肛直腸彎曲，是維持排便禁制的關鍵。"
    },
    {
      "question_id": "109-1_medicine-1_028",
      "question_number": 28,
      "correct_answer": "B",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "會陰淺凹與會陰深凹的包含構造區分。",
      "explanation": "會陰淺凹（superficial perineal pouch）內含勃起組織如陰莖根/陰蒂根（1）、坐骨海綿體肌（4）及女性的大前庭腺（3）。而球尿道腺（2，僅限男性）與尿道外括約肌（5）則位於會陰深凹內，因此屬於會陰淺凹構造的為 1, 3, 4，答案為B。",
      "flashcard_front": "會陰淺凹 / 陰莖根 / 坐骨海綿體肌 / 大前庭腺 / 深凹對比",
      "flashcard_back": "會陰淺凹內含陰莖根、坐骨海綿體肌及大前庭腺；球尿道腺與尿道外括約肌則定位於會陰深凹。",
      "flashcard_summary": "會陰淺凹 / 陰莖根 / 坐骨海綿體肌 / 大前庭腺 / 深凹對比 -> 會陰淺凹內含陰莖根、坐骨海綿體肌及大前庭腺；球尿道腺與尿道外括約肌則定位於會陰深凹。"
    },
    {
      "question_id": "109-1_medicine-1_029",
      "question_number": 29,
      "correct_answer": "D",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "大腿各側肌群的神經支配分布。",
      "explanation": "大腿後側肌群（膕繩肌，包括股二頭肌、半腱肌、半膜肌）主要負責膝關節屈曲與髖關節伸展，其神經支配為坐骨神經（sciatic nerve，選項D正確，主要為其中的脛神經支，股二頭肌短頭由腓總神經支配）。股神經（選項A）支配大腿前側肌群；閉孔神經（選項C）支配大腿內側內收肌群；脛神經（選項B）支配小腿後側肌群。",
      "flashcard_front": "膕繩肌 / 大腿後側 / 坐骨神經支配 / 前側股神經 / 內側閉孔",
      "flashcard_back": "大腿後側肌群（膕繩肌）由坐骨神經支配；前側由股神經支配；內側由閉孔神經支配。",
      "flashcard_summary": "膕繩肌 / 大腿後側 / 坐骨神經支配 / 前側股神經 / 內側閉孔 -> 大腿後側肌群（膕繩肌）由坐骨神經支配；前側由股神經支配；內側由閉孔神經支配。"
    },
    {
      "question_id": "109-1_medicine-1_030",
      "question_number": 30,
      "correct_answer": "D",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "肌皮神經支配的上臂前側屈肌群與肱橈肌的橈神經支配。",
      "explanation": "肌皮神經支配上臂前群的所有屈肌，包括喙肱肌（選項C）、肱二頭肌（選項B）及大部分肱肌（選項A）。肱橈肌（選項D）雖然也是前臂屈肌，但其解剖結構上定位於前臂外側，其神經支配為橈神經，因此在肌皮神經受損時最不可能受到影響，故選D。",
      "flashcard_front": "肌皮神經 / 上臂前側屈肌 / 肱二頭肌與肱肌 / 肱橈肌 (橈神經)",
      "flashcard_back": "肌皮神經支配肱二頭肌、喙肱肌與肱肌；肱橈肌雖能屈肘，但由橈神經支配。",
      "flashcard_summary": "肌皮神經 / 上臂前側屈肌 / 肱二頭肌與肱肌 / 肱橈肌 (橈神經) -> 肌皮神經支配肱二頭肌、喙肱肌與肱肌；肱橈肌雖能屈肘，但由橈神經支配。"
    }
  ]
}

# 109-1_medicine-1_batch-003 (Q31 - Q45)
batch_109_1_med1_003 = {
  "dataset_id": "109-1_medicine-1",
  "batch_id": "109-1_medicine-1_batch-003",
  "items": [
    {
      "question_id": "109-1_medicine-1_031",
      "question_number": 31,
      "correct_answer": "C",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "橈腕關節（腕關節）的組成骨頭交通。",
      "explanation": "橈腕關節（腕關節）是由橈骨遠端關節面及關節盤，與近側列腕骨中的舟狀骨（scaphoid）及月狀骨（lunate，以及三角骨的一部分）共同組成關節，故選C。大多角骨與小多角骨（選項A）、頭狀骨與鉤狀骨（選項B）屬於遠側列腕骨；豆狀骨（選項D）是附著於尺側腕屈肌腱上的籽骨，不參與橈腕關節。",
      "flashcard_front": "橈腕關節 / 橈骨遠端 / 舟狀骨 / 月狀骨 / 尺骨不參與",
      "flashcard_back": "橈骨遠端直接與舟狀骨（scaphoid）及月狀骨（lunate）形成關節，尺骨不直接參與。",
      "flashcard_summary": "橈腕關節 / 橈骨遠端 / 舟狀骨 / 月狀骨 / 尺骨不參與 -> 橈骨遠端直接與舟狀骨（scaphoid）及月狀骨（lunate）形成關節，尺骨不直接參與。"
    },
    {
      "question_id": "109-1_medicine-1_032",
      "question_number": 32,
      "correct_answer": "C",
      "category_group": "醫學（一）",
      "category": "胚胎及發育生物學",
      "category_confidence": "high",
      "key_point": "胚胎發育中橫膈的下降與背側最終腰椎定位。",
      "explanation": "在胚胎發育早期，橫膈的原基橫膈膜位於頸椎 C3-C5 水平。隨著頸部伸展及胸腔、心肺的快速生長，橫膈逐步向下遷移。到了發育的第8週，其背側附著部（如左右膈腳）最終定位於第一腰椎（L1，選項C正確）的高度。這也解釋了為何起源於頸部的膈神經（C3-C5）必須向下行經整個胸腔。",
      "flashcard_front": "橫膈發育 / 胚胎膈下移 / 最終高度 L1 / 膈神經 C3-C5 起源",
      "flashcard_back": "胚胎發育中橫膈原基自頸部下移，其背側部分最終到達 L1 椎骨高度，由C3-C5發源的膈神經支配。",
      "flashcard_summary": "橫膈發育 / 胚胎膈下移 / 最終高度 L1 / 膈神經 C3-C5 起源 -> 胚胎發育中橫膈原基自頸部下移，其背側部分最終到達 L1 椎骨高度，由C3-C5發源的膈神經支配。"
    },
    {
      "question_id": "109-1_medicine-1_033",
      "question_number": 33,
      "correct_answer": "A",
      "category_group": "醫學（一）",
      "category": "胚胎及發育生物學",
      "category_confidence": "high",
      "key_point": "胚胎咽溝的命運與外聽道的形成來源。",
      "explanation": "在胚胎頭頸部發育中，只有「第一對咽溝（pharyngeal groove，選項A正確）」會持續存在並深入發育為外聽道（external acoustic meatus）。其內側的第一咽囊則衍生為中耳鼓室與耳咽管。第二、三、四對咽溝則會被向下方生長的第二咽弓覆蓋，形成一個暫時性的頸竇，隨後完全閉鎖消失。",
      "flashcard_front": "第一咽溝 / 咽溝發育 / 外聽道來源 / 頸竇 (cervical sinus)",
      "flashcard_back": "第一咽溝是唯一持續存在並發育為外聽道的咽溝；第二至四咽溝閉鎖消失，若未閉鎖會形成頸廔管。",
      "flashcard_summary": "第一咽溝 / 咽溝發育 / 外聽道來源 / 頸竇 (cervical sinus) -> 第一咽溝是唯一持續存在並發育為外聽道的咽溝；第二至四咽溝閉鎖消失，若未閉鎖會形成頸廔管。"
    },
    {
      "question_id": "109-1_medicine-1_034",
      "question_number": 34,
      "correct_answer": "B",
      "category_group": "醫學（一）",
      "category": "胚胎及發育生物學",
      "category_confidence": "high",
      "key_point": "睪丸下降與腹膜鞘突閉鎖異常導致的疾病。",
      "explanation": "睪丸在胚胎期下降至陰囊時，會牽引腹膜形成一個突起稱為鞘突（processus vaginalis，選項B正確）。正常情況下，鞘突的近端及中段在出生前會自行閉鎖。若精索部位的鞘突閉鎖不全（中段未閉且積液），便會形成精索積水。若完全未閉鎖，則會引發先天性腹股溝疝氣。白膜（選項A）是睪丸的固有包膜。",
      "flashcard_front": "鞘突 / processus vaginalis / 精索積水 / 閉鎖不全 / 疝氣相關",
      "flashcard_back": "腹膜鞘突（processus vaginalis）在精索段閉鎖不全會導致精索積水；完全未閉鎖則導致先天性腹股溝斜疝。",
      "flashcard_summary": "鞘突 / processus vaginalis / 精索積水 / 閉鎖不全 / 疝氣相關 -> 腹膜鞘突（processus vaginalis）在精索段閉鎖不全會導致精索積水；完全未閉鎖則導致先天性腹股溝斜疝。"
    },
    {
      "question_id": "109-1_medicine-1_035",
      "question_number": 35,
      "correct_answer": "A",
      "category_group": "醫學（一）",
      "category": "解剖學",
      "category_confidence": "high",
      "key_point": "前腹壁的腹膜皺襞與胚胎血管殘餘的對應。",
      "explanation": "前腹壁有五條由腹膜覆蓋韌帶形成的皺襞：一條正中臍皺襞（由退化的臍尿管形成，選項B）、兩條內側臍皺襞（由退化的臍動脈實體段形成，選項D）、以及兩條外側臍皺襞（由仍在使用的下腹壁動脈形成，選項C）。而靜脈導管（ductus venosus，選項A）位於肝臟後方的膈面，退化後形成靜脈韌帶，不在前腹壁上造成任何腹膜皺襞，故選A。",
      "flashcard_front": "前腹壁皺襞 / 臍尿管 (正中) / 臍動脈 (內側) / 下腹壁動脈 (外側) / 靜脈導管非前腹壁",
      "flashcard_back": "靜脈導管位於肝臟，退化為靜脈韌帶；前腹壁皺襞由臍尿管、臍動脈及下腹壁動脈形成。",
      "flashcard_summary": "前腹壁皺襞 / 臍尿管 (正中) / 臍動脈 (內側) / 下腹壁動脈 (外側) / 靜脈導管非前腹壁 -> 靜脈導管位於肝臟，退化為靜脈韌帶；前腹壁皺襞由臍尿管、臍動脈及下腹壁動脈形成。"
    },
    {
      "question_id": "109-1_medicine-1_036",
      "question_number": 36,
      "correct_answer": "C",
      "category_group": "醫學（一）",
      "category": "胚胎及發育生物學",
      "category_confidence": "high",
      "key_point": "神經顱與臟顱的發育起源、分區與保護功能。",
      "explanation": "顱骨分為包繞保護大腦的神經顱（neurocranium，這才是大腦的主要保護結構）以及構成面部支架的臟顱（viscerocranium），因此選項C稱「臟顱是大腦的主要保護結構」是錯誤的。顱骨起源於脊索與腦組織周圍的間充質（選項A）；神經顱的一部分（枕骨、蝶骨等）由多塊軟骨癒合經軟骨內骨化形成（選項B）；第一、二咽弓會參與發育為軟骨性臟顱（如聽小骨、舌骨，選項D）。",
      "flashcard_front": "神經顱 / 臟顱 / 大腦主要保護 / 第一、二咽弓參與",
      "flashcard_back": "包繞並保護大腦的結構是神經顱而非臟顱；臟顱形成面部支架，部分由第一、二咽弓發育而來。",
      "flashcard_summary": "神經顱 / 臟顱 / 大腦主要保護 / 第一、二咽弓參與 -> 包繞並保護大腦的結構是神經顱而非臟顱；臟顱形成面部支架，部分由第一、二咽弓發育而來。"
    },
    {
      "question_id": "109-1_medicine-1_037",
      "question_number": 37,
      "correct_answer": "A",
      "category_group": "醫學（一）",
      "category": "組織學",
      "category_confidence": "high",
      "key_point": "類上皮組織（epithelioid tissue）的結構特徵與游離表面缺乏。",
      "explanation": "類上皮組織（epithelioid tissue）是由緊密相鄰、具有上皮樣外觀的細胞所組成的組織，如間質細胞（Leydig cells）、腎上腺髓質細胞等。雖然它們有緊密連接組成的側區（選項B）與基底區（選項C、D），但其典型特徵是「不具備游離面（free surface，不與外界或管腔腔面接觸）」，因此選項A稱其「有游離表面」是錯誤的（為本題答案）。",
      "flashcard_front": "類上皮組織 / epithelioid / 游離面 (free surface) 缺乏 / 基底與側區完整",
      "flashcard_back": "類上皮組織（如腎上腺皮質、Leydig細胞）具有側區與基底區，但「無游離面」，此與典型上皮不同。",
      "flashcard_summary": "類上皮組織 / epithelioid / 游離面 (free surface) 缺乏 / 基底與側區完整 -> 類上皮組織（如腎上腺皮質、Leydig細胞）具有側區與基底區，但「無游離面」，此與典型上皮不同。"
    },
    {
      "question_id": "109-1_medicine-1_038",
      "question_number": 38,
      "correct_answer": "D",
      "category_group": "醫學（一）",
      "category": "組織學",
      "category_confidence": "high",
      "key_point": "平滑肌細胞收縮單元中的細肌絲固著結構。",
      "explanation": "平滑肌細胞內沒有骨骼肌中的Z盤結構。在平滑肌中，細肌絲（含肌動蛋白）和中間絲會共同固著在細胞質內及細胞膜下的一種特殊蛋白質結構——緻密體（dense body，選項D正確），相當於骨骼肌的Z線。胞飲小泡與小凹與物質轉運及鈣內流有關；平滑肌沒有橫小管（選項B）。",
      "flashcard_front": "平滑肌 / 緻密體 / dense body / 細肌絲與中間絲固著 / 相當於Z線",
      "flashcard_back": "平滑肌細胞內細肌絲與中間絲錨定在緻密體（dense body）上；平滑肌無Z線與橫小管。",
      "flashcard_summary": "平滑肌 / 緻密體 / dense body / 細肌絲與中間絲固著 / 相當於Z線 -> 平滑肌細胞內細肌絲與中間絲錨定在緻密體（dense body）上；平滑肌無Z線與橫小管。"
    },
    {
      "question_id": "109-1_medicine-1_039",
      "question_number": 39,
      "correct_answer": "A",
      "category_group": "醫學（一）",
      "category": "組織學",
      "category_confidence": "high",
      "key_point": "骨髓的竇狀血管系統與新生血球穿透機制。",
      "explanation": "骨髓的血管系統由竇狀隙（sinusoids）組成，其屬於封閉型循環系統（血管壁完整），新生的血球必須以「跨內皮移行（transendothelial migration）」的方式主動穿透內皮細胞進入血流，故選A。黃骨髓充滿脂肪細胞，是不活化的骨髓，無造血功能（選項B錯誤）；造血空間充滿網狀結締組織而非纖維母細胞（選項C錯誤）；巨核細胞釋放血小板時，是將其胞質突起伸入竇壁孔內直接釋放，不需網狀細胞協助（選項D錯誤）。",
      "flashcard_front": "骨髓 / 竇狀隙 / 封閉型循環 / 跨內皮移行 / 黃骨髓無造血",
      "flashcard_back": "骨髓為封閉循環，新生血球需穿透內皮進入血管；黃骨髓是不造血的脂肪組織。",
      "flashcard_summary": "骨髓 / 竇狀隙 / 封閉型循環 / 跨內皮移行 / 黃骨髓無造血 -> 骨髓為封閉循環，新生血球需穿透內皮進入血管；黃骨髓是不造血的脂肪組織。"
    },
    {
      "question_id": "109-1_medicine-1_040",
      "question_number": 40,
      "correct_answer": "A",
      "category_group": "醫學（一）",
      "category": "組織學",
      "category_confidence": "high",
      "key_point": "周邊神經神經內膜中膠原纖維的合成來源。",
      "explanation": "在周邊神經組織中，神經內膜包裹在單根神經纖維外，其內部的膠原纖維主要並非由纖維母細胞合成，而是由施旺細胞（Schwann cells，即髓鞘形成細胞）合成並分泌的，因此選項A錯誤（本題答案）。神經束膜由多層扁平的神經束膜細胞組成（選項B），其間的緊密連接構成血-神經屏障（選項C）；神經外膜由緻密結締組織組成，包裹整條神經（選項D）。",
      "flashcard_front": "神經內膜 / endoneurium / 膠原纖維 / 施旺細胞合成 / 神經束膜緊密連接",
      "flashcard_back": "神經內膜的膠原纖維主要由施旺細胞（非纖維母細胞）合成；神經束膜細胞的緊密連接構成血-神經屏障。",
      "flashcard_summary": "神經內膜 / endoneurium / 膠原纖維 / 施旺細胞合成 / 神經束膜緊密連接 -> 神經內膜的膠原纖維主要由施旺細胞（非纖維母細胞）合成；神經束膜細胞的緊密連接構成血-神經屏障。"
    },
    {
      "question_id": "109-1_medicine-1_041",
      "question_number": 41,
      "correct_answer": "C",
      "category_group": "醫學（一）",
      "category": "組織學",
      "category_confidence": "high",
      "key_point": "第一型肺泡細胞（type-I pneumocyte）的結構與功能定位。",
      "explanation": "Ⅰ型肺泡細胞（type-I pneumocyte）是極薄的扁平上皮細胞，其與毛細血管內皮細胞及其融合的基底膜共同構成氣血屏障（負責氣體交換），故選C。層狀體（lamellar body）是負責分泌肺泡表面活性物質的Ⅱ型肺泡細胞的特徵（選項A錯誤）；吞噬塵埃的是肺泡巨噬細胞（選項B錯誤）；Ⅰ型細胞僅占肺泡細胞總數的40%，但因其極扁平，覆蓋了95%的肺泡表面積（選項D錯誤，此處數據與佔比顛倒）。",
      "flashcard_front": "I型肺泡細胞 / 氣血屏障 / 扁平上皮 / 覆蓋95%面積 / II型層狀體",
      "flashcard_back": "I型肺泡細胞扁平，與內皮細胞組成氣血屏障；II型細胞有層狀體且分泌表面活性物質。",
      "flashcard_summary": "I型肺泡細胞 / 氣血屏障 / 扁平上皮 / 覆蓋95%面積 / II型層狀體 -> I型肺泡細胞扁平，與內皮細胞組成氣血屏障；II型細胞有層狀體且分泌表面活性物質。"
    },
    {
      "question_id": "109-1_medicine-1_042",
      "question_number": 42,
      "correct_answer": "B",
      "category_group": "醫學（一）",
      "category": "組織學",
      "category_confidence": "high",
      "key_point": "膽囊內襯黏膜的上皮分類。",
      "explanation": "膽囊主要負責儲存與濃縮膽汁，其黏膜層具有許多高皺襞，其內襯上皮為單層柱狀上皮（simple columnar epithelium，與小腸上皮相似，具有發育良好的微絨毛以利水分吸收），故選B。移形上皮（選項A）位於泌尿道；複層柱狀（選項C）見於大導管；角質化複層扁平（選項D）見於皮膚表皮。",
      "flashcard_front": "膽囊內襯上皮 / 單層柱狀 / simple columnar / 濃縮膽汁 / 微絨毛",
      "flashcard_back": "膽囊的內襯上皮是單層柱狀上皮（simple columnar），富含微絨毛以重吸收水分濃縮膽汁。",
      "flashcard_summary": "膽囊內襯上皮 / 單層柱狀 / simple columnar / 濃縮膽汁 / 微絨毛 -> 膽囊的內襯上皮是單層柱狀上皮（simple columnar），富含微絨毛以重吸收水分濃縮膽汁。"
    },
    {
      "question_id": "109-1_medicine-1_043",
      "question_number": 43,
      "correct_answer": "B",
      "category_group": "醫學（一）",
      "category": "組織學",
      "category_confidence": "high",
      "key_point": "胃黏膜層細胞組成與腸道特有細胞的辨識。",
      "explanation": "胃黏膜的上皮為單層柱狀，主要由表面黏液細胞（選項A）、胃底腺中的壁細胞（parietal cells，分泌胃酸，選項C）、主細胞以及未分化的幹細胞（選項D）組成。而杯狀細胞（goblet cells，選項B）是「小腸和大腸」黏膜的特徵性分泌細胞，正常胃黏膜中沒有；若在胃中發現杯狀細胞，臨床上稱為腸上皮化生，屬於癌前病變。",
      "flashcard_front": "胃黏膜細胞 / 表面黏液細胞 / 壁細胞 / 杯狀細胞缺乏 (腸道特有)",
      "flashcard_back": "胃黏膜沒有杯狀細胞（杯狀細胞分布於小腸和大腸）；胃黏膜出現杯狀細胞為腸上皮化生。",
      "flashcard_summary": "胃黏膜細胞 / 表面黏液細胞 / 壁細胞 / 杯狀細胞缺乏 (腸道特有) -> 胃黏膜沒有杯狀細胞（杯狀細胞分布於小腸和大腸）；胃黏膜出現杯狀細胞為腸上皮化生。"
    },
    {
      "question_id": "109-1_medicine-1_044",
      "question_number": 44,
      "correct_answer": "C",
      "category_group": "醫學（一')胎",
      "category": "組織學",
      "category_confidence": "high",
      "key_point": "游離神經末梢在皮膚表皮層的分佈終點。",
      "explanation": "游離神經末梢（free nerve endings）是皮膚中負責傳導痛覺、溫度覺與粗觸覺的無髓鞘感覺纖維。它們穿過真皮-表皮交界處的基底膜，在表皮的基底層（選項A）與棘狀層（選項B）中分支，最遠可向上延伸並終止於「顆粒層（stratum granulosum，選項C正確）」。它們不會穿入最外層的死細胞角質層（選項D）。",
      "flashcard_front": "游離神經末梢 / 皮膚表皮 / 痛溫覺傳導 / 顆粒層 / 角質層無分布",
      "flashcard_back": "傳導痛溫覺的游離神經末梢可穿入表皮，最遠可抵達顆粒層（stratum granulosum），不入角質層。",
      "flashcard_summary": "游離神經末梢 / 皮膚表皮 / 痛溫覺傳導 / 顆粒層 / 角質層無分布 -> 傳導痛溫覺的游離神經末梢可穿入表皮，最遠可抵達顆粒層（stratum granulosum），不入角質層。"
    },
    {
      "question_id": "109-1_medicine-1_045",
      "question_number": 45,
      "correct_answer": "A",
      "category_group": "醫學（一）",
      "category": "組織學",
      "category_confidence": "high",
      "key_point": "輸精管壁平滑肌分層與精索管道組織結構特徵。",
      "explanation": "輸精管（ductus deferens）是一條壁厚腔小的管道，其管壁的肌層極為發達，由內縱、中環、外縱三層平滑肌構成，強力的收縮可推動精子排出，故選A。其內襯上皮為假複層柱狀上皮，非單層柱狀上皮（選項C錯誤）；蔓狀叢是由多條特殊的小型/中型靜脈組成，且其靜脈壁中含有極厚的縱行平滑肌（非典型中型靜脈，選項B錯誤）；精索中主要由疏鬆結締組織、血管、神經填充，非網狀纖維（選項D錯誤）。",
      "flashcard_front": "輸精管 / 三層平滑肌 / 內縱、中環、外縱 / 假複層柱狀上皮 / 蔓狀叢靜脈",
      "flashcard_back": "輸精管具有三層發達平滑肌（內縱、中環、外縱）；蔓狀叢靜脈壁內含有特化肥厚的平滑肌層。",
      "flashcard_summary": "輸精管 / 三層平滑肌 / 內縱、中環、外縱 / 假複層柱狀上皮 / 蔓狀叢靜脈 -> 輸精管具有三層發達平滑肌（內縱、中環、外縱）；蔓狀叢靜脈壁內含有特化肥厚的平滑肌層。"
    }
  ]
}

# Correct category group for 109-1_medicine-1_044 is "醫學（一）" (fixed a typo in category_group)
batch_109_1_med1_003["items"][-2]["category_group"] = "醫學（一）"

# Helper to write files
def write_batch(batch_data, file_name):
    target_path = Path(f"reports/gemini_outputs/{file_name}.json")
    # Pretty print JSON with ensure_ascii=False
    json_str = json.dumps(batch_data, ensure_ascii=False, indent=2)
    target_path.write_text(json_str, encoding="utf-8")
    print(f"Successfully generated {target_path}")

write_batch(batch_108_2_med6_002, "108-2_medicine-6_batch-002")
write_batch(batch_108_2_med6_003, "108-2_medicine-6_batch-003")
write_batch(batch_108_2_med6_004, "108-2_medicine-6_batch-004")
write_batch(batch_108_2_med6_005, "108-2_medicine-6_batch-005")
write_batch(batch_108_2_med6_006, "108-2_medicine-6_batch-006")
write_batch(batch_109_1_med1_001, "109-1_medicine-1_batch-001")
write_batch(batch_109_1_med1_002, "109-1_medicine-1_batch-002")
write_batch(batch_109_1_med1_003, "109-1_medicine-1_batch-003")
print("Done writing all 8 batches!")
