const fs = require("node:fs");
const path = require("node:path");

const sourceFile = "public/data/exams/111-1/medicine-2.json";
const datasetId = "111-1_medicine-2";
const outDir = "scratch/rewrite_updates/111-1_medicine-2";
const now = "2026-08-12T22:35:00+08:00";
const model = "codex-high-quality-detemplate-rewrite";

const rewrites = {
  1: {
    stem: "本題問分枝桿菌屬的例外特徵。Mycobacterium 的細胞壁富含 mycolic acid，因此抗酸染色陽性，且通常生長慢；但其基因組 GC 含量偏高，不是低 GC ratio，所以答案選 D。",
    options: {
      A: "錯誤。Mycolic acid 是分枝桿菌細胞壁的重要脂質，造成抗酸性與對許多藥物、染劑較不易通透，這是典型特徵。",
      B: "錯誤。分枝桿菌多數生長緩慢，結核分枝桿菌培養常需數週；大腸桿菌則可在一般培養條件下快速生長。",
      C: "錯誤。抗酸染色正是辨識分枝桿菌的重要方法，因 mycolic acid 讓菌體可保留 carbol fuchsin。",
      D: "正確。分枝桿菌的 GC ratio 通常偏高；說其染色體 G+C 比例較低，才是本題要找的錯誤敘述。",
    },
    core: "Mycobacterium 的高產考點是 mycolic acid、抗酸染色、生長慢與較高 GC content。遇到「何者不是」時，低 GC ratio 是例外。",
    key: "分枝桿菌具 mycolic acid、抗酸性與慢生長，GC ratio 不是偏低。",
    front: "Mycobacterium / mycolic acid / acid-fast stain / GC ratio",
    back: "分枝桿菌細胞壁有 mycolic acid、抗酸染色陽性且生長慢；其 GC ratio 通常偏高，不是偏低。",
    summary: "分枝桿菌特徵 -> mycolic acid、抗酸、慢生長、高 GC",
  },
  2: {
    stem: "題幹強調必須在含氮氣操作箱或厭氧系統培養，代表要找嚴格厭氧菌。破傷風桿菌 Clostridium tetani 為產芽孢革蘭陽性厭氧桿菌，答案選 B。",
    options: {
      A: "錯誤。Bacillus cereus 是產芽孢革蘭陽性桿菌，但屬需氧或兼性厭氧，並非只能在嚴格厭氧環境生長。",
      B: "正確。Clostridium tetani 是 obligate anaerobe，培養需要厭氧條件，臨床上也與深部缺氧傷口相關。",
      C: "錯誤。Staphylococcus aureus 是兼性厭氧菌，可在一般含氧培養條件下生長。",
      D: "錯誤。Listeria monocytogenes 是兼性胞內菌，也是兼性厭氧，並不需要只能用厭氧系統培養。",
    },
    core: "Clostridium 屬多為產芽孢厭氧桿菌；Bacillus 屬雖也產芽孢，但多為需氧或兼性厭氧。",
    key: "Clostridium tetani 是嚴格厭氧、產芽孢革蘭陽性桿菌。",
    front: "obligate anaerobe / Clostridium tetani / Bacillus",
    back: "破傷風桿菌需厭氧培養；金葡菌、李斯特菌為兼性厭氧，仙人掌桿菌不是只能厭氧培養。",
    summary: "厭氧培養題 -> Clostridium tetani",
  },
  3: {
    stem: "白喉毒素是 A-B toxin；B 次單元負責結合細胞，A 次單元進入後 ADP-ribosylate elongation factor-2，使 EF-2 失活並抑制蛋白質合成，答案選 C。",
    options: {
      A: "錯誤。40S 次單元是真核小核糖體次單元，白喉毒素不是直接與 40S 結合。",
      B: "錯誤。60S 次單元不是白喉毒素的直接標的；題目要找的是延長階段的 EF-2。",
      C: "正確。Diphtheria toxin 會使 EF-2 失活，轉譯延長反應停止，細胞蛋白質合成被抑制。",
      D: "錯誤。EF-3 主要見於真菌轉譯系統，並非白喉毒素在人體細胞中的經典標的。",
    },
    core: "白喉毒素的關鍵是 ADP-ribosylation of EF-2；Pseudomonas exotoxin A 也可考同一個 EF-2 標的。",
    key: "白喉毒素使 EF-2 失活，抑制蛋白質合成。",
    front: "diphtheria toxin / EF-2 / ADP-ribosylation",
    back: "白喉毒素 A 次單元 ADP-ribosylate EF-2，阻斷轉譯延長。",
    summary: "白喉毒素 -> EF-2 失活 -> 蛋白質合成停止",
  },
  4: {
    stem: "本題問哪一個抗生素不是抑制細菌蛋白質合成。Kanamycin、clindamycin、tetracycline 都作用於核糖體；metronidazole 在厭氧環境形成自由基傷害 DNA，答案選 C。",
    options: {
      A: "錯誤。Kanamycin 屬 aminoglycoside，主要作用於 30S 核糖體，干擾蛋白質合成並造成誤讀 mRNA。",
      B: "錯誤。Clindamycin 作用於 50S 核糖體，抑制 peptide chain elongation。",
      C: "正確。Metronidazole 經厭氧菌還原後產生活性自由基，破壞 DNA，不是靠抑制核糖體蛋白質合成。",
      D: "錯誤。Tetracycline 作用於 30S，阻止 aminoacyl-tRNA 進入 A site。",
    },
    core: "蛋白質合成抑制藥常考 30S aminoglycoside/tetracycline 與 50S macrolide/clindamycin/chloramphenicol；metronidazole 是 DNA damage。",
    key: "Metronidazole 抗厭氧菌靠 DNA 損傷，不是蛋白質合成抑制。",
    front: "protein synthesis inhibitors / metronidazole / DNA damage",
    back: "Kanamycin、tetracycline 作用 30S，clindamycin 作用 50S；metronidazole 傷害 DNA。",
    summary: "抗生素機轉 -> metronidazole 不是核糖體抑制劑",
  },
  5: {
    stem: "題目比較細胞膜 sterols。哺乳類細胞膜有 cholesterol，真菌有 ergosterol，Mycoplasma 可從宿主取得 sterol；典型細菌細胞膜不含 sterol，結核分枝桿菌雖細胞壁富脂質，但不以膜固醇為成分，答案選 B。",
    options: {
      A: "錯誤。哺乳類細胞膜含 cholesterol，是維持膜流動性的重要成分。",
      B: "正確。Mycobacterium tuberculosis 是細菌，細胞壁有 mycolic acid，但細胞膜不以 sterols 為典型成分。",
      C: "錯誤。Mycoplasma pneumoniae 缺乏細胞壁，細胞膜可含 sterols，這是黴漿菌的特殊點。",
      D: "錯誤。真菌細胞膜含 ergosterol，這也是 amphotericin B、azole 類藥物的治療標的。",
    },
    core: "Sterol 記憶：哺乳類 cholesterol、真菌 ergosterol、黴漿菌可有 sterol；多數細菌沒有 sterol。",
    key: "結核分枝桿菌屬細菌，細胞膜不含典型固醇。",
    front: "sterol / Mycoplasma / fungus / Mycobacterium",
    back: "真菌有 ergosterol、哺乳類有 cholesterol、Mycoplasma 可含 sterol；典型細菌如結核分枝桿菌不含 sterol。",
    summary: "膜固醇 -> 細菌通常無，Mycoplasma 與真菌例外要記",
  },
  6: {
    stem: "遊走性紅斑 erythema migrans 是萊姆病的典型早期皮膚病灶，病原為 Borrelia burgdorferi，經 Ixodes tick 傳播，答案選 D。",
    options: {
      A: "錯誤。Coxiella burnetii 造成 Q fever，常與吸入受污染動物產物氣膠相關，不造成典型遊走性紅斑。",
      B: "錯誤。Leptospira interrogans 造成鉤端螺旋體病，可有發燒、結膜充血、肝腎症狀，不是 erythema migrans。",
      C: "錯誤。Rickettsia rickettsii 造成 Rocky Mountain spotted fever，皮疹型態與病媒不同。",
      D: "正確。Borrelia burgdorferi 是萊姆病病原，早期常見擴大的環狀遊走性紅斑。",
    },
    core: "Erythema migrans 直接連到 Lyme disease、Borrelia burgdorferi、Ixodes tick。",
    key: "遊走性紅斑是 Borrelia burgdorferi 感染的典型皮膚表現。",
    front: "erythema migrans / Lyme disease / Borrelia",
    back: "遊走性紅斑提示萊姆病，病原是 Borrelia burgdorferi，病媒是 Ixodes tick。",
    summary: "遊走性紅斑 -> Borrelia burgdorferi",
  },
  7: {
    stem: "題幹的免疫缺陷感染、生物膜、高度抗藥性、耐膽鹽與高鹽環境，指向 Enterococcus faecalis。腸球菌可造成院內感染，且能在 bile 與 6.5% NaCl 中生長，答案選 D。",
    options: {
      A: "錯誤。肺炎鏈球菌可造成肺炎、腦膜炎與菌血症，但不以耐膽鹽、高鹽及生物膜型院內感染為主要考點。",
      B: "錯誤。化膿鏈球菌造成咽炎、蜂窩性組織炎、壞死性筋膜炎等，沒有題幹所列腸球菌耐受特徵。",
      C: "錯誤。轉糖鏈球菌與齲齒、牙菌斑相關，但不是耐膽鹽與高鹽的典型答案。",
      D: "正確。糞腸球菌常見於免疫低下或住院病人，可形成生物膜並具有抗藥性，且耐膽鹽與高鹽環境。",
    },
    core: "Enterococcus 的辨識點是 bile esculin 陽性、可在 6.5% NaCl 生長、院內感染與抗藥性。",
    key: "Enterococcus faecalis 可耐膽鹽與高鹽，並常造成抗藥性院內感染。",
    front: "Enterococcus faecalis / biofilm / bile / 6.5% NaCl",
    back: "糞腸球菌可在膽鹽與高鹽環境生長，常見免疫低下或院內抗藥感染。",
    summary: "耐膽鹽高鹽 + 生物膜抗藥 -> Enterococcus faecalis",
  },
  8: {
    stem: "題目問無乳鏈球菌何者錯誤。Streptococcus agalactiae 是 Group B Streptococcus，CAMP 陽性，可定殖腸胃道與泌尿生殖道並造成新生兒腦膜炎、肺炎；說它屬 A 群是錯的，答案選 A。",
    options: {
      A: "正確。無乳鏈球菌是 B 群鏈球菌，不是 A 群；A 群代表多為 Streptococcus pyogenes。",
      B: "錯誤。CAMP test 陽性是 Group B Streptococcus 的經典實驗室特徵。",
      C: "錯誤。GBS 可無症狀定殖於腸胃道或女性生殖泌尿道，孕婦帶菌會增加新生兒感染風險。",
      D: "錯誤。GBS 是新生兒肺炎、敗血症與腦膜炎的重要病原。",
    },
    core: "Streptococcus agalactiae = Group B、CAMP positive、新生兒感染；Streptococcus pyogenes = Group A。",
    key: "無乳鏈球菌是 B 群鏈球菌，非 A 群。",
    front: "Streptococcus agalactiae / Group B / CAMP / neonate",
    back: "GBS 是 Streptococcus agalactiae，CAMP 陽性，可造成新生兒肺炎、敗血症、腦膜炎。",
    summary: "無乳鏈球菌 -> Group B Streptococcus",
  },
  9: {
    stem: "本題問 Legionella pneumophila 的錯誤敘述。Legionella 可存活於阿米巴原蟲內，培養需 L-cysteine 與 iron，治療用 macrolide 或 fluoroquinolone；宿主防禦主要靠細胞免疫，不是抗莢膜抗體，答案選 C。",
    options: {
      A: "錯誤。Legionella 在自然界常與水環境、阿米巴原蟲相關，能在原蟲內存活與增殖。",
      B: "錯誤。培養 Legionella 常用 BCYE agar，需要 L-cysteine 與 iron。",
      C: "正確。Legionella 是胞內病原，主要靠 T 細胞與巨噬細胞相關的細胞免疫控制；抗莢膜抗體不是主軸。",
      D: "錯誤。因為是胞內菌，治療常選可進入細胞的 macrolides 或 fluoroquinolones。",
    },
    core: "Legionella：水環境、阿米巴、BCYE agar 需 cysteine/iron、細胞免疫、macrolide/fluoroquinolone。",
    key: "Legionella 的免疫控制主要靠細胞免疫，不是抗莢膜抗體。",
    front: "Legionella / BCYE / L-cysteine / cell-mediated immunity",
    back: "Legionella 培養需 L-cysteine 與 iron，治療用 macrolide 或 fluoroquinolone，防禦重點是細胞免疫。",
    summary: "Legionella -> 胞內菌，靠細胞免疫",
  },
  10: {
    stem: "本題官方接受 B、C、D。第四型過敏反應屬細胞媒介免疫，病毒感染造成的免疫病理可由干擾素、發炎細胞與細胞激素參與；單純病毒抗體比較偏向中和或免疫複合體機轉，不是本題接受答案。",
    options: {
      A: "錯誤。病毒抗體可中和病毒或參與免疫複合體反應，但第四型過敏的核心不是抗體，而是 T 細胞與細胞激素造成的延遲型發炎。",
      B: "正確。干擾素是病毒感染時重要 cytokine，可參與細胞免疫活化與發炎反應，官方將其列為可接受答案。",
      C: "正確。多形核白血球可參與發炎組織傷害；雖不是第四型過敏的起始核心，官方答案將其併列接受。",
      D: "正確。細胞激素是第四型過敏與病毒免疫病理的重要媒介，例如活化巨噬細胞與招募發炎細胞。",
    },
    core: "第四型過敏是細胞媒介反應，重點在 T 細胞、cytokines 與發炎細胞；本題官方多重給分為 B、C、D。",
    key: "第四型過敏反應以細胞免疫與 cytokine-mediated inflammation 為主，本題官方接受 B、C、D。",
    front: "type IV hypersensitivity / viral immunopathogenesis / multiple correct",
    back: "第四型過敏不是抗體主導，而是 T 細胞、細胞激素與發炎細胞造成組織傷害；本題 B、C、D 皆給分。",
    summary: "病毒免疫病理 -> type IV 為細胞媒介，官方 BCD",
  },
  11: {
    stem: "HIV 主要感染帶有 CD4 且具 CCR5 或 CXCR4 coreceptor 的細胞，包括 CD4 T cell、macrophage 與 dendritic cell。嗜中性白血球不是主要感染對象，答案選 B。",
    options: {
      A: "錯誤。CD4 T 細胞是 HIV 最重要的感染與破壞對象，與後續免疫缺陷直接相關。",
      B: "正確。嗜中性白血球主要負責吞噬與急性發炎，並非 HIV 的主要感染宿主細胞。",
      C: "錯誤。巨噬細胞可表現 CD4 與 chemokine coreceptors，可被 HIV 感染並作為病毒儲存庫。",
      D: "錯誤。樹突細胞可參與 HIV 捕捉與傳播，也可成為感染相關細胞。",
    },
    core: "HIV 主要目標：CD4 T cells、macrophages、dendritic cells；不是 neutrophils。",
    key: "嗜中性白血球不是 HIV 主要感染對象。",
    front: "HIV target cells / CD4 / macrophage / dendritic cell",
    back: "HIV 主要感染 CD4 T 細胞、巨噬細胞與樹突細胞；嗜中性球不是主要宿主。",
    summary: "HIV 目標細胞 -> CD4 T、巨噬、樹突，不是嗜中性球",
  },
  12: {
    stem: "Baloxavir marboxil 抑制 influenza virus polymerase acidic protein 的 endonuclease 活性，阻斷 cap-snatching。題目選項 PB2、M2、HA、NA 都不是正確標的，因此官方全給分。",
    options: {
      A: "全給分。PB2 參與 cap binding，但 baloxavir 的藥理標的是 PA endonuclease，不是 PB2；因正確標的未列出，官方接受本題全部選項。",
      B: "全給分。M2 是 amantadine、rimantadine 的離子通道標的，不是 baloxavir；本題因缺少 PA endonuclease 選項而全給分。",
      C: "全給分。HA 負責病毒附著與膜融合，並非 baloxavir 的標的；官方全給分並不代表 HA 正確。",
      D: "全給分。NA 是 oseltamivir 等 neuraminidase inhibitors 的標的，不是 baloxavir；本題官方以全給分處理。",
    },
    core: "Baloxavir 抑制 PA endonuclease；M2 對 amantadine，NA 對 oseltamivir，HA 是附著/融合相關。本題因選項缺正答而全給分。",
    key: "Baloxavir 的標的是 influenza PA endonuclease，本題官方全給分。",
    front: "baloxavir / PA endonuclease / all credit",
    back: "Baloxavir 阻斷 PA endonuclease 的 cap-snatching；PB2、M2、HA、NA 都不是正確標的，所以本題全給分。",
    summary: "Baloxavir -> PA endonuclease；選項缺漏 -> 全給分",
  },
  13: {
    stem: "本題問疱疹病毒與疾病配對的錯誤項。HSV-1 可造成疱疹性腦炎，EBV 可造成 infectious mononucleosis，VZV 可再活化為帶狀疱疹；herpangina 多由 Coxsackie A virus 等 enterovirus 引起，不是 HHV-6，答案選 D。",
    options: {
      A: "錯誤。HSV-1 是成人散發性疱疹性腦炎的重要病原，常侵犯顳葉。",
      B: "錯誤。EBV 感染 B 細胞，可造成發燒、咽炎、淋巴結腫大的傳染性單核球增多症。",
      C: "錯誤。VZV 初感染造成水痘，潛伏於神經節後再活化可造成帶狀疱疹。",
      D: "正確。HHV-6 典型與玫瑰疹 roseola infantum 相關；herpangina 常由 Coxsackie A virus 引起。",
    },
    core: "HHV-6 記 roseola；herpangina 記 Coxsackie A。疱疹病毒配對題要分清 HSV、EBV、VZV、HHV-6。",
    key: "Herpangina 不是 HHV-6 的典型疾病，常見病原是 Coxsackie A virus。",
    front: "HHV-6 / roseola / herpangina / Coxsackie",
    back: "HHV-6 典型造成 roseola infantum；herpangina 多由 Coxsackie A 等 enterovirus 引起。",
    summary: "疱疹病毒配對 -> HHV-6 是 roseola，不是 herpangina",
  },
  14: {
    stem: "Ebola virus 是不穩定的 enveloped RNA virus，主要經血液、體液或接觸感染者分泌物傳播，不是以腸胃道為主要傳染途徑。它可感染內皮細胞與單核球，引發 cytokine storm、血管通透性增加與出血，答案選 A。",
    options: {
      A: "正確。Ebola 不是穩定且主要經腸胃道傳染的病毒；典型傳播是接觸感染者血液、體液或污染物。",
      B: "錯誤。Ebola 可感染單核球、巨噬細胞與內皮細胞等，快速複製並造成廣泛組織傷害。",
      C: "錯誤。嚴重 Ebola 感染可引發大量發炎介質釋放，造成 cytokine storm 與休克。",
      D: "錯誤。內皮受損與發炎反應會增加血管通透性，造成出血與血流動力學不穩。",
    },
    core: "Ebola 是 enveloped filovirus，傳播重點是體液接觸；重症機轉包括 cytokine storm、內皮傷害與出血。",
    key: "Ebola 主要經體液接觸傳播，不是穩定且以腸胃道為主的病毒。",
    front: "Ebola / body fluids / cytokine storm / hemorrhage",
    back: "Ebola 是 enveloped RNA virus，經血液體液傳播，可感染內皮與單核球並造成 cytokine storm、出血。",
    summary: "Ebola -> 體液接觸傳播，非腸胃道主傳染",
  },
  15: {
    stem: "登革病毒是有套膜的 Flavivirus，與 C 型肝炎病毒同屬 Flaviviridae。它可被乙醚或氯仿去活化，血球凝集抑制不適合精準區分四型，且臨床沒有特效抗登革病毒藥物，答案選 B。",
    options: {
      A: "錯誤。登革病毒有套膜，脂溶劑如乙醚或氯仿可破壞 envelope 而使病毒失活。",
      B: "正確。Dengue virus 與 hepatitis C virus 同屬 Flaviviridae，都是正股 RNA 病毒家族成員。",
      C: "錯誤。血球凝集抑制試驗有交叉反應，不能可靠區分四種登革病毒血清型；分型需靠更專一方法。",
      D: "錯誤。登革熱治療以支持療法為主，沒有常規可用的特效抗病毒藥物。",
    },
    core: "Dengue 是 enveloped Flavivirus；治療以支持療法為主，分型不能靠非專一的血球凝集抑制當作唯一依據。",
    key: "登革病毒與 HCV 同屬 Flaviviridae。",
    front: "dengue / Flaviviridae / envelope / supportive care",
    back: "登革病毒為有套膜 Flavivirus，可被脂溶劑去活化；與 HCV 同屬 Flaviviridae。",
    summary: "登革病毒 -> Flaviviridae，有套膜",
  },
  16: {
    stem: "題目問阻斷真菌 microtubule 的抗黴菌藥。Griseofulvin 會干擾微管與有絲分裂，常用於皮癬菌感染，答案選 B。",
    options: {
      A: "錯誤。Itraconazole 是 azole 類，抑制 ergosterol 合成，不是 microtubule 抑制劑。",
      B: "正確。Griseofulvin 會結合真菌微管蛋白，抑制有絲分裂紡錘體功能。",
      C: "錯誤。Nystatin 與 ergosterol 結合形成膜孔洞，常用於念珠菌局部感染。",
      D: "錯誤。Terbinafine 抑制 squalene epoxidase，使 ergosterol 合成受阻。",
    },
    core: "抗黴菌藥機轉：griseofulvin 抑制 microtubule；azoles、terbinafine 影響 ergosterol 合成；nystatin/amphotericin B 結合 ergosterol。",
    key: "Griseofulvin 阻斷真菌微小管與有絲分裂。",
    front: "griseofulvin / fungal microtubule / antifungal mechanisms",
    back: "Griseofulvin 抑制真菌微管；itraconazole 抑制 ergosterol 合成，nystatin 結合 ergosterol，terbinafine 抑制 squalene epoxidase。",
    summary: "抗黴菌機轉 -> griseofulvin 抑制 microtubule",
  },
  17: {
    stem: "Cryptococcus neoformans 可產生 phenol oxidase/laccase，在 niger seed agar 將 substrate 轉成 melanin，使菌落呈咖啡色，答案選 D。",
    options: {
      A: "錯誤。Buffered charcoal yeast extract agar 主要用於 Legionella 培養，不是 Cryptococcus 產棕色色素的鑑別培養基。",
      B: "錯誤。CHROMagar 可用於某些 Candida species 鑑別，但不是新型隱球菌咖啡色菌落的經典答案。",
      C: "錯誤。Cornmeal agar 常用於觀察 Candida 的型態如 chlamydospore，不是此題重點。",
      D: "正確。Niger seed agar 含 caffeic acid 類 substrate，Cryptococcus neoformans 產 melanin 後菌落呈棕黑色。",
    },
    core: "Cryptococcus neoformans：厚莢膜、India ink、urease positive、niger seed agar 棕黑色菌落。",
    key: "Cryptococcus neoformans 在 niger seed agar 可形成咖啡色/棕黑色菌落。",
    front: "Cryptococcus neoformans / niger seed agar / melanin",
    back: "新型隱球菌有 laccase，可在 niger seed agar 產生 melanin，菌落呈棕黑色。",
    summary: "Cryptococcus 鑑別 -> niger seed agar 棕黑色",
  },
  18: {
    stem: "題目問免疫系統消滅病原體的錯誤描述。NK cell 可辨識低 MHC I、stress ligands 或經 ADCC 殺細胞，但沒有像 TCR/BCR 那樣以抗原特異性受體直接辨識抗原，答案選 A。",
    options: {
      A: "正確。NK 細胞屬先天免疫，靠 activating/inhibitory receptors 與 missing-self 概念，不靠抗原特異性受體直接辨識抗原。",
      B: "錯誤。巨噬細胞吞噬細菌後，可在 phagolysosome 中以酵素與活性氧等方式殺菌。",
      C: "錯誤。補體活化可形成 membrane attack complex 或促進 opsonization，對細菌清除有重要作用。",
      D: "錯誤。中和抗體可阻斷病毒與細胞受體結合，防止病毒進入宿主細胞。",
    },
    core: "抗原特異性受體是 TCR/BCR 的特色；NK cell 屬先天免疫，靠 missing-self、stress ligand 與 ADCC。",
    key: "NK 細胞不以抗原特異性受體直接辨識抗原。",
    front: "NK cell / antigen-specific receptor / innate immunity",
    back: "NK cell 靠 missing-self、活化/抑制受體與 ADCC，不像 T/B 細胞用抗原特異性受體直接辨識抗原。",
    summary: "NK cell -> 先天免疫，不是 TCR/BCR 式抗原特異辨識",
  },
  19: {
    stem: "T follicular helper cells 協助 germinal center B cells 進行 class switching、somatic hypermutation 與 plasma cell 分化，主要分泌 IL-21，答案選 A。",
    options: {
      A: "正確。IL-21 是 TFH 細胞的重要 cytokine，可促進 B 細胞增生、分化與抗體反應成熟。",
      B: "錯誤。IL-22 常與 Th17/Th22 及上皮屏障反應相關，不是 TFH 的主要代表 cytokine。",
      C: "錯誤。IL-23 主要由抗原呈現細胞分泌，促進 Th17 維持與擴增。",
      D: "錯誤。IL-27 由抗原呈現細胞產生，參與 T 細胞分化調節，不是 TFH 的主要分泌物。",
    },
    core: "TFH 的重點是 B cell help、germinal center、IL-21、CD40L 與 class switching。",
    key: "TFH 細胞主要分泌 IL-21 以協助 B 細胞反應。",
    front: "TFH / IL-21 / germinal center",
    back: "濾泡輔助 T 細胞分泌 IL-21，協助 germinal center B cell 做 class switching、親和力成熟與分化。",
    summary: "TFH -> IL-21 -> B cell help",
  },
  20: {
    stem: "題目問腫瘤免疫互動最不適當敘述。CAR-T 通常取出病人自己的 T 細胞進行基因改造後回輸，而不是取健康人的 T 細胞直接改造打回癌症病人，答案選 C。",
    options: {
      A: "錯誤。免疫監視理論認為新生腫瘤細胞可被 T 細胞與 NK 細胞辨識並清除，雖然腫瘤也可能免疫逃脫。",
      B: "錯誤。Rituximab、trastuzumab 等單株抗體可透過補體活化、ADCC 或受體訊號阻斷發揮抗腫瘤作用。",
      C: "正確。CAR-T 多使用患者自體 T 細胞改造後回輸；若使用健康人異體 T 細胞，會涉及排斥與 graft-versus-host 風險，不是標準描述。",
      D: "錯誤。Checkpoint blockade 以 anti-CTLA-4、anti-PD-1/PD-L1 阻斷抑制訊號，使 T 細胞重新攻擊腫瘤。",
    },
    core: "CAR-T 的典型流程是取自體 T cell、基因改造表現 CAR、擴增後回輸；checkpoint blockade 是解除 T cell 抑制。",
    key: "CAR-T 療法典型使用病人自體 T 細胞，而不是健康人的 T 細胞。",
    front: "CAR-T / autologous T cell / checkpoint blockade",
    back: "CAR-T 通常取病人自己的 T cell 改造後回輸；checkpoint inhibitors 阻斷 CTLA-4 或 PD-1/PD-L1。",
    summary: "腫瘤免疫治療 -> CAR-T 多為自體 T 細胞",
  },
  21: {
    stem: "腫瘤細胞常表現 PD-L1，與 T 細胞上的 PD-1 結合後傳遞抑制訊號，使 T 細胞活性下降，達到 immune escape，答案選 B。",
    options: {
      A: "錯誤。CD28 是 T 細胞上的共刺激受體，與 B7 結合促進 T cell activation，不是腫瘤用來抑制免疫的典型配體。",
      B: "正確。PD-L1 可由腫瘤細胞表現，結合 PD-1 後抑制 T 細胞反應，是免疫檢查點治療的重要標的。",
      C: "錯誤。PD-1 主要是 T 細胞上的抑制性受體；題目問腫瘤細胞表現以抑制宿主免疫的分子，較精準是 PD-L1。",
      D: "錯誤。CTLA-4 是 T 細胞上的抑制性受體，會與 B7 競爭 CD28 訊號，不是腫瘤細胞表現的典型答案。",
    },
    core: "PD-1 在 T cell，PD-L1 常在 tumor/APC；PD-1/PD-L1 interaction 會抑制 T cell，anti-PD-1/PD-L1 可解除抑制。",
    key: "腫瘤細胞表現 PD-L1 可抑制 T 細胞免疫反應。",
    front: "PD-L1 / PD-1 / tumor immune escape",
    back: "腫瘤細胞表現 PD-L1，結合 T 細胞 PD-1 後抑制 T cell 活性，是 checkpoint blockade 的標的。",
    summary: "腫瘤免疫逃脫 -> tumor PD-L1 抑制 T cell PD-1",
  },
  22: {
    stem: "Opsonization 是病原體表面被 IgG 或 C3b 等調理素標記後，讓吞噬細胞更容易辨識與吞噬。吞噬細胞表面的 complement receptors 可辨識 C3b，答案選 B。",
    options: {
      A: "錯誤。Toll-like receptors 辨識 PAMPs 並啟動先天免疫訊號，但不是辨識已附著調理素的主要受體。",
      B: "正確。Complement receptors 可辨識附著在病菌表面的 C3b/iC3b，促進吞噬作用。",
      C: "錯誤。Lectin-like receptors 可辨識醣類結構，例如 mannose receptor，但不等同調理素受體。",
      D: "錯誤。Chemokine receptors 主要接收趨化訊號，引導白血球移動，不是辨識 opsonin 的受體。",
    },
    core: "調理作用常考 IgG Fc receptor 與 C3b complement receptor；C3b 是很高產的 opsonin。",
    key: "吞噬細胞的 complement receptors 可辨識 C3b 等補體調理素。",
    front: "opsonization / C3b / complement receptor",
    back: "調理作用靠 IgG 或 C3b 標記病原；吞噬細胞以 Fc receptor 或 complement receptor 辨識後吞噬。",
    summary: "Opsonization -> C3b + complement receptor",
  },
  23: {
    stem: "Ataxia-telangiectasia 由 ATM DNA repair defect 造成，對 DNA double-strand breaks 修復能力差。V(D)J recombination 需要產生並修復雙股斷裂，因此 B、T 細胞受體生成受影響，答案選 A。",
    options: {
      A: "正確。V(D)J recombination 需要 DNA 斷裂與修復；ATM 缺陷會影響淋巴球受體重組，導致免疫缺陷。",
      B: "錯誤。無法產生 IgM 不是 ataxia-telangiectasia 的主要機轉描述；它的根本問題是 DNA repair。",
      C: "錯誤。MHC class I 辨識缺陷會影響 CD8 T cell 相關反應，但不是本病 B、T 細胞數量減少的主因。",
      D: "錯誤。MHC class II 缺陷會造成 bare lymphocyte syndrome 類型免疫缺陷，不是 ataxia-telangiectasia。",
    },
    core: "Ataxia-telangiectasia = ATM mutation、DNA double-strand break repair defect、免疫缺陷、共濟失調、微血管擴張。",
    key: "Ataxia-telangiectasia 因 DNA 修復缺陷影響 V(D)J 重組。",
    front: "ataxia-telangiectasia / ATM / V(D)J recombination",
    back: "ATM 缺陷造成 DNA 雙股斷裂修復不良，會影響 V(D)J 重組與淋巴球發育。",
    summary: "A-T syndrome -> ATM DNA repair defect -> V(D)J 受影響",
  },
  24: {
    stem: "本題問免疫球蛋白基因重組何者錯誤。重鏈先 D-J 再 V-DJ、輕鏈先 κ 再 λ、allelic exclusion 都是正確概念；但 V(D)J junctional diversity 主要集中在 CDR3，不是 CDR1、CDR2、CDR3 都由 junction 造成最大歧異，答案選 C。",
    options: {
      A: "錯誤。B 細胞早期發育時，重鏈基因確實先做 D-J，再做 V-DJ 重組。",
      B: "錯誤。輕鏈通常先嘗試 κ chain V-J 重組，失敗後再嘗試 λ chain，這是輕鏈重組順序的典型考點。",
      C: "正確。V(D)J 接合處造成的 junctional diversity 主要影響 CDR3；CDR1、CDR2 多由 germline V segment 編碼，不是同樣由接合位置造成最大歧異。",
      D: "錯誤。成功重組後會抑制另一等位基因繼續重組，稱 allelic exclusion，使單一 B 細胞表現單一抗原特異性。",
    },
    core: "免疫球蛋白重組：heavy chain D-J -> V-DJ；light chain κ before λ；junctional diversity mainly CDR3；allelic exclusion 保持單一特異性。",
    key: "V(D)J 接合造成的最大歧異主要在 CDR3，不是 CDR1、CDR2、CDR3 全部。",
    front: "BCR rearrangement / CDR3 / allelic exclusion",
    back: "重鏈先 D-J 再 V-DJ；輕鏈先 κ 後 λ；junctional diversity 主要在 CDR3。",
    summary: "免疫球蛋白重組 -> 接合歧異主要 CDR3",
  },
  25: {
    stem: "本題資料疑似把第 25 題題幹與第 26 題 AID 題幹/選項黏在一起；目前選項實際上是 AID 相關敘述，且官方答案為 C。依現有選項解讀，AID 可促進 somatic hypermutation 與 IgE class switching；CSR 起於 AID 去胺化 cytosine 後的 DNA 修復與雙股斷裂。若把 C 當錯誤選項，可能與穩定免疫學概念不一致，需人工複核原始題目。",
    options: {
      A: "Germinal center 高表現這點合理；AID 進入活化 B 細胞後，讓免疫球蛋白可變區發生 somatic hypermutation。",
      B: "IgE 轉換屬 class switch recombination，需要 AID 啟動 switch region 的去胺化與後續修復。",
      C: "Cytosine 去胺成 uridine 正是 AID 的反應起點，後續 repair 才會造成雙股斷裂並完成 CSR；官方把 C 列為答案，需複核。",
      D: "RSS 是 V(D)J recombination 的訊號序列，不主導 class switch；若僅看 AID/CSR 選項，這句反而比較像錯誤敘述。",
    },
    core: "此題需回查官方原題：目前題幹前半問 Th 分化配對，但選項為 AID；且官方答案 C 與常規 AID/CSR 概念疑似衝突。先保留官方答案，不改題庫結構。",
    key: "第 25 題疑似題幹/選項錯置，官方答案 C 需人工複核。",
    front: "Q25 manual review / AID / CSR / RSS",
    back: "AID 參與 somatic hypermutation 與 class switch recombination；RSS 是 V(D)J recombination 訊號。第 25 題資料疑似混入下一題並需複核。",
    summary: "第25題 -> 題幹選項疑似錯置，AID/CSR 答案需人工複核",
    notes: ["題幹疑似混入第26題，且現有 AID 選項與官方答案 C 可能不一致；請對照原始試題人工複核。"],
  },
  26: {
    stem: "AID 會將 cytosine 去胺化成 uridine，啟動 DNA 修復，造成 somatic hypermutation 與 class switch recombination。RSS 是 V(D)J recombination 的訊號序列，不是 CSR 主導序列，所以答案選 D。",
    options: {
      A: "錯誤。AID 在 germinal center B cells 高表現，促進 somatic hypermutation，這是正確敘述。",
      B: "錯誤。IgE 類別轉換屬 class switch recombination，需要 AID 參與，因此這句正確。",
      C: "錯誤。CSR 的起始確實與 AID 將 cytosine 轉成 uridine、引發修復與 DNA 雙股斷裂有關。",
      D: "正確。RSS 是 V(D)J recombination 的 recombination signal sequence，不是 class switch recombination 的主導序列；CSR 主要發生在 switch regions。",
    },
    core: "AID 負責 SHM 與 CSR；RSS 屬 V(D)J recombination，switch regions 才是 CSR 的關鍵位置。",
    key: "Class switch recombination 不由 RSS 主導，AID 才是核心酵素。",
    front: "AID / class switch recombination / RSS",
    back: "AID 造成 cytosine deamination，促進 SHM 與 CSR；RSS 是 V(D)J 重組訊號，不是 CSR 訊號。",
    summary: "AID -> SHM/CSR；RSS -> V(D)J，不是 CSR",
  },
  27: {
    stem: "題目問去年得流感、今年仍可能再感染的原因。流感病毒抗原變異可使既有免疫保護不完全；此題官方答案選 C，指向 original antigenic sin 對後續變異株抗體反應的影響。",
    options: {
      A: "錯誤。流感病毒不會像 HSV/VZV 一樣潛伏在神經節後冬天再活化；反覆感染主要來自新暴露與抗原變異。",
      B: "錯誤。流感 RNA polymerase 易出錯可造成點突變，但點突變造成的是 antigenic drift，不是 antigenic shift；shift 是基因片段重組 reassortment。",
      C: "正確。Original antigenic sin 指免疫系統偏向喚起第一次感染株的記憶反應，可能使對新變異株的抗體反應不夠理想。",
      D: "錯誤。流感疫苗可降低感染與重症風險，但因抗原變異與疫苗株匹配度限制，不能保證完全不會罹患流感。",
    },
    core: "流感反覆感染要分 antigenic drift、antigenic shift 與 original antigenic sin；點突變是 drift，不是 shift。",
    key: "流感反覆感染與抗原變異、original antigenic sin 有關；點突變稱 antigenic drift。",
    front: "influenza reinfection / original antigenic sin / drift vs shift",
    back: "流感點突變是 antigenic drift；original antigenic sin 會讓免疫反應偏向舊株，疫苗也不能保證完全不感染。",
    summary: "流感再感染 -> 抗原變異與 original antigenic sin",
  },
  28: {
    stem: "氣喘與異位性皮膚炎屬典型 type 2 immune response，常見 Th2 cytokines 如 IL-4、IL-5、IL-13，以及 IgE 升高。IL-5 與嗜酸性球活化相關，IgE 參與第一型過敏反應，答案選 B。",
    options: {
      A: "錯誤。IL-5 符合 Th2 過敏反應，但 IgA 不是氣喘與異位性皮膚炎最典型升高的抗體類別。",
      B: "正確。Th2/IL-5 反應與嗜酸性球、過敏發炎相關，血清 IgE 升高也符合 atopic disease。",
      C: "錯誤。IFN-γ 是 Th1 代表 cytokine，IgA 主要與黏膜免疫相關，不是此類過敏病的典型組合。",
      D: "錯誤。IgE 正確，但 IFN-γ 偏 Th1 反應；氣喘、異位性皮膚炎更偏 Th2 cytokine profile。",
    },
    core: "Atopy/asthma/eczema 連到 Th2、IL-4/IL-5/IL-13、IgE、eosinophils。",
    key: "過敏性氣喘與異位性皮膚炎常見 Th2/IL-5 反應與 IgE 升高。",
    front: "atopy / asthma / IL-5 / IgE",
    back: "氣喘、異位性皮膚炎屬 Th2 型過敏反應，常有 IL-5、IL-4/13、IgE 與嗜酸性球增加。",
    summary: "過敏疾病 -> Th2/IL-5 + IgE",
  },
  29: {
    stem: "吃淡水魚生魚片後出現腹痛、眼眶附近浮腫，並取出約 4 mm 蟲體，典型指向 gnathostomiasis。有棘頜口線蟲幼蟲可由未熟淡水魚傳染並在皮下或眼部移行，答案選 B。",
    options: {
      A: "錯誤。Onchocerca volvulus 經黑蠅傳播，造成河盲症、皮下結節與眼病變，與淡水魚生食不符。",
      B: "正確。Gnathostoma spinigerum 常與食用未熟淡水魚、蛙、雞等有關，可造成移行性皮下腫脹或眼部寄生。",
      C: "錯誤。Thelazia callipaeda 是東方眼蟲，經果蠅類媒介傳播，通常寄生於結膜囊，不是吃淡水魚後腹痛加皮下移行的典型答案。",
      D: "錯誤。Dracunculus medinensis 經飲用含感染性劍水蚤的水傳播，成蟲常從下肢皮膚鑽出。",
    },
    core: "Gnathostoma 與未熟淡水魚/肉類、生食史、移行性皮下腫脹與眼部侵犯相關。",
    key: "食用淡水魚生魚片後移行性眼周腫脹，考 Gnathostoma spinigerum。",
    front: "Gnathostoma spinigerum / raw freshwater fish / migratory swelling",
    back: "有棘頜口線蟲可因食用未熟淡水魚感染，幼蟲移行造成皮下或眼部腫脹病灶。",
    summary: "淡水魚生食 + 眼周移行蟲體 -> Gnathostoma",
  },
  30: {
    stem: "題目問鞭蟲感染何者錯誤。Trichuris trichiura 成蟲寄生大腸，幼蟲在腸道發育，重度感染幼童可脫肛；它不像 Strongyloides stercoralis 會自體感染，答案選 C。",
    options: {
      A: "錯誤。人吞入感染性蟲卵後，幼蟲可在小腸孵化並於腸道內發育，之後成蟲主要定居大腸。",
      B: "錯誤。鞭蟲成蟲主要寄生於盲腸與大腸，前端插入黏膜吸附。",
      C: "正確。自體感染是糞小桿線蟲 Strongyloides 的重要特徵，不是鞭蟲的典型生活史。",
      D: "錯誤。幼童重度鞭蟲感染可造成慢性腹瀉、貧血、生長不良，甚至直腸脫垂。",
    },
    core: "Trichuris trichiura：感染性蟲卵入口、成蟲在大腸、重症可脫肛；autoinfection 記 Strongyloides。",
    key: "鞭蟲不會造成典型自體感染；自體感染要想到 Strongyloides。",
    front: "Trichuris trichiura / autoinfection / rectal prolapse",
    back: "鞭蟲成蟲寄生大腸，重度兒童感染可脫肛；自體感染是 Strongyloides 的特色。",
    summary: "鞭蟲 -> 大腸與脫肛；非自體感染",
  },
  31: {
    stem: "北歐、醃魚或淡水魚食用史，加上嚴重維生素 B12 缺乏與空腸近端帶狀蟲體，典型為廣節裂頭絛蟲 Diphyllobothrium latum，答案選 C。",
    options: {
      A: "錯誤。中華肝吸蟲與食用淡水魚有關，但主要寄生膽道，可造成膽管炎與膽管癌風險，不以 B12 缺乏為典型。",
      B: "錯誤。橫川吸蟲可因食用淡水魚感染並寄生小腸，但不是造成嚴重 B12 缺乏的代表寄生蟲。",
      C: "正確。Diphyllobothrium latum 又稱 fish tapeworm，常與北歐淡水魚相關，可競爭維生素 B12 造成巨幼紅血球性貧血。",
      D: "錯誤。Sparganum proliferum 是裂頭蚴病相關，常呈組織侵犯，不是空腸近端大型帶狀成蟲與 B12 缺乏的典型。",
    },
    core: "魚絛蟲 Diphyllobothrium latum 的高產線索是淡水魚、北方地區、空腸寄生與 vitamin B12 deficiency。",
    key: "Diphyllobothrium latum 可因魚類感染並造成維生素 B12 缺乏。",
    front: "Diphyllobothrium latum / fish tapeworm / B12 deficiency",
    back: "廣節裂頭絛蟲常由淡水魚傳染，寄生小腸，可造成維生素 B12 缺乏與巨幼紅血球性貧血。",
    summary: "北歐醃魚 + B12 缺乏 -> Diphyllobothrium latum",
  },
  32: {
    stem: "神經性囊尾幼蟲症 neurocysticercosis 最常由 Taenia solium 的蟲卵感染造成。人吞入豬肉絛蟲蟲卵後幼蟲可播散至中樞神經，答案選 C。",
    options: {
      A: "錯誤。旋毛蟲來自未熟豬肉或野味，幼蟲侵犯肌肉，造成肌痛、眼眶水腫，不是 neurocysticercosis。",
      B: "錯誤。牛肉絛蟲 Taenia saginata 通常造成腸道成蟲感染，不造成典型囊尾幼蟲症。",
      C: "正確。Taenia solium 蟲卵感染可造成 cysticercosis，侵犯腦部時即 neurocysticercosis，是癲癇的重要可預防原因。",
      D: "錯誤。亞洲無鉤絛蟲與腸道絛蟲感染相關，不是神經囊尾幼蟲症的主要病原。",
    },
    core: "Taenia solium 有兩種考法：吃未熟豬肉得腸道成蟲；吞入蟲卵得 cysticercosis/neurocysticercosis。",
    key: "Neurocysticercosis 最常由 Taenia solium 蟲卵感染造成。",
    front: "Taenia solium / neurocysticercosis / eggs",
    back: "豬肉絛蟲蟲卵感染可形成囊尾幼蟲症，侵犯腦部造成 neurocysticercosis。",
    summary: "神經囊尾幼蟲症 -> Taenia solium",
  },
  33: {
    stem: "瘧疾週期性發燒與紅血球內裂殖體同步破裂、merozoites 與代謝產物釋放有關。P. vivax 通常 48 小時週期，但不同族群不同步可讓發燒不規則；官方答案選 C。",
    options: {
      A: "錯誤。紅血球破裂時釋放 merozoites 與代謝產物，正是發燒週期的核心機轉之一，不是錯誤敘述。",
      B: "錯誤。許多非 falciparum 感染紅血球階段較同步，因此發燒較有規律；falciparum 常較不規則。",
      C: "正確。P. vivax 多為 48 小時 tertian fever；若有不同 sub-populations 感染，裂殖不同步，可造成不規則發燒。",
      D: "錯誤。P. malariae 潛伏期通常較長，且典型為 72 小時 quartan fever；說它比 P. vivax 潛伏期短並不恰當。",
    },
    core: "瘧疾發燒週期來自 RBC schizont rupture；vivax/ovale 約 48 小時，malariae 約 72 小時，falciparum 可不規則。",
    key: "P. vivax 通常 48 小時發燒週期，但不同族群不同步可造成不規則發燒。",
    front: "malaria fever periodicity / P. vivax / RBC rupture",
    back: "瘧疾週期性發燒來自紅血球內裂殖體同步破裂；P. vivax 常 48 小時，P. malariae 常 72 小時。",
    summary: "瘧疾發燒週期 -> RBC 破裂；vivax 48 小時",
  },
  34: {
    stem: "Leishmania donovani 造成內臟利什曼病 kala-azar，可有發燒、體重減輕、貧血、肝脾腫大與腹瀉。Blackwater fever 是嚴重瘧疾相關血紅素尿，不是杜氏利什曼原蟲典型表現，答案選 C。",
    options: {
      A: "錯誤。內臟利什曼病可出現腸胃症狀，包括腹瀉，並非完全無關。",
      B: "錯誤。骨髓與單核吞噬系統受侵犯可造成貧血、白血球低下與血小板低下。",
      C: "正確。Blackwater fever 典型與 falciparum malaria 嚴重溶血及血紅素尿相關，不是 Leishmania donovani 的代表病症。",
      D: "錯誤。肝脾腫大是 kala-azar 的典型臨床表現之一。",
    },
    core: "Leishmania donovani = visceral leishmaniasis/kala-azar、肝脾腫大、貧血；blackwater fever 記 falciparum malaria。",
    key: "Blackwater fever 與嚴重瘧疾較相關，不是 Leishmania donovani 典型病症。",
    front: "Leishmania donovani / kala-azar / blackwater fever",
    back: "杜氏利什曼原蟲造成內臟利什曼病，有貧血與肝脾腫大；blackwater fever 是嚴重瘧疾相關。",
    summary: "Leishmania donovani -> kala-azar；非 blackwater fever",
  },
  35: {
    stem: "鼠疫由 Yersinia pestis 引起，鼠蚤吸血後前胃被菌塊阻塞，反覆吸血時會反流/嘔吐含菌血液到叮咬處，造成感染。若題目問錯誤，官方選 C 可能需依原文細節判讀；目前仍保留官方答案並說明常規機轉。",
    options: {
      A: "錯誤。人類腺鼠疫常出現引流淋巴結疼痛腫大，若叮咬部位在上肢可見腋窩 buboes。",
      B: "錯誤。鼠疫可進展為肺鼠疫，肺鼠疫可經飛沫人傳人，是公共衛生重點。",
      C: "正確。經典機轉常描述為被阻塞鼠蚤 regurgitation/反流帶菌內容物；若選項用「嘔吐作用污染叮咬傷口」可能是對此機轉的簡化，但官方列為錯誤，需注意命題用語。",
      D: "錯誤。Yersinia pestis 是革蘭陰性桿菌，為鼠疫主要致病菌。",
    },
    core: "鼠疫：Yersinia pestis、鼠蚤、腺鼠疫 bubo、肺鼠疫可人傳人。此題 C 的中文用語與經典 regurgitation 機轉接近，建議考前對照官方解析。",
    key: "鼠疫由 Yersinia pestis 經鼠蚤傳播，可造成腺鼠疫與肺鼠疫；第35題 C 用語需留意官方判讀。",
    front: "plague / Yersinia pestis / flea / regurgitation",
    back: "鼠疫由 Y. pestis 引起，鼠蚤傳播；肺鼠疫可人傳人。C 選項與經典反流機轉接近，但官方列錯誤，宜複核用語。",
    summary: "鼠疫 -> Y. pestis + 鼠蚤；C 選項用語需留意",
    notes: ["C 選項描述與鼠蚤反流傳播機轉相近，但官方答案列 C；建議人工複核原題文字與官方說明。"],
  },
  36: {
    stem: "一因子 ANOVA 比較三組平均數時，基本假設包含各組獨立、各母體近似常態、變異數同質。最恰當敘述為三組母體變異數皆相等，答案選 A。",
    options: {
      A: "正確。ANOVA 的重要前提之一是 homogeneity of variance，也就是各組母體變異數相等或近似相等。",
      B: "錯誤。三組兩兩比較共有 3 次，不是 6 次；而且以多個 t 檢定取代 ANOVA 會增加 family-wise type I error，需做適當校正。",
      C: "錯誤。ANOVA 的檢定統計量服從 F distribution，不是 t distribution。",
      D: "錯誤。若以迴歸處理三組類別變項，應使用 dummy variables；直接用 1、2、3 當連續數值會假設線性趨勢，並不等同一般三組比較。",
    },
    core: "ANOVA 考點：F test、組間/組內變異、常態與等變異假設；類別組別做迴歸要用 dummy variables。",
    key: "三組 ANOVA 的前提之一是各組母體變異數相等。",
    front: "ANOVA / equal variance / F distribution",
    back: "ANOVA 比較三組平均數需假設等變異，檢定統計量為 F；類別組別不能隨便用 1、2、3 當連續變項。",
    summary: "ANOVA -> 等變異假設 + F 分配",
  },
  37: {
    stem: "簡單線性迴歸用一個自變項 X 解釋依變項 Y 的線性關係，但觀察性迴歸本身不能直接證明因果關係。因此最不恰當的是把線性關係說成線性因果關係，答案選 C。",
    options: {
      A: "錯誤。簡單線性迴歸確實是在評估 X 與 Y 是否呈線性關係。",
      B: "錯誤。在標準線性迴歸假設中，更精準是殘差在各 X 下近似常態；考題常簡化為 Y 在給定 X 下近似常態。",
      C: "正確。迴歸可顯示關聯與預測，不代表一定有因果；因果推論需要時序、混雜控制與研究設計支持。",
      D: "錯誤。Simple linear regression 只有一個 independent variable；多個自變項才是 multiple regression。",
    },
    core: "迴歸關係不等於因果關係。Simple linear regression 是一個 X，一個 Y，重點看線性關聯與殘差假設。",
    key: "簡單線性迴歸不能單憑模型結果宣稱線性因果關係。",
    front: "simple linear regression / association vs causation",
    back: "簡單線性迴歸評估一個 X 與 Y 的線性關聯；迴歸結果本身不能證明因果。",
    summary: "線性迴歸 -> 關聯/預測，不直接等於因果",
  },
  38: {
    stem: "女性體脂率越高、乳癌風險越高，呈現暴露程度增加時疾病風險也增加，符合因果判斷中的 dose-response effect，答案選 C。",
    options: {
      A: "錯誤。Specificity 指某暴露較特異地導致某結果，但體脂率與乳癌風險的描述不是在強調一對一特異性。",
      B: "錯誤。Temporality 強調暴露必須早於疾病發生；題幹沒有描述時間先後。",
      C: "正確。體脂率越高風險越高，正是劑量反應關係或生物梯度的概念。",
      D: "錯誤。Biologic plausibility 指有合理生物機制支持；題幹沒有描述雌激素、脂肪組織等機制，而是在說風險隨劑量上升。",
    },
    core: "Bradford Hill 因果準則中，暴露越多風險越高就是 dose-response effect；暴露先於疾病才是 temporality。",
    key: "體脂率越高乳癌風險越高，屬劑量效應。",
    front: "causal inference / dose-response effect / Bradford Hill",
    back: "暴露程度增加，疾病風險隨之上升，稱 dose-response effect 或 biological gradient。",
    summary: "因果判斷 -> 暴露越高風險越高 = dose-response",
  },
  39: {
    stem: "病例致死率 case-fatality rate 是死亡病例數除以已確診病例數。題幹中 621 人確診、2 人死亡，因此病例致死率為 2/621，答案選 B。",
    options: {
      A: "錯誤。2/24 是死亡數除以重症數，較接近重症個案中的死亡比例，不是全部確診病例的 case-fatality。",
      B: "正確。Case-fatality rate 的分母是病例數；本題病例數為 621，死亡數為 2。",
      C: "錯誤。2/3711 是死亡數除以所有船上旅客與船員，較像整個受檢疫群體的死亡比例，不是病例致死率。",
      D: "錯誤。2/(621-2) 把死亡者從病例分母中扣除，會低估定義上的病例總數。",
    },
    core: "Case-fatality = deaths among cases / total cases。不要把分母拿成總暴露人口或重症人口。",
    key: "病例致死率為死亡病例數除以確診病例數。",
    front: "case-fatality rate / deaths / confirmed cases",
    back: "病例致死率 = 死亡數 / 確診病例數；本題為 2/621。",
    summary: "病例致死率 -> 2 deaths / 621 cases",
  },
  40: {
    stem: "全球暖化可改變病媒與病原分布、降雨型態，且高溫會促進光化學反應，使臭氧等二次污染物濃度上升並增加心肺疾病風險。說高溫下二次空氣污染物濃度不會增加最不恰當，答案選 B。",
    options: {
      A: "錯誤。溫度、濕度與降雨改變會影響蚊媒、蜱媒及病原生態，進而改變傳染病風險。",
      B: "正確。高溫與日照常促進光化學反應，使臭氧等二次污染物增加；說濃度不會增加不恰當。",
      C: "錯誤。氣候變遷可改變降雨總量、季節分布與極端降雨事件。",
      D: "錯誤。二次污染物如臭氧升高，可能增加氣喘、慢性肺病與心血管事件風險。",
    },
    core: "氣候變遷公共衛生衝擊包括病媒分布、極端天氣、空污加劇與心肺疾病風險增加。",
    key: "高溫可促進二次空氣污染物形成，不是濃度不會增加。",
    front: "climate change / secondary air pollutants / ozone",
    back: "高溫與日照可促進光化學反應，讓臭氧等二次污染物增加，並提高心肺疾病風險。",
    summary: "氣候變遷 -> 高溫可增加二次空污",
  },
  41: {
    stem: "UV-C 能量最大但大多被臭氧層吸收，通常無法大量到達地表；對室外地表生物主要造成傷害的是 UV-B 與 UV-A，尤其 UV-B 與皮膚癌相關。因此 A 最不恰當。",
    options: {
      A: "正確。UV-C 雖能量最高，但幾乎被大氣臭氧吸收，不能說它對地表生物傷害最大。",
      B: "錯誤。UV-A 波長最長、能量較低，可穿透較深並到達地表最多。",
      C: "錯誤。UV-B 可造成 DNA damage，過度暴露會增加皮膚癌風險。",
      D: "錯誤。臭氧層稀薄會讓更多 UV 進入低層大氣，促進光化學反應並影響對流層臭氧形成。",
    },
    core: "紫外線能量 UV-C > UV-B > UV-A；但到達地表量 UV-A 最多，UV-C 多被臭氧層擋住。",
    key: "UV-C 能量最大但多被臭氧層吸收，非地表主要紫外線傷害來源。",
    front: "UV-A UV-B UV-C / ozone layer / skin cancer",
    back: "UV-A 波長最長且到地表最多；UV-B 與皮膚癌相關；UV-C 能量高但多被臭氧吸收。",
    summary: "UV 題 -> UV-C 能量高但不到地表",
  },
  42: {
    stem: "職業毒性物質進入人體最常見途徑是吸入、皮膚吸收與食入。Infiltration 不是職業暴露中常用的主要進入途徑分類，答案選 D。",
    options: {
      A: "錯誤。吸入是職場氣體、蒸氣、粉塵、煙霧暴露最重要且常見的途徑之一。",
      B: "錯誤。許多脂溶性化學物、農藥與溶劑可經皮膚吸收進入人體。",
      C: "錯誤。食入雖常因手口接觸或污染食物而發生，仍是職業衛生會列入的暴露途徑。",
      D: "正確。滲入不是典型職業毒物進入人體的主要分類；若指注射或傷口進入，也遠少於吸入與皮膚吸收。",
    },
    core: "職業毒物暴露途徑記 inhalation、skin absorption、ingestion；少數才是針扎/傷口進入。",
    key: "職業毒物最常見進入途徑為吸入與皮膚吸收；infiltration 不常見。",
    front: "occupational toxic exposure / inhalation / skin absorption",
    back: "職業毒物主要經吸入、皮膚吸收、食入進入人體；infiltration 不是常見分類。",
    summary: "職業暴露途徑 -> 吸入、皮膚、食入",
  },
  43: {
    stem: "PM2.5 的名稱即代表 aerodynamic diameter 小於或等於 2.5 micrometers 的細懸浮微粒，因此答案選 A。",
    options: {
      A: "正確。PM2.5 指粒徑約小於 2.5 微米的空氣微粒，可深入細支氣管與肺泡。",
      B: "錯誤。2.5 奈米太小，不是 PM2.5 定義的單位。",
      C: "錯誤。2.5 公分是肉眼可見尺度，完全不符合懸浮微粒定義。",
      D: "錯誤。2.5 公釐也遠大於細懸浮微粒，不是 PM2.5。",
    },
    core: "PM2.5 = particulate matter with diameter <= 2.5 micrometers；單位是微米，不是奈米、毫米或公分。",
    key: "PM2.5 指粒徑小於 2.5 微米的細懸浮微粒。",
    front: "PM2.5 / 2.5 micrometers",
    back: "PM2.5 是粒徑小於或等於 2.5 微米的細懸浮微粒。",
    summary: "PM2.5 -> 2.5 微米",
  },
  44: {
    stem: "社會資本與集體效能強調社區層次的人際互信、社會凝聚與非正式社會控制。居民個人知識屬個人層次因素，不是此理論的核心社會環境概念，答案選 B。",
    options: {
      A: "錯誤。非正式社會控制是集體效能的重要構面，指社區成員共同維持秩序與互相監督的能力。",
      B: "正確。居民個人知識偏向個體教育或認知，不是社會資本/集體效能理論的群體層次核心構面。",
      C: "錯誤。社會凝聚力是社會資本的重要元素，代表社群連結與共同感。",
      D: "錯誤。人們互信程度是社會資本的典型構成，會影響群體合作與健康。",
    },
    core: "社會資本是群體關係資源：trust、social cohesion、reciprocity；集體效能加上 informal social control。",
    key: "社會資本/集體效能重點在群體互信、凝聚與非正式社會控制，不是個人知識。",
    front: "social capital / collective efficacy / individual knowledge",
    back: "社會資本包含互信與社會凝聚；集體效能包含非正式社會控制。個人知識不是核心社會資本構面。",
    summary: "社會資本 -> 群體互信凝聚，不是個人知識",
  },
  45: {
    stem: "社會經濟改善與教育提升通常會提高健康識能、壽命與對醫療保健服務品質的期待，不會讓醫療需求單純降低。人口老化與社會異質性也會增加醫療與公衛需求，答案選 A。",
    options: {
      A: "正確。教育與所得提升通常使民眾更重視預防、篩檢與醫療品質，醫療保健需求不一定降低，說法過度簡化。",
      B: "錯誤。人口老化會增加慢性病、長照、復健與醫療照護需求。",
      C: "錯誤。地區社經差異擴大會讓健康不平等與衛生問題更複雜。",
      D: "錯誤。婦女就業率提高時，兒童照護與預防保健確實更常需要學校、托育與社區系統配合。",
    },
    core: "社會變遷常使公共衛生需求更複雜：老化、社經差異、家庭結構改變與服務期待提高。",
    key: "教育與所得提升不代表醫療保健服務需求降低。",
    front: "social change / health care demand / aging",
    back: "人口老化與社會經濟變遷常增加醫療保健需求與複雜度；教育所得提升不等於需求降低。",
    summary: "社會變遷 -> 醫療需求更複雜，不是降低",
  },
  46: {
    stem: "藥物濫用預防不能只靠單純知識傳遞或情感性教育；有效介入通常需要生活技能、同儕/家庭/社區策略與持續支持。社會控制、藥物治療與減害策略皆為常見概念，答案選 A。",
    options: {
      A: "正確。單獨講授知識或情感訴求效果有限，不能說只靠這些就能有效延遲或降低青少年非法藥物使用。",
      B: "錯誤。司法體系、藥檢與反毒政策都屬社會控制或結構層面的預防管道。",
      C: "錯誤。物質使用疾患可用替代療法、拮抗劑或厭惡療法等藥物策略，例如 methadone、naltrexone、disulfiram。",
      D: "錯誤。提供乾淨針具屬 harm reduction，可降低 HIV、HCV 等血液傳染與其他傷害。",
    },
    core: "藥物濫用預防要分需求降低、供給控制、治療與 harm reduction；單純知識宣導效果有限。",
    key: "青少年藥物濫用預防不能只靠單純知識或情感教育。",
    front: "substance abuse prevention / harm reduction / education",
    back: "有效藥物濫用預防需多層次介入；乾淨針具是減害，methadone/naltrexone 是治療策略。",
    summary: "藥物濫用預防 -> 單純宣導不足",
  },
  47: {
    stem: "物質使用疾患的自然史起點通常是暴露與使用，而非已經進入濫用或依賴才開始。降低暴露與可近性可預防，診斷需看長期型態，答案選 A。",
    options: {
      A: "正確。自然史的起始應從物質暴露、初次使用與風險因子開始；濫用或依賴已是發展後段。",
      B: "錯誤。降低物質暴露機會與可近性可降低使用與後續疾患風險。",
      C: "錯誤。過量等傷害可藉由降低可近性、改變使用情境或治療介入降低風險。",
      D: "錯誤。物質使用疾患診斷看一段時間內的失控使用、功能損害與持續使用模式，不以單次使用判定。",
    },
    core: "物質使用疾患自然史：暴露/初用 -> 規律使用 -> 問題使用 -> 疾患與傷害；預防可在前端降低暴露與可近性。",
    key: "物質使用疾患自然史起點不是濫用或依賴，而是暴露與初次使用。",
    front: "substance use natural history / exposure / dependence",
    back: "物質使用疾患從暴露與初次使用開始發展，濫用或依賴不是自然史起點。",
    summary: "物質使用自然史 -> 起點是暴露/初用",
  },
  48: {
    stem: "一般稅、社會保險費、指定用途稅都具有某種風險分攤與所得重分配功能。醫療儲蓄帳戶較偏個人帳戶累積與自我支付，社會互助與所得重分配最小，答案選 D。",
    options: {
      A: "錯誤。一般稅可透過累進稅制與公共支出達到較強的所得重分配與社會互助。",
      B: "錯誤。社會保險費透過共同基金與風險分攤，仍具社會互助性。",
      C: "錯誤。指定用途稅雖有特定用途限制，但仍可由社會共同籌資並支持公共服務。",
      D: "正確。醫療儲蓄帳戶多與個人累積、個人支出連動，對高低所得間重分配與社會互助效果較小。",
    },
    core: "財源制度重分配強度通常是稅收/社會保險較高，個人醫療儲蓄帳戶較低。",
    key: "醫療儲蓄帳戶的所得重分配與社會互助作用最小。",
    front: "health financing / medical saving account / redistribution",
    back: "醫療儲蓄帳戶偏個人自我儲蓄支付，風險分攤與所得重分配較弱。",
    summary: "醫療財源制度 -> MSA 重分配最小",
  },
  49: {
    stem: "本題官方全給分，代表四個選項都被接受。醫院市場行為常可用不同目標函數解釋，包括利潤、效用、服務量或價值等模型；既然官方 correct_answers 為 A、B、C、D，作答時以全給分狀態記憶即可。",
    options: {
      A: "全給分。價值極大化也可被視為解釋醫院行為的模型之一；官方未排除此選項。",
      B: "全給分。利潤極大化是市場行為常見模型，尤其用於營利組織分析；官方也給分。",
      C: "全給分。效用極大化常用來描述非營利醫院或管理者目標，官方也接受。",
      D: "全給分。服務量極大化亦可作為醫院行為模型之一；本題官方採全給分處理。",
    },
    core: "遇到官方全給分題，不要硬把四個選項分出唯一錯誤；詳解重點是說明全給分原因與各模型可能成立的語境。",
    key: "第 49 題官方全給分，四個醫院市場行為模型選項皆接受。",
    front: "hospital market behavior / all credit",
    back: "醫院行為可用利潤、效用、服務量、價值等模型解釋；本題官方全給分。",
    summary: "醫院市場行為模型 -> 官方全給分",
  },
  50: {
    stem: "基本 ADLs 包括洗澡、穿衣、如廁、移位、大小便控制與進食。洗衣屬 instrumental ADLs，需較高層次生活功能，不是基本 ADLs，答案選 C。",
    options: {
      A: "錯誤。洗澡是 Katz ADL 等量表常列的基本日常生活活動。",
      B: "錯誤。穿衣是基本 ADL 項目之一，用來評估個人自理能力。",
      C: "正確。洗衣屬 IADL，例如做家事、購物、理財、交通與用藥管理，不屬基本 ADL。",
      D: "錯誤。進食是基本 ADL 的核心項目之一。",
    },
    core: "ADL 是基本自理；IADL 是較複雜的工具性活動。洗衣、購物、煮飯、理財通常歸 IADL。",
    key: "洗衣屬 IADL，不是基本 ADL。",
    front: "ADL / IADL / laundry",
    back: "ADL 包括洗澡、穿衣、進食等基本自理；洗衣是 IADL。",
    summary: "ADL vs IADL -> 洗衣是 IADL",
  },
  51: {
    stem: "Thiopental 是 barbiturate 類靜脈全身麻醉劑，脂溶性高、起效快，但因迅速再分布到肌肉與脂肪，單次給藥作用時間短。答案選 B。",
    options: {
      A: "再分布會讓單次給藥迅速退效，而非延長成長效麻醉；長效說法方向相反。",
      B: "脂溶性高使藥物很快通過血腦障壁，靜脈給藥後可快速誘導麻醉。",
      C: "低脂溶性不對；thiopental 恰好因脂溶性高才有快速中樞作用，臨床以靜脈誘導為主。",
      D: "肝代謝不是快速產生活性代謝物；本題短效重點是從腦部再分布到周邊組織。",
    },
    core: "Thiopental：barbiturate、脂溶性高、rapid onset、short duration due to redistribution。",
    key: "Thiopental 是速效型靜脈麻醉藥，單次作用短來自再分布。",
    front: "thiopental / rapid onset / redistribution",
    back: "Thiopental 脂溶性高、起效快，單次作用因再分布而短暫。",
    summary: "Thiopental -> rapid onset，redistribution 終止作用",
  },
  52: {
    stem: "慢性 paraquat 暴露與氧化壓力、多巴胺神經元傷害相關，流行病學上與 Parkinson disease 風險增加最相關，答案選 A。",
    options: {
      A: "正確。Paraquat 結構與 MPP+ 類似，可造成氧化壓力，常被拿來連結帕金森氏症風險。",
      B: "錯誤。阿茲海默症以 amyloid beta、tau 與認知退化為主，和 paraquat 的經典毒理關聯不如 Parkinson disease。",
      C: "錯誤。ALS 與運動神經元退化相關，但 paraquat 題目的標準連結是 Parkinsonism。",
      D: "錯誤。亨丁頓舞蹈症是 CAG repeat 擴增造成的遺傳性基底核疾病，不是 paraquat 慢性暴露的典型後果。",
    },
    core: "Paraquat/農藥暴露常考 Parkinson disease，機轉與 oxidative stress、dopaminergic neuron injury 有關。",
    key: "長期 paraquat 暴露最常與帕金森氏症相關。",
    front: "paraquat / Parkinson disease / oxidative stress",
    back: "慢性 paraquat 暴露與氧化壓力、多巴胺神經元傷害相關，和 Parkinson disease 風險最相關。",
    summary: "Paraquat 暴露 -> Parkinson disease",
  },
  53: {
    stem: "Canakinumab 阻斷 IL-1β，tocilizumab 阻斷 IL-6 receptor，ustekinumab 阻斷 IL-12/23 p40；etanercept 是可溶性 TNF receptor fusion protein，阻斷 TNF-α，不是 interleukin，答案選 B。",
    options: {
      A: "錯誤。Canakinumab 是 anti-IL-1β monoclonal antibody，作用於 interleukin pathway。",
      B: "正確。Etanercept 結合並中和 TNF-α，屬 TNF inhibitor，不是阻斷 interleukin 功能。",
      C: "錯誤。Tocilizumab 阻斷 IL-6 receptor，屬抗 interleukin 訊號藥物。",
      D: "錯誤。Ustekinumab 阻斷 IL-12/IL-23 共用 p40 subunit，仍是 interleukin 相關。",
    },
    core: "生物製劑配對：canakinumab-IL-1β、tocilizumab-IL-6R、ustekinumab-IL-12/23、etanercept-TNF。",
    key: "Etanercept 阻斷 TNF，不是 interleukin。",
    front: "etanercept / TNF / interleukin blockers",
    back: "Canakinumab 抗 IL-1β，tocilizumab 抗 IL-6R，ustekinumab 抗 IL-12/23；etanercept 是 TNF inhibitor。",
    summary: "抗發炎生物製劑 -> etanercept 阻斷 TNF",
  },
  54: {
    stem: "Vancomycin 抗藥常來自 D-Ala-D-Ala 改成 D-Ala-D-Lac，使藥物失去結合力。Telavancin 可對部分 vancomycin-resistant 或耐受革蘭陽性菌有作用；dalbavancin 對 VRE 尤其 VanA 型 enterococci 通常效果不足，因此 D 錯。",
    options: {
      A: "錯誤。Vancomycin 抗藥的核心是細胞壁前驅物標的改變，導致與 peptidoglycan precursor 結合能力下降。",
      B: "錯誤。對 penicillin 抗藥肺炎鏈球菌嚴重感染，可用 vancomycin 搭配第三代 cephalosporin 如 cefotaxime/ceftriaxone。",
      C: "錯誤。Telavancin 是 lipoglycopeptide，對多種革蘭陽性菌有效，可涵蓋部分 vancomycin-resistant 或耐受情境，依題目語境為可接受敘述。",
      D: "正確。Dalbavancin 對 vancomycin-resistant enterococci，特別 VanA 型，並非可靠治療選擇；不能概括說可治療 VRE。",
    },
    core: "Vancomycin 抗藥：D-Ala-D-Ala -> D-Ala-D-Lac；VRE 治療不能把 dalbavancin 當標準答案，常需依菌種與 VanA/VanB 判斷。",
    key: "Dalbavancin 不是治療 vancomycin-resistant enterococci 的可靠標準選擇。",
    front: "vancomycin resistance / D-Ala-D-Lac / dalbavancin",
    back: "Vancomycin 抗藥因標的改變而失去結合；dalbavancin 對 VRE 尤其 VanA 型不可靠。",
    summary: "Vancomycin 抗藥 -> D-Ala-D-Lac；dalbavancin 非 VRE 標準",
  },
  55: {
    stem: "Busulfan 是 alkylating agent，作用於 DNA，常用於骨髓移植前 conditioning 或慢性骨髓性疾病相關情境，不是常用乳癌治療藥。抗藥性可與 glutathione S-transferase 增加相關，常見副作用包含腸胃不適，答案選 B。",
    options: {
      A: "錯誤。Busulfan 可烷化 DNA，造成交聯與細胞毒性，抑制癌細胞增生。",
      B: "正確。Busulfan 與 cyclophosphamide 都屬 alkylating agents，但 busulfan 不是乳癌常用治療藥；cyclophosphamide 才常見於乳癌方案。",
      C: "錯誤。Glutathione S-transferase 可增加藥物解毒與清除，可能造成 busulfan 抗藥或暴露量改變。",
      D: "錯誤。噁心、嘔吐是許多烷化劑常見副作用，busulfan 也可出現腸胃不適。",
    },
    core: "Busulfan 是 DNA alkylating agent，常記骨髓抑制/移植 conditioning；不要把它當乳癌常用藥。",
    key: "Busulfan 屬烷化劑，但不是常用於治療乳癌的代表藥。",
    front: "busulfan / alkylating agent / breast cancer",
    back: "Busulfan 烷化 DNA，常用於骨髓移植 conditioning；不是乳癌常用治療藥。",
    summary: "Busulfan -> alkylating agent，非乳癌常用",
  },
  56: {
    stem: "Trimethoprim 對細菌 dihydrofolate reductase 具有較高選擇性，常與 sulfamethoxazole 合用。Pyrimethamine 和 methotrexate 也抑制 DHFR，但分別偏寄生蟲與哺乳類/腫瘤細胞用途，答案選 B。",
    options: {
      A: "錯誤。Sulfamethoxazole 抑制 dihydropteroate synthase，阻斷 PABA 進入葉酸合成，不是 DHFR。",
      B: "正確。Trimethoprim 選擇性抑制細菌 DHFR，使 tetrahydrofolate 合成下降。",
      C: "錯誤。Pyrimethamine 抑制原蟲 DHFR，常用於 toxoplasmosis 或 malaria 相關治療，不是對細菌 DHFR 最具專一性的選項。",
      D: "錯誤。Methotrexate 抑制人類 DHFR，用於癌症、自體免疫疾病與異位妊娠等，不是細菌選擇性最高。",
    },
    core: "TMP-SMX：SMX 抑制 dihydropteroate synthase，TMP 抑制 bacterial DHFR。",
    key: "Trimethoprim 選擇性抑制細菌 DHFR。",
    front: "trimethoprim / bacterial DHFR / TMP-SMX",
    back: "Sulfamethoxazole 抑制 dihydropteroate synthase；trimethoprim 抑制細菌 DHFR。",
    summary: "葉酸代謝藥 -> TMP 抑制細菌 DHFR",
  },
  57: {
    stem: "Diphenhydramine 是第一代 H1 antagonist，具抗膽鹼作用，可用於急性 dystonia、藥物誘發 extrapyramidal symptoms 的緩解。答案選 C。",
    options: {
      A: "錯誤。Famotidine 是 H2 blocker，主要降低胃酸，不用於錐體外症狀。",
      B: "錯誤。Haloperidol 是 D2 antagonist，本身常造成 EPS，不是緩解 EPS 的 H1 拮抗劑。",
      C: "正確。Diphenhydramine 是第一代 H1 blocker，能穿過血腦障壁且具抗膽鹼作用，可治療急性肌張力不全等 EPS。",
      D: "錯誤。Cetirizine 是第二代 H1 blocker，較少中樞與抗膽鹼作用，不是治療藥物誘發 EPS 的典型選擇。",
    },
    core: "藥物誘發急性 dystonia 可用 benztropine 或 diphenhydramine；第一代 H1 blocker 有中樞抗膽鹼效果。",
    key: "Diphenhydramine 是第一代 H1 拮抗劑，可緩解急性 EPS。",
    front: "diphenhydramine / H1 antagonist / extrapyramidal symptoms",
    back: "Diphenhydramine 有中樞抗膽鹼作用，可用於急性 dystonia 等藥物誘發 EPS。",
    summary: "EPS 治療 -> diphenhydramine 或 benztropine",
  },
  58: {
    stem: "血栓溶解治療的目標是活化 plasminogen 生成 plasmin；但 plasmin 本身在血中會被快速抑制，不能直接全身靜脈注射作為有效血栓溶解藥。答案選 C。",
    options: {
      A: "抗原性是 streptokinase 的罩門，因來源接近鏈球菌蛋白，過敏反應比 t-PA 常見。",
      B: "這句是在描述 streptokinase 的活化方式：先和 plasminogen 成複合物，再促進 plasmin 形成。",
      C: "直接注射 plasmin 會在血中被 alpha-2 antiplasmin 快速中和，也缺乏血栓局部選擇性，因此是錯誤敘述。",
      D: "Fibrin-bound plasminogen 是 t-PA 較偏好的目標，這也是它較具血栓選擇性的理由。",
    },
    core: "Thrombolytics 活化 plasminogen，而不是直接打 plasmin；t-PA 較 fibrin-specific，streptokinase 較易過敏。",
    key: "Plasmin 不能直接全身靜脈注射作為有效血栓溶解治療。",
    front: "thrombolytics / plasminogen / plasmin / t-PA",
    back: "血栓溶解藥活化 plasminogen 產生 plasmin；直接注射 plasmin 會被快速中和。",
    summary: "血栓溶解 -> 活化 plasminogen，不直接注射 plasmin",
  },
  59: {
    stem: "Fibrates 如 gemfibrozil 活化 PPAR-α，上調 lipoprotein lipase 與 apoA，增加脂肪酸氧化並降低 VLDL/TG，答案選 A。",
    options: {
      A: "正確。Gemfibrozil 是 fibrate，活化 PPAR-α，最主要降低 triglycerides/VLDL。",
      B: "錯誤。Simvastatin 抑制 HMG-CoA reductase，主要降低 LDL。",
      C: "錯誤。Colestipol 是 bile acid sequestrant，阻斷腸道膽酸再吸收以降低 LDL。",
      D: "錯誤。Ezetimibe 抑制 NPC1L1，降低小腸膽固醇吸收。",
    },
    core: "降血脂藥機轉：fibrate-PPARα-TG；statin-HMG-CoA reductase-LDL；ezetimibe-NPC1L1；bile acid resin-膽酸再吸收。",
    key: "Gemfibrozil 活化 PPAR-α，增加 LPL 並降低 VLDL/TG。",
    front: "gemfibrozil / PPAR-alpha / LPL / VLDL",
    back: "Fibrates 活化 PPAR-α，增加 LPL 與脂肪酸氧化，降低 VLDL/TG。",
    summary: "Fibrate -> PPARα -> 降 TG/VLDL",
  },
  60: {
    stem: "病人甲狀腺切除後呈 hypothyroidism，應補充 levothyroxine；上呼吸道症狀可用 dextromethorphan 或 acetaminophen。Methimazole 抑制甲狀腺素合成，會加重甲狀腺低下，不適合，答案選 C。",
    options: {
      A: "錯誤。Levothyroxine 是 T4 補充，用於甲狀腺切除後或 hypothyroidism。",
      B: "錯誤。Dextromethorphan 是止咳藥，對甲狀腺低下本身不是禁忌重點。",
      C: "正確。Methimazole 抑制 thyroid peroxidase，減少甲狀腺素合成，適用 hyperthyroidism，不適合已經 hypothyroid 的病人。",
      D: "錯誤。Acetaminophen 可退燒止痛，輕微上呼吸道感染時可用，與加重甲狀腺低下無直接關係。",
    },
    core: "Methimazole/PTU 治 hyperthyroidism；levothyroxine 治 hypothyroidism。先看病人是甲狀腺素過多還是不足。",
    key: "Hypothyroidism 病人不適合使用 methimazole。",
    front: "hypothyroidism / methimazole / levothyroxine",
    back: "Methimazole 抑制甲狀腺素合成，治療 hyperthyroidism；甲狀腺切除後 hypothyroidism 應用 levothyroxine。",
    summary: "甲狀腺低下 -> 補 T4，避免 methimazole",
  },
  61: {
    stem: "題目問主要作用受體不在細胞膜而在細胞內的藥物。Prednisolone 是 glucocorticoid，通過細胞膜後結合細胞質/核內受體，調控基因轉錄，答案選 C。",
    options: {
      A: "錯誤。Erlotinib 抑制 EGFR tyrosine kinase，EGFR 是細胞膜受體型酪胺酸激酶。",
      B: "錯誤。Metoclopramide 主要拮抗 D2 receptor，也有 5-HT4 促進作用，作用於膜上 GPCR。",
      C: "正確。Prednisolone 是類固醇，受體位於細胞內，藥物進入細胞後調控轉錄。",
      D: "錯誤。Diphenhydramine 拮抗 H1 receptor，H1 是細胞膜上的 GPCR。",
    },
    core: "類固醇、甲狀腺素、維生素 D、retinoids 常考 intracellular/nuclear receptors；多數胜肽與單胺受體在膜上。",
    key: "Prednisolone 作用於細胞內 glucocorticoid receptor。",
    front: "intracellular receptor / prednisolone / glucocorticoid",
    back: "Prednisolone 為類固醇，進入細胞後結合細胞內受體並調控基因轉錄。",
    summary: "細胞內受體 -> 類固醇 prednisolone",
  },
  62: {
    stem: "Mifepristone (RU-486) 是 progesterone receptor antagonist，阻斷黃體素維持子宮內膜與妊娠的作用，常與 prostaglandin analog 合用終止早期妊娠，答案選 D。",
    options: {
      A: "抗糖皮質激素作用確實存在，但墮胎用途的主軸是阻斷 progesterone receptor。",
      B: "雌激素分泌不是 RU-486 的主要靶點；拿 estrogen 下降來解釋懷孕中止不精準。",
      C: "PGI2 antagonist 不是這個藥的角色；臨床搭配的是 misoprostol 這類 prostaglandin analog 來促進收縮。",
      D: "阻斷 progesterone 會破壞蛻膜與子宮內膜對妊娠的支持，所以能使早期妊娠無法維持。",
    },
    core: "Mifepristone = anti-progesterone；misoprostol = prostaglandin E1 analog，兩者常合用於藥物流產。",
    key: "RU-486 墮胎主要靠拮抗 progesterone receptor。",
    front: "mifepristone / RU-486 / progesterone receptor antagonist",
    back: "Mifepristone 是 progesterone receptor antagonist，阻斷黃體素維持妊娠的作用。",
    summary: "RU-486 -> 抗黃體素",
  },
  63: {
    stem: "Chlorothiazide 是 thiazide diuretic，抑制遠曲小管 Na-Cl cotransporter，可降低尿鈣、治療高鈣尿，但可造成高血糖、低血鉀；說會引起高血鉀錯，答案選 D。",
    options: {
      A: "錯誤。Thiazide 抑制 Na+ 與 Cl- 再吸收，增加鈉氯排泄。",
      B: "錯誤。Thiazide 可增加遠曲小管鈣再吸收，降低尿鈣，可用於 idiopathic hypercalciuria。",
      C: "錯誤。Thiazide 可造成高血糖、高尿酸、高脂血症等代謝副作用。",
      D: "正確。Thiazide 會增加遠端鈉送達與醛固酮相關鉀排泄，典型副作用是低血鉀，不是高血鉀。",
    },
    core: "Thiazide：抑制 NCC、降尿鈣；副作用 hyperGLUC：hyperGlycemia、hyperLipidemia、hyperUricemia、hyperCalcemia，另有 hypokalemia。",
    key: "Chlorothiazide 典型造成低血鉀，不是高血鉀。",
    front: "thiazide / chlorothiazide / hypokalemia / hypercalciuria",
    back: "Thiazide 抑制 Na-Cl cotransporter，降低尿鈣；常見低血鉀、高血糖與高尿酸。",
    summary: "Thiazide -> 低血鉀、降尿鈣",
  },
  64: {
    stem: "Adenosine 主要活化 A1 receptor，增加 AV node K+ conductance 並降低 Ca2+ influx，使 AV nodal conduction 暫停；它不是 Na+ channel blocker。Amiodarone、flecainide、mexiletine 都有抑制 Na+ channel 的作用，答案選 A。",
    options: {
      A: "正確。Adenosine 作用在 purinergic receptor，主要抑制 AV node conduction，不屬 class I Na+ channel blocker。",
      B: "錯誤。Amiodarone 以 class III K+ channel blockade 為主，但也有 class I Na+ channel blocking 等多重作用。",
      C: "錯誤。Flecainide 是 class IC antiarrhythmic，強力抑制 Na+ channel。",
      D: "錯誤。Mexiletine 是 class IB antiarrhythmic，抑制 Na+ channel，類似口服 lidocaine。",
    },
    core: "抗心律不整：class I 阻 Na+；adenosine 用於 PSVT，作用在 AV node，不是 Na+ channel blocker。",
    key: "Adenosine 不抑制 Na+ channel，主要短暫抑制 AV node。",
    front: "adenosine / antiarrhythmic / sodium channel",
    back: "Adenosine 活化 A1 receptor 抑制 AV node；flecainide、mexiletine 為 Na+ channel blockers，amiodarone 有多重作用。",
    summary: "抗心律不整 -> adenosine 非 Na channel blocker",
  },
  65: {
    stem: "Nicorandil 兼具 nitrate-like NO donor 與 ATP-sensitive K+ channel opener 作用，可降低細胞內鈣、血管擴張並治療心絞痛。它不是打開 sodium channel，答案選 B。",
    options: {
      A: "錯誤。Nicorandil 有 nitrate-like 作用，可增加 NO/cGMP 訊號，促進血管舒張。",
      B: "正確。Nicorandil 打開的是 KATP channel，不是 sodium channel。",
      C: "錯誤。血管平滑肌超極化與 NO 訊號會降低 intracellular Ca2+，造成血管舒張。",
      D: "錯誤。Nicorandil 可用於心絞痛治療，透過降低前後負荷與冠狀動脈擴張改善供需平衡。",
    },
    core: "Nicorandil = nitrate + KATP opener；心絞痛治療，不是 Na+ channel opener。",
    key: "Nicorandil 打開 KATP channel，不是 sodium channel。",
    front: "nicorandil / KATP opener / nitrate",
    back: "Nicorandil 兼具 NO donor 與 KATP channel opener 作用，可治心絞痛；不是開 sodium channel。",
    summary: "Nicorandil -> NO + KATP，不是 Na channel",
  },
  66: {
    stem: "Labetalol 同時阻斷 alpha-1 與 beta receptors，因此在列出的 beta blockers 中 alpha 阻斷作用最明顯。Atenolol 偏 β1，propranolol 與 pindolol 主要是非選擇性 beta blockade，答案選 B。",
    options: {
      A: "錯誤。Atenolol 偏 β1 selective，沒有明顯 alpha receptor blockade。",
      B: "正確。Labetalol 兼具 α1 blockade 與非選擇性 β blockade，可降血壓，也常見於妊娠或急症高血壓情境。",
      C: "錯誤。Propranolol 是非選擇性 β blocker，主要阻斷 β1/β2，不以 alpha 阻斷為特色。",
      D: "錯誤。Pindolol 是具 partial agonist activity 的非選擇性 β blocker，不是 alpha blocker。",
    },
    core: "有 alpha + beta blockade 的代表藥是 labetalol、carvedilol；單純 beta blockers 不要混淆。",
    key: "Labetalol 具有明顯 alpha-1 阻斷作用。",
    front: "labetalol / alpha beta blocker",
    back: "Labetalol 同時阻斷 α1 與 β receptors；atenolol、propranolol、pindolol 主要是 beta blockers。",
    summary: "交感受體拮抗劑 -> labetalol 有 alpha blockade",
  },
  67: {
    stem: "Myasthenia gravis 治療使用周邊作用的 acetylcholinesterase inhibitors，如 pyridostigmine、neostigmine、ambenonium。Physostigmine 可進入中樞，常用於抗膽鹼中毒，不適合作為 MG 治療，答案選 B。",
    options: {
      A: "錯誤。Pyridostigmine 是 MG 長期症狀治療最常用的膽鹼酯酶抑制劑之一。",
      B: "正確。Physostigmine 是三級胺，可穿過血腦障壁，主要用於抗膽鹼中毒；MG 治療不選它。",
      C: "錯誤。Neostigmine 是周邊性膽鹼酯酶抑制劑，可用於 MG 或逆轉非去極化肌鬆。",
      D: "錯誤。Ambenonium 也可用於 MG，屬周邊作用的膽鹼酯酶抑制劑。",
    },
    core: "MG 用 pyridostigmine/neostigmine/ambenonium；physostigmine 進 CNS，考抗膽鹼中毒。",
    key: "Physostigmine 不適合用於重症肌無力常規治療。",
    front: "myasthenia gravis / physostigmine / pyridostigmine",
    back: "MG 用周邊膽鹼酯酶抑制劑如 pyridostigmine；physostigmine 可進 CNS，常用於抗膽鹼中毒。",
    summary: "MG 膽鹼酯酶抑制劑 -> 不選 physostigmine",
  },
  68: {
    stem: "Omalizumab 是 anti-IgE monoclonal antibody，可與游離 IgE 結合形成複合體，降低 IgE 與 mast cell/basophil FcεRI 結合，答案選 C。",
    options: {
      A: "錯誤。Mepolizumab 是 anti-IL-5，降低 eosinophil 活性，常用於嗜酸性氣喘。",
      B: "錯誤。Tocilizumab 阻斷 IL-6 receptor，用於類風濕性關節炎、cytokine release syndrome 等。",
      C: "正確。Omalizumab 結合血中 IgE，減少 IgE 介導過敏反應，適用於過敏性氣喘等。",
      D: "錯誤。Efalizumab 曾是 anti-CD11a 藥物，與 IgE 中和無關，且因安全性問題已不常使用。",
    },
    core: "氣喘生物製劑：omalizumab-IgE、mepolizumab/reslizumab-IL-5、dupilumab-IL-4R。",
    key: "Omalizumab 是 anti-IgE，可清除血中 IgE 複合體。",
    front: "omalizumab / anti-IgE / asthma",
    back: "Omalizumab 結合游離 IgE，降低 mast cell/basophil IgE-mediated activation。",
    summary: "氣喘 anti-IgE -> omalizumab",
  },
  69: {
    stem: "COPD 長效 muscarinic receptor antagonist 的代表是 tiotropium。Ipratropium 是短效 SAMA，formoterol 是長效 β2 agonist，答案選 C。",
    options: {
      A: "Atropine 不是吸入型 COPD 維持治療常用的長效抗膽鹼選擇，且非專一肺部用藥。",
      B: "Ipratropium 屬 SAMA，適合短效支氣管擴張；題目要找的是長效藥。",
      C: "Tiotropium 是 LAMA，作用時間長，常作 COPD 維持治療的吸入抗膽鹼藥。",
      D: "Formoterol 雖然也是長效支氣管擴張劑，但分類是 LABA，不是 muscarinic antagonist。",
    },
    core: "COPD 吸入藥：SAMA ipratropium、LAMA tiotropium；LABA formoterol/salmeterol。",
    key: "Tiotropium 是長效 muscarinic receptor antagonist。",
    front: "COPD / LAMA / tiotropium",
    back: "Tiotropium 是 COPD 用長效抗膽鹼 LAMA；ipratropium 是短效 SAMA，formoterol 是 LABA。",
    summary: "COPD LAMA -> tiotropium",
  },
  70: {
    stem: "Diclegis 是 doxylamine 加 pyridoxine 的複方，doxylamine 為第一代 H1 antagonist，常用於妊娠噁心嘔吐。答案選 D。",
    options: {
      A: "錯誤。Ondansetron 是 5-HT3 antagonist，可止吐，但題目指定 H1 receptor 拮抗且適合懷孕，較精準是 Diclegis。",
      B: "錯誤。Ranitidine 是 H2 blocker，主要抑制胃酸，不是 H1 antagonist 止吐藥。",
      C: "錯誤。Tiprolisant/pitolisant 類與 H3 receptor 調節較相關，不是妊娠噁心嘔吐的標準 H1 拮抗藥。",
      D: "正確。Diclegis 含 doxylamine（H1 antagonist）與 pyridoxine，是妊娠噁心嘔吐常用選擇。",
    },
    core: "Pregnancy nausea/vomiting 常考 doxylamine-pyridoxine；H1 antagonist 不是 H2 blocker 或 5-HT3 blocker。",
    key: "Diclegis 含 doxylamine，透過 H1 拮抗治療妊娠噁心嘔吐。",
    front: "Diclegis / doxylamine / pregnancy nausea",
    back: "Diclegis = doxylamine + pyridoxine；doxylamine 是 H1 antagonist，可用於妊娠噁心嘔吐。",
    summary: "妊娠噁心嘔吐 -> Diclegis/doxylamine-pyridoxine",
  },
  71: {
    stem: "Tolvaptan 是選擇性 vasopressin V2 receptor antagonist，可增加自由水排泄 aquaresis，用於特定低血鈉如 SIADH。Conivaptan 同時阻斷 V1a/V2，不是選擇性 V2，答案選 D。",
    options: {
      A: "錯誤。Selepressin 是選擇性 V1a agonist，曾研究於血管張力支持，並非 V2 antagonist。",
      B: "錯誤。Terlipressin 是 vasopressin 類似物，偏 V1 作用，用於食道靜脈曲張出血或肝腎症候群等，不是 V2 antagonist。",
      C: "錯誤。Conivaptan 是 V1a/V2 antagonist，並非選擇性 V2 antagonist。",
      D: "正確。Tolvaptan 選擇性阻斷 V2 receptor，減少集合管水再吸收，可提高血鈉。",
    },
    core: "Vaptans 治療 euvolemic/hypervolemic hyponatremia；tolvaptan 選擇性 V2，conivaptan 阻 V1a/V2。",
    key: "Tolvaptan 是選擇性 V2 receptor antagonist。",
    front: "tolvaptan / V2 antagonist / hyponatremia",
    back: "Tolvaptan 阻斷 V2 receptor 造成 aquaresis，可治療特定低血鈉；conivaptan 是 V1a/V2 antagonist。",
    summary: "低血鈉 V2 antagonist -> tolvaptan",
  },
  72: {
    stem: "CAPS 是 cryopyrin/NLRP3 inflammasome 過度活化造成 IL-1β 相關自體發炎疾病。Rilonacept 是 IL-1 trap，可治療 CAPS，包含 familial cold autoinflammatory syndrome，答案選 B。",
    options: {
      A: "錯誤。Ketorolac 是 NSAID，可止痛抗發炎，但不能針對 CAPS 的 IL-1β 核心機轉。",
      B: "正確。Rilonacept 是 IL-1 receptor fusion protein trap，能中和 IL-1，適用於 CAPS。",
      C: "錯誤。Secukinumab 是 anti-IL-17A，常用於乾癬、僵直性脊椎炎等，不是 CAPS 主要治療。",
      D: "錯誤。Tramadol 是止痛藥，不能治療 CAPS 的自體發炎機轉。",
    },
    core: "CAPS = NLRP3/cryopyrin inflammasome -> IL-1β；治療記 anakinra、rilonacept、canakinumab。",
    key: "Rilonacept 可中和 IL-1，用於 CAPS。",
    front: "CAPS / cryopyrin / IL-1 / rilonacept",
    back: "Cryopyrin-associated periodic syndrome 由 IL-1β 過度活化相關，可用 rilonacept、anakinra、canakinumab。",
    summary: "CAPS -> IL-1 blockade，rilonacept",
  },
  73: {
    stem: "Benztropine 是抗膽鹼藥，可改善 Parkinson disease tremor，但會造成尿滯留、便秘、認知變差等副作用。老年人若已有排尿不順，最不適合使用 benztropine，答案選 A。",
    options: {
      A: "正確。Benztropine 的 antimuscarinic effect 會加重攝護腺肥大或排尿困難造成的尿滯留。",
      B: "錯誤。Ropinirole 是 dopamine agonist，副作用偏嗜睡、衝動控制、姿態性低血壓，不以抗膽鹼尿滯留為主。",
      C: "錯誤。Selegiline 是 MAO-B inhibitor，增加中樞 dopamine，並非造成排尿不順的代表藥。",
      D: "錯誤。Levodopa 是 dopamine 前驅物，是 Parkinson disease 主要治療藥，不是因排尿不順最該避免的選項。",
    },
    core: "老年人用抗膽鹼藥要小心 urinary retention、glaucoma、delirium；Parkinson tremor 可用 benztropine 但禁忌較多。",
    key: "Benztropine 抗膽鹼作用會加重老年人排尿不順。",
    front: "benztropine / anticholinergic / urinary retention",
    back: "Benztropine 可治 Parkinson tremor，但抗膽鹼副作用會造成尿滯留，排尿不順老人不適合。",
    summary: "Parkinson 藥物 -> 排尿不順避免 benztropine",
  },
  74: {
    stem: "Methadone 是長效 opioid receptor agonist，可口服給藥，用於 opioid use disorder 替代治療。它仍有成癮性、停藥可戒斷，且不是拮抗劑，答案選 A。",
    options: {
      A: "正確。Methadone 口服生體可用率佳、半衰期長，適合監督下替代治療。",
      B: "錯誤。Methadone 本身是 opioid agonist，仍具依賴與成癮風險，只是藥動學較平穩可減害。",
      C: "錯誤。Methadone 是 μ-opioid receptor agonist，不是 antagonist；naltrexone、naloxone 才是拮抗劑。",
      D: "錯誤。長期使用 methadone 停藥仍可出現戒斷症狀，甚至因半衰期長而拖得較久。",
    },
    core: "Methadone：口服、長效 μ agonist、替代治療；naltrexone/naloxone 是 antagonist。",
    key: "Methadone 可口服，是長效 opioid agonist。",
    front: "methadone / oral / opioid agonist",
    back: "Methadone 是可口服長效 μ-opioid agonist，用於鴉片類成癮替代治療；仍會依賴與戒斷。",
    summary: "Methadone -> 可口服長效 opioid agonist",
  },
  75: {
    stem: "Zaleplon 是 nonbenzodiazepine hypnotic，起效快且半衰期很短，適合入睡困難。Flurazepam、diazepam、chlordiazepoxide 都是較長效 benzodiazepines，答案選 A。",
    options: {
      A: "正確。Zaleplon 半衰期約 1 小時，主要改善 sleep onset insomnia，隔日殘餘鎮靜較少。",
      B: "錯誤。Flurazepam 半衰期長且有活性代謝物，較容易隔日嗜睡，不是最短效。",
      C: "錯誤。Diazepam 半衰期長、活性代謝物多，不適合用「半衰期最短」描述。",
      D: "錯誤。Chlordiazepoxide 也是長效 benzodiazepine，常見於酒精戒斷治療，不是短效入睡藥。",
    },
    core: "Z-drugs 中 zaleplon 很短效，適合入睡困難；長效 benzodiazepines 易有隔日殘留。",
    key: "Zaleplon 起效快、半衰期短，適合入睡困難。",
    front: "zaleplon / short half-life / sleep onset insomnia",
    back: "Zaleplon 是短效 nonbenzodiazepine hypnotic，適合改善入睡困難。",
    summary: "安眠藥 -> zaleplon 短效助入睡",
  },
  76: {
    stem: "IL-17/Th17 軸對招募嗜中性球與抗細菌、抗真菌黏膜防禦很重要。IL-17 缺乏會使嗜中性球性發炎不足，病灶較可能缺少大量嗜中性球；冷膿瘍的概念是膿瘍發炎反應不明顯，答案選 D。",
    options: {
      A: "錯誤。IL-17 促進 neutrophil recruitment；若缺乏 IL-17，反而不容易形成大量嗜中性球浸潤的典型急性化膿炎。",
      B: "錯誤。尋常型天皰瘡主要是抗 desmoglein 自體抗體造成表皮內水疱，與 IL-17 缺乏不是最直接連結。",
      C: "錯誤。類天皰瘡主要是抗 hemidesmosome/basement membrane zone 抗體造成表皮下水疱。",
      D: "正確。冷膿瘍表示局部紅熱痛等急性發炎反應不明顯，可與嗜中性球招募不足或細胞免疫異常的概念連結。",
    },
    core: "IL-17 促進嗜中性球反應；缺乏時會降低典型化膿性發炎與黏膜抗菌/抗黴菌能力。",
    key: "IL-17 缺乏會影響嗜中性球招募，較能連到冷膿瘍樣發炎不明顯病灶。",
    front: "IL-17 / neutrophil recruitment / cold abscess",
    back: "Th17/IL-17 促進嗜中性球浸潤；缺乏時急性化膿性發炎反應較不足。",
    summary: "IL-17 缺乏 -> 嗜中性球反應不足，冷膿瘍",
  },
  77: {
    stem: "胃食道逆流造成食道末端慢性傷害時，可出現 Barrett esophagus，也就是鱗狀上皮被腸型柱狀上皮取代。良性柱狀上皮細胞代表化生 metaplasia，答案選 D。",
    options: {
      A: "錯誤。Dysplasia 是上皮異型增生，代表癌前變化；題幹說良性柱狀上皮，重點是細胞型態轉換。",
      B: "錯誤。Hyperplasia 是細胞數目增加，不是食道鱗狀上皮轉為柱狀上皮。",
      C: "錯誤。Metastasis 是惡性腫瘤轉移，題幹描述良性上皮變化，不符合。",
      D: "正確。Metaplasia 是一種成熟細胞型態被另一種成熟細胞型態取代，Barrett esophagus 即食道末端柱狀化生。",
    },
    core: "Barrett esophagus = intestinal metaplasia from chronic GERD；metaplasia 可增加 adenocarcinoma 風險。",
    key: "GERD 後食道末端良性柱狀上皮為化生。",
    front: "Barrett esophagus / metaplasia / GERD",
    back: "慢性胃食道逆流可造成食道末端鱗狀上皮化生成柱狀上皮，稱 Barrett esophagus。",
    summary: "GERD + 食道柱狀上皮 -> metaplasia",
  },
  78: {
    stem: "Ewing sarcoma family tumors 最常見特徵性染色體轉位是 t(11;22)(q24;q12)，形成 EWSR1-FLI1 fusion，可作為分子診斷依據，答案選 B。",
    options: {
      A: "錯誤。Trisomy 22 不是 ESFT 的典型診斷性異常。",
      B: "正確。t(11;22)(q24;q12) 形成 EWSR1-FLI1，是 Ewing sarcoma 最經典分子變化。",
      C: "錯誤。1p/19q co-deletion 是 oligodendroglioma 的重要分子標記，不是 Ewing sarcoma。",
      D: "錯誤。N-MYC amplification 常與 neuroblastoma 預後不良相關，不是 ESFT 的代表異常。",
    },
    core: "Ewing sarcoma = small round blue cell tumor + t(11;22) EWSR1-FLI1。",
    key: "Ewing sarcoma 常見 t(11;22)(q24;q12) translocation。",
    front: "Ewing sarcoma / t(11;22) / EWSR1-FLI1",
    back: "Ewing sarcoma family tumors 的典型分子診斷是 t(11;22) 造成 EWSR1-FLI1 fusion。",
    summary: "Ewing sarcoma -> t(11;22) EWSR1-FLI1",
  },
  79: {
    stem: "7 歲兒童、遠端股骨、偏心性小型放射線透亮多葉病灶，最符合 fibrous cortical defect，又稱 non-ossifying fibroma 小型病灶，常為偶然發現，答案選 A。",
    options: {
      A: "正確。Fibrous cortical defect 常見於兒童長骨 metaphysis，偏心、界線清楚、放射線透亮，通常良性且可自限。",
      B: "錯誤。Fibrous dysplasia 可見 ground-glass appearance，常位於骨髓腔，年齡與影像描述不如 A 符合。",
      C: "錯誤。Giant cell tumor 多見骨骺閉合後年輕成人，位於 epiphysis，年齡與位置不符。",
      D: "錯誤。Chondrosarcoma 多見成人/老年，屬惡性軟骨腫瘤，與 7 歲小孩小型皮質缺損不符。",
    },
    core: "兒童長骨 metaphysis 偏心性 radiolucent lesion 要想到 fibrous cortical defect/non-ossifying fibroma。",
    key: "兒童遠端股骨偏心性小型透亮病灶最符合 fibrous cortical defect。",
    front: "fibrous cortical defect / child / eccentric radiolucent metaphysis",
    back: "Fibrous cortical defect 常見兒童長骨 metaphysis，偏心性、放射線透亮，通常良性自限。",
    summary: "兒童遠端股骨偏心透亮病灶 -> fibrous cortical defect",
  },
  80: {
    stem: "腦外傷後可有精神症狀、post-traumatic epilepsy、hydrocephalus 等後遺症。脫髓鞘性疾病通常屬免疫或代謝等其他機轉，不是腦外傷常見後遺症，答案選 D。",
    options: {
      A: "錯誤。腦外傷後可出現情緒障礙、人格改變、焦慮、憂鬱或認知行為問題。",
      B: "錯誤。腦外傷是後天性癲癇的重要原因之一，可造成 post-traumatic epilepsy。",
      C: "錯誤。腦外傷後出血、蛛網膜下腔沾黏或吸收障礙可造成水腦。",
      D: "正確。脫髓鞘性病變如 multiple sclerosis 多為免疫相關疾病，不是腦外傷常見後遺症。",
    },
    core: "TBI 後遺症可記 cognitive/psychiatric change、seizure、hydrocephalus；demyelinating disease 不是典型外傷後果。",
    key: "脫髓鞘性病變少見於腦外傷後遺症。",
    front: "traumatic brain injury / sequelae / demyelinating disease",
    back: "腦外傷後可有精神症狀、癲癇與水腦；脫髓鞘疾病不是常見後遺症。",
    summary: "腦外傷後遺症 -> 精神、癲癇、水腦；非脫髓鞘",
  },
  81: {
    stem: "AIDS 病人免疫監控下降，較易發生與 DNA virus 相關腫瘤。原發性中樞神經 B 細胞淋巴瘤多與 EBV 相關，子宮頸鱗狀上皮癌與 HPV 相關，Kaposi sarcoma 與 HHV-8 相關，三者皆是 DNA virus 相關，答案選 A。",
    options: {
      A: "正確。1、2、3 都與 DNA virus 相關，且 AIDS 免疫缺陷時風險增加。",
      B: "錯誤。僅 1、2 漏掉 Kaposi sarcoma；Kaposi sarcoma 是 AIDS-defining malignancy，與 HHV-8 相關。",
      C: "錯誤。僅 2、3 漏掉 EBV 相關原發性 CNS lymphoma。",
      D: "錯誤。僅 1、3 漏掉 HPV 相關子宮頸癌。",
    },
    core: "AIDS 相關腫瘤：EBV-CNS lymphoma，HHV-8-Kaposi sarcoma，HPV-cervical/anal cancers。",
    key: "AIDS 病人較易得到 EBV、HPV、HHV-8 等 DNA 病毒相關腫瘤。",
    front: "AIDS malignancies / EBV / HPV / HHV-8",
    back: "AIDS 易發 EBV 相關 CNS lymphoma、HPV 相關子宮頸癌、HHV-8 相關 Kaposi sarcoma。",
    summary: "AIDS 腫瘤 -> EBV、HPV、HHV-8 皆 DNA virus",
  },
  82: {
    stem: "Rhinocerebral mucormycosis 常見於糖尿病酮酸中毒、中性球低下或類固醇使用者。Mucorales 會侵犯血管造成 thrombosis 與組織壞死；典型菌絲寬大、無隔或少隔、直角分枝，答案選 D。",
    options: {
      A: "錯誤。快速壞死主因是血管侵犯與血栓造成缺血壞死，不是外毒素傷害。",
      B: "錯誤。分節清楚、銳角分枝、寬度較固定較像 Aspergillus；Mucor 是寬大 pauciseptate、近直角分枝。",
      C: "錯誤。Mucorales 不是典型雙態性真菌；雙態性真菌如 Histoplasma、Blastomyces、Coccidioides 等。",
      D: "正確。糖尿病、類固醇、嗜中性球低下是 rhinocerebral mucormycosis 的重要危險因子。",
    },
    core: "Mucor：diabetic ketoacidosis、neutropenia、steroids；broad nonseptate hyphae with right-angle branching；angioinvasion。",
    key: "鼻腦白黴菌病易發於糖尿病、嗜中性球低下與類固醇使用者。",
    front: "mucormycosis / DKA / broad nonseptate hyphae",
    back: "Mucormycosis 好發 DKA、neutropenia、steroid use；菌絲寬大少隔、直角分枝，會侵犯血管造成壞死。",
    summary: "Mucor -> DKA/中性球低下，寬大少隔直角分枝",
  },
  83: {
    stem: "遺傳性 retinoblastoma 來自 germline RB1 mutation，患者日後最常見重要第二惡性腫瘤為 osteosarcoma，尤其曾接受放射治療者風險更高，答案選 C。",
    options: {
      A: "錯誤。Leukemia 可作為兒童惡性腫瘤之一，但不是 familial retinoblastoma 最典型繼發癌。",
      B: "錯誤。Lymphoma 與 RB1 遺傳性視網膜母細胞瘤的典型第二癌關聯不如 osteosarcoma。",
      C: "正確。Osteosarcoma 是 hereditary retinoblastoma 患者經典第二惡性腫瘤。",
      D: "錯誤。Hepatoblastoma 與某些遺傳症候群如 FAP/Beckwith-Wiedemann 相關，不是本題典型答案。",
    },
    core: "RB1 mutation：retinoblastoma，第二癌記 osteosarcoma；RB pathway 控制 G1/S checkpoint。",
    key: "Familial retinoblastoma 最常見重要繼發惡性腫瘤是 osteosarcoma。",
    front: "familial retinoblastoma / RB1 / osteosarcoma",
    back: "遺傳性視網膜母細胞瘤與 RB1 germline mutation 有關，日後易發 osteosarcoma。",
    summary: "RB1 遺傳性視網膜母細胞瘤 -> osteosarcoma",
  },
  84: {
    stem: "全身性血栓栓塞指動脈系統栓子進入體循環，最常源自左心腔內 mural thrombus，尤其心肌梗塞後左心室壁梗塞處。下肢深靜脈血栓通常造成肺栓塞，答案選 B。",
    options: {
      A: "錯誤。下肢深層靜脈血栓會經右心進入肺動脈，造成 pulmonary embolism，不是一般 systemic thromboembolism 的最常見來源。",
      B: "正確。左心室心肌梗塞區域可形成 mural thrombus，脫落後進入體循環造成腦、腎、脾或下肢栓塞。",
      C: "錯誤。主動脈動脈瘤或粥狀硬化斑塊可形成栓子，但不是最常見來源。",
      D: "錯誤。下肢淺層靜脈血栓較少造成嚴重栓塞，且即使脫落也多走肺循環，不是體循環栓子來源。",
    },
    core: "Venous thrombi -> pulmonary emboli；left heart/aorta thrombi -> systemic emboli。",
    key: "全身性血栓栓塞最常見來源是左心 mural thrombus，尤其心肌梗塞後。",
    front: "systemic thromboembolism / left ventricular mural thrombus",
    back: "心肌梗塞後左心室壁可形成 mural thrombus，脫落造成全身性動脈栓塞；DVT 多造成肺栓塞。",
    summary: "Systemic emboli -> 左心室 mural thrombus",
  },
  85: {
    stem: "咽炎後 3 週、ASO 上升、發燒、心臟炎、關節痛與皮下結節，符合急性風濕熱。心臟 Aschoff bodies 中的 Anitschkow cells 是特徵性細胞，答案選 A。",
    options: {
      A: "正確。Anitschkow cells 是活化巨噬細胞，核染色質呈 caterpillar-like，是風濕性心臟炎 Aschoff body 的特徵。",
      B: "錯誤。Reed-Sternberg cells 是 Hodgkin lymphoma 的代表細胞。",
      C: "錯誤。Cajal cells 是腸胃道間質細胞，與 GIST 相關，不是風濕熱心臟病灶特異細胞。",
      D: "錯誤。Purkinje cells 在心臟傳導系統或小腦皮質皆有名詞使用，但不是急性風濕熱診斷細胞。",
    },
    core: "急性風濕熱：Group A strep 後、Jones criteria、Aschoff bodies、Anitschkow cells。",
    key: "急性風濕熱心臟病灶特徵細胞是 Anitschkow cell。",
    front: "acute rheumatic fever / Aschoff body / Anitschkow cell",
    back: "鏈球菌咽炎後急性風濕熱可有 Aschoff body，其中 Anitschkow cell 具 caterpillar-like nucleus。",
    summary: "風濕熱心臟炎 -> Anitschkow cell",
  },
  86: {
    stem: "四腔室擴大、心重增加、心室無明顯肥厚、冠脈無狹窄，符合 dilated cardiomyopathy。常見 myocyte hypertrophy、interstitial fibrosis 與 small subendocardial scars；myofiber disarray 是 hypertrophic cardiomyopathy 的特徵，答案選 D。",
    options: {
      A: "錯誤。Dilated cardiomyopathy 可因負荷與代償出現心肌細胞肥大。",
      B: "錯誤。間質纖維化常見於擴張型心肌病變的慢性心肌損傷修復。",
      C: "錯誤。Subendocardial scars 可見於慢性心肌缺氧或微小損傷後變化。",
      D: "正確。Myofiber disarray 是 hypertrophic cardiomyopathy 的典型組織特徵，不是 dilated cardiomyopathy 最常見變化。",
    },
    core: "Dilated cardiomyopathy = 四腔擴大、收縮衰竭；HCM = septal hypertrophy、myofiber disarray。",
    key: "Myofiber disarray 是肥厚型心肌病變特徵，不常見於擴張型心肌病變。",
    front: "dilated cardiomyopathy / myofiber disarray / HCM",
    back: "擴張型心肌病變有四腔擴大與纖維化；myofiber disarray 屬肥厚型心肌病變典型。",
    summary: "DCM vs HCM -> myofiber disarray 屬 HCM",
  },
  87: {
    stem: "Follicular lymphoma 是成熟 B cell lymphoma，典型 t(14;18) 導致 BCL2 overexpression，使細胞不易凋亡。答案選 C。",
    options: {
      A: "錯誤。濾泡性淋巴瘤是 B 細胞來源，不是 NK cell lymphoma。",
      B: "錯誤。Follicular lymphoma 常表現 CD20、CD10、BCL6、BCL2；CD5/cyclin D1 典型見於 mantle cell lymphoma。",
      C: "正確。t(14;18) 把 BCL2 放到 Ig heavy chain enhancer 旁，造成 BCL2 過度表現並抑制 apoptosis。",
      D: "錯誤。副免疫母細胞與前淋巴細胞組成較像 CLL/SLL 的 proliferation centers，不是 follicular lymphoma 的典型描述。",
    },
    core: "Follicular lymphoma = B cell、CD10、BCL2、t(14;18)、多為 indolent。",
    key: "濾泡性淋巴瘤常有 t(14;18) 造成 BCL2 過度表現。",
    front: "follicular lymphoma / t(14;18) / BCL2",
    back: "Follicular lymphoma 是 B cell lymphoma，常見 t(14;18) 導致 BCL2 overexpression。",
    summary: "Follicular lymphoma -> t(14;18) BCL2",
  },
  88: {
    stem: "缺鐵性貧血典型為 microcytic hypochromic anemia，血清鐵與 ferritin 下降、TIBC 上升，常見於育齡女性或慢性失血。答案選 A。",
    options: {
      A: "正確。缺鐵造成血紅素合成不足，紅血球變小且顏色較淡。",
      B: "錯誤。缺鐵性貧血常見於月經失血、懷孕或慢性失血族群；不是較常發生於男性。",
      C: "錯誤。西方國家成人缺鐵常見原因是慢性失血，尤其腸胃道出血或月經，而非單純飲食攝取不足。",
      D: "錯誤。缺鐵時 transferrin/TIBC 通常上升，以增加攜鐵能力；降低較像慢性病貧血。",
    },
    core: "Iron deficiency anemia：低 MCV、低 ferritin、低 serum iron、高 TIBC；成人要找慢性失血來源。",
    key: "缺鐵性貧血為小球性低色素性貧血，TIBC 通常升高。",
    front: "iron deficiency anemia / microcytic hypochromic / TIBC",
    back: "缺鐵性貧血紅血球小且淡，ferritin 低、serum iron 低、TIBC 高。",
    summary: "缺鐵貧血 -> 小球低色素，TIBC 高",
  },
  89: {
    stem: "雙側胸膜積水最常見原因是鬱血性心衰竭，因靜水壓上升形成 transudative pleural effusion，常可雙側出現，答案選 B。",
    options: {
      A: "錯誤。肺癌可造成惡性胸水，常為 exudate，可能單側或雙側，但不是雙側胸水最常見原因。",
      B: "正確。鬱血性心衰竭使肺靜脈與全身靜脈壓升高，造成雙側漏出性胸水，是最常見原因。",
      C: "錯誤。惡性間皮瘤與石綿暴露相關，造成胸膜腫瘤與胸水，但遠少於 CHF。",
      D: "錯誤。呼吸窘迫是臨床表現或症候群，不是雙側 hydrothorax 的最常見病因。",
    },
    core: "Bilateral transudative pleural effusion 最先想到 CHF；Light criteria 可區分 transudate/exudate。",
    key: "雙側胸膜積水最常見原因是鬱血性心衰竭。",
    front: "bilateral pleural effusion / CHF / hydrothorax",
    back: "鬱血性心衰竭造成靜水壓升高，常引起雙側漏出性胸水。",
    summary: "雙側胸水 -> CHF 最常見",
  },
  90: {
    stem: "小細胞肺癌與抽菸高度相關，常位於肺中央，具有神經內分泌標記，早期即縱隔淋巴結與遠端轉移。說它與抽菸關聯性不大是錯的，答案選 A。",
    options: {
      A: "正確。Small cell carcinoma 是與吸菸關聯最強的肺癌之一，這句明顯錯誤。",
      B: "錯誤。小細胞肺癌常發生於中央肺門/支氣管附近。",
      C: "錯誤。小細胞肺癌常表現 chromogranin、synaptophysin、CD56 等神經內分泌標記。",
      D: "錯誤。小細胞肺癌侵襲性強，診斷時常已有縱隔淋巴結或遠端轉移。",
    },
    core: "Small cell lung cancer：central、smoking、neuroendocrine、早期轉移、常伴 paraneoplastic syndrome。",
    key: "小細胞肺癌與抽菸高度相關。",
    front: "small cell lung carcinoma / smoking / neuroendocrine",
    back: "小細胞肺癌常中央型、與吸菸高度相關、具神經內分泌標記且早期轉移。",
    summary: "小細胞肺癌 -> 抽菸高度相關",
  },
  91: {
    stem: "ARDS 最常見原因包含敗血症與肺炎；在選項中肺炎是最常見且最直接的誘因。Aspiration、外傷、輸血反應也可造成 ARDS，但頻率較低，答案選 D。",
    options: {
      A: "錯誤。吸入胃內容物可造成化學性肺炎與 ARDS，但不是此選項組合中最常見原因。",
      B: "錯誤。外傷可透過 shock、脂肪栓塞或大量輸血等引發 ARDS，但不是最常見。",
      C: "錯誤。輸血反應如 TRALI 可造成急性肺損傷，但整體上不如肺炎常見。",
      D: "正確。肺炎是 ARDS 最常見直接肺部原因之一，也是此題最適合答案。",
    },
    core: "ARDS 常見誘因：sepsis、pneumonia、aspiration、trauma、pancreatitis、TRALI；選項中 pneumonia 最常見。",
    key: "選項中引起 ARDS 最常見的原因是肺炎。",
    front: "ARDS / pneumonia / aspiration / TRALI",
    back: "ARDS 可由肺炎、敗血症、吸入、外傷、輸血反應等引起；選項中肺炎最常見。",
    summary: "ARDS 原因 -> 肺炎常見",
  },
  92: {
    stem: "H. pylori 與慢性胃炎、消化性潰瘍、胃腺癌、胃 MALT lymphoma 關係密切。胃底腺息肉 fundic gland polyp 常與 PPI 使用或 FAP 相關，和 H. pylori 最無直接關係，答案選 A。",
    options: {
      A: "正確。Fundic gland polyp 通常與 PPI 使用或家族性腺瘤性瘜肉症相關，和 H. pylori 關聯最弱。",
      B: "錯誤。H. pylori 是慢性消化性潰瘍的重要原因，尤其十二指腸潰瘍與部分胃潰瘍。",
      C: "錯誤。H. pylori 慢性胃炎可增加 intestinal-type gastric adenocarcinoma 風險。",
      D: "錯誤。胃 MALT lymphoma 與 H. pylori 關係強，早期病灶可能因根除 H. pylori 而緩解。",
    },
    core: "H. pylori：peptic ulcer、gastric carcinoma、MALT lymphoma；fundic gland polyp 多連 PPI/FAP。",
    key: "胃底腺息肉與 H. pylori 最無直接關係。",
    front: "H. pylori / fundic gland polyp / MALT lymphoma",
    back: "H. pylori 與消化性潰瘍、胃癌、MALT lymphoma 相關；fundic gland polyp 多與 PPI 或 FAP 相關。",
    summary: "H. pylori 相關疾病 -> 不含典型 fundic gland polyp",
  },
  93: {
    stem: "Crohn disease 是全壁性發炎，可有 skip lesions；ulcerative colitis 從直腸連續向近端侵犯，通常不跳躍。說 skip lesion 是 UC 特徵錯，答案選 C。",
    options: {
      A: "區域性腸炎這個別名用在 Crohn disease，常見侵犯末端迴腸，敘述本身沒錯。",
      B: "全壁性發炎也是 Crohn 的特色，能解釋狹窄、瘻管與 fissure。",
      C: "Skip lesions 不是 UC 的型態；UC 典型從直腸開始連續往近端延伸，所以此句錯。",
      D: "長期、廣泛 UC 會增加 colorectal cancer 風險，這是需要追蹤監測的原因。",
    },
    core: "Crohn：skip lesion、transmural、任何 GI；UC：continuous from rectum、mucosal/submucosal、大腸癌風險。",
    key: "Skip lesion 是 Crohn disease 特徵，不是 ulcerative colitis。",
    front: "IBD / Crohn / ulcerative colitis / skip lesion",
    back: "Crohn disease 有 skip lesions 與全壁發炎；ulcerative colitis 多為直腸起始連續性黏膜發炎。",
    summary: "IBD 分辨 -> skip lesion 屬 Crohn",
  },
  94: {
    stem: "酒後上腹痛放射背部、amylase/lipase 上升與低血鈣，符合急性胰臟炎。嚴重急性胰臟炎可有脂肪壞死、皂化造成低血鈣，以及出血性壞死，答案選 A。",
    options: {
      A: "正確。急性胰臟炎時消化酶活化造成胰臟自我消化，可見 hemorrhagic necrosis 與脂肪壞死。",
      B: "錯誤。心臟廣泛性壞死不會解釋酒後上腹痛放射背部與胰臟酵素上升。",
      C: "錯誤。胃潰瘍穿孔可造成急腹症與腹膜炎，但不典型造成 amylase/lipase 明顯上升與低血鈣。",
      D: "錯誤。肝臟大塊性壞死會以肝衰竭、凝血異常與轉氨酶大幅上升為主，不是此題表現。",
    },
    core: "急性胰臟炎：酒精/膽石、上腹痛放背、amylase/lipase 上升、脂肪壞死皂化低血鈣、出血性壞死。",
    key: "急性胰臟炎可出現胰臟出血性壞死與低血鈣。",
    front: "acute pancreatitis / hemorrhagic necrosis / hypocalcemia",
    back: "酒精後上腹痛放射背部加 amylase/lipase 上升提示急性胰臟炎，可有出血性壞死與脂肪皂化低血鈣。",
    summary: "急性胰臟炎 -> 出血性壞死、低血鈣",
  },
  95: {
    stem: "Dense deposit disease 是 alternative complement pathway 調控異常，常因 C3 nephritic factor 穩定 C3 convertase，導致 C3、factor B、properdin 等 alternative pathway 成分消耗。Classical pathway 的 C1 通常維持正常，答案選 B。",
    options: {
      A: "C3 是被持續活化與消耗的核心成分，DDD 常見低 C3。",
      B: "C1 代表 classical pathway 起始端；DDD 主問題在 alternative pathway，所以 C1 較可能維持正常。",
      C: "Factor B 參與 alternative pathway C3 convertase，路徑過度活化時可能被消耗。",
      D: "Properdin 會穩定 alternative pathway 的 C3 convertase，因此同樣屬受影響路徑。",
    },
    core: "Dense deposit disease/C3 glomerulopathy：alternative pathway dysregulation，低 C3，C1/C4 相對正常。",
    key: "Dense deposit disease 主要消耗 alternative pathway，C1 通常正常。",
    front: "dense deposit disease / alternative complement pathway / C1",
    back: "DDD 常因 alternative pathway 過度活化造成 C3 下降；classical pathway 的 C1 通常維持正常。",
    summary: "DDD -> alternative pathway，C1 正常",
  },
  96: {
    stem: "典型 HUS 常發生在兒童腹瀉後，由 Shiga toxin-producing E. coli，尤其 O157:H7 引起。毒素傷害內皮造成微血管病變、血小板低下與急性腎損傷，答案選 B。",
    options: {
      A: "錯誤。A 群鏈球菌可造成咽炎、猩紅熱、風濕熱與腎絲球腎炎，但不是典型 HUS 最常見病原。",
      B: "正確。E. coli O157:H7 產 Shiga-like toxin，是典型腹瀉後 HUS 最常見原因。",
      C: "錯誤。Hib 可造成腦膜炎、會厭炎、肺炎等，不是典型 HUS 主因。",
      D: "錯誤。Viridans streptococci 常與心內膜炎、齲齒相關，不是 HUS 典型病原。",
    },
    core: "Typical HUS = shiga toxin E. coli O157:H7、bloody diarrhea、microangiopathic hemolytic anemia、thrombocytopenia、AKI。",
    key: "典型 HUS 最常見病原是產 Shiga toxin 的 E. coli O157:H7。",
    front: "typical HUS / E. coli O157:H7 / Shiga toxin",
    back: "典型腹瀉後 HUS 多由 Shiga toxin-producing E. coli O157:H7 引起，造成 MAHA、血小板低下與 AKI。",
    summary: "典型 HUS -> E. coli O157:H7",
  },
  97: {
    stem: "副甲狀腺癌與腺瘤在細胞異型、核仁、壞死或有絲分裂上可能重疊；最可靠診斷依據是明確侵犯或轉移。選項中腫瘤轉移最能確診 carcinoma，答案選 A。",
    options: {
      A: "正確。遠端轉移或明確局部侵犯是區分副甲狀腺癌與腺瘤最可靠的證據。",
      B: "錯誤。頻繁有絲分裂可增加惡性疑慮，但單獨不如轉移可靠。",
      C: "錯誤。大核仁屬細胞學 atypia，可能提示惡性，但不是最可靠條件。",
      D: "錯誤。腫瘤壞死可見於惡性腫瘤，但副甲狀腺癌診斷仍以侵犯或轉移最具決定性。",
    },
    core: "內分泌腫瘤常不能只靠 atypia 判斷良惡性；parathyroid carcinoma 最可靠是 invasion/metastasis。",
    key: "診斷副甲狀腺癌最可靠條件是侵犯或轉移。",
    front: "parathyroid carcinoma / metastasis / adenoma",
    back: "副甲狀腺癌與腺瘤細胞形態可能相似，最可靠診斷依據是局部侵犯或轉移。",
    summary: "副甲狀腺癌 -> 轉移/侵犯最可靠",
  },
  98: {
    stem: "非典型乳管增生 atypical ductal hyperplasia 會明顯增加日後乳癌風險，約為一般女性 4 到 5 倍。非增生性囊腫通常不顯著增加風險，台灣篩檢主要是乳房攝影，纖維腺瘤不典型以乳頭分泌物表現，答案選 B。",
    options: {
      A: "錯誤。Non-proliferative breast cyst 一般不會增加或只極低幅度增加乳癌風險，不是 2.5 倍。",
      B: "正確。Atypical ductal hyperplasia 屬高風險良性病變，日後乳癌風險約增加 4-5 倍。",
      C: "錯誤。台灣乳癌篩檢主要工具是 mammography，超音波可作輔助但不是主要篩檢工具。",
      D: "錯誤。Fibroadenoma 常為可移動、界線清楚腫塊；乳頭分泌物較常考 intraductal papilloma。",
    },
    core: "乳房良性病變風險：non-proliferative 低，proliferative without atypia 中等，atypical hyperplasia 高。",
    key: "非典型乳管增生會使乳癌風險約增加 4-5 倍。",
    front: "atypical ductal hyperplasia / breast cancer risk / mammography",
    back: "ADH 是高風險乳房病變，乳癌風險約 4-5 倍；篩檢主要靠乳房攝影。",
    summary: "ADH -> 乳癌風險 4-5 倍",
  },
  99: {
    stem: "子宮頸癌最常見為鱗狀上皮癌，其次腺癌；多數與高危險 HPV 相關。腺鱗癌與神經內分泌癌通常較侵襲、預後較差，不是發展到侵襲癌時間較長於鱗狀上皮癌，答案選 D。",
    options: {
      A: "錯誤。Squamous cell carcinoma 仍是子宮頸癌最常見組織型。",
      B: "錯誤。Adenocarcinoma 是第二常見組織型，比例隨篩檢與流行病學變化而相對增加。",
      C: "錯誤。高危險 HPV 與多種子宮頸癌組織型相關，包括腺癌、腺鱗癌與部分神經內分泌癌。",
      D: "正確。腺鱗癌與神經內分泌癌通常較具侵襲性，不能說一般從原位癌發展到侵襲癌較慢。",
    },
    core: "子宮頸癌：最常見 SCC，其次 adenocarcinoma；high-risk HPV 是核心危險因子，神經內分泌癌通常侵襲性高。",
    key: "腺鱗癌與神經內分泌癌不應被描述為比鱗狀上皮癌進展更慢。",
    front: "cervical carcinoma / squamous / adenocarcinoma / neuroendocrine",
    back: "子宮頸癌最常見為鱗狀上皮癌，其次腺癌；腺鱗癌與神經內分泌癌多較侵襲。",
    summary: "子宮頸癌組織型 -> SCC 最常見；D 進展慢說法錯",
  },
  100: {
    stem: "停經後婦女雙側實質性卵巢腫瘤，顯微鏡若見 signet-ring cells，典型為 Krukenberg tumor，也就是胃腸道癌轉移至卵巢，常雙側，答案選 B。",
    options: {
      A: "錯誤。卵巢類癌屬性索/生殖細胞或轉移相關神經內分泌腫瘤，可分泌 serotonin，但不以雙側實質性 signet-ring 轉移為典型。",
      B: "正確。Krukenberg tumor 是含黏液 signet-ring cells 的轉移性卵巢腫瘤，常來自胃癌且常雙側。",
      C: "錯誤。Brenner tumor 由 transitional-type epithelium 組成，常為良性單側卵巢腫瘤。",
      D: "錯誤。Struma ovarii 主要由甲狀腺組織構成，屬 monodermal teratoma，不是典型雙側轉移性 signet-ring 腫瘤。",
    },
    core: "Krukenberg tumor = metastatic mucin-producing signet-ring cell carcinoma to ovary，常胃來源、雙側。",
    key: "雙側實質性卵巢腫瘤合併 signet-ring cells 要想到 Krukenberg tumor。",
    front: "Krukenberg tumor / ovary / signet-ring cells",
    back: "Krukenberg tumor 是轉移至卵巢的黏液性 signet-ring cell carcinoma，常來自胃且常雙側。",
    summary: "雙側卵巢 + signet-ring cells -> Krukenberg tumor",
  },
};

function compact(text) {
  return String(text || "").replace(/\s+/g, " ").trim();
}

function buildExplanation(q, rewrite) {
  const answerLabel = q.correct_answer === "#" ? "官方全給分" : `標準答案為 ${q.correct_answer}`;
  const multi =
    Array.isArray(q.correct_answers) && q.correct_answers.length > 1 && q.correct_answer !== "#"
      ? `；官方接受 ${q.correct_answers.join("、")}`
      : "";
  return [
    "【題幹解析】",
    `${rewrite.stem}${multi ? multi : ""}`,
    "",
    "【選項詳解】",
    `- A. ${rewrite.options.A}`,
    `- B. ${rewrite.options.B}`,
    `- C. ${rewrite.options.C}`,
    `- D. ${rewrite.options.D}`,
    "",
    "【核心考點】",
    `${rewrite.core}（${answerLabel}${multi}。）`,
  ].join("\n");
}

function validateUpdateItem(item, q) {
  const required = ["【題幹解析】", "【選項詳解】", "【核心考點】", "- A.", "- B.", "- C.", "- D."];
  for (const token of required) {
    if (!item.explanation.includes(token)) throw new Error(`${q.id} missing ${token}`);
  }
  const banned = [
    "非本題答案",
    "不是本題標準答案",
    "回到題幹線索",
    "請用題幹線索連回",
    "題目中選項 A 所代表的鑑別或處置",
    "不能最精準回答本題",
    "最符合題幹",
    "核心記憶點",
    "定義、機轉、典型表現或處置原則",
    "標準答案所接受的判斷",
    "雖然與題目主題相關",
    "與標準答案的關鍵判斷不一致",
    "對照本題核心解析",
    "不符合本題判斷規則",
    "不是最佳答案",
  ];
  for (const phrase of banned) {
    if (item.explanation.includes(phrase)) throw new Error(`${q.id} contains banned phrase ${phrase}`);
  }
}

function makeUpdate(q) {
  const rewrite = rewrites[q.question_number];
  if (!rewrite) throw new Error(`Missing rewrite for Q${q.question_number}`);
  const item = {
    question_id: q.id,
    question_number: q.question_number,
    explanation: buildExplanation(q, rewrite),
    key_point: rewrite.key,
    flashcard_front: rewrite.front,
    flashcard_back: rewrite.back,
    flashcard_summary: rewrite.summary,
    review_status: "ai_generated",
    explanation_model: model,
    explanation_generated_at: now,
    manual_review_notes: rewrite.notes || [],
  };
  validateUpdateItem(item, q);
  return item;
}

function applyUpdate(question, item) {
  for (const field of [
    "explanation",
    "key_point",
    "flashcard_front",
    "flashcard_back",
    "flashcard_summary",
    "review_status",
    "explanation_model",
    "explanation_generated_at",
    "manual_review_notes",
  ]) {
    question[field] = item[field];
  }
}

const data = JSON.parse(fs.readFileSync(sourceFile, "utf8").replace(/^\uFEFF/, ""));
if (data.id !== datasetId) throw new Error(`Unexpected dataset id ${data.id}`);
if (!Array.isArray(data.questions) || data.questions.length !== 100) {
  throw new Error(`Expected 100 questions, got ${data.questions?.length}`);
}

fs.mkdirSync(outDir, { recursive: true });
const updates = data.questions.map(makeUpdate);
for (let start = 1; start <= 100; start += 10) {
  const end = start + 9;
  const batch = {
    source_file: sourceFile,
    dataset_id: datasetId,
    range: { start, end },
    updates: updates.filter((item) => item.question_number >= start && item.question_number <= end),
  };
  const file = path.join(outDir, `q${String(start).padStart(3, "0")}-q${String(end).padStart(3, "0")}.json`);
  fs.writeFileSync(file, `${JSON.stringify(batch, null, 2)}\n`, "utf8");
}

for (const item of updates) {
  const question = data.questions.find((q) => q.id === item.question_id);
  if (!question) throw new Error(`Cannot find ${item.question_id}`);
  applyUpdate(question, item);
}
data.updated_at = now;
fs.writeFileSync(sourceFile, `${JSON.stringify(data, null, 2)}\n`, "utf8");

console.log(JSON.stringify({
  dataset_id: datasetId,
  source_file: sourceFile,
  update_dir: outDir,
  update_files: 10,
  merged_questions: updates.length,
  manual_review_questions: updates.filter((item) => item.manual_review_notes.length).map((item) => item.question_number),
}, null, 2));
