import json
from pathlib import Path


SOURCE_FILE = "public/data/exams/110-1/medicine-2.json"
DATASET_ID = "110-1_medicine-2"
READABLE_SOURCE = Path("scratch/rewrite_updates/110-1_medicine-2/readable_source.json")
OUT_DIR = Path("scratch/rewrite_updates/110-1_medicine-2")
STAMP = "2026-07-13T00:00:00+08:00"


FACTS = {
    1: ("金黃色葡萄球菌致病因子；題目問錯誤敘述，官方答案為 D。",
        {"A": "正確。protein A 結合 IgG Fc 端，讓補體與吞噬細胞較難辨識已被抗體包覆的細菌。",
         "B": "正確。腸毒素與 TSST-1 都可作為 superantigen，非特異性活化大量 T 細胞並造成細胞激素反應。",
         "C": "正確。exfoliative toxin 破壞表皮細胞間連結，可造成 staphylococcal scalded skin syndrome。",
         "D": "錯誤。staphylokinase 是 fibrinolysin，會分解 fibrin clot，幫助細菌擴散，不是促進 fibrin 形成。"},
        "S. aureus 的 coagulase 促進凝固，staphylokinase 則分解 fibrin；兩者方向相反。"),
    2: ("細菌 porin 的位置與功能；官方答案為 B。",
        {"A": "錯誤。porin 主要位於革蘭陰性菌外膜，不是內膜。",
         "B": "正確。porin 形成水性通道，讓小型親水分子通過外膜。",
         "C": "錯誤。endotoxin 是 LPS 的 lipid A 相關毒性，功能不同於通道蛋白。",
         "D": "錯誤。fimbriae 是附著構造，porin 是外膜通道蛋白。"},
        "革蘭陰性菌外膜的 porin 負責小型親水分子通過，和 LPS、fimbriae 不同。"),
    3: ("Listeria monocytogenes 的基本特性；官方答案為 A。",
        {"A": "正確。Listeria 是具翻滾運動性的革蘭陽性桿菌，可在細胞內存活。",
         "B": "錯誤。Listeria 是 facultative intracellular pathogen，不是 obligate intracellular pathogen。",
         "C": "錯誤。Listeria 可在低溫冷藏環境生長，是食品安全重點。",
         "D": "錯誤。主要經污染食物傳播，常見於未消毒乳品、熟食或冷藏食品，不以飛沫為主。"},
        "Listeria 是具運動性、可低溫生長的革蘭陽性桿菌，主要經食物感染。"),
    4: ("Streptococcus pyogenes 軟組織感染的臨床危險；官方答案為 C。",
        {"A": "錯誤。GAS 對 penicillin 仍通常敏感，抗藥性不是最大治療挑戰。",
         "B": "錯誤。雖然壞死性軟組織感染可混合感染，但 GAS 本身也可快速造成嚴重病變。",
         "C": "正確。壞死性筋膜炎等病變進展快，組織壞死與毒素反應可迅速導致敗血症與休克。",
         "D": "錯誤。GAS 重點不是慢性持續性感染，而是急性侵襲性進展。"},
        "GAS 軟組織感染最怕快速壞死、毒素反應與敗血症，治療需早期抗生素加外科處置。"),
    5: ("炭疽桿菌毒素組成；題目問錯誤敘述，官方答案為 B。",
        {"A": "正確。poly-D-glutamate 莢膜可抗吞噬，是重要毒力因子。",
         "B": "錯誤。protective antigen 是主要免疫原，也是疫苗與抗毒素免疫反應的重要目標，並不比 EF 或 LF 差。",
         "C": "正確。lethal factor 是 zinc metalloprotease，與 PA 組成 lethal toxin。",
         "D": "正確。edema factor 具有 adenylate cyclase 活性，與 PA 組成 edema toxin。"},
        "炭疽毒素三成分為 PA、EF、LF；PA 負責細胞結合並是重要保護性免疫原。"),
    6: ("結核分枝桿菌特性；題目問錯誤敘述，官方答案為 D。",
        {"A": "正確。細胞壁富含 mycolic acid，因此抗酸染色陽性。",
         "B": "正確。Mycobacterium 屬通常 G+C 含量偏高，高於 E. coli。",
         "C": "正確。mycolic acids 是抗酸性與細胞壁脂質性的核心。",
         "D": "錯誤。對結核的防禦以 Th1、IFN-gamma 活化巨噬細胞為主，不是 Th2 反應。"},
        "結核免疫重點是 Th1/IFN-gamma/巨噬細胞與肉芽腫反應。"),
    7: ("神奈川試驗陽性的副溶血弧菌毒力因子；官方答案為 C。",
        {"A": "錯誤。莢膜多醣不是神奈川現象的判定依據。",
         "B": "錯誤。heat-labile enterotoxin 不是此試驗的核心毒力指標。",
         "C": "正確。Kanagawa-positive 與 thermostable direct hemolysin 有關，是造成溶血與腸炎的重要因子。",
         "D": "錯誤。LPS 可參與革蘭陰性菌發炎反應，但不是神奈川試驗陽性的特異成分。"},
        "副溶血弧菌神奈川現象要聯想到 thermostable direct hemolysin。"),
    8: ("HTLV-1 與成人 T 細胞白血病；題目問錯誤敘述，官方答案為 B。",
        {"A": "正確。HTLV-1 可經血液、性接觸與母乳傳播。",
         "B": "錯誤。HTLV-1 感染者只有少數日後發展為 ATLL，不是約一半。",
         "C": "正確。ATLL 治療可包含 zidovudine 加 interferon-alpha，依病型與風險調整。",
         "D": "正確。ATLL 通常侵襲性高，預後不佳。"},
        "HTLV-1 感染常終身存在，但只有少數感染者會發展為 ATLL。"),
    9: ("反轉錄病毒科分類；題目問不屬於者，官方答案為 B。",
        {"A": "錯誤。Oncovirinae 屬於傳統反轉錄病毒分類。",
         "B": "正確。Orbivirinae 屬於 Reoviridae 相關分類，為分節雙股 RNA 病毒，非反轉錄病毒。",
         "C": "錯誤。Lentivirinae 包含 HIV，屬反轉錄病毒。",
         "D": "錯誤。Spumavirinae 為泡沫病毒，屬反轉錄病毒。"},
        "HIV 屬 Lentivirus；Orbivirus 是 Reoviridae，不屬 Retroviridae。"),
    10: ("prion 對消毒滅菌的抗性；題目問最不能去除感染力者，官方答案為 D。",
         {"A": "較有效。prion 需比一般病原更嚴格的高壓滅菌條件，長時間高壓滅菌可降低感染性。",
          "B": "較有效。高濃度次氯酸可用於 prion 污染去活化。",
          "C": "較有效。1 M NaOH 是 prion 去活化常用強處理方式。",
          "D": "最不適合。紫外線主要傷害核酸，prion 是錯誤摺疊蛋白，對 UV 相對抗性高。"},
         "prion 不靠核酸複製，對一般消毒與 UV 抗性高，需強鹼、次氯酸或嚴格高壓處理。"),
    11: ("HPV 病毒學與致癌蛋白；題目問錯誤敘述，官方答案為 C。",
         {"A": "正確。HPV 可感染皮膚與黏膜上皮。",
          "B": "正確。HPV 是無套膜雙股 DNA 病毒。",
          "C": "錯誤。E1A/E1B 是 adenovirus 的早期蛋白；HPV 致癌關鍵是 E6 抑制 p53、E7 抑制 Rb。",
          "D": "正確。HPV 16、18 是高風險型，與子宮頸癌等癌症相關。"},
         "HPV 高風險型靠 E6/E7 干擾 p53/Rb，不是 E1A/E1B。"),
    12: ("肝炎病毒傳播與基因體；題目問錯誤敘述，官方答案為 C。",
         {"A": "正確。HAV 與 HCV 都是正股 RNA 病毒。",
          "B": "正確。HBV 與 HCV 都有 envelope。",
          "C": "錯誤。HAV 與 HEV 主要經糞口傳染，不是常透過血液傳染。",
          "D": "正確。HBV 的 relaxed circular DNA 進入細胞核形成 cccDNA，並以 reverse transcription 完成複製循環。"},
         "HAV/HEV 走糞口；HBV/HCV 常與血液、體液傳播相關。"),
    13: ("HIV envelope protein；官方答案為 A。",
         {"A": "正確。gp120 是 HIV 表面 envelope glycoprotein，負責結合 CD4 與共同受體。",
          "B": "錯誤。HIV 跨膜 envelope 為 gp41，不是 gp21。",
          "C": "錯誤。p66 是 reverse transcriptase 次單元，不是 envelope protein。",
          "D": "錯誤。p55 是 Gag 前驅蛋白，不是套膜蛋白。"},
         "HIV envelope 記 gp120 負責附著，gp41 負責融合。"),
    14: ("皮癬菌屬的分生孢子特徵；官方答案為 B。",
         {"A": "錯誤。皮癬菌可透過人、人畜或環境接觸傳播。",
          "B": "正確。Epidermophyton 產生 macroconidia，但不產生 microconidia。",
          "C": "錯誤。Microsporum 常有粗糙壁 macroconidia，並非極少產生。",
          "D": "錯誤。Trichophyton 通常 microconidia 較常見，macroconidia 可少見。"},
         "Epidermophyton 的考點是不產生 microconidia。"),
    15: ("polyene 抗黴菌藥機轉；官方答案為 A。",
         {"A": "正確。amphotericin B、nystatin 等 polyenes 與 ergosterol 結合形成膜孔，造成內容物流失。",
          "B": "錯誤。14-alpha-demethylase 是 azole 類抑制目標。",
          "C": "錯誤。squalene epoxidase 是 allylamine 類如 terbinafine 的目標。",
          "D": "錯誤。1,3-beta-glucan 合成抑制是 echinocandin 類機轉。"},
         "Polyenes 直接結合 ergosterol 破壞真菌細胞膜。"),
    16: ("真菌菌絲基本型態；官方答案為 A。",
         {"A": "正確。真菌菌絲可分為有隔菌絲與無隔、多核的 coenocytic hyphae。",
          "B": "錯誤。germ tube 是 Candida albicans 等的鑑別特徵，不是菌絲基本二分型。",
          "C": "錯誤。pseudohyphae 是酵母出芽後延長的形態，不是基本菌絲分類之一。",
          "D": "錯誤。clamp connection 是擔子菌類構造，不是全部真菌菌絲的基本型態。"},
         "菌絲基本分類是 septate 與 coenocytic。"),
    17: ("百日咳疫苗組成；官方答案為 A。",
         {"A": "正確。現行常用 DTaP/Tdap 為 acellular pertussis vaccine，含純化抗原成分。",
          "B": "錯誤。LPS 不是百日咳疫苗主要組成。",
          "C": "錯誤。百日咳疫苗不是活性減毒疫苗。",
          "D": "錯誤。莢膜多醣體疫苗用於部分莢膜菌，非百日咳主要策略。"},
         "百日咳預防重點是 acellular vaccine。"),
    18: ("抗病毒免疫時序；題目問錯誤敘述，官方答案為 C。",
         {"A": "正確。病毒感染早期會誘發 type I/III interferons，使周邊細胞進入抗病毒狀態。",
          "B": "正確。NK cell 在早期辨識並殺死受感染細胞。",
          "C": "錯誤。CD8 T 細胞主要透過 TCR 辨識 MHC I 抗原後以 perforin/granzyme 或 Fas-FasL 殺傷，不是靠 ADCC；ADCC 典型由 NK cell 經 Fc receptor 執行。",
          "D": "正確。B 細胞分化為漿細胞後產生抗體，中和病毒並限制擴散。"},
         "病毒免疫：干擾素與 NK 早期上場，CD8 T 細胞靠 MHC I 抗原辨識，不是 ADCC。"),
    19: ("補體調控與 MAC；官方答案為 A。",
         {"A": "正確。CD59 抑制 C9 聚合，阻止 MAC 形成。",
          "B": "錯誤。MCP/CD46 是 factor I 的輔因子，促進 C3b/C4b 分解。",
          "C": "錯誤。DAF/CD55 加速 C3/C5 convertase 解離。",
          "D": "錯誤。C1 inhibitor 抑制 classical pathway 初始步驟。"},
         "CD59 專門擋 C9 聚合與 MAC。"),
    20: ("專業抗原呈現給 CD4 T 細胞；官方答案為 B。",
         {"A": "錯誤。MHC I 幾乎所有有核細胞表現，主要呈現給 CD8 T 細胞。",
          "B": "正確。專業 APC 大量表現 MHC II，將外源性抗原呈現給 CD4 T 細胞。",
          "C": "錯誤。MHC III 區域包含補體等基因，不是抗原呈現分子。",
          "D": "錯誤。PRR 可辨識病原模式，但不是呈現抗原給 CD4 T 細胞的主要原因。"},
         "CD4 T 細胞看 MHC II；CD8 T 細胞看 MHC I。"),
    21: ("本題資料疑似把第 21 題抗體多樣性題幹與第 22 題腫瘤免疫選項混在一起，官方答案為 D，需人工複核。",
         {"A": "若依目前選項，A 是正確的腫瘤免疫敘述：腫瘤特異抗原可誘發 cytotoxic T cells。",
          "B": "若依目前選項，B 才是不正確敘述：CTLA-4 主要表現在 T 細胞上，腫瘤常用 PD-L1 等路徑抑制 T 細胞。",
          "C": "若依目前選項，C 正確；NK cells 也能清除部分腫瘤細胞，特別是 MHC I 表現下降者。",
          "D": "若依前半抗體題幹，isotype switching 改變 Fc/constant region 與效應功能，不增加抗原結合位點多樣性；但若依目前腫瘤選項，D 是正確敘述。"},
         "本題題幹與選項疑似錯置；保留官方答案但應人工核對原始試題。", ["題幹與選項疑似混入第22題內容；官方答案 D 與目前選項邏輯不一致，需人工複核。"]),
    22: ("腫瘤免疫檢查點治療；題目問錯誤敘述，官方答案為 B。",
         {"A": "正確。腫瘤特異抗原可被 MHC 呈現並誘發專一性 CTL 反應。",
          "B": "錯誤。CTLA-4 是 T 細胞抑制性受體，不是腫瘤細胞累積突變後典型表現在腫瘤表面的分子。",
          "C": "正確。NK cell 可辨識 MHC I 下降或壓力配體表現的腫瘤細胞。",
          "D": "正確。抗 CTLA-4 或抗 PD-1/PD-L1 抗體可解除抑制訊號，增強抗腫瘤 T 細胞反應。"},
         "免疫檢查點治療是解除 T 細胞煞車；CTLA-4/PD-1 主要是 T 細胞端的抑制路徑。"),
    23: ("Fc receptor 與抗體亞型功能；題目問錯誤敘述，官方答案為 B。",
         {"A": "正確。Fc receptor 可為單鏈或多鏈複合體，並帶有訊號傳遞結構。",
          "B": "錯誤。不同抗體 isotype/subclass 對不同 Fc receptor 親和力不同，這正是功能差異來源。",
          "C": "正確。抗原結合後形成免疫複合體，更能交聯 Fc receptor 並傳遞活化或抑制訊號。",
          "D": "正確。吞噬細胞同時透過 Fc receptor 與補體受體辨識 opsonized bacteria，可增強吞噬。"},
         "抗體 Fc 區決定與 Fc receptor、補體及效應細胞的互動。"),
    24: ("黏膜抗體類型；官方答案為 B。",
         {"A": "錯誤。IgG 是血清與組織間液主要抗體，不是黏膜分泌主力。",
          "B": "正確。IgA 是黏膜與分泌液中的主要抗體，常以 dimeric secretory IgA 存在。",
          "C": "錯誤。IgM 是初次免疫反應早期抗體，非黏膜主力。",
          "D": "錯誤。IgD 主要作為初始 B 細胞受體的一部分。"},
         "黏膜免疫關鍵抗體是 secretory IgA。"),
    25: ("結核桿菌免疫逃脫；官方答案為 D。",
         {"A": "錯誤。antigenic drift 典型見於 influenza 等病毒抗原變異。",
          "B": "錯誤。gene conversion/rearrangement 不是結核菌主要免疫逃脫方式。",
          "C": "錯誤。阻斷 MHC I pathway 常見於部分病毒或腫瘤免疫逃脫。",
          "D": "正確。M. tuberculosis 可抑制 phagosome 與 lysosome 融合，使其在巨噬細胞內存活。"},
         "結核菌在巨噬細胞內存活的重點是阻止吞噬溶酶體形成。"),
    26: ("tumor immunoediting 三階段；題目問錯誤敘述，官方答案為 D。",
         {"A": "正確。免疫壓力會篩選出較能逃脫的腫瘤細胞株，表現出新的變異特性。",
          "B": "正確。腫瘤可透過失去抗原表現逃避免疫辨識。",
          "C": "正確。免疫選擇壓力會改變腫瘤細胞表型與生物特性。",
          "D": "錯誤。immunoediting 強調 elimination、equilibrium、escape；促進 T 細胞毒殺導致腫瘤縮小屬於清除效應，不是腫瘤逃脫被編輯後的典型結果。"},
         "Tumor immunoediting 是免疫系統清除並篩選腫瘤，最後可能產生免疫逃脫株。"),
    27: ("移植後 10 分鐘內排斥；官方答案為 C。",
         {"A": "錯誤。MHC I 不合可造成排斥，但 10 分鐘內發生最典型不是單純 MHC I 不合。",
          "B": "錯誤。MHC II 不合多與 T 細胞相關反應有關，時間通常較久。",
          "C": "正確。hyperacute rejection 由既存抗供者抗體造成，補體活化後迅速血栓與缺血。",
          "D": "錯誤。H antigen 不合不是此題最典型機轉。"},
         "數分鐘到數小時的超急性排斥要想到既存抗體與補體。"),
    28: ("Rituximab 標的；官方答案為 C。",
         {"A": "錯誤。CD4 T 細胞不表現 CD20，不是 rituximab 主要剔除對象。",
          "B": "錯誤。CD8 T 細胞不是 anti-CD20 主要作用細胞。",
          "C": "正確。rituximab 是 anti-CD20 monoclonal antibody，主要清除 B 細胞與 B 細胞淋巴瘤細胞。",
          "D": "錯誤。樹突細胞不是 CD20 標的治療主角。"},
         "Rituximab 等於 anti-CD20，臨床重點是 B cell depletion。"),
    29: ("生魚片後嚴重腸道症狀與低蛋白、電解質失衡；官方答案為 A。",
         {"A": "正確。Capillaria philippinensis 可因魚類感染，造成慢性腹瀉、吸收不良、低蛋白與電解質失衡。",
          "B": "錯誤。Anisakis 常造成急性胃腸道疼痛或過敏反應，不典型造成長期低蛋白與低血鉀低血鈣。",
          "C": "錯誤。Trichinella 與未熟豬肉/野味、肌痛與眼周水腫較相關。",
          "D": "錯誤。Gnathostoma 常造成移行性皮膚或內臟幼蟲移行病變，不是此典型腸道吸收不良。"},
         "生魚相關慢性腹瀉合併低蛋白與電解質失衡，要想到菲律賓毛線蟲。"),
    30: ("廣東住血線蟲；題目問錯誤敘述，官方答案為 C。",
         {"A": "正確。人體感染可引起 eosinophilic meningitis。",
          "B": "正確。若能在 CSF 找到蟲體可確診，但臨床上不一定容易找到。",
          "C": "錯誤。生菜若被中間宿主或幼蟲污染，仍可能造成感染。",
          "D": "正確。CSF 嗜酸性白血球增加是重要線索。"},
         "廣東住血線蟲與生食螺、蛞蝓或污染蔬菜相關，可造成嗜酸性腦膜炎。"),
    31: ("Echinococcus granulosus 感染；官方答案為 B。",
         {"A": "錯誤。人類通常誤食犬科動物糞便污染的蟲卵，不是吃羊肉感染。",
          "B": "正確。幼蟲可在肝臟形成 hydatid cyst。",
          "C": "錯誤。alveolar cyst 多與 E. multilocularis 相關。",
          "D": "錯誤。人類是中間宿主，通常不在糞便排出蟲卵。"},
         "E. granulosus：狗是終宿主，人誤食蟲卵後肝臟形成 hydatid cyst。"),
    32: ("寄生蟲造成腦部異位病變的可能；官方答案為 C。",
         {"A": "錯誤。日本血吸蟲蟲卵可異位到中樞造成病變。",
          "B": "錯誤。衛氏肺吸蟲可異位至腦部，造成嚴重神經症狀。",
          "C": "正確。薑片蟲主要寄生小腸，最不典型造成腦部異位病變。",
          "D": "錯誤。異形吸蟲蟲卵異位栓塞可造成中樞或心臟等病變，雖少見但比薑片蟲更相關。"},
         "薑片蟲以腸道病變為主；肺吸蟲、血吸蟲等較需留意異位中樞病變。"),
    33: ("瘧疾併發症；官方答案為 B。",
         {"A": "錯誤。P. malariae 相關腎病主要與免疫複合體沉積有關，不是大量原蟲直接沉積。",
          "B": "正確。blackwater fever 與大量溶血、血紅素尿相關，可涉及免疫性或藥物誘發溶血機轉。",
          "C": "錯誤。tropical splenomegaly syndrome 與慢性免疫刺激、IgM 增高較相關，不是單純 T 細胞大量增生。",
          "D": "錯誤。低血糖可見於重症 falciparum malaria 或 quinine 治療，不是血壓快速降低的定義。"},
         "瘧疾併發症要分清免疫複合體腎病、blackwater fever、脾腫大與低血糖。"),
    34: ("誤食受感染貓狗蚤；官方答案為 B。",
         {"A": "錯誤。犬蛔蟲經誤食含卵土壤或污染物感染，不是跳蚤中間宿主。",
          "B": "正確。Dipylidium caninum 以貓狗蚤為中間宿主，人誤食感染蚤可感染。",
          "C": "錯誤。犬鉤蟲常經皮膚侵入造成幼蟲移行，不是誤食跳蚤。",
          "D": "錯誤。菲律賓毛線蟲與食入感染魚類相關。"},
         "貓狗蚤加絛蟲要想到 Dipylidium caninum。"),
    35: ("采采蠅傳播病原；官方答案為 C。",
         {"A": "錯誤。Leishmania tropica 由白蛉傳播。",
          "B": "錯誤。Leishmania donovani 也由白蛉傳播。",
          "C": "正確。Trypanosoma brucei gambiense 經 tsetse fly 傳播，造成非洲睡眠病。",
          "D": "錯誤。Trypanosoma cruzi 由錐蝽傳播，造成 Chagas disease。"},
         "Tsetse fly 傳播 African trypanosomiasis。"),
    36: ("病例對照研究缺點；官方答案為 A。",
         {"A": "正確。病例與對照選取方式容易造成 selection bias，是病例對照研究重要限制。",
          "B": "錯誤。病例對照研究通常較省時，適合罕見疾病。",
          "C": "錯誤。相較世代研究，通常需要較少樣本。",
          "D": "錯誤。病例對照研究可同時探討多個暴露因子。"},
         "病例對照研究省時省樣本、可看多重病因，但易有選擇與回憶偏差。"),
    37: ("兩組樣本罹患率估計；題目問最不恰當，官方答案為 D。",
         {"A": "可接受。若樣本間互相傳染，獨立性假設會受影響。",
          "B": "可接受。以 42/100 估計年輕人罹患率需同分布與近似獨立假設。",
          "C": "可接受。安養中心樣本可能有群聚效應，不能簡單當作獨立樣本。",
          "D": "最不恰當。研究目的比較年輕與老年族群，直接合併成 0.32 會忽略族群結構與分層差異。"},
         "比較兩族群罹患率時應保留分層，不可任意合併成單一人口估計。"),
    38: ("信賴區間重疊與顯著差異；官方答案為 B。",
         {"A": "錯誤。A 94-98 與 B 98-106 邊界接觸，不能直接判定顯著差異。",
          "B": "正確。A 94-98 與 C 100-106 完全不重疊，最能支持兩校平均有顯著差異。",
          "C": "錯誤。B 98-106 與 D 104-108 有重疊，不能由區間直接判定顯著。",
          "D": "錯誤。C 100-106 與 D 104-108 有重疊。"},
         "以 95% CI 粗判兩組差異時，完全不重疊比有重疊更支持顯著差異。"),
    39: ("全球暖化與懸浮微粒；題目問最不恰當，官方答案為 B。",
         {"A": "正確。除水蒸氣外，CO2 是重要溫室氣體。",
          "B": "錯誤。懸浮微粒可能散射陽光造成冷卻，也可能吸收熱量，影響方向不等同 CO2，不能說一致且加成。",
          "C": "正確。全球暖化會影響熱傷害、傳染病、糧食與極端氣候健康風險。",
          "D": "正確。京都議定書重點是減少溫室氣體排放。"},
         "CO2 是典型暖化氣體；氣膠/懸浮微粒對氣候有冷卻或加熱等複雜效應。"),
    40: ("砷暴露與台灣烏腳病；題目問最不恰當，官方答案為 A。",
         {"A": "依官方答案列為不恰當；此選項可能因文字寫成「地河井水」而非地下水/深井水而有問題，但歷史上烏腳病確與西南沿海含砷地下水相關。",
          "B": "正確。砷暴露與皮膚癌、肺癌、膀胱癌、肝腎等癌症風險增加相關。",
          "C": "正確。毛髮與指甲可反映慢性砷等環境暴露。",
          "D": "正確。供應自來水後，飲用含砷地下水的風險明顯下降。"},
         "台灣烏腳病與含砷地下水是高頻考點；本題官方答案可能受選項文字瑕疵影響。", ["官方答案 A 可能是因選項文字疑似誤植；砷與西南沿海地下水/烏腳病的實質關聯仍為正確知識。"]),
    41: ("肝血管肉瘤的職業暴露；官方答案為 C。",
         {"A": "錯誤。二異氰酸甲苯較與氣喘、呼吸道刺激等職業病相關。",
          "B": "錯誤。錳暴露主要與神經毒性、類巴金森症候群相關。",
          "C": "正確。氯乙烯單體暴露典型與肝血管肉瘤相關，常見於 PVC/石化相關工業。",
          "D": "錯誤。鉛暴露主要造成血液、神經、腎臟與生殖毒性。"},
         "肝血管肉瘤要聯想到 vinyl chloride。"),
    42: ("8 小時日時量平均容許濃度定義；官方答案為 C。",
         {"A": "錯誤。48 小時、6 天不是一般 TWA 容許濃度的標準工作週。",
          "B": "錯誤。44 小時不是題目所問標準。",
          "C": "正確。8 小時 TWA 通常以每天 8 小時、每週 40 小時工作暴露為基準。",
          "D": "錯誤。42 小時不是標準設定。"},
         "職業暴露 8 小時 TWA 以每天 8 小時、每週 40 小時為基準。"),
    43: ("健康城市概念；題目問最不恰當，官方答案為 A。",
         {"A": "錯誤。健康城市是持續改進環境與治理的過程，不只是最後結果。",
          "B": "正確。行動方案應依城市自身需求與優先順序制定。",
          "C": "正確。城市間合作、學習與交流是健康城市網絡精神。",
          "D": "正確。健康城市重視公平、永續與資源分配。"},
         "健康城市是一個持續推動健康與公平的過程。"),
    44: ("行為改變階段；官方答案為 C。",
         {"A": "錯誤。懵懂期是不認為需要改變；題幹 I 已想運動，不是懵懂期。",
          "B": "錯誤。題幹 I 尚未行動，較符合沉思期而非準備期。",
          "C": "正確。I 想運動但未行動是 contemplation；II 已買器材但未規律執行是 preparation。",
          "D": "錯誤。行動期需已規律開始改變行為，II 尚未規律運動。"},
         "想改但未做是沉思期；已準備資源但未規律做是準備期。"),
    45: ("毒品防制與處遇；題目問最不恰當，官方答案為 C。",
         {"A": "正確。K 他命屬第三級毒品。",
          "B": "正確。高刺激追求、外向冒險傾向可增加嘗試物質的風險。",
          "C": "錯誤。毒品使用者不一定一律起訴，法規有觀察勒戒、戒癮治療或緩起訴等處遇設計。",
          "D": "正確。methadone 是 opioid 成癮替代療法。"},
         "毒品防制不只有刑罰，還包含戒癮治療與替代療法。"),
    46: ("媒體暴力與涵化理論；官方答案為 C。",
         {"A": "錯誤。創新擴散強調新觀念或行為如何在群體中傳播。",
          "B": "錯誤。媒體倡導是運用媒體推動政策與公共議題。",
          "C": "正確。涵化理論認為長期接觸媒體內容會形塑對社會真實的認知。",
          "D": "錯誤。知溝理論強調不同社經群體吸收資訊速度差異。"},
         "長期看媒體而把媒體世界當社會真實，是 cultivation theory。"),
    47: ("傷害防制範圍；題目問最不恰當，官方答案為 A。",
         {"A": "錯誤。傷害防制包含非蓄意與蓄意傷害，不只家暴、兒虐、自殺等蓄意傷害。",
          "B": "正確。傷害防制需要跨領域合作。",
          "C": "正確。宿主、作因、環境模式可用於分析傷害風險。",
          "D": "正確。找出事故原因並降低傷亡是傷害防制核心。"},
         "傷害防制涵蓋 intentional 與 unintentional injuries。"),
    48: ("支付制度與節約誘因；官方答案為 D。",
         {"A": "錯誤。論量計酬按服務項目支付，節約誘因最小，甚至可能誘導增加服務量。",
          "B": "錯誤。論日計酬以住院日為單位，節約誘因中等。",
          "C": "錯誤。論病例計酬以病例包裹支付，誘因比論量大但仍小於論人。",
          "D": "正確。論人計酬以人頭為基準，提供者需管理整體成本，節約誘因最大。"},
         "支付單位越大、越包裹，提供者節約誘因越強；論人計酬最大。"),
    49: ("WHO 功能；題目問最不恰當，官方答案為 B。",
         {"A": "正確。世界衛生大會是 WHO 最高決策機構。",
          "B": "錯誤。WHO 重要功能包含技術合作、規範制定、監測與協調國際衛生。",
          "C": "正確。WHO 是聯合國體系內衛生專門機構。",
          "D": "正確。經費與效率問題常被視為 WHO 組織挑戰。"},
         "WHO 角色包含國際衛生規範、監測、協調與技術合作。"),
    50: ("平衡計分卡；題目問最不恰當，官方答案為 C。",
         {"A": "正確。BSC 目的在將策略轉成可衡量行動與指標。",
          "B": "正確。典型四構面為財務、顧客、內部流程、學習與成長。",
          "C": "錯誤。財務構面多屬落後指標，反映過去成果；流程與學習成長較常是領先指標。",
          "D": "正確。非營利組織可依使命與治理需求調整或新增構面。"},
         "BSC 中財務多為結果/落後指標，不是典型領先指標。"),
    51: ("HLA-B*5701 與藥物過敏；官方答案為 C。",
         {"A": "錯誤。amoxicillin 過敏不以 HLA-B*5701 篩檢為常規。",
          "B": "錯誤。carbamazepine 重要基因是 HLA-B*1502 或 HLA-A*3101，依族群而定。",
          "C": "正確。abacavir 使用前需檢測 HLA-B*5701，以避免嚴重過敏反應。",
          "D": "錯誤。allopurinol 嚴重皮膚反應常與 HLA-B*5801 相關。"},
         "Abacavir 對應 HLA-B*5701；allopurinol 對應 HLA-B*5801。"),
    52: ("青黴素類抗生素特性；官方答案為 C。",
         {"A": "錯誤。ampicillin 吸收會受食物影響，amoxicillin 口服吸收較佳。",
          "B": "錯誤。dicloxacillin 抗酸且耐 penicillinase，吸收差不是因酸性不穩定。",
          "C": "正確。amoxicillin 抗藥性常來自 beta-lactamase，可與 clavulanate 併用克服部分抗藥性。",
          "D": "錯誤。nafcillin 主要經肝膽排泄，腎排泄不是主要途徑。"},
         "Amoxicillin 常因 beta-lactamase 失效；nafcillin 主要肝膽排泄。"),
    53: ("單株抗體腫瘤治療；官方答案為 C。",
         {"A": "錯誤。alemtuzumab 抗 CD52，會造成明顯淋巴球減少與感染風險。",
          "B": "錯誤。bevacizumab 抗 VEGF，會影響傷口癒合，通常不適合術後立即投藥。",
          "C": "正確。catumaxomab 是 bispecific/trifunctional antibody，可連結腫瘤 EpCAM 與 T cell CD3。",
          "D": "錯誤。cetuximab 阻斷 EGFR；ramucirumab 阻斷 VEGFR2，不是同樣阻斷 EGFR。"},
         "Catumaxomab 可同時橋接腫瘤細胞與 T 細胞。"),
    54: ("topoisomerase II 抑制抗癌藥；官方答案為 C。",
         {"A": "錯誤。busulfan 是 alkylating agent，常用於骨髓移植前處置。",
          "B": "錯誤。cyclophosphamide 是 alkylating agent。",
          "C": "正確。idarubicin 是 anthracycline，可抑制 topoisomerase II 並造成 DNA 斷裂。",
          "D": "錯誤。methotrexate 抑制 dihydrofolate reductase，影響葉酸代謝。"},
         "Anthracyclines 如 doxorubicin、idarubicin 可抑制 topoisomerase II。"),
    55: ("CMF 與 pyrimidine 類似物；官方答案為 A。",
         {"A": "正確。5-FU 是 pyrimidine analog，代謝物 FdUMP 抑制 thymidylate synthase。",
          "B": "錯誤。cytarabine 是 cytidine analog，主要用於 AML 等，非 CMF 乳癌標準成分。",
          "C": "錯誤。methotrexate 是 antifolate，CMF 成分之一但不是 pyrimidine 類似物。",
          "D": "錯誤。vincristine 是 vinca alkaloid，抑制微小管聚合。"},
         "CMF 包含 cyclophosphamide、methotrexate、5-fluorouracil；5-FU 抑制 thymidylate synthase。"),
    56: ("Sumatriptan 機轉與禁忌；題目問錯誤敘述，官方答案為 A。",
         {"A": "錯誤。sumatriptan 是 5-HT1B/1D agonist，不是 antagonist。",
          "B": "正確。與 SSRI/SNRI 等併用需注意 serotonin syndrome 風險。",
          "C": "正確。因會造成血管收縮，冠狀動脈疾病病人禁用或避免使用。",
          "D": "正確。5-HT1B/1D 活化可使顱內血管收縮並抑制三叉神經胜肽釋放。"},
         "Triptans 是 5-HT1B/1D agonists，禁用於冠心病等血管收縮高風險者。"),
    57: ("Fenofibrate 機轉；題目問錯誤敘述，官方答案為 D。",
         {"A": "正確。fibrate 類增加脂肪酸氧化，降低三酸甘油脂。",
          "B": "正確。fenofibrate 活化 PPAR-alpha。",
          "C": "正確。副作用包含肌肉病變、肝功能異常，與 statin 併用需小心。",
          "D": "錯誤。fibrate 會增加 lipoprotein lipase 活性，不是抑制。"},
         "Fibrates 活化 PPAR-alpha，上升 LPL、下降 TG。"),
    58: ("EPO 藥理與訊號；題目問錯誤敘述，官方答案為 C。",
         {"A": "正確。darbepoetin alfa 是長效 EPO 類似物。",
          "B": "正確。EPO 類藥物可能造成高血壓與血栓風險。",
          "C": "錯誤。EPO receptor 主要透過 JAK2/STAT 訊號促進紅血球生成；ERK 可為下游之一但不是主要考點描述。",
          "D": "正確。EPO 刺激紅血球前驅細胞增殖與分化。"},
         "EPO 受體典型訊號是 JAK2/STAT，臨床副作用注意高血壓與血栓。"),
    59: ("Desmopressin 促凝血機轉；官方答案為 B。",
         {"A": "錯誤。促進 plasminogen 活化會偏向纖溶，不是促凝血。",
          "B": "正確。desmopressin 促進 vWF 與 factor VIII 釋放，可用於輕型 hemophilia A 或 vWD。",
          "C": "錯誤。desmopressin 作用於 V2 receptor 增加 cAMP 訊號，不是增加 cAMP 分解。",
          "D": "錯誤。ADP receptor 是血小板抗血栓藥如 clopidogrel 的標的。"},
         "DDAVP 促進 vWF 與 factor VIII 釋放。"),
    60: ("甲狀腺機能亢進用藥；題目問不適合者，官方答案為 B。",
         {"A": "適合。PTU 抑制甲狀腺素合成，也抑制 T4 轉 T3。",
          "B": "不適合。levothyroxine 是 T4 補充，會加重甲狀腺亢進。",
          "C": "適合。Lugol's solution 可短期抑制甲狀腺素釋放，常用於特定情境。",
          "D": "適合。propranolol 可控制心悸、手抖等交感症狀，也部分抑制 T4 轉 T3。"},
         "甲亢治療避免補充 T4；症狀控制可用 beta blocker。"),
    61: ("第一型糖尿病用藥；官方答案為 C。",
         {"A": "錯誤。SGLT2 inhibitor 不是第一型糖尿病基本治療，且有 ketoacidosis 風險。",
          "B": "錯誤。DPP-4 inhibitor 主要用於第二型糖尿病。",
          "C": "正確。第一型糖尿病是絕對胰島素缺乏，必須使用 insulin。",
          "D": "錯誤。glipizide 需刺激殘存 beta cell 分泌胰島素，不適合第一型糖尿病作為核心治療。"},
         "第一型糖尿病治療核心是胰島素。"),
    62: ("類固醇適應症與不適合情境；官方答案為 C。",
         {"A": "適合。Addison disease 需要補充糖皮質與鹽皮質素。",
          "B": "適合。IBD 急性發作可用類固醇控制發炎。",
          "C": "不適合。消化性潰瘍可能因類固醇、NSAID 等風險而惡化，不是治療主軸。",
          "D": "適合。氣喘急性或控制不佳時可使用吸入或全身性類固醇。"},
         "類固醇可抗發炎與替代治療，但消化性潰瘍不是適應症且可能加重風險。"),
    63: ("D1 dopamine receptor agonist 降血壓藥；官方答案為 C。",
         {"A": "錯誤。clonidine 是 alpha-2 agonist，降低交感輸出。",
          "B": "錯誤。diazoxide 是血管平滑肌 KATP channel opener。",
          "C": "正確。fenoldopam 是 D1 receptor agonist，使腎與周邊血管擴張，可用於高血壓急症。",
          "D": "錯誤。ketanserin 主要拮抗 5-HT2 受體，也有 alpha-1 阻斷作用。"},
         "Fenoldopam 是 D1 agonist，可擴張腎血管與降血壓。"),
    64: ("Acetazolamide；官方答案為 B。",
         {"A": "錯誤。acetazolamide 作用於近曲小管，抑制 carbonic anhydrase。",
          "B": "正確。可降低房水生成，用於青光眼，也可用於高山症等。",
          "C": "錯誤。耳毒性較典型見於 loop diuretics。",
          "D": "錯誤。會增加碳酸氫鹽排出並可造成代謝性酸中毒，血鉀多偏低而非高血鉀。"},
         "Acetazolamide 是近曲小管 carbonic anhydrase inhibitor，可用於青光眼。"),
    65: ("alpha-1 交感受體反應；題目問錯誤敘述，官方答案為 A。",
         {"A": "錯誤。alpha-1 主要使膀胱頸與括約肌收縮；逼尿肌收縮主要是 muscarinic M3。",
          "B": "正確。豎毛肌收縮屬 alpha-1 反應。",
          "C": "正確。alpha-1 造成多數血管平滑肌收縮，包括骨骼肌血管。",
          "D": "可接受。心肌以 beta-1 為主，但 alpha-1 也可有正性肌力作用；本題最明確錯誤為逼尿肌收縮。"},
         "Alpha-1 記血管、瞳孔放大肌、括約肌與豎毛肌收縮；逼尿肌是 M3。"),
    66: ("長效吸入型 antimuscarinic；官方答案為 C。",
         {"A": "錯誤。tropicamide 常用於散瞳，作用短。",
          "B": "錯誤。ipratropium 是短效吸入型 muscarinic antagonist。",
          "C": "正確。tiotropium 是長效吸入型 muscarinic antagonist，不易通過 BBB，適用 COPD，半衰期長。",
          "D": "錯誤。benztropine 可進入中樞，用於巴金森症或錐體外副作用。"},
         "COPD 長效吸入抗膽鹼藥首選記 tiotropium。"),
    67: ("短效吸入型 beta-2 agonist；官方答案為 A。",
         {"A": "正確。albuterol 是 SABA，吸入後主要作用於肺部，起效快且全身生體可用率低。",
          "B": "錯誤。montelukast 是 leukotriene receptor antagonist，非計量吸入器急救支氣管擴張藥。",
          "C": "錯誤。flunisolide 是吸入型類固醇，抗發炎但非短效支氣管擴張。",
          "D": "錯誤。tiotropium 是長效抗 muscarinic 藥，多用於 COPD。"},
         "Albuterol 是短效 beta-2 agonist，吸入急救支氣管擴張。"),
    68: ("H2 blocker 強度；官方答案為 D。",
         {"A": "錯誤。cimetidine 較早期、效力較弱且藥物交互作用多。",
          "B": "錯誤。ranitidine 效力高於 cimetidine，但不是最強。",
          "C": "錯誤。nizatidine 類似 ranitidine，非最強。",
          "D": "正確。famotidine 在常見 H2 blockers 中抑酸效力較強。"},
         "H2 blocker 效力常記 famotidine 較強、cimetidine 較弱。"),
    69: ("MT1/MT2 agonist 失眠用藥；官方答案為 A。",
         {"A": "正確。tasimelteon 是 melatonin MT1/MT2 receptor agonist，可調節睡醒節律。",
          "B": "錯誤。sumatriptan 是 5-HT1B/1D agonist，用於偏頭痛。",
          "C": "錯誤。repinotan 是 5-HT1A agonist 研究藥物，非本題重點失眠藥。",
          "D": "錯誤。orlistat 抑制腸道 lipase，用於減重。"},
         "Tasimelteon/ramelteon 類藥物作用於 melatonin MT1/MT2。"),
    70: ("開放性青光眼用藥；官方答案為 B。",
         {"A": "錯誤。alprostadil 是 PGE1 類似物，用於維持 PDA 或勃起功能障礙等。",
          "B": "正確。latanoprost 是 PGF2-alpha 類似物，增加葡萄膜鞏膜房水外流，是開放性青光眼常用藥。",
          "C": "錯誤。misoprostol 是 PGE1 類似物，用於胃保護或產科用途。",
          "D": "錯誤。dinoprostone 是 PGE2，用於子宮頸成熟/引產。"},
         "Latanoprost 增加房水外流，是開放性青光眼高頻用藥。"),
    71: ("慢性高尿酸血症治療；官方答案為 D。",
         {"A": "錯誤。tramadol 是止痛藥，不降低尿酸。",
          "B": "錯誤。rilonacept 抑制 IL-1，可用於特定發炎症候群或痛風發作預防情境，不是慢性降尿酸主軸。",
          "C": "錯誤。ketorolac 是 NSAID，可緩解急性痛風疼痛但不治療慢性高尿酸。",
          "D": "正確。febuxostat 抑制 xanthine oxidase，降低尿酸生成。"},
         "慢性高尿酸血症要降尿酸，febuxostat/allopurinol 抑制 xanthine oxidase。"),
    72: ("抗精神病藥 EPS 風險；官方答案為 A。",
         {"A": "正確。haloperidol 是高效價典型抗精神病藥，D2 阻斷強，EPS 明顯。",
          "B": "錯誤。clozapine EPS 較少，但有 agranulocytosis、癲癇、代謝副作用等。",
          "C": "錯誤。olanzapine 為非典型藥，EPS 少於 haloperidol，代謝副作用較重要。",
          "D": "錯誤。aripiprazole 是 D2 partial agonist，EPS 通常較低。"},
         "高效價典型抗精神病藥 haloperidol 最容易考 EPS。"),
    73: ("精神依賴性；官方答案為 D。",
         {"A": "錯誤。cocaine 強烈增強 dopamine reward pathway，精神依賴性高。",
          "B": "錯誤。psilocybin 可造成幻覺與心理使用風險，雖生理依賴低但仍非解毒劑。",
          "C": "錯誤。ketamine 有濫用與心理依賴風險。",
          "D": "正確。naloxone 是 opioid receptor antagonist，用於 opioid overdose，不造成欣快感或心理依賴。"},
         "Naloxone 是鴉片類解毒劑，不是成癮性欣快藥。"),
    74: ("Buspirone 機轉；題目問錯誤敘述，官方答案為 B。",
         {"A": "正確。buspirone 沒有 benzodiazepine 典型抗癲癇或肌肉鬆弛作用。",
          "B": "錯誤。buspirone 主要是 5-HT1A partial agonist，不作用於 GABAA receptor。",
          "C": "正確。相較 benzodiazepines，不明顯增強酒精中樞抑制。",
          "D": "正確。抗焦慮效果需數週才明顯，不適合急性焦慮快速緩解。"},
         "Buspirone 是 5-HT1A partial agonist，慢起效、少鎮靜與依賴。"),
    75: ("Beta blocker 過量解毒；官方答案為 A。",
         {"A": "正確。glucagon 可經 cAMP 路徑增加心肌收縮與心率，繞過 beta receptor。",
          "B": "錯誤。atropine 可處理部分 bradycardia，但對 beta blocker 中毒低血壓效果有限。",
          "C": "錯誤。digoxin 會增加心律不整風險，不是 propranolol 中毒解毒劑。",
          "D": "錯誤。pralidoxime 用於有機磷中毒。"},
         "Beta blocker 中毒造成低血壓、心搏過慢時，glucagon 是經典解毒選項。"),
    76: ("類纖維蛋白性壞死；官方答案為 C。",
         {"A": "錯誤。結核典型是乾酪性壞死與肉芽腫。",
          "B": "錯誤。腦梗塞典型是液化性壞死。",
          "C": "正確。血管炎或免疫複合體沉積造成血管壁損傷，常見 fibrinoid necrosis。",
          "D": "錯誤。急性胰臟炎常見脂肪壞死與酵素性壞死。"},
         "Fibrinoid necrosis 常考血管炎、惡性高血壓與免疫複合體血管壁傷害。"),
    77: ("肉芽組織組織學；官方答案為 B。",
         {"A": "錯誤。granuloma 是巨噬細胞/類上皮細胞聚集，常見於慢性肉芽腫發炎。",
          "B": "正確。granulation tissue 由新生微血管、纖維母細胞、疏鬆基質與發炎細胞組成，是傷口修復特徵。",
          "C": "錯誤。keloid 是過度膠原沉積形成隆起疤痕。",
          "D": "錯誤。amyloid 是異常蛋白沉積。"},
         "傷口癒合早期的肉芽組織等於新生血管加纖維母細胞。"),
    78: ("SLE 病理；官方答案為 B。",
         {"A": "錯誤。SLE 腎病主要是免疫複合體沉積，不是抗 GBM 抗體為主。",
          "B": "正確。SLE 可有急性血管炎與 fibrinoid necrosis。",
          "C": "錯誤。皮膚病變重點是免疫複合體沉積於 dermoepidermal junction，不是鱗狀細胞膜周圍造成水泡。",
          "D": "錯誤。wire-loop lesion 典型見於 diffuse proliferative lupus nephritis，不是 membranous 型典型變化。"},
         "SLE 是免疫複合體疾病，腎臟 wire-loop 多屬增生型狼瘡腎炎。"),
    79: ("鏈球菌相關病變；官方答案為 B。",
         {"A": "會引起。肺炎鏈球菌是大葉性肺炎典型病原。",
          "B": "較少引起。壞死性腸炎常與 Clostridium perfringens 等相關，不是鏈球菌典型病變。",
          "C": "會引起。猩紅熱由產紅疹毒素的 S. pyogenes 引起。",
          "D": "會引起。鏈球菌感染後可造成急性腎小球腎炎。"},
         "鏈球菌常考大葉性肺炎、猩紅熱、風濕熱與感染後腎炎；壞死性腸炎不是典型。"),
    80: ("Aflatoxin B1 致癌機轉；官方答案為 D。",
         {"A": "錯誤。MYC 不是 aflatoxin B1 最典型突變標的。",
          "B": "錯誤。RAS 不是本題高頻連結。",
          "C": "錯誤。RB 與視網膜母細胞瘤等較相關。",
          "D": "正確。aflatoxin B1 常造成 TP53 mutation，與肝細胞癌風險增加相關。"},
         "Aflatoxin B1 加 HBV 是肝癌考點，分子標的是 TP53。"),
    81: ("造血惡性腫瘤活化致癌基因的核型改變；官方答案為 A。",
         {"A": "正確。染色體轉位常見於白血病/淋巴瘤，如 BCR-ABL、MYC、BCL2。",
          "B": "錯誤。deletion 常造成 tumor suppressor loss，不是最常活化 oncogene 的方式。",
          "C": "錯誤。gene amplification 可活化 oncogene，但在造血系統惡性腫瘤最典型不如 translocation。",
          "D": "錯誤。aneuploidy 是染色體數目異常，非最典型活化特定 oncogene 的方式。"},
         "血液腫瘤活化 oncogene 最常考 chromosomal translocation。"),
    82: ("乳糜胸水；官方答案為 B。",
         {"A": "錯誤。心衰竭胸水多為漏出液，不是乳白色高三酸甘油脂。",
          "B": "正確。淋巴管或胸管阻塞/破裂可造成 chylous pleural effusion，胸水乳白且 TG 高。",
          "C": "錯誤。肺梗塞可造成血性或滲出性胸水，但非典型乳糜胸。",
          "D": "錯誤。下腔靜脈阻塞不是乳白高 TG 胸水最可能原因。"},
         "乳白胸水加高 triglyceride 代表乳糜胸，想到淋巴/胸管阻塞。"),
    83: ("二尖瓣環鈣化；題目問錯誤敘述，官方答案為 A。",
         {"A": "錯誤。退化性二尖瓣鈣化多在 mitral annulus，特別後瓣環，不是最容易在 commissure。",
          "B": "正確。多數 mitral annular calcification 無明顯瓣膜功能異常。",
          "C": "正確。鈣化不平整可增加感染性心內膜炎風險。",
          "D": "正確。局部鈣化與心內膜表面不規則可增加血栓形成機會。"},
         "老人退化性二尖瓣鈣化重點是 annulus，不是 commissure。"),
    84: ("慢性 ITP；官方答案為 B。",
         {"A": "錯誤。慢性 ITP 較常見於年輕至中年女性，不是好發 60 歲以上老年女性。",
          "B": "正確。血漿中有抗血小板自體抗體，導致脾臟破壞血小板。",
          "C": "錯誤。骨髓巨核細胞通常正常或增加，反映代償性生成。",
          "D": "錯誤。多數病人對 glucocorticoid 或免疫抑制治療有反應。"},
         "ITP 是抗血小板抗體造成周邊破壞，骨髓巨核細胞不會顯著減少。"),
    85: ("CLL 免疫表現；官方答案為 C。",
         {"A": "錯誤。CLL/SLL 是成熟 B 細胞腫瘤。",
          "B": "錯誤。好發於老年人，不是 20 歲以下。",
          "C": "正確。典型表現 CD20、CD5、CD23，並可見 smudge cells。",
          "D": "錯誤。BCL2 translocation t(14;18) 典型為 follicular lymphoma。"},
         "CLL 是老年 B 細胞腫瘤，免疫表現 CD5、CD23 陽性。"),
    86: ("鼻咽癌病理；官方答案為 D。",
         {"A": "錯誤。WHO 分類重點為 keratinizing、non-keratinizing differentiated/undifferentiated 等，非分化不良型腺癌。",
          "B": "可作輔助。EBER 原位雜交可偵測 EBV，對非角化型鼻咽癌很有用，但診斷仍需整合形態與免疫/病毒檢測。",
          "C": "錯誤。組織型態與放射治療反應及預後有關。",
          "D": "正確。角化型鱗狀上皮癌通常較非角化型對放射治療反應差。"},
         "鼻咽癌常與 EBV 相關；非角化型通常較 radiosensitive。"),
    87: ("肺氣腫 elastin 破壞來源；官方答案為 A。",
         {"A": "正確。嗜中性球 elastase 是破壞肺泡壁 elastin 的重要蛋白酶，alpha-1 antitrypsin 可抑制它。",
          "B": "錯誤。淋巴球不是 elastase 主要來源。",
          "C": "錯誤。嗜酸性球與氣喘、過敏、寄生蟲較相關。",
          "D": "錯誤。嗜鹼性球與過敏反應介質較相關。"},
         "肺氣腫核心是 protease-antiprotease imbalance，重點 protease 來自嗜中性球。"),
    88: ("原發性纖毛運動障礙肺部疾病；官方答案為 A。",
         {"A": "依官方答案列為正確，但 PCD 更典型造成反覆感染與支氣管擴張；慢性支氣管炎可因黏液清除差而出現慢性咳痰。",
          "B": "本選項在標準病理學中也很典型：纖毛運動障礙導致黏液清除不良、反覆感染，常造成 bronchiectasis。",
          "C": "錯誤。氣喘是可逆性氣道高反應與發炎，不是 PCD 典型主要後果。",
          "D": "錯誤。肺氣腫主要與吸菸、alpha-1 antitrypsin deficiency 等相關。"},
         "PCD 造成黏液清除不良、反覆呼吸道感染；官方答案與常見 bronchiectasis 教材重點需核對。", ["官方答案 A 可能與常見教科書重點 B（支氣管擴張）有落差，建議人工核對原始答案。"]),
    89: ("DNA 肝炎病毒；官方答案為 B。",
         {"A": "錯誤。HAV 是正股 RNA 病毒。",
          "B": "正確。HBV 是部分雙股環狀 DNA 病毒，屬 Hepadnaviridae。",
          "C": "錯誤。HCV 是正股 RNA 病毒。",
          "D": "錯誤。HDV 是缺陷 RNA 病毒，需 HBV envelope 協助。"},
         "肝炎病毒中 HBV 是 DNA virus，且複製過程用 reverse transcriptase。"),
    90: ("偽膜性腸炎診斷；題目問錯誤敘述，官方答案為 D。",
         {"A": "正確。常與抗生素使用後腸道菌相改變有關。",
          "B": "正確。典型病原是 Clostridioides difficile。",
          "C": "正確。偽膜由壞死碎屑、黏蛋白、纖維素與嗜中性球等形成。",
          "D": "錯誤。診斷多用糞便毒素或 NAAT/抗原檢測，通常不靠細菌培養作常規診斷。"},
         "C. difficile 腸炎靠毒素/NAAT 等檢測，不是例行細菌培養。"),
    91: ("胃癌分類與危險因子；題目問錯誤敘述，官方答案為 C。",
         {"A": "正確。胃癌有明顯地域差異，日本等地發生率較高。",
          "B": "正確。家族性 diffuse gastric cancer 與 CDH1/E-cadherin 突變相關。",
          "C": "錯誤。H. pylori 與 intestinal type gastric cancer 關係較密切；diffuse type 更常與 CDH1 相關。",
          "D": "正確。發炎相關基因多型性可影響 H. pylori 相關胃癌風險。"},
         "H. pylori 主要連到 intestinal type 胃癌；CDH1 連到 diffuse type。"),
    92: ("外因性皮質醇過多對腎上腺；官方答案為 A。",
         {"A": "正確。外源性 glucocorticoid 抑制 ACTH，造成雙側腎上腺皮質萎縮。",
          "B": "錯誤。瀰漫性增生見於 ACTH 長期刺激。",
          "C": "錯誤。微結節性增生不是外因性皮質醇過多典型變化。",
          "D": "錯誤。巨結節性增生也屬內源性刺激或特定增生病變。"},
         "外源性類固醇會負回饋抑制 ACTH，腎上腺皮質萎縮。"),
    93: ("黃色肉芽腫性腎盂腎炎病原；官方答案為 A。",
         {"A": "正確。Proteus 常與尿路結石與慢性阻塞感染相關，是常見病原。",
          "B": "錯誤。腸球菌可造成尿路感染，但不是本病最典型常見病原。",
          "C": "錯誤。Klebsiella 可造成尿路感染，但相較 Proteus 不是本題最佳答案。",
          "D": "錯誤。S. aureus 不是 xanthogranulomatous pyelonephritis 最常見病原。"},
         "Xanthogranulomatous pyelonephritis 常與慢性阻塞、結石、Proteus/E. coli 感染相關。"),
    94: ("甲狀腺髓質癌來源與基質；官方答案為 B。",
         {"A": "錯誤。來源 C cell 正確，但砂樣小體較典型見於乳突癌。",
          "B": "正確。medullary carcinoma 來自 parafollicular C cells，間質常見 calcitonin 相關 amyloid deposits。",
          "C": "錯誤。濾泡細胞來源是乳突癌、濾泡癌等，不是髓質癌。",
          "D": "錯誤。類澱粉沉積正確，但來源不是濾泡細胞。"},
         "Medullary thyroid carcinoma：C cell、calcitonin、amyloid、MEN2/RET。"),
    95: ("卵巢性索間質瘤；題目問較不正確，官方答案為 A。",
         {"A": "錯誤。成人型顆粒細胞瘤屬低度惡性、可復發，不能簡單視為良性腫瘤。",
          "B": "正確。顆粒細胞瘤可分泌 estrogen，造成子宮內膜增生與相關乳房病變。",
          "C": "正確。Sertoli-Leydig cell tumor 可分泌 androgen，導致男性化或去女性化。",
          "D": "正確。相當比例 Sertoli-Leydig cell tumor 與 DICER1 mutation 相關。"},
         "成人型 granulosa cell tumor 可分泌 estrogen，且具低度惡性潛能。"),
    96: ("睪丸與附睪發炎；題目問較不正確，官方答案為 B。",
         {"A": "正確。附睪炎比單純睪丸炎常見。",
          "B": "錯誤。結核性病變通常先侵犯附睪，再延伸至睪丸。",
          "C": "正確。淋病等上行感染常先造成附睪炎。",
          "D": "正確。梅毒較可直接侵犯睪丸造成睪丸炎或 gumma。"},
         "結核與淋病多先附睪；梅毒較常先睪丸。"),
    97: ("三歲以下最常見睪丸腫瘤；官方答案為 B。",
         {"A": "錯誤。seminoma 典型見於較年長成人，不是三歲以下最常見。",
          "B": "正確。yolk sac tumor 是兒童尤其三歲以下常見睪丸腫瘤，AFP 可上升。",
          "C": "錯誤。choriocarcinoma 少見且高度惡性，可分泌 hCG。",
          "D": "錯誤。embryonal carcinoma 多見於年輕成人混合生殖細胞腫瘤。"},
         "幼兒睪丸腫瘤高頻答案是 yolk sac tumor，常見 AFP 上升。"),
    98: ("骨肉瘤分子與病理；題目問錯誤敘述，官方答案為 A。",
         {"A": "錯誤。low-grade osteosarcoma 常見 12q13-q15 amplification，涉及 MDM2/CDK4，不是 MYC 過度表現。",
          "B": "正確。原發性骨肉瘤好發於青少年長骨 metaphysis。",
          "C": "正確。Li-Fraumeni syndrome 的 germline TP53 mutation 會增加骨肉瘤風險。",
          "D": "正確。診斷關鍵是惡性腫瘤細胞產生 osteoid。"},
         "骨肉瘤診斷看 malignant osteoid；low-grade 型常考 MDM2/CDK4 amplification。"),
    99: ("阿茲海默症主要病理；官方答案為 A。",
         {"A": "正確。neuritic plaques 與 neurofibrillary tangles 是 Alzheimer disease 主要病理變化。",
          "B": "錯誤。nemaline rods 見於 nemaline myopathy，不是 AD。",
          "C": "錯誤。雖含 tangle，但 nemaline rods 錯。",
          "D": "錯誤。Lewy body 是 Parkinson disease、Lewy body dementia 等重點，不是 AD 主要二聯。"},
         "AD 病理記 beta-amyloid neuritic plaques 與 tau neurofibrillary tangles。"),
    100: ("HSV-1 腦炎病理；題目問較不可能，官方答案為 D。",
          {"A": "可見。HSV 感染可有 Cowdry type A intranuclear inclusions。",
           "B": "可見。病毒性腦炎常見 perivascular lymphocytic cuffing。",
           "C": "可見。microglial nodules 是病毒性腦炎常見反應之一。",
           "D": "較不可能。caseous necrotizing granuloma 典型與結核等肉芽腫感染相關，不是 HSV-1 腦炎典型病理。"},
          "HSV-1 腦炎是壞死性病毒性腦炎，見 Cowdry A、淋巴球 cuffing、microglial nodules；乾酪性肉芽腫屬結核。"),
}


def build_explanation(task, reasons, core):
    return (
        "【題幹解析】\n"
        f"{task} 解題時先判斷題目是在問正確或錯誤，再把病原、免疫機轉、藥理作用或病理特徵對回各選項。\n\n"
        "【選項詳解】\n"
        f"- A. {reasons['A']}\n"
        f"- B. {reasons['B']}\n"
        f"- C. {reasons['C']}\n"
        f"- D. {reasons['D']}\n\n"
        "【核心考點】\n"
        f"{core}"
    )


def main():
    data = json.loads(READABLE_SOURCE.read_text(encoding="utf-8"))
    questions = data["questions"]
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    for start in range(1, 101, 10):
        end = start + 9
        updates = []
        for q in questions[start - 1:end]:
            qnum = q["question_number"]
            item = FACTS[qnum]
            if len(item) == 4:
                task, reasons, core, notes = item
            else:
                task, reasons, core = item
                notes = []
            updates.append(
                {
                    "question_id": q["id"],
                    "question_number": qnum,
                    "explanation": build_explanation(task, reasons, core),
                    "key_point": core,
                    "flashcard_front": task.split("；")[0],
                    "flashcard_back": core,
                    "flashcard_summary": f"{task.split('；')[0]} -> {core}",
                    "review_status": "ai_generated",
                    "explanation_model": "codex-high-quality-rewrite",
                    "explanation_generated_at": STAMP,
                    "manual_review_notes": notes,
                }
            )
        payload = {
            "source_file": SOURCE_FILE,
            "dataset_id": DATASET_ID,
            "range": {"start": start, "end": end},
            "updates": updates,
        }
        (OUT_DIR / f"q{start:03d}-q{end:03d}.json").write_text(
            json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )


if __name__ == "__main__":
    main()
