import json
from pathlib import Path


SOURCE_FILE = "public/data/exams/109-2/medicine-3.json"
DATASET_ID = "109-2_medicine-3"
OUT_DIR = Path("scratch/rewrite_updates/109-2_medicine-3")
STAMP = "2026-07-19T23:20:00+08:00"


def load_questions():
    data = json.loads(Path(SOURCE_FILE).read_text(encoding="utf-8-sig"))
    return data["questions"]


def make_explanation(stem, details, core):
    return (
        "【題幹解析】\n"
        + stem.strip()
        + "\n\n【選項詳解】\n"
        + "\n".join(f"- {letter}. {text.strip()}" for letter, text in details.items())
        + "\n\n【核心考點】\n"
        + core.strip()
    )


def update(qnum, stem, details, core, key_point, front, back, summary=None, notes=None):
    return {
        "question_id": f"{DATASET_ID}_{qnum:03d}",
        "question_number": qnum,
        "explanation": make_explanation(stem, details, core),
        "key_point": key_point,
        "flashcard_front": front,
        "flashcard_back": back,
        "flashcard_summary": summary or f"{front} -> {back}",
        "review_status": "ai_generated",
        "explanation_model": "codex-high-quality-rewrite",
        "explanation_generated_at": STAMP,
        "manual_review_notes": notes or [],
    }


UPDATES = [
    update(
        1,
        "年輕男性突發下肢無力，血鉀 2.0 mEq/L 且尿鉀只有 10 mEq/L，重點不是腎臟漏鉀，而是鉀離子往細胞內移動。亞洲男性出現低血鉀週期性麻痺時，要想到甲狀腺毒性週期性麻痺（thyrotoxic periodic paralysis），因此應加驗甲狀腺功能。",
        {
            "A": "TTKG = 尿鉀 10 x 血漿滲透壓 290 / 血鉀 2.0 / 尿滲透壓 580，約為 2.5，不是 2.0。",
            "B": "尿鉀偏低代表腎臟正在保留鉀，與腎臟排鉀過多不合。",
            "C": "低血鉀麻痺合併低尿鉀排出，尤其在年輕男性，應檢查 TSH、free T4 以排除甲狀腺毒性週期性麻痺。",
            "D": "補鉀不宜加在葡萄糖水，葡萄糖誘發胰島素分泌會讓鉀更往細胞內移動；周邊靜脈濃度限制本身不是本題陷阱。",
        },
        "低血鉀先看尿鉀：尿鉀低表示體內轉移或腸胃流失，年輕男性突發麻痺要想到甲狀腺毒性週期性麻痺。",
        "低血鉀麻痺合併低尿鉀時，年輕男性要加驗甲狀腺功能。",
        "低血鉀麻痺與尿鉀",
        "尿鉀低代表非腎性流失或細胞內轉移；亞洲年輕男性突發麻痺要排除 thyrotoxic periodic paralysis。",
    ),
    update(
        2,
        "篩檢適合用在重要、可早期偵測、自然史清楚且有有效治療的疾病；檢查本身也要安全、可接受、成本合理。",
        {
            "A": "可治療是篩檢的核心條件，否則提早發現未必能改善預後。",
            "B": "自然史不清楚時，不容易判斷篩檢時點與追蹤策略，並非良好篩檢標的。",
            "C": "對健康影響不大的疾病，篩檢容易造成過度診斷與不必要焦慮。",
            "D": "高風險檢查不適合拿來做大量無症狀族群篩檢。",
        },
        "Wilson-Jungner 篩檢原則強調疾病重要、自然史清楚、可治療，且篩檢工具安全可接受。",
        "篩檢疾病必須重要、自然史清楚且可治療。",
        "篩檢原則",
        "可治療是必要條件；高風險、自然史不明或健康影響小的疾病不適合篩檢。",
    ),
    update(
        3,
        "Basic ADL 評估的是最基本的自我照顧動作，例如清潔、穿脫衣、如廁、移位、進食與洗澡；服藥管理屬於較複雜的 instrumental ADL。",
        {
            "A": "個人衛生屬於 basic ADL，反映病人能否完成基本自我照顧。",
            "B": "穿衣脫衣是典型 basic ADL 項目。",
            "C": "自行服藥需要記憶、安排與執行治療計畫，屬於 instrumental ADL，不是 basic ADL。",
            "D": "床椅間移位是 Katz ADL 常見項目，屬於 basic ADL。",
        },
        "Basic ADL 是吃、穿、洗、如廁、移位等基本照護；服藥、財務、交通多屬 IADL。",
        "自行服藥不屬於 basic ADL，而屬於 IADL。",
        "Basic ADL vs IADL",
        "Basic ADL 評基本自我照顧；服藥管理是 instrumental ADL。",
    ),
    update(
        4,
        "此題官方為全體給分。若依常見 RPI 公式，先以 reticulocyte count x Hct/45 校正，9 x 23/45 約 4.6；再依貧血程度用 maturation correction 約 2 校正，約 2.3，最接近 2.25，但不同考試版本可能因公式或給分爭議而全體給分。",
        {
            "A": "9.0 是未校正的網狀紅血球百分比，未反映貧血時紅血球總量下降。",
            "B": "4.5 接近 reticulocyte index，但還沒有用 maturation time 校正。",
            "C": "2.25 接近以 Hct 與成熟時間校正後的 RPI，若按標準算法最合理。",
            "D": "1.12 會多校正一次，低估骨髓反應。",
        },
        "RPI 需先用 hematocrit 校正 reticulocyte percentage，再依貧血嚴重度校正網狀紅血球成熟時間。",
        "RPI 約等於 corrected reticulocyte count 再除以 maturation correction。",
        "Reticulocyte production index",
        "Retic 9%、Hct 23% 時，校正後 RPI 約 2.25；本題官方為全體給分。",
        notes=["官方給分狀態為 all_credit；依一般公式最接近 C，但題庫保留官方全體給分。"],
    ),
    update(
        5,
        "本題考腹痛理學檢查的手法與陽性定義。Obturator sign 與 psoas sign 都常用於疑似闌尾炎或腹膜刺激的評估，但姿勢不同。",
        {
            "A": "Grey Turner sign 是腰側或脇腹瘀斑，常見於後腹腔出血；肚臍周圍瘀斑是 Cullen sign。",
            "B": "小腸阻塞初期常有高亢、金屬音或陣發性腸音；晚期才可能低活動性。",
            "C": "Murphy sign 是右上腹深壓時，吸氣因疼痛突然中止；不是吸氣吐氣都痛就算陽性。",
            "D": "Obturator sign 讓髖膝屈曲後內旋；psoas sign 常使髖伸展或抵抗屈髖誘發疼痛，因此敘述最合理。",
        },
        "腹痛檢查要分清瘀斑位置、腸阻塞腸音，以及 Murphy、obturator、psoas sign 的動作。",
        "Grey Turner 在脇腹，Cullen 在臍周；Murphy sign 是吸氣中止。",
        "腹痛理學檢查",
        "腹痛特殊徵象的關鍵是位置與誘發動作，不是只背疾病名稱。",
    ),
    update(
        6,
        "題目問急性冠心症分子機制何者錯誤。斑塊破裂後血小板活化、釋放介質、凝血系統啟動都正確；錯在說 GP IIb/IIIa 受體彼此直接連結。",
        {
            "A": "發炎細胞與 matrix metalloproteinase 會分解纖維帽膠原，使斑塊不穩定。",
            "B": "內皮下基質暴露後，血小板黏附活化並釋放 thromboxane A2、serotonin 等促進血管收縮與血小板募集。",
            "C": "GP IIb/IIIa 不是彼此直接相連，而是透過 fibrinogen 或 von Willebrand factor 作橋接形成聚集。",
            "D": "凝血系統產生 thrombin，將 fibrinogen 轉為 fibrin，穩定血栓。",
        },
        "血小板聚集靠 GP IIb/IIIa 與 fibrinogen 橋接，不是受體直接互黏。",
        "急性冠心症血小板聚集靠 fibrinogen 橋接 GP IIb/IIIa。",
        "ACS platelet aggregation",
        "GP IIb/IIIa 受體需由 fibrinogen/vWF 橋接，形成血小板團塊。",
    ),
    update(
        7,
        "NSTEMI 有心肌壞死生物標記上升，但沒有持續 ST elevation。治療需依風險分層安排侵入性策略，不是所有病人都必須 12 小時內接受 PCI。",
        {
            "A": "臨床缺血症狀加 troponin 或 cardiac enzyme 上升、無 ST elevation，符合 NSTEMI 概念。",
            "B": "cardiac troponin 對心肌壞死的敏感度與特異度都優於傳統酵素，是診斷核心。",
            "C": "12 小時內立即侵入治療主要用於極高風險或不穩定病人；一般 NSTEMI 需依 GRACE、症狀與血流動力學判斷。",
            "D": "抗血小板、抗凝血、硝酸鹽與適當 beta blocker 是 NSTEMI 常見內科治療骨架。",
        },
        "NSTEMI 的侵入性治療時機依風險分層，不是全部病人一律 12 小時內 PCI。",
        "NSTEMI 治療時機要依風險分層。",
        "NSTEMI risk stratification",
        "NSTEMI 不等於全部立即 PCI；極高風險才需非常早期侵入治療。",
    ),
    update(
        8,
        "CHA2DS2-VASc 計分：年齡 75 歲以上 2 分、女性 1 分、高血壓 1 分、糖尿病 1 分，至少為 5 分。若把症狀性喘與心房顫動個案視為心衰竭表現，則可再加 1 分成 6 分，因此官方接受 B 與 C。",
        {
            "A": "4 分少算了題幹明確提供的年齡、性別、高血壓或糖尿病其中一項。",
            "B": "不計心衰竭時，76 歲 2 分、女性 1 分、高血壓 1 分、糖尿病 1 分，合計 5 分。",
            "C": "若把活動喘視為心衰竭臨床表現，可再加 1 分，合計 6 分，因此官方也接受。",
            "D": "7 分需要再有中風/TIA、血管病變等條件，題幹未提供。",
        },
        "CHA2DS2-VASc 需逐項加總；此題因心衰竭判定空間，官方接受 5 或 6 分。",
        "CHA2DS2-VASc：75 歲以上 2 分，女性、高血壓、糖尿病各 1 分。",
        "CHA2DS2-VASc",
        "本題至少 5 分；若計入心衰竭則 6 分，官方接受 B 與 C。",
        notes=["官方答案為 multiple_correct：B 與 C；差異來自是否把活動喘視為心衰竭。"],
    ),
    update(
        9,
        "題幹有胸悶、疲倦、心跳 48 次/分並附心電圖；官方答案指向房室傳導阻滯。這類圖題需由 PR 間期、P 波與 QRS 的關係判斷，而不是只看心跳慢。",
        {
            "A": "竇性心動過緩需每個 QRS 前都有規則竇性 P 波且傳導關係固定；若 P-QRS 脫鉤或漏傳就不是單純竇性慢。",
            "B": "QTc 延長重點是 QT 間期經心率校正後變長，題幹症狀與官方圖像判讀不以此為主。",
            "C": "左心室肥厚需看電壓標準與 repolarization pattern，不能解釋明顯緩脈與傳導問題。",
            "D": "房室傳導阻滯可造成緩脈、疲倦、胸悶或運動耐受差，是本題最符合的心電圖判讀。",
        },
        "緩脈心電圖要先看 P 波與 QRS 的傳導關係；P-R 不固定、漏傳或 AV dissociation 要想到 AV block。",
        "心跳慢合併症狀，心電圖若顯示 P-QRS 傳導異常，優先判斷 AV block。",
        "房室傳導阻滯心電圖",
        "AV block 的重點是 P 波與 QRS 的關係，不只是心跳慢。",
        notes=["本題依附圖判讀；目前 JSON 未包含影像，解說保留官方答案並標示為圖題。"],
    ),
    update(
        10,
        "年輕人運動時暈厥、家族猝死、收縮期雜音、左心室肥厚與心室內壓力梯度，典型指向肥厚型阻塞性心肌病變（HOCM）。會降低前負荷或左心室容積的動作會讓阻塞與雜音變明顯。",
        {
            "A": "handgrip 增加後負荷，通常會降低 HOCM 的流出道壓力梯度，使雜音不會更明顯。",
            "B": "蹲下增加靜脈回流與後負荷，左心室腔變大，HOCM 雜音常變小。",
            "C": "站起會減少前負荷，左心室腔變小，流出道阻塞加劇，雜音變大。",
            "D": "抬腳增加 venous return，通常使左心室充盈增加，HOCM 雜音不會增強。",
        },
        "HOCM 雜音：前負荷下降或左心室腔變小會變大；蹲下、抬腳通常變小。",
        "HOCM 雜音站起變大，蹲下或抬腳變小。",
        "HOCM murmur maneuver",
        "standing 降低 preload，使 HOCM 流出道阻塞更嚴重。",
    ),
    update(
        11,
        "Paradoxical splitting 是 A2 延後，使原本吸氣時應變寬的 S2 分裂反而在吸氣時變窄或消失。典型原因包括嚴重主動脈瓣狹窄、左束支傳導阻滯等左心射血延遲狀態。",
        {
            "A": "二尖瓣關閉屬於 S1，不是 S2 paradoxical splitting 的主因。",
            "B": "嚴重主動脈瓣狹窄會使左心室射血時間延長，A2 延後，形成 paradoxical splitting。",
            "C": "right bundle branch block 會延後 P2，造成一般吸氣變寬的 splitting，不是 paradoxical splitting。",
            "D": "肺高壓與右心衰竭多影響 P2 或右心射血，不是典型 A2 延後機轉。",
        },
        "Paradoxical splitting 的關鍵是 A2 延後，常見於主動脈瓣狹窄或左束支傳導阻滯。",
        "S2 paradoxical splitting 是 A2 延後。",
        "Paradoxical splitting",
        "嚴重 AS 可延後 A2，造成 paradoxical splitting。",
    ),
    update(
        12,
        "題目問下肢周邊動脈疾病何者錯誤。血管雜音代表狹窄處亂流，不代表血管分流；其他選項多與 PAD 嚴重度或偵測方式有關。",
        {
            "A": "皮膚冷、跛行與脈搏異常都表示下肢灌流不足，病情較嚴重。",
            "B": "vascular bruit 是血流通過狹窄造成的亂流聲，不等於 shunting。",
            "C": "腳趾與手指氧飽和差異可作為周邊灌流不足的線索，但臨床常用 ABI 更標準。",
            "D": "雜音大小受血流量、狹窄形態與聽診條件影響，不能單靠音量判斷狹窄程度。",
        },
        "PAD 的 bruit 代表狹窄亂流，不是血管分流。",
        "血管雜音不等於 shunt，而常提示 stenosis。",
        "PAD vascular bruit",
        "周邊動脈疾病的 vascular bruit 來自狹窄亂流。",
    ),
    update(
        13,
        "本題考心雜音時相與姿勢變化。僧帽瓣狹窄的低頻 rumbling diastolic murmur 在左側臥、心尖部以 bell 聽診最典型。",
        {
            "A": "主動脈狹窄是 crescendo-decrescendo 收縮期射出性雜音，常在右上胸骨緣，並非單純早期收縮期。",
            "B": "HOCM 由蹲下變站立時前負荷下降，阻塞加重，雜音會變大，不是變小。",
            "C": "連續性雜音可見 PDA、動靜脈廔管或 sinus of Valsalva rupture；心房中膈缺損典型是固定分裂 S2 與收縮期流量雜音。",
            "D": "僧帽瓣狹窄是舒張中晚期低頻雜音，左側臥時在心尖部較清楚。",
        },
        "僧帽瓣狹窄是心尖部低頻舒張期 rumble；HOCM 站立變大、蹲下變小。",
        "MS 是心尖部舒張期低頻雜音。",
        "心雜音時相",
        "僧帽瓣狹窄的典型聽診是左側臥心尖部 diastolic rumble。",
    ),
    update(
        14,
        "收縮性心衰竭（HFrEF）治療要降低死亡率與住院：RAAS 抑制、beta blocker、MRA、SGLT2 inhibitor 等是核心；非 dihydropyridine CCB 會抑制心肌收縮，通常不宜使用。",
        {
            "A": "利尿劑可改善鬱血症狀，aldosterone antagonist 在合適病人也可改善預後。",
            "B": "verapamil、diltiazem 具負性肌力作用，HFrEF 容易惡化心衰竭，因此不宜。",
            "C": "ACE inhibitor 或 ARB 抑制 RAAS，可降低 HFrEF 死亡率與住院風險。",
            "D": "beta blocker 是 HFrEF 預後藥物；ivabradine 可用於部分心跳仍快且竇性節律病人。",
        },
        "HFrEF 避免 verapamil、diltiazem 等 non-dihydropyridine CCB。",
        "HFrEF 不宜用 verapamil/diltiazem。",
        "HFrEF contraindicated CCB",
        "Non-DHP CCB 會抑制收縮力，收縮性心衰竭不宜。",
    ),
    update(
        15,
        "題目問懷孕肝病何者錯誤。懷孕時 alkaline phosphatase 可因胎盤來源上升，但 AST、ALT 通常不因正常懷孕而上升；若轉氨酶升高要找病因。",
        {
            "A": "AFLP 多在第三孕期發生，病理為 microvesicular steatosis，敘述正確。",
            "B": "HELLP 的根本處置是終止妊娠，臨床常需依母胎狀況安排生產。",
            "C": "ALP 可生理性升高，但 AST、ALT 升高不是正常懷孕常見變化，因此此句錯誤。",
            "D": "肝腺瘤受雌激素影響，懷孕時可增大並增加破裂出血風險。",
        },
        "正常懷孕可使 ALP 上升，但 AST/ALT 升高應視為異常。",
        "懷孕 ALP 可上升，AST/ALT 不應被視為正常升高。",
        "Pregnancy liver enzymes",
        "懷孕期間轉氨酶升高要評估肝病，而不是當作生理變化。",
    ),
    update(
        16,
        "PSC 與 PBC 都是膽汁鬱積型疾病，但癌症風險不同。PSC 與 UC、cholangiocarcinoma 風險密切相關；PBC 主要是中年女性、AMA 陽性與小膽管破壞。",
        {
            "A": "PSC 常合併 ulcerative colitis，是考試常見配對。",
            "B": "膽管癌風險明顯上升的是 PSC，不是 PBC，因此此句錯誤。",
            "C": "末期 PBC 主要根治選項是肝移植；UDCA 對早期或未末期病人較有意義。",
            "D": "PBC 以女性居多，常見於中年女性。",
        },
        "PSC 合併 UC 且增加 cholangiocarcinoma 風險；PBC 則以女性、AMA、UDCA 為重點。",
        "膽管癌風險考 PSC，不是 PBC。",
        "PSC vs PBC",
        "PSC-UC-cholangiocarcinoma；PBC-中年女性-AMA-UDCA。",
    ),
    update(
        17,
        "此題官方為全體給分。化膿性肝膿瘍的致病菌會因感染來源與地區而不同，台灣常見 Klebsiella pneumoniae，糖尿病病人可有轉移性感染；治療通常需抗生素加引流。",
        {
            "A": "血行播散造成的肝膿瘍可與 Staphylococcus aureus 或 streptococci 相關，但是否「最常見」受來源與地區影響。",
            "B": "原發性肝膿瘍在台灣常見 Klebsiella pneumoniae；若寫 Escherichia coli，可能與部分教材或來源分類不一致。",
            "C": "糖尿病合併 Klebsiella 肝膿瘍可併發眼內炎，是高考點。",
            "D": "標準處理多為適當抗生素加上經皮或手術引流。",
        },
        "Klebsiella 肝膿瘍在糖尿病病人可造成眼內炎；治療以抗生素合併引流為主。",
        "化膿性肝膿瘍治療：抗生素加引流。",
        "Pyogenic liver abscess",
        "台灣常見 Klebsiella；糖尿病注意 endophthalmitis。",
        notes=["官方給分狀態為 all_credit；題幹問錯誤但選項流行病學可能因教材或地區差異產生爭議。"],
    ),
    update(
        18,
        "本題需依表格判讀 B 型肝炎血清標誌；官方答案指向個案 3 的描述錯誤。過往感染即使 HBsAg 陰性，仍可能有 occult HBV 或低量病毒 DNA，不宜寫成「不可能偵測到病毒」。",
        {
            "A": "HBeAg 陰性且特定抗體組合可見於 HBeAg-negative chronic hepatitis B，也可能是急性感染恢復期，需搭配 HBsAg、IgM anti-HBc 與 HBV DNA。",
            "B": "個案 2 若 HBsAg 持續陽性，仍可歸為慢性 B 肝帶原或慢性感染狀態。",
            "C": "過往感染通常 anti-HBc、anti-HBs 陽性，但仍不能排除低量 HBV DNA 或 occult infection，因此「不可能偵測到病毒」太絕對。",
            "D": "只有 anti-HBs 陽性可見於疫苗接種後，也可能受檢驗假陽性影響。",
        },
        "B 肝血清標誌要避免絕對化；過往感染不等於永遠不可能偵測到 HBV DNA。",
        "Resolved HBV 仍可能有 occult HBV。",
        "HBV serology",
        "過往感染常見 anti-HBc/anti-HBs；但不能說病毒一定不可能存在。",
        notes=["本題依表格判讀；目前 JSON 未包含表格，解說依官方答案保留並說明可能判讀重點。"],
    ),
    update(
        19,
        "題目問慢性 B 肝治療何者錯誤。干擾素雖有固定療程與無抗藥性的優點，但失代償性肝硬化不可使用，可能誘發嚴重肝衰竭或感染風險。",
        {
            "A": "此排序本身在現代藥物觀點可討論，但本題官方錯誤點不在這句；高效低抗藥性的 nucleo(t)side analogues 是慢性 B 肝主力。",
            "B": "干擾素不可用於失代償性肝硬化，因此把它列為可使用是錯誤。",
            "C": "tenofovir disoproxil fumarate 可能影響腎功能與骨密度，需監測腎功能。",
            "D": "肝硬化且 HBV DNA 達治療門檻時應給抗病毒藥物，以降低肝衰竭與 HCC 風險。",
        },
        "Interferon 可固定療程、無抗藥性，但失代償性肝硬化禁用。",
        "失代償性肝硬化不可用 interferon。",
        "HBV interferon contraindication",
        "慢性 B 肝合併 decompensated cirrhosis 應避免 interferon。",
    ),
    update(
        20,
        "肝性腦病變常由誘發因素引起或惡化，例如感染、腸胃道出血、便秘、脫水、低血鉀、鎮靜藥等；治療要找誘因並降低腸道氨產生。",
        {
            "A": "ammonia 常升高，但數值與臨床嚴重度不一定成正比，不能單靠氨值分級。",
            "B": "感染與低血鉀都是常見誘發因素，需主動尋找並矯正。",
            "C": "不建議長期嚴格限制蛋白質，過度限制會造成營養不良；通常維持適當蛋白攝取。",
            "D": "治療首選通常是 lactulose，必要時加 rifaximin；MgO 不是標準治療核心。",
        },
        "肝性腦病變要找誘因；感染、低血鉀、便秘、出血都常見，治療以 lactulose 為主。",
        "肝性腦病變誘因包括感染與低血鉀。",
        "Hepatic encephalopathy triggers",
        "HE 的處置是找誘因與 lactulose/rifaximin，不是嚴格禁蛋白。",
    ),
    update(
        21,
        "IBD 治療要分 induction 與 maintenance。類固醇可誘導緩解，但不適合維持治療；生物製劑能減少類固醇依賴、改善 fistula，5-ASA 是潰瘍性大腸炎維持治療重要藥物。",
        {
            "A": "包含第 1 點，但類固醇不應作為 maintenance therapy，故此組合錯。",
            "B": "第 2、3、4 點都正確：biologics 可 steroid-sparing 並改善 fistula；5-ASA 可用於 UC 維持。",
            "C": "只列 2、4 漏掉 biologics 對 fistula healing 的重要效果。",
            "D": "全選包含錯誤的第 1 點，因此不對。",
        },
        "IBD 類固醇用於誘導緩解，不用作長期維持；biologics 可減少 steroid 並幫助 fistula。",
        "IBD steroids induction only，不作維持治療。",
        "IBD induction maintenance",
        "UC 維持可用 5-ASA；生物製劑可 steroid-sparing 與促進 fistula 癒合。",
    ),
    update(
        22,
        "IBS 是腸腦互動障礙，與內臟敏感、腸道蠕動、心理壓力與中樞調控都有關。嚴重 IBS 在女性較多見。",
        {
            "A": "IBS 不是單純腸壁病變，腸腦軸與中樞神經調控很重要。",
            "B": "感染後 IBS 通常女性風險較高，不是男性多於女性。",
            "C": "IBS 常見於年輕至中年族群；45 歲以上新發症狀反而要注意警訊與器質性疾病。",
            "D": "嚴重 IBS 女性比例較高，約可達多數，是本題正確敘述。",
        },
        "IBS 是腸腦互動障礙，嚴重個案以女性較多；高齡新發症狀要排除警訊。",
        "IBS 與 gut-brain interaction 有關，女性較常見。",
        "Irritable bowel syndrome",
        "IBS 不是純腸壁病，嚴重者女性居多。",
    ),
    update(
        23,
        "本題考遺傳性大腸癌與息肉症候群的配對。Lynch syndrome 屬 hereditary nonpolyposis colorectal cancer，常為近端大腸癌與子宮內膜、卵巢等腫瘤風險上升，息肉數不一定多但仍由 adenoma-carcinoma pathway 發展。",
        {
            "A": "FAP 是大量腺瘤性息肉，癌化風險高；但先天異常組合更接近 Gardner 變異型，敘述不如 D 精準。",
            "B": "Peutz-Jeghers 的息肉是 hamartomatous polyp，不是 adenoma。",
            "C": "Turcot syndrome 主要是腺瘤性息肉合併中樞神經腫瘤；骨瘤、脂肪瘤、CHRPE 等是 Gardner/FAP 相關特徵。",
            "D": "Lynch syndrome 常見近端大腸癌，並增加子宮內膜、卵巢、胃、泌尿道、胰膽道等癌症風險。",
        },
        "Lynch syndrome 是非息肉性遺傳性大腸癌，常見近端大腸與子宮內膜、卵巢等癌症。",
        "Lynch：proximal colon、endometrial/ovarian cancers。",
        "Hereditary GI polyposis syndromes",
        "Peutz-Jeghers 是 hamartoma；Gardner 有骨瘤與軟組織腫瘤；Lynch 常近端大腸癌。",
    ),
    update(
        24,
        "腎移植後急性腎功能惡化，切片有 C4d 沉積與內皮細胞損傷，典型為抗體媒介排斥（antibody-mediated rejection）。治療重點是移除或中和抗體。",
        {
            "A": "單純增加 tacrolimus/MMF 對 T 細胞反應較有意義，無法快速處理抗體媒介排斥。",
            "B": "類固醇脈衝常用於細胞性排斥，對 C4d 陽性的抗體媒介排斥不足。",
            "C": "降低 tacrolimus 可能讓排斥更惡化；透析只能支持腎功能，不能治療排斥機轉。",
            "D": "血漿置換移除 donor-specific antibody，IVIG 調節免疫，是抗體媒介排斥的標準治療組合。",
        },
        "腎移植 C4d 沉積加內皮損傷指向 antibody-mediated rejection，治療用 plasmapheresis 加 IVIG。",
        "C4d 陽性排斥治療：血漿置換加 IVIG。",
        "Antibody-mediated rejection",
        "AMR 的核心是 donor-specific antibody，需移除或中和抗體。",
    ),
    update(
        25,
        "上呼吸道感染後數天即出現肉眼或顯微血尿，腎切片 mesangium 有 IgA 沉積，典型為 IgA nephropathy。與鏈球菌感染後腎炎不同，IgA 常是 synpharyngitic hematuria。",
        {
            "A": "minimal change disease 主要造成 nephrotic syndrome，光學顯微鏡變化少，不是 mesangial IgA 沉積。",
            "B": "IgA nephropathy 典型為感染同時或數天內血尿，mesangial IgA deposition。",
            "C": "FSGS 常見節段性硬化與蛋白尿，不以感染後 3 天血尿加 IgA 沉積為特徵。",
            "D": "membranous nephropathy 是成人腎病症候群與基底膜免疫沉積，非 mesangial IgA。",
        },
        "IgA nephropathy：上呼吸道感染同時或數天內血尿，mesangial IgA deposition。",
        "Synpharyngitic hematuria + mesangial IgA = IgA nephropathy。",
        "IgA nephropathy",
        "IgA nephropathy 與 post-strep GN 的時間差是高頻考點。",
    ),
    update(
        26,
        "Goodpasture syndrome 的抗體是針對 type IV collagen alpha-3 chain NC1 domain，不是 alpha-5 NC1 domain；其他配對較符合常見腎臟免疫疾病機轉。",
        {
            "A": "PR3-ANCA 與 granulomatosis with polyangiitis 相關，是典型配對。",
            "B": "鏈球菌感染後腎炎可與抗鏈球菌抗體反應相關，選項方向較可接受。",
            "C": "PLA2R antibody 是 primary membranous nephropathy 的重要抗體。",
            "D": "Goodpasture 抗 glomerular basement membrane 的目標是 type IV collagen alpha-3 NC1 domain；alpha-5 配對錯誤。",
        },
        "Goodpasture syndrome 是 anti-alpha-3 NC1 domain of type IV collagen。",
        "Goodpasture 抗體不是 alpha-5，而是 alpha-3 NC1。",
        "Goodpasture antibody",
        "Anti-GBM disease 針對 type IV collagen alpha-3 NC1 domain。",
    ),
    update(
        27,
        "老人使用 metformin 後發生急性腎衰竭，pH 7.0、HCO3 4 顯示嚴重代謝性酸中毒，尿液無酮體線索且血糖不算典型 DKA，最符合 metformin-associated lactic acidosis。",
        {
            "A": "DKA 通常有高血糖、酮酸與陰離子間隙酸中毒；題幹沒有尿酮或典型酮酸線索。",
            "B": "rhabdomyolysis 會有肌肉症狀、CK 升高、尿潛血陽性但少紅血球等線索，題幹未提示。",
            "C": "腎衰竭使 metformin 蓄積，造成嚴重 lactic acidosis，是最可能診斷。",
            "D": "type 4 RTA 常為高血鉀、輕中度正常陰離子間隙酸中毒，不會典型 pH 7.0、HCO3 4 如此嚴重。",
        },
        "Metformin 在急性腎衰竭時可蓄積，導致嚴重 lactic acidosis。",
        "Metformin + AKI + severe metabolic acidosis = lactic acidosis。",
        "Metformin-associated lactic acidosis",
        "腎功能急壞時 metformin 需停用，避免乳酸性酸中毒。",
    ),
    update(
        28,
        "題目問 AKI 何者錯誤。慢性腎臟病、利尿劑、敗血症等情境會使 FeNa 判讀不可靠；FeNa >1% 不能排除腎前性 AKI。",
        {
            "A": "腎前性 AKI 因尿素重吸收增加，BUN/Cr 常大於 20。",
            "B": "敗血症可造成腎小管傷害與 intrinsic AKI，是住院 AKI 常見原因。",
            "C": "postrenal AKI 的首要處置是解除阻塞，例如導尿、腎造廔或處理結石腫瘤。",
            "D": "CKD 或使用利尿劑時 FeNa 可能偏高，不能用 FeNa >1% 直接排除 prerenal AKI。",
        },
        "FeNa 判讀受 CKD 與利尿劑影響；不能單靠 FeNa >1% 排除腎前性 AKI。",
        "FeNa >1% 不一定排除 prerenal AKI。",
        "AKI FeNa limitation",
        "AKI 要結合病史、尿沉渣與容量狀態，FeNa 不是絕對規則。",
    ),
    update(
        29,
        "腎移植免疫抑制藥物有典型副作用。Sirolimus 常見高脂血症、傷口癒合差、口腔潰瘍、骨髓抑制等；高尿酸血症不是其典型配對。",
        {
            "A": "glucocorticoid 可造成骨質疏鬆、血糖上升、感染風險增加，配對正確。",
            "B": "cyclosporine 是 calcineurin inhibitor，腎毒性是重要副作用。",
            "C": "tacrolimus 也屬 calcineurin inhibitor，移植後糖尿病比 cyclosporine 更典型。",
            "D": "sirolimus 是 mTOR inhibitor，典型是高脂血症與傷口癒合不良，不是高尿酸血症。",
        },
        "Sirolimus 典型副作用是高脂血症、傷口癒合差與骨髓抑制。",
        "Sirolimus 不典型配對高尿酸血症。",
        "Transplant drug adverse effects",
        "Calcineurin inhibitors 腎毒性；tacrolimus 糖尿病；sirolimus 高脂血症與傷口癒合差。",
    ),
    update(
        30,
        "尿毒性出血主要是血小板功能障礙。可用透析、DDAVP、cryoprecipitate、矯正貧血等方式改善；androgen 起效慢，多用於特定慢性情境，不適合持續出血的急性止血。",
        {
            "A": "尿毒素會干擾血小板黏附與凝集，敘述正確。",
            "B": "貧血會降低血小板貼近血管壁的機會，矯正貧血可改善止血。",
            "C": "desmopressin 可短暫改善血小板功能；cryoprecipitate 也可作為治療選項。",
            "D": "androgen 起效需數天至數週，且有血栓風險，不是持續出血時合適的急性處置。",
        },
        "尿毒性出血急性處置可用 DDAVP、cryoprecipitate、透析與矯正貧血；androgen 起效慢。",
        "Uremic bleeding 是血小板功能不良。",
        "Uremic bleeding treatment",
        "DDAVP 可短效改善尿毒性血小板功能；androgen 不是急性止血首選。",
    ),
    update(
        31,
        "Sarcoidosis 是非乾酪性肉芽腫疾病，免疫機轉以 CD4 T cell 與巨噬細胞活化為主，最常侵犯肺與肺門淋巴結。",
        {
            "A": "CD4 T 淋巴細胞活化與 granuloma 形成是 sarcoidosis 的核心病理。",
            "B": "肺部是 sarcoidosis 最常受侵犯器官，且可造成肺高壓，故此句錯。",
            "C": "高血鈣主要來自肉芽腫巨噬細胞增加 1-alpha hydroxylase，產生 calcitriol；不是 ACE 本身造成。",
            "D": "治療主力仍是 corticosteroid；TNF-alpha inhibitor 可用於部分難治病例，IL-1 inhibitor 不是最有效標準答案。",
        },
        "Sarcoidosis 是 CD4 T cell 驅動的非乾酪性肉芽腫，常侵犯肺部。",
        "Sarcoidosis：noncaseating granuloma + CD4 T cell activation。",
        "Sarcoidosis",
        "高血鈣來自 granuloma 巨噬細胞產生 calcitriol，不是 ACE 直接造成。",
    ),
    update(
        32,
        "MCTD 的典型抗體是 anti-U1 RNP。Anti-centromere antibody 主要與 limited cutaneous systemic sclerosis 或 CREST syndrome 相關。",
        {
            "A": "Sjögren syndrome 常見 anti-Ro/SSA 與 anti-La/SSB，配對正確。",
            "B": "SLE 的 anti-dsDNA 與疾病活動、腎炎相關，是典型配對。",
            "C": "MCTD 應配 anti-U1 RNP；anti-centromere 配 limited scleroderma，因此錯誤。",
            "D": "diffuse systemic sclerosis 常與 anti-Scl-70 相關，配對正確。",
        },
        "MCTD 對應 anti-U1 RNP；anti-centromere 對應 limited systemic sclerosis。",
        "MCTD 的抗體是 anti-U1 RNP。",
        "Autoantibody disease pair",
        "Anti-centromere 不是 MCTD，而是 limited scleroderma/CREST。",
    ),
    update(
        33,
        "風濕熱是 A 群鏈球菌感染後的免疫反應，抗體或 T 細胞與心臟、關節等宿主組織交叉反應，屬分子模仿。",
        {
            "A": "streptococcal antigens 與宿主組織交叉反應，造成 rheumatic fever，是最典型病理機轉。",
            "B": "金黃色葡萄球菌可造成感染性心內膜炎或毒素疾病，不是風濕熱主因。",
            "C": "癌細胞侵襲與風濕熱無關。",
            "D": "類風濕性關節炎是自體免疫關節病，不能解釋鏈球菌感染後風濕熱。",
        },
        "Rheumatic fever 是 group A strep 後 molecular mimicry。",
        "風濕熱機轉：鏈球菌後分子模仿。",
        "Rheumatic fever pathogenesis",
        "GAS antigen 與宿主組織交叉反應造成風濕熱。",
    ),
    update(
        34,
        "僵直性脊椎炎治療第一線是運動與 NSAIDs；若仍控制不佳才考慮 TNF inhibitor 或 IL-17 inhibitor 等生物製劑。",
        {
            "A": "sulfasalazine 對周邊關節炎較有幫助，對 axial spine disease 效果有限。",
            "B": "anti-TNF 對脊椎發炎與周邊關節都可有效，不只周邊關節。",
            "C": "NSAIDs 是僵直性脊椎炎第一線藥物，搭配運動復健。",
            "D": "methotrexate 對 axial disease 幫助有限，也不是每位使用 anti-TNF 者都必須併用。",
        },
        "Ankylosing spondylitis 第一線是 NSAIDs 與運動；sulfasalazine/MTX 對 axial disease 有限。",
        "AS 第一線藥物是 NSAIDs。",
        "Ankylosing spondylitis treatment",
        "NSAIDs first-line；anti-TNF 可治 axial inflammation。",
    ),
    update(
        35,
        "纖維肌痛症是臨床診斷，重點是廣泛疼痛指數與症狀嚴重度，例如睡眠差、疲倦、認知症狀；影像與免疫抽血主要用來排除其他疾病，不是確診核心。",
        {
            "A": "問卷評估疼痛區與全身症狀符合 ACR 診斷方向，是最適當處置。",
            "B": "頸椎 MRI 只能評估局部結構病變，不能確立纖維肌痛症。",
            "C": "RF 可協助評估類風濕關節炎，但病人多年檢查正常且症狀符合 fibromyalgia，重複抽血不是最關鍵。",
            "D": "女性荷爾蒙不是纖維肌痛症診斷標準。",
        },
        "Fibromyalgia 以 WPI 與 symptom severity 量表評估；不是靠影像或單一抽血確診。",
        "Fibromyalgia 診斷靠疼痛分布與症狀量表。",
        "Fibromyalgia diagnosis",
        "廣泛疼痛加睡眠、疲倦、認知症狀，比影像檢查更能確立診斷。",
    ),
    update(
        36,
        "慢性 B 肝合併疑似 HCC 時，血小板低、白蛋白低、INR 延長可反映肝硬化與門脈高壓或肝合成功能下降；AST 升高只代表肝細胞傷害，不等於已有肝硬化。",
        {
            "A": "血小板 70,000/μL 常見於門脈高壓造成脾臟鬱血，支持肝硬化。",
            "B": "albumin 2.8 g/dL 表示肝臟合成功能差，支持肝硬化或嚴重肝病。",
            "C": "INR >2.2 表示凝血因子合成差，是肝功能不全的重要線索。",
            "D": "AST 100 U/L 只表示肝細胞發炎或傷害，不能單獨代表肝硬化。",
        },
        "肝硬化證據看門脈高壓與合成功能：血小板低、albumin 低、INR 高；AST 升高不等於肝硬化。",
        "AST 升高不是肝硬化證據。",
        "Cirrhosis lab evidence",
        "肝硬化常見 thrombocytopenia、hypoalbuminemia、INR prolongation。",
    ),
    update(
        37,
        "可切除胰管腺癌即使能手術，仍常有微小殘存或早期復發風險，所以術後輔助化療有存活益處；題目問正確敘述，R1 resection 約三成是合理考點。",
        {
            "A": "多數胰臟癌初診斷時已局部晚期或轉移，真正可切除比例不是約 60%。",
            "B": "胰臟癌即使可切除，5 年存活率仍不佳，不能說多數預後良好達約 60%。",
            "C": "手術病理常發現 microscopic residual disease，R1 resection 約三成可作為考點。",
            "D": "術後輔助化療可改善整體存活，不能說不應進行。",
        },
        "可切除胰臟癌仍需重視 R1 與復發風險；術後輔助化療有存活益處。",
        "Pancreatic ductal adenocarcinoma resectable disease 仍常需 adjuvant chemotherapy。",
        "Resectable pancreatic cancer",
        "胰臟癌可切除不代表預後好；輔助化療重要。",
    ),
    update(
        38,
        "第四期腎細胞癌對傳統 cytotoxic chemotherapy 反應差；有效治療以免疫治療與標靶治療為主。",
        {
            "A": "checkpoint inhibitors 是轉移性 RCC 的重要治療，常與其他免疫或 TKI 藥物合併。",
            "B": "傳統化學治療對 RCC 效果差，因此不是有效治療。",
            "C": "VEGF/VEGFR 抗血管新生標靶治療是 metastatic RCC 重要藥物類別。",
            "D": "mTOR inhibitors 如 everolimus/temsirolimus 曾用於 advanced RCC，屬有效標靶選項。",
        },
        "Metastatic RCC 以免疫檢查點抑制劑與 VEGF/mTOR 標靶為主，傳統化療效果差。",
        "RCC 對傳統 chemotherapy 不敏感。",
        "Metastatic renal cell carcinoma treatment",
        "第四期 RCC 的有效治療不是傳統化療。",
    ),
    update(
        39,
        "老人有 atrophic gastritis、anti-parietal cell antibody、巨球性貧血、pancytopenia、LDH 高與間接膽紅素上升，最符合 pernicious anemia 造成的維生素 B12 缺乏。骨髓會代償性 erythroid hyperplasia，而非 precursor 減少。",
        {
            "A": "B12 缺乏有 ineffective erythropoiesis，網狀紅血球常偏低，敘述正確。",
            "B": "骨髓通常是 megaloblastic change 與 erythroid hyperplasia，不是 erythroid precursors 減少。",
            "C": "高 LDH 來自 ineffective erythropoiesis 與髓內溶血，符合 B12 缺乏。",
            "D": "周邊血 granulocytes 可見 hypersegmented neutrophils，是巨球性貧血典型所見。",
        },
        "Pernicious anemia 造成 B12 缺乏：巨球性貧血、LDH 高、網狀球低、骨髓 erythroid hyperplasia。",
        "B12 缺乏骨髓 precursor 不少，反而有 megaloblastic hyperplasia。",
        "Pernicious anemia",
        "Anti-parietal cell antibody 加 atrophic gastritis 指向 pernicious anemia。",
    ),
    update(
        40,
        "Warfarin 造成 INR 5.4 但沒有出血時，通常先停藥或調整劑量並追蹤 INR；不應為了預防出血而例行靜脈注射 vitamin K 至 INR <3，尤其機械瓣膜病人還要避免過度逆轉造成血栓。",
        {
            "A": "Warfarin 初期會先降低 protein C/S，抗凝效果也延遲，所以常需 heparin bridging。",
            "B": "無出血且 INR 5.4 時不應常規 IV vitamin K 逆轉，處置過度且增加血栓風險。",
            "C": "嚴重出血時 FFP 可補充 vitamin K-dependent coagulation factors，快速部分逆轉抗凝。",
            "D": "protein C/S 缺乏者用 warfarin 需小心皮膚壞死與血栓風險，敘述正確。",
        },
        "Warfarin INR 升高但無出血時多先停藥與追蹤；嚴重出血才快速逆轉。",
        "INR 5.4 無出血不常規 IV vitamin K。",
        "Warfarin supratherapeutic INR",
        "機械瓣膜病人過度逆轉 warfarin 可能增加血栓風險。",
    ),
    update(
        41,
        "造血幹細胞移植來源包括骨髓、G-CSF 動員後周邊血幹細胞與臍帶血；成人脾臟不是常規可接受來源。",
        {
            "A": "骨髓細胞是傳統造血幹細胞來源。",
            "B": "G-CSF 可將造血幹細胞動員到周邊血，周邊血幹細胞是常用來源。",
            "C": "臍帶血含造血幹細胞，可用於移植。",
            "D": "成人脾臟細胞不是臨床造血幹細胞移植的標準來源。",
        },
        "HSCT 標準來源：bone marrow、mobilized peripheral blood、umbilical cord blood。",
        "成人脾臟不是 HSCT 標準來源。",
        "HSCT stem cell source",
        "造血幹細胞移植來源不包含成人脾臟細胞。",
    ),
    update(
        42,
        "早期喉癌常可用放射治療達到控制並保留發聲與喉部功能，是頭頸癌器官保存的經典考點。",
        {
            "A": "口頰癌屬口腔癌，早期多以手術切除為主。",
            "B": "早期 laryngeal cancer 可考慮 definitive radiotherapy，兼顧腫瘤控制與器官功能保存。",
            "C": "舌癌早期通常以手術為主要治療，視病理風險加輔助治療。",
            "D": "唾液腺癌以手術為主，放療多作為輔助或特定情境使用。",
        },
        "早期喉癌可用放射治療作器官保存治療。",
        "早期 laryngeal cancer 可 RT 保留器官功能。",
        "Organ preservation head and neck cancer",
        "喉癌是早期放療保留功能的典型頭頸癌。",
    ),
    update(
        43,
        "輔助性標靶治療已明確改善早期 HER2 陽性乳癌整體存活，代表藥物是 trastuzumab。其他選項在輔助治療提升整體存活的證據或適應症不符合題意。",
        {
            "A": "EGFR 突變肺癌的輔助 EGFR-TKI 證據近年增加，但 gefitinib 作為提升整體存活的經典答案不如 trastuzumab 明確。",
            "B": "KRAS wild-type 大腸癌使用 cetuximab 主要在轉移性疾病；輔助治療未證實提升整體存活。",
            "C": "HER2 過度表現乳癌術後 trastuzumab 可降低復發並改善存活，是本題正確配對。",
            "D": "Sorafenib 用於進階 HCC；HBV 相關早期肝癌術後輔助 sorafenib 不是標準提升存活療法。",
        },
        "HER2 陽性早期乳癌術後 trastuzumab 是經典有效輔助標靶治療。",
        "Adjuvant trastuzumab improves survival in HER2-positive breast cancer。",
        "Adjuvant targeted therapy",
        "早期癌症輔助標靶治療的經典答案是 HER2 乳癌 trastuzumab。",
    ),
    update(
        44,
        "停經後女性、ER/PR 陽性、HER2 陰性，且只有骨轉移、無臟器危象時，第一線以內分泌治療為主；aromatase inhibitor 是合適選擇。",
        {
            "A": "bevacizumab 不是 HR 陽性轉移性乳癌的標準第一線核心藥物。",
            "B": "trastuzumab 用於 HER2 陽性乳癌；題幹 HER2 陰性。",
            "C": "沒有 visceral crisis 時，HR 陽性轉移性乳癌通常先內分泌治療，不先化療。",
            "D": "停經後 ER/PR 陽性乳癌可用 aromatase inhibitor 作第一線內分泌治療。",
        },
        "停經後 HR positive、HER2 negative、骨轉移且無臟器危象，首選內分泌治療如 aromatase inhibitor。",
        "HR+ HER2- metastatic breast cancer without visceral crisis：先內分泌治療。",
        "Metastatic breast cancer endocrine therapy",
        "停經後 ER/PR 陽性乳癌可選 aromatase inhibitor。",
    ),
    update(
        45,
        "肺腺癌手術後預後與組織型態相關。Lepidic pattern 生長較貼附肺泡壁、侵襲性較低，完整切除後預後最佳；solid、micropapillary 預後較差。",
        {
            "A": "micropapillary pattern 侵襲性高，復發風險較高，預後差。",
            "B": "solid pattern 也屬預後較差的肺腺癌亞型。",
            "C": "acinar pattern 預後中等，不是最佳。",
            "D": "lepidic pattern 侵襲性較低，完整切除後預後最好。",
        },
        "肺腺癌 lepidic pattern 預後最佳；micropapillary 與 solid 較差。",
        "Lepidic lung adenocarcinoma has best prognosis after resection。",
        "Lung adenocarcinoma subtype prognosis",
        "相同期別肺腺癌，lepidic pattern 預後最佳。",
    ),
    update(
        46,
        "支氣管音（bronchial breath sounds）在周邊肺野出現，代表肺泡實變使聲音傳導增加，最典型是大葉性肺炎。",
        {
            "A": "大量肋膜積水常使呼吸音變小，積液上緣可有支氣管音，但題目左後肺野明顯支氣管音最直接指向實變。",
            "B": "氣胸使患側呼吸音減弱或消失，不會典型產生支氣管音。",
            "C": "肺水腫多聽到 crackles，不是局部左後肺野支氣管音。",
            "D": "左下葉大葉性肺炎造成肺實變，最能解釋局部 bronchial sound。",
        },
        "肺野支氣管音提示肺實變，典型診斷是 lobar pneumonia。",
        "Bronchial breath sound in peripheral lung suggests consolidation。",
        "Bronchial breath sounds",
        "局部支氣管音是大葉性肺炎的典型聽診線索。",
    ),
    update(
        47,
        "肺功能顯示 FEV1/FVC 78% 不低，TLC 66% 下降、FVC 下降，屬限制型通氣障礙；DLco 40% 顯著下降代表肺間質或肺泡微血管交換受損，最符合肺纖維化。",
        {
            "A": "COPD 是阻塞型，FEV1/FVC 會下降，與題幹不符。",
            "B": "胸廓畸形可造成限制型，但 DLco 通常相對保留，不會典型大幅降低。",
            "C": "重症肌無力造成神經肌肉限制，DLco 通常也不會像間質肺病般降低。",
            "D": "肺纖維化造成限制型肺功能與 DLco 明顯下降，最符合。",
        },
        "限制型肺功能合併 DLco 明顯下降，優先想到間質性肺病或肺纖維化。",
        "Low TLC + low DLco = pulmonary fibrosis/interstitial lung disease。",
        "Pulmonary function test interpretation",
        "FEV1/FVC 保留但 TLC 與 DLco 下降，支持肺纖維化。",
    ),
    update(
        48,
        "潛伏結核感染是感染但無活動性疾病、無傳染性。診斷常用 TST 或 IGRA，治療可大幅降低日後發病風險。",
        {
            "A": "TST 與 interferon-gamma release assay 都可用於診斷 latent TB infection。",
            "B": "一般 LTBI 終生進展為活動性結核約 5-10%，不是約 30%。",
            "C": "LTBI 沒有活動性排菌，通常不具傳染性，不需因潛伏感染戴口罩避免傳染。",
            "D": "有效治療可降低發病風險，常見估計約 60-90%；選項寫約 70%可接受，但本題最佳為診斷工具。",
        },
        "LTBI 用 TST 或 IGRA 診斷；沒有活動病灶時不具傳染性。",
        "Latent TB infection diagnosis：TST or IGRA。",
        "Latent TB infection",
        "LTBI 不是活動性結核，通常不會傳染他人。",
    ),
    update(
        49,
        "原發性肺膿瘍最常與 aspiration 有關，常在重力依賴部位，例如右上葉後段或下葉上段；右中葉與左舌葉不是最典型位置。",
        {
            "A": "aspiration 是原發性肺膿瘍最常見原因，尤其意識不清、吞嚥障礙或口腔衛生差者。",
            "B": "吸入性肺膿瘍常見於 dependent segments，不是以右中葉與左舌葉最常見，因此最不適當。",
            "C": "治療常需長期抗生素，通常超過 3 週；失敗或併發症時才考慮手術。",
            "D": "吸入性肺膿瘍常為厭氧菌與多種口腔菌混合感染。",
        },
        "吸入性肺膿瘍常在 dependent lung segments，致病菌多為 polymicrobial anaerobes。",
        "Lung abscess most commonly from aspiration in dependent segments。",
        "Lung abscess location",
        "右中葉與左舌葉不是吸入性肺膿瘍最典型位置。",
    ),
    update(
        50,
        "甲狀腺功能低下會使代謝下降，典型有怕冷、體重增加、心跳慢、便祕、皮膚乾、黏液性水腫；體重急速下降較像甲狀腺亢進。",
        {
            "A": "myxedema 是重度甲狀腺低下的典型表現。",
            "B": "代謝下降與交感活性降低可造成靜態心跳過慢。",
            "C": "體重急速下降是甲狀腺功能亢進較典型，不是低下症狀。",
            "D": "怕冷是甲狀腺低下常見症狀。",
        },
        "Hypothyroidism 典型是怕冷、體重增加、bradycardia、myxedema；體重下降偏 hyperthyroidism。",
        "體重急速下降不是 hypothyroidism 典型症狀。",
        "Hypothyroidism symptoms",
        "甲狀腺低下是低代謝狀態。",
    ),
    update(
        51,
        "第 1 型糖尿病因胰島 beta cell 破壞而絕對胰島素缺乏，必須依賴胰島素預防高血糖與酮酸血症。",
        {
            "A": "lispro 是速效胰島素，不是中長效；detemir、glargine 才是基礎胰島素類。",
            "B": "短效或速效胰島素主要處理餐前或校正需求，不是每天 basal insulin 的主要來源。",
            "C": "protamine 會延緩吸收、延長作用，例如 NPH 或預混製劑中的中效成分，不是加速。",
            "D": "第 1 型糖尿病需胰島素治療，否則容易發生 DKA。",
        },
        "Type 1 DM 是絕對胰島素缺乏，需胰島素預防 DKA。",
        "Lispro 是速效；glargine/detemir 是長效。",
        "Insulin preparations",
        "Protamine 延緩胰島素吸收；第 1 型糖尿病必須用胰島素。",
    ),
    update(
        52,
        "糖尿病是大血管疾病高風險狀態，血脂治療門檻與風險分層通常比一般族群更積極，不能說膽固醇治療準則與無糖尿病者一樣。",
        {
            "A": "糖尿病使心血管疾病風險約增加 2-4 倍，敘述正確。",
            "B": "同時控制血糖、血壓、血脂可降低大血管併發症風險。",
            "C": "糖尿病病人的 statin 適應症與 LDL 目標常依高風險處理，不與無糖尿病者完全一樣。",
            "D": "statin 已證實能降低糖尿病病人心血管事件；aspirin 則依初級或次級預防風險權衡。",
        },
        "糖尿病血脂治療採較高心血管風險策略，不能等同一般無糖尿病族群。",
        "Diabetes dyslipidemia management is more aggressive than general population。",
        "Diabetes macrovascular prevention",
        "糖尿病預防大血管疾病要控制血糖、血壓與血脂。",
    ),
    update(
        53,
        "我國代謝症候群標準包含腰圍、血壓、空腹血糖、三酸甘油脂、HDL-C。女性腰圍大於等於或大於 80 公分是腹部肥胖切點，最符合選項。",
        {
            "A": "代謝症候群使用腰圍，不是男女 BMI 都超過 24 作為五項標準之一。",
            "B": "LDL-C 不是我國代謝症候群五項判定標準。",
            "C": "HDL-C 切點男女不同，男性 <40、女性 <50 mg/dL；不是男女都 <50。",
            "D": "女性腰圍大於 80 公分符合腹部肥胖標準。",
        },
        "代謝症候群看腰圍、血壓、空腹血糖、TG、HDL；女性腰圍切點 80 cm。",
        "台灣代謝症候群女性腰圍切點為 80 cm。",
        "Metabolic syndrome criteria Taiwan",
        "LDL 與 BMI 不是我國代謝症候群五項判定標準。",
    ),
    update(
        54,
        "年輕、BMI 正常、高血壓合併低血鉀，要先懷疑原發性醛固酮增多症；篩檢應測 aldosterone 與 renin，計算 aldosterone-renin ratio。",
        {
            "A": "aldosterone 高且 renin 低是原發性醛固酮增多症線索，是最合適初步檢查。",
            "B": "ACTH/cortisol 用於 Cushing syndrome 評估，但題幹低血鉀加正常外觀更先考 aldosteronism。",
            "C": "VMA/catecholamines 用於嗜鉻細胞瘤，通常有陣發高血壓、心悸、頭痛、冒汗。",
            "D": "fT4/TSH 可評估甲狀腺造成心跳或血壓問題，但不能解釋典型低血鉀高血壓。",
        },
        "高血壓合併低血鉀，先篩檢 primary aldosteronism：aldosterone-renin ratio。",
        "Hypertension + hypokalemia -> aldosterone and renin。",
        "Primary aldosteronism screening",
        "年輕高血壓低血鉀要測 ARR。",
    ),
    update(
        55,
        "甲狀腺功能亢進常用治療包括抗甲狀腺藥物、放射性碘與手術；立體定位放射線治療不是常規治療方式。",
        {
            "A": "methimazole、propylthiouracil 等口服抗甲狀腺藥物是常用治療。",
            "B": "甲狀腺切除可用於大型甲狀腺腫、懷疑癌症、藥物不適用等情境。",
            "C": "立體定位放射線治療用於許多腫瘤或腦部病灶，不是甲亢標準治療。",
            "D": "放射性碘治療是甲亢常用根治選項之一。",
        },
        "Hyperthyroidism 治療三大類：抗甲狀腺藥、radioiodine、手術。",
        "立體定位放射線治療不是甲亢常用治療。",
        "Hyperthyroidism treatment",
        "甲亢常用治療不包含 stereotactic radiotherapy。",
    ),
    update(
        56,
        "20 歲男性第二性徵不全、睪丸小而軟，需先確認性腺功能低下型態。第一步應抽 FSH、LH、testosterone，分辨 primary 與 central hypogonadism。",
        {
            "A": "睪丸超音波可看結構，但無法先分辨軸線問題，不是下一步最適當。",
            "B": "未先測 testosterone 與 gonadotropins 就直接補充男性荷爾蒙，可能掩蓋診斷。",
            "C": "腦下垂體/下視丘 MRI 適用於懷疑 central hypogonadism，但需先由 FSH/LH 結果支持。",
            "D": "FSH、LH、testosterone 可區分原發性睪丸衰竭與中樞性低性腺素，是最合適第一步。",
        },
        "男性性腺功能低下先測 testosterone、FSH、LH，再決定影像或治療。",
        "Hypogonadism workup starts with FSH/LH/testosterone。",
        "Male hypogonadism evaluation",
        "先用 FSH/LH 分 primary vs secondary hypogonadism。",
    ),
    update(
        57,
        "鉤端螺旋體病常由受感染動物尿液污染的水或土壤傳播。初期常有發燒、頭痛、肌肉痠痛，尤其小腿肌痛；嚴重者可黃疸、腎衰竭與出血。",
        {
            "A": "重要傳播途徑是動物尿液污染環境，不是蚊子叮咬。",
            "B": "發燒、頭痛、肌肉酸痛是最初常見症狀，敘述正確。",
            "C": "Weil disease 可有明顯黃疸，膽紅素可升高；說膽紅素正常或些微升高不典型。",
            "D": "暗視野顯微鏡敏感度與特異度有限；診斷常用血清學 MAT 或 PCR，非最準確單一方法。",
        },
        "Leptospirosis 早期發燒、頭痛、肌痛；傳播來自動物尿液污染水土。",
        "Leptospirosis 初期症狀：fever、headache、myalgia。",
        "Leptospirosis",
        "鉤端螺旋體不是蚊媒；嚴重時可黃疸與腎衰竭。",
    ),
    update(
        58,
        "化療後 neutropenic fever 需立即給抗綠膿桿菌的廣效 beta-lactam 單方治療；cefepime 是常用選項。",
        {
            "A": "ertapenem 沒有 Pseudomonas 活性，不適合作為高風險嗜中性球低下發燒單方經驗治療。",
            "B": "cefepime 覆蓋 Pseudomonas，常用於 febrile neutropenia 的單方經驗治療。",
            "C": "tigecycline 血中濃度與 Pseudomonas 覆蓋不足，不適合作為此情境單方首選。",
            "D": "daptomycin 只涵蓋革蘭陽性菌，且不能治療肺炎；不適合單方處理 neutropenic fever。",
        },
        "Febrile neutropenia 經驗治療需 anti-pseudomonal beta-lactam，如 cefepime。",
        "Neutropenic fever monotherapy：cefepime。",
        "Febrile neutropenia antibiotics",
        "Ertapenem 不抗 Pseudomonas，不能當高風險單方首選。",
    ),
    update(
        59,
        "孕婦疑似流感屬高風險族群，若症狀符合應儘早使用 oseltamivir，不因懷孕而避免抗病毒藥。",
        {
            "A": "詢問旅遊史與流感接觸史有助於感染風險與群聚判斷。",
            "B": "醫療工作者群聚症狀需通知感染管制並依規定通報，避免院內傳播。",
            "C": "輕症可居家休養與自我健康管理，但孕婦仍須評估抗病毒治療。",
            "D": "懷孕是流感併發症高風險，oseltamivir 可使用；說不建議任何抗病毒治療是不恰當。",
        },
        "孕婦疑似流感應儘早給 oseltamivir；懷孕不是抗病毒禁忌。",
        "Pregnancy influenza：use oseltamivir early。",
        "Influenza in pregnancy",
        "孕婦流感屬高風險，不應因懷孕拒用抗病毒藥。",
    ),
    update(
        60,
        "糖尿病人右眼視力模糊、鼻腔黑色分泌物提示侵襲性鼻竇眼眶黴菌感染；官方選項以麴菌為答案，需依附圖病理型態判斷。若看到有隔、銳角分枝菌絲會偏 Aspergillus。",
        {
            "A": "Aspergillus 可造成侵襲性鼻竇炎，病理常見有隔菌絲與銳角分枝；官方答案採此判讀。",
            "B": "Candida 常見酵母與假菌絲，較少以黑色鼻分泌物、眼眶侵犯作為典型題幹。",
            "C": "非結核分枝桿菌是抗酸菌感染，不會呈現黴菌菌絲病理。",
            "D": "金黃色葡萄球菌是細菌，不符合題幹附圖病理黴菌感染方向。",
        },
        "侵襲性鼻竇黴菌感染需依病理菌絲型態分 Aspergillus 與 Mucorales；本題官方為 Aspergillus。",
        "有隔銳角分枝菌絲支持 Aspergillus。",
        "Invasive fungal sinusitis pathology",
        "糖尿病黑色鼻分泌物是黴菌感染警訊，圖題要看菌絲型態。",
        notes=["本題依附圖判斷；臨床文字也會讓人想到 mucormycosis，但選項未列 Mucorales，故保留官方 Aspergillus。"],
    ),
    update(
        61,
        "HIV 合併肺結核且 CD4 70，開始抗結核治療後應儘早加入 ART，但為降低藥物交互作用與 IRIS 風險，通常在抗結核治療 2-4 週後開始；CD4 很低者不應延後數月。",
        {
            "A": "立即同步治療會增加藥物交互作用、副作用與 IRIS 管理困難，通常先讓抗結核治療啟動。",
            "B": "CD4 <50 或接近重度免疫低下時，抗結核治療 2-4 週後開始 ART 是合適時點。",
            "C": "延到 3-4 個月對 CD4 70 的病人太晚，會增加 HIV 相關併發症。",
            "D": "等抗結核結束才治療 HIV 會不必要延誤 ART。",
        },
        "HIV/TB 共病：先啟動 TB treatment，重度免疫低下者約 2-4 週後開始 ART。",
        "HIV with TB and low CD4：start ART after 2-4 weeks of TB therapy。",
        "HIV TB ART timing",
        "CD4 低者 ART 不應延後到抗結核治療結束。",
    ),
    update(
        62,
        "多年反覆濃痰咳嗽，年輕時反覆感染，X 光兩側下肺葉 tram-track sign，典型為支氣管擴張症。",
        {
            "A": "ABPA 常與氣喘、嗜酸性球、IgE 與中央支氣管擴張相關，題幹無這些線索。",
            "B": "氣喘以可逆性喘鳴與氣道阻塞為主，不會典型造成長年濃痰與 tram tracks。",
            "C": "肺泡蛋白沉積症常見 crazy paving 與低氧，不以反覆感染濃痰和 tram-track 為主。",
            "D": "bronchiectasis 會有慢性大量膿痰、反覆感染與 tram-track sign。",
        },
        "慢性膿痰、反覆感染與 tram-track sign 指向 bronchiectasis。",
        "Tram-track sign + chronic purulent sputum = bronchiectasis。",
        "Bronchiectasis diagnosis",
        "支氣管擴張症常見反覆感染與下肺葉 tram tracks。",
    ),
    update(
        63,
        "支氣管擴張症治療包括痰液清除、急性惡化抗生素、必要時支氣管擴張劑或化痰藥；局部反覆感染且內科難控制時可考慮切除。",
        {
            "A": "NTM 培養陽性不等於一定有 NTM lung disease，也不一定具傳染性；需看症狀、影像與多次培養標準。",
            "B": "無急性發作時不一定長期預防性抗生素，需依惡化頻率與菌種風險決定。",
            "C": "支氣管擴張劑、化痰與呼吸道清除對部分病人有幫助，不能說無幫助。",
            "D": "病灶局部且反覆難控制感染或出血時，可考慮外科切除。",
        },
        "支氣管擴張症以氣道清除與惡化期抗生素為主；局部難治病灶可手術。",
        "Localized bronchiectasis with recurrent uncontrolled infection may undergo resection。",
        "Bronchiectasis treatment",
        "NTM 培養陽性需符合疾病診斷標準，不是立刻治療。",
    ),
    update(
        64,
        "針扎暴露處置要立即評估來源與被暴露者、抽 HIV/HBV/HCV 等檢驗、評估 PEP，不能因假期延到數天後才處置。",
        {
            "A": "來源者與被針扎者的 HIV 檢驗是暴露評估基本步驟。",
            "B": "HBV、HCV、梅毒等血清檢查可建立基線與後續追蹤。",
            "C": "告知空窗期與後續抽血時間是必要衛教。",
            "D": "PEP 與風險評估有時需在數小時內完成，不能安排年初四才到門診處理。",
        },
        "針扎暴露需立即處理與評估 PEP，不可延後數天。",
        "Needlestick injury requires immediate evaluation。",
        "Needlestick management",
        "職業暴露處置不能因假期延後。",
    ),
    update(
        65,
        "來源者 HIV 抗體陰性，但醫療工作者本人篩檢陽性，下一步不是 PEP，而是做確認試驗以判斷是否真的 HIV 感染；本題選 Western blot。",
        {
            "A": "通報通常需確認診斷後依規定進行；單一 screening test 陽性仍需確認。",
            "B": "Western blot 是傳統確認試驗，可用來確認 HIV screening test 陽性結果。",
            "C": "來源者陰性且本人篩檢陽性時，重點是確認本人感染狀態，不是暴露後預防投藥。",
            "D": "陽性 screening test 不能只觀察一個月，需立即確認。",
        },
        "HIV screening test 陽性需做確認試驗；職業暴露 PEP 要看來源者風險。",
        "Positive HIV screen -> confirmatory test。",
        "HIV confirmatory testing",
        "單一篩檢陽性不能當確診，也不能只觀察。",
    ),
    update(
        66,
        "台灣代謝症候群五項：男性腰圍 >=90 cm、血壓 >=130/85、空腹血糖 >=100、TG >=150、HDL 男性 <40。林先生腰圍 88 不算，血壓、血糖、TG 符合，HDL 42 不算，共 3 項。",
        {
            "A": "2 項少算了血壓、血糖、三酸甘油脂三個明確異常。",
            "B": "血壓 132/88、空腹血糖 106、TG 180 符合，共 3 項。",
            "C": "若把 HDL 42 誤算為異常才會到 4 項；男性 HDL 切點是 <40。",
            "D": "5 項需要腰圍與 HDL 也符合，但本題兩者未達標準。",
        },
        "台灣男性代謝症候群：腰圍 90、BP 130/85、glucose 100、TG 150、HDL <40。",
        "此題符合血壓、血糖、TG，共 3 項。",
        "Metabolic syndrome item count",
        "男性腰圍 88 與 HDL 42 不達代謝症候群異常標準。",
    ),
    update(
        67,
        "起身行走測驗（Timed Up and Go）評估行動能力、平衡與跌倒風險，不是坐骨神經功能檢查。16 秒通常屬異常，提示跌倒風險上升。",
        {
            "A": "由椅子起身、走 3 公尺、轉身走回坐下，就是 get-up-and-go 或 timed up and go test。",
            "B": "16 秒完成較慢，常視為行動功能下降與跌倒高風險。",
            "C": "此測驗評估整體移動、平衡與功能狀態，不是坐骨神經專一檢查。",
            "D": "跌倒後活動減少、行動測驗異常，可支持衰弱或衰弱風險評估。",
        },
        "Timed Up and Go 評估行動功能與跌倒風險，不是坐骨神經測驗。",
        "TUG test assesses mobility and fall risk。",
        "Timed Up and Go test",
        "走 3 公尺來回坐下的測驗重點是跌倒風險。",
    ),
    update(
        68,
        "雙向轉診需要家庭醫師整合不同層級醫療資源、安排病人流向與資訊回饋，最能體現協調性。",
        {
            "A": "可近性指病人容易取得醫療服務，不是轉診制度的核心特色。",
            "B": "負責性強調對病人健康結果與照護品質負責，與轉診有關但不是最直接。",
            "C": "協調性是連結專科、醫院與社區資源，正是雙向轉診的重點。",
            "D": "持續性指長期醫病關係與連續照護；轉診可支持它，但題目問制度特色最直接是協調性。",
        },
        "家庭醫師的轉診角色體現 coordination：整合不同醫療層級與資源。",
        "雙向轉診是家庭醫師協調性的表現。",
        "Family medicine coordination",
        "轉診制度重點是協調照護。",
    ),
    update(
        69,
        "慢性疾病運動處方可採分段累積，只要總量達標即可；要求每次必須連續 30-60 分鐘不符合安全、漸進與個人化原則。",
        {
            "A": "有氧、阻力與伸展分別改善心肺、肌力與柔軟度，敘述合適。",
            "B": "能說話不能唱歌是中等強度的實用主觀判斷。",
            "C": "每週至少 3 天是常見最低頻率建議，依疾病與能力調整。",
            "D": "運動可分段累積，例如每次 10 分鐘以上逐步增加，不必每次連續半小時到一小時。",
        },
        "慢性病運動可分段累積，重點是安全漸進與總運動量。",
        "Exercise prescription can be accumulated in bouts。",
        "Chronic disease exercise prescription",
        "不可分段做是錯誤的運動處方觀念。",
    ),
    update(
        70,
        "對病人與臨床決策最有意義的是知道檢查結果出來後代表什麼：陽性時真正有病機率與陰性時真正沒病機率，也就是 PPV 與 NPV。",
        {
            "A": "敏感度與特異度描述檢查本身特性，但病人拿到結果後更想知道結果代表的機率。",
            "B": "敏感度加 PPV 只涵蓋一部分問題，沒有說明陰性結果的意義。",
            "C": "特異度加 NPV 也只涵蓋一部分問題，少了陽性結果的臨床意義。",
            "D": "PPV 與 NPV 直接回答陽性或陰性結果對該病人的實際意義，最有臨床溝通價值。",
        },
        "臨床解釋檢查結果時，PPV/NPV 比 sensitivity/specificity 更貼近病人決策。",
        "Test result counseling relies on PPV and NPV。",
        "Screening test clinical meaning",
        "陽性預測值與陰性預測值回答結果出來後的機率。",
    ),
    update(
        71,
        "非語言溝通包括眼神、姿勢、表情、距離與語調。頭微傾且注視對方通常表示注意與興趣；雙臂交叉較常被解讀為防衛或封閉。",
        {
            "A": "非語言訊息在溝通中占很大比例，不只是十分之一。",
            "B": "基本情緒表情有跨文化共通性；不能說在不同文化差異都很大。",
            "C": "頭部微傾並注視對方，通常傳達專注、聆聽與興趣。",
            "D": "雙臂交叉常表示防衛、保留或不開放，不是典型放鬆姿態。",
        },
        "非語言溝通中，眼神與開放姿勢可傳達專注；雙臂交叉常顯得防衛。",
        "Head tilt with eye contact suggests attentive listening。",
        "Nonverbal communication",
        "非語言訊號會影響醫病溝通品質。",
    ),
    update(
        72,
        "社區健康促進計畫應從社區診斷、界定對象、確認健康問題、設計介入與評估效果開始；若把活動同時拿來宣傳診所服務，會偏離公共健康促進並有利益衝突疑慮。",
        {
            "A": "界定目標族群是健康促進計畫的基本步驟。",
            "B": "確認社區健康課題屬於需求評估，必要且正確。",
            "C": "擬定介入計畫與執行步驟是計畫設計核心。",
            "D": "衛教活動若同時宣傳診所服務項目，容易變成行銷，不符合社區健康促進專業目的。",
        },
        "社區健康促進以社區需求與介入評估為中心，不應混入診所行銷。",
        "Community health promotion should not become clinic advertising。",
        "Community health promotion planning",
        "先界定族群與健康問題，再設計介入，不做服務宣傳。",
    ),
    update(
        73,
        "末期病人譫妄合併躁動、幻覺，若需藥物控制，首選通常是低劑量抗精神病藥物，例如 haloperidol；鎮靜安眠藥可能加重譫妄。",
        {
            "A": "zolpidem 可增加混亂、跌倒與譫妄，不是首選。",
            "B": "haloperidol 可控制譫妄相關躁動與幻覺，是常用首選。",
            "C": "肌肉鬆弛劑不能治療譫妄，還可能造成嗜睡。",
            "D": "benzodiazepine 除酒精或鎮靜劑戒斷等特殊情境外，常會惡化譫妄。",
        },
        "末期譫妄需藥物時常用 haloperidol；避免不必要 benzodiazepine 或安眠藥。",
        "Delirium agitation first-line: antipsychotic such as haloperidol。",
        "Terminal delirium medication",
        "譫妄不是失眠，治療首選不是安眠藥。",
    ),
    update(
        74,
        "骨髓炎診斷需及早，通常先做 X 光作基線與尋找骨破壞；早期 X 光可能正常，若懷疑脊椎或早期病灶，MRI 更敏感。",
        {
            "A": "診斷延遲會增加骨壞死、慢性感染與功能損傷，預後有關。",
            "B": "一般先做患部 X 光，部分慢性或明顯病例可提供診斷線索。",
            "C": "脊椎骨髓炎常需要 MRI 評估椎體、椎間盤與硬膜外膿瘍。",
            "D": "白血球同位素掃描可在特定情境使用，但不是必要診斷工具。",
        },
        "骨髓炎影像常先 X 光，MRI 對早期與脊椎病灶更敏感。",
        "Osteomyelitis workup often starts with X-ray; MRI is more sensitive。",
        "Osteomyelitis diagnosis",
        "診斷及時會影響骨髓炎預後。",
    ),
    update(
        75,
        "酗酒、肝硬化與 CT 箭頭異常，官方答案指向門脈高壓造成的側枝循環或相關影像表現。肝硬化最常見重要血流併發症就是 portal hypertension。",
        {
            "A": "肝硬化會造成門脈壓上升，進而形成靜脈曲張、側枝循環、脾大或腹水，是最符合官方圖題的原因。",
            "B": "淋巴結腫大可在 CT 上呈現結節，但與酗酒肝硬化脈絡不如門脈高壓直接。",
            "C": "HCC 可見肝內腫塊與動脈增強，但題目箭頭異常官方並非指向腫瘤本身。",
            "D": "腹腔內出血會有高密度血液或休克脈絡；題幹慢性肝硬化較支持門脈高壓。",
        },
        "肝硬化影像若見側枝循環、靜脈曲張、脾大或腹水，要想到 portal hypertension。",
        "Cirrhosis complications on CT often reflect portal hypertension。",
        "Portal hypertension imaging",
        "肝硬化的血流併發症核心是門脈高壓。",
        notes=["本題依 CT 圖箭頭判讀；目前 JSON 未包含影像，解說依官方答案保留。"],
    ),
    update(
        76,
        "老人肋骨骨折後因疼痛不敢深呼吸與咳痰，容易肺不張、痰液滯留，最常引發肺炎。",
        {
            "A": "疼痛造成通氣不足與清痰能力下降，肺炎是老人肋骨骨折最常見重要併發症。",
            "B": "肺栓塞可因臥床增加風險，但不是肋骨骨折最常引發的直接併發症。",
            "C": "張力性氣胸多與嚴重胸部外傷或肺裂傷相關，不是老人單純肋骨骨折最常見。",
            "D": "心包填塞通常來自心臟或大血管穿刺傷，不是常見肋骨骨折併發症。",
        },
        "老人肋骨骨折最怕疼痛導致低通氣與痰液滯留，進而肺炎。",
        "Elderly rib fracture complication: pneumonia。",
        "Rib fracture elderly complication",
        "止痛與肺部復健可降低肋骨骨折後肺炎風險。",
    ),
    update(
        77,
        "化學災難現場分熱區、暖區、冷區。熱區污染最高，主要做救援與快速移出；除污通常在暖區，醫療處置與後送在冷區。",
        {
            "A": "除污不應在冷區進行，否則會把污染帶到安全區；通常在暖區除污。",
            "B": "檢傷可在暖區或除污後依流程進行，但化災現場需先兼顧污染控制。",
            "C": "熱區只做必要搜救與移出污染區，避免在高污染區停留處置，是最正確原則。",
            "D": "化災通常先移出與除污，再進入完整檢傷與治療；不能先在污染區大規模檢傷。",
        },
        "化災熱區救出，暖區除污，冷區治療與後送。",
        "Chemical disaster zones: hot rescue, warm decontamination, cold treatment。",
        "Chemical disaster zones",
        "熱區不做完整醫療處置，重點是搜救並離開污染區。",
    ),
    update(
        78,
        "HHS 以嚴重高血糖、高血清滲透壓與脫水為主。血鈉需校正高血糖造成的稀釋效應，單看實測鈉不能可靠代表體液缺少程度。",
        {
            "A": "HHS 常見血糖 >600、pH >7.3、bicarbonate >15，酮酸較不明顯，敘述正確。",
            "B": "高血糖會造成水分由細胞內移到細胞外，使血鈉被稀釋；需用 corrected sodium，不能當可靠體液缺水指標。",
            "C": "HHS 可因乳酸、腎衰竭或輕度酮症出現代謝性酸中毒，但通常不像 DKA 明顯。",
            "D": "血清滲透壓越高，意識改變與昏迷風險越高，相關性明確。",
        },
        "HHS 要看 corrected sodium 與 serum osmolality；實測鈉不能可靠反映缺水。",
        "HHS serum sodium must be corrected for hyperglycemia。",
        "Hyperosmolar hyperglycemic state",
        "HHS 嚴重度與血清滲透壓和意識狀態密切相關。",
    ),
    update(
        79,
        "人體試驗知情同意必須告知受試者其他可能治療方式與說明，不能因想增加收案而省略。這是法律與倫理都要求的基本內容。",
        {
            "A": "說知情同意不包括其他治療方式是錯的；受試者需要知道替代選項才能自主決定。",
            "B": "醫療法人體試驗告知事項包括其他可能治療方式及說明，因此 A 醫師必須告知。",
            "C": "知情同意不只是倫理期待，相關法律明確規範告知內容。",
            "D": "研究者不能自行刪減會影響受試者決定的重要資訊。",
        },
        "人體試驗知情同意需告知其他可能治療方式，不能為收案省略。",
        "Clinical trial informed consent must include alternative treatments。",
        "Human trial informed consent",
        "受試者自主決定需要完整替代治療資訊。",
    ),
    update(
        80,
        "醫療法要求醫療機構採必要措施確保醫事人員執業安全，警察也應協助排除妨礙醫療業務行為；若涉及刑責，並非一律由醫療機構主動提出告訴才可處理。",
        {
            "A": "不得以強暴、脅迫、恐嚇或其他非法方法妨礙醫療業務，是醫療安全保護重點。",
            "B": "警察機關應協助排除或制止妨礙醫療業務的行為，敘述正確。",
            "C": "涉及刑事責任時，依法可能由檢警偵辦或依罪名性質處理，不是必須由醫療機構主動告訴才成立，因此此句錯誤。",
            "D": "醫療法第 24 條要求醫療機構採必要措施確保醫事人員執業安全，敘述正確。",
        },
        "醫療暴力或妨礙醫療業務涉及刑責時，不是全靠醫療機構主動告訴才處理。",
        "醫療法保障醫事人員執業安全，警察應協助排除妨礙行為。",
        "Medical Care Act workplace safety",
        "醫療機構須採必要安全措施；刑責處理不以機構主動告訴為唯一前提。",
    ),
]


def main():
    questions = load_questions()
    if len(questions) != 80:
        raise SystemExit(f"expected 80 questions, got {len(questions)}")
    if sorted(item["question_number"] for item in UPDATES) != list(range(1, 81)):
        raise SystemExit("updates must cover Q1-Q80 exactly")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    by_num = {item["question_number"]: item for item in UPDATES}
    for start in range(1, 81, 10):
        end = start + 9
        batch = {
            "source_file": SOURCE_FILE,
            "dataset_id": DATASET_ID,
            "range": {"start": start, "end": end},
            "updates": [by_num[qnum] for qnum in range(start, end + 1)],
        }
        out = OUT_DIR / f"q{start:03d}-q{end:03d}.json"
        out.write_text(json.dumps(batch, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {len(list(OUT_DIR.glob('q*.json')))} update files to {OUT_DIR}")


if __name__ == "__main__":
    main()
