import json
from pathlib import Path


SOURCE_FILE = "public/data/exams/109-1/medicine-2.json"
DATASET_ID = "109-1_medicine-2"
READABLE_SOURCE = Path("scratch/rewrite_updates/109-1_medicine-2/readable_source.json")
OUT_DIR = Path("scratch/rewrite_updates/109-1_medicine-2")
STAMP = "2026-07-13T00:00:00+08:00"


NOTES = {
    1: ("氣性壞疽典型由 Clostridium perfringens 等厭氧梭菌造成，題目問錯誤敘述。",
        {"A": "錯誤。最常見致病菌不是化膿性鏈球菌，而是產氣莢膜梭菌等 Clostridium，會產生毒素與氣體。",
         "B": "正確。傷口受污染後可造成急性壞死性肌炎，病灶進展很快並可沿肌肉筋膜擴散。",
         "C": "正確。治療重點是立即清創、給予有效抗生素；高壓氧可作為輔助以抑制厭氧菌。",
         "D": "正確。氣性壞疽沒有常規可用的保護性疫苗，預防靠傷口處理與早期治療。"},
        "氣性壞疽最典型是 Clostridium perfringens，而非 Streptococcus pyogenes。"),
    2: ("白喉桿菌的流行病學、毒素基因與預防是本題重點。",
        {"A": "錯誤。白喉桿菌不是耐酸性染色陽性；耐酸性染色是分枝桿菌等的特色。",
         "B": "正確。白喉桿菌主要自然宿主是人類，因此帶菌者與病人是重要感染來源。",
         "C": "錯誤。白喉毒素基因由溶原性噬菌體攜帶，不是位於細菌質體上。",
         "D": "錯誤。白喉可用類毒素疫苗預防，常見於 DTaP/Tdap 接種。"},
        "白喉毒素來自噬菌體，白喉可由類毒素疫苗預防，人類是主要宿主。"),
    3: ("ESAT-6、CFP-10 刺激 T 細胞釋放 IFN-gamma 是 IGRA 的核心。",
        {"A": "錯誤。Rickettsia rickettsii 造成落磯山斑疹熱，診斷不靠 ESAT-6/CFP-10。",
         "B": "錯誤。Aspergillus fumigatus 是黴菌，與 IGRA 使用的結核特異抗原無關。",
         "C": "錯誤。Mycoplasma pneumoniae 常引起非典型肺炎，不以 ESAT-6/CFP-10 偵測。",
         "D": "正確。ESAT-6 與 CFP-10 是結核分枝桿菌相關抗原，用於干擾素釋放試驗。"},
        "IGRA 以 ESAT-6/CFP-10 偵測結核分枝桿菌感染。"),
    4: ("人類單核細胞艾利希體症是細胞內感染，治療首選 doxycycline；題目問錯誤。",
        {"A": "錯誤。penicillin、aminoglycoside、macrolide 不是主要有效治療，典型治療為 doxycycline。",
         "B": "正確。Ehrlichia 可在單核球與巨噬細胞內形成 morulae 並繁殖。",
         "C": "正確。常見白血球或血小板下降、轉胺酶上升等實驗室異常。",
         "D": "正確。可用 PCR/核酸檢測與血清學檢驗輔助診斷。"},
        "Ehrlichiosis 是細胞內感染，典型治療是 doxycycline，不是青黴素類。"),
    5: ("肺炎鏈球菌的莢膜、發炎機轉與疫苗成分是常考點；題目問錯誤。",
        {"A": "正確。莢膜是重要毒力因子，可抗吞噬並影響血清型。",
         "B": "正確。肺泡腔中增殖與發炎滲出會造成典型肺炎。",
         "C": "正確。細胞壁成分可引發補體與發炎反應，導致組織傷害。",
         "D": "錯誤。多價肺炎鏈球菌疫苗主要針對莢膜多醣，不是體表蛋白質。"},
        "肺炎鏈球菌疫苗重點是莢膜多醣抗原。"),
    6: ("Enterobacteriaceae 的 O antigen 是 LPS 的外側多醣部分。",
        {"A": "錯誤。控制物質進出較符合外膜孔蛋白等構造，不是 O 抗原。",
         "B": "錯誤。flagellin 是 H 抗原，與 O 抗原不同。",
         "C": "正確。O 抗原是脂多醣 LPS 的多醣側鏈，常用於血清分型。",
         "D": "錯誤。peptidoglycan 是細胞壁骨架，並非 O antigen。"},
        "革蘭陰性菌 O antigen 是 LPS 的一部分；H antigen 才是鞭毛蛋白。"),
    7: ("C. difficile 常在抗生素後腸道菌相改變而致病。",
        {"A": "正確。長期或廣效抗生素破壞腸道菌相，是艱難梭菌感染的重要危險因子。",
         "B": "錯誤。ampicillin 和 clindamycin 可誘發感染；治療常用口服 vancomycin 或 fidaxomicin。",
         "C": "錯誤。其毒素造成腸炎與偽膜性結腸炎，不是肌肉痙攣。",
         "D": "錯誤。alpha toxin 造成軟組織壞死較符合 Clostridium perfringens。"},
        "抗生素後腹瀉與偽膜性結腸炎要想到 C. difficile。"),
    8: ("題目問節肢動物叮咬傳播且能在人體細胞內繁殖的病原。",
        {"A": "錯誤。Shigella 是糞口傳染；Brucella 可細胞內生存但不是主要節肢動物叮咬傳播。",
         "B": "正確。Francisella tularensis 可由蜱等節肢動物傳播；Anaplasma phagocytophilum 也由蜱傳播且細胞內寄生。",
         "C": "錯誤。Brucella 不是典型節肢動物叮咬傳播，雖然 Anaplasma 符合。",
         "D": "錯誤。Shigella 不符合節肢動物傳播，Francisella 符合但組合不完整。"},
        "Francisella 與 Anaplasma 可由節肢動物傳播並在宿主細胞內存活。"),
    9: ("金黃色葡萄球菌常見毒力因子包含 coagulase、TSST-1、protein A。",
        {"A": "正確。coagulase 是金黃色葡萄球菌的重要鑑別與毒力因子。",
         "B": "正確。TSST-1 是可造成毒性休克症候群的超抗原。",
         "C": "錯誤。edema factor 是 Bacillus anthracis 毒素成分，不是 S. aureus 常見毒力因子。",
         "D": "正確。protein A 可結合 IgG Fc 端，干擾調理吞噬。"},
        "S. aureus 有 coagulase、protein A、TSST-1；edema factor 屬炭疽毒素。"),
    10: ("腺病毒是無套膜線型雙股 DNA 病毒，可形成核內包涵體。",
        {"A": "錯誤。E6/E7 抑制 p53/Rb 是 HPV 的特徵。",
         "B": "正確。腺病毒感染上皮細胞後可在細胞核內形成包涵體。",
         "C": "錯誤。腺病毒是線型雙股 DNA，但沒有 envelope。",
         "D": "錯誤。腺病毒可在淋巴組織潛伏或持續存在，不是此選項描述的典型重點。"},
        "Adenovirus 是無套膜線型 dsDNA 病毒，常見核內包涵體。"),
    11: ("具有 reverse transcriptase 的病毒包含 retrovirus 與 hepatitis B virus。",
        {"A": "錯誤。乳突瘤病毒是 dsDNA 病毒，不靠反轉錄複製基因體。",
         "B": "錯誤。西尼羅河病毒是正股 RNA 黃病毒，不使用反轉錄酶。",
         "C": "正確。B 型肝炎病毒是部分雙股 DNA 病毒，複製過程有 RNA 中間體並使用 reverse transcriptase。",
         "D": "錯誤。RSV 是負股 RNA 病毒，使用 RNA-dependent RNA polymerase。"},
        "HBV 雖是 DNA 病毒，但複製週期需要 reverse transcriptase。"),
    12: ("Oseltamivir 是流感病毒 neuraminidase inhibitor。",
        {"A": "錯誤。蛋白酶抑制劑多用於 HIV 或 HCV 等治療，不是 oseltamivir 主要靶點。",
         "B": "正確。oseltamivir 抑制流感病毒 neuraminidase，阻止新病毒顆粒釋放。",
         "C": "錯誤。thymidine kinase 與 acyclovir 類抗疱疹病毒藥物活化有關。",
         "D": "錯誤。reverse transcriptase 是 HIV/HBV 相關靶點，不是 oseltamivir 的作用點。"},
        "Oseltamivir 抑制流感病毒 neuraminidase。"),
    13: ("Negri body 是狂犬病病毒感染神經細胞的典型包涵體。",
        {"A": "正確。狂犬病病毒可在神經細胞胞質形成 Negri bodies。",
         "B": "錯誤。HSV 常見核內包涵體與 Cowdry type A，不是 Negri body。",
         "C": "錯誤。poxvirus 在胞質複製，可見 Guarnieri bodies。",
         "D": "錯誤。HBV 的病理重點是肝細胞感染與免疫傷害，不產生 Negri bodies。"},
        "Negri bodies 指向 rabies virus。"),
    14: ("抗病毒胜肽類藥物以 HIV fusion inhibitor enfuvirtide 為代表。",
        {"A": "正確。enfuvirtide 是胜肽類融合抑制劑，作用於 HIV gp41。",
         "B": "錯誤。ganciclovir 是核苷類似物，主要治療 CMV 等感染。",
         "C": "錯誤。lamivudine 是核苷類 reverse transcriptase inhibitor。",
         "D": "錯誤。oseltamivir 是小分子 neuraminidase inhibitor。"},
        "Enfuvirtide 是 HIV gp41 fusion inhibitor，屬胜肽類抗病毒藥。"),
    15: ("德國麻疹病毒可由 MMR 預防；診斷不以常規喉拭子培養為主，題目問錯誤。",
        {"A": "正確。rubella 的自然宿主主要是人類。",
         "B": "正確。rubella 只有一種血清型，因此疫苗保護力可涵蓋主要感染。",
         "C": "正確。MMR 疫苗可預防麻疹、腮腺炎與德國麻疹。",
         "D": "錯誤。臨床診斷常依血清學或分子檢測，常規病毒培養不是主要診斷依據。"},
        "Rubella 可用 MMR 預防；診斷重點多為血清學/分子檢測。"),
    16: ("Malassezia furfur 是親脂性酵母菌，培養需要脂質。",
        {"A": "錯誤。澱粉不是提升 Malassezia 培養率的關鍵營養。",
         "B": "錯誤。L-cysteine 常見於某些特殊菌培養需求，不是此菌重點。",
         "C": "正確。Malassezia furfur 親脂，培養基加入橄欖油可提高培養率。",
         "D": "錯誤。N-acetylglucosamine 不是此題所問的主要培養添加物。"},
        "Malassezia furfur 親脂，培養常需外加油脂。"),
    17: ("Candida glabrata 通常以酵母型存在，不像 C. albicans 常形成假菌絲/菌絲。",
        {"A": "錯誤。Candida tropicalis 可形成假菌絲或菌絲樣構造。",
         "B": "錯誤。Candida albicans 具 germ tube、假菌絲與菌絲形成能力。",
         "C": "正確。Candida glabrata 通常不形成菌絲，較以小型酵母型為主。",
         "D": "錯誤。Candida parapsilosis 可形成假菌絲。"},
        "Candida glabrata 通常不形成菌絲，是與 C. albicans 的高頻對比。"),
    18: ("M cell 的功能是跨上皮運送腸腔抗原到 Peyer patches 等淋巴組織。",
        {"A": "錯誤。M 細胞本身不是主要殺菌效應細胞。",
         "B": "錯誤。製造抗體是漿細胞功能，不是 M 細胞主要功能。",
         "C": "正確。M 細胞負責捕捉並轉運腸道抗原到下方免疫組織。",
         "D": "錯誤。保護表皮屏障較屬上皮屏障與黏液等功能，不是 M 細胞重點。"},
        "M cell 是腸道黏膜抗原取樣與轉運細胞。"),
    19: ("RIG-I-like receptors 主要辨識病毒 RNA，不是 DNA 病毒的 DNA；題目問錯誤。",
        {"A": "正確。TLR 是演化保守的先天免疫受體，無脊椎動物也有相關系統。",
         "B": "正確。TLR3 辨識雙股 RNA，TLR7/8 辨識單股 RNA。",
         "C": "正確。NOD-like receptors 位於胞內，可辨識細菌細胞壁成分並引發發炎訊號。",
         "D": "錯誤。RIG-I-like receptors 主要感知病毒 RNA；胞質 DNA 另由 cGAS-STING 等路徑偵測。"},
        "RIG-I/MDA5 感知病毒 RNA；胞質 DNA 另有 cGAS-STING 等路徑。"),
    20: ("TCR 需 CD3 複合體傳遞訊號，CD3 的關鍵 motif 是 ITAM，不是 ITIM；題目問錯誤。",
        {"A": "正確。TCR alpha/beta 鏈胞質端短，無法獨立有效傳遞訊號。",
         "B": "正確。TCR 與 CD3 複合體共同表現在細胞表面。",
         "C": "正確。CD3 複合體含 ITAM，磷酸化後啟動 T 細胞訊號。",
         "D": "錯誤。ITIM 是抑制性 motif；CD3 促進活化主要靠 ITAM。"},
        "TCR 辨識抗原，CD3 的 ITAM 負責活化訊號傳遞。"),
    21: ("pre-B cell receptor 成功表現代表重鏈重排成功，會進入增殖階段。",
        {"A": "錯誤。輕鏈重組多在 pre-BCR 訊號後才進一步發生。",
         "B": "錯誤。表面 IgM 是未成熟 B 細胞階段的特徵。",
         "C": "正確。pre-BCR 訊號促進前期 B 細胞快速分裂與擴增。",
         "D": "錯誤。此階段尚未以成熟 BCR 接受專一性抗原刺激。"},
        "pre-BCR 訊號表示重鏈成功，下一步是增殖與輕鏈重排。"),
    22: ("IL-17 分泌型 CD4 T 細胞是 Th17，負責招募嗜中性球對抗胞外細菌/黴菌。",
        {"A": "錯誤。胞內病原主要由 Th1/IFN-gamma 與細胞毒 T 細胞反應處理。",
         "B": "正確。Th17 促進 neutrophil 反應，對清除胞外細菌很重要。",
         "C": "錯誤。胞外寄生蟲較偏 Th2、IgE 與嗜酸性球反應。",
         "D": "錯誤。抑制過度發炎主要是 Treg 功能。"},
        "Th17 分泌 IL-17，強化嗜中性球與胞外細菌防禦。"),
    23: ("本題考原發性免疫缺損；bare lymphocyte syndrome 影響 MHC II 表現與 CD4 發育。",
        {"A": "正確。APECED 與 AIRE 基因缺陷導致中樞耐受失常有關。",
         "B": "錯誤。MHC class II 無法表現會影響正選擇，使 CD4 T 細胞數目下降，不是數目正常只是表面無 MHC II。",
         "C": "正確。Omenn syndrome 常與 RAG1/RAG2 hypomorphic mutation 有關。",
         "D": "正確。部分白血球先天性缺陷可用造血幹細胞移植治療。"},
        "MHC II 缺陷會造成 CD4 T 細胞發育不足。"),
    24: ("分泌型 IgA 的 secretory component 來自上皮細胞的 poly-Ig receptor。",
        {"A": "錯誤。血清 IgA 與黏膜 IgA 的亞型比例不同，黏膜以分泌型 IgA 為主。",
         "B": "錯誤。促進 IgA class switching 常見的是 TGF-beta 等訊號，不是 IL-12。",
         "C": "正確。secretory component 由上皮細胞合成，協助 IgA 穿越上皮並抗蛋白酶分解。",
         "D": "錯誤。IgA 主要中和與阻斷附著，並不有效啟動古典補體路徑。"},
        "分泌型 IgA 的 secretory component 由上皮細胞提供。"),
    25: ("塵蟎過敏屬第一型過敏反應，以 IgE、肥大細胞脫顆粒為核心。",
        {"A": "錯誤。TGF-beta 較偏免疫調節與 IgA switching，不是急性過敏主軸。",
         "B": "錯誤。遲發性過敏反應是第四型過敏，非典型過敏性鼻炎主機轉。",
         "C": "錯誤。塵蟎過敏主要是特異性 IgE，而不是 IgA 顯著升高。",
         "D": "正確。肥大細胞被 IgE 交聯後釋放 histamine 等介質，引發流鼻水、打噴嚏與眼癢。"},
        "過敏性鼻炎是 IgE 介導的肥大細胞活化。"),
    26: ("Trastuzumab 是抗 HER2/neu 的單株抗體，常用於 HER2 陽性乳癌。",
        {"A": "正確。trastuzumab 靶向 HER2/neu 受體，抑制訊號並促進免疫效應。",
         "B": "錯誤。MAG-1 不是 trastuzumab 的治療靶點。",
         "C": "錯誤。MUC-1 是腫瘤相關抗原，但不是 Herceptin 的目標。",
         "D": "錯誤。CD20 是 rituximab 等抗體靶點，主要用於 B 細胞腫瘤。"},
        "Trastuzumab/Herceptin 對應 HER2/neu。"),
    27: ("減少 GVHD 的策略是降低成熟供者 T 細胞或提高 HLA 相合；混合淋巴球反應是檢測，不是去除 T 細胞。",
        {"A": "正確。alemtuzumab 抗 CD52，可降低成熟淋巴球以減少 GVHD。",
         "B": "錯誤。mixed lymphocyte reaction 用於評估異體反應性，不是減低 T 淋巴球數目的處理方法。",
         "C": "正確。MHC/HLA 相合度越高，成熟 T 細胞攻擊宿主的機率越低。",
         "D": "正確。抗胸腺球蛋白可耗竭 T 細胞，降低 GVHD 風險。"},
        "GVHD 預防重點是 HLA 相合與 T 細胞耗竭；MLR 是檢測方法。"),
    28: ("NK 細胞透過 missing-self 原理攻擊 MHC I 表現降低的細胞。",
        {"A": "正確。腫瘤細胞缺乏 MHC class I 時，抑制性 NK 受體訊號減少，較易被殺傷。",
         "B": "錯誤。MHC class II 主要和 CD4 T 細胞抗原呈現有關，不是 NK missing-self 的核心。",
         "C": "錯誤。T1 不是 NK 細胞判斷腫瘤細胞的標準抑制訊號。",
         "D": "錯誤。HER2/neu 是乳癌標靶抗原，不是 NK missing-self 的主要分子。"},
        "NK 細胞善於殺傷 MHC I 低表現的腫瘤或病毒感染細胞。"),
    29: ("瀰漫性糞小桿線蟲症常見於免疫低下，嗜酸性球可能不明顯；不只限腸肺。",
        {"A": "錯誤。第 1 句不完整，瀰漫性感染可侵犯腸肺以外器官。",
         "B": "錯誤。第 1 句錯，雖然第 3 句可見於重症或免疫低下者。",
         "C": "正確。第 2、3 句正確：免疫缺陷者易發生，嗜酸性球增加可不明顯。",
         "D": "錯誤。包含第 1 句，因此組合錯誤。"},
        "Strongyloides hyperinfection 常見免疫低下，嗜酸性球反應可不明顯。"),
    30: ("廣東住血線蟲人類感染常因食入未熟蝸牛等中間宿主，造成嗜酸性腦膜炎；人是偶然宿主。",
        {"A": "錯誤。正確不只 1 項，食入未熟帶蟲蝸牛與嗜酸性球明顯增加皆正確。",
         "B": "正確。第 1、4 句正確；人不是終宿主，蟲體也不只以『只侵犯』腦脊髓概括。",
         "C": "錯誤。第 2 句人為終宿主錯誤，因此不是 3 項。",
         "D": "錯誤。第 2、3 句不正確，所以不是 4 項皆正確。"},
        "A. cantonensis：食入未熟蝸牛，人體為偶然宿主，常見嗜酸性腦膜炎。"),
    31: ("日本血吸蟲感染皮膚穿入的是尾幼，病變有蟲卵肉芽腫與片山熱；囊幼是其他吸蟲概念。",
        {"A": "正確相關。血吸蟲尾幼可直接穿入皮膚造成感染。",
         "B": "不相關。囊幼 metacercariae 是肝吸蟲、肺吸蟲等常見感染型態，不是日本血吸蟲感染型。",
         "C": "正確相關。蟲卵沉積會引發肉芽腫與纖維化。",
         "D": "正確相關。急性血吸蟲症可出現 Katayama fever。"},
        "Schistosoma japonicum 感染型是尾幼，不是囊幼。"),
    32: ("Dipylidium caninum 的受孕節片可見卵囊/卵包，是鑑別特色。",
        {"A": "正確。犬複殖器絛蟲受孕節片有卵囊或卵包構造。",
         "B": "錯誤。牛肉絛蟲以子宮分枝與節片活動性等作鑑別，不是卵囊特色。",
         "C": "錯誤。縮小包膜絛蟲不以受孕節片卵囊為典型考點。",
         "D": "錯誤。廣節裂頭絛蟲有帶蓋卵等特色，不是此處所問。"},
        "Dipylidium caninum 的受孕節片具有卵囊/卵包。"),
    33: ("隱形眼鏡相關角膜炎加雙層壁囊體，典型是棘阿米巴。",
        {"A": "錯誤。Entamoeba coli 是腸道非致病或低致病阿米巴，與角膜炎無關。",
         "B": "錯誤。Entamoeba histolytica 主要造成腸炎與肝膿瘍。",
         "C": "錯誤。Naegleria fowleri 典型造成原發性阿米巴腦膜腦炎。",
         "D": "正確。Acanthamoeba 可造成隱形眼鏡相關角膜炎，囊體常呈雙層壁。"},
        "隱形眼鏡、角膜炎、雙層壁囊體指向 Acanthamoeba。"),
    34: ("Leishmania donovani 是內臟利什曼病/黑熱病的重要病原。",
        {"A": "錯誤。chiclero ulcer 傳統上與墨西哥利什曼原蟲等皮膚病灶較相關，不是巴西利什曼侵蝕耳軟骨的典型描述。",
         "B": "錯誤。Leishmania 主要在巨噬細胞內以 amastigote 增殖，不是所有有核細胞。",
         "C": "正確。Leishmania donovani 可造成黑熱病，也就是內臟利什曼病。",
         "D": "錯誤。L. tropica 主要皮膚型，但『從未』造成內臟病例過於絕對。"},
        "Kala-azar 的經典病原是 Leishmania donovani。"),
    35: ("病媒配對題：Chagas disease 是錐蝽傳播，不是采采蠅。",
        {"A": "正確。Aedes aegypti 可傳播黃熱病、登革熱等。",
         "B": "正確。Simulium 蚋傳播 Onchocerca volvulus，造成河川盲。",
         "C": "錯誤。采采蠅傳播非洲錐蟲病；Chagas disease 由錐蝽傳播 Trypanosoma cruzi。",
         "D": "正確。白蛉傳播利什曼原蟲。"},
        "采采蠅傳非洲睡眠病；Chagas disease 是錐蝽傳播。"),
    36: ("提高陽性判定切點會讓較少人被判為陽性。",
        {"A": "正確。切點從 7 提高到 8.5，無抽菸者被誤判陽性的機率下降；抽菸者被抓到的比例也下降，所以敏感度下降。",
         "B": "錯誤。偽陽率會下降，但敏感度不會上升。",
         "C": "錯誤。提高切點不會使偽陽率上升。",
         "D": "錯誤。提高切點同時造成偽陽率下降與敏感度下降。"},
        "診斷切點提高：特異度上升、偽陽率下降、敏感度下降。"),
    37: ("三組獨立樣本平均數比較，最恰當是 ANOVA。",
        {"A": "錯誤。Z 檢定通常用於單一或兩組特定條件下平均/比例檢定，不適合三組平均數整體比較。",
         "B": "正確。ANOVA 可檢定北中南三組男大學生平均身高是否相同。",
         "C": "錯誤。配對 t 檢定用於同一受試者前後或配對資料，不是三組獨立樣本。",
         "D": "錯誤。列聯表分析用於類別變項關聯，不是連續身高平均數比較。"},
        "三組以上獨立平均數比較用 ANOVA。"),
    38: ("病例與對照一對一配對，基因型又被二分成 AA/AG 對 GG，選配對二元資料的 McNemar 檢定。",
        {"A": "錯誤。線性迴歸適合連續結果變項，非此配對二元暴露比較。",
         "B": "錯誤。獨立卡方忽略病例對照的配對設計。",
         "C": "錯誤。配對 t 檢定用於連續變項的配對差異。",
         "D": "正確。McNemar 卡方檢定適合配對二元分類資料。"},
        "配對病例對照且暴露二分時，可用 McNemar 檢定。"),
    39: ("基因型改變藥物反應效果，屬於效果修飾。",
        {"A": "錯誤。干擾因子會同時和暴露、結果有關並扭曲關聯，不是描述反應差異的角色。",
         "B": "錯誤。拮抗因子不是流行病學中描述分層治療效果差異的標準用語。",
         "C": "正確。AA 基因型使同一治療藥物反應不同，代表效果修飾因子。",
         "D": "錯誤。分化因子不是此研究情境的適當概念。"},
        "某特徵改變治療效果大小時，稱為效果修飾因子。"),
    40: ("第 50 百分位數即中位數，可描述連續資料集中趨勢。",
        {"A": "錯誤。標準誤描述估計值精確度，不是原始資料分散程度；分散常用標準差或 IQR。",
         "B": "錯誤。幾何平均適合偏態的正連續資料，不適合類別資料集中趨勢。",
         "C": "錯誤。標準差描述連續資料分散，不描述類別資料集中趨勢。",
         "D": "正確。第 50 百分位數就是中位數，可描述連續資料集中位置。"},
        "中位數是第 50 百分位數，用於描述連續資料集中趨勢。"),
    41: ("主要溫室氣體包括 CO2、CH4、N2O 等；NH3 不是典型主要溫室氣體。",
        {"A": "錯誤。N2O 是重要溫室氣體。",
         "B": "錯誤。CO2 是最重要的人為溫室氣體之一。",
         "C": "錯誤。CH4 是重要溫室氣體。",
         "D": "正確。NH3 不是通常列舉的主要溫室效應氣體。"},
        "常考溫室氣體：CO2、CH4、N2O、含氟氣體；NH3 不是典型答案。"),
    42: ("雞肉必須煮熟是把烹調加熱列為關鍵控制點的概念。",
        {"A": "錯誤。危害評估是辨識可能危害，還不是指定煮熟這個管制點。",
         "B": "正確。HACCP 中將雞肉煮熟列為關鍵控制點，用以控制病原危害。",
         "C": "錯誤。這是在關鍵控制點後設定臨界限值或程序，題目較先問屬於哪個原則。",
         "D": "錯誤。監測系統是追蹤控制點是否達標，不是判定煮熟這件事本身。"},
        "HACCP 中『煮熟雞肉』是決定關鍵控制點。"),
    43: ("水俣病是甲基汞中毒造成的神經症狀。",
        {"A": "正確。汞，尤其甲基汞，會造成震顫、共濟失調、感覺與視野異常等神經毒性。",
         "B": "錯誤。鉈中毒常見落髮、腸胃與神經症狀，但非水俣病典型金屬。",
         "C": "錯誤。鎘中毒與腎傷害、骨軟化和痛痛病較相關。",
         "D": "錯誤。鋁暴露不會造成典型水俣病表現。"},
        "水俣病是甲基汞中毒。"),
    44: ("塵肺症常與無機粉塵如二氧化矽、石棉暴露相關。",
        {"A": "正確。報社印刷工暴露紙屑纖維不是典型塵肺症高危險暴露。",
         "B": "錯誤。噴砂二氧化矽暴露是矽肺症高危險工作。",
         "C": "錯誤。耐火磚製造可有石棉或矽塵暴露，屬危險族群。",
         "D": "錯誤。造船工人石棉暴露與石棉肺、間皮瘤風險相關。"},
        "塵肺症高風險暴露是二氧化矽、石棉、煤塵等無機粉塵。"),
    45: ("TWA 是各時段濃度乘時間後除以總工時。",
        {"A": "錯誤。70 ppm 低於加權計算值。",
         "B": "錯誤。74 ppm 接近但不是精確加權結果。",
         "C": "正確。TWA=(40x2.5+150x3+20x2.5)/8=600/8=75 ppm。",
         "D": "錯誤。80 ppm 高於正確時量平均濃度。"},
        "TWA=Σ濃度x時間/總時間。"),
    46: ("鉻酸/六價鉻暴露會造成鼻中膈潰瘍與穿孔。",
        {"A": "錯誤。四氯化碳主要毒性是肝腎傷害。",
         "B": "錯誤。二甲基甲醯胺主要與肝毒性等職業暴露問題相關。",
         "C": "正確。鉻酸具腐蝕性，長期暴露可造成鼻中膈穿孔。",
         "D": "錯誤。有機磷主要抑制 acetylcholinesterase，造成膽鹼性中毒。"},
        "鼻中膈穿孔的職業暴露常考鉻酸/六價鉻。"),
    47: ("依戒菸意願階段給不同介入，是跨理論模式的核心。",
        {"A": "錯誤。社會學習理論重視觀察學習、自我效能等，不是此處階段式改變模型。",
         "B": "錯誤。健康信念模式強調知覺罹患性、嚴重性、利益與障礙。",
         "C": "錯誤。操作性制約重視增強與懲罰。",
         "D": "正確。跨理論模式依無意圖、意圖、準備、行動、維持等階段設計介入。"},
        "依行為改變階段安排策略是跨理論模式。"),
    48: ("WHO 健康城市指標含死亡、出生、疾病與環境等指標；墮胎率不是典型健康城市指標。",
        {"A": "錯誤。低出生體重比率可反映母嬰健康。",
         "B": "錯誤。嬰兒死亡率是常用健康指標。",
         "C": "正確。墮胎率相對於活產數不是 WHO 健康城市常列的核心健康指標。",
         "D": "錯誤。總死亡率是常見人口健康指標。"},
        "健康城市常用死亡率、嬰兒死亡率、低出生體重等指標。"),
    49: ("強制性衛生政策仍需符合必要性、比例原則與最小侵害。",
        {"A": "正確。政策手段需能達成公共衛生目的，符合有效性。",
         "B": "正確。公共利益與個人權益限制間需符合比例。",
         "C": "正確。即使限制自由，也應採取最小侵害手段。",
         "D": "錯誤。不能毫無例外推動；仍須逐案考量必要性、比例與替代方案。"},
        "公共衛生強制措施須有效、必要、比例且最小侵害。"),
    50: ("SWOT 中 O 代表外部環境的機會。",
        {"A": "正確。O 是 opportunity，指外部機會。",
         "B": "錯誤。opponent 不是 SWOT 的標準項目。",
         "C": "錯誤。optimum 不是 SWOT 字母含義。",
         "D": "錯誤。operation 不是 SWOT 中 O 的意思。"},
        "SWOT：Strengths、Weaknesses、Opportunities、Threats。"),
    51: ("Fondaparinux 是間接 factor Xa inhibitor，不是主要抑制 thrombin；題目問錯誤。",
        {"A": "錯誤。fondaparinux 主要透過 antithrombin 抑制 factor Xa，對 thrombin 作用不是主軸。",
         "B": "正確。它與 antithrombin III 結合後增強對 factor Xa 的抑制。",
         "C": "正確。臨床使用為皮下注射，常為每日一次。",
         "D": "正確。主要腎排除，嚴重腎功能不全者不宜使用。"},
        "Fondaparinux 是 ATIII 依賴的間接 factor Xa inhibitor。"),
    52: ("骨質疏鬆治療包含 vitamin D、bisphosphonate、SERM 等；danazol 不是治療藥。",
        {"A": "錯誤。vitamin D 可改善鈣磷平衡並輔助骨質疏鬆治療。",
         "B": "錯誤。alendronate 是 bisphosphonate，可抑制蝕骨細胞。",
         "C": "錯誤。raloxifene 是 SERM，可用於停經後骨質疏鬆。",
         "D": "正確。danazol 是弱雄性素樣藥物，常用於子宮內膜異位症等，不改善骨質疏鬆。"},
        "Danazol 不是骨質疏鬆治療藥。"),
    53: ("Paget disease 可用抑制骨吸收的藥物，calcitonin 是可用選項之一。",
        {"A": "錯誤。thyroxine 用於甲狀腺素補充，非 Paget disease 治療。",
         "B": "錯誤。exenatide 是 GLP-1 receptor agonist，用於糖尿病等。",
         "C": "正確。calcitonin 可抑制蝕骨細胞，用於 Paget disease；雙磷酸鹽也常用。",
         "D": "錯誤。rosiglitazone 是 thiazolidinedione 類降血糖藥。"},
        "Paget disease 治療可用 bisphosphonates 或 calcitonin 抑制骨吸收。"),
    54: ("Beta blocker 可治療部分心房心律不整並降低心肌梗塞後死亡與猝死風險。",
        {"A": "錯誤。verapamil 可控制心室速率，但不如 beta blocker 符合預防 MI 後猝死的整體描述。",
         "B": "錯誤。quinidine 可抗心律不整但有促心律不整風險，不是此題最佳答案。",
         "C": "正確。propranolol 為 beta blocker，可用於心房心律不整控制並降低 MI 後復發與猝死風險。",
         "D": "錯誤。flecainide 不適合結構性心臟病或 MI 後病人，可能增加死亡風險。"},
        "MI 後保護與部分心房心律不整控制常考 beta blockers。"),
    55: ("Dihydropyridine 類鈣離子通道阻斷劑可抑制血管平滑肌鈣離子內流。",
        {"A": "錯誤。aliskiren 抑制 renin，降低 RAAS 活性。",
         "B": "錯誤。carvedilol 是 alpha/beta blocker。",
         "C": "錯誤。doxazosin 是 alpha-1 blocker。",
         "D": "正確。felodipine 是 dihydropyridine CCB，主要使血管平滑肌舒張。"},
        "Felodipine 以阻斷 L-type 鈣通道造成血管舒張。"),
    56: ("Cimetidine 具抗雄性素與抑制藥物代謝作用，長期使用可造成性功能問題。",
        {"A": "錯誤。omeprazole 是 PPI，陽痿不是其典型高頻副作用。",
         "B": "正確。cimetidine 可有抗雄性素作用，長期使用可能造成陽痿、男性女乳等。",
         "C": "錯誤。nizatidine 較少抗雄性素與 CYP 抑制問題。",
         "D": "錯誤。ranitidine 較 cimetidine 少見這類內分泌副作用。"},
        "H2 blocker 中 cimetidine 的抗雄性素副作用最典型。"),
    57: ("NSAID 抑制 prostaglandin 合成，可促進早產兒 PDA 關閉。",
        {"A": "錯誤。diclofenac 雖是 NSAID，但新生兒 PDA 常用 indomethacin 或 ibuprofen。",
         "B": "正確。ibuprofen 可抑制 prostaglandin 合成，促進動脈導管關閉。",
         "C": "錯誤。rofecoxib 為 COX-2 inhibitor，非 PDA 關閉常用藥。",
         "D": "錯誤。sulindac 不是早產兒 PDA 關閉的標準選擇。"},
        "PDA 關閉用 indomethacin/ibuprofen；PGE 則維持 PDA 開放。"),
    58: ("Topiramate 作用多重，但不是阻斷 glutamate transporter；題目問錯誤。",
        {"A": "正確。ethosuximide 抑制丘腦 T-type Ca channel，治療 absence seizure。",
         "B": "正確。tiagabine 抑制 GABA reuptake transporter，增加 GABA 活性。",
         "C": "錯誤。topiramate 可阻斷 AMPA/kainate glutamate receptors、增強 GABA、阻斷 Na channel 等，不是阻斷 glutamate transporter。",
         "D": "正確。valproic acid 可阻斷 Na channel，亦增加 GABA 活性。"},
        "Topiramate 抑制 AMPA/kainate 受體等，不是 glutamate transporter blocker。"),
    59: ("Nalbuphine 是 kappa agonist、mu antagonist/partial antagonist，不是單純活化 mu receptor。",
        {"A": "正確。nalbuphine 的止痛不主要靠活化 mu receptor，且可拮抗 mu 作用。",
         "B": "錯誤。morphine 是典型 mu opioid receptor agonist。",
         "C": "錯誤。methadone 是 mu agonist，另具 NMDA antagonist 特色。",
         "D": "錯誤。fentanyl 是強效 mu agonist。"},
        "Nalbuphine 是 kappa agonist、mu antagonist；嗎啡類多為 mu agonist。"),
    60: ("Isoproterenol 活化 beta receptor 增加 cAMP，不是 cGMP；題目問不會增加 cGMP。",
        {"A": "正確。isoproterenol 透過 beta receptor 活化 adenylyl cyclase，增加 cAMP。",
         "B": "錯誤。sodium nitroprusside 釋放 NO，活化 guanylyl cyclase 增加 cGMP。",
         "C": "錯誤。sildenafil 抑制 PDE5，減少 cGMP 分解而增加 cGMP。",
         "D": "錯誤。ANP 活化 particulate guanylyl cyclase，增加 cGMP。"},
        "Beta agonist 增加 cAMP；NO、ANP、PDE5 inhibitor 與 cGMP 相關。"),
    61: ("NaHCO3 鹼化尿液，使酸性藥物離子化後減少腎小管再吸收。",
        {"A": "錯誤。NaHCO3 的主要目的不是加速肝臟代謝。",
         "B": "錯誤。不是藉由改變血液中藥物穩定度解毒。",
         "C": "錯誤。提高 free form 不是主要機轉，且蛋白結合藥物的過濾受限。",
         "D": "正確。尿液鹼化使弱酸性藥物離子化，降低腎小管再吸收並促進排泄。"},
        "弱酸中毒給 NaHCO3 是尿液鹼化與 ion trapping。"),
    62: ("Imipenem 會被腎 dehydropeptidase 分解，因此與 cilastatin 合用。",
        {"A": "正確。cilastatin 抑制腎 dehydropeptidase，保護 imipenem 不被水解。",
         "B": "錯誤。minocycline 不需 cilastatin。",
         "C": "錯誤。sulfamethoxazole 不因腎 dehydropeptidase 而需 cilastatin。",
         "D": "錯誤。tobramycin 是 aminoglycoside，不與 cilastatin 固定併用。"},
        "Imipenem/cilastatin 是固定高頻考點。"),
    63: ("Beta-lactam 破壞細胞壁可促進 aminoglycoside 進入細菌，產生協同作用。",
        {"A": "錯誤。amantadine 是抗流感/抗帕金森藥，不是與 cefepime 協同的抗菌藥。",
         "B": "正確。amikacin 為 aminoglycoside，與 beta-lactam 併用可增加進入細菌而協同殺菌。",
         "C": "錯誤。azlocillin 本身也是 beta-lactam，題目問的是被促進進入的藥物類型。",
         "D": "錯誤。aztreonam 是 monobactam，非 aminoglycoside。"},
        "Beta-lactam 加 aminoglycoside 可協同，尤其腸球菌等感染常考。"),
    64: ("6-MP 由 xanthine oxidase 代謝，allopurinol 併用需減量以免毒性。",
        {"A": "錯誤。5-FU 主要由 DPD 等路徑代謝，非本題 xanthine oxidase 重點。",
         "B": "正確。6-mercaptopurine 會被 xanthine oxidase 代謝，allopurinol 會增加其毒性。",
         "C": "錯誤。methotrexate 主要與葉酸代謝與腎排除相關。",
         "D": "錯誤。6-thioguanine 較不依賴 xanthine oxidase 代謝。"},
        "Allopurinol 會提高 6-MP 毒性，併用需調整劑量。"),
    65: ("Calcineurin inhibitors 包含 cyclosporine 與 tacrolimus。",
        {"A": "錯誤。basiliximab 是抗 IL-2 receptor CD25 單株抗體。",
         "B": "錯誤。methylprednisolone 是類固醇，廣泛抑制發炎轉錄。",
         "C": "正確。cyclosporine 抑制 calcineurin，降低 IL-2 轉錄與 T 細胞活化。",
         "D": "錯誤。OKT3 是抗 CD3 抗體，不是 calcineurin inhibitor。"},
        "Cyclosporine/tacrolimus 抑制 calcineurin，降低 T 細胞活化。"),
    66: ("長期 glucocorticoid 會抑制骨形成、增加骨吸收，造成骨質疏鬆。",
        {"A": "錯誤。類狼瘡反應不是長期 glucocorticoid 最典型副作用。",
         "B": "正確。骨質疏鬆、糖尿病、感染風險、腎上腺抑制等是長期使用重要副作用。",
         "C": "錯誤。肝毒性不是 glucocorticoid 最典型限制毒性。",
         "D": "錯誤。長期外源性類固醇會抑制腎上腺軸，不是造成腎上腺腫瘤。"},
        "長期類固醇最常考副作用之一是骨質疏鬆。"),
    67: ("生長激素受體突變造成 IGF-1 缺乏/不反應，應補充 IGF-1 類藥物。",
        {"A": "錯誤。somatropin 是 recombinant GH；受體突變時效果有限。",
         "B": "錯誤。octreotide 是 somatostatin 類似物，抑制 GH 等分泌。",
         "C": "錯誤。atosiban 是 oxytocin receptor antagonist，用於早產相關情境。",
         "D": "正確。mecasermin 是 recombinant IGF-1，可用於 GH receptor 缺陷造成的生長障礙。"},
        "GH receptor defect 要繞過受體，使用 IGF-1 類 mecasermin。"),
    68: ("Oxybutynin 是 M3 muscarinic antagonist，可治療膀胱過動症。",
        {"A": "錯誤。pirenzepine 偏 M1 antagonist，與胃酸分泌較相關。",
         "B": "錯誤。trihexyphenidyl 用於帕金森症等中樞抗膽鹼用途。",
         "C": "錯誤。ipratropium 用於支氣管擴張，主要吸入治療 COPD/氣喘。",
         "D": "正確。oxybutynin 抑制膀胱逼尿肌 M3 receptor，減少急尿與頻尿。"},
        "膀胱過動症常用 M3 antagonist，如 oxybutynin。"),
    69: ("本題官方答案與常規藥理有衝突：5-HT3 antagonist 用於 CINV/PONV 的典型藥是 ondansetron。",
        {"A": "官方答案標為正確，但需複核。methysergide 主要是 5-HT2 antagonist/偏頭痛相關舊藥，不是典型 5-HT3 止吐藥。",
         "B": "錯誤。ketanserin 主要拮抗 5-HT2A，也有 alpha-1 作用。",
         "C": "錯誤。cyproheptadine 是 H1 與 serotonin antagonist，非 CINV/PONV 首選 5-HT3 antagonist。",
         "D": "依標準藥理應為正確。ondansetron 是 5-HT3 antagonist，常用於化療與術後噁心嘔吐。"},
        "5-HT3 antagonist 止吐代表藥是 ondansetron；此題官方答案 A 建議人工複核。",
        ["官方答案為 A，但標準藥理通常支持 ondansetron 為 5-HT3 antagonist，建議人工複核。"]),
    70: ("兒童病毒感染發燒首選退燒常用 acetaminophen，避免 aspirin 造成 Reye syndrome 風險。",
        {"A": "錯誤。兒童病毒感染時 aspirin 與 Reye syndrome 風險相關，通常避免使用。",
         "B": "正確。acetaminophen 是兒童常用首選退燒止痛藥。",
         "C": "錯誤。etodolac 是 NSAID，不是兒童病毒發燒首選。",
         "D": "錯誤。celecoxib 是 COX-2 inhibitor，不是此情境首選退燒藥。"},
        "兒童病毒感染發燒首選 acetaminophen，避免 aspirin。"),
    71: ("Baclofen 是 GABAB receptor agonist，治療痙攣。",
        {"A": "錯誤。dantrolene 作用於骨骼肌 ryanodine receptor，降低鈣釋放。",
         "B": "正確。baclofen 活化 GABAB receptor，抑制脊髓神經傳遞以減少痙攣。",
         "C": "錯誤。rocuronium 是非去極化神經肌肉阻斷劑。",
         "D": "錯誤。tizanidine 是 alpha-2 agonist，可治療痙攣但不是 GABAB agonist。"},
        "GABAB agonist 治療痙攣代表藥：baclofen。"),
    72: ("非典型抗精神病藥造成 EPS 較少，與 D2 阻斷較弱/解離較快及 5-HT2A 阻斷有關。",
        {"A": "錯誤。alpha-adrenergic receptor 活化不是 olanzapine 減少 EPS 的原因。",
         "B": "錯誤。抑制突觸前 dopamine 釋放不是主要機轉。",
         "C": "正確。相較 haloperidol，olanzapine 對 D2 的有效占據/親和力較低並具 serotonin receptor 作用，EPS 較少。",
         "D": "錯誤。D1 親和力較高不是降低 EPS 的主要解釋。"},
        "非典型抗精神病藥 EPS 較少，重點是較少 D2 阻斷與 5-HT2A 拮抗。"),
    73: ("Disulfiram 抑制 aldehyde dehydrogenase，飲酒後乙醛堆積。",
        {"A": "正確。disulfiram 使乙醛堆積，造成潮紅、噁心、嘔吐、低血壓等不適。",
         "B": "錯誤。acamprosate 用於酒精使用疾患維持戒酒，與乙醛堆積無關。",
         "C": "錯誤。naltrexone 是 opioid receptor antagonist，可降低酒精 craving。",
         "D": "錯誤。baclofen 是 GABAB agonist，非 disulfiram-like 反應主因。"},
        "Disulfiram + alcohol 造成 acetaldehyde accumulation。"),
    74: ("無機砷中毒可用含巯基螯合劑，如 dimercaprol、succimer、DMPS/unithiol。",
        {"A": "正確。unithiol 可螯合砷等重金屬，用於砷中毒。",
         "B": "錯誤。penicillamine 常用於銅、鉛等特定重金屬，非本題最佳砷中毒答案。",
         "C": "錯誤。deferoxamine 主要治療鐵中毒。",
         "D": "錯誤。Prussian blue 用於鉈或放射性銫中毒。"},
        "砷中毒螯合治療可用含巯基藥物，如 unithiol/DMPS。"),
    75: ("細胞週期專一性藥物配對以 irinotecan 抑制 topoisomerase I、影響 S 期為本題答案；但 ixabepilone-M 也需留意。",
        {"A": "錯誤。capecitabine/5-FU 類主要影響 DNA 合成，偏 S 期，不是 M 期。",
         "B": "正確。irinotecan 抑制 topoisomerase I，主要在 DNA synthesis 的 S 期發揮作用。",
         "C": "可能有爭議。ixabepilone 作用於微小管，藥理上可造成 M 期阻滯；若題目要求單選，官方取 B。",
         "D": "錯誤。vincristine 抑制微小管聚合，作用於 M 期，不是 S 期。"},
        "Irinotecan/topoisomerase I inhibitor 屬 S phase 相關；微小管藥多為 M phase。",
        ["C 選項 ixabepilone-M phase 在藥理上也合理，若此題為單選官方答案 B，建議人工複核題目脈絡。"]),
    76: ("Xanthoma 的泡沫細胞是吞噬脂質的巨噬細胞，細胞質堆積膽固醇/膽固醇酯。",
        {"A": "錯誤。磷酸鈣沉積較見於鈣化病灶。",
         "B": "正確。foamy cells 含大量膽固醇或脂質，呈泡沫狀。",
         "C": "錯誤。Mallory-Denk body 是肝細胞內中間絲聚集，常見酒精性肝病等。",
         "D": "錯誤。尿酸沉積形成痛風石，不是黃瘤泡沫細胞主要內容。"},
        "黃瘤泡沫細胞堆積膽固醇/脂質。"),
    77: ("萎縮可因細胞變小與細胞數量減少造成；題目問錯誤。",
        {"A": "正確。胚胎發育中某些暫時性組織會退化萎縮。",
         "B": "錯誤。萎縮可包括細胞體積變小，也可能伴隨細胞數目減少。",
         "C": "正確。老年性腦萎縮與血液供應減少、細胞耗損等因素相關。",
         "D": "正確。脂褐質可在萎縮或老化器官中累積，形成 brown atrophy。"},
        "萎縮不只細胞變小，也可有細胞數目減少。"),
    78: ("22q11.2 deletion 多為 de novo，典型影響胸腺與副甲狀腺發育。",
        {"A": "錯誤。主要免疫問題是胸腺發育不良造成 T 細胞功能/數量異常，不是 B 細胞為主。",
         "B": "錯誤。內分泌問題常為副甲狀腺低下造成低血鈣，不是腦下腺發育不良。",
         "C": "正確。多數個案為生殖細胞形成或早期胚胎發育時的 de novo 缺失。",
         "D": "錯誤。微小缺失常需 FISH、microarray 等方法，傳統核型分析解析度通常不足。"},
        "22q11.2 deletion 多為 de novo；胸腺/副甲狀腺發育異常是核心。"),
    79: ("三個選項皆可有小血管炎或血管侵犯相關病理。",
        {"A": "正確。梅毒可有 endarteritis，typhus 侵犯血管內皮，ecthyma gangrenosum 也有血管侵犯/壞死。",
         "B": "錯誤。只選 1、2 會漏掉 ecthyma gangrenosum 的小血管病變。",
         "C": "錯誤。只選 2、3 會漏掉梅毒的血管炎/內膜炎。",
         "D": "錯誤。只選 1、3 會漏掉 typhus 典型小血管炎。"},
        "梅毒、斑疹傷寒、壞疽性臁瘡都可見小血管侵犯/血管炎。"),
    80: ("鉛中毒常見血液、神經、腎臟與痛風相關表現；擴張性心肌病變較不典型。",
        {"A": "錯誤。鉛抑制 heme 合成，可造成貧血與溶血相關表現。",
         "B": "正確。擴張性心肌病變不是鉛中毒的典型常見病變。",
         "C": "錯誤。鉛可造成周邊神經病變，成人常見運動神經受損。",
         "D": "錯誤。鉛腎病變可造成高尿酸血症與痛風。"},
        "鉛中毒常考貧血、腹痛、神經病變、腎病變與痛風。"),
    81: ("BRAF V600E 常見於黑色素瘤、甲狀腺乳突癌與部分大腸癌；乳癌相對少見。",
        {"A": "正確。breast cancer 相對較少有 BRAF V600E mutation。",
         "B": "錯誤。部分 colon cancer 可見 BRAF V600E，且具臨床意義。",
         "C": "錯誤。malignant melanoma 常見 BRAF mutation。",
         "D": "錯誤。papillary thyroid carcinoma 常見 BRAF V600E。"},
        "BRAF V600E 常考 melanoma、papillary thyroid carcinoma、部分 colon cancer。"),
    82: ("A-C 都是淋巴回流阻塞造成的水腫/積液；肺梗塞肋膜積水多為發炎性滲出液。",
        {"A": "錯誤。血絲蟲象皮病是淋巴阻塞。",
         "B": "錯誤。乳糜胸多與胸管/淋巴回流受損相關。",
         "C": "錯誤。乳癌手術後上肢水腫是淋巴結清除造成淋巴回流障礙。",
         "D": "正確。肺梗塞引起肋膜積水主要與發炎、血管通透性增加有關，機轉不同。"},
        "淋巴阻塞水腫要和發炎性滲出液區分。"),
    83: ("肥厚型心肌病變典型是不對稱心室中隔肥厚，而非游離壁更厚；題目問錯誤。",
        {"A": "正確。sarcomere 蛋白基因突變常見，beta-myosin heavy chain 是代表之一。",
         "B": "正確。是年輕人運動中猝死的重要原因。",
         "C": "錯誤。典型為心室中隔肥厚比左心室游離壁更明顯。",
         "D": "正確。中隔肥厚可造成左心室流出道阻塞。"},
        "HCM 典型是不對稱心室中隔肥厚與流出道阻塞。"),
    84: ("CML 的核心是 t(9;22) Philadelphia chromosome 產生 BCR-ABL。",
        {"A": "錯誤。CML 多見於成人，不是兒童青少年為主。",
         "B": "錯誤。CML 骨髓通常 hypercellular，粒細胞系列增生。",
         "C": "錯誤。myeloblast >20% 代表急性白血病或 blast crisis，不是慢性期 CML 典型。",
         "D": "正確。t(9;22) 造成 BCR-ABL tyrosine kinase，是 CML 關鍵病因。"},
        "CML = Philadelphia chromosome t(9;22) / BCR-ABL。"),
    85: ("胸腺癌最常見組織型是鱗狀細胞癌。",
        {"A": "錯誤。腺癌可見但不是最常見胸腺癌型態。",
         "B": "錯誤。淋巴上皮瘤樣癌不是最常見型。",
         "C": "錯誤。神經內分泌癌屬胸腺癌亞型之一，但非最常見。",
         "D": "正確。鱗狀細胞癌是胸腺癌最常見型。"},
        "最常見 thymic carcinoma：squamous cell carcinoma。"),
    86: ("鼻腔血管纖維瘤多見青少年男性，源自鼻咽/鼻腔後側壁附近富血管纖維組織。",
        {"A": "錯誤。典型是青春期男性，不是中老年男性。",
         "B": "正確。一般認為源自鼻腔後側壁或鼻咽附近富含纖維血管的間質。",
         "C": "錯誤。鼻中隔壞死性潰瘍常需考慮感染、血管炎、藥物或惡性腫瘤等，不是 angiofibroma 最常見原因。",
         "D": "錯誤。雖為良性但局部侵襲性強，易出血且可能復發。"},
        "Juvenile nasopharyngeal angiofibroma：青少年男性、富血管、可復發。"),
    87: ("石棉暴露與胸膜斑、肺癌、間皮瘤相關；肺淋巴瘤較無典型關聯。",
        {"A": "錯誤。纖維疤塊/胸膜斑是石棉暴露典型表現。",
         "B": "正確。肺淋巴瘤與 asbestosis 的典型關聯較弱。",
         "C": "錯誤。石棉暴露增加肺癌風險，吸菸有加乘效果。",
         "D": "錯誤。間皮瘤與石棉暴露高度相關。"},
        "Asbestos：pleural plaques、lung carcinoma、mesothelioma。"),
    88: ("EGFR mutation 在肺腺癌較常見，尤其非吸菸者、女性、亞洲族群。",
        {"A": "正確。肺腺癌相對最常見 EGFR mutation。",
         "B": "錯誤。鱗癌較常見 TP53、p40/p63 等相關病理，不是 EGFR mutation 最典型。",
         "C": "錯誤。小細胞癌與吸菸、RB/TP53 失活較相關。",
         "D": "錯誤。大細胞癌不是 EGFR mutation 最常見類型。"},
        "肺癌 EGFR mutation 最常考肺腺癌。"),
    89: ("PSC 男性較多，常合併 IBD；題目問錯誤。",
        {"A": "正確。PSC 可見肝內外膽管纖維化狹窄與節段性擴張，影像呈串珠狀。",
         "B": "正確。PSC 與 HLA-B8 等免疫遺傳背景有關。",
         "C": "正確。常合併 ulcerative colitis 等發炎性腸病。",
         "D": "錯誤。PSC 較常發生於男性，不是女性較多；疲勞、搔癢、黃疸可見。"},
        "PSC：男性較多、IBD 相關、膽管串珠狀纖維化狹窄。"),
    90: ("胰臟黏液性囊性腫瘤常見卵巢樣間質，是重要鑑別點。",
        {"A": "正確。mucinous cystic neoplasm/cystadenoma 常有 ovarian-type stroma，多見女性。",
         "B": "錯誤。solid-pseudopapillary neoplasm 多見年輕女性，具低度惡性潛能，不是年輕男性良性腫瘤。",
         "C": "錯誤。serous cystic neoplasm 較常見於女性，不是男性兩倍。",
         "D": "錯誤。IPMN 與胰管系統相通，且由產黏液柱狀上皮組成。"},
        "胰臟 mucinous cystic neoplasm 常有 ovarian-type stroma；IPMN 與胰管相通。"),
    91: ("口腔紅斑惡性潛能高於一般白斑。",
        {"A": "錯誤。白斑可癌化，但平均風險低於紅斑。",
         "B": "正確。erythroplakia 常已有重度 dysplasia、原位癌或侵襲癌，最需警覺。",
         "C": "錯誤。毛狀白斑與 EBV/免疫低下相關，癌化風險不是最高。",
         "D": "錯誤。口瘡性潰瘍是良性復發性潰瘍，不是癌前病灶。"},
        "口腔 erythroplakia 比 leukoplakia 更容易已有或演變為 SCC。"),
    92: ("腎上腺微結節性增生，尤其 primary pigmented nodular adrenocortical disease，可有脂褐質色素。",
        {"A": "錯誤。黑色素不是此腎上腺微結節性增生的主要沉積色素。",
         "B": "錯誤。血鐵素代表鐵沉積或出血後分解產物。",
         "C": "錯誤。血色素不是微結節性增生主要色素。",
         "D": "正確。脂褐質可造成棕黑色外觀，是此病變常考色素。"},
        "腎上腺微結節性增生常考脂褐質沉積。"),
    93: ("Pheochromocytoma 的 sustentacular cells 常以 S100 標記突顯。",
        {"A": "錯誤。chromogranin 標記主要腫瘤性神經內分泌細胞。",
         "B": "正確。S100 可標示嗜鉻細胞瘤周邊的 sustentacular cells。",
         "C": "錯誤。synaptophysin 也是神經內分泌細胞標記，不是支持細胞最佳答案。",
         "D": "錯誤。NSE 可標記神經內分泌分化，但不如 S100 對支持細胞典型。"},
        "Pheochromocytoma：chief cells chromogranin/synaptophysin，sustentacular cells S100。"),
    94: ("Fibromuscular dysplasia 好發年輕女性，常影響腎動脈，可呈串珠狀；不只侵犯中層。",
        {"A": "錯誤。女性較多是典型特徵。",
         "B": "錯誤。好發年輕至中年女性，20-40 歲合理。",
         "C": "正確。FMD 可分 intimal、medial、adventitial/perimedial 等型態，並非僅侵犯中層。",
         "D": "錯誤。腎動脈狹窄可造成腎缺血與萎縮。"},
        "FMD 好發年輕女性腎動脈，不限於血管中層。"),
    95: ("外陰部乳房外 Paget disease 多為表皮內腺癌樣病變，伴隨深部侵襲癌比例低於乳房 Paget disease。",
        {"A": "正確。臨床可呈濕疹樣、紅斑脫屑病灶，類似乳房 Paget disease。",
         "B": "錯誤。外陰部乳房外 Paget disease 多數沒有伴隨潛在侵襲癌，與乳頭 Paget disease 不完全相同。",
         "C": "正確。Paget cells 常表現 CK7 等腺上皮標記。",
         "D": "正確。腫瘤細胞可超越肉眼邊界蔓延，造成切除不完全與復發。"},
        "Extramammary Paget disease 常 CK7+，可表皮內蔓延，但多數不伴隨深部侵襲癌。"),
    96: ("卵巢 dysgerminoma 多見青春期與年輕女性，不是大多 10 歲以下。",
        {"A": "正確。成熟囊性畸胎瘤是最常見卵巢生殖細胞瘤。",
         "B": "正確。dysgerminoma 是常見的惡性卵巢生殖細胞瘤。",
         "C": "錯誤。dysgerminoma 多發生於青少年與年輕成人，不是大部分 10 歲以下。",
         "D": "正確。yolk sac tumor 可分泌 AFP，是重要腫瘤標記。"},
        "Dysgerminoma 多見年輕女性；yolk sac tumor 常 AFP 升高。"),
    97: ("完全性葡萄胎惡性轉化風險高於部分性葡萄胎；題目問較不正確。",
        {"A": "正確。完全性葡萄胎通常遺傳物質全為父源。",
         "B": "錯誤。choriocarcinoma 風險是完全性葡萄胎高於部分性葡萄胎。",
         "C": "正確。完全性葡萄胎較部分性葡萄胎更易進展為侵入性葡萄胎。",
         "D": "正確。部分性葡萄胎通常有母源與父源遺傳物質，常為三倍體。"},
        "完全性葡萄胎比部分性葡萄胎更易侵入與惡性轉化。"),
    98: ("退化性關節炎主軸是關節軟骨退化與軟骨細胞修復失衡，不是原發滑膜炎。",
        {"A": "錯誤。軟骨下骨變化可出現，但不是由成骨細胞損傷引發發炎作為主要機轉。",
         "B": "錯誤。滑膜細胞退化與淋巴球浸潤不是 OA 的主要起始機轉，較像發炎性關節炎概念。",
         "C": "正確。OA 主要是 articular cartilage degeneration 與 chondrocyte repair 失衡。",
         "D": "錯誤。滑膜細胞修復性增生阻礙血管通透性不是 OA 主要病理。"},
        "OA 主要是關節軟骨退化與軟骨細胞修復失衡。"),
    99: ("CAA 是皮質/腦膜小中型血管 amyloid-beta 沉積，與 lobar hemorrhage、ApoE 相關。",
        {"A": "錯誤。第 2 句錯在沉積物不是 tau，而主要是 amyloid-beta。",
         "B": "正確。第 1 句 lobar hemorrhage 風險與第 3 句 ApoE 多形性相關皆正確。",
         "C": "錯誤。第 2 句 tau 蛋白錯誤。",
         "D": "錯誤。第 4 句將 CAA 描述成 arteriolar sclerosis/fibrosis 不精確，且第 2 句也錯。"},
        "CAA：amyloid-beta 沉積於皮質/腦膜血管，造成 lobar hemorrhage，與 ApoE 相關。"),
    100: ("髓芽細胞瘤分子亞型中 WNT type 預後最佳。",
        {"A": "正確。WNT subtype 通常預後最好，治療反應佳。",
         "B": "錯誤。SHH subtype 預後依年齡與分子特徵而異，不是整體最佳。",
         "C": "錯誤。group 3 常與 MYC amplification、轉移風險及較差預後相關。",
         "D": "錯誤。group 4 常見但預後通常不如 WNT。"},
        "Medulloblastoma 預後最佳分子亞型是 WNT。"),
}


def build_explanation(q, note):
    analysis, options, key, *rest = note
    answer = q.get("correct_answer")
    lines = [
        "【題幹解析】",
        f"{analysis}官方答案為 {answer}。解題時要先判斷題目是否在問「正確」或「錯誤」，再把病原、藥理機轉或病理特徵對回選項。",
        "",
        "【選項詳解】",
    ]
    for letter in ("A", "B", "C", "D"):
        lines.append(f"- {letter}. {options[letter]}")
    lines.extend(["", "【核心考點】", key])
    return "\n".join(lines)


def make_update(q, note):
    analysis, _options, key, *rest = note
    manual_notes = rest[0] if rest else []
    front = q["question_text"].replace("\n", " ")
    if len(front) > 96:
        front = front[:96] + "..."
    return {
        "question_id": q["id"],
        "question_number": q["question_number"],
        "explanation": build_explanation(q, note),
        "key_point": key,
        "flashcard_front": front,
        "flashcard_back": key,
        "flashcard_summary": f"{front} -> {key}",
        "review_status": "ai_generated",
        "explanation_model": "codex-high-quality-rewrite",
        "explanation_generated_at": STAMP,
        "manual_review_notes": manual_notes,
    }


def main():
    data = json.loads(READABLE_SOURCE.read_text(encoding="utf-8"))
    questions = data["questions"]
    missing = [q["question_number"] for q in questions if q["question_number"] not in NOTES]
    if missing:
        raise SystemExit(f"missing notes for questions: {missing}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for start in range(1, 101, 10):
        end = start + 9
        batch_questions = [q for q in questions if start <= q["question_number"] <= end]
        payload = {
            "source_file": SOURCE_FILE,
            "dataset_id": DATASET_ID,
            "range": {"start": start, "end": end},
            "updates": [make_update(q, NOTES[q["question_number"]]) for q in batch_questions],
        }
        out = OUT_DIR / f"q{start:03d}-q{end:03d}.json"
        out.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(out)


if __name__ == "__main__":
    main()
