import json
from pathlib import Path


SOURCE_FILE = "public/data/exams/109-2/medicine-5.json"
DATASET_ID = "109-2_medicine-5"
OUT_DIR = Path("scratch/rewrite_updates/109-2_medicine-5")
STAMP = "2026-07-19T12:00:00+08:00"


def explanation(stem, options, core):
    return (
        f"【題幹解析】\n{stem}\n\n"
        "【選項詳解】\n"
        f"- A. {options['A']}\n"
        f"- B. {options['B']}\n"
        f"- C. {options['C']}\n"
        f"- D. {options['D']}\n\n"
        f"【核心考點】\n{core}"
    )


def update(qnum, stem, options, core, key, front, back=None, summary=None, notes=None):
    if notes is None and isinstance(summary, list):
        notes = summary
        summary = None
    if back is None:
        back = core
    if summary is None:
        summary = f"{front} -> {back}"
    return {
        "question_id": f"{DATASET_ID}_{qnum:03d}",
        "question_number": qnum,
        "explanation": explanation(stem, options, core),
        "key_point": key,
        "flashcard_front": front,
        "flashcard_back": back,
        "flashcard_summary": summary,
        "review_status": "ai_generated",
        "explanation_model": "codex-high-quality-rewrite",
        "explanation_generated_at": STAMP,
        "manual_review_notes": notes or [],
    }


UPDATES = [
    update(
        1,
        "本題問零期乳癌敘述何者錯誤。零期乳癌主要指原位癌，尚未穿破基底膜，因此淋巴結轉移風險低；治療重點是局部控制，不是例行腋下淋巴廓清。官方答案 C 是錯誤敘述。",
        {
            "A": "DCIS 常在乳房攝影以顯微鈣化表現，這是臨床篩檢常見線索，敘述正確。",
            "B": "原位病灶可呈多灶或範圍較廣分布，術前影像評估切除範圍很重要，敘述正確。",
            "C": "零期乳癌通常不需要例行 level II 腋下淋巴廓清；只有在特定高風險或全乳切除情境才會考慮前哨淋巴結評估，因此本項錯誤。",
            "D": "原位癌手術後一般不需要全身化學治療；可依病灶與受體狀態考慮放射或荷爾蒙治療，敘述正確。",
        },
        "零期乳癌未侵犯基底膜，治療以局部切除或全乳切除搭配適當輔助治療為主，不做例行腋下廓清。",
        "零期乳癌不需例行 level II 腋下淋巴廓清。",
        "carcinoma in situ；DCIS；腋下淋巴廓清",
        "零期乳癌未侵犯基底膜，淋巴轉移風險低；錯誤敘述是例行 level II axillary dissection。",
        "零期乳癌 -> 不例行腋下淋巴廓清",
    ),
    update(
        2,
        "本題問頸部穿刺傷分區何者錯誤。Zone I 到 Zone III 的位置要由下往上記：Zone I 是胸廓入口到環狀軟骨，Zone II 是環狀軟骨到下顎角，Zone III 是下顎角到顱底。官方答案 C 把 Zone I 與 Zone III 的範圍搞反。",
        {
            "A": "Zone II 位在頸部中段，外科暴露相對容易，因此被稱為最容易手術進入的區域，敘述正確。",
            "B": "Zone II 從 cricoid cartilage 到 angle of mandible，這是標準分界，敘述正確。",
            "C": "angle of mandible 到 skull base 是 Zone III，不是 Zone I；Zone I 應是胸廓入口到 cricoid cartilage，因此本項錯誤。",
            "D": "Zone III 靠近顱底，含頸動脈、椎動脈等重要血管，外科近端控制困難，敘述正確。",
        },
        "頸部穿刺傷分區：Zone I 在下、Zone II 在中、Zone III 在上；下顎角到顱底屬 Zone III。",
        "頸部外傷 Zone III 是下顎角到顱底。",
        "neck penetrating injury；Zone I II III",
        "Zone I: thoracic inlet-cricoid；Zone II: cricoid-mandible angle；Zone III: mandible angle-skull base。",
        "頸部穿刺傷分區 -> C 把 Zone I 寫成 Zone III",
    ),
    update(
        3,
        "本題考選擇性手術前 warfarin 停藥後可接受的 INR 目標。多數手術希望凝血功能接近正常，常以 INR 小於 1.5 作為可進刀的門檻。官方答案 C。",
        {
            "A": "INR 2.0 仍接近抗凝治療範圍，對一般選擇性手術出血風險偏高，不是常用上限。",
            "B": "INR 1.8 雖比治療範圍低，但仍未達常見術前安全目標，尤其對出血風險較高的手術不夠理想。",
            "C": "INR 低於 1.5 通常表示 warfarin 效果已充分退去，是選擇性手術常用門檻，因此正確。",
            "D": "INR 1.2 太接近完全正常，並非常規要求；若一律要求到此數值，可能不必要地延後手術。",
        },
        "Warfarin 選擇性手術通常停藥約 5 天，常見目標是 INR < 1.5。",
        "Warfarin 術前停藥；INR 門檻",
        "選擇性手術前停 warfarin 約 5 天，常以 INR < 1.5 作為可接受門檻。",
        "warfarin 術前處置 -> INR < 1.5",
    ),
    update(
        4,
        "本題問大量出血或休克的 lethal triad 何者不屬於其中。創傷出血的惡性循環是酸中毒、低體溫與凝血障礙，三者會彼此加重出血。官方答案 A。",
        {
            "A": "Arrhythmia 可能出現在休克或電解質異常時，但不是創傷大量出血所稱 lethal triad 的固定三要素，因此為答案。",
            "B": "Acidosis 會降低凝血酵素活性與心肌功能，是 lethal triad 的一環。",
            "C": "Hypothermia 會抑制凝血反應並加重出血，是 lethal triad 的一環。",
            "D": "Coagulopathy 是大量出血、稀釋、低溫與酸中毒後的重要死亡因子，屬於 lethal triad。",
        },
        "創傷出血 lethal triad 是 acidosis、hypothermia、coagulopathy。",
        "lethal triad；trauma shock",
        "大量出血的 lethal triad：酸中毒、低體溫、凝血障礙；不包含 arrhythmia。",
        "大量出血休克 -> lethal triad 三要素",
    ),
    update(
        5,
        "本題問傷口分類與 SSI 發生率何者錯誤。Clean wound 的感染率通常約 1-5% 左右，不會低到 0.1-0.3%；其他分類的感染率會隨污染程度上升。官方答案 A。",
        {
            "A": "Clean wound 沒有進入呼吸、消化、生殖泌尿道等 hollow viscus 且可一期縫合，但 SSI 風險通常仍約百分之數，不是 0.1-0.3% 這種極低值，因此錯誤。",
            "B": "Clean-contaminated wound 是有控制地進入 hollow viscus，感染率約數個百分比，5-8% 合理。",
            "C": "Contaminated wound 有明顯污染或 uncontrolled spillage，感染率可到 20% 以上，敘述合理。",
            "D": "Dirty wound 代表既有感染、壞死或未控制污染，SSI 風險最高，30-40% 合理。",
        },
        "SSI 風險隨傷口污染程度增加；clean wound 不是零風險，感染率不應低估到 0.1-0.3%。",
        "SSI；clean wound 感染率",
        "Clean wound 感染率仍約百分之數；污染越重，SSI 風險越高。",
        "傷口分類 -> clean wound 感染率不是 0.1-0.3%",
    ),
    update(
        6,
        "本題問傷口癒合何者錯誤。纖維母細胞主要由局部間質細胞活化、增生並遷移到傷口，不是大多數從遠端組織經血液循環運送而來。官方答案 B。",
        {
            "A": "受傷後先止血與發炎，血小板、血管通透性增加與趨化因子會招募中性球與巨噬細胞，敘述符合發炎期。",
            "B": "增生期的 fibroblast 主要來自局部組織遷移與增生，受 PDGF、TGF-beta 等因子刺激合成膠原；說大多數由血液從遠處運來並不正確。",
            "C": "Myofibroblast 約在數天後出現，含 alpha-smooth muscle actin，可產生收縮力量促進傷口攣縮，敘述可接受。",
            "D": "早期肉芽組織先以第三型膠原為主，之後成熟重塑時逐漸被第一型膠原取代，敘述正確。",
        },
        "傷口增生期的 fibroblast 主要是局部細胞活化遷移，不是遠端經血流大量運來。",
        "傷口癒合；fibroblast；collagen III",
        "發炎期先招募發炎細胞；增生期局部 fibroblast 合成膠原，早期 collagen III 先於 collagen I。",
        "傷口癒合 -> fibroblast 來源與膠原轉換",
    ),
    update(
        7,
        "本題官方更正接受 A、B、C、D 皆給分。題目問吸菸與何種癌症無關，但這些癌症與吸菸風險的關聯程度在流行病學上並非完全沒有關係，題目設計容易產生爭議。",
        {
            "A": "膀胱癌與吸菸有明確關聯，芳香胺等致癌物經尿液排出會暴露泌尿上皮；若題目問無關，本項不適合作為唯一答案。",
            "B": "食道癌，尤其鱗狀上皮癌，與吸菸和飲酒都有流行病學關聯；因此也不是明確無關。",
            "C": "胰臟癌風險會因吸菸上升，是常被列入吸菸相關癌症的項目之一。",
            "D": "大腸癌與吸菸的關聯較前幾項弱，但仍有研究支持風險增加；因此官方採全給分較能反映題目不精確。",
        },
        "若考題問吸菸與癌症無關，要小心選項是否其實都有一定流行病學關聯；本題官方全給分。",
        "吸菸相關癌症；官方全給分",
        "膀胱、食道、胰臟與大腸癌都可與吸菸風險有關，本題官方接受 A-D。",
        "吸菸與癌症 -> 本題官方 A-D 全給分",
        ["官方答案接受 A-D 全給分；題幹『無關』與流行病學關聯可能有爭議，建議人工複核原始更正。"],
    ),
    update(
        8,
        "本題問開腹術後消化液引流流失何者錯誤。膽汁每日量約 300-800 mL，但其碳酸氫根濃度不會高於胰液；胰液才是富含 bicarbonate 的鹼性分泌液。官方答案 C。",
        {
            "A": "胃液每日可約 1-2 L，含氫離子與氯離子，持續大量流失會造成低鉀與代謝性鹼中毒風險，敘述可接受。",
            "B": "小腸液量大且富含 bicarbonate，若由腸瘻或引流大量流失，可能造成 bicarbonate 流失與代謝性酸中毒，敘述正確。",
            "C": "膽汁有 bicarbonate，但胰液與腸液的鹼性分泌更重要；說膽汁 HCO3- 濃度比腸液、胰液還高不正確。",
            "D": "胰液透明、鹼性且每日約 600-800 mL，含 bicarbonate 與消化酵素，敘述正確。",
        },
        "消化液流失要記量與電解質：胰液/腸液富含 bicarbonate，膽汁不是 HCO3- 最高者。",
        "消化液流失；bicarbonate；胰液",
        "胰液與腸液富含 HCO3-；膽汁每日約 300-800 mL，但 HCO3- 不高於胰液。",
        "消化液引流 -> C 高估膽汁 HCO3-",
    ),
    update(
        9,
        "本題問抗排斥藥物何者正確。Cyclosporine 與 tacrolimus/FK-506 都是 calcineurin inhibitor，會抑制 T 細胞 IL-2 訊號，也都有腎毒性。官方答案 D。",
        {
            "A": "Cyclosporine 與 tacrolimus 都會抑制 calcineurin，進而降低 IL-2 transcription；不是只有 cyclosporine 會抑制 IL-2。",
            "B": "急性排斥仍可使用高劑量類固醇作為治療之一，不能說目前已經很少用到而排除。",
            "C": "葡萄柚汁會影響 CYP3A/P-gp，可能提高 cyclosporine 濃度；tacrolimus 也受類似代謝交互作用影響，不是簡單改用即可。",
            "D": "Cyclosporine 與 FK-506 都可能造成血管收縮性腎毒性，是臨床監測濃度與腎功能的重點，因此正確。",
        },
        "Calcineurin inhibitors 包含 cyclosporine 與 tacrolimus，兩者都抑制 IL-2 且都有腎毒性。",
        "cyclosporine；tacrolimus；腎毒性",
        "Cyclosporine 和 tacrolimus 都是 calcineurin inhibitor；共同重點是 IL-2 抑制與 nephrotoxicity。",
        "移植免疫抑制 -> CNI 皆有腎毒性",
    ),
    update(
        10,
        "本題問意識不清頭部外傷處置何者錯誤。急性頭部外傷要先做初級評估、神經學評估、穩定生命徵象並安排影像；不應以低劑量抗癲癇藥試驗取代診斷與治療。官方答案 D。",
        {
            "A": "GCS、瞳孔大小與對光反射可快速判斷腦傷嚴重度與顱內壓危象，是正確處置。",
            "B": "頭部外傷常合併胸腹、脊椎或四肢傷害，必須同步評估生命徵象與 associated injury。",
            "C": "生命徵象穩定後頭部 CT 是評估顱內出血、腦挫傷與需手術病灶的重要檢查。",
            "D": "抗癲癇藥可用於特定高風險病人預防早期癲癇，但不是先給低劑量 therapeutic trial 並等 24 小時的標準流程，因此錯誤。",
        },
        "頭部外傷先穩定 ABC、做 GCS/瞳孔評估與 CT；抗癲癇藥不是診斷性試驗。",
        "頭部外傷；GCS；抗癲癇預防",
        "意識不清頭部外傷不可用低劑量抗癲癇藥試驗拖延評估；應先穩定並安排 CT。",
        "頭部外傷處置 -> D 非標準流程",
    ),
    update(
        11,
        "本題問脈絡叢乳突狀瘤何者錯誤。此腫瘤兒童較常在側腦室，成人則較常見於第四腦室；官方答案 C 把成人好發位置寫成側腦室。",
        {
            "A": "Choroid plexus papilloma 可見於小孩與成人，只是年齡與位置分布不同，敘述正確。",
            "B": "嬰幼兒發生比例較高，且常因腦脊髓液過度生成或阻塞而水腦，敘述正確。",
            "C": "成人最常見位置較偏第四腦室；側腦室較典型見於兒童，因此本項錯誤。",
            "D": "側腦室腫瘤若壓迫鄰近白質、內囊或造成水腦，可能有半癱等神經缺損，敘述可接受。",
        },
        "Choroid plexus papilloma：兒童常在側腦室，成人較常在第四腦室。",
        "choroid plexus papilloma；成人位置",
        "脈絡叢乳突狀瘤成人好發第四腦室；兒童較常側腦室。",
        "脈絡叢乳突狀瘤 -> 成人不是最常側腦室",
    ),
    update(
        12,
        "本題描述小腦扁桃體下垂約 5 mm 到頸椎脊髓腔，合併 syringomyelia，但沒有脊柱裂或水腦，最符合 Chiari I malformation。官方答案 A。",
        {
            "A": "Chiari I 是小腦扁桃體下疝，常在較大兒童或成人發現，可合併脊髓空洞症，因此正確。",
            "B": "Chiari II 常與 myelomeningocele、腦幹與小腦蚓部下移、水腦相關；題幹明確說沒有脊柱裂或水腦，不符合。",
            "C": "Dandy-Walker syndrome 以小腦蚓部發育不良與第四腦室囊狀擴大為核心，不是單純 tonsillar descent。",
            "D": "Myelomeningocele 是神經管閉合缺陷，題幹明確排除 spinal bifida 相關病灶。",
        },
        "Chiari I = cerebellar tonsil herniation，可合併 syringomyelia；Chiari II 常合併 myelomeningocele。",
        "Chiari I；syringomyelia",
        "小腦扁桃體下垂約 5 mm 加 syringomyelia、無脊柱裂水腦，選 Chiari I。",
        "小腦扁桃體下垂 -> Chiari I",
    ),
    update(
        13,
        "本題問腦膿瘍何者正確。腦膿瘍若突然在數小時內惡化，要想到破入腦室或蜘蛛膜下腔，會造成急性腦膜炎、腦室炎與顱內壓快速上升。官方答案 C。",
        {
            "A": "腦膿瘍可血行播散，但也常由中耳炎、乳突炎、鼻竇炎、牙源性感染或外傷鄰近擴散而來；不能說通常都是血行進入。",
            "B": "好發族群不是單純老年人；兒童、青壯年、免疫低下者或有耳鼻竇感染者都可能發生。",
            "C": "膿瘍破入腦室或蜘蛛膜下腔會讓感染突然擴散，臨床可在短時間內急遽惡化，因此正確。",
            "D": "典型影像是腦實質 ring-enhancing lesion 與周邊水腫，不是最常表現為額葉腦表面的單純 cystic lesion。",
        },
        "腦膿瘍突然惡化要想到 rupture into ventricle/subarachnoid space。",
        "腦膿瘍；急遽惡化；破入腦室",
        "腦膿瘍可由鄰近感染或血行而來；突然惡化最怕破入腦室或蜘蛛膜下腔。",
        "腦膿瘍 -> 急惡化代表破裂擴散",
    ),
    update(
        14,
        "本題考藥物難治型癲癇且放電點定位在右側顳葉時，哪種手術治癒率最高。局部且可切除的顳葉癲癇以 anterior temporal lobectomy 效果最佳。官方答案 A。",
        {
            "A": "Anterior temporal lobectomy 直接切除癲癇焦點及相關顳葉內側結構，對藥物難治型顳葉癲癇的 seizure-free 比例最高，因此正確。",
            "B": "Multiple subpial transection 用於焦點位於功能皮質、不能完整切除時，治癒率通常不如顳葉切除。",
            "C": "Corpus callosotomy 是阻斷癲癇擴散的緩解性手術，常用於跌倒發作等廣泛性癲癇，不是局部顳葉癲癇首選。",
            "D": "Vagus nerve stimulation 多為減少發作頻率的輔助療法，通常不以治癒為目標。",
        },
        "藥物難治且定位明確的顳葉癲癇，anterior temporal lobectomy 的治癒率最高。",
        "顳葉癲癇；anterior temporal lobectomy",
        "可定位、可切除的 temporal lobe epilepsy，首選治癒性手術是 anterior temporal lobectomy。",
        "難治型顳葉癲癇 -> anterior temporal lobectomy",
    ),
    update(
        15,
        "本題問後骨間神經受損時哪個肌肉不會無力。Posterior interosseous nerve 是 radial nerve 的深支，支配多數手指與拇指伸肌；extensor carpi radialis longus 通常在 PIN 分支前已由 radial nerve 支配。官方答案 B。",
        {
            "A": "Abductor pollicis longus 由 posterior interosseous nerve 支配，PIN 受損會影響拇指外展與伸展相關動作。",
            "B": "Extensor carpi radialis longus 多由 radial nerve 在分出 PIN 前支配，因此單純 PIN injury 通常不會使它無力，故為答案。",
            "C": "Extensor pollicis longus 由 PIN 支配，受損會造成拇指 IP 關節伸展無力。",
            "D": "Extensor digitorum communis 由 PIN 支配，受損會造成 MCP 伸指無力。",
        },
        "PIN 支配多數拇指與手指伸肌；ECRL 在分支前由 radial nerve 支配，通常保留。",
        "posterior interosseous nerve；ECRL",
        "PIN injury 會影響 EPL、APL、EDC；ECRL 通常不受影響。",
        "PIN injury -> ECRL 保留",
    ),
    update(
        16,
        "本題問糖尿病足何者錯誤。糖尿病足合併骨髓炎時，X 光變化常比臨床感染延遲約 2 週甚至更久才明顯；MRI 對早期骨髓炎較敏感。官方答案 A。",
        {
            "A": "X-ray 對早期 osteomyelitis 不敏感，骨質破壞通常需一段時間才看得到；只晚 1 週的說法低估延遲，因此錯誤。",
            "B": "MRI 對骨髓水腫、骨髓炎與深部軟組織感染敏感，可協助早期診斷，敘述正確。",
            "C": "Bone scan 對骨代謝活性敏感，雖特異性有限，仍可輔助診斷骨髓炎。",
            "D": "糖尿病足潰瘍與感染是非創傷性下肢截肢的重要原因，敘述正確。",
        },
        "糖尿病足疑骨髓炎時，早期影像首重 MRI；X-ray 變化常延後出現。",
        "糖尿病足；osteomyelitis；MRI",
        "糖尿病足骨髓炎 X-ray 變化晚，MRI 可早期診斷。",
        "糖尿病足骨髓炎 -> X-ray 不是早期敏感工具",
    ),
    update(
        17,
        "本題考手腕背側伸肌腱區間。第 5 伸展區間內容物是 extensor digiti minimi；第 4 是 EDC/EIP，第 3 是 EPL，第 6 是 ECU。官方答案 D。",
        {
            "A": "Extensor indicis proprius 位於第 4 伸展區間，和 extensor digitorum communis 同區，不是第 5。",
            "B": "Extensor pollicis longus 位於第 3 伸展區間，繞過 Lister tubercle，不是第 5。",
            "C": "Extensor carpi ulnaris 位於第 6 伸展區間，最靠尺側，不是第 5。",
            "D": "Extensor digiti minimi 位於第 5 伸展區間，負責小指伸展，因此正確。",
        },
        "手腕伸展區間：3 = EPL，4 = EDC/EIP，5 = EDM，6 = ECU。",
        "腕背伸展區間；EDM",
        "第 5 extensor compartment 是 extensor digiti minimi。",
        "手腕第 5 伸展區間 -> EDM",
    ),
    update(
        18,
        "本題考身體各部位拆線時機。臉部與眼皮血流佳、張力小，通常較早拆線約 5-7 天；背部、頭皮、手部多需較久。官方答案 B。",
        {
            "A": "頭皮通常約 7-10 天拆線，12-14 天偏久，除非特殊張力或癒合風險，不是最適當配對。",
            "B": "眼皮皮膚薄、血流佳，拆線約 5-7 天最合適，因此正確。",
            "C": "背部張力較大且活動牽拉多，通常需要約 10-14 天，5-7 天太早。",
            "D": "手部活動多、張力與污染風險較高，常需約 10-14 天，5-7 天偏早。",
        },
        "拆線時間依血流與張力調整：眼皮約 5-7 天，背部與手部較久。",
        "拆線時機；eyelid",
        "眼皮血流佳且張力小，約 5-7 天拆線；背部與手部通常更久。",
        "拆線時間 -> 眼皮 5-7 天",
    ),
    update(
        19,
        "本題有圖片，官方答案為 B。題幹描述頭皮快速增生且診斷為 melanoma；臨床上 nodular melanoma 可快速垂直生長，但僅憑文字與未檢視圖片不能獨立確認分型外觀，因此以官方答案與選項邏輯說明。",
        {
            "A": "若圖片呈現快速隆起、結節狀、顏色不均的病灶，會支持 nodular melanoma；但分型仍需依臨床外觀與病理整體判斷，本項不是官方採認的單一正答。",
            "B": "Nodular melanoma 可發生在多數有皮膚的部位，包括頭皮與軀幹四肢，不限於手足等肢端部位，因此本項最符合官方答案。",
            "C": "Melanoma 診斷以完整切除切片較佳，但病灶太大或位置困難時可做 incisional biopsy；切片本身不等於促進腫瘤擴散，故本項錯。",
            "D": "可切除 melanoma 的主要治療是手術；放射治療可用於特定輔助或緩和情境，不能說與手術有一樣存活率。",
        },
        "黑色素瘤診斷以切片確認；nodular melanoma 可見於多數皮膚部位，治療仍以手術為主。",
        "melanoma；nodular melanoma；切片",
        "Nodular melanoma 可發生於多數皮膚部位；切片不因怕擴散而絕對禁止。",
        "melanoma 圖片題 -> 官方 B，需參照原圖",
        ["本題依賴圖片判讀；目前文字資料沒有圖像，建議人工對照原始試題圖片確認分型。"],
    ),
    update(
        20,
        "本題問乳房重建方式何者錯誤。DIEP flap 保留腹直肌，只取深下腹穿通血管與皮瓣，腹壁疝氣或無力風險通常低於 TRAM flap。官方答案 D。",
        {
            "A": "義乳重建手術時間較短、沒有取自體皮瓣區傷口，是臨床常見且多數病人會選擇的方式，敘述可接受。",
            "B": "放射治療會增加莢膜攣縮、纖維化、脂肪壞死與重建失敗風險，敘述正確。",
            "C": "Latissimus dorsi flap 可提供可靠軟組織覆蓋，對小乳房或需要補強皮膚軟組織者是不錯選擇。",
            "D": "DIEP 相較 TRAM 的優點正是較少犧牲腹直肌，腹部疝氣風險較低；說 DIEP 較高比例疝氣是錯誤。",
        },
        "TRAM 取腹直肌，DIEP 保留肌肉；DIEP 的腹壁併發症通常較少。",
        "乳房重建；TRAM；DIEP",
        "DIEP flap 保留腹直肌，腹壁疝氣風險低於 TRAM。",
        "乳房重建 -> DIEP 不比 TRAM 更易腹部疝氣",
    ),
    update(
        21,
        "本題問體外循環何者錯誤。Cardiopulmonary bypass 可提供心臟手術需要的無血視野，但時間越長，發炎反應、凝血異常與器官傷害風險越高，不能說沒有時間限制。官方答案 C。",
        {
            "A": "啟動體外循環前需足量 heparin，使 ACT 通常大於 400-480 秒；題目 300-400 units/kg、ACT >450 秒符合常見原則。",
            "B": "常溫灌流量約 2.4 L/min/m2；低溫可降低代謝與氧耗，體溫下降會明顯降低氧氣需求，敘述正確。",
            "C": "CPB 時間越長，術後出血、發炎、腎傷害、神經併發症等風險增加；不能說使用時間沒有限制，因此錯誤。",
            "D": "血液接觸人工管路與非生理灌流可引起凝血異常、全身發炎與栓塞相關器官功能不良，敘述正確。",
        },
        "體外循環可創造無血視野，但 CPB time 越久併發症越多，不能視為無限制。",
        "cardiopulmonary bypass；CPB time",
        "CPB 前 heparin、ACT 達標；CPB 時間越久，凝血、發炎、栓塞與器官傷害越多。",
        "體外循環 -> 時間不是沒有限制",
    ),
    update(
        22,
        "本題問心臟瓣膜外科解剖何者錯誤。Koch triangle 是房室結所在的重要區域，三尖瓣手術縫合時最怕傷及傳導系統，不能說不必擔心房室傳導異常。官方答案 C。",
        {
            "A": "主動脈瓣與肺動脈瓣為三片半月瓣葉組成，敘述正確。",
            "B": "僧帽瓣由 anterior leaflet 與 posterior leaflet 兩片瓣葉構成，敘述正確。",
            "C": "Koch triangle 內有 AV node，三尖瓣修補或置換靠近 septal annulus 縫合時需避開；本項說必須縫合且不用擔心傳導異常，錯誤。",
            "D": "左迴旋冠狀動脈走行可接近僧帽瓣後葉瓣環，僧帽瓣手術需注意避免傷及，敘述正確。",
        },
        "Koch triangle 含 AV node；三尖瓣手術要避免傷及傳導系統。",
        "Koch triangle；AV node；三尖瓣手術",
        "Koch triangle 是傳導系統危險區，不是可放心縫合的區域。",
        "瓣膜外科解剖 -> Koch triangle 需避開 AV node",
    ),
    update(
        23,
        "本題為圖片題，官方答案 A。DeBakey type II 主動脈剝離侷限於升主動脈，不延伸到主動脈弓或降主動脈；題圖中 A 對應的 I 應為升主動脈區段。",
        {
            "A": "若圖中 I 標示升主動脈，這正是 DeBakey type II 的侵犯範圍，因此為官方答案。",
            "B": "若 II 代表主動脈弓或其後續區段，已超出 DeBakey type II 的定義，不符合。",
            "C": "若 III 代表降胸主動脈，會接近 DeBakey type III 的概念，不是 type II。",
            "D": "若 IV 代表更遠端腹主動脈或分支區，與侷限升主動脈的 type II 不符。",
        },
        "DeBakey type II = dissection confined to ascending aorta。",
        "aortic dissection；DeBakey type II",
        "DeBakey II 只侵犯升主動脈；本題依圖中 I 對應升主動脈選 A。",
        "主動脈剝離 -> DeBakey II 侷限升主動脈",
        ["本題答案仰賴圖中 I-IV 標示；目前文字資料沒有圖片，建議人工對照原圖確認 A/I 是否為升主動脈。"],
    ),
    update(
        24,
        "本題比較 CABG conduit 的 10 年通暢率。內乳動脈長期通暢率最高，橈動脈通常優於大隱靜脈，因此排序為 1 > 3 > 2。官方答案 A。",
        {
            "A": "Internal mammary artery 尤其 LIMA-to-LAD 長期通暢率最佳，radial artery 次之，saphenous vein graft 較低，故本項正確。",
            "B": "大隱靜脈不會優於內乳動脈；把靜脈 graft 放第一不符合長期結果。",
            "C": "大隱靜脈與內乳動脈位置顛倒，低估了 arterial graft 的長期通暢優勢。",
            "D": "橈動脈雖是動脈 graft，但一般仍不優於內乳動脈；且大隱靜脈不會優於內乳動脈。",
        },
        "CABG conduit 長期通暢率：internal mammary artery > radial artery > saphenous vein。",
        "CABG conduit；10 年通暢率",
        "內乳動脈長期通暢率最高，橈動脈次之，大隱靜脈較低。",
        "CABG conduit -> IMA > radial > SVG",
    ),
    update(
        25,
        "本題描述急性心肌梗塞後休克、Grade 4/6 收縮期雜音與肺水腫，要警覺機械性併發症或嚴重缺血性瓣膜問題，需快速超音波評估與循環支持。錯誤在於把不停跳 CABG 說成狀況差時必須使用的固定策略。官方答案 C。",
        {
            "A": "新出現 loud systolic murmur 合併肺水腫時，心臟超音波可評估急性二尖瓣逆流、心室中隔破裂與心室功能，應該進行。",
            "B": "IABP 可作為心因性休克與急性機械併發症的暫時循環支持選項，臨床上可考慮。",
            "C": "病況差不代表一定要 off-pump CABG；是否用體外循環取決於病灶、血流動力學與手術策略，說必須不停跳以減少併發症過度武斷。",
            "D": "多條冠狀動脈嚴重狹窄且合併休克或機械併發症時，外科血運重建可屬重要適應症，敘述可接受。",
        },
        "AMI 後休克合併新雜音要先找機械性併發症；off-pump CABG 不是病況差時的必然選擇。",
        "AMI；新收縮期雜音；off-pump CABG",
        "心肌梗塞後休克加新雜音需 echo 與支持；CABG 技術選擇不是固定必須 off-pump。",
        "AMI 後新雜音 -> C 過度絕對",
    ),
    update(
        26,
        "本題問末期心衰竭治療何者錯誤。STICH 試驗顯示在 CABG 加做 surgical ventricular restoration 並未較單純 CABG 改善主要臨床結局，因此 B 錯。官方答案 B。",
        {
            "A": "HeartMate II 是連續流左心室輔助器，可作為 bridge to transplant，也可作 destination therapy，敘述正確。",
            "B": "STICH 的 SVR 結果沒有證明 CABG 加左心室成型能改善症狀與存活率；本項把沒有明確利益說成改善，錯誤。",
            "C": "HeartWare 也是 LVAD，可用於長期支持與移植前橋接，敘述正確。",
            "D": "Total artificial heart 可在特定雙心室末期衰竭病人作為移植前支持，屬可行治療之一。",
        },
        "STICH：CABG 加 surgical ventricular restoration 未優於單純 CABG 的主要臨床結局。",
        "STICH；SVR；LVAD",
        "末期心衰竭可用 LVAD/人工心臟橋接；STICH 不支持常規加做 SVR 改善存活。",
        "末期心衰竭 -> STICH 不支持 SVR 加成",
    ),
    update(
        27,
        "本題問胸壁腫瘤中哪一種血液檢驗通常不異常。Fibrous dysplasia 是良性骨發育異常，通常沒有特異血液檢驗異常；其他惡性或漿細胞疾病較可能有實驗室異常。官方答案 B。",
        {
            "A": "Plasmacytoma 屬漿細胞腫瘤，可能有單株免疫球蛋白、貧血或骨髓相關檢驗異常，不是最佳答案。",
            "B": "Fibrous dysplasia 多為局部骨病變，血液檢查通常沒有特殊異常，因此正確。",
            "C": "Osteosarcoma 可伴隨 alkaline phosphatase 或 LDH 升高，血液檢驗較可能出現異常。",
            "D": "Ewing sarcoma 可有發炎指標、LDH 或血球相關變化，且為惡性腫瘤，不如 fibrous dysplasia 典型正常。",
        },
        "胸壁 fibrous dysplasia 通常血液檢驗無特異異常；惡性骨腫瘤或 plasmacytoma 較可能有異常。",
        "胸壁腫瘤；fibrous dysplasia",
        "Fibrous dysplasia 是良性骨發育異常，通常不造成血液檢驗異常。",
        "胸壁腫瘤血檢 -> fibrous dysplasia 通常正常",
    ),
    update(
        28,
        "本題問縱膈腔生殖細胞瘤何者正確。縱膈腔 GCT 多見於年輕男性，約三分之一為 seminoma；血清腫瘤標記與組織診斷都會影響判斷。官方答案 B。",
        {
            "A": "縱膈腔 germ cell tumor 不是最常發生在 65 歲以上，典型族群是年輕男性，因此錯。",
            "B": "縱膈腔 GCT 中 seminoma 佔相當比例，約三分之一可接受，因此正確。",
            "C": "Pure seminoma 通常 AFP 不升高，hCG 可輕度上升；若 AFP 高要懷疑 nonseminomatous component，因此本項錯。",
            "D": "診斷不能完全不看血液 AFP、beta-hCG 等腫瘤標記；FNA 也不一定是最安全且最正確的唯一方式。",
        },
        "縱膈腔 GCT 多見於年輕男性；seminoma 約佔三分之一，AFP 高則不支持 pure seminoma。",
        "mediastinal germ cell tumor；seminoma；AFP",
        "縱膈腔 GCT 約三分之一為 seminoma；pure seminoma 通常 AFP 不升高。",
        "縱膈腔 GCT -> seminoma 約三分之一",
    ),
    update(
        29,
        "本題考成人出血性休克分期。體重 60 公斤成人估計血量約 4.2 公升，第三期出血約 30-40% 全血量，會出現明顯心搏過速、低血壓與尿量下降。官方答案 C。",
        {
            "A": "第一期出血通常小於 15%，尿量多仍維持大於 30 mL/h；5-15 mL/h 已是較嚴重休克，不符合第一期。",
            "B": "第二期呼吸速率多約 20-30 次/分，14-20 次/分較接近第一期或正常範圍。",
            "C": "第三期出血量約 30-40% 全身血量，這是 ATLS 分期的典型記憶點，因此正確。",
            "D": "第四期心跳通常大於 140/min，100-120/min 較接近第二期，不符合第四期。",
        },
        "ATLS 出血性休克：Class III = 30-40% blood loss。",
        "hemorrhagic shock；ATLS Class III",
        "60 kg 成人血量約 4.2 L；第三期出血約 30-40%。",
        "出血性休克分期 -> 第三期 30-40%",
    ),
    update(
        30,
        "本題問張力性氣胸與心包膜填塞在理學檢查上的差別。兩者都可能有低血壓與頸靜脈怒張，但張力性氣胸會有單側呼吸聲下降與胸廓異常，tamponade 則以心音變小較典型。官方答案 A。",
        {
            "A": "張力性氣胸會造成患側呼吸聲降低或消失；心包膜填塞通常不造成兩側呼吸聲不一致，因此這是最能區分的發現。",
            "B": "外頸靜脈怒張可見於兩者，通常不是以左右不一致作為主要區分點。",
            "C": "心音變小是 tamponade 的 Beck triad 之一，張力性氣胸不典型，但選項 A 更直接區分氣胸。",
            "D": "血壓下降兩者都會發生，不能用來區分。",
        },
        "張力性氣胸和心包膜填塞都可低血壓/JVD；單側呼吸聲下降指向張力性氣胸。",
        "tension pneumothorax；cardiac tamponade",
        "兩者都可休克與 JVD；呼吸聲不一致最能區分 tension pneumothorax。",
        "張力性氣胸 vs tamponade -> 單側呼吸聲",
    ),
    update(
        31,
        "本題問肺部手術術前評估何者錯誤。阻塞性肺病的典型肺功能變化是 FEV1 下降較 FVC 明顯，使 FEV1/FVC ratio 下降，不是上升。官方答案 B。",
        {
            "A": "FEV1 < 60% predicted 代表通氣功能下降，肺切除後 pulmonary morbidity 風險增加，敘述正確。",
            "B": "Obstructive disease 如 COPD 會使 FEV1/FVC ratio 降低；說 ratio 上升是限制型疾病較可能的方向，因此錯誤。",
            "C": "DLCO < 40-50% 表示氣體交換能力差，會增加肺部手術風險，敘述正確。",
            "D": "VO2 max < 11-15 mL/kg/min 代表運動耐受性差，術後併發症與死亡風險增加，敘述正確。",
        },
        "阻塞性肺病的肺功能關鍵是 FEV1/FVC 下降。",
        "肺切除術前評估；FEV1/FVC",
        "Obstructive disease 使 FEV1/FVC 下降；DLCO 與 VO2 max 低代表手術風險高。",
        "肺部手術評估 -> 阻塞型 FEV1/FVC 下降",
    ),
    update(
        32,
        "本題問腹內壓上升何者錯誤。腹內高壓會推高橫膈、降低胸肺順應性、增加呼吸器壓力，對呼吸系統影響明顯；官方答案 A。",
        {
            "A": "腹內壓升高不只影響腹內器官灌流與靜脈回流，也會抬高橫膈、降低肺順應性並造成通氣困難；說呼吸影響不明顯是錯誤。",
            "B": "肥胖會增加基礎腹內壓，是 abdominal hypertension 的風險因素之一。",
            "C": "腹內高壓可依壓力分級；較低級別可先保守處理，嚴重或合併器官功能不全時需考慮減壓，敘述方向正確。",
            "D": "腹內壓高於約 25 mmHg 且合併器官功能惡化時，要高度懷疑 abdominal compartment syndrome 並評估手術減壓。",
        },
        "腹內高壓會同時傷害靜脈回流、腎腸灌流與呼吸力學。",
        "intra-abdominal pressure；abdominal compartment syndrome",
        "腹內壓升高會推高橫膈並降低肺順應性；呼吸影響很明顯。",
        "腹內壓升高 -> 呼吸影響明顯",
    ),
    update(
        33,
        "本題病人 BMI 43、第二型糖尿病控制不佳，又有 LA grade C 胃食道逆流；最適合的代謝減重手術是 Roux-en-Y gastric bypass，兼具減重、改善糖尿病與減少胃食道逆流效果。官方答案 B。",
        {
            "A": "Nissen fundoplication 可治療 GERD，但不是病態性肥胖合併糖尿病的代謝減重手術，不能解決主要問題。",
            "B": "Roux-en-Y gastric bypass 適合 BMI >40 或 BMI >35 合併代謝疾病者，且對 GERD 較 sleeve gastrectomy 友善，因此正確。",
            "C": "Vertical banded gastroplasty 已較少使用，減重與代謝效果不如胃繞道，也不適合此情境作為最佳答案。",
            "D": "Vagotomy 是傳統消化性潰瘍治療相關手術，不是現代代謝減重手術選擇。",
        },
        "BMI 43 合併 T2DM 與嚴重 GERD，Roux-en-Y gastric bypass 是較合適的減重代謝手術。",
        "病態性肥胖；T2DM；GERD；RYGB",
        "肥胖合併糖尿病與嚴重 GERD，優先考慮 Roux-en-Y gastric bypass。",
        "減重手術選擇 -> GERD 加 T2DM 選 RYGB",
    ),
    update(
        34,
        "本題問早期胃癌何者錯誤。Early gastric cancer 的定義是癌侵犯侷限於黏膜或黏膜下層，不論是否已有淋巴結轉移；因此侵犯黏膜下層仍可算早期胃癌。官方答案 A。",
        {
            "A": "早期胃癌可以侵犯到 submucosa，只要沒有超過黏膜下層即可；本項把黏膜下侵犯排除，錯誤。",
            "B": "早期胃癌已有淋巴結轉移的比例約一成上下，尤其黏膜下侵犯風險較高，敘述可接受。",
            "C": "早期胃癌定義看胃壁侵犯深度，不以淋巴結是否轉移排除，敘述正確。",
            "D": "早期胃癌中分化較好的腺癌比例高，題目給的約 70% 屬可接受考點。",
        },
        "早期胃癌 = 侵犯限於 mucosa/submucosa，與淋巴結轉移有無無關。",
        "early gastric cancer；submucosa",
        "癌侵犯到黏膜下層仍可稱 early gastric cancer；定義不看淋巴結狀態。",
        "早期胃癌定義 -> 可侵犯黏膜下層",
    ),
    update(
        35,
        "本題要計算 Child-Pugh score。病人意識清楚且無腹水各 1 分，白蛋白 4.3 為 1 分，INR 1.12 為 1 分，總膽紅素 2.52 mg/dL 為 2 分，合計 6 分。官方答案 B。",
        {
            "A": "5 分會是所有項目都 1 分；但此病人 bilirubin 2.52 mg/dL 落在 2-3 mg/dL，應給 2 分，所以不是 5。",
            "B": "bilirubin 2 分，加上 albumin、INR、ascites、encephalopathy 各 1 分，總分 6 分，因此正確。",
            "C": "7 分需要至少再多一個項目達 2 分；本題白蛋白、INR、腹水與腦病變都沒有達到。",
            "D": "8 分代表肝功能更差，與本題無腹水、無腦病變且凝血白蛋白良好不符。",
        },
        "Child-Pugh：bilirubin 2.52 給 2 分，其餘各 1 分，總分 6。",
        "Child-Pugh score；bilirubin",
        "無腹水/腦病變、Alb 4.3、INR 1.12 各 1 分；bilirubin 2.52 給 2 分，總分 6。",
        "Child-Pugh 計算 -> 6 分",
    ),
    update(
        36,
        "本題問現今肝內細菌性膿瘍最常見原因。現代常見來源是膽道感染或膽道阻塞相關的 ascending infection。官方答案 C。",
        {
            "A": "闌尾炎過去可經門脈造成肝膿瘍，但在現代不是最常見原因。",
            "B": "上腸繫膜動脈阻塞造成腸壞死可引起嚴重感染，但不是典型最常見肝膿瘍來源。",
            "C": "膽道感染、膽管炎或膽道阻塞可讓細菌上行進入肝內膽道，是目前常見原因，因此正確。",
            "D": "外傷可造成肝膿瘍或繼發感染，但比例上不是最常見。",
        },
        "細菌性肝膿瘍現代常見原因是膽道感染。",
        "肝膿瘍；膽道感染",
        "現代 pyogenic liver abscess 常由膽道感染或阻塞造成。",
        "細菌性肝膿瘍 -> 膽道感染",
    ),
    update(
        37,
        "本題問甲狀腺乳突癌合併頸部淋巴結與肺轉移何者正確。分化良好的乳突癌即使有轉移，仍常以甲狀腺全切除、頸部淋巴處理與術後放射性碘治療作為選項。官方答案 D。",
        {
            "A": "甲狀腺乳突癌不是以 paclitaxel 全身化療作首選；分化癌主要靠手術、放射性碘與 TSH suppression。",
            "B": "乳突癌整體預後通常相對良好，即使有可攝碘轉移也可能長期控制；不能說大多一年內死亡。",
            "C": "Methimazole 是治療甲狀腺亢進的抗甲狀腺藥，不能抑制乳突癌細胞生長作為癌症治療。",
            "D": "甲狀腺全切除可移除原發病灶並利於後續 I-131 治療與 thyroglobulin 追蹤，因此正確。",
        },
        "Papillary thyroid carcinoma 有轉移時仍可考慮全甲狀腺切除加 I-131。",
        "papillary thyroid carcinoma；I-131",
        "乳突癌治療核心是手術、放射性碘與追蹤；不是抗甲狀腺藥或一般化療首選。",
        "甲狀腺乳突癌轉移 -> total thyroidectomy + I-131",
    ),
    update(
        38,
        "本題問洗腎病人續發性副甲狀腺亢進何時建議副甲狀腺切除。Calciphylaxis 代表嚴重鈣磷代謝異常與皮膚缺血壞死，是手術介入的重要適應症。官方答案 D。",
        {
            "A": "鈣磷乘積 45 mg2/dL2 未達嚴重升高門檻，單獨看不構成手術適應症。",
            "B": "PTH 200 pg/mL 對洗腎病人並不算難治性嚴重升高，通常不會因此直接手術。",
            "C": "25(OH)D 40 nmol/L 表示維生素 D 不足，可先內科補充與調整礦物質代謝，不是切除適應症。",
            "D": "Calciphylaxis 是嚴重且可能致命的併發症，若與難治性副甲狀腺亢進相關，應考慮副甲狀腺切除，因此正確。",
        },
        "洗腎續發性副甲狀腺亢進若出現 calciphylaxis，屬重要手術適應症。",
        "secondary hyperparathyroidism；calciphylaxis",
        "Calciphylaxis 表示嚴重鈣磷代謝異常與皮膚缺血壞死，需考慮 parathyroidectomy。",
        "洗腎副甲狀腺亢進 -> calciphylaxis 要手術",
    ),
    update(
        39,
        "本題問原發性高醛固酮症與腎上腺腺瘤何者錯誤。篩檢用 ARR，確診可用鹽水負荷；但分辨單側腺瘤與雙側增生時，並不是 40 歲以下都常規必須做 adrenal vein sampling。官方答案 C。",
        {
            "A": "Aldosterone-to-renin ratio 是原發性高醛固酮症最常用初步篩檢，敘述正確。",
            "B": "靜脈生理食鹽水輸注試驗可用來確認 aldosterone 分泌是否可被抑制，敘述正確。",
            "C": "AVS 常用於區分單側與雙側分泌，但年輕、典型低血鉀、明顯醛固酮升高且 CT 單側腺瘤者可有例外；說 40 歲以下常規都要 AVS 不精確，因此錯誤。",
            "D": "單側分泌造成的低血鉀在腎上腺切除後常可迅速改善，敘述正確。",
        },
        "Primary aldosteronism：ARR 篩檢、鹽水負荷確認；AVS 是否需要依年齡與典型程度判斷。",
        "primary aldosteronism；ARR；AVS",
        "ARR 是篩檢，高鹽/鹽水負荷可確認；AVS 不是所有 40 歲以下都常規必做。",
        "原發性高醛固酮症 -> C 的 AVS 說法過度絕對",
    ),
    update(
        40,
        "本題問 ER/PR 陽性、HER2 1+ 的 infiltrating ductal carcinoma 何者正確。Invasive ductal carcinoma/NST 是最常見侵襲性乳癌，約占多數病例。官方答案 A。",
        {
            "A": "Infiltrating ductal carcinoma 是最常見侵襲性乳癌，約占 50-70% 或更高比例，敘述符合考點。",
            "B": "未停經且 ER/PR 陽性者常用 tamoxifen，aromatase inhibitor 通常需停經後或合併卵巢抑制，不能說最適合就是 AI。",
            "C": "HER2 1+ 屬 HER2 negative 傳統分類，不是術後雙標靶治療的典型適應症。",
            "D": "術後病理應寫 pT；1.2 cm 是 T1c 而非 T1b，且病理分期不應寫 cT1bN0M0。",
        },
        "IDC/NST 是最常見侵襲性乳癌；未停經 ER/PR 陽性多考慮 tamoxifen，HER2 1+ 不屬標靶陽性。",
        "invasive ductal carcinoma；ER/PR；HER2 1+",
        "IDC 是最常見侵襲性乳癌；HER2 1+ 不代表需要 HER2 標靶。",
        "乳癌病理與治療 -> IDC 最常見",
    ),
    update(
        41,
        "本題問侵襲性乳癌下一步治療何者正確。對適合乳房保留的病人，乳房保留手術加術後放射治療與全乳切除的長期存活率相近。官方答案 B。",
        {
            "A": "立即乳房重建不會因本身而降低存活率或增加局部復發率；需考量放療與併發症，但不是癌症預後禁忌。",
            "B": "乳房保留手術加放射治療可達到與全乳切除相近的長期存活，這是乳癌治療基本觀念，因此正確。",
            "C": "侵襲性乳癌乳房保留手術的陰性邊緣原則多為 no ink on tumor，並非為提高存活率一定要大於 2 mm。",
            "D": "乳房保留加 clear margin 的局部復發率可受放療與病人因素影響；相較全乳切除不能簡化為完全沒有差別。",
        },
        "早期乳癌：BCS + radiotherapy 與 mastectomy 長期存活率相近。",
        "breast conserving surgery；mastectomy",
        "適合病人可選 BCS + RT；長期存活率與全乳切除相近。",
        "乳癌手術選擇 -> BCS+RT 存活率不劣於全乳切除",
    ),
    update(
        42,
        "本題問膽道閉鎖診斷的黃金標準，官方答案為肝臟切片。嬰兒長期黃疸合併灰白便要高度懷疑膽道閉鎖，必須快速確認並轉介手術，以免錯過 Kasai portoenterostomy 時機。",
        {
            "A": "病毒血清可排除 TORCH、肝炎等新生兒膽汁鬱積原因，但不能作為診斷膽道閉鎖的黃金標準。",
            "B": "超音波可看 gallbladder、triangular cord sign 與其他構造異常，是重要初步檢查，但診斷力有限。",
            "C": "HIDA 若無腸道排泄可支持膽道阻塞，但重度肝細胞功能不良也會造成假陽性，不能單獨作黃金標準。",
            "D": "在本題選項中，肝臟切片可顯示膽管增生、膽汁栓塞與門脈區纖維化等典型變化，最符合官方答案。",
        },
        "膽道閉鎖重點是灰白便與持續膽汁鬱積；本題選項中以肝臟切片作黃金標準。",
        "biliary atresia；clay-colored stool；liver biopsy",
        "灰白便嬰兒要懷疑膽道閉鎖；本題官方選 liver biopsy。",
        "膽道閉鎖診斷 -> 本題選肝臟切片",
        ["部分臨床教材會把術中膽道攝影視為 definitive test；本題選項無該項且官方答案為肝臟切片，建議保留人工複核註記。"],
    ),
    update(
        43,
        "本題女嬰 4 個月大已有第二次泌尿道感染，且超音波有輕微水腎；此時最優先要找膀胱輸尿管逆流，檢查是 VCUG。官方答案 C。",
        {
            "A": "腹部 CT 有輻射且不是評估嬰兒 vesicoureteral reflux 的優先檢查，除非懷疑複雜膿瘍或其他問題。",
            "B": "MRI 不是反覆嬰兒 UTI 後評估 VUR 的第一線檢查，成本與可近性也不適合優先。",
            "C": "VCUG 可在排尿時觀察膀胱尿液逆流到輸尿管與腎盂，是評估 VUR 的標準檢查，因此正確。",
            "D": "IVP 對泌尿道解剖可提供資訊，但對 VUR 診斷不如 VCUG，且已較少作為優先檢查。",
        },
        "嬰兒反覆 febrile UTI 加水腎，要優先用 VCUG 評估 vesicoureteral reflux。",
        "recurrent UTI；VCUG；VUR",
        "反覆嬰兒 UTI 合併水腎，下一步優先 VCUG。",
        "反覆嬰兒 UTI -> VCUG",
    ),
    update(
        44,
        "本題為食道閉鎖相關圖片題，官方答案 D。新生兒餵食嗆咳、發紺、大量流涎且胃管無法進入胃部，典型懷疑 esophageal atresia with/without tracheoesophageal fistula；需先穩定呼吸、避免吸入，並評估 VACTERL 等合併異常，再安排手術。",
        {
            "A": "食道閉鎖有多種型態；若本題圖示符合常見 Gross type C 則有 distal TEF，但不是所有食道閉鎖都必定有瘻管，文字上此項需依圖判斷。",
            "B": "食道閉鎖常合併 VACTERL 相關異常，術前需檢查心臟、脊椎、肛門、腎臟與四肢等系統，敘述正確。",
            "C": "Gross type C，即近端食道閉鎖合併遠端氣管食道瘻管，是最常見型態，敘述正確。",
            "D": "手術時機需在穩定呼吸、控制吸入風險並完成重要合併異常評估後安排；若說沒有其他緊急狀況就一律儘速手術，官方判為較不適當。",
        },
        "食道閉鎖先穩定、抽吸近端囊袋並評估 VACTERL；手術時機取決於整體穩定與合併異常。",
        "esophageal atresia；TEF；VACTERL",
        "新生兒餵食嗆咳、流涎且 NG tube 下不去，懷疑食道閉鎖；術前要評估合併異常。",
        "食道閉鎖 -> 先穩定與評估，不是一句儘速手術",
        ["本題含食道鋇劑圖；官方答案為 D，但 A 的『必定』也可能因文字解讀有爭議，建議人工對照原圖與官方更正。"],
    ),
    update(
        45,
        "本題問 omphalocele 與 gastroschisis 何者錯誤。Omphalocele 常有包膜且與染色體、心臟等腸道外異常較相關；gastroschisis 無包膜，較常見腸道發育或功能問題。官方答案 B 把兩者特徵顛倒。",
        {
            "A": "Omphalocele 有囊膜包覆膨出臟器；gastroschisis 腸管直接暴露於羊水，無包膜，敘述正確。",
            "B": "腸道發育問題較常見於 gastroschisis；腸道外其他系統異常則較常伴隨 omphalocele，因此本項顛倒而錯誤。",
            "C": "Omphalocele 缺損位於臍部中線，臍帶插入囊膜，敘述正確。",
            "D": "Gastroschisis 的腹壁缺損典型在臍右側，敘述正確。",
        },
        "Omphalocele 有包膜且常合併腸道外異常；gastroschisis 無包膜且常有腸道問題。",
        "omphalocele；gastroschisis",
        "Omphalocele = 中線、有包膜、多合併其他異常；gastroschisis = 臍右側、無包膜、腸道問題多。",
        "腹壁缺損 -> B 顛倒兩者合併異常",
    ),
    update(
        46,
        "本題問哪位未合併疾病的手術病人最需要預防性抗生素。Nuss procedure 會置入金屬矯正板，植入物感染後處理困難，因此最需要 perioperative prophylaxis。官方答案 C。",
        {
            "A": "一般小兒腹股溝疝氣修補屬乾淨手術，若無網片或高風險因素，預防性抗生素需求較低。",
            "B": "單純睪丸固定手術多屬乾淨泌尿/陰囊手術，未合併感染時通常不是最需要抗生素的選項。",
            "C": "Nuss procedure 會放置胸壁金屬板，植入物感染風險與後果較大，因此最應給預防性抗生素。",
            "D": "頸部淋巴管瘤切除若無感染與植入物，通常屬乾淨手術，預防抗生素需求不如置入矯正板明確。",
        },
        "有植入物的乾淨手術通常比單純乾淨軟組織手術更需要預防性抗生素。",
        "prophylactic antibiotics；Nuss procedure",
        "Nuss procedure 置入金屬板，最需要預防性抗生素。",
        "小兒手術抗生素 -> 植入物優先",
    ),
    update(
        47,
        "本題問兒童頸部淋巴結何時最需要手術切片。鎖骨上淋巴結、單顆較大、持續或質地異常都提高惡性或重要病因風險；2 公分 supraclavicular node 最需要切片。官方答案 B。",
        {
            "A": "多顆 0.5 公分前頸部淋巴結常見於反應性增生或感染後變化，大小與位置都不特別高風險。",
            "B": "鎖骨上淋巴結即使兒童也屬警訊位置，且單顆 2 公分較大，最需要手術切片確認診斷。",
            "C": "0.8 公分耳後淋巴結常與頭皮或耳部感染相關，大小未達高風險。",
            "D": "0.5 公分枕骨區多顆淋巴結常見於頭皮感染或反應性變化，不是最需要切片者。",
        },
        "兒童頸部淋巴結警訊：supraclavicular、>2 cm、持續變大、硬固定或全身症狀。",
        "兒童頸部淋巴結；supraclavicular",
        "鎖骨上 2 公分單顆淋巴結是切片警訊。",
        "兒童淋巴結切片 -> supraclavicular 2 cm",
    ),
    update(
        48,
        "本題問結腸憩室炎必須手術適應症。游離穿孔造成腹膜炎與結腸膀胱瘻管是明確手術適應症；小型局部膿瘍可先抗生素或引流，貧血較像憩室出血議題，不是憩室炎必須手術。官方答案 B：僅 1、3。",
        {
            "A": "包含 2 的局部 2 公分膿瘍並不一定必須手術，許多可先保守治療，因此僅 1、2、3 不正確。",
            "B": "1 游離穿孔腹膜炎與 3 結腸膀胱瘻管都是複雜性憩室炎手術適應症，因此正確。",
            "C": "2 不一定必須手術，4 貧血不是憩室炎本身的手術適應症，故不對。",
            "D": "把小膿瘍與貧血都列為必須手術過度擴大適應症，不正確。",
        },
        "憩室炎必須手術：free perforation with peritonitis、fistula、無法控制敗血症或保守失敗。",
        "diverticulitis；perforation；colovesical fistula",
        "憩室炎游離穿孔腹膜炎與瘻管需手術；小膿瘍可先保守或引流。",
        "憩室炎手術適應症 -> 1 和 3",
    ),
    update(
        49,
        "本題比較 UC 與 Crohn colitis 何者錯誤。Crohn disease 典型是 transmural inflammation，會造成腸壁增厚、狹窄與 creeping fat；UC 主要限於黏膜層，較不會有 thickened colon wall。官方答案 A。",
        {
            "A": "Thickened colon wall 是 Crohn colitis 較典型的 gross feature，不是 UC 較多，因此本項錯誤。",
            "B": "Crohn colitis 可見 transmural lymphoid aggregates 與 granuloma 等特徵，敘述正確。",
            "C": "UC 以連續性黏膜發炎與潰瘍為主，血便比 Crohn 更典型，敘述正確。",
            "D": "Crohn disease 會復發於小腸與 pouch，通常是 ileal pouch-anal anastomosis 的禁忌或相對禁忌，敘述正確。",
        },
        "UC 主要黏膜層、血便常見；Crohn 是 transmural，腸壁增厚與 lymphoid aggregates 較典型。",
        "ulcerative colitis；Crohn colitis",
        "Crohn 才常見 thickened bowel wall；UC 較典型是血便與連續性黏膜病灶。",
        "UC vs Crohn -> 厚壁屬 Crohn",
    ),
    update(
        50,
        "本題問骨盆底肌肉群何者錯誤。Levator ani 主要包括 pubococcygeus、puborectalis、iliococcygeus；piriformis 屬臀部深層肌，不是 levator ani 的組成。官方答案 A。",
        {
            "A": "Levator ani 不包含 piriformis；應包含 iliococcygeus 等肌群，因此本項錯誤。",
            "B": "骨盆底肌肉維持骨盆器官支撐，並與肛門括約肌協調排便控制，敘述正確。",
            "C": "Puborectalis 形成 U 型吊帶，放鬆時 anorectal angle 變直，有助排便，敘述正確。",
            "D": "骨盆底功能障礙可造成便祕、排便不全、失禁或骨盆器官脫垂等問題，敘述正確。",
        },
        "Levator ani = pubococcygeus、puborectalis、iliococcygeus；不含 piriformis。",
        "pelvic floor；levator ani；piriformis",
        "提肛肌不包含梨狀肌；恥骨直腸肌放鬆可拉直肛門直腸角。",
        "骨盆底肌肉 -> piriformis 不是 levator ani",
    ),
    update(
        51,
        "本題問總膽管結石何者正確。ERCP 加 sphincterotomy/取石是總膽管結石常用且成功率高的治療方式之一，尤其適合先解除膽道阻塞。官方答案 A。",
        {
            "A": "ERCP 可直接取出 CBD stone 或放置支架，是常用治療方式，因此正確。",
            "B": "ERCP 取出總膽管結石成功率通常高於 50%，本項明顯低估。",
            "C": "ERCP 後復發風險常與年齡、膽道擴張、膽囊未處理等因素相關，老人不一定低於年輕人；本項不正確。",
            "D": "腹腔鏡膽囊切除合併總膽管探查是選項之一，但不一定優先於 ERCP；需依病人狀況與資源決定。",
        },
        "CBD stone 可用 ERCP 取石，成功率高且常作為解除膽道阻塞的一線方式。",
        "CBD stone；ERCP",
        "總膽管結石常以 ERCP 取石；不是只有不到 50% 成功。",
        "總膽管結石 -> ERCP 是治療方式",
    ),
    update(
        52,
        "本題問 single-incision laparoscopic surgery 設備與操作益處何者錯誤。單孔手術器械容易互相干擾，因此細長或小直徑器械與鏡頭都有助於減少碰撞、增加操作空間與視野。官方答案 C。",
        {
            "A": "細長器械可減少體外手柄與體內器械互相碰撞，對單孔手術有幫助。",
            "B": "較細長器械可在狹小切口與有限 triangulation 下提升操作便利性，敘述正確。",
            "C": "小直徑鏡頭可減少單孔通道擁擠，對操作空間有幫助；說沒有幫助是錯誤。",
            "D": "高解析影像能補償單孔手術視角限制並提升辨識組織能力，敘述正確。",
        },
        "單孔腹腔鏡的難點是器械擁擠與碰撞；細長器械、小直徑鏡頭與高解析視野都有幫助。",
        "single-incision laparoscopic surgery；小直徑鏡頭",
        "單孔手術空間有限，小直徑鏡頭可減少擁擠，不是無幫助。",
        "單孔腹腔鏡 -> C 否定小鏡頭效益",
    ),
    update(
        53,
        "本題問哪項不是 robotic surgery 的優點。達文西系統提供符合人體工學的 console、3D 立體視野、影像穩定與去顫，但仍需要 bedside assistant 更換器械、吸引、牽引與處理突發狀況。官方答案 D。",
        {
            "A": "Console 可讓外科醫師以較符合人體工學的姿勢操作，是機械手臂優點之一。",
            "B": "3D stereoscopic vision 是 robotic surgery 的重要優勢，可增加深度感。",
            "C": "系統可過濾手部 tremor，讓精細操作更穩定，敘述屬優點。",
            "D": "手術仍需 bedside assistant 協助 trocar、換器械、吸引與緊急處理；說不需要助手是錯誤。",
        },
        "Robotic surgery 有 3D 視野與 tremor filtering，但仍需要 bedside assistant。",
        "robotic surgery；bedside assistant",
        "達文西優點包含 3D、去顫與人體工學；缺點是仍需床邊助手與團隊配合。",
        "robotic surgery -> 仍需 bedside assistant",
    ),
    update(
        54,
        "本題術後第 7 天開始正常進食後，引流量突然增加且變成乳白混濁，病人無發燒，最符合淋巴管受傷後的 chyle leak。官方答案 C。",
        {
            "A": "Pancreatic leak 常見引流液 amylase 升高，外觀不一定是乳白色，且與進食脂肪後乳糜增加的線索較不吻合。",
            "B": "Intra-abdominal abscess 常伴發燒、腹痛、白血球上升或膿性引流；本題無感染症狀，不像膿瘍。",
            "C": "Chyle leak 典型在恢復進食尤其脂肪攝取後出現乳白色高量引流液，因此最可能。",
            "D": "Bile leak 常呈黃綠色膽汁樣，引流液 bilirubin 高，不會典型呈乳白色混濁。",
        },
        "術後進食後乳白色大量引流液，要想到 chyle leak。",
        "chyle leak；胰十二指腸切除術後",
        "進食後引流變乳白且量大，最符合乳糜液滲漏。",
        "術後乳白引流 -> chyle leak",
    ),
    update(
        55,
        "本題承上題診斷 chyle leak，檢查應見三酸甘油脂升高、膽固醇相對低，且淋巴球比例高。官方答案 A：4、5。",
        {
            "A": "Chyle 富含 triglyceride 與淋巴球，cholesterol 相對低，因此 4、5 符合診斷。",
            "B": "細菌培養陽性偏向膿瘍或感染；amylase 高偏向胰液滲漏，不符合 chyle leak。",
            "C": "細菌培養陽性與低 triglyceride、高 cholesterol 都不支持乳糜液滲漏。",
            "D": "Amylase 高是 pancreatic leak 線索；低 triglyceride 與高 cholesterol 也和 chyle leak 相反。",
        },
        "Chyle leak：drain triglyceride 高、lymphocyte predominance、cholesterol 相對低。",
        "chyle leak；triglyceride；lymphocyte",
        "乳糜液滲漏檢查是 TG 高與淋巴球比例高。",
        "chyle leak 檢驗 -> 4 和 5",
    ),
    update(
        56,
        "本題病人頸椎骨折合併四肢癱瘓、低血壓、心跳不快且四肢不冰冷，符合脊髓損傷後交感神經失張力造成的 neurogenic shock。官方答案 C。",
        {
            "A": "Anaphylactic shock 通常有過敏暴露、皮疹、支氣管痙攣或血管性水腫，題幹沒有這些線索。",
            "B": "Hypovolemic shock 常見心搏過速與四肢冰冷濕黏；本題沒有失血線索，且心跳 60/min 不符合代償性心搏過速。",
            "C": "高位脊髓損傷會造成交感輸出下降、血管擴張與相對 bradycardia，最符合 neurogenic shock。",
            "D": "Cardiogenic shock 需心肌梗塞、心律不整或心泵衰竭線索；題幹主要是頸髓損傷。",
        },
        "頸髓損傷後低血壓合併相對心搏過慢與溫暖肢體，典型為 neurogenic shock。",
        "neurogenic shock；cervical spinal cord injury",
        "高位脊髓損傷造成交感失張力，休克時不會有典型心搏過速。",
        "頸髓損傷休克 -> neurogenic shock",
    ),
    update(
        57,
        "本題年輕運動員扭轉落地、膝內啪聲、數小時內大量血膝，最典型是 anterior cruciate ligament 斷裂。官方答案 B。",
        {
            "A": "Quadriceps tendon rupture 多見於較年長或慢性肌腱病變，會有主動伸膝困難，不是急性血膝最典型原因。",
            "B": "ACL rupture 常在非接觸或扭轉落地時發生，聽到 pop 並快速 hemarthrosis，是最符合的診斷。",
            "C": "Patellar tendon rupture 會造成主動伸膝障礙與髕骨高位，題幹沒有這些伸膝機轉線索。",
            "D": "Prepatellar bursitis 是髕前滑囊發炎腫脹，通常不是關節腔抽出大量暗紅血液。",
        },
        "運動扭轉落地後 pop 聲加快速 hemarthrosis，要想到 ACL rupture。",
        "ACL rupture；acute hemarthrosis",
        "年輕運動員扭轉受傷、啪聲、數小時內血膝，最像 ACL 斷裂。",
        "急性血膝 -> ACL rupture",
    ),
    update(
        58,
        "本題問 Paget disease 何者最正確。Paget disease 是骨吸收與骨生成都增加、重塑失序的高轉換骨病；病理可見 mosaic pattern、粗大骨小樑、woven bone 與 cement lines。官方答案 B。",
        {
            "A": "Paget disease 不是單純骨生成增加且骨吸收降低，而是破骨與造骨活動都增加但排列混亂，故錯。",
            "B": "粗大骨小樑、不規則 woven bone 與明顯 cement lines 是典型病理特徵，因此正確。",
            "C": "尿中 pyridinoline、deoxypyridinoline 等骨吸收標記通常升高，不是偏低。",
            "D": "治療常用 bisphosphonate 抑制破骨細胞活性，不是連續 PTH 注射。",
        },
        "Paget disease 是高骨轉換且重塑混亂；病理為 mosaic cement lines，治療常用 bisphosphonate。",
        "Paget disease；cement lines；bisphosphonate",
        "Paget 病理有粗大骨小樑與 mosaic cement lines；骨轉換標記升高。",
        "Paget disease -> mosaic cement lines",
    ),
    update(
        59,
        "本題問 solitary osteochondroma 與 multiple hereditary exostoses 何者最正確。發生在骨盆、肩胛骨等軀幹扁平骨的外生骨贅，惡性轉化為 chondrosarcoma 的風險較高。官方答案 C。",
        {
            "A": "Multiple hereditary exostoses 多為自體顯性遺傳，外顯率高；不是自體隱性且外顯率低。",
            "B": "Osteochondroma 的骨性突起通常朝遠離相鄰關節方向生長，不是朝關節方向。",
            "C": "骨盆、肩胛骨等扁平骨病灶較難追蹤且 cartilage cap 惡性變風險較高，因此本項正確。",
            "D": "無症狀 osteochondroma 常可觀察到骨骼成熟後；未成熟前常規切除並非必要，除非疼痛、壓迫或疑惡性。",
        },
        "Osteochondroma 若位於骨盆或肩胛骨等軀幹扁平骨，惡性轉化風險較高。",
        "osteochondroma；multiple hereditary exostoses",
        "MHE 是 AD；骨盆/肩胛骨外生骨贅惡性化風險較高。",
        "骨軟骨瘤 -> 軀幹扁平骨惡性化風險高",
    ),
    update(
        60,
        "本題問踝部骨折 X 光三相位何者最不適當。踝部標準影像包含 AP、lateral、mortise；AP view 不是用來判斷跟骨骨折的最佳相位，跟骨需側位與 axial/Harris view。官方答案 C。",
        {
            "A": "踝部骨折基本 X 光常包含 AP、lateral、mortise views，敘述正確。",
            "B": "Mortise view 可打開 ankle mortise，對判斷 talar lateral shift 與 syndesmosis/medial clear space 有幫助。",
            "C": "Calcaneus fracture 不是靠踝部 AP view 最有助判斷，需跟骨專用影像；本項最不適當。",
            "D": "Lateral view 可看 posterior malleolus fragment 與踝關節後方關係，敘述正確。",
        },
        "踝部骨折看 AP、lateral、mortise；跟骨骨折需跟骨專用側位與軸位，不是踝 AP 最有用。",
        "ankle fracture；mortise view；calcaneus",
        "Mortise 看距骨外移；側位看後踝；跟骨骨折不是踝 AP 的重點。",
        "踝部 X 光 -> AP 不最適合看跟骨",
    ),
    update(
        61,
        "本題問黏多醣症病童最少發生哪種骨骼病變。Mucopolysaccharidoses 的 dysostosis multiplex 可見鎖骨變寬、脊椎體形狀異常與髖臼發育不良；髖內翻不是典型常見表現。官方答案 D。",
        {
            "A": "Broad clavicle 屬 dysostosis multiplex 可見的骨骼表現，不是最少發生。",
            "B": "Ovoid 或異常形狀脊椎體可見於黏多醣症骨病變，屬常見考點。",
            "C": "Acetabular dysplasia 與髖關節發育異常可見於黏多醣症，不是最少發生。",
            "D": "MPS 較典型為髖臼發育不良、髖外翻或股骨頭問題；coxa vara 相對不是典型常見，因此最符合答案。",
        },
        "MPS 的 dysostosis multiplex 包含鎖骨、脊椎與髖臼異常；coxa vara 相對少見。",
        "mucopolysaccharidoses；dysostosis multiplex",
        "黏多醣症常見 broad clavicle、vertebral body abnormality、acetabular dysplasia；較少 coxa vara。",
        "MPS 骨病變 -> coxa vara 最少見",
    ),
    update(
        62,
        "本題問 cubital tunnel syndrome 何者最不適當。此病是尺神經在肘部受壓，臨床診斷加神經傳導/肌電圖最常用；MRI 不是最常用檢查。官方答案 C。",
        {
            "A": "Cubital tunnel syndrome 是尺神經在肘隧道或其附近受壓，敘述正確。",
            "B": "尺神經感覺支配小指與無名指尺側半，麻木位置符合本病。",
            "C": "最常用的輔助檢查是 nerve conduction study/electromyography；MRI 可用於特殊結構病灶評估，但不是最常用，因此錯誤。",
            "D": "晚期尺神經運動支受損會有 intrinsic muscle wasting 與 claw hand，敘述正確。",
        },
        "Cubital tunnel syndrome 是尺神經壓迫；常用神經傳導與肌電圖，不是 MRI。",
        "cubital tunnel syndrome；ulnar nerve；EMG",
        "小指與無名指尺側麻、晚期 claw hand；常用 NCS/EMG 檢查。",
        "肘隧道症候群 -> MRI 不是最常用",
    ),
    update(
        63,
        "本題問 adolescent idiopathic scoliosis 何者最正確。AIS 的典型胸椎主彎凸側多在右側；女性在嚴重或需治療曲線比例較高，但 10 度輕微側彎不會到女男 10:1。官方答案 B。",
        {
            "A": "側彎角約 10 度時性別差距不大；女性比例會在較大角度、進展性曲線中明顯上升，10 倍說法不適當。",
            "B": "AIS 最常見胸椎右凸曲線，若胸椎左凸反而要注意非典型原因，因此本項正確。",
            "C": "Risser sign 通常從髂嵴外側/前外側骨化並向後內側進展，不是前下腸骨脊開始。",
            "D": "越年輕、骨骼越不成熟時發病，進展風險越高；年紀越大才發病通常惡化風險較低。",
        },
        "AIS 典型胸椎右凸；進展風險高在年紀小、Risser 低、曲線大。",
        "adolescent idiopathic scoliosis；right thoracic curve",
        "青春期自發性脊椎側彎常見右胸凸；越接近骨骼成熟，惡化風險越低。",
        "AIS -> 胸椎凸側多為右側",
    ),
    update(
        64,
        "本題問飲食來源草酸占尿中草酸比例。大部分尿中草酸來自內生性代謝，飲食直接貢獻約 10-15%。官方答案 B。",
        {
            "A": "1-5% 低估飲食草酸對尿中草酸的貢獻，不是典型比例。",
            "B": "飲食獲得草酸約占尿液排出草酸 10-15%，是本題記憶點，因此正確。",
            "C": "40-50% 過高，會誤以為尿中草酸主要由飲食直接決定。",
            "D": "80-90% 明顯過高；尿中草酸多數仍與內生性代謝相關。",
        },
        "尿中草酸多數為內生性；飲食草酸約占 10-15%。",
        "oxalate；尿路結石",
        "Dietary oxalate 約占尿中 oxalate 10-15%。",
        "尿中草酸來源 -> 飲食約 10-15%",
    ),
    update(
        65,
        "本題問睪丸腫瘤何者錯誤。隱睪是睪丸癌風險因子；睪丸固定術主要改善檢查與保留功能，考試傳統常強調不能完全消除或明顯降低癌化風險，尤其小學才手術已偏晚。官方答案 C。",
        {
            "A": "Seminoma 是睪丸生殖細胞腫瘤中常見類型，敘述正確。",
            "B": "隱睪病人睪丸腫瘤風險較高，題目給 7-10% 可視為隱睪與腫瘤關聯的考點。",
            "C": "Orchidopexy 並不能把睪丸癌風險恢復到一般人，且小學時矯正已非最佳早期時機；因此本項說可減少發生為官方錯誤點。",
            "D": "胎內荷爾蒙環境與生殖細胞腫瘤風險被認為有關，母體 estrogen 暴露是傳統考點之一，敘述可接受。",
        },
        "隱睪增加睪丸癌風險；orchidopexy 改善追蹤與生育，不能視為完全預防癌症。",
        "testicular tumor；cryptorchidism；orchidopexy",
        "隱睪是睪丸癌風險因子；固定術不等於消除癌症風險。",
        "睪丸腫瘤 -> orchidopexy 不可當作癌症預防保證",
    ),
    update(
        66,
        "本題問前列腺癌何者錯誤。PSA 可用於篩檢、風險分層、追蹤治療反應，但不是比影像更適合用來偵測淋巴結轉移的工具。官方答案 A。",
        {
            "A": "PSA 高低反映腫瘤負荷與預後風險，但無法直接定位淋巴結轉移；CT/MRI 等影像才是評估淋巴結的工具，因此本項錯誤。",
            "B": "一般而言 PSA 越高，代表腫瘤負荷或進展風險越高，預後較差，敘述正確。",
            "C": "前列腺癌常轉移骨骼，晚期死亡病人骨轉移比例高，敘述正確。",
            "D": "骨轉移常見於中軸骨，尤其脊椎與骨盆，敘述正確。",
        },
        "PSA 用於風險與追蹤，不是偵測淋巴結轉移的影像工具替代品。",
        "prostate cancer；PSA；lymph node metastasis",
        "PSA 高代表風險高，但不能直接偵測淋巴結轉移；骨轉移常在脊椎骨盆。",
        "前列腺癌 -> PSA 不優於影像偵測淋巴結",
    ),
    update(
        67,
        "本題問腎細胞癌 Stauffer syndrome 可能與何種因子過多有關，官方答案為 GM-CSF。Stauffer syndrome 是腎癌的副腫瘤性肝功能異常，沒有肝轉移卻出現膽汁鬱積型肝功能異常與發炎表現。",
        {
            "A": "TNF 可參與癌症發炎與惡病質，但題目所問的腎癌副腫瘤性肝功能異常並未以 TNF 作為命題關鍵。",
            "B": "Interferon 與免疫調節相關，也曾出現在腎癌治療歷史中；它不是用來解釋此症候群的主要分泌因子。",
            "C": "EGF 與細胞增生訊號有關，並非此副腫瘤症候群的考試關鍵。",
            "D": "本題官方採 GM-CSF 作為腎癌相關副腫瘤表現可能因子，因此選 D。",
        },
        "Stauffer syndrome 是 RCC 的副腫瘤性肝功能異常；本題官方因子為 GM-CSF。",
        "renal cell carcinoma；Stauffer syndrome；GM-CSF",
        "RCC 可有 Stauffer syndrome；本題官方選 GM-CSF。",
        "腎癌 Stauffer syndrome -> 官方 GM-CSF",
        ["常見現代資料也會提到 IL-6 與 Stauffer syndrome；本題選項沒有 IL-6 且官方答案為 GM-CSF，建議人工複核教材來源。"],
    ),
    update(
        68,
        "本題問 5-alpha reductase inhibitor 治療 BPH 何者錯誤。5-ARI 透過降低 DHT 使前列腺縮小，主要適合前列腺體積較大的病人；體積小者療效有限。官方答案 D。",
        {
            "A": "Finasteride、dutasteride 抑制 testosterone 轉為 DHT，可讓腺體上皮萎縮並縮小前列腺，敘述正確。",
            "B": "5-ARI 起效慢，通常需 6 個月以上才能達最大或明顯療效，敘述正確。",
            "C": "治療後前列腺體積可約縮小 20%，PSA 約下降 50%，追蹤 PSA 時要校正解讀，敘述正確。",
            "D": "5-ARI 對前列腺較大者效果較好，對小體積 BPH 症狀改善有限；說不論大小均有療效是錯誤。",
        },
        "5-ARI 適合較大前列腺，使用後 PSA 約下降一半，效果需數月。",
        "BPH；5-alpha reductase inhibitor；PSA",
        "5-ARI 會降低 DHT、縮小前列腺；不是所有大小前列腺都有效。",
        "BPH 5-ARI -> 大前列腺較有效",
    ),
    update(
        69,
        "本題問急性細菌性副睪丸炎何者錯誤。年輕男性常與性傳染病原如 Chlamydia、Gonorrhea 相關；糖尿病或泌尿道結構問題較常見於年長或複雜感染族群。官方答案 B。",
        {
            "A": "急性副睪丸炎常造成陰囊疼痛腫脹，嚴重時理學檢查難區分睪丸與副睪丸，敘述正確。",
            "B": "年輕男性多與性行為相關病原有關，不是通常與糖尿病有關，因此錯誤。",
            "C": "小男孩發生副睪丸炎需考慮尿路先天異常或尿液逆流，敘述正確。",
            "D": "若形成膿瘍或感染無法控制，常需外科引流，敘述正確。",
        },
        "急性副睪丸炎：年輕男性想到 STI；小兒想到泌尿道解剖異常；膿瘍需引流。",
        "acute epididymitis；STI；糖尿病",
        "年輕男性副睪丸炎多與 Chlamydia/Gonorrhea 相關，不是糖尿病為主。",
        "副睪丸炎 -> 年輕男性不是糖尿病典型",
    ),
    update(
        70,
        "本題問高齡男性低睪固酮無關症狀。低 testosterone 可造成性慾下降、骨質疏鬆、肌肉量下降與肥胖/代謝症候群相關；venous leakage 是陰莖血管閉鎖機制問題，不是低睪固酮本身的典型症狀。官方答案 B。",
        {
            "A": "Decreased libido 是低睪固酮最典型症狀之一，不是答案。",
            "B": "海綿體靜脈溢漏屬勃起時靜脈閉鎖功能不全，偏血管結構/功能問題，與低睪固酮症候群不直接相同，因此為答案。",
            "C": "Testosterone 對骨密度有維持作用，低下可導致 osteoporosis，敘述相關。",
            "D": "肥胖與低睪固酮常互相相關，並可伴隨代謝症候群，敘述相關。",
        },
        "男性低睪固酮典型為性慾低、骨密度下降、肌肉量下降與代謝問題；venous leak 屬血管性 ED。",
        "late-onset hypogonadism；venous leakage",
        "低睪固酮會低性慾與骨鬆；海綿體 venous leakage 不是典型低睪固酮症狀。",
        "低睪固酮 -> venous leakage 無直接關係",
    ),
    update(
        71,
        "本題問睪丸生理何者正確。LH 作用於 Leydig cell 促進 testosterone 分泌；FSH 作用於 Sertoli cell 支持造精；精液 fructose 主要來自儲精囊。官方答案 C。",
        {
            "A": "LH 主要作用在 Leydig cell，不是 Sertoli cell，因此錯。",
            "B": "FSH 主要作用在 Sertoli cell，支持 spermatogenesis，不是 Leydig cell。",
            "C": "Testosterone 由 Leydig cell 產生，是本題正確敘述。",
            "D": "精液中的 fructose 主要由 seminal vesicle 分泌，不是前列腺；前列腺主要提供 PSA、citrate 等成分。",
        },
        "LH-Leydig-testosterone；FSH-Sertoli-spermatogenesis；fructose 來自 seminal vesicle。",
        "Leydig cell；Sertoli cell；fructose",
        "LH 作用 Leydig 產生 testosterone；FSH 作用 Sertoli；fructose 來自儲精囊。",
        "睪丸生理 -> Leydig 產生 testosterone",
    ),
    update(
        72,
        "本題為血管攝影圖片題，官方答案 B。下腸繫膜動脈血管攝影若箭號位於直腸上段出血，最可能來源是 superior rectal artery，這是 IMA 的終末分支。官方答案 B。",
        {
            "A": "Internal pudendal artery 來自 internal iliac system，主要供應會陰與外生殖器，不是 IMA 攝影中典型直腸上段出血來源。",
            "B": "Superior rectal artery 是 inferior mesenteric artery 的延續，供應上直腸，最符合 IMA angiography 的箭號出血。",
            "C": "Inferior gluteal artery 來自 internal iliac，供應臀部，不符合下腸繫膜動脈攝影路徑。",
            "D": "Superior vesical artery 供應膀胱上部，來自 internal iliac，不是 IMA 分支。",
        },
        "IMA 的終末分支是 superior rectal artery，供應上直腸。",
        "inferior mesenteric artery；superior rectal artery",
        "下腸繫膜動脈攝影看到直腸出血，選 superior rectal artery。",
        "IMA 血管攝影 -> superior rectal artery",
        ["本題仰賴血管攝影箭號位置；目前文字資料沒有圖片，建議人工對照原圖確認出血點。"],
    ),
    update(
        73,
        "本題為 IVU 圖片題，官方答案 C。肉眼血尿合併腎盂或集尿系統內填充缺損，最要考慮上泌尿道 urothelial cell carcinoma。官方答案 C。",
        {
            "A": "Renal cell carcinoma 多來自腎實質，影像常是實質腫塊造成腎輪廓變形或壓迫 collecting system，不是典型集尿系統內病灶。",
            "B": "Renal lymphoma 可造成多發腎實質病灶或腎臟腫大，但以肉眼血尿與 IVU 集尿系統填充缺損作為典型表現較不合。",
            "C": "Renal pelvis/upper tract urothelial carcinoma 常以無痛性血尿表現，IVU 可見集尿系統 filling defect，因此最可能。",
            "D": "Angiomyolipoma 是含脂肪的腎實質良性腫瘤，CT 脂肪密度較具診斷性，與本題 IVU 線索不符。",
        },
        "無痛性肉眼血尿加集尿系統 filling defect，要想到 upper tract urothelial carcinoma。",
        "gross hematuria；IVU；upper tract urothelial carcinoma",
        "IVU 若見 renal pelvis filling defect，最像 renal urothelial cell carcinoma。",
        "血尿 IVU -> 腎盂尿路上皮癌",
        ["本題依賴 IVU 圖像；目前文字資料沒有圖片，建議人工對照原圖確認 filling defect 位置。"],
    ),
    update(
        74,
        "本題為三相式 CT 圖片題，官方答案 B。HCC 典型影像是動脈期增強、門脈/延遲期 washout；AFP 可以正常，肝功能也可能尚可，不能因此排除。官方答案 B。",
        {
            "A": "Hemangioma 典型是周邊結節狀不連續增強並逐漸向中央填入，若題圖為 arterial enhancement with washout 則不符合。",
            "B": "Hepatocellular carcinoma 可呈 arterial phase hyperenhancement 與 venous washout，即使 AFP 正常仍可能成立，因此正確。",
            "C": "Hepatic cyst 通常為水樣低密度且不增強，不會有典型三相血流增強變化。",
            "D": "Cholangiocarcinoma 常有延遲性纖維性增強、膽管擴張或周邊病灶特徵，與典型 HCC vascular pattern 不同。",
        },
        "HCC 影像重點是 arterial enhancement 與 portal/venous washout；AFP 正常不能排除。",
        "hepatocellular carcinoma；triphasic CT；AFP normal",
        "三相 CT 若動脈期增強、靜脈期 washout，即使 AFP 正常仍可診斷 HCC。",
        "肝臟三相 CT -> HCC 可 AFP 正常",
        ["本題仰賴 CT 圖像；目前文字資料沒有圖片，建議人工對照原圖確認增強型態。"],
    ),
    update(
        75,
        "本題問病態性肥胖術後何者最正確。Roux-en-Y gastric bypass 後常見功能性併發症之一是 dumping syndrome，通常在開始進食後出現心悸、冒汗、腹痛、腹瀉或低血糖相關症狀。官方答案 D。",
        {
            "A": "胃繞道後若有腸阻塞，依阻塞位置可能出現膽汁性嘔吐；不能說不會有膽汁嘔吐物。",
            "B": "術後併發症與病人風險、手術種類及外科技術都有關，不能說與技術無明顯關係。",
            "C": "吻合口潰瘍多是較晚期併發症，與胃酸、抽菸、NSAID、缺血等相關，不是通常術後 3-5 天產生。",
            "D": "Dumping syndrome 是 RYGB 常見併發症，與食物快速進入小腸有關，開始進食後才會表現，因此最正確。",
        },
        "RYGB 常見併發症包含 dumping syndrome，與進食後高滲食糜快速進入小腸相關。",
        "Roux-en-Y gastric bypass；dumping syndrome",
        "胃繞道後開始進食出現 dumping syndrome 是常見考點。",
        "減重手術併發症 -> RYGB dumping syndrome",
    ),
    update(
        76,
        "本題是懷孕 34 週外傷合併腹痛、陰道出血與休克。需同時照顧母體復甦與胎兒風險；官方答案 A 指出陰道液 pH 偏鹼支持羊膜破裂，但其餘選項有危險或不精確處。",
        {
            "A": "羊水偏鹼性，陰道分泌物 pH 約 7 可支持 amniotic membrane rupture，需再配合臨床與檢查確認，因此為官方答案。",
            "B": "陰道出血時若未先排除 placenta previa，貿然內診可能造成大量出血，應先以超音波等方式評估。",
            "C": "懷孕後期休克復甦要避免子宮壓迫下腔靜脈，通常採左側傾斜或墊高右髖使子宮左移；題目寫左側抬高容易造成方向錯誤。",
            "D": "孕婦創傷以母體救命優先；必要的腹部或骨盆 CT 不應只因胎兒輻射就禁做，需衡量風險並適當防護。",
        },
        "孕婦創傷先救母體；疑前置胎盤避免直接內診，必要影像不可因懷孕一概禁止。",
        "pregnancy trauma；ROM；placenta previa；CT",
        "陰道液 pH 偏鹼支持破水；孕婦休克需左側傾斜/子宮左移並以母體復甦優先。",
        "孕婦創傷 -> pH 7 支持羊膜破裂",
    ),
    update(
        77,
        "本題計算 GCS。疼痛刺激會張眼是 E2，發出無法理解聲音是 V2，左右手臂反應要取最佳運動反應；左手能撥開疼痛是 localizes pain，M5。總分 2+2+5=9。官方答案 C。",
        {
            "A": "7 分低估了最佳運動反應；不能因右手臂變形無反應就忽略左手較好的反應。",
            "B": "8 分仍少算了 localizes pain 的 M5，或把運動反應算成 withdraw M4。",
            "C": "E2、V2、M5 合計 9 分，符合題幹描述，因此正確。",
            "D": "10 分會需要更好的睜眼、語言或運動反應；題幹語言只有 incomprehensible sounds，不足以到 10。",
        },
        "GCS 計分取最佳反應：E2 + V2 + M5 = 9。",
        "Glasgow Coma Scale；localizes pain",
        "疼痛張眼 E2，不可理解聲音 V2，撥開疼痛 M5，總分 9。",
        "GCS -> 2+2+5=9",
    ),
    update(
        78,
        "本題考 HIV 診斷後告知、法定通報與法律責任。醫師有通報主管機關義務；若病人同意，可告知同居女友；病人明知感染仍隱瞞並進行危險性行為造成感染，可能負法律責任。官方答案 C：1、3、4。",
        {
            "A": "1、2、3 包含『病人不同意仍應立即告知女友』，這會牽涉隱私與法定程序；醫師應走通報與輔導機制，而非任意對伴侶揭露。",
            "B": "1、2、4 同樣包含未經同意立即告知伴侶，且漏掉醫師法定通報主管機關義務，因此不正確。",
            "C": "1 病人同意可告知、3 法定通報、4 明知感染仍危險傳染可能有法律責任，三者符合題意，因此正確。",
            "D": "2 不符合本題保密與通報程序邏輯；雖含 3、4，仍因 2 錯而不選。",
        },
        "HIV 確診要通報主管機關；告知伴侶需依病人同意與法定程序處理，不可任意洩露隱私。",
        "HIV；法定通報；告知伴侶",
        "HIV：同意可告知伴侶，醫師須通報主管機關，故意隱瞞傳染可能有法律責任。",
        "HIV 法律倫理 -> 1、3、4",
        ["法規可能隨時間修訂；本題依 109-2 官方答案與考試邏輯撰寫，若用於現行臨床法規請再查最新規範。"],
    ),
    update(
        79,
        "本題考有決定能力成年病人的自主權。30 歲未婚男性具決定能力，已經醫師說明並同意手術；即使父母不同意或未知情，醫師也應尊重本人決定並完整記錄。官方答案 C。",
        {
            "A": "成年且具決定能力者不需要等父母同意才能接受醫療，除非法律另有特殊情況。",
            "B": "私下取得父母同意侵犯病人隱私與自主，不是合適作法。",
            "C": "尊重病人本人決定，並在病歷記錄告知內容、理解能力與同意過程，是最適當作法。",
            "D": "病人明確不願告知父母，進手術室後再通知仍違反其隱私與自主。",
        },
        "成年且有決定能力的病人，醫療決定以本人知情同意為準，父母不是必要同意人。",
        "知情同意；成年病人自主權",
        "30 歲具決定能力者可自行同意手術；醫師應尊重並記錄，不私下通知父母。",
        "成年病人自主 -> 尊重本人決定並記錄",
    ),
    update(
        80,
        "本題問醫療糾紛後補充病歷何者錯誤。病歷可以補充，但必須真實、標明補記時間與原因，不能在事後加入未曾發生的內容或讓補記看起來像原始紀錄。官方答案 A。",
        {
            "A": "醫師不能把糾紛後新增內容當作原始病歷任意補上；若未標明補記且內容可疑，法院可不採信，因此本項錯誤。",
            "B": "補充病歷應清楚標明補記日期、時間與補記者，避免被認為偽造或變造，敘述正確。",
            "C": "若補記內容不是事實，可能涉及業務文書登載不實等刑事責任，敘述正確。",
            "D": "不實或可疑補記可能造成舉證妨礙的不利益，民事上可能影響舉證責任分配，敘述正確。",
        },
        "病歷補記必須真實且標明補記時間；不可事後偽裝成原始紀錄。",
        "病歷補記；醫療糾紛；舉證妨礙",
        "醫療糾紛後可補記真實內容，但須註明日期時間；不實補記會有刑民事風險。",
        "病歷補記 -> 不能事後偽裝原始紀錄",
    ),
]


def main():
    source = json.loads(Path(SOURCE_FILE).read_text(encoding="utf-8-sig"))
    questions = source["questions"]
    if len(questions) != 80:
        raise SystemExit(f"expected 80 questions, got {len(questions)}")
    by_num = {q["question_number"]: q for q in questions}
    if sorted(by_num) != list(range(1, 81)):
        raise SystemExit("question numbers are not 1-80")
    if [u["question_number"] for u in UPDATES] != list(range(1, 81)):
        raise SystemExit("updates are not exactly 1-80")
    for item in UPDATES:
        q = by_num[item["question_number"]]
        if item["question_id"] != q["id"]:
            raise SystemExit(f"question id mismatch at Q{item['question_number']}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for start in range(1, 81, 10):
        end = start + 9
        chunk = [u for u in UPDATES if start <= u["question_number"] <= end]
        payload = {
            "source_file": SOURCE_FILE,
            "dataset_id": DATASET_ID,
            "range": {"start": start, "end": end},
            "updates": chunk,
        }
        path = OUT_DIR / f"q{start:03d}-q{end:03d}.json"
        path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(f"wrote {len(range(1, 81, 10))} update files to {OUT_DIR}")


if __name__ == "__main__":
    main()
