import json
from pathlib import Path


SOURCE_FILE = "public/data/exams/112-2/medicine-6.json"
DATASET_ID = "112-2_medicine-6"
OUT_DIR = Path("scratch/rewrite_updates/112-2_medicine-6")
STAMP = "2026-07-16T00:00:00+08:00"


def exp(stem, options, core):
    return f"【題幹解析】\n{stem}\n\n【選項詳解】\n{options}\n\n【核心考點】\n{core}"


def item(n, explanation, key_point, front, back, summary, notes=None):
    return {
        "question_id": f"{DATASET_ID}_{n:03d}",
        "question_number": n,
        "explanation": explanation,
        "key_point": key_point,
        "flashcard_front": front,
        "flashcard_back": back,
        "flashcard_summary": summary,
        "review_status": "ai_generated",
        "explanation_model": "codex-high-quality-rewrite",
        "explanation_generated_at": STAMP,
        "manual_review_notes": notes or [],
    }


UPDATES = [
    item(1, exp(
        "本題考困難面罩通氣的術前預測因子。典型風險可用 MOANS 記憶：Mask seal 困難、Obesity/Obstruction、Age、No teeth、Stiff lungs；大量鬍鬚會破壞面罩密合，是最直接的危險因子。",
        "- A. 有大量鬍鬚之男性會讓面罩邊緣漏氣，難以建立有效正壓通氣，是困難面罩通氣的重要預測因子。\n- B. 青少年通常不是困難面罩通氣的典型高風險族群；年長、肥胖、睡眠呼吸中止或顏面結構異常更常見。\n- C. BMI 小於 20 kg/m2 不屬於常見風險；肥胖或頸部軟組織增加才會增加通氣困難。\n- D. Mallampati II 只代表口咽視野輕度受限，較不如 Mallampati III/IV 或鬍鬚造成的密合不良具有預測力。",
        "困難面罩通氣要先想「面罩密合」與「上呼吸道阻塞」；鬍鬚、肥胖、無牙、年長與肺順應性差都會增加風險。"),
        "大量鬍鬚會造成面罩漏氣，是困難面罩通氣的預測因子。",
        "difficult mask ventilation 預測因子",
        "大量鬍鬚、肥胖、無牙、年長、睡眠呼吸中止或肺順應性差；本題選大量鬍鬚。",
        "困難面罩通氣 -> 鬍鬚造成面罩密合不良"),
    item(2, exp(
        "SvO2 是全身靜脈血回到右心後、經肺動脈混合後的氧飽和度，因此最準確的採血位置是肺動脈。中心靜脈氧飽和度 ScvO2 可作替代趨勢，但不等同於真正混合靜脈血。",
        "- A. 外頸靜脈只反映局部頭頸部靜脈血，不能代表全身混合靜脈血。\n- B. 橈動脈導管抽到的是動脈血，可測 SaO2 或 PaO2，不是 SvO2。\n- C. 中央靜脈導管多位於上腔靜脈或右心房附近，測得的是 ScvO2，仍未完全混合下半身與冠狀竇回流。\n- D. 肺動脈導管位於肺動脈，血液已在右心充分混合，最能測得 mixed venous oxygen saturation。",
        "SvO2 要由肺動脈導管測量；中心靜脈導管測的是 ScvO2，兩者臨床趨勢相關但位置與意義不同。"),
        "混合靜脈氧飽和度 SvO2 應由肺動脈導管抽血。",
        "SvO2 採血位置",
        "肺動脈導管；中央靜脈導管是 ScvO2。",
        "SvO2 -> pulmonary artery catheter"),
    item(3, exp(
        "題目問麻醉中呼吸監測何者錯誤。氧合與換氣都要監測；pulse oximetry 看氧合，capnography 看換氣與氣管內管位置。EtCO2 與 PaCO2 的差距會受死腔、肺栓塞、低心輸出、肺部疾病影響，不是固定值。",
        "- A. 呼吸監測確實包含 oxygenation 與 ventilation，兩者代表不同生理層面。\n- B. Pulse oximetry 是麻醉基礎監測的必要項目，用於連續追蹤血氧飽和度。\n- C. Capnography 可監測 ventilation，持續有二氧化碳波形也能協助確認氣管內管在氣管內。\n- D. EtCO2 與 PaCO2 的差距不是固定不變，尤其通氣灌流不均或死腔增加時會改變，所以不能說完全反映 PaCO2。",
        "EtCO2 是 PaCO2 的趨勢指標，不是固定差距的完全替代品；氧合與換氣要分開監測。"),
        "EtCO2-PaCO2 差距會隨死腔與循環狀態改變。",
        "麻醉呼吸監測錯誤敘述",
        "錯在 EtCO2 與 PaCO2 差距固定且可完全反映 PaCO2。",
        "麻醉監測 -> EtCO2 可看趨勢但不等於 PaCO2"),
    item(4, exp(
        "本題考局部麻醉劑分類與代謝。Ester 類主要由血漿 pseudocholinesterase 代謝；amide 類主要在肝臟代謝，因此 A 把 amide 與 ester 的代謝方式混淆。",
        "- A. amide 類如 lidocaine、bupivacaine 主要經肝臟代謝，不是主要靠血中偽膽鹼酯酶，故為錯誤敘述。\n- B. 注射部位血管越豐富，systemic absorption 越快、血中濃度越高，這是正確觀念。\n- C. 非離子化型較能穿過神經膜，比例受 pKa 與組織 pH 影響，會影響 onset。\n- D. Bupivacaine 誤入血管可造成嚴重心律不整與心血管毒性，需警覺 LAST。",
        "Ester 類局麻藥靠 pseudocholinesterase；amide 類靠肝臟代謝。Bupivacaine 血管內注射心臟毒性特別重要。"),
        "Amide 類局部麻醉劑主要肝臟代謝，不是 pseudocholinesterase。",
        "局部麻醉劑代謝",
        "ester -> pseudocholinesterase；amide -> liver。",
        "local anesthetics -> amide 肝代謝"),
    item(5, exp(
        "題目問 opioids 何者錯誤。長期 opioid 使用可出現耐受、依賴與 opioid-induced hyperalgesia，也就是痛覺敏感增加，不是痛覺減退。",
        "- A. Morphine 代謝物可在肝腎功能不佳時累積，造成鎮靜、昏迷與呼吸抑制，臨床需減量或換藥。\n- B. 快速給予大劑量 opioid，尤其 fentanyl 類，可造成胸壁僵硬而影響通氣。\n- C. 長期使用 opioids 可能造成 hyperalgesia 或 tolerance，不是 hypoalgesia，因此此敘述錯誤。\n- D. 大劑量 opioid 可抑制手術壓力反應，減少 catecholamine 上升，常見於心臟麻醉概念。",
        "長期 opioid 不是單純越用越不痛；可出現耐受與 opioid-induced hyperalgesia。"),
        "長期 opioid 可造成痛覺過敏 hyperalgesia，而非 hypoalgesia。",
        "opioid 長期使用",
        "可能出現 tolerance、dependence、opioid-induced hyperalgesia。",
        "opioids -> 長期使用可能痛覺過敏"),
    item(6, exp(
        "孕婦接受非產科手術時，要維持母體氧合、正常二氧化碳與子宮胎盤灌流。Permissive hypercapnia 可能造成胎兒酸中毒或影響 uteroplacental perfusion，不是常規原則。",
        "- A. 孕婦麻醉應避免明顯高碳酸血症，維持接近正常 PaCO2；permissive hypercapnia 不適合作為常規處置，故為錯誤敘述。\n- B. 氣腹壓力過高會降低靜脈回流與子宮胎盤灌流，腹腔鏡時應盡量使用較低且足夠的壓力。\n- C. 過度頭低或頭高都可能影響呼吸力學與血流動力學，孕婦應避免極端姿勢。\n- D. 25 週已有胎兒存活可能性，術中或術前術後胎心監測應與產科團隊討論並執行可行方案。",
        "孕婦非產科手術重點是母體氧合、正常換氣、避免低血壓與過高氣腹壓；不要把 ARDS 的 permissive hypercapnia 直接套用。"),
        "孕婦腹腔鏡麻醉不宜採 permissive hypercapnia。",
        "孕婦非產科手術麻醉",
        "維持氧合、接近正常 CO2、低氣腹壓、避免極端姿勢並考慮胎心監測。",
        "pregnancy anesthesia -> avoid permissive hypercapnia"),
    item(7, exp(
        "題目問 labor epidural analgesia 何者錯誤。現代觀念不要求等子宮頸開 3 cm 才能施打；產婦有需求且無禁忌時可給予，早期施打不會因此必然增加剖腹產率。",
        "- A. 第一產程疼痛主要來自子宮收縮與子宮頸擴張，傳入約 T10-L1，敘述正確。\n- B. 必須等到子宮頸口 3 cm 以上才可施打是過時觀念；不應因開指未達 3 cm 而延遲有效止痛，故為錯誤。\n- C. Epidural 持續到第二產程可能與第二產程延長、器械助產增加有關，需調整濃度與劑量。\n- D. Test dose 可協助偵測誤入血管或蜘蛛膜下腔，避免高位脊髓麻醉或局麻藥毒性。",
        "產痛硬脊膜外止痛不需等到 3 cm；第一產程 T10-L1，第二產程加上 S2-S4。"),
        "Labor epidural 可依產婦需求施打，不必等子宮頸開 3 cm。",
        "產痛 epidural 時機",
        "無禁忌且產婦需要即可施打；3 cm 才能打是錯誤限制。",
        "labor epidural -> 不需等 3 cm"),
    item(8, exp(
        "癌症慢性疼痛需使用可長期、穩定、可調整的 opioid。Meperidine 代謝物 normeperidine 會累積造成神經毒性與癲癇風險，不適合長期使用，尤其不建議以靜脈 meperidine 作長期癌痛控制。",
        "- A. Transdermal fentanyl 可用於穩定慢性癌痛，尤其已使用 opioid 且需要長效控制者。\n- B. Oral morphine 是癌症疼痛長期控制的典型選項，可用速效與長效劑型調整。\n- C. Intravenous meperidine 不適合長期癌痛用藥，因作用短、代謝物神經毒性及累積風險高。\n- D. Oral oxycodone 可作癌痛長期治療選項之一，依疼痛程度與副作用調整。",
        "Meperidine 不適合慢性癌痛長期使用；癌痛常用 oral morphine、oxycodone 或 transdermal fentanyl。"),
        "癌痛長期用藥避免 meperidine，尤其 IV meperidine。",
        "癌症疼痛長期 opioid",
        "常用 morphine、oxycodone、fentanyl patch；避免 meperidine。",
        "cancer pain -> meperidine not for long-term"),
    item(9, exp(
        "Berlin definition 的 ARDS 包含：一週內發生、雙側肺部浸潤、非心衰或輸液過多完全解釋、且在 PEEP/CPAP >=5 下依 PaO2/FiO2 分輕中重度。",
        "- A. 一週內出現已知臨床事件或新的/惡化呼吸症狀，是 Berlin definition 的時間條件。\n- B. PaO2/FiO2 <=300 是 ARDS 氧合條件，但重度是 <=100；<=300 包含輕度到重度。\n- C. ARDS 不能由左心衰竭或液體過多完全解釋；初期常合併左心室衰竭不是診斷條件。\n- D. 影像應為雙側混濁陰影，不能用單側左肺浸潤作為典型描述。",
        "ARDS Berlin definition：一週內、雙側浸潤、非心衰完全解釋、PaO2/FiO2 <=300 且需 PEEP/CPAP 條件。"),
        "ARDS Berlin 定義的時間條件是一週內發生或惡化。",
        "ARDS Berlin definition",
        "一週內、雙側浸潤、非心因性為主、PaO2/FiO2 分級。",
        "ARDS -> Berlin definition timing within 1 week"),
    item(10, exp(
        "OCT 主要提供黃斑部與視網膜/脈絡膜的橫切面結構，適合看高度近視的黃斑裂孔、脈絡膜新生血管相關變化、後葡萄腫造成的黃斑牽引等。格子狀退化位於周邊視網膜，主要靠散瞳眼底檢查，不是 OCT 的主要用途。",
        "- A. 黃斑裂孔位於黃斑中心，OCT 可直接看全層或部分厚度裂孔，是主要檢查。\n- B. 格子狀退化多在周邊視網膜，OCT 臨床上不是主要檢查工具，因此為除外。\n- C. 脈絡膜新生血管會影響黃斑結構，OCT/OCT-A 可協助評估積液與病灶。\n- D. 高度近視後葡萄腫可伴隨黃斑牽引或劈裂，OCT 有助於評估後極部病變。",
        "OCT 強在黃斑與後極部橫切面；周邊 lattice degeneration 主要靠散瞳眼底檢查。"),
        "OCT 不是格子狀退化的主要檢查。",
        "高度近視 OCT 除外",
        "黃斑裂孔、CNV、後極部病變適合 OCT；lattice degeneration 多靠周邊眼底檢查。",
        "OCT -> macula/posterior pole, not peripheral lattice"),
    item(11, exp(
        "Behçet disease 是全身性血管炎，可造成復發性口腔潰瘍、生殖器潰瘍、皮膚與眼部病變。HLA-B51 是相關風險因子，不是診斷必備條件；也不能把雙眼葡萄膜炎加 HLA-B51 當成診斷標準。",
        "- A. HLA-B51 陽性可支持風險但非診斷標準，且 Behçet 診斷需整合口腔、生殖器、皮膚、眼部等臨床表現，因此此敘述錯誤。\n- B. 口腔潰瘍、生殖器潰瘍與血管病灶都是 Behçet 常見全身表現。\n- C. Behçet 血管炎可影響動脈與靜脈，眼底螢光血管攝影可評估視網膜血管炎與滲漏。\n- D. 治療可依嚴重度使用類固醇、免疫調節劑或抗 TNF 等生物製劑。",
        "Behçet 是臨床診斷的全身性血管炎；HLA-B51 是關聯因子，不是必要診斷標準。"),
        "Behçet disease 不以 HLA-B51 陽性作為必要診斷條件。",
        "Behçet 葡萄膜炎",
        "臨床診斷重點是復發口腔潰瘍、眼病變、生殖器潰瘍、皮膚/血管病變；HLA-B51 非必備。",
        "Behçet -> HLA-B51 not diagnostic criterion"),
    item(12, exp(
        "中年男性、角膜基質晶狀沉積與 arcus，典型指向 Schnyder corneal dystrophy 或脂質沉積相關角膜病變，常與血中膽固醇或脂質異常有關。",
        "- A. 膽固醇升高可造成角膜脂質沉積、arcus 或晶狀沉積，是本題最可能答案。\n- B. 鈣離子沉積較典型是 band keratopathy，呈帶狀角膜鈣化，不是本題晶狀脂質沉積的主要線索。\n- C. 銅離子沉積典型是 Wilson disease 的 Kayser-Fleischer ring，位置與臨床意義不同。\n- D. 同半胱胺酸升高與晶狀體脫位、血栓風險相關，非典型角膜晶狀沉積原因。",
        "角膜 arcus 合併晶狀脂質沉積要想到 cholesterol/lipid abnormality；銅是 Kayser-Fleischer ring。"),
        "角膜晶狀沉積與 arcus 最要懷疑膽固醇升高。",
        "角膜脂質沉積",
        "Schnyder/脂質沉積 -> cholesterol；Wilson -> copper ring。",
        "corneal crystal + arcus -> cholesterol"),
    item(13, exp(
        "本題官方為全給分，作答時仍可掌握考點：角膜內皮細胞主要靠增大與移行代償，真正再生能力有限；若受損過多會導致角膜水腫，嚴重時需角膜移植。",
        "- A. 一般教學認為角膜內皮細胞再生能力很差，主要靠鄰近細胞擴大與移行補位；若題目說具有適度再生能力，容易被視為錯誤，但本題官方全給分，需保留異常計分狀態。\n- B. 內皮的 barrier 與 pump 功能維持角膜相對脫水與透明，含水量約 78%，是正確核心。\n- C. 外傷或手術若造成內皮細胞密度不足，pump failure 會造成不可逆角膜水腫。\n- D. 不可逆角膜水腫造成視力下降時，可考慮內皮角膜移植或穿透性角膜移植等治療。",
        "角膜內皮細胞再生能力有限；功能是 barrier/pump，失代償會角膜水腫。本題官方 all_credit，勿擅改答案。"),
        "角膜內皮再生能力有限，官方全給分需保留。",
        "角膜內皮 all_credit",
        "內皮靠 pump 維持透明；再生差，受損過多會水腫。",
        "corneal endothelium -> limited regeneration, all_credit",
        ["官方 answer_status 為 all_credit；題解保留全給分，不改答案。"]),
    item(14, exp(
        "本題問較不會合併白內障的全身病。糖尿病、myotonic dystrophy、異位性皮膚炎都可增加白內障風險；Graves disease 主要造成甲狀腺眼病變，如眼球突出、眼外肌肥厚與複視，白內障不是典型合併症。",
        "- A. 糖尿病會增加白內障風險，且可較早發生。\n- B. 強直性肌肉失養症常合併特徵性白內障，是經典關聯。\n- C. 異位性皮膚炎可合併 anterior/posterior subcapsular cataract，也可能與搔抓外傷或類固醇使用相關。\n- D. Graves disease 典型眼部問題是 thyroid eye disease，不是白內障，因此最不會合併白內障。",
        "白內障全身關聯：DM、myotonic dystrophy、atopic dermatitis；Graves 主要是甲狀腺眼病變。"),
        "Graves disease 較不會典型合併白內障。",
        "白內障全身病除外",
        "DM、myotonic dystrophy、atopic dermatitis 會；Graves 較不是。",
        "cataract association -> Graves is exception"),
    item(15, exp(
        "三歲以下兒童雙眼視網膜出血、沒有明顯頭部外傷，要高度懷疑 abusive head trauma/shaken baby syndrome。眼底常見多層、多區域視網膜出血。",
        "- A. 第一型糖尿病兒童可有糖尿病視網膜病變，但三歲以下初診且雙眼大量出血不是典型。\n- B. 嬰兒搖晃症可因加減速與顱內壓變化造成雙眼視網膜出血，是本題最重要診斷。\n- C. 頑固型癲癇本身不會典型造成雙眼視網膜出血。\n- D. JIA 相關葡萄膜炎多為慢性前葡萄膜炎，重點是發炎與併發症，不是無外傷雙眼視網膜出血。",
        "幼兒無明顯外傷卻有雙眼視網膜出血，要想到 shaken baby syndrome/abusive head trauma。"),
        "三歲以下雙眼視網膜出血要懷疑嬰兒搖晃症。",
        "幼兒雙眼視網膜出血",
        "無明顯外傷時優先警覺 shaken baby syndrome。",
        "retinal hemorrhage in infant -> shaken baby syndrome"),
    item(16, exp(
        "弱視來自視覺發育期影像品質差、兩眼影像不等或斜視造成抑制。間歇性交替性外斜視因兩眼可交替使用，較不易造成單眼長期抑制；單眼白內障與高度屈光參差風險更高。",
        "- A. 間歇性交替性外斜視通常兩眼輪流注視，單眼被長期抑制的機會較小，因此造成弱視可能性較小。\n- B. 單眼先天性白內障會造成嚴重 deprivation amblyopia，風險很高。\n- C. 兩眼視差五百度屬高度 anisometropia，容易造成屈光參差性弱視。\n- D. 兩眼遠視四百度可能造成雙眼影像模糊，形成屈光性弱視。",
        "交替性斜視比單眼固定斜視較不易弱視；單眼白內障與高度屈光參差是高風險。"),
        "間歇性交替性外斜視造成弱視的可能性較小。",
        "兒童弱視風險",
        "單眼白內障、屈光參差、高度遠視風險高；交替外斜視較低。",
        "amblyopia -> alternating intermittent exotropia lower risk"),
    item(17, exp(
        "類固醇眼部副作用包括 posterior subcapsular cataract、眼壓升高/青光眼，以及可能誘發或加重 central serous chorioretinopathy。視神經炎不是典型類固醇副作用。",
        "- A. 1、2、4 包含視神經炎；視神經炎不是類固醇常見眼副作用，因此不完整。\n- B. 2、3、4 同樣包含視神經炎且漏掉白內障，不正確。\n- C. 1、3、4 包含視神經炎且漏掉眼壓升高，不正確。\n- D. 1 白內障、2 眼壓升高、3 中心性漿液性脈絡膜視網膜病變皆可與類固醇相關，是正確組合。",
        "類固醇眼副作用：白內障、眼壓升高/青光眼、central serous chorioretinopathy；不是視神經炎。"),
        "類固醇眼部副作用為白內障、眼壓升高、CSCR。",
        "steroid eye side effects",
        "cataract + IOP elevation + CSCR；不包括 optic neuritis。",
        "steroid -> cataract, glaucoma, CSCR"),
    item(18, exp(
        "Graves ophthalmopathy 造成複視主要因眼外肌發炎纖維化與肥厚，最常侵犯下直肌。影像典型是肌腹肥厚但肌腱相對 spared；若肌腹和肌腱都肥大，較不像典型甲狀腺眼病變。",
        "- A. 眼外肌肥厚與纖維化會限制眼球運動，導致複視，敘述正確。\n- B. 下直肌最常受侵犯，常造成上轉受限與垂直複視。\n- C. 典型 CT 是 extraocular muscle belly enlargement with tendon sparing，不是肌腹與肌腱都肥大，故為錯誤。\n- D. 斜視手術應等甲狀腺狀態與眼位穩定，通常至少數月，避免活動期變化造成復發或過矯。",
        "甲狀腺眼病變影像：眼外肌肌腹肥厚、肌腱相對保留；最常下直肌。"),
        "Graves 眼病變 CT 典型為肌腹肥厚、肌腱保留。",
        "Graves diplopia CT",
        "inferior rectus common；tendon sparing 是關鍵。",
        "thyroid eye disease -> belly enlarged, tendon spared"),
    item(19, exp(
        "聽神經瘤常造成單側感音神經性聽損、耳鳴、語音辨識度下降，ABR 可見第 V 波潛時延長或 I-V interval 延長。患側語音辨識度通常不會和健側相同。",
        "- A. 純音聽力檢查患側聽力變差符合 vestibular schwannoma 常見表現。\n- B. 單側耳鳴很常見，是臨床警訊之一。\n- C. 患側語音辨識度常比健側差，若說相同最不適當。\n- D. ABR 第五波潛時延長可反映聽神經傳導受影響，是可見檢查結果。",
        "聽神經瘤：單側 SNHL、耳鳴、speech discrimination 下降、ABR V wave latency 延長。"),
        "聽神經瘤患側語音辨識度通常下降。",
        "聽神經瘤聽力檢查",
        "患側聽力與語音辨識較差，ABR V 波延長。",
        "acoustic neuroma -> poor speech discrimination"),
    item(20, exp(
        "眩暈合併聽力症狀時要想到內耳病變。Meniere disease 典型為反覆眩暈、波動性低頻聽損、耳鳴與耳悶；BPPV、前庭神經炎與前庭性偏頭痛通常不以聽損為主要特徵。",
        "- A. BPPV 是短暫姿勢誘發眩暈，通常沒有聽力損失。\n- B. 前庭神經炎主要侵犯前庭神經，若合併聽損則較像 labyrinthitis，不是典型 vestibular neuritis。\n- C. Meniere disease 最常合併聽力損失，且常為波動性低頻感音神經性聽損。\n- D. 前庭性偏頭痛可有聲光敏感與眩暈，但固定聽力損失不是主要特徵。",
        "反覆眩暈加波動性聽損、耳鳴、耳悶是 Meniere disease 的經典組合。"),
        "最常合併聽力損失的眩暈疾病是 Meniere disease。",
        "眩暈合併聽損",
        "Meniere disease = episodic vertigo + fluctuating hearing loss + tinnitus/aural fullness。",
        "vertigo + hearing loss -> Meniere"),
    item(21, exp(
        "本題官方為全給分。鼻竇發育的常考概念是：上頜竇與篩竇出生時即已存在，額竇與蝶竇較晚氣化並在兒童期到青春期逐步發育；不同教材對「開始氣化」與「完成發育」表述容易造成爭議。",
        "- A. 額竇通常不是最早開始氣化的鼻竇；上頜竇、篩竇較早可見。因此若單純問最早，A 可能有爭議。\n- B. 篩竇小室出生後仍會發育與氣化，不能說數量不再增加。\n- C. 上頜竇出生時已存在，兒童期逐步變大，青春期也會再明顯增長；視教材語意可能部分可接受。\n- D. 蝶竇發育較晚，但是否同時是最晚開始且最晚完成，需看題目定義；本題官方全給分，應保留異常計分狀態。",
        "鼻竇發育題要分清楚出生即存在、開始氣化與完成發育；本題官方 all_credit，不宜改成單一答案。"),
        "鼻竇發育題官方全給分，題解保留爭議。",
        "鼻竇發育 all_credit",
        "上頜竇/篩竇較早；額竇/蝶竇較晚；本題全給分。",
        "sinus development -> all_credit",
        ["官方 answer_status 為 all_credit；不同教材對鼻竇氣化時序表述可能造成爭議。"]),
    item(22, exp(
        "過敏性鼻炎常見 allergic shiners、Dennie-Morgan lines、allergic salute 造成鼻尖上橫紋、蒼白水腫鼻黏膜與清水鼻涕。本題問理學檢查正確現象。",
        "- A. 常見是下眼瞼暗沉或 allergic shiners，不是顏色反白。\n- B. 鼻尖上橫紋 transverse supratip nasal crease 來自反覆用手上推鼻子，是典型過敏性鼻炎體徵。\n- C. 過敏性鼻炎不會造成縮短的眼睫毛，這不是典型體徵。\n- D. Dennie-Morgan folds 是下眼瞼皺褶，不是上眼瞼皺褶。",
        "過敏性鼻炎體徵：allergic shiners、Dennie-Morgan lower lid folds、transverse nasal crease。"),
        "鼻尖上橫紋是過敏性鼻炎的典型理學檢查發現。",
        "過敏性鼻炎體徵",
        "allergic salute -> transverse supratip nasal crease。",
        "allergic rhinitis -> nasal crease"),
    item(23, exp(
        "題目問軟式與硬式喉內視鏡何者錯誤，官方狀態為 multiple_correct，代表可能接受不只一個錯誤敘述。判斷重點是檢查方式、麻醉需求、診斷與治療用途，以及影像解析度。",
        "- A. 軟式喉內視鏡經鼻或口觀察喉部，通常歸類為間接喉鏡；硬式內視鏡若指門診 rigid laryngoscopy，也常仍是間接觀察，不等於全身麻醉下直接喉鏡，因此此敘述有爭議。\n- B. 若把硬式喉鏡解讀為手術用直接喉鏡，常需全麻；但門診硬式喉內視鏡也可局麻進行，所以此敘述也可能過度絕對。\n- C. 軟式喉內視鏡不僅能診斷，也可做部分處置或導引；說僅能局限於診斷用途過度狹窄。\n- D. 現代軟式與硬式內視鏡皆可提供高解析影像，這個敘述較合理。",
        "喉內視鏡題要辨認 rigid 門診檢查與 direct laryngoscopy 手術語境；官方 multiple_correct 時需保留可爭議選項。"),
        "軟式喉內視鏡不只限於診斷；硬式是否需全麻要看語境。",
        "喉內視鏡 multiple_correct",
        "A/C 都有錯誤或爭議；D 較正確。",
        "laryngoscopy -> flexible diagnostic/therapeutic nuance",
        ["官方 answer_status 為 multiple_correct；題目對硬式喉鏡語境可能有歧義，保留人工複核。"]),
    item(24, exp(
        "氣管切開術相較長期經喉插管，可降低氣道阻力與死腔、增加病人舒適度、利於口腔照護與分泌物清除，也可減少喉部傷害。本題問不是優點。",
        "- A. 氣管切開通常減少上呼吸道無效腔，不是增加 dead space，因此不是優點。\n- B. 在適當病人可利於呼吸器脫離與照護，可能縮短 ICU 或住院時程。\n- C. 避免長期管路通過聲門，可降低聲帶、聲門下與氣管局部傷害。\n- D. 氣切可使用較短且相對較大管徑的管路，減少阻力並利於抽痰。",
        "氣管切開優點包括減少 dead space/阻力、利於照護與降低喉部傷害；增加 dead space 不是優點。"),
        "氣切不是增加 dead space，而是減少上呼吸道無效腔。",
        "氣管切開優點除外",
        "減少 dead space、降低喉部傷害、利於抽痰；A 錯。",
        "tracheostomy -> decreases dead space"),
    item(25, exp(
        "上喉神經外支支配 cricothyroid muscle。該肌負責拉長、拉緊聲帶以產生高音；甲狀腺手術傷到此神經會造成高音困難、聲音疲乏。",
        "- A. Vocalis muscle 主要由 recurrent laryngeal nerve 支配，不是上喉神經外支主要支配。\n- B. Cricothyroid muscle 由 external branch of superior laryngeal nerve 支配，因此受影響最大。\n- C. Posterior cricoarytenoid 是唯一主要外展聲帶的肌肉，由 recurrent laryngeal nerve 支配。\n- D. Lateral cricoarytenoid 內收聲帶，也由 recurrent laryngeal nerve 支配。",
        "External branch of superior laryngeal nerve 支配 cricothyroid；其他多數喉內肌由 recurrent laryngeal nerve 支配。"),
        "上喉神經外支傷害主要影響 cricothyroid muscle。",
        "上喉神經外支",
        "external superior laryngeal nerve -> cricothyroid -> high pitch。",
        "EBSLN injury -> cricothyroid"),
    item(26, exp(
        "口腔癌術後輔助治療中，positive margin 與 extranodal extension 是最明確需要 postoperative chemoradiotherapy 的高危險因子。T3/T4、PNI、LVI 常支持術後放射治療，但不一定都需同步化療。",
        "- A. 陽性切緣代表仍可能有殘餘腫瘤，是術後同步化學放射治療的典型高危險因子。\n- B. T3/T4 是高復發風險，常需術後放療評估，但單獨存在時不如 positive margin 明確指向同步化放療。\n- C. 神經侵犯是中高風險因子，常考慮術後放療，但不是最典型的同步化療指標。\n- D. 淋巴血管侵犯增加復發與轉移風險，常支持放療，但同步化療通常看 positive margin 或 extranodal extension。",
        "頭頸癌術後 concurrent chemoradiotherapy 最強指標：positive margin、extranodal extension。"),
        "口腔癌術後陽性切緣建議同步化學放射治療。",
        "口腔癌術後 CCRT",
        "positive margin/ENE -> CCRT；PNI/LVI/T3-4 多偏 adjuvant RT 風險因子。",
        "oral cancer postop -> positive margin CCRT"),
    item(27, exp(
        "唾液腺良性腫瘤中 pleomorphic adenoma 最常見，但治療不能只做 enucleation，因易復發且有惡性轉化風險；Warthin tumor 與抽菸男性相關，別名 papillary cystadenoma lymphomatosum。",
        "- A. Pleomorphic adenoma 最常見沒錯，但主要治療通常是腮腺淺葉切除或適當切除，不是單純 enucleation，因此整句錯。\n- B. Pleomorphic adenoma 有惡性轉化風險，年輕成人通常不以長期觀察為首選。\n- C. Warthin tumor 常見於抽菸男性，但治療不以單純 enucleation 為典型主軸，需依位置與症狀處理。\n- D. Warthin tumor 又稱 papillary cystadenoma lymphomatosum，這是正確配對。",
        "Pleomorphic adenoma 常見但不可單純剜除；Warthin tumor 與抽菸男性相關，別名 papillary cystadenoma lymphomatosum。"),
        "Warthin tumor 又稱 papillary cystadenoma lymphomatosum。",
        "唾液腺良性腫瘤",
        "pleomorphic adenoma 最常見但非 enucleation；Warthin = papillary cystadenoma lymphomatosum。",
        "Warthin tumor -> papillary cystadenoma lymphomatosum"),
    item(28, exp(
        "第一孕期藥物流產常用 mifepristone 加 misoprostol；misoprostol 單用也可作為方案。Methotrexate 加 misoprostol可用於某些早期妊娠終止或異位妊娠情境，但 mifepristone 加 methotrexate 不是實務建議組合。",
        "- A. Misoprostol alone 可用，但效果通常低於 mifepristone 合併 misoprostol。\n- B. Mifepristone and misoprostol 是第一孕期藥物流產的標準有效組合。\n- C. Methotrexate and misoprostol 曾用於早期妊娠終止或特定情境，並非本題最不建議組合。\n- D. Mifepristone and methotrexate 機轉組合不符合常用實務，缺少促進子宮收縮排出的 prostaglandin，因此不建議。",
        "藥物流產標準組合是 mifepristone + misoprostol；不是 mifepristone + methotrexate。"),
        "第一孕期終止妊娠不建議 mifepristone + methotrexate。",
        "第一孕期藥物流產",
        "標準：mifepristone + misoprostol；避免 mifepristone + methotrexate。",
        "medical abortion -> mifepristone + misoprostol"),
    item(29, exp(
        "生命徵象穩定且未大量出血的子宮頸懷孕，首要目標是保留子宮並避免大出血。Methotrexate 是常用保守治療的一線選項；手術或栓塞多留給出血、治療失敗或特殊情況。",
        "- A. Methotrexate 注射可抑制滋養層，適合穩定、早期、希望保留生育功能者，是優先考慮。\n- B. 子宮切除是最後手段，通常用於無法控制的大出血或保守治療失敗。\n- C. Cerclage followed by D&C 可能導致嚴重出血，不是穩定病人的多數優先處理。\n- D. 子宮動脈栓塞可作輔助或出血控制，但不是題目描述穩定無症狀時的第一優先。",
        "穩定子宮頸懷孕優先保守治療，常用 methotrexate；大出血才考慮侵入處置。"),
        "穩定 cervical pregnancy 優先 methotrexate。",
        "子宮頸懷孕處置",
        "stable -> MTX；unstable/bleeding -> embolization/surgery as needed。",
        "cervical pregnancy -> methotrexate first"),
    item(30, exp(
        "早期妊娠蛻膜中最豐富的免疫細胞是 uterine natural killer cells。它們參與滋養層侵襲、血管生成與螺旋動脈重塑，是母胎介面免疫調節的核心。",
        "- A. 巨噬細胞存在於蛻膜並參與免疫調節，但數量通常少於 uterine NK cells。\n- B. 嗜中性球不是早期蛻膜中最多的免疫細胞。\n- C. 樹突細胞參與抗原呈現與免疫調節，但不是最多族群。\n- D. 自然殺手細胞，特別是 uterine NK cells，是早期蛻膜最主要免疫細胞，與螺旋動脈重塑密切相關。",
        "早期 decidua 最多免疫細胞是 uterine NK cell，功能是調控 trophoblast invasion 與 spiral artery remodeling。"),
        "早期蛻膜中最多的是自然殺手細胞。",
        "decidua immune cells",
        "uterine NK cells predominate; regulate trophoblast invasion and spiral artery remodeling。",
        "decidua -> uterine NK cell"),
    item(31, exp(
        "會陰裂傷分級：第 1 度皮膚/陰道黏膜；第 2 度會陰肌肉但未傷肛門括約肌；第 3 度傷肛門括約肌，3a 是 external anal sphincter 小於 50% 厚度撕裂；第 4 度延伸至 anorectal mucosa。",
        "- A. 第 1 度只傷及 vaginal epithelium 或 perineal skin，正確。\n- B. 第 2 度傷及 perineal muscles，但 anal sphincter complex 完整，正確。\n- C. 3a 不是小於 1/3，而是小於 50% external anal sphincter thickness，故此敘述錯誤。\n- D. 第 4 度包括 anal sphincter complex 並延伸到 anorectal mucosa，描述正確。",
        "OASIS 分級：3a 是 EAS 厚度小於 50%，不是小於 1/3。"),
        "第 3a 度會陰裂傷為 EAS 小於 50% 撕裂。",
        "會陰裂傷分級",
        "1皮膚黏膜、2會陰肌、3括約肌、4直腸黏膜；3a <50% EAS。",
        "perineal tear -> 3a <50% EAS"),
    item(32, exp(
        "剖腹產相較自然產常見風險包括出血、感染、血栓、麻醉與手術相關傷害；但骨盆底肌肉受損較常與陰道生產、產鉗或難產相關。題目問剖腹產潛在合併症何者錯誤。",
        "- A. 剖腹產為手術，平均出血量通常較自然產多，正確。\n- B. 手術、產褥期與活動減少會增加靜脈血栓風險，正確。\n- C. 有糖尿病或血栓風險者需考慮胰島素或抗凝血劑銜接，正確。\n- D. 骨盆底肌肉受損機會較高是陰道生產較典型，剖腹產相對有保護效果，因此此敘述錯誤。",
        "剖腹產增加手術出血、感染與血栓風險；骨盆底受損較偏陰道生產風險。"),
        "剖腹產不會比自然產更容易造成骨盆底肌肉受損。",
        "剖腹產合併症除外",
        "C/S: bleeding, VTE, surgical risks; pelvic floor injury more vaginal delivery。",
        "cesarean complications -> pelvic floor injury less typical"),
    item(33, exp(
        "產褥熱是產後發燒的臨床問題，產後第一天發燒常見原因可為脫水、肺不張、藥物、脹奶等；骨盆腔感染通常較常在產後 2-3 天後出現，不能說自然產產後第一天超過一半是骨盆腔細菌感染。",
        "- A. 產褥熱一般以產後體溫超過 38 度作為重要門檻，敘述可接受。\n- B. 自然產產後第一天發燒超過一半為骨盆腔細菌感染此說法過度，故為錯誤。\n- C. 高燒、spiking fever、病程快速惡化時需警覺 A 型鏈球菌等嚴重感染。\n- D. 脹奶可造成產後發燒，是產褥熱鑑別之一。",
        "產後第一天發燒不等於多數骨盆腔感染；產褥感染常在產後數日較典型。"),
        "自然產產後第一天發燒不應直接認定多數為骨盆腔感染。",
        "產褥熱錯誤敘述",
        "postpartum day 1 fever often non-pelvic; pelvic infection later more likely。",
        "puerperal fever -> day 1 not mostly pelvic infection"),
    item(34, exp(
        "SMA 是常染色體隱性運動神經元疾病，大多與 5q13.2 的 SMN1 基因缺失或突變相關。新生兒篩檢與帶因篩檢日益重要，並非只有孕婦有症狀才檢驗。",
        "- A. 多數 SMA 由染色體 5q13.2 上 SMN1 基因異常造成，正確。\n- B. SMA 不代表多數胎兒第三孕期胎死腹中；臨床嚴重度從嬰兒期重症到成人型不等。\n- C. 即使發生率不高，帶因篩檢與新生兒篩檢有其價值，不是等孕婦肌無力才檢驗。\n- D. SMA 不是以胎兒股骨過短作為典型超音波特徵。",
        "SMA 經典基因位置是 5q13.2 SMN1；不是以孕婦症狀或胎兒短股骨診斷。"),
        "SMA 多由 5q13.2 的 SMN1 基因突變或缺失造成。",
        "SMA 遺傳",
        "autosomal recessive, SMN1 on 5q13.2。",
        "SMA -> SMN1 5q13.2"),
    item(35, exp(
        "剖腹產預防性抗生素通常術前單次給藥。若盤尼西林/頭孢嚴重過敏，可用 clindamycin 加 aminoglycoside 作替代。本題產婦體重未達需高劑量 cefazolin 的情況且有過敏史。",
        "- A. Cefazolin 是常用第一線，但盤尼西林過敏尤其若擔心立即型過敏時不選，且 1.5 mg 劑量也不合理。\n- B. Gentamycin 單用缺乏足夠厭氧與革蘭陽性覆蓋，不適合作剖腹產預防單方。\n- C. Clindamycin 合併 gentamycin 可覆蓋革蘭陽性、厭氧與部分革蘭陰性菌，是過敏病人的合適替代方案。\n- D. Ceftriaxone 每 12 小時不是剖腹產術前預防感染的標準單次預防策略。",
        "剖腹產預防抗生素：cefazolin 為常用；嚴重 beta-lactam 過敏可用 clindamycin + gentamicin。"),
        "盤尼西林過敏剖腹產預防感染可用 clindamycin + gentamycin。",
        "剖腹產預防抗生素",
        "beta-lactam allergy -> clindamycin plus gentamicin。",
        "C/S prophylaxis allergy -> clindamycin + gentamicin"),
    item(36, exp(
        "題目問並非哺乳禁忌。HCV 感染通常不是哺乳禁忌，除非乳頭破裂出血需暫停該側或依情況處理；化療、HIV、未治療開放性肺結核則需避免或暫停直接哺乳。",
        "- A. 產婦正在接受化學治療時，藥物可能經乳汁影響嬰兒，是哺乳禁忌或需停止。\n- B. C 型肝炎感染本身不是哺乳禁忌，病毒不主要透過乳汁傳播，因此為答案。\n- C. HIV 感染在可取得安全替代餵食的環境通常不建議哺乳，以避免垂直傳播。\n- D. 未治療開放性肺結核有傳染風險，治療前不宜直接哺乳接觸嬰兒。",
        "HCV 不是一般哺乳禁忌；HIV、化療、未治療開放性 TB 則需避免或暫停。"),
        "C 型肝炎感染不是產後哺乳禁忌。",
        "哺乳禁忌除外",
        "HCV may breastfeed unless nipple bleeding; HIV/chemo/untreated TB avoid。",
        "breastfeeding -> HCV not contraindication"),
    item(37, exp(
        "White classification 中，妊娠期間才診斷的 GDM 依是否需藥物分 A1 與 A2。A1 是飲食控制即可；A2 需要藥物。題目空腹 95、飯後 2 小時 115 且飲食控制，屬 A1。",
        "- A. A1 代表妊娠糖尿病以飲食控制即可，符合題幹。\n- B. A2 代表需要胰島素或藥物控制，題目未需要藥物。\n- C. B 類通常指孕前已存在、發病年齡或病程符合特定條件的糖尿病，不是單純 GDM 飲食控制。\n- D. C 類也屬孕前糖尿病分類，與本題初次妊娠診斷不符。",
        "GDM White classification：A1 飲食控制，A2 需藥物。"),
        "妊娠糖尿病飲食控制即可為 White A1。",
        "White classification GDM",
        "A1 diet controlled; A2 medication required。",
        "GDM -> White A1 if diet controlled"),
    item(38, exp(
        "Congenital Zika syndrome 最嚴重與最具代表性的異常是中樞神經系統，尤其小頭症、腦鈣化、皮質發育異常與神經發展障礙。",
        "- A. 腦部是先天性茲卡症最嚴重、最典型受影響器官系統。\n- B. 肺臟不是 congenital Zika syndrome 的主要靶器官。\n- C. 心臟異常不是此症候群的核心嚴重表現。\n- D. 可有關節攣縮等表現，但最嚴重與最典型仍是腦部與神經發育異常。",
        "Zika 垂直感染最重要是 fetal brain injury：microcephaly、intracranial calcification、neurodevelopmental impairment。"),
        "先天性茲卡症最嚴重異常在腦部。",
        "congenital Zika syndrome",
        "most severe abnormalities involve fetal brain/CNS。",
        "Zika -> fetal brain abnormalities"),
    item(39, exp(
        "32+5 週 PPROM 且無羊膜腔感染時，處置包含住院觀察、抗生素延長潛伏期、GBS 預防、34 週前皮質類固醇促肺成熟。Tocolytics 在 PPROM 通常不常規建議，可能增加感染風險，僅非常短期特定目的才考慮。",
        "- A. GBS prophylaxis 需依篩檢或風險處理，是合理治療。\n- B. 宮縮抑制劑在 PPROM 不建議常規使用，尤其無明確短期目標時最不建議。\n- C. 34 週前使用 corticosteroid 可促進胎肺成熟，降低新生兒併發症。\n- D. 抗生素可延長 latency 並降低感染與新生兒風險，是 PPROM 常規處置之一。",
        "PPROM 未感染：抗生素、GBS prophylaxis、34 週前 steroid；tocolytics 不常規使用。"),
        "PPROM 32+5 週最不建議常規使用 tocolytics。",
        "PPROM management",
        "latency antibiotics + steroids + GBS prophylaxis; avoid routine tocolysis。",
        "PPROM -> no routine tocolytics"),
    item(40, exp(
        "卵巢子宮內膜異位瘤手術中，囊腫剝除 excisional surgery 相較單純引流/燒灼可降低復發並改善疼痛與自然懷孕機會，但可能影響卵巢儲備。題目問最不適當。",
        "- A. Endometrioma 常與骨盆側壁、卵巢窩或周邊組織沾黏，正確。\n- B. Excisional surgery 通常降低復發機率，不是增加復發機率，因此最不適當。\n- C. 骨盆側壁沾黏或解剖變形時，腹腔鏡手術可能傷及輸尿管，需辨認走向。\n- D. 適當 excision 可改善後續自然懷孕機會，但需平衡卵巢功能損失。",
        "Endometrioma cystectomy/excision 通常降低復發並改善自然懷孕機會，但需避免輸尿管與卵巢儲備傷害。"),
        "Endometrioma excisional surgery 不會增加復發，通常降低復發。",
        "卵巢子宮內膜異位瘤手術",
        "excision lowers recurrence and may improve fertility; watch ureter/ovarian reserve。",
        "endometrioma -> excision reduces recurrence"),
    item(41, exp(
        "腹腔鏡 CO2 氣體栓塞時，處置包含停止充氣、釋放腹腔氣體、給 100% 氧、循環支持、左側臥與頭低姿勢讓氣體滯留右心尖端，必要時由中央靜脈導管抽氣。右側臥不是典型建議姿勢。",
        "- A. 抽吸或釋放腹腔內 CO2 可停止氣體繼續進入循環，是立即處置之一。\n- B. 右側躺不是典型 Durant maneuver；通常採左側臥加頭低，因此較少考慮。\n- C. 大孔徑中央靜脈導管若位置合適，可嘗試由右心抽吸氣體。\n- D. 頭低可讓氣體遠離右室流出道，配合左側臥較符合典型處置。",
        "CO2 embolism：stop insufflation、release gas、100% O2、left lateral decubitus + Trendelenburg、aspirate if possible。"),
        "腹腔鏡 CO2 栓塞較不採右側臥，典型是左側臥頭低。",
        "CO2 embolism position",
        "Durant maneuver = left lateral decubitus + head down。",
        "CO2 embolus -> not right lateral"),
    item(42, exp(
        "子宮肌瘤是良性平滑肌腫瘤，與 leiomyosarcoma 多被視為不同生物行為，肌瘤癌化成肉瘤非常罕見且不應當作一般自然病程。題目問最不適當。",
        "- A. 一般不認為常見子宮肌瘤會癌化成 leiomyosarcoma；若出現肉瘤，多半不是由良性肌瘤逐步癌化而來，因此最不適當。\n- B. 肌瘤常為單株平滑肌細胞腫瘤，部分有染色體異常，敘述正確。\n- C. 雌激素與黃體素可促進肌瘤生長，故生育年齡常變大、停經後縮小。\n- D. 生長因子與 extracellular matrix 增加參與肌瘤生長，是合理病理機轉。",
        "子宮肌瘤是 estrogen/progesterone-sensitive monoclonal benign tumor；不要把 leiomyosarcoma 視為常規癌化結果。"),
        "子宮肌瘤通常不會癌化成 leiomyosarcoma。",
        "子宮肌瘤錯誤敘述",
        "leiomyoma and leiomyosarcoma are generally distinct; hormones and ECM promote fibroid growth。",
        "fibroid -> not typical malignant transformation"),
    item(43, exp(
        "MRKH syndrome 是 Mullerian duct 發育異常，典型為 46,XX、卵巢功能正常、子宮與上段陰道發育不全。常合併泌尿系統與骨骼異常；本題原始選項 D 顯示為亂碼，但官方答案指向泌尿系統。",
        "- A. 視覺異常不是 MRKH 常見合併系統。\n- B. 味覺異常不是 MRKH 的典型合併異常。\n- C. 嗅覺異常較讓人想到 Kallmann syndrome，不是 MRKH 的主要關聯。\n- D. MRKH 常合併腎臟或泌尿系統異常，例如單側腎缺如、異位腎或馬蹄腎；雖然此選項文字在來源檔疑似亂碼，仍符合官方答案方向。",
        "MRKH = Mullerian agenesis with normal ovaries; 常合併 renal/urinary tract anomalies。"),
        "MRKH syndrome 常合併泌尿系統異常。",
        "MRKH 合併異常",
        "uterovaginal agenesis + renal anomalies; option D source text needs review。",
        "MRKH -> renal/urinary anomalies",
        ["來源檔第 43 題 D 選項顯示為亂碼；本次未修改選項文字，僅依官方答案方向撰寫題解。"]),
    item(44, exp(
        "子宮切除時輸尿管危險區包括骨盆上緣跨過髂血管處、子宮動脈下方 water under the bridge、靠近子宮頸與 cardinal ligament 處。位在 psoas muscle 上方較偏近端、較容易辨認，不是典型最易受傷位置。",
        "- A. 輸尿管跨過骨盆上緣與髂血管附近是進入骨盆的重要辨認點，可能受傷。\n- B. 輸尿管穿過子宮動脈下方是婦科手術最經典危險區。\n- C. 靠近子宮頸與陰道穹窿處結紮、分離時也容易傷及輸尿管。\n- D. 在 psoas muscle 上的位置通常較高位且較可辨認，不是子宮切除時最典型易受傷位置。",
        "婦科手術輸尿管危險點：pelvic brim、under uterine artery、near cervix/cardinal ligament。"),
        "腹腔鏡子宮切除時 psoas muscle 上不是典型輸尿管易傷位置。",
        "子宮切除輸尿管危險區",
        "water under the bridge and near cervix are high-risk; psoas segment less typical。",
        "hysterectomy ureter injury -> not psoas segment"),
    item(45, exp(
        "PID 常見症狀與徵象包括下腹/骨盆腔疼痛、發燒、子宮頸位移痛、子宮或附件壓痛、陰道分泌物增加。血尿較指向泌尿道疾病，不是 PID 常見症狀。",
        "- A. 骨盆腔疼痛是 PID 的主要症狀。\n- B. 發燒可出現在 PID，尤其較嚴重感染。\n- C. 子宮頸位移痛是 PID 重要理學檢查線索。\n- D. 血尿較常見於泌尿道感染、結石或泌尿系統病變，不是 PID 典型症狀。",
        "PID 診斷線索：pelvic pain、fever、cervical motion tenderness；hematuria 不是常見表現。"),
        "血尿不是 PID 常見症狀。",
        "PID 症狀除外",
        "pelvic pain + fever + CMT; hematuria suggests urinary tract disease。",
        "PID -> not hematuria"),
    item(46, exp(
        "先天性子宮異常與早期流產、反覆流產、早產與胎位不正有關。一般早期流產族群中先天性子宮異常比例約為 5-10%，反覆流產族群會更高。",
        "- A. 1-5% 偏低，較接近一般族群部分估計，不是早期流產孕婦常考比例。\n- B. 5-10% 符合早期流產孕婦可能合併先天性子宮異常的常見考題答案。\n- C. 20-30% 偏高，較不像單次或一般早期流產族群。\n- D. 35-40% 過高，通常不是本題所問比例。",
        "早期流產中先天性子宮異常約 5-10%；反覆流產族群比例可更高。"),
        "早期流產孕婦約 5-10% 有先天性子宮異常。",
        "早期流產與子宮異常",
        "uterine anomaly prevalence in early miscarriage around 5-10%。",
        "miscarriage -> uterine anomaly 5-10%"),
    item(47, exp(
        "Pseudohermaphroditism 指染色體/性腺性別與外生殖器表現不一致，原因常與荷爾蒙合成、作用或受體異常有關。46,XX 女性假性陰陽人的卵巢通常為正常卵巢，不會因此比一般女性更大。",
        "- A. 外生殖器表現與染色體性別不一致，是 pseudohermaphroditism 的核心概念。\n- B. 46,XY 男性假性陰陽人可有尿道下裂、陰莖發育不足或外生殖器模糊。\n- C. 46,XX 女性假性陰陽人常因雄性素暴露導致外生殖器男性化，但卵巢通常仍為女性卵巢，不是較大，因此錯誤。\n- D. 性荷爾蒙濃度異常或受體異常可造成性分化異常，敘述正確。",
        "46,XX pseudohermaphroditism 是外生殖器受雄性素影響，卵巢本身通常正常。"),
        "女性假性陰陽人不代表卵巢較大。",
        "pseudohermaphroditism",
        "chromosomal/gonadal sex differs from external genitalia; hormone or receptor disorders。",
        "female pseudohermaphroditism -> ovaries not enlarged"),
    item(48, exp(
        "反覆發作、多處疼痛性外陰潰瘍最典型是 genital herpes，由 HSV 引起。梅毒初期常是單一無痛性硬下疳；帶狀疱疹沿皮節；LGV 初期潰瘍常不明顯且後續淋巴結病變較突出。",
        "- A. 梅毒初期典型為無痛性 chancre，與反覆疼痛性多處潰瘍不符。\n- B. 單純性疱疹會造成反覆、疼痛性群聚水泡或潰瘍，是最可能診斷。\n- C. 帶狀疱疹通常沿單側皮節分布，不以反覆外陰多處潰瘍為典型。\n- D. 花柳性淋巴肉芽腫常見短暫小潰瘍後出現疼痛淋巴結腫大，不是本題最典型。",
        "疼痛、反覆、多發 genital ulcers 要先想到 HSV；無痛硬下疳才偏 syphilis。"),
        "反覆疼痛性外陰潰瘍最可能是單純性疱疹。",
        "genital ulcer differential",
        "painful recurrent multiple ulcers -> HSV; painless chancre -> syphilis。",
        "painful recurrent vulvar ulcer -> HSV"),
    item(49, exp(
        "Endometrial cancer type I 多為 estrogen-related endometrioid carcinoma，前驅病灶是 atypical hyperplasia/EIN，預後較好。Type II 多為 serous/clear cell、高惡性度、與萎縮內膜及 p53 異常相關，前驅不是 atypical hyperplasia。",
        "- A. Type I 多為 endometrioid type，正確。\n- B. Type I 通常較低 grade、預後較好，正確。\n- C. Atypical hyperplasia 是 type I 的 precursor，不是 type II，因此此敘述錯誤。\n- D. Type II 通常分化差、侵襲性高，正確。",
        "Endometrial cancer type I = endometrioid + atypical hyperplasia precursor；type II = serous/clear cell + high grade。"),
        "Type II endometrial cancer 的 precursor 不是 atypical hyperplasia。",
        "子宮內膜癌 type I/II",
        "type I precursor atypical hyperplasia; type II high-grade serous/clear cell。",
        "endometrial cancer -> atypical hyperplasia type I"),
    item(50, exp(
        "婦科腫瘤標記常考配對：choriocarcinoma 與 beta-hCG、yolk sac tumor 與 AFP、granulosa cell tumor 與 inhibin/AMH、上皮性卵巢癌與 CA-125。故正確配對是 granulosa cell tumor 與 AMH。",
        "- A. Choriocarcinoma 主要標記是 beta-hCG，不是 LDH。\n- B. Yolk sac tumor 主要標記是 AFP，不是 beta-hCG。\n- C. Granulosa cell tumor 可分泌 inhibin 與 AMH，是正確配對。\n- D. Epithelial ovarian cancer 常用 CA-125；SCC antigen 較常與鱗狀細胞癌相關。",
        "腫瘤標記：choriocarcinoma beta-hCG、yolk sac AFP、granulosa inhibin/AMH、epithelial ovarian CA-125。"),
        "Granulosa cell tumor 可用 AMH 作腫瘤標記。",
        "婦科腫瘤標記",
        "granulosa cell tumor -> inhibin/AMH。",
        "granulosa tumor -> AMH"),
    item(51, exp(
        "2008 FIGO 子宮內膜癌手術分期不再把 positive peritoneal cytology 單獨納入分期，但仍應記錄，因可能有預後意義。肌層侵犯、淋巴結與膀胱侵犯都會影響期別。",
        "- A. 肌層侵犯深度決定 IA/IB 等分期，會影響期別。\n- B. Positive peritoneal cytology 在 2008 FIGO 不改變手術期別，因此為答案。\n- C. 骨盆腔淋巴結陽性屬 stage IIIC1，會影響期別。\n- D. 膀胱侵犯屬局部進展 stage IVA，會影響期別。",
        "2008 FIGO endometrial cancer：腹腔細胞學陽性需記錄但不改變分期。"),
        "Positive peritoneal cytology 不影響 2008 FIGO 子宮內膜癌期別。",
        "endometrial cancer FIGO 2008",
        "peritoneal cytology no longer changes stage; nodes/bladder/myometrium do。",
        "FIGO 2008 endometrial -> cytology not staging"),
    item(52, exp(
        "子宮頸癌 FIGO 2018 納入影像與病理資訊，淋巴結轉移列為 IIIC；但子宮頸癌分期基本仍是臨床分期為主，不是主要以手術分期為依據。",
        "- A. 2018 FIGO 可參考影像與病理結果，敘述正確。\n- B. 子宮頸癌不是主要以手術分期為依據，因此此敘述錯誤。\n- C. PET/CT 常用於評估骨盆腔外淋巴結或遠端轉移，正確。\n- D. 骨盆腔淋巴轉移在 2018 FIGO 屬 IIIC1，為第三期，正確。",
        "子宮頸癌 FIGO 2018 可用影像/病理補充分期，但不是以手術分期為主；淋巴結陽性為 IIIC。"),
        "子宮頸癌分期不是主要以手術分期為依據。",
        "子宮頸癌 FIGO 2018",
        "imaging allowed; nodal disease stage IIIC; not primarily surgical staging。",
        "cervical cancer staging -> not surgical staging"),
    item(53, exp(
        "子宮頸小細胞癌是罕見但高度惡性的神經內分泌癌，早期即容易淋巴與遠端轉移，預後比一般鱗狀上皮癌差，常需含 platinum/etoposide 類似小細胞癌策略的多模式治療。",
        "- A. 子宮頸小細胞癌多為原發子宮頸神經內分泌癌，不是 60% 由肺部轉移。\n- B. 治療常用 platinum/etoposide 概念；carboplatin/paclitaxel 不是此題最典型配方。\n- C. 遠端轉移比例高於一般鱗狀上皮癌，符合其高侵襲性。\n- D. 肥胖或雌激素使用較與子宮內膜癌 type I 相關，不是子宮頸小細胞癌主因。",
        "子宮頸小細胞癌侵襲性高、遠端轉移多，治療常採 platinum-based chemotherapy。"),
        "子宮頸小細胞癌遠端轉移比例高於鱗狀上皮癌。",
        "子宮頸小細胞癌",
        "aggressive neuroendocrine carcinoma; distant metastasis common。",
        "cervical small cell carcinoma -> high distant metastasis"),
    item(54, exp(
        "OHSS 預防重點是降低卵巢刺激強度、使用 GnRH antagonist cycle 時以 GnRH agonist trigger 替代 hCG、使用 cabergoline、freeze-all 等。植入兩個胚胎不會預防 OHSS，懷孕反而可能延長或加重 OHSS。",
        "- A. 降低 gonadotropin 劑量可減少過度卵巢反應，是預防方法。\n- B. Antagonist protocol 中用 GnRH agonist trigger 可減少 hCG 造成的 OHSS 風險。\n- C. 植入兩個胚胎不是 OHSS 預防方法，且多胎/懷孕相關 hCG 可能使 OHSS 更嚴重。\n- D. Cabergoline 可降低 VEGF-mediated vascular permeability，是預防高風險 OHSS 的方法之一。",
        "OHSS 預防：減少刺激、agonist trigger、cabergoline、freeze-all；胚胎植入數不是預防手段。"),
        "植入兩個胚胎不是預防 OHSS 的方法。",
        "OHSS prevention",
        "reduce gonadotropin, GnRH agonist trigger, cabergoline; not two-embryo transfer。",
        "OHSS -> embryo transfer number not prevention"),
    item(55, exp(
        "女性生殖細胞在胎兒期完成 oogonium 增殖並進入減數分裂，出生時多為停在 prophase I 的 primary oocytes。青春期後每週期部分濾泡受 FSH 影響發育，排卵時排出的是 secondary oocyte，需受精後才完成第二次減數分裂。",
        "- A. 卵原細胞在出生前大多已進入初級卵母細胞狀態並停在 meiosis I，為正確核心。\n- B. Primordial follicle 是 primary oocyte 由扁平濾泡細胞包圍；primary follicle 形成時序與敘述用語不精確。\n- C. 初級濾泡早期發育不完全依賴 FSH；FSH 主要促進後續 antral follicle 成長與選擇。\n- D. 排卵時排出 secondary oocyte，停在 meiosis II metaphase，受精後才完成第二次減數分裂。",
        "出生時卵細胞多為 primary oocyte 停在 meiosis I；排卵排出 secondary oocyte，受精後完成 meiosis II。"),
        "卵原細胞出生前已進入初級卵母細胞。",
        "卵細胞發育",
        "oogonia -> primary oocytes before birth; ovulation releases secondary oocyte。",
        "oogenesis -> primary oocytes before birth"),
    item(56, exp(
        "Rotterdam criteria 診斷 PCOS 需三項取二：寡排卵/無排卵、臨床或生化高雄性素、多囊性卵巢型態，並排除其他疾病。胰島素阻抗常見但不是診斷條件之一。",
        "- A. 寡經或無月經反映寡排卵/無排卵，是診斷條件。\n- B. 高雄性素或其臨床表現如多毛、痤瘡，是診斷條件。\n- C. 胰島素阻抗與 PCOS 代謝風險密切相關，但不是 Rotterdam 診斷條件，因此為答案。\n- D. 超音波多囊性卵巢型態是診斷條件之一。",
        "PCOS Rotterdam：oligo/anovulation、hyperandrogenism、polycystic ovaries 三取二；insulin resistance 不是條件。"),
        "胰島素阻抗不是 Rotterdam PCOS 診斷條件。",
        "PCOS Rotterdam criteria",
        "2 of 3: oligo/anovulation, hyperandrogenism, polycystic ovaries。",
        "PCOS -> insulin resistance not diagnostic criterion"),
    item(57, exp(
        "POP-Q 用固定量測點描述骨盆器官脫垂：Aa、Ba、C、D、Ap、Bp，加上 genital hiatus、perineal body、total vaginal length。突出 hymen 外記正值，hymen 內側記負值。",
        "- A. POP-Q 包含 A、B、C、D 點、genital hiatus、perineal body 與陰道總長等描述，是正確概念。\n- B. 突出 hymen 外應記為正號，不是負號。\n- C. 子宮頸/子宮脫垂程度主要看 C 點，不是 Aa 點。\n- D. 膀胱前壁脫垂看 anterior compartment 的 Aa/Ba，不是 C 點。",
        "POP-Q：hymen 為 0，外側正、內側負；C 點看 cervix/apex，Aa/Ba 看前壁。"),
        "POP-Q 包含 Aa/Ba/C/D/Ap/Bp 與 gh、pb、TVL。",
        "POP-Q",
        "outside hymen positive; C is cervix/apex; Aa/Ba anterior wall。",
        "POP-Q -> outside hymen positive"),
    item(58, exp(
        "Brunnstrom 中風復健分期：I 無動作，II 開始痙攣與 synergy，III 痙攣達高峰且 voluntary synergy，IV 開始出現脫離 synergy 的動作且痙攣下降，V 更複雜動作，VI 痙攣接近消失。",
        "- A. Stage II 是痙攣開始出現與 basic synergy 開始，不是獨立動作較明顯。\n- B. Stage III 是痙攣高峰與 synergy pattern 主導。\n- C. Stage IV 開始有部分 independent movement，肌張力開始下降，符合題幹。\n- D. Stage V 是更複雜、較多脫離 synergy 的動作，不是題幹所指開始階段。",
        "Brunnstrom IV：開始脫離 synergy 的獨立動作，spasticity 開始下降。"),
        "開始有獨立動作且肌張力下降是 Brunnstrom stage IV。",
        "Brunnstrom stage",
        "stage IV begins movements out of synergy with decreasing spasticity。",
        "Brunnstrom -> stage IV"),
    item(59, exp(
        "老化肌肉常見 sarcopenia：肌肉量與肌力/爆發力下降，近端與下肢功能影響明顯，type II fast-twitch fibers 較易萎縮。上肢比下肢明顯不符合常見功能衰退模式。",
        "- A. 肌力減少通常下肢比上肢更影響功能且較明顯；說上肢比下肢明顯最不適當。\n- B. 肌肉量減少是老化肌肉核心變化。\n- C. 近端肌群功能下降常較遠端明顯，影響起立、爬樓梯等活動。\n- D. Type II 肌纖維較易萎縮，造成速度與爆發力下降。",
        "Aging muscle：muscle mass/power 下降、type II fiber atrophy、下肢與近端功能影響重要。"),
        "老年肌力下降通常不是上肢比下肢更明顯。",
        "aging muscle",
        "sarcopenia affects mass/power; type II fibers and lower limb function decline。",
        "aging muscle -> lower limb/type II more affected"),
    item(60, exp(
        "Central cord syndrome 多見於老年人頸椎退化狹窄後過伸傷害，造成上肢比下肢無力更明顯，且下肢恢復通常較好。它不一定需要骨折脫位，反而常可在無明顯骨折脫位下發生。",
        "- A. 中髓症候群最常發生於頸髓，正確。\n- B. 常因脊椎骨折脫位造成較像其他嚴重脊髓損傷；central cord 常見於頸椎狹窄加過伸傷害且可無骨折，故此敘述最不適當。\n- C. 老年人跌倒造成頸部過伸是典型情境。\n- D. 下肢功能通常比上肢恢復較好，因上肢受影響較重。",
        "Central cord syndrome：老年頸椎狹窄過伸傷害、上肢弱於下肢、可無骨折脫位。"),
        "Central cord syndrome 不一定由骨折脫位造成。",
        "central cord syndrome",
        "cervical hyperextension in elderly; upper limb worse than lower limb。",
        "central cord -> hyperextension, no fracture often"),
    item(61, exp(
        "正常吞嚥咽部期由腦幹吞嚥中樞協調，時間很短，軟顎與懸雍垂上舉封閉鼻咽，喉部上提前移以保護呼吸道並打開上食道括約肌。喉部下壓會增加誤吸風險，故錯。",
        "- A. 咽部期是反射性、由腦幹吞嚥中樞控制，正確。\n- B. 咽部期通常小於 1 秒，快速完成以避免食團進入氣道。\n- C. 吞嚥時喉部應上提前移，不是下壓，因此此敘述錯誤。\n- D. 懸雍垂與軟顎後縮上舉可封閉鼻咽，避免鼻腔逆流。",
        "咽部期吞嚥：軟顎上舉、喉部上提前移、會厭與聲門保護氣道。"),
        "吞嚥咽部期喉部會上提前移，不是下壓。",
        "吞嚥咽部期",
        "brainstem controlled, <1 sec, larynx elevates/anteriorly moves。",
        "pharyngeal swallow -> larynx elevates"),
    item(62, exp(
        "物理因子是使用物理能量達治療或評估目的，雖然常見於復健醫學與物理治療，但也可用於其他醫療領域，如疼痛、皮膚、運動醫學與術後照護；不能說只應用在復健醫學。",
        "- A. 動力、聲能、光能、電能、熱/冷與水療都屬常見物理因子範圍。\n- B. 物理因子不只應用於復健醫學，其他醫療領域也會使用，因此最不適當。\n- C. 增加熱能為熱療，降低熱能為冷療，定義正確。\n- D. 熱傳遞可包含傳導、對流、輻射、蒸發與轉換等方式，敘述正確。",
        "物理因子不是復健專科獨占工具；其核心是以物理能量產生治療效果。"),
        "物理因子不只應用在復健醫學領域。",
        "physical modality",
        "includes heat/cold/electric/sound/light/water; not limited to PM&R。",
        "physical modality -> not only rehabilitation"),
    item(63, exp(
        "截肢復健應早期開始，包括殘肢照護、腫脹控制、關節活動、肌力、轉位與心理調適；義肢準備也可在傷口完全癒合前進行評估與 shaping，不是等完全癒合才開始一切。",
        "- A. 殘肢痛可由傷口、感染、缺血、神經瘤、骨刺或義肢壓迫等造成，正確。\n- B. 義肢裝配流程不應等傷口完全癒合後才開始；術後早期就要進行復健與殘肢塑形，因此最不適當。\n- C. 幻肢痛被視為神經性疼痛與中樞/周邊神經重塑相關，正確。\n- D. 幻肢痛是已截除肢體仍感疼痛，定義正確。",
        "截肢復健要早期介入；義肢前準備、殘肢塑形與訓練不必等完全癒合才開始。"),
        "截肢復健與義肢準備應早期開始，不是等傷口完全癒合後才開始。",
        "截肢復健",
        "early rehab, residual limb shaping, pain control; phantom pain neuropathic。",
        "amputation rehab -> early prosthetic preparation"),
    item(64, exp(
        "僵直性脊椎炎屬 seronegative spondyloarthropathy，常與 HLA-B27 相關，多見於年輕男性，發病常在 40 歲前。男女比率相近且 35 歲以上居多不符合典型流行病學。",
        "- A. AS 屬血清陰性脊椎關節病變，RF 通常陰性，正確。\n- B. HLA-B27 多為陽性但不是診斷必備，敘述大致正確。\n- C. AS 男性較多、年輕發病，通常 35 歲以前或 40 歲前起病；說男女相近且 35 歲以上居多錯誤。\n- D. Modified New York Criteria 包含影像 sacroiliitis 與臨床條件，HLA-B27 不是必備條件，正確。",
        "AS 典型是年輕男性、發炎性下背痛、HLA-B27 常陽性；不是 35 歲以上居多且男女相近。"),
        "僵直性脊椎炎多為年輕男性發病，不是 35 歲以上居多。",
        "ankylosing spondylitis epidemiology",
        "young male predominance, HLA-B27 associated, modified New York criteria。",
        "AS -> young male, not older equal sex"),
    item(65, exp(
        "胸腔復健是跨專業整合，包括運動訓練、呼吸訓練、營養、心理支持、職能治療、教育與日常生活節能技巧。最適當選項是指出呼吸困難影響 ADL 時可接受上肢訓練、活動簡化與職能治療。",
        "- A. 胸腔復健不是只由物理治療師主導、其他人偶爾配合；它是跨團隊模式。\n- B. 上肢肌力訓練、ADL 簡化與職能治療可改善呼吸困難病人的生活功能，是正確且完整的描述。\n- C. 心理治療與心理支持屬胸腔復健重要項目，不能排除。\n- D. 只有呼吸運動與姿勢引流不算完整胸腔復健，還需運動、教育、營養與心理等整合。",
        "Pulmonary rehabilitation 是 multidisciplinary program，不只是呼吸運動；包含運動、ADL、心理與教育。"),
        "胸腔復健可包含職能治療與日常生活活動訓練。",
        "胸腔復健",
        "multidisciplinary: exercise, OT/ADL, education, nutrition, psychology。",
        "pulmonary rehab -> multidisciplinary ADL training"),
    item(66, exp(
        "孕前到早孕補充 folic acid 可降低神經管缺損，如 spina bifida 與 anencephaly 的發生率。它不能預防腦性麻痺、SMA 或染色體不分離造成的唐氏症。",
        "- A. 腦性麻痺原因多元，葉酸補充不是已證實主要預防方法。\n- B. 神經管缺損與葉酸不足相關，補充葉酸可明顯降低風險。\n- C. SMA 是 SMN1 遺傳疾病，葉酸不能預防。\n- D. 唐氏症多為第 21 對染色體三體，葉酸不是主要預防策略。",
        "葉酸補充最經典預防的是 neural tube defects。"),
        "孕婦補充葉酸可降低胎兒神經管缺損。",
        "folic acid pregnancy",
        "prevents neural tube defects, not SMA/Down syndrome/CP。",
        "folic acid -> neural tube defects"),
    item(67, exp(
        "腦性麻痺是發育中腦部非進行性損傷造成的姿勢與動作障礙，原因包括早產、缺氧缺血、感染、核黃疸等；通常不是以遺傳性疾病為主要關聯。可合併認知、癲癇、聽視覺與骨骼問題。",
        "- A. 腦性麻痺患者可合併認知缺損，敘述正確。\n- B. 核黃疸可影響聽覺路徑，需評估聽力，正確。\n- C. 腦性麻痺通常不與遺傳性疾病直接相關，說通常與遺傳性疾病相關為錯誤。\n- D. 抗癲癇藥物與活動量低都可增加 osteopenia 風險，正確。",
        "CP 是非進行性腦損傷造成的動作障礙，常合併認知/癲癇/骨質問題，但不是通常遺傳病。"),
        "腦性麻痺通常不是遺傳性疾病。",
        "cerebral palsy comorbidity",
        "nonprogressive brain injury; cognitive impairment/hearing issues/osteopenia possible。",
        "CP -> not usually genetic"),
    item(68, exp(
        "Barthel index 評估日常生活功能，10 個項目，總分常為 0-100。分數越高代表越獨立，分數越低代表越需要他人協助。",
        "- A. Barthel index 總分通常為 0 至 100 分，正確。\n- B. 它是 ADL 功能評估量表，正確。\n- C. 分數越低代表越依賴、越需要協助；此選項說越不需要協助，故錯誤。\n- D. 常見評估項目共 10 項，包括進食、移位、如廁、行走等，正確。",
        "Barthel index 越高越獨立，越低越依賴。"),
        "Barthel index 分數越低代表越需要協助。",
        "Barthel index",
        "10 ADL items, 0-100; higher is more independent。",
        "Barthel -> low score more dependent"),
    item(69, exp(
        "頸髓完全損傷的功能預後常考各 neurological level。C5 保留肘屈與部分肩功能，經訓練可能在平地短距離操作手動輪椅；C4 通常需電動輪椅，C6/C7 功能更好但不是最高位。",
        "- A. C4 通常需要呼吸與姿勢支持較多，難以獨立操作手動輪椅。\n- B. C5 是經一年訓練後可能獨立操作手動輪椅的最高位損傷。\n- C. C6 有腕伸，手動輪椅能力較 C5 好，但題目問最高位，故不是最佳答案。\n- D. C7 有肘伸，功能更佳，但不是最高位。",
        "脊髓損傷功能題：C5 可能手動輪椅，C4 多電動，C6/C7 功能逐步增加。"),
        "完全頸髓損傷可獨立操作手動輪椅的最高位約 C5。",
        "SCI wheelchair level",
        "C5 may propel manual wheelchair after training; C4 usually power wheelchair。",
        "SCI -> C5 manual wheelchair possible"),
    item(70, exp(
        "肌少症是隨年齡增加而出現肌肉量、肌力與身體表現下降的症候群，會增加跌倒、失能、住院、感染併發症與死亡風險，且盛行率隨年齡上升。",
        "- A. 肌少症定義包含肌肉量、肌肉力量與活動功能下降，是最適當描述。\n- B. 肌少症增加失能風險不只限男性，女性與男性都受影響。\n- C. 住院肌少症會增加感染、壓瘡等不良結果，也與死亡率增加相關，不可說不增加死亡率。\n- D. 發生率與年齡直接相關；失用與不活動會加重，但不是與年齡無關。",
        "Sarcopenia = age-related loss of muscle mass, strength, and performance; increases disability and mortality。"),
        "肌少症是肌肉量、肌力與活動功能隨年齡下降的症候群。",
        "sarcopenia definition",
        "loss of mass + strength + performance with aging。",
        "sarcopenia -> mass strength function decline"),
    item(71, exp(
        "輪椅扶手高度會影響上肢支撐、姿勢、肩膀負荷與推輪動作路徑。太高會使肩膀上提或外展，太低則支撐不足；因此說與推動施力無關是不適當的。",
        "- A. 扶手高度可用手肘約 90 度時座椅到前臂的距離評估，敘述可接受。\n- B. 扶手高度會影響推輪施力、肩部姿勢與效率；說無關最不適當。\n- C. 扶手若干擾推輪路徑，可能使肩膀過度外展並增加傷害風險，正確。\n- D. 扶手太低無法給上肢與肩部足夠支撐，正確。",
        "輪椅扶手高度會影響支撐、肩部負荷與推輪效率。"),
        "扶手高度與推動輪椅施力有關。",
        "wheelchair armrest",
        "armrest height affects support, propulsion, and shoulder strain。",
        "armrest height -> propulsion matters"),
    item(72, exp(
        "年輕女性下腹痛、發燒，影像若見複雜性附件腫塊或輸卵管卵巢區膿瘍，最符合 tubo-ovarian abscess，通常是 PID 的嚴重併發症。",
        "- A. 巧克力囊腫可造成慢性骨盆痛或急性破裂痛，但發燒與感染性膿瘍影像更支持 TOA。\n- B. 卵巢癌在 26 歲較少，且急性發燒下腹痛不是最典型。\n- C. 畸胎瘤可扭轉造成急痛，但發燒與感染徵象不是主要表現。\n- D. Tubo-ovarian abscess 會造成發燒、下腹痛與複雜性附件膿瘍影像，是最可能診斷。",
        "年輕女性發燒加下腹痛、影像複雜性附件膿瘍，要想到 TOA。"),
        "下腹痛發燒合併附件膿瘍影像最可能為輸卵管卵巢膿瘍。",
        "TOA diagnosis",
        "PID complication with fever, pelvic pain, complex adnexal abscess。",
        "fever pelvic pain CT -> tubo-ovarian abscess"),
    item(73, exp(
        "頭部外傷後眼球突出、紅腫、顱內或眼眶雜音、視力快速下降，典型為 traumatic direct carotid-cavernous fistula。診斷可用 CTA/MRA/血管攝影，治療多為血管內栓塞，不是放射治療即可痊癒。",
        "- A. Direct CCF 不能以放射治療即可痊癒作為處置，通常需血管內治療，因此最不恰當。\n- B. 血管攝影是診斷與治療規劃標準，CTA 也可協助確認。\n- C. 上眼靜脈擴張是 CCF 影像線索之一。\n- D. 外傷性 direct CCF 常與顱底骨折或頸內動脈海綿竇段損傷相關。",
        "外傷後 pulsatile proptosis/bruit/vision loss 要想到 direct CCF；治療以 endovascular embolization 為主。"),
        "直接型頸動脈海綿竇瘻管不是放射治療即可痊癒。",
        "direct carotid-cavernous fistula",
        "trauma + proptosis + bruit; diagnose CTA/angiography; treat endovascularly。",
        "direct CCF -> not radiotherapy"),
    item(74, exp(
        "起床第一步足底跟骨附著處疼痛是 plantar fasciitis 經典表現。超音波常見足底筋膜增厚、低回音或附著處變化，與對側比較更明顯。",
        "- A. 跟骨骨髓炎通常有感染、持續疼痛與全身徵象，不是典型晨起第一步痛。\n- B. 腱鞘囊腫多為局部囊性腫塊，與足底筋膜附著處晨痛不符。\n- C. 足底筋膜炎最符合年長女性、足跟底部疼痛、晨起著地加劇與超音波足底筋膜變化。\n- D. 足底筋膜斷裂常有急性撕裂感、瘀青或突然疼痛，非本題最可能。",
        "Plantar fasciitis：heel pain worst with first steps in morning，ultrasound shows thickened plantar fascia。"),
        "晨起第一步足底跟骨附著處疼痛最像足底筋膜炎。",
        "plantar fasciitis",
        "first-step heel pain + thickened plantar fascia on ultrasound。",
        "first-step heel pain -> plantar fasciitis"),
    item(75, exp(
        "這位病人休克、嚴重低氧、肺炎且有氣喘史，插管誘導藥需避免明顯降血壓並兼具支氣管擴張。Ketamine 可維持交感張力、較不抑制血壓，且有 bronchodilation，是較適合選項。",
        "- A. Midazolam 起效較慢且可造成低血壓與呼吸抑制，不是休克低氧插管最佳誘導選擇。\n- B. Ketamine 對血壓相對友善並有支氣管擴張效果，適合氣喘合併休克病人 RSI 誘導。\n- C. Propofol 容易造成血管擴張與心肌抑制，休克病人可能血壓崩落。\n- D. Barbiturate 也可能造成心血管抑制與低血壓，不適合此情境。",
        "休克或氣喘病人插管誘導常考 ketamine：維持血壓、支氣管擴張。"),
        "休克合併氣喘急插管較適合 ketamine。",
        "RSI induction asthma shock",
        "ketamine supports BP and bronchodilates; avoid propofol/barbiturate hypotension。",
        "intubation asthma shock -> ketamine"),
    item(76, exp(
        "Herpes zoster ophthalmicus 是水痘帶狀疱疹病毒侵犯三叉神經第一分支 V1。鼻尖水泡 Hutchinson sign 代表鼻睫神經受侵犯，眼部併發症風險較高。",
        "- A. HZO 是三叉神經眼支，不是顏面神經侵犯。\n- B. 鼻頭水泡 Hutchinson sign 提示鼻睫神經受侵犯，可能產生眼部病變，是正確。\n- C. HZO 可造成角膜炎、葡萄膜炎、視網膜炎，也可造成視神經炎或眼肌麻痺等，不可說不會視神經炎。\n- D. 治療重點是早期全身抗病毒藥，類固醇需依眼科評估使用；抗生素藥膏不是主要治療。",
        "HZO = V1 zoster；Hutchinson sign 提示 ocular involvement，治療重點是早期 systemic antiviral。"),
        "鼻頭水泡 Hutchinson sign 代表 HZO 眼部侵犯風險較高。",
        "herpes zoster ophthalmicus",
        "V1 involvement, Hutchinson sign, systemic antivirals。",
        "HZO -> Hutchinson sign"),
    item(77, exp(
        "主動肩外展或前抬疼痛、夜間痛、被動活動相對保留，較符合 rotator cuff tendinopathy/tear 或 impingement。Adhesive capsulitis 會主動與被動活動都受限；fibromyalgia 多全身廣泛痛。",
        "- A. 纖維肌痛是廣泛性疼痛與壓痛，不會只表現為單側肩外展痛且特殊動作誘發。\n- B. 肩旋轉肌袖損傷會造成主動外展/前抬疼痛、夜間痛，且被動活動可相對保留，最符合。\n- C. 沾黏性肩關節囊炎典型是主動與被動活動皆受限，尤其外旋受限，不符合題幹被動外展不痛。\n- D. 肩關節炎常有關節活動受限、摩擦或影像退化，與此題較不吻合。",
        "Rotator cuff injury：主動外展痛、夜間痛、被動 ROM 相對保留；frozen shoulder 主被動都受限。"),
        "主動肩外展痛但被動活動保留最像 rotator cuff injury。",
        "shoulder pain diagnosis",
        "active painful arc/night pain with preserved passive ROM -> rotator cuff。",
        "shoulder active pain passive ok -> rotator cuff"),
    item(78, exp(
        "我國醫療實務中，病歷由醫療機構/醫師製作與保管，通常認為醫師及醫院具病歷所有權；病人有依法請求複製、摘要與使用其病歷資料的權利。因此醫師、醫院與病人皆有使用權。",
        "- A. 醫師及醫院不具使用權的說法錯誤；醫療照護、品質管理與法定目的都需使用病歷。\n- B. 醫師及醫院具病歷所有權，醫師、醫院及病人皆具使用權，最符合考點。\n- C. 病人不是病歷正本所有權人，且病人有取得與使用病歷資料權利。\n- D. 病人具病歷所有權此說法不符合一般醫療法規考點。",
        "病歷正本所有/保管在醫療機構，病人有取得複製本與使用資料的權利。"),
        "病歷所有權屬醫師/醫院，使用權醫師、醫院、病人皆有。",
        "病歷所有權使用權",
        "medical record owned/kept by provider; patient has access/use rights。",
        "medical records -> provider ownership, patient use rights"),
    item(79, exp(
        "本題考人體試驗/臨床試驗相關病歷保存。未成年人參與臨床試驗且涉及癌症治療等重大資料，依法規與研究倫理通常需永久保存，官方答案為永久保存。",
        "- A. 治療後 7 年是一般病歷保存年限概念之一，但臨床試驗與未成年癌症治療不適用這麼短。\n- B. 保存至成年不足以涵蓋臨床試驗長期追蹤與法律責任。\n- C. 成年後 7 年仍非本題法規考點的最佳答案。\n- D. 臨床試驗治療過程病歷依規定需永久保存，符合官方答案。",
        "臨床試驗相關治療病歷保存年限常較一般病歷嚴格；本題為永久保存。"),
        "兒童癌症臨床試驗治療病歷應永久保存。",
        "臨床試驗病歷保存",
        "clinical trial medical records in this scenario -> permanent preservation。",
        "clinical trial record -> permanent"),
    item(80, exp(
        "第二孕期母血唐氏症篩檢是風險評估，不是診斷。1/30 代表高風險，下一步應提供遺傳諮詢並建議診斷性檢查如羊膜穿刺；不能只依篩檢結果直接安排人工流產。",
        "- A. 篩檢高風險尚未診斷胎兒唐氏症，直接依要求安排人工流產不是最適宜處置。\n- B. 應說明母血篩檢只是風險評估，建議羊膜穿刺確認染色體，最適當。\n- C. 重做一次母血篩檢不能取代診斷性檢查，且會延誤決策。\n- D. 高層次超音波可找結構異常或軟指標，但不能確診唐氏症，診斷仍需染色體檢查。",
        "產前篩檢高風險不等於診斷；下一步是診斷性檢查，如羊膜穿刺。"),
        "唐氏症母血篩檢高風險應建議羊膜穿刺確認。",
        "唐氏症篩檢高風險",
        "screening risk is not diagnosis; confirm with amniocentesis/karyotype or genetic testing。",
        "Down screening high risk -> amniocentesis"),
]


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    if len(UPDATES) != 80:
        raise SystemExit(f"expected 80 updates, got {len(UPDATES)}")
    for start in range(1, 81, 10):
        end = start + 9
        updates = [u for u in UPDATES if start <= u["question_number"] <= end]
        payload = {
            "source_file": SOURCE_FILE,
            "dataset_id": DATASET_ID,
            "range": {"start": start, "end": end},
            "updates": updates,
        }
        path = OUT_DIR / f"q{start:03d}-q{end:03d}.json"
        path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
