import json
from pathlib import Path


SOURCE_FILE = "public/data/exams/111-2/medicine-6.json"
DATASET_ID = "111-2_medicine-6"
OUT_DIR = Path("scratch/rewrite_updates/111-2_medicine-6")
STAMP = "2026-07-16T00:00:00+08:00"


def exp(analysis, options, core):
    return "\n".join(
        [
            "【題幹解析】",
            analysis,
            "",
            "【選項詳解】",
            f"- A. {options['A']}",
            f"- B. {options['B']}",
            f"- C. {options['C']}",
            f"- D. {options['D']}",
            "",
            "【核心考點】",
            core,
        ]
    )


ITEMS = {
    1: {
        "front": "OPA / NPA / 清醒病人 / 顱底骨折",
        "analysis": "本題問氣道輔助工具何者錯誤。口咽人工氣道（OPA）與鼻咽人工氣道（NPA）的差別，關鍵在病人是否保有咽喉反射，以及鼻腔置入是否可能因顱底骨折而進入顱內。",
        "options": {
            "A": "錯誤。清醒病人通常保有 gag reflex，放置 OPA 會刺激舌根與咽後壁，容易造成嘔吐、喉痙攣或吸入風險；若需要輔助氣道，通常 NPA 較能被清醒或半清醒病人耐受。",
            "B": "正確。OPA 會刺激口咽部，是誘發嘔吐與吸入性併發症的重要風險，因此適合用在意識不清、咽喉反射減弱的病人。",
            "C": "正確。疑似顱底骨折或篩骨板受損時，NPA 可能沿鼻腔誤入顱內，屬於重要禁忌。",
            "D": "正確。NPA 通過鼻腔黏膜，鼻黏膜血管豐富，置入過粗、潤滑不足或操作粗暴都可能造成鼻出血。",
        },
        "core": "OPA 適合無意識且咽喉反射弱的病人；NPA 較可用於清醒或半清醒病人，但顱底骨折禁用，常見併發症是鼻出血。",
        "key": "清醒病人不優先使用 OPA；顱底骨折禁用 NPA。",
        "summary": "人工氣道選擇 -> 清醒病人避免 OPA，顱底骨折避免 NPA",
        "back": "OPA 易刺激 gag reflex，清醒病人不宜；NPA 可較被耐受，但顱底骨折禁用。",
    },
    2: {
        "front": "SvO2 / TEE / PPV / CVP",
        "analysis": "本題問麻醉與重症心血管監測何者錯誤。解題重點是 SvO2 的正常範圍、TEE 可提供的即時心臟資訊，以及動態前負荷指標比靜態壓力更能預測輸液反應性。",
        "options": {
            "A": "錯誤。肺動脈導管可測混合靜脈血氧飽和度（SvO2），用來反映全身氧供與氧耗平衡；正常多約 60% 至 80%，30% 至 50% 已提示嚴重氧供不足或氧耗過高。",
            "B": "正確。TEE 可評估心室收縮與舒張、瓣膜、容量狀態、心內血栓與導管位置，除心臟手術外，高風險非心臟手術也可使用。",
            "C": "正確。PPV、SVV 等動態指標利用正壓通氣造成的心肺交互作用，通常比 CVP、PCWP 這類靜態壓力更能預測輸液後心輸出是否增加。",
            "D": "正確。CVP 與肺動脈導管數值容易受體位、PEEP、心室順應性與操作者解讀影響，臨床最大風險常是誤用數值而非導管本身。",
        },
        "core": "SvO2 正常約 60% 至 80%；輸液反應性應優先看動態指標，壓力數值需結合臨床脈絡解讀。",
        "key": "SvO2 30% 至 50% 不是正常值，而是危險的低氧供訊號。",
        "summary": "心血管監測 -> SvO2 正常約 60-80%，動態指標較能預測輸液反應",
        "back": "SvO2 反映氧供與氧耗平衡；PPV/SVV 通常比 CVP/PCWP 更能預測輸液反應性。",
    },
    3: {
        "front": "術中腎臟保護 / 尿量 / creatinine / hemodynamics",
        "analysis": "本題問麻醉中腎功能監測與處理何者正確。術中腎保護的核心不是單靠尿量或 creatinine，而是維持足夠血流動力學、心輸出量、血容量與組織灌流。",
        "options": {
            "A": "錯誤。尿量是常用且容易取得的監測，但會受 ADH、交感神經、利尿劑、輸液與麻醉深度影響，不能精準代表 GFR 或腎實質功能。",
            "B": "錯誤。Creatinine 與 GFR 不是線性正比，而是非線性反比；早期 GFR 下降時 creatinine 可能尚未明顯上升。",
            "C": "正確。維持 hemodynamics、足夠心輸出量、血管內容積與腎灌流，是麻醉中預防急性腎損傷最重要的處置方向。",
            "D": "錯誤。IL-18 是急性腎小管損傷相關 biomarker，與缺血、發炎或腎小管壓力反應相關，不能說完全無關。",
        },
        "core": "術中腎臟保護看的是有效灌流與血液動力學穩定；尿量和 creatinine 都有延遲或干擾，不能單獨代表腎功能。",
        "key": "麻醉中保腎最重要是維持足夠血液動力學與組織灌流。",
        "summary": "術中腎保護 -> 維持 hemodynamics 比單看尿量或 creatinine 更關鍵",
        "back": "尿量與 creatinine 都有侷限；預防 AKI 的核心是維持心輸出、血容量與腎灌流。",
    },
    4: {
        "front": "opioid reversal / naloxone / flumazenil",
        "analysis": "本題問何者可拮抗過量鴉片類藥物造成的呼吸抑制。題目關鍵是辨認各藥物作用受體：opioid receptor、benzodiazepine receptor、α2 receptor 與 NMDA receptor。",
        "options": {
            "A": "正確。Naloxone 是 opioid receptor 競爭性拮抗劑，可快速逆轉 morphine、fentanyl 等鴉片類藥物造成的呼吸抑制、嗜睡與瞳孔縮小。",
            "B": "錯誤。Flumazenil 是 benzodiazepine receptor 拮抗劑，用於逆轉 benzodiazepine 鎮靜，不是 opioid 過量的解藥。",
            "C": "錯誤。Dexmedetomidine 是 α2 agonist，可鎮靜、止痛並降低交感活性，沒有 opioid receptor 專一拮抗作用。",
            "D": "錯誤。Ketamine 主要是 NMDA receptor antagonist，具有解離麻醉與止痛效果，不能拮抗 opioid 造成的呼吸抑制。",
        },
        "core": "Opioid 過量造成呼吸抑制時使用 naloxone；benzodiazepine 過量才考慮 flumazenil。",
        "key": "Naloxone 是 opioid receptor antagonist，可逆轉 opioid-induced respiratory depression。",
        "summary": "鴉片類過量 -> naloxone",
        "back": "Naloxone 競爭性拮抗 opioid receptor；flumazenil 是 benzodiazepine 拮抗劑。",
    },
    5: {
        "front": "靜脈麻醉劑 / benzodiazepine / propofol / barbiturate",
        "analysis": "本題問靜脈麻醉劑何者錯誤。需要分辨各藥物的主要受體與臨床風險：benzodiazepine 與 barbiturate 都偏向 GABA-A 系統，propofol 製劑則有感染風險。",
        "options": {
            "A": "正確。Benzodiazepine 可造成劑量相關呼吸抑制，與 opioid 或其他鎮靜藥併用時甚至可導致 apnea。",
            "B": "正確。Propofol 是脂質乳劑，若無菌操作或保存不當，容易支持細菌生長，因此開瓶後需依規範使用。",
            "C": "正確。Barbiturate 抑制中樞神經，包含腦幹 reticular activating system，臨床可造成鎮靜與麻醉。",
            "D": "錯誤。Barbiturate 主要增強 GABA-A 受體 chloride channel 的抑制作用；NMDA receptor antagonist 是 ketamine 的典型機轉。",
        },
        "core": "Barbiturate 與 benzodiazepine 的重點是 GABA-A；ketamine 才是 NMDA 拮抗。",
        "key": "Barbiturate 不是靠 NMDA receptor，而是增強 GABA-A 抑制作用。",
        "summary": "靜脈麻醉劑機轉 -> barbiturate: GABA-A；ketamine: NMDA",
        "back": "Barbiturate 增強 GABA-A 抑制；propofol 脂質乳劑需注意污染與感染。",
    },
    6: {
        "front": "困難面罩通氣 / airway adjunct / jaw position",
        "analysis": "本題問麻醉誘導時面罩通氣困難，哪個改善效果最差。困難面罩通氣通常要改善上呼吸道塌陷、舌根後墜與面罩密合，而不是單純用力下壓。",
        "options": {
            "A": "最差。用力往下壓緊面罩可能造成軟組織塌陷、壓迫下顎與舌根後墜，反而惡化氣道阻塞；正確是雙手托下顎並維持密合。",
            "B": "有效。OPA 可將舌根與咽後壁分開，減少上呼吸道阻塞，適合無意識且無 gag reflex 的病人。",
            "C": "有效。NPA 可繞過口咽舌根阻塞，對部分保有咽喉反射或張口困難病人有幫助，但需避開顱底骨折。",
            "D": "有效。壓額抬下巴可改善舌根後墜，是基本氣道開放手法之一。",
        },
        "core": "面罩通氣困難時要開放氣道、使用 airway adjunct、調整頭頸與下顎位置；單純用力壓面罩不是好方法。",
        "key": "困難面罩通氣不應只用力下壓面罩，應改善氣道開放與面罩密合。",
        "summary": "困難面罩通氣 -> airway positioning 與 adjunct 優於用力壓面罩",
        "back": "改善面罩通氣要抬下巴、托下顎、放 OPA/NPA；硬壓面罩可能使氣道更塌陷。",
    },
    7: {
        "front": "TEE / cardiac function / coronary stenosis",
        "analysis": "本題問何者不是經食道超音波（TEE）能取得的資訊。TEE 可直接看心室、瓣膜、容量與主動脈等結構，但不能像冠狀動脈攝影一樣評估冠狀動脈狹窄程度。",
        "options": {
            "A": "可取得。TEE 可由二尖瓣流入、組織都卜勒與左心房相關指標評估左心室舒張功能。",
            "B": "可取得。TEE 可透過 ventricular volume、outflow tract velocity-time integral 等方式估算心輸出量。",
            "C": "可取得。TEE 可測主動脈瓣面積、壓力梯度與瓣膜形態，用於評估主動脈瓣狹窄嚴重度。",
            "D": "不能可靠取得。冠狀動脈狹窄程度主要靠冠狀動脈攝影、冠脈 CT 或功能性缺血評估；TEE 不能作為常規冠脈狹窄分級工具。",
        },
        "core": "TEE 擅長即時評估心臟結構與功能；冠狀動脈狹窄程度不是 TEE 的常規可靠資訊。",
        "key": "TEE 不能取代冠狀動脈攝影來判斷冠脈狹窄程度。",
        "summary": "TEE 能看心室與瓣膜 -> 不能可靠分級冠狀動脈狹窄",
        "back": "TEE 可評估心室、瓣膜與容量；冠脈狹窄需冠狀動脈攝影或相關檢查。",
    },
    8: {
        "front": "epidural steroid injection / radicular pain / cervical injection",
        "analysis": "本題問慢性疼痛硬脊膜外注射何者錯誤。重點是 epidural injection 可用於神經根痛，通常需影像導引；頸椎注射風險較高但並非臨床不用。",
        "options": {
            "A": "正確。輕到中度神經根壓迫造成 radicular pain 時，硬脊膜外類固醇注射可減少發炎與神經根刺激。",
            "B": "正確。為了確認針尖位置、避免血管內或硬膜內注射，臨床常用 X 光透視或其他影像導引。",
            "C": "正確。類固醇可減少神經根發炎，合併局部麻醉藥常較單用局部麻醉藥有較佳短中期疼痛控制。",
            "D": "錯誤。頸椎 epidural injection 因脊髓與血管風險較高，需要嚴格適應症與技術，但仍是臨床可使用的處置。",
        },
        "core": "硬脊膜外注射可治療神經根痛；頸椎注射是高風險技術，不等於完全不用。",
        "key": "頸椎 epidural injection 仍可臨床使用，只是風險與技術要求較高。",
        "summary": "慢性神經根痛 -> image-guided epidural steroid injection 可用",
        "back": "Epidural injection 常需影像導引；頸椎注射風險高但不是禁用或不存在。",
    },
    9: {
        "front": "敗血性休克 / insulin resistance / DIC / thrombocytopenia",
        "analysis": "本題問敗血性休克多重器官問題何者錯誤。敗血症常造成發炎、凝血活化、血小板低下、壓力性潰瘍與代謝異常；胰島素阻抗通常導致高血糖而非低血糖。",
        "options": {
            "A": "錯誤。敗血症與壓力反應會造成 catecholamine、cortisol 上升與 insulin resistance，典型表現是高血糖；低血糖若出現常代表肝衰竭、耗竭或嚴重病況。",
            "B": "正確。敗血症會活化血小板與凝血系統，血小板消耗導致 thrombocytopenia，可是早期警訊之一。",
            "C": "正確。嚴重敗血症可引發凝血與纖溶失衡，造成 DIC、微血栓與出血傾向。",
            "D": "正確。重症壓力、低灌流與凝血異常可造成 stress-related mucosal disease，增加上消化道出血風險。",
        },
        "core": "敗血症的 insulin resistance 典型造成高血糖；血小板低下、DIC 與壓力性潰瘍都是常見重症併發症。",
        "key": "敗血性休克的胰島素阻抗通常導致高血糖，不是低血糖。",
        "summary": "敗血症代謝 -> insulin resistance 多造成高血糖",
        "back": "敗血症常有高血糖、血小板低下、DIC 與壓力性潰瘍出血風險。",
    },
    10: {
        "front": "AMD / anti-VEGF / choroidal neovascularization",
        "analysis": "本題問年齡相關黃斑部退化（AMD）何者最適合 anti-VEGF。Anti-VEGF 主要治療濕性 AMD 的脈絡膜新生血管，對乾性退化與已形成纖維瘢痕效果有限。",
        "options": {
            "A": "不最適合。Drusen 是乾性 AMD 的典型沉積物，代表風險與退化，但不是 anti-VEGF 的主要治療標的。",
            "B": "不最適合。RPE atrophy 屬乾性或地圖狀萎縮表現，anti-VEGF 無法逆轉已萎縮的 RPE 與感光細胞。",
            "C": "正確。Choroidal neovascularization 是濕性 AMD 的核心病變，VEGF 驅動血管新生與滲漏，因此 anti-VEGF 是主要治療。",
            "D": "不最適合。Disciform scarring 代表末期纖維化瘢痕，活動性新生血管減少，視力恢復有限。",
        },
        "core": "Anti-VEGF 治療濕性 AMD 的活動性脈絡膜新生血管；乾性 drusen、RPE 萎縮或末期瘢痕不是主要適應症。",
        "key": "濕性 AMD 有 choroidal neovascularization 時最適合 anti-VEGF。",
        "summary": "AMD 治療 -> anti-VEGF 用於 choroidal neovascularization",
        "back": "Anti-VEGF 的目標是 VEGF 驅動的新生血管與滲漏，典型適應症是濕性 AMD。",
    },
    11: {
        "front": "tractional retinal detachment / PDR / ROP / PVD",
        "analysis": "本題問何者不是牽引性視網膜剝離常見原因。牽引性剝離來自纖維血管膜或瘢痕收縮牽拉；急性後玻璃體剝離較常造成裂孔性剝離。",
        "options": {
            "A": "是常見原因。增殖性糖尿病視網膜病變會形成纖維血管膜，收縮後牽拉視網膜造成 tractional retinal detachment。",
            "B": "是常見原因。嚴重早產兒視網膜病變可有異常血管增生與纖維化牽引，造成牽引性剝離。",
            "C": "是常見原因。穿透性後段眼外傷可造成玻璃體與視網膜纖維化、增殖性玻璃體視網膜病變，進而牽引視網膜。",
            "D": "不是常見原因。急性後玻璃體剝離常因牽拉造成視網膜裂孔，典型後續是裂孔性而非牽引性視網膜剝離。",
        },
        "core": "牽引性視網膜剝離常見於 PDR、ROP、外傷後纖維化；急性 PVD 更典型連到裂孔性剝離。",
        "key": "急性後玻璃體剝離不是牽引性視網膜剝離的常見原因。",
        "summary": "視網膜剝離機轉 -> fibrous traction vs retinal tear",
        "back": "PDR/ROP/外傷纖維膜會牽引視網膜；急性 PVD 常造成裂孔性剝離。",
    },
    12: {
        "front": "結膜炎分泌物 / watery / mucoid / purulent",
        "analysis": "本題問結膜炎分泌物何者錯誤。分泌物型態可提示病因：病毒多 watery，過敏常 mucoid/stringy，細菌與性病感染多膿性或黏液膿性。",
        "options": {
            "A": "正確。披衣菌結膜炎常有慢性濾泡性結膜炎與黏液膿狀分泌物。",
            "B": "正確。淋病奈瑟菌可造成急性嚴重膿性分泌物，甚至迅速侵犯角膜，是眼科急症。",
            "C": "錯誤。急性過敏性結膜炎常見的是黏液性、牽絲狀或水樣分泌物；若題目將單純 mucoid 與急性過敏作不恰當對應，考點在分泌物分類需更精準，過敏尤其重點是癢與黏絲狀分泌物。",
            "D": "正確。病毒性結膜炎典型為水樣分泌物，常合併濾泡、耳前淋巴結或上呼吸道症狀。",
        },
        "core": "Watery 偏病毒，severe purulent 偏淋病，mucopurulent 可見於細菌或披衣菌；過敏最重要線索是癢與黏絲狀分泌物。",
        "key": "結膜炎分泌物判讀要連同癢、濾泡、膿性程度與病程一起看。",
        "summary": "結膜炎分泌物 -> watery 病毒，膿性細菌/淋病，癢加黏絲狀偏過敏",
        "back": "病毒多水樣；淋病可嚴重膿性；披衣菌常黏液膿性；過敏重點是癢與黏絲狀分泌物。",
    },
    13: {
        "front": "遠距視力 / 裸視 1.5 / 近視遠視",
        "analysis": "本題問遠距視力表結果如何解讀。裸視視力代表未矯正狀態下看遠的能力；視力好不等於一定遠視，視力差也不能單獨診斷遠視或排除遠視。",
        "options": {
            "A": "不正確。裸視 1.5 代表遠距視力很好，但不能直接推論是遠視眼；正視眼或輕度遠視也可能視力好。",
            "B": "較正確。近視眼遠方影像落在視網膜前，未矯正時遠距視力通常下降；裸視 1.5 表示明顯近視的可能性低。",
            "C": "不正確。裸視 0.5 代表未矯正遠距視力較差，可能是近視、散光、眼疾或其他原因，不能直接等於遠視。",
            "D": "不正確。遠視病人若調節不足、年齡較大或合併其他屈光問題，也可能裸視不佳，因此不能說 0.5 不會是遠視。",
        },
        "core": "遠距裸視好代表明顯近視可能低，但不能用單一視力值診斷遠視；屈光狀態需驗光確認。",
        "key": "裸視 1.5 只能說不太像明顯近視，不能直接診斷遠視。",
        "summary": "遠距視力解讀 -> 裸視佳不等於遠視，但明顯近視機率低",
        "back": "視力表結果是功能表現；近視遠視需屈光檢查，不能只靠裸視數字判斷。",
    },
    14: {
        "front": "先天性白內障 / leukocoria / amblyopia",
        "analysis": "本題問先天性白內障何者錯誤。先天性白內障可造成白瞳與剝奪性弱視；單側白內障因兩眼競爭不平衡，通常比雙側更容易造成嚴重弱視。",
        "options": {
            "A": "正確。先天性白內障是白瞳的重要鑑別診斷，需與視網膜母細胞瘤、ROP、Coats disease 等區分。",
            "B": "正確。雙眼輕微、不影響視軸的白內障可追蹤觀察，視覺發育受威脅時才需及早手術。",
            "C": "錯誤。單側白內障通常比雙側更容易造成深度弱視，因為正常眼會抑制患眼視覺輸入；雙側雖也會影響發育，但競爭性抑制較不同。",
            "D": "正確。先天性白內障手術後可能發生續發性青光眼，需要長期追蹤眼壓與視神經。",
        },
        "core": "先天性白內障要警覺白瞳與弱視；單側病灶常比雙側更容易造成嚴重弱視。",
        "key": "單側先天性白內障較容易造成嚴重剝奪性弱視。",
        "summary": "先天性白內障 -> 單側比雙側更容易造成嚴重弱視",
        "back": "先天性白內障可造成白瞳；若影響視軸需及早處理並長期追蹤青光眼。",
    },
    15: {
        "front": "弱視 / critical period / screening",
        "analysis": "本題問弱視何者正確。弱視是視覺發育關鍵期因斜視、屈光不正或剝奪造成視皮質發育異常，越早發現與治療效果越好。",
        "options": {
            "A": "錯誤。弱視可單眼也可雙眼，例如雙眼高度屈光不正或雙側視覺剝奪都可能造成雙眼弱視。",
            "B": "錯誤。內斜視常造成弱視，但外斜視若持續或造成抑制，也可能造成弱視，不能說完全不會。",
            "C": "錯誤。老年人白內障造成矯正視力不佳屬於眼球介質混濁造成的視力下降，不是發育關鍵期的弱視。",
            "D": "正確。弱視治療有時間窗，學齡前篩檢視力、立體感與斜視能及早發現並改善預後。",
        },
        "core": "弱視是兒童視覺發育期問題；早期篩檢、矯正屈光、遮眼或其他治療越早越有效。",
        "key": "弱視需在 critical period 內及早發現與治療。",
        "summary": "弱視 -> 關鍵期內治療效果最好，學齡前應篩檢",
        "back": "弱視可由斜視、屈光不正或視覺剝奪造成；不是所有成人視力差都叫弱視。",
    },
    16: {
        "front": "optic disc swelling / papilledema / glaucoma / CRVO",
        "analysis": "本題問視神經盤水腫的鑑別何者不相關。真正的 disc swelling 代表視神經乳頭腫脹；正常眼壓性青光眼典型是視神經凹陷與神經纖維層流失，不是乳頭水腫。",
        "options": {
            "A": "相關。糖尿病或高血壓可造成視神經病變、缺血性視神經病變或相關眼底變化，可能出現視神經盤腫脹。",
            "B": "相關。Papilledema 是顱內壓上升造成的雙側視神經盤水腫，是重要鑑別。",
            "C": "不相關。正常眼壓性青光眼是視神經萎縮與杯盤比增加，通常不是視神經盤水腫的表現。",
            "D": "相關。中心視網膜靜脈阻塞早期或輕微病例可有視神經盤充血腫脹與視網膜出血。",
        },
        "core": "Disc swelling 的鑑別包含顱壓高、缺血、發炎、血管阻塞等；青光眼重點是 cupping，不是 swelling。",
        "key": "正常眼壓性青光眼通常造成視神經凹陷，不是 optic disc swelling。",
        "summary": "視神經盤水腫鑑別 -> papilledema/血管/缺血；青光眼是 cupping",
        "back": "Papilledema 是顱壓高；正常眼壓性青光眼典型為視神經凹陷與視野缺損。",
    },
    17: {
        "front": "herpes viruses / VZV / EBV / CMV / HIV",
        "analysis": "本題問侵犯眼睛的病毒何者不屬於疱疹病毒科。需背疱疹病毒家族成員：HSV、VZV、CMV、EBV、HHV-6/7/8；HIV 是反轉錄病毒。",
        "options": {
            "A": "屬於。Varicella-zoster virus 是 human herpesvirus 3，可造成帶狀疱疹眼病變。",
            "B": "屬於。Epstein-Barr virus 是 human herpesvirus 4，可與眼部發炎或免疫相關病變有關。",
            "C": "不屬於。HIV 屬於 Retroviridae 的 lentivirus，不是 herpes viruses；它可造成免疫低下並增加 CMV retinitis 等機會。",
            "D": "屬於。Cytomegalovirus 是 human herpesvirus 5，免疫低下者可造成 CMV retinitis。",
        },
        "core": "VZV、EBV、CMV 都是 herpesvirus；HIV 是 retrovirus。",
        "key": "HIV 不屬於疱疹病毒科。",
        "summary": "病毒分類 -> VZV/EBV/CMV 是 herpesvirus，HIV 是 retrovirus",
        "back": "Herpesvirus 家族包含 HSV、VZV、EBV、CMV；HIV 是反轉錄病毒。",
    },
    18: {
        "front": "Graves ophthalmopathy / lid retraction / lid lag",
        "analysis": "本題問甲狀腺眼病變眼瞼攣縮何者錯誤。Lid retraction 是眼瞼位置異常偏高或偏低；眼球下看時上眼瞼跟隨下降延遲稱 lid lag，不是 lid retraction 的定義特徵。",
        "options": {
            "A": "正確。甲狀腺眼病變可單側或雙側，雖常雙側但不必然對稱。",
            "B": "正確。眼瞼攣縮可發生於上眼瞼或下眼瞼，造成 scleral show 與暴露性角膜病變。",
            "C": "正確。提上瞼肌與 Müller muscle 等 lid retractors 受交感活性、發炎或纖維化影響，可造成眼瞼攣縮。",
            "D": "錯誤。眼球下看時上眼瞼下降延遲是 lid lag；它可見於 Graves，但不是眼瞼攣縮本身的特徵描述。",
        },
        "core": "Graves 眼病變常見 lid retraction；lid lag 是下視時上眼瞼追隨延遲，兩者要分開。",
        "key": "下視時上眼瞼下落延遲是 lid lag，不是 lid retraction 的定義。",
        "summary": "甲狀腺眼病變 -> lid retraction 與 lid lag 不同",
        "back": "Lid retraction 是眼瞼位置退縮；lid lag 是眼球下看時眼瞼跟隨延遲。",
    },
    19: {
        "front": "耳漏 / 聽損 / 慢性中耳炎 / 膽脂瘤",
        "analysis": "本題描述 50 歲左耳聽損、偶爾流膿，配合耳鏡影像判斷最可能診斷。慢性反覆耳漏與鼓膜穿孔或中耳慢性發炎最符合慢性中耳炎；膽脂瘤通常需有上鼓室凹陷袋、角質堆積或骨破壞線索。",
        "options": {
            "A": "較不符合。急性中耳炎通常是急性耳痛、發燒、鼓膜紅腫膨出，病程較急，不是長期偶爾流膿與聽損。",
            "B": "較不符合。積液性中耳炎多為中耳積液與傳導性聽損，通常沒有反覆膿性耳漏。",
            "C": "正確。慢性中耳炎常有鼓膜穿孔、反覆耳漏與傳導性聽力損失，符合題幹慢性病程。",
            "D": "需鑑別但不是最可能。膽脂瘤可有惡臭耳漏與骨破壞，若影像呈典型角質堆積或 attic retraction 才更支持。",
        },
        "core": "慢性耳漏加聽損優先想到慢性中耳炎；膽脂瘤要看角質堆積、凹陷袋與骨破壞等特徵。",
        "key": "反覆耳漏與聽力損失是慢性中耳炎的典型線索。",
        "summary": "耳漏與聽損 -> 慢性中耳炎",
        "back": "慢性中耳炎常見鼓膜穿孔、反覆耳漏與傳導性聽損；膽脂瘤需注意骨破壞線索。",
    },
    20: {
        "front": "presbycusis / high frequency hearing loss",
        "analysis": "本題問老年型聽力退化何者最不適當。Presbycusis 典型為雙側對稱、漸進性高頻聽力下降，會影響語音辨識，噪音暴露會加重。",
        "options": {
            "A": "適當。男性常因噪音與職業暴露等因素，同年齡聽力退化可較女性嚴重。",
            "B": "適當。長期噪音傷害會破壞毛細胞，使年齡相關聽力退化更明顯。",
            "C": "適當。高頻聽損會影響子音辨識，病人常抱怨聽得到聲音但聽不清楚內容。",
            "D": "不適當。老年型聽力退化通常從高頻開始，不是低頻先退化。",
        },
        "core": "Presbycusis 典型是高頻感音神經性聽損，造成語音辨識下降。",
        "key": "老年型聽力退化通常先影響高頻。",
        "summary": "老年型聽損 -> 高頻先下降，語音辨識變差",
        "back": "Presbycusis 是漸進性高頻感音神經性聽損；噪音暴露會加劇。",
    },
    21: {
        "front": "Pott puffy tumor / frontal sinusitis / osteomyelitis",
        "analysis": "本題問 Pott puffy tumor 何者正確。它是額竇炎併發額骨骨髓炎與骨膜下膿瘍，早期可能只有前額局部腫脹、壓痛或硬結，常見於兒童與青少年。",
        "options": {
            "A": "錯誤。病灶是額骨（frontal bone）骨髓炎與骨膜下膿瘍，不是篩骨。",
            "B": "錯誤。較常見於兒童、青少年或額竇發育後年輕族群，不是老年人典型疾病。",
            "C": "錯誤。它主要與鼻竇炎感染擴散相關，不是自體免疫疾病的典型併發症。",
            "D": "正確。早期可能只是前額局部軟組織硬化、腫脹或壓痛，若延誤可進展成顱內併發症。",
        },
        "core": "Pott puffy tumor = 額竇炎造成額骨骨髓炎與骨膜下膿瘍，前額腫脹可很早出現。",
        "key": "Pott puffy tumor 的部位是 frontal bone，不是 ethmoid bone。",
        "summary": "Pott puffy tumor -> 額骨骨髓炎與骨膜下膿瘍",
        "back": "額竇炎若併額骨骨髓炎與骨膜下膿瘍，會出現前額腫脹或硬結。",
    },
    22: {
        "front": "allergic rhinitis / first-line therapy / immunotherapy",
        "analysis": "本題問過敏性鼻炎治療何者不屬第一線。第一線多為避免過敏原、抗組織胺、鼻用類固醇與必要時去充血劑；免疫治療屬於特定病人長期控制策略，不是初始第一線。",
        "options": {
            "A": "屬第一線。第二代口服或鼻用抗組織胺可改善打噴嚏、流鼻水與鼻癢。",
            "B": "可作第一線輔助。去充血劑可短期改善鼻塞，但鼻噴劑不可長期連用以免反彈性鼻炎。",
            "C": "屬第一線。鼻用類固醇對鼻塞、流鼻水、打噴嚏與鼻癢都有良好效果，是中重度或持續性過敏性鼻炎核心治療。",
            "D": "不屬一般第一線。免疫治療適用於過敏原明確、常規藥物控制不佳或希望減少長期用藥者，屬進階長期治療。",
        },
        "core": "過敏性鼻炎第一線是抗組織胺與鼻用類固醇等藥物；免疫治療是篩選後的長期疾病調節治療。",
        "key": "免疫治療不是過敏性鼻炎的一般第一線起始治療。",
        "summary": "過敏性鼻炎 -> 抗組織胺/鼻噴類固醇第一線，免疫治療進階",
        "back": "鼻用類固醇是中重度過敏性鼻炎核心治療；免疫治療需特定適應症。",
    },
    23: {
        "front": "epistaxis / anterior septum compression / nasal packing",
        "analysis": "本題問流鼻血治療何者最適當。大多數鼻出血來自前鼻中隔 Kiesselbach plexus，初步處理應壓迫鼻翼前下方與前鼻中隔，必要時鼻填塞或局部止血。",
        "options": {
            "A": "不適當。應壓迫鼻翼軟部、前鼻中隔區域，不是壓鼻骨；壓鼻骨無法有效壓住前鼻中隔血管叢。",
            "B": "不適當。膠原蛋白凝膠基質、氧化纖維素等止血敷料可作為局部止血輔助，不能說無效益。",
            "C": "正確。加壓前鼻中隔或做前鼻填塞是常見且合理的處理方式，符合最常見前鼻出血來源。",
            "D": "不作為初步最適當。前篩動脈結紮屬於保守與填塞治療失敗、或特定後鼻/上方出血時才考慮的侵入性處置。",
        },
        "core": "鼻出血初步處理是壓迫前鼻中隔/鼻翼軟部，局部止血與鼻填塞；手術結紮是後線處置。",
        "key": "鼻出血要壓前鼻中隔，不是壓鼻骨。",
        "summary": "鼻出血處理 -> 壓迫前鼻中隔或鼻填塞",
        "back": "多數鼻出血來自 Kiesselbach plexus；先壓鼻翼軟部與前鼻中隔。",
    },
    24: {
        "front": "idiopathic subglottic stenosis / all credit / estrogen receptor",
        "analysis": "本題官方更正為一律給分，原公告作答鍵為 B。解題仍可掌握成人原因不明聲門下狹窄（iSGS）的典型族群與可能相關因子；若考場遇到最不適當題，需注意官方曾認定選項有爭議。",
        "options": {
            "A": "通常正確。iSGS 典型好發於中年或生育年齡女性，是此病的重要流行病學線索。",
            "B": "有爭議。iSGS 曾被推測與女性荷爾蒙相關，但雌激素受體表現並非穩定、明確的診斷事實；本題原答案指向此項，但官方後來一律給分。",
            "C": "可為相關因素。胃食道或咽喉逆流常被討論為可能刺激與發炎因子，雖因果不完全確定，但臨床常評估與治療逆流。",
            "D": "可見於研究與臨床推論。聲門下瘢痕組織檢出 pepsin 可支持逆流物到達喉氣管區域的可能性。",
        },
        "core": "iSGS 好發女性，可能與局部發炎、逆流與荷爾蒙假說相關；本題因官方一律給分，應保留爭議而不硬改答案。",
        "key": "111-2 醫學六第 24 題官方一律給分；原答案 B 涉及 iSGS 與雌激素受體爭議。",
        "summary": "iSGS -> 好發女性，逆流/荷爾蒙假說；本題官方 all credit",
        "back": "成人 iSGS 典型見於女性；本題官方更正一律給分，原答案 B 不宜硬背成絕對。",
        "notes": ["官方更正：第24題一律給分；原公告作答鍵為 B。"],
    },
    25: {
        "front": "early laryngeal cancer / radiation / surgery / laryngeal preservation",
        "analysis": "本題問早期喉癌 T1/T2 手術與放療比較何者錯誤。早期喉癌可用放射線或保喉手術治療，局部控制與存活率相近；手術不必然造成較差的長期喉保存。",
        "options": {
            "A": "正確。放射線治療需多次療程，時間與成本通常較單次或短期手術高。",
            "B": "正確。對適當選擇的早期喉癌，放療與內視鏡/保喉手術的局部控制、治癒率與存活率大致相近。",
            "C": "錯誤。早期喉癌手術多可採保喉方式，如經口雷射或部分喉切除，長期喉保存不一定比放療差。",
            "D": "正確。腫瘤位置、暴露困難或侵犯範圍會影響內視鏡切除可行性，可考慮 TORS 或放療。",
        },
        "core": "早期喉癌治療強調腫瘤控制與功能保存；手術與放療各有優缺點，不能概括說手術喉保存較差。",
        "key": "早期喉癌保喉手術的喉保存不一定比放療差。",
        "summary": "早期喉癌 -> 手術與放療控制率相近，手術不必然喉保存較差",
        "back": "T1/T2 喉癌可選放療或保喉手術；依腫瘤位置與功能需求決策。",
    },
    26: {
        "front": "sialolithiasis / submandibular gland",
        "analysis": "本題問唾液腺結石最常出現在哪裡。唾液腺結石最常見於下頷腺，與唾液較黏稠、管徑長、Wharton duct 逆重力向上走有關。",
        "options": {
            "A": "正確。下頷腺是唾液腺結石最常見部位，常表現為進食時疼痛或腫脹。",
            "B": "錯誤。腮腺也可有結石，但比下頷腺少見，Stensen duct 分泌液較稀且流向較有利。",
            "C": "錯誤。舌下腺結石相對少見。",
            "D": "錯誤。小唾液腺不是典型最常見的唾液腺結石部位。",
        },
        "core": "Sialolithiasis 最常發生在 submandibular gland；餐時腫痛是典型症狀。",
        "key": "唾液腺結石最常見於下頷腺。",
        "summary": "唾液腺結石 -> submandibular gland 最常見",
        "back": "下頷腺唾液較黏、管道長且逆重力，最容易形成結石。",
    },
    27: {
        "front": "medullary thyroid carcinoma / C cell / calcitonin / sporadic",
        "analysis": "本題問甲狀腺髓質癌何者錯誤。髓質癌來自 parafollicular C cell，分泌 calcitonin；多數是偶發型，少數與 MEN2/RET 家族遺傳相關。",
        "options": {
            "A": "正確。Medullary thyroid carcinoma 起源於甲狀腺濾泡旁 C 細胞。",
            "B": "錯誤。多數髓質癌為 sporadic，少數為 familial 或 MEN2 相關；題目把比例倒過來。",
            "C": "正確。髓質癌診斷時頸部淋巴結轉移相當常見，手術評估需重視淋巴結。",
            "D": "正確。Calcitonin 是診斷與術後追蹤的重要腫瘤標記，CEA 也常搭配追蹤。",
        },
        "core": "甲狀腺髓質癌來自 C cell、calcitonin 可追蹤；多數是偶發型，不是家族型。",
        "key": "Medullary thyroid carcinoma 多數為 sporadic。",
        "summary": "甲狀腺髓質癌 -> C cell、calcitonin、sporadic 多數",
        "back": "髓質癌源自 C cell；calcitonin 可追蹤；MEN2 相關是少數但重要。",
    },
    28: {
        "front": "android pelvis / outlet transverse diameter",
        "analysis": "本題問 android 型骨盆何者錯誤。Android pelvis 形態較男性化，入口偏心形、側壁會聚、坐骨棘突出、恥骨弓狹窄，通常不利陰道生產。",
        "options": {
            "A": "正確。Android 型骨盆常有 convergent sidewalls，使胎頭下降空間變窄。",
            "B": "正確。明顯坐骨棘會縮小中骨盆，增加產程受阻風險。",
            "C": "正確。狹窄恥骨弓是 android pelvis 的典型特徵。",
            "D": "錯誤。Android 型骨盆的出口與恥骨弓偏狹窄，不會以骨盆出口橫徑大於 10 cm 作為典型特徵。",
        },
        "core": "Android pelvis 的考點是會聚側壁、坐骨棘突出與恥骨弓狹窄；它不是寬出口骨盆。",
        "key": "Android 型骨盆通常出口狹窄，不是 transverse diameter of pelvic outlet > 10 cm。",
        "summary": "Android pelvis -> convergent sidewalls、prominent spines、narrow pubic arch",
        "back": "Android pelvis 較不利生產，因中骨盆與出口空間較狹窄。",
    },
    29: {
        "front": "pregnancy hormones / hCG peak",
        "analysis": "本題問懷孕全程哪個荷爾蒙不會隨週數持續增加。Estradiol、estriol 與 hPL 多隨胎盤與妊娠進展上升；hCG 則在第一孕期達高峰後下降並維持平台。",
        "options": {
            "A": "會持續上升。Estradiol 隨胎盤功能與妊娠週數增加而上升。",
            "B": "會持續上升。Estriol 主要反映胎盤與胎兒腎上腺/肝臟單位，孕期通常逐漸上升。",
            "C": "正確。hCG 在早孕快速上升，約 8 至 10 週達峰後下降，不是整個孕期持續增加。",
            "D": "會持續上升。Human placental lactogen 隨胎盤量增加而上升，與孕期胰島素阻抗相關。",
        },
        "core": "hCG 早孕達峰後下降；hPL 與 estrogen 類多隨妊娠進展增加。",
        "key": "hCG 不會整個孕期持續增加，而是第一孕期達峰後下降。",
        "summary": "孕期荷爾蒙 -> hCG 早期高峰，hPL/estrogen 持續上升",
        "back": "hCG 是早孕診斷重點；第一孕期達高峰後下降並維持較低平台。",
    },
    30: {
        "front": "amniotic fluid regulation / fetal swallowing / all credit",
        "analysis": "本題官方更正為一律給分，原公告作答鍵為 A。羊水量由胎兒尿液、胎兒吞嚥、肺液分泌、胎盤表面 intramembranous flow 與羊膜 transmembranous flow 共同調控；不同資料對「除胎兒尿液外最多」的表述可有爭議。",
        "options": {
            "A": "原公告作答鍵。胎兒吞嚥是移除羊水的重要路徑，量很大，常被列為羊水量調控的主要因素之一。",
            "B": "有角色但通常不是最多。胎兒肺液分泌會增加羊水量，但相對於吞嚥與胎兒尿液，常不是最大通量來源。",
            "C": "可能造成爭議。Intramembranous flow 可在胎盤表面與胎兒血管間調節水分，部分教材強調其在淨調控上的重要性。",
            "D": "較少作為最大因素。Transmembranous flow 經羊膜與母體循環交換，通常量較小或在淨調控中較次要。",
        },
        "core": "羊水量調控不是單一路徑；胎兒尿液增加羊水、胎兒吞嚥移除羊水，肺液與膜內流動也參與。此題官方 all credit，應記概念而非硬背單一選項。",
        "key": "111-2 醫學六第 30 題官方一律給分；原答案 A，但羊水通量表述有爭議。",
        "summary": "羊水調控 -> 胎兒尿液、吞嚥、肺液、intramembranous flow 共同參與；本題 all credit",
        "back": "胎兒尿液是主要來源之一，胎兒吞嚥是主要移除路徑；本題官方更正一律給分。",
        "notes": ["官方更正：第30題一律給分；原公告作答鍵為 A。"],
    },
    31: {
        "front": "umbilical artery Doppler / S-D ratio / absent end-diastolic flow",
        "analysis": "本題問足月胎兒臍動脈 Doppler 何者正常。正常臍動脈阻力會隨妊娠進展下降，足月 S/D ratio 通常小於 3，舒張末期血流應存在且向前。",
        "options": {
            "A": "異常。S/D ratio 大於該週數第 95 百分位代表胎盤阻力偏高，不是正常。",
            "B": "正確。足月臍動脈 S/D ratio 小於 3 通常屬正常範圍。",
            "C": "異常。Absent end-diastolic flow 表示胎盤阻力嚴重上升，與胎兒生長受限、缺氧風險相關。",
            "D": "異常。Reversed end-diastolic flow 是更嚴重異常，代表高風險胎兒狀態。",
        },
        "core": "正常足月臍動脈 Doppler 應有向前舒張末期血流，S/D ratio 通常小於 3。",
        "key": "足月 umbilical artery Doppler 正常常見 S/D ratio < 3。",
        "summary": "臍動脈 Doppler -> 足月 S/D < 3 且舒張末期血流向前",
        "back": "Absent 或 reversed end-diastolic flow 都是胎盤阻力升高的危險異常。",
    },
    32: {
        "front": "dystocia / power passenger passage",
        "analysis": "本題問難產三大因素何者錯誤。難產常用 3P：power、passenger、passage；pubic symphysis shape 不是標準三大分類之一。",
        "options": {
            "A": "錯誤。Pubic symphysis shape 不是難產三大因素的標準項目；骨盆問題應歸在 passage，而非另列 pubis。",
            "B": "正確。Power 指子宮收縮力與產婦用力不足，是產程遲滯常見因素。",
            "C": "正確。Passenger 指胎兒大小、姿勢、胎位或先露異常，胎兒過大可造成難產。",
            "D": "正確。Passage 指骨盆或軟組織產道狹窄、阻塞或不利生產。",
        },
        "core": "難產三大 P 是 power、passenger、passage；骨盆形態屬 passage。",
        "key": "Dystocia 的三大因素是 power、passenger、passage。",
        "summary": "難產 -> 3P: power, passenger, passage",
        "back": "子宮收縮不足、胎兒過大或胎位異常、產道狹窄都可造成難產。",
    },
    33: {
        "front": "hydrops fetalis / Turner / CMV / TTTS / anencephaly",
        "analysis": "本題問胎兒水腫常見原因何者錯誤。Hydrops fetalis 可由染色體異常、感染、心衰竭、貧血或雙胎併發症造成；無腦症不是典型常見原因。",
        "options": {
            "A": "可造成。Turner syndrome 常與 cystic hygroma、淋巴回流異常及胎兒水腫相關。",
            "B": "可造成。CMV 感染可導致胎兒貧血、肝脾腫大、心衰竭或低蛋白，進而水腫。",
            "C": "可造成。雙胞胎輸血症候群可造成受血胎心衰竭或供血胎貧血，兩者都可能導致 hydrops。",
            "D": "錯誤。無腦症是神經管缺陷，雖可合併羊水過多等問題，但不是胎兒水腫的常見典型原因。",
        },
        "core": "非免疫性胎兒水腫常見原因包括染色體異常、感染、心血管問題、貧血與 TTTS；無腦症不是常見主因。",
        "key": "Anencephaly 不是 hydrops fetalis 的常見原因。",
        "summary": "胎兒水腫 -> Turner、CMV、TTTS 常見；anencephaly 非典型",
        "back": "Hydrops 是胎兒心衰竭或液體平衡失調的結果，需找染色體、感染、貧血與心血管原因。",
    },
    34: {
        "front": "biophysical profile / BPP score / delivery",
        "analysis": "本題問胎兒生理評估 BPP 處置何者錯誤。BPP 低分代表胎兒缺氧風險；4 分通常已屬異常，依週數與臨床情況多應考慮生產，而不是單純隔日再評估。",
        "options": {
            "A": "正確。BPP 6 分且羊水過少代表慢性胎盤功能或胎兒狀態風險，通常建議生產。",
            "B": "正確。BPP 6 分、羊水正常且週數大於 36 週時，因已接近足月，常建議生產。",
            "C": "錯誤。BPP 4 分通常代表胎兒狀態異常，若已達可存活週數，多應進一步處置或生產，不是等隔日再看作為合理處置。",
            "D": "正確。BPP 2 分表示高度異常，通常建議立即評估並生產。",
        },
        "core": "BPP 分數越低越擔心胎兒缺氧；6 分依羊水與週數處理，4 分或 2 分多偏向積極生產。",
        "key": "BPP 4 分通常不應只是隔日再評估。",
        "summary": "BPP 處置 -> 低分尤其 4 分以下多需積極處理",
        "back": "BPP 評估 NST、呼吸、張力、胎動、羊水；羊水過少會使 6 分也偏向生產。",
    },
    35: {
        "front": "chorioamnionitis / prolonged rupture of membranes",
        "analysis": "本題問絨毛膜羊膜炎最主要原因。上行性感染是主要機轉，破水時間延長使陰道菌上行進入羊膜腔的機會增加，是最重要危險因子。",
        "options": {
            "A": "不是主要原因。抽菸與多種孕產風險相關，但不是 chorioamnionitis 的最主要原因。",
            "B": "正確。破水時間延長會破壞羊膜屏障，增加細菌上行感染，是絨毛膜羊膜炎最重要危險因子之一。",
            "C": "不是最主要。免疫抑制可能增加感染風險，但不如 prolonged rupture of membranes 典型。",
            "D": "不是主要原因。妊娠糖尿病可增加感染風險，但不是絨毛膜羊膜炎最主要原因。",
        },
        "core": "Chorioamnionitis 多由陰道菌上行感染，破水時間越長風險越高。",
        "key": "破水時間延長是絨毛膜羊膜炎的重要危險因子。",
        "summary": "絨毛膜羊膜炎 -> prolonged rupture of membranes",
        "back": "羊膜破裂後屏障消失，陰道菌更容易上行感染羊膜腔。",
    },
    36: {
        "front": "fetal death / fetal growth restriction",
        "analysis": "本題問幾乎一半胎兒死亡由哪種懷孕併發症造成。胎兒生長受限反映胎盤功能不全與慢性缺氧，是胎死腹中的重要相關因素。",
        "options": {
            "A": "可相關但非此題最佳。子癇前症可造成胎盤灌流不良與胎兒風險，但題目指向更廣泛且常見的胎兒生長受限。",
            "B": "可相關但非最佳。羊水過少常反映胎盤功能或胎兒腎泌尿問題，可增加風險，但不是此題所問主要併發症。",
            "C": "可造成胎死。胎兒畸形是重要原因之一，但不是題目所指幾乎一半的併發症分類。",
            "D": "正確。Fetal growth restriction 與胎盤功能不全、慢性缺氧及胎兒死亡高度相關，是胎死風險的重要指標。",
        },
        "core": "胎兒生長受限代表胎盤供應不足與慢性胎兒壓力，是胎死腹中的重要風險線索。",
        "key": "Fetal growth restriction 是胎兒死亡的重要相關併發症。",
        "summary": "胎兒死亡風險 -> fetal growth restriction",
        "back": "FGR 常反映胎盤功能不全與慢性缺氧，需加強胎兒監測。",
    },
    37: {
        "front": "pregnancy glucose metabolism / insulin resistance / glucagon",
        "analysis": "本題問何者不是正常懷孕葡萄糖代謝現象。懷孕會形成空腹低血糖、飯後高血糖與高胰島素血症；飯後 glucagon 正常仍會被抑制，不是更不受抑制。",
        "options": {
            "A": "是懷孕現象。胎兒持續消耗葡萄糖，加上母體代謝改變，孕婦可有輕微空腹低血糖。",
            "B": "是懷孕現象。胎盤荷爾蒙造成胰島素阻抗，使飯後血糖上升更明顯。",
            "C": "是懷孕現象。為克服胰島素阻抗，母體胰島素分泌增加，飯後可有高胰島素血症。",
            "D": "不是典型現象。飯後升糖素應受抑制；懷孕的主要代謝特徵是胰島素阻抗與補償性高胰島素，而不是飯後 glucagon 更不受抑制。",
        },
        "core": "正常孕期有加速飢餓與飯後胰島素阻抗：空腹血糖偏低、飯後血糖與胰島素偏高。",
        "key": "懷孕時不是以飯後 glucagon 不受抑制作為典型現象。",
        "summary": "孕期糖代謝 -> 空腹低血糖、飯後高血糖、高胰島素",
        "back": "胎盤荷爾蒙造成胰島素阻抗；母體以增加胰島素分泌補償。",
    },
    38: {
        "front": "severe preeclampsia / immediate delivery / uncontrolled hypertension",
        "analysis": "本題問 30 週重度子癇前症若需終止懷孕，何種情況不能等待 48 小時類固醇而應立即生產。若母體病況不穩，尤其無法控制的高血壓急症，母體安全優先。",
        "options": {
            "A": "正確。無法控制的高血壓急症代表中風、腦出血、心衰竭與器官傷害風險高，不應為完成類固醇而延遲生產。",
            "B": "不一定立即。早期破水需看感染、胎兒狀態與孕週；若母胎穩定，可能仍可短期期待或完成類固醇。",
            "C": "不一定立即。羊水過少提示胎盤或胎兒狀態風險，需監測，但未必單獨成為立即生產的絕對理由。",
            "D": "不一定立即。肝功能上升是 severe feature，但若未進展為 HELLP、肝破裂疑慮或母胎不穩，處置需綜合判斷。",
        },
        "core": "重度子癇前症期待治療的前提是母胎穩定；無法控制的高血壓急症需立即處置與生產。",
        "key": "無法控制的高血壓急症是重度子癇前症立即生產的重要指標。",
        "summary": "重度子癇前症 -> 母體不穩或高血壓急症不可等類固醇",
        "back": "類固醇可爭取 48 小時促胎肺成熟，但不能犧牲母體安全。",
    },
    39: {
        "front": "preeclampsia / endothelial injury / vasospasm / leakage / thrombosis",
        "analysis": "本題問子癇前症內皮損傷後續變化不包括何者。子癇前症是全身血管內皮功能失調，典型造成血管痙攣、血管通透性增加與血栓性病變，不是充血性病變。",
        "options": {
            "A": "包括。內皮功能失調造成 vasospasm，導致高血壓與器官灌流下降。",
            "B": "包括。血管通透性增加造成 plasma leakage、水腫與血液濃縮。",
            "C": "包括。凝血系統活化與內皮傷害可造成微血栓、血小板消耗與 HELLP 相關表現。",
            "D": "不包括。子癇前症核心是痙攣、漏出與血栓性缺血，不是血管充血性病變。",
        },
        "core": "子癇前症病理是 endothelial dysfunction：vasospasm、capillary leak、microthrombi。",
        "key": "子癇前症後續變化不包括充血性病變。",
        "summary": "子癇前症 -> 血管痙攣、血漿外洩、血栓性病變",
        "back": "內皮損傷造成高血壓、水腫/蛋白尿與器官缺血，不是單純充血。",
    },
    40: {
        "front": "congenital adrenal hyperplasia / 17-OHP / uterus",
        "analysis": "本題問先天性腎上腺增生診治何者最不適當。常見 21-hydroxylase deficiency 造成 androgen 過多，46,XX 可外陰男性化但內生殖器由 Müllerian duct 正常發育，通常有子宮。",
        "options": {
            "A": "適當。女性胎兒 androgen 過多可造成 ambiguous genitalia。",
            "B": "最不適當。CAH 主要影響腎上腺類固醇合成與外陰分化，Müllerian 結構通常存在，不是常合併子宮畸形。",
            "C": "適當。21-hydroxylase deficiency 會使 17-hydroxyprogesterone 上升，是診斷重要檢驗。",
            "D": "適當。治療需補充 glucocorticoid，如 hydrocortisone；鹽流失型還需 mineralocorticoid 與鹽分。",
        },
        "core": "CAH 典型是 cortisol 合成缺陷、ACTH 上升與 androgen 過多；46,XX 內生殖器通常正常。",
        "key": "CAH 不會常規造成子宮畸形；17-OHP 上升支持 21-hydroxylase deficiency。",
        "summary": "CAH -> ambiguous genitalia、17-OHP 高、hydrocortisone 治療",
        "back": "46,XX CAH 可外陰男性化，但子宮與 Müllerian 結構通常存在。",
    },
    41: {
        "front": "生育年齡骨盆腔腫塊 / pregnancy test / uterine myoma",
        "analysis": "本題問生育年齡婦女骨盆腔腫塊何者最不適當。第一步要排除懷孕；此年齡層多數卵巢腫瘤良性。子宮肌瘤很常見，但多數無症狀。",
        "options": {
            "A": "適當。生育年齡婦女骨盆腔腫塊需先驗孕，排除子宮內或子宮外孕相關問題。",
            "B": "最不適當。子宮肌瘤確實是最常見良性子宮腫瘤，但大部分肌瘤無症狀，不是大部分會引起症狀。",
            "C": "適當。生育年齡層常見卵巢囊腫與腫瘤多為良性，但仍需依影像特徵與風險評估。",
            "D": "適當。畸胎瘤與子宮內膜異位瘤是此年齡層常見良性卵巢腫瘤。",
        },
        "core": "生育年齡骨盆腔腫塊先驗孕；肌瘤常見但多數無症狀。",
        "key": "子宮肌瘤多數無症狀，不是大部分都會造成症狀。",
        "summary": "骨盆腔腫塊 -> 生育年齡先驗孕，肌瘤多無症狀",
        "back": "評估骨盆腔腫塊要先排除懷孕，再依年齡與影像判斷良惡性風險。",
    },
    42: {
        "front": "syphilis treatment / penicillin G",
        "analysis": "本題問梅毒最常使用治療藥物。Treponema pallidum 對 penicillin 仍高度敏感，benzathine penicillin G 是多數梅毒分期的一線治療。",
        "options": {
            "A": "正確。Penicillin G 是梅毒治療標準藥物；懷孕或神經梅毒也尤其強調 penicillin 治療。",
            "B": "錯誤。Interferon 用於部分病毒或免疫疾病治療，不是梅毒標準治療。",
            "C": "錯誤。Azithromycin 曾被研究或作替代，但抗藥性與失敗風險使其不是最常用治療。",
            "D": "錯誤。Doxycycline 可作為非孕、penicillin 過敏者某些情境替代，但不是最常使用標準治療。",
        },
        "core": "梅毒治療首選 penicillin G；替代藥需看分期、懷孕與過敏狀態。",
        "key": "Syphilis standard treatment 是 penicillin G。",
        "summary": "梅毒治療 -> penicillin G",
        "back": "Penicillin G 是梅毒首選；懷孕梅毒需脫敏後使用 penicillin。",
    },
    43: {
        "front": "prepubertal simple ovarian cyst / observation",
        "analysis": "本題描述 7 歲女孩單側 6 cm、單房、無實心成分、無腹水的單純卵巢囊腫。若影像良性且無急症，兒童卵巢功能保留很重要，通常先密切觀察。",
        "options": {
            "A": "正確。單純囊腫、無實心成分與腹水、另一側正常，最適當是觀察與追蹤，避免過度手術傷害卵巢。",
            "B": "不首選。囊腫抽吸復發率高，也可能漏診病理，通常不是單純囊腫的最佳處置。",
            "C": "不首選。囊腫切除可保留卵巢，但在無症狀且影像良性時，先觀察較合理。",
            "D": "不適當。單側卵巢全切除過度治療，除非高度懷疑惡性或卵巢不可保留。",
        },
        "core": "青春前良性外觀單純卵巢囊腫可先觀察；處置原則是避免不必要卵巢切除。",
        "key": "兒童單純卵巢囊腫、無惡性徵象時可密切觀察。",
        "summary": "兒童單純卵巢囊腫 -> observation",
        "back": "單房、無實心、無腹水的卵巢囊腫偏良性；兒童應盡量保留卵巢。",
    },
    44: {
        "front": "abnormal uterine bleeding / PALM-COEIN / hydrosalpinx",
        "analysis": "本題問不正常子宮出血通常不包括何項。AUB 常見原因包括懷孕相關、內分泌、甲狀腺、子宮內膜息肉/肌瘤/惡性病變與凝血等；輸卵管積水通常造成不孕或骨盆症狀，不是 AUB 常見原因。",
        "options": {
            "A": "包括。生育年齡 AUB 必須先排除懷孕、流產或子宮外孕等懷孕相關出血。",
            "B": "包括。甲狀腺功能異常會影響排卵與月經規律，可造成 AUB。",
            "C": "不通常包括。Hydrosalpinx 是輸卵管積水，常與骨盆感染後遺症或不孕相關，不是子宮出血的典型原因。",
            "D": "包括。子宮內膜增生或腫瘤可造成異常出血，尤其停經後出血要警覺。",
        },
        "core": "AUB 來源多與子宮內膜、排卵、懷孕、內分泌或凝血有關；輸卵管積水不是典型原因。",
        "key": "Hydrosalpinx 通常不是 abnormal uterine bleeding 的原因。",
        "summary": "AUB 鑑別 -> pregnancy、thyroid、endometrium；hydrosalpinx 非典型",
        "back": "生育年齡 AUB 先驗孕，再評估內分泌、結構性與子宮內膜病變。",
    },
    45: {
        "front": "endometrial polyp / tamoxifen / AUB / dysmenorrhea",
        "analysis": "本題問子宮內膜息肉何者錯誤。息肉常無症狀，也可造成不規則出血；tamoxifen 會增加息肉與內膜病變風險。息肉可伴隨經痛或經期不適，不能說絕不會造成經痛。",
        "options": {
            "A": "正確。Tamoxifen 對子宮內膜有類雌激素作用，與內膜息肉、增生與癌症風險增加相關。",
            "B": "正確。許多子宮內膜息肉沒有症狀，是超音波或子宮鏡偶然發現。",
            "C": "正確。不規則子宮出血、經間出血或經血量異常是常見表現。",
            "D": "錯誤。雖然經痛不是最典型症狀，但息肉可能造成子宮收縮、出血異常或合併其他病灶，不能絕對說不會造成經痛。",
        },
        "core": "子宮內膜息肉常無症狀或造成不規則出血；醫學敘述中的「不會」過度絕對時要小心。",
        "key": "子宮內膜息肉不應被絕對說成不會造成經痛。",
        "summary": "子宮內膜息肉 -> tamoxifen 相關，常無症狀或 AUB",
        "back": "內膜息肉常見症狀是不規則出血；tamoxifen 是重要風險因子。",
    },
    46: {
        "front": "uterine leiomyoma / submucosal / subserosal / GnRH agonist",
        "analysis": "本題問子宮平滑肌瘤何者錯誤。肌瘤症狀取決於位置：黏膜下最容易造成經血過多與不孕，漿膜下較常造成壓迫症狀。",
        "options": {
            "A": "正確。子宮肌瘤是最常見的良性婦科腫瘤。",
            "B": "錯誤。漿膜下肌瘤向子宮外生長，較常造成壓迫或腹部腫塊；經血量增多主要與黏膜下或影響子宮腔的肌瘤相關。",
            "C": "正確。GnRH agonist 可暫時降低雌激素、縮小肌瘤與改善貧血，常作術前或短期治療。",
            "D": "正確。黏膜下肌瘤影響子宮腔與著床，移除後可改善受孕率或流產風險。",
        },
        "core": "肌瘤位置決定症狀：submucosal 造成出血與不孕，subserosal 偏壓迫症狀。",
        "key": "經血過多最典型是黏膜下肌瘤，不是漿膜下肌瘤。",
        "summary": "子宮肌瘤 -> submucosal 出血/不孕，subserosal 壓迫",
        "back": "GnRH agonist 可短期縮小肌瘤；黏膜下肌瘤切除可改善生育。",
    },
    47: {
        "front": "Mullerian duct anomaly / uterus / supernumerary ovary",
        "analysis": "本題問 Müllerian duct 融合與隔層吸收異常不包括哪項。Müllerian duct 形成輸卵管、子宮、子宮頸與上陰道；卵巢來源不是 Müllerian duct。",
        "options": {
            "A": "可包括。Müllerian duct 發育不全可造成無子宮或子宮發育不全。",
            "B": "可包括。雙角子宮是 Müllerian duct 融合不全造成。",
            "C": "可包括。中膈子宮是兩側 Müllerian duct 融合後中隔吸收失敗造成。",
            "D": "不包括。多卵巢症與卵巢發育或異位組織相關，卵巢不是由 Müllerian duct 形成。",
        },
        "core": "Müllerian duct 異常造成子宮與上生殖道畸形；卵巢不是 Müllerian duct 衍生物。",
        "key": "Supernumerary ovary 不屬於 Müllerian duct 融合/吸收異常。",
        "summary": "Mullerian anomalies -> 無子宮、雙角、中膈；不包括多卵巢",
        "back": "Müllerian duct 形成子宮、輸卵管、上陰道；卵巢來源不同。",
    },
    48: {
        "front": "bacterial vaginosis / Gardnerella vaginalis",
        "analysis": "本題問細菌性陰道炎最常由何者引起。BV 是陰道菌叢失衡，乳酸菌減少、厭氧菌與 Gardnerella vaginalis 增加，典型為魚腥味與 clue cells。",
        "options": {
            "A": "錯誤。乳酸菌是正常陰道保護菌，產生乳酸維持酸性環境；BV 常是乳酸菌減少。",
            "B": "正確。Gardnerella vaginalis 是 BV 最典型相關菌，常與厭氧菌共同形成 biofilm。",
            "C": "錯誤。GBS 可造成孕產或新生兒感染風險，但不是 BV 最常見原因。",
            "D": "錯誤。Chlamydia trachomatis 造成子宮頸炎、PID 等，不是 BV 的典型主因。",
        },
        "core": "BV 是菌叢失衡：乳酸菌下降、Gardnerella 與厭氧菌上升。",
        "key": "細菌性陰道炎最典型相關菌是 Gardnerella vaginalis。",
        "summary": "BV -> Gardnerella vaginalis、clue cells、fishy odor",
        "back": "BV 不是單純外來感染，而是陰道菌叢失衡，乳酸菌減少。",
    },
    49: {
        "front": "ovarian cancer metastasis / peritoneal spread",
        "analysis": "本題問卵巢癌轉移路徑何者正確。卵巢癌最典型是腫瘤細胞脫落後沿腹水與腹膜表面播散，造成腹膜、網膜與橫膈表面轉移。",
        "options": {
            "A": "錯誤。血行轉移可發生，但不是早期最常見路徑。",
            "B": "正確。腹膜播散是卵巢癌最典型、最重要的轉移方式。",
            "C": "錯誤。卵巢癌可經淋巴轉移，末期並不少見骨盆與主動脈旁淋巴結轉移。",
            "D": "錯誤。皮膚轉移罕見，不能作為典型轉移路徑。",
        },
        "core": "卵巢癌典型轉移是腹膜播散，常侵犯網膜與腹腔表面。",
        "key": "卵巢癌常經腹膜轉移。",
        "summary": "卵巢癌轉移 -> peritoneal seeding",
        "back": "卵巢癌腫瘤細胞可隨腹水在腹膜與網膜表面播散。",
    },
    50: {
        "front": "vulvar cancer risk factors / HPV / lichen sclerosus",
        "analysis": "本題問何者不是外陰癌危險因子。外陰癌主要風險路徑包括 HPV 相關病變與慢性外陰皮膚疾病如 lichen sclerosus；未生育不是典型危險因子。",
        "options": {
            "A": "是危險因子。HPV 感染，尤其高危型，可造成 vulvar intraepithelial neoplasia 與外陰癌。",
            "B": "是危險因子。Lichen sclerosus 與分化型 VIN 和外陰鱗狀細胞癌相關。",
            "C": "不是典型危險因子。Nulliparity 與某些婦癌如子宮內膜癌、卵巢癌風險較相關，但不是外陰癌主要危險因子。",
            "D": "是風險線索。子宮頸癌病史反映 HPV 相關下生殖道病變風險，也增加外陰癌或 VIN 風險。",
        },
        "core": "外陰癌危險因子重點是 HPV 相關病變與慢性外陰皮膚病變；nulliparity 不是典型外陰癌風險。",
        "key": "Nulliparity 不是 vulvar cancer 的典型 risk factor。",
        "summary": "外陰癌風險 -> HPV、lichen sclerosus、下生殖道癌病史",
        "back": "外陰癌有 HPV 相關與非 HPV 慢性皮膚病變兩大路徑。",
    },
    51: {
        "front": "colposcopy / invasive lesion / acetowhite",
        "analysis": "本題問何者不是陰道鏡下侵犯性病灶特徵。醋酸白化可見於 HPV/CIN 等上皮病變，敏感但不特異；真正侵犯性病灶更重視異常血管、不規則表面、潰瘍與壞死。",
        "options": {
            "A": "是特徵。異常、粗大或不規則血管可提示高級別或侵犯性病灶。",
            "B": "是特徵。不規則表面、上皮潰爛或腫塊樣變化需懷疑侵犯癌。",
            "C": "不是侵犯專一特徵。醋酸塗抹後白化常見於 HPV 感染或 CIN，不能單獨代表侵犯性病灶。",
            "D": "是特徵。血管增生、壞死或顏色不均可提示侵犯性病變。",
        },
        "core": "Acetowhite 是陰道鏡常見異常但不等於侵犯癌；侵犯性病灶要看血管、潰瘍、壞死與表面不規則。",
        "key": "醋酸白化不是子宮頸陰道鏡下侵犯性病灶的專一特徵。",
        "summary": "陰道鏡侵犯癌特徵 -> 異常血管/潰瘍/壞死；acetowhite 不特異",
        "back": "醋酸白化可見於 CIN；若疑侵犯癌需切片確認。",
    },
    52: {
        "front": "GTD / hCG / GTN chemotherapy / normal pregnancy after cure",
        "analysis": "本題問妊娠滋養細胞疾病何者錯誤。多數 GTD 會 hCG 升高，但不能說所有病人都一定異常上升；疾病包含葡萄胎、侵襲性葡萄胎、絨毛膜癌、胎盤部位滋養細胞腫瘤等，表現不同。",
        "options": {
            "A": "大致正確。GTD 是妊娠相關滋養層細胞異常增生疾病，常與胎盤滋養細胞來源有關。",
            "B": "錯誤。多數 GTD 會 hCG 上升，但某些型態如 placental site trophoblastic tumor hCG 可不高或僅輕度上升，不能說都會異常上升。",
            "C": "正確。GTN 化療治癒後仍可能保留生育能力並正常懷孕，需完成追蹤後再懷孕。",
            "D": "正確。低風險 GTN 對 methotrexate 或 actinomycin D 等化療反應佳，緩解率高。",
        },
        "core": "GTD/GTN 追蹤常用 hCG，但不是所有滋養細胞腫瘤都一定高 hCG；低風險 GTN 化療效果好。",
        "key": "不能絕對說所有 GTD 病人 hCG 都會異常上升。",
        "summary": "GTD -> 多數 hCG 高，但 PSTT 等可不明顯；低風險 GTN 化療佳",
        "back": "GTD 需以 hCG 追蹤，但要知道不同亞型表現不同。",
    },
    53: {
        "front": "endometrial cancer type I type II / synchronous ovarian cancer",
        "analysis": "本題問子宮內膜癌 type I 與 type II 何者不恰當。Type I 多為 estrogen-related endometrioid carcinoma，較年輕、常見 PTEN；type II 較高齡、高惡性、與 HER2/p53 等相關。同步原發卵巢上皮癌較常與 type I/endometrioid 型相關。",
        "options": {
            "A": "恰當。Type I 通常與 estrogen exposure、肥胖、無排卵等相關；type II 較不直接依賴荷爾蒙。",
            "B": "恰當。Type I 常較年輕或圍停經族群；type II 多見於較高齡、萎縮性內膜背景。",
            "C": "不恰當。同步原發卵巢上皮癌較常見於 type I endometrioid carcinoma，不是 type II 比 type I 更容易。",
            "D": "恰當。PTEN mutation 常見於 type I；HER2/neu 擴增可見於 serous/type II 相關腫瘤。",
        },
        "core": "Type I 子宮內膜癌與雌激素、PTEN、較年輕及同步卵巢 endometrioid 腫瘤較相關；type II 較高惡性。",
        "key": "同步原發卵巢癌較常與 type I 子宮內膜癌相關。",
        "summary": "內膜癌分類 -> type I: estrogen/PTEN/synchronous ovarian；type II: 高齡高惡性",
        "back": "Type I 多為 endometrioid、荷爾蒙相關；type II 多為 serous/clear cell 等高惡性型。",
    },
    54: {
        "front": "ovarian reserve / AFC / AMH / day 3 FSH",
        "analysis": "本題問何者最能表示卵巢卵泡庫存量下降。卵巢庫存下降時 AFC 低、AMH 低、day 3 FSH 常上升；AFC 小於 4 是直接且強的低庫存線索。",
        "options": {
            "A": "錯誤。卵巢庫存下降時 day 3 FSH 常上升，不是下降。",
            "B": "錯誤。Day 3 estradiol 偏高可能假性壓低 FSH，低 estradiol 不是最能代表庫存下降的指標。",
            "C": "正確。兩側 antral follicle count 總數小於 4 表示可募集卵泡數少，支持卵巢庫存下降。",
            "D": "錯誤。AMH 由小卵泡分泌，卵巢庫存下降時 AMH 下降，不是上升。",
        },
        "core": "卵巢庫存下降：AFC 低、AMH 低、day 3 FSH 高。",
        "key": "AFC < 4 是卵巢庫存量下降的重要指標。",
        "summary": "卵巢庫存下降 -> AFC 低、AMH 低、FSH 高",
        "back": "Antral follicle count 與 AMH 反映可募集卵泡數；低值提示 ovarian reserve decreased。",
    },
    55: {
        "front": "PCOS / hyperandrogenism / SHBG / insulin",
        "analysis": "本題問 PCOS 雄性素過高何者不是原因。PCOS 高胰島素會刺激卵巢 androgen 生成並降低肝臟 SHBG，使游離睪固酮增加；SHBG 過多反而會降低游離 androgen。",
        "options": {
            "A": "可造成。部分 PCOS 或相關高雄性素狀態可有腎上腺 DHEAS 增加。",
            "B": "可造成。卵巢 theca cell 在 LH 與 insulin 影響下增加 testosterone 生成。",
            "C": "不是原因。SHBG 會結合性激素，肝臟分泌過多 SHBG 會降低游離 testosterone；PCOS 常見的是 SHBG 降低。",
            "D": "可造成。胰島素過多會促進卵巢 androgen 生成並抑制 SHBG，增加游離雄性素。",
        },
        "core": "PCOS 高雄性素來自卵巢/腎上腺 androgen 增加與 SHBG 降低；高 SHBG 不是高雄性素原因。",
        "key": "PCOS 常是 SHBG 下降造成游離 androgen 增加，不是 SHBG 上升。",
        "summary": "PCOS 高雄性素 -> insulin 高、testosterone/DHEAS 高、SHBG 低",
        "back": "高胰島素促進卵巢 androgen 並降低 SHBG，使游離 testosterone 增加。",
    },
    56: {
        "front": "LH surge / ovulation timing / IVF trigger",
        "analysis": "本題問正常女性 LH surge 開始後多久排卵。LH surge 啟動卵母細胞成熟與濾泡破裂，排卵通常在 LH surge 開始後約 34 至 36 小時。",
        "options": {
            "A": "太早。10 至 12 小時通常不足以完成 LH surge 後的排卵流程。",
            "B": "偏早。22 至 24 小時仍早於典型排卵時間。",
            "C": "正確。排卵通常發生在 LH surge 開始後約 34 至 36 小時，IVF 取卵時間也依此安排。",
            "D": "偏晚。46 至 48 小時通常已超過排卵典型時間，可能錯過最佳取卵時機。",
        },
        "core": "LH surge 開始後約 34 至 36 小時排卵；取卵需在排卵前安排。",
        "key": "Ovulation occurs about 34-36 hours after onset of LH surge。",
        "summary": "LH surge -> 34-36 小時後排卵",
        "back": "IVF 取卵通常安排在 trigger 後約 34-36 小時，避免已排卵。",
    },
    57: {
        "front": "stress urinary incontinence surgery / TVT / mid-urethra",
        "analysis": "本題問尿失禁手術何者錯誤。壓力性尿失禁吊帶手術的重點是中段尿道支撐；TVT 是無張力置於 mid-urethra，而不是膀胱頸。",
        "options": {
            "A": "正確。Burch colposuspension 將陰道旁組織固定到 Cooper ligament，以改善尿道膀胱頸支撐。",
            "B": "錯誤。TVT 是以無張力方式放在中段尿道（mid-urethra）下方，不是膀胱頸處。",
            "C": "正確。TOT 經閉孔路徑較避開 Retzius space，因此腸道與大血管損傷風險較 TVT 低。",
            "D": "正確。TVT 經恥骨後路徑，較 TOT 更容易發生膀胱穿孔。",
        },
        "core": "TVT/TOT 都是 mid-urethral sling；TVT 膀胱穿孔風險較高，TOT 大血管與腸道風險較低。",
        "key": "TVT 吊帶放在中段尿道，不是膀胱頸。",
        "summary": "尿失禁手術 -> TVT 是 mid-urethral sling",
        "back": "TVT 走恥骨後路徑，TOT 走閉孔路徑；兩者皆支撐中段尿道。",
    },
    58: {
        "front": "MCA stroke / neglect / apraxia / akinetic mutism",
        "analysis": "本題問何者不是中大腦動脈中風常見症狀。MCA 供應外側額頂顳葉，可造成偏癱、失語、忽略、失用等；動作不能性緘默較典型與雙側前額葉或 ACA/扣帶迴相關。",
        "options": {
            "A": "常見。非優勢半球 MCA，特別右頂葉受損，可造成 neglect syndrome。",
            "B": "常見。優勢半球頂葉或額頂網絡受損可造成 apraxia。",
            "C": "可見但不是典型最核心。Affective agnosia 可與右半球情緒韻律或臉部情緒辨識網絡受損相關，但不是 MCA 經典常見主症狀。",
            "D": "最不屬常見 MCA。Akinetic mutism 多見於雙側前額葉、前扣帶或 ACA 區域病變，非典型 MCA 常見表現。",
        },
        "core": "MCA 中風常見外側大腦皮質症狀：失語、忽略、失用、偏癱；akinetic mutism 更偏 ACA/前扣帶病灶。",
        "key": "動作不能性緘默不是 MCA 中風常見典型症狀。",
        "summary": "MCA stroke -> neglect/apraxia/aphasia 常見，akinetic mutism 偏 ACA",
        "back": "MCA 供應外側大腦半球；ACA/前扣帶病變較會造成 akinetic mutism。",
    },
    59: {
        "front": "peripheral nerve injury / neurotmesis / surgery",
        "analysis": "本題問周邊神經病變復健治療何者錯誤。Neurotmesis 是神經完全斷裂，若沒有連續性，單靠復健等 3 個月會延誤修補時機，應及早外科評估。",
        "options": {
            "A": "正確。早期支架與被動關節運動可預防攣縮、維持關節活動度與功能位置。",
            "B": "正確。完全去神經肌肉可使用特定電刺激策略延緩萎縮與纖維化，但效果有限且需適當參數。",
            "C": "錯誤。Neurotmesis 是神經截斷或完全斷裂，通常需要早期手術評估與修補，不應一律先復健 3 個月。",
            "D": "正確。Neuropraxia 是傳導阻斷、軸突連續性保留，預後通常良好，數週到數月可恢復。",
        },
        "core": "神經損傷分級決定處置：neuropraxia 可期待恢復；neurotmesis 需早期外科評估。",
        "key": "Neurotmesis 不應固定先復健 3 個月才考慮手術。",
        "summary": "周邊神經損傷 -> neurotmesis 需早期手術評估",
        "back": "Neuropraxia 預後好；axonotmesis 需再生；neurotmesis 常需修補。",
    },
    60: {
        "front": "Froment sign / ulnar nerve / all credit",
        "analysis": "本題官方更正為一律給分，原公告作答鍵為 A。題目所稱 Formet's sign 應是 Froment's sign，典型測試拇指內收肌功能；尺神經病變時病人夾紙會以拇長屈肌代償而拇 IP 關節屈曲。",
        "options": {
            "A": "原公告作答鍵且醫學上最符合。尺神經支配 adductor pollicis 與多數骨間肌，病變會造成 Froment sign 陽性。",
            "B": "不符合。橈神經主要影響腕指伸展，典型是垂腕，不是 Froment sign 的神經。",
            "C": "不符合。正中神經支配 thenar 部分肌肉與拇長屈肌；Froment sign 中拇長屈肌常是代償肌，不是主要受損神經。",
            "D": "不符合。肌皮神經支配肱二頭肌等前臂屈肌群，與手內在肌萎縮及 Froment sign 無直接關係。",
        },
        "core": "Froment sign 是尺神經病變導致 adductor pollicis 無力的表現；本題因拼字或命題因素官方 all credit。",
        "key": "Froment sign 典型是 ulnar nerve lesion；111-2 第 60 題官方一律給分。",
        "summary": "Froment sign -> ulnar nerve；本題 all credit",
        "back": "夾紙時拇 IP 屈曲代表以 median-innervated FPL 代償 ulnar-innervated adductor pollicis。",
        "notes": ["官方更正：第60題一律給分；原公告作答鍵為 A。"],
    },
    61: {
        "front": "EMG / fasciculation / motor neuron disease",
        "analysis": "本題問肌電圖何種疾病最容易出現 fasciculation。肌束顫動常見於下運動神經元興奮性增加，運動神經元疾病如 ALS 是經典考點。",
        "options": {
            "A": "可有周邊神經病變表現，但糖尿病神經病變以感覺症狀、遠端多發神經病變與去神經變化為主，fasciculation 不是最典型。",
            "B": "正確。Motor neuron disease 侵犯下運動神經元時常見 fasciculation、fibrillation、慢性神經再支配等 EMG 變化。",
            "C": "不最典型。GBS 是急性免疫性多發神經病變，EMG 常見傳導變慢或 block，fasciculation 不是主要特徵。",
            "D": "可有去神經變化。Radiculopathy 可有 fibrillation 與 positive sharp waves，但 fasciculation 最典型仍是運動神經元疾病。",
        },
        "core": "Fasciculation 是下運動神經元疾病的重要線索，尤其 ALS 等 motor neuron disease。",
        "key": "EMG 最容易見 fasciculation 的選項是 motor neuron disease。",
        "summary": "肌電圖 fasciculation -> motor neuron disease",
        "back": "ALS 可同時有上、下運動神經元徵象；肌束顫動提示下運動神經元受損。",
    },
    62: {
        "front": "tennis elbow / ECRB / tendinosis",
        "analysis": "本題問網球肘何者正確。網球肘是 lateral epicondylalgia，病理多為 ECRB 肌腱退化性 tendinosis，而非單純急性發炎。",
        "options": {
            "A": "錯誤。病理以退化、微撕裂與 angiofibroblastic hyperplasia 為主，不是典型發炎。",
            "B": "錯誤。典型病變在外上髁附近伸肌總腱起點，尤其 ECRB 起點，不是肌腱交界處。",
            "C": "錯誤。肘關節 ROM 通常保留，疼痛多在 resisted wrist extension 或 gripping 時誘發。",
            "D": "正確。最常侵犯 extensor carpi radialis brevis 肌腱。",
        },
        "core": "Tennis elbow 是 ECRB 起點的退化性肌腱病變，ROM 多正常。",
        "key": "網球肘最常侵犯 ECRB 肌腱起點。",
        "summary": "網球肘 -> ECRB tendinosis，不是單純 inflammation",
        "back": "外上髁疼痛、握力或抗阻腕伸誘發，病灶多在 ECRB。",
    },
    63: {
        "front": "lumbar disc pressure / sitting flexion",
        "analysis": "本題問 L3-L4 椎間盤內壓何種姿勢最高。坐姿本身比站立增加腰椎負荷，坐姿前傾又增加彎曲力矩與椎間盤壓力。",
        "options": {
            "A": "最低之一。平躺時軀幹重量不由腰椎承受，椎間盤壓力較低。",
            "B": "較高但非最高。站立需承受體重，但腰椎彎曲力矩較坐姿前傾小。",
            "C": "正確。坐姿上半身前傾 20 度會增加腰椎屈曲與椎間盤壓力，是選項中最高。",
            "D": "高於平躺與部分站立狀態，但少了前傾力矩，通常低於坐姿前傾。",
        },
        "core": "腰椎椎間盤壓力通常平躺最低，坐姿前傾最高；搬重物前傾會更增加風險。",
        "key": "坐姿上半身前傾會使腰椎椎間盤內壓上升最多。",
        "summary": "椎間盤壓力 -> sitting flexion 最高",
        "back": "坐姿加前傾增加腰椎彎曲力矩與椎間盤負荷。",
    },
    64: {
        "front": "PTB socket / pressure tolerant area / medial femoral condyle",
        "analysis": "本題問膝下義肢 PTB 承筒哪個部位可承壓。PTB socket 會把壓力放在可承壓區，避開骨突與敏感區；股骨內髁/髕骨肌腱等可作為承重與懸吊接觸區。",
        "options": {
            "A": "不宜承壓。腓骨頭表淺且附近有 common peroneal nerve，壓迫可能疼痛或神經傷害。",
            "B": "不宜承壓。脛骨嵴是骨性突出，皮膚軟組織少，應避免直接高壓。",
            "C": "正確。股骨內髁區域相對可承受壓力，常用於承筒穩定與部分負重接觸。",
            "D": "不宜作主要承壓。膕肌肌腱區與後方軟組織需避免過度壓迫，以免疼痛與血管神經受壓。",
        },
        "core": "PTB socket 要壓可耐受區、避開骨突與神經；腓骨頭與脛骨嵴是典型 relief 區。",
        "key": "PTB 承筒可承壓區包含股骨髁附近，需避開腓骨頭與脛骨嵴。",
        "summary": "PTB socket -> medial femoral condyle 可承壓，fibular head/tibial crest 避壓",
        "back": "膝下義肢承筒設計重點是分散負重並保護骨突與神經。",
    },
    65: {
        "front": "aerobic exercise / anaerobic threshold / exercise classification",
        "analysis": "本題問有氧運動何者正確。有氧與無氧不是只靠單一活動名稱劃分，許多運動同時包含不同能量系統；強度、持續時間與肌群大小都會影響分類。",
        "options": {
            "A": "錯誤。超過 anaerobic threshold 後無氧代謝比例增加，不是典型有氧運動定義。",
            "B": "正確。有些運動同時使用有氧與無氧能量系統，依強度與時間不同而難以絕對分類。",
            "C": "錯誤。最大心率 30% 至 35% 通常強度太低；有氧訓練常需達中等強度以上並持續一段時間。",
            "D": "錯誤。有氧運動通常是大肌群、節律性、可持續的活動；短時間小肌肉運動較不符合典型定義。",
        },
        "core": "有氧運動是大肌群、節律性、可持續並主要依賴氧化代謝；實際運動常混合不同能量系統。",
        "key": "有些運動不容易被絕對分成有氧或無氧。",
        "summary": "有氧運動 -> 能量系統取決於強度與時間，分類可重疊",
        "back": "超過 anaerobic threshold 時無氧代謝增加；典型有氧運動需可持續且動用大肌群。",
    },
    66: {
        "front": "cardiac rehabilitation risk stratification / EF < 30%",
        "analysis": "本題問冠心病危險分級何者屬高危險。心臟復健風險分級中，左心室收縮功能嚴重下降、複雜心律不整、運動誘發缺血或低血壓等屬高危險。",
        "options": {
            "A": "不是高危險。急性心肌梗塞後無明顯併發症通常可歸低到中風險，需看運動測試與功能狀態。",
            "B": "正確。LVEF 低於 30% 代表嚴重左心室功能不全，是高危險分級重要條件。",
            "C": "不一定高危險。CABG 後本身不等於高危險，需看 EF、症狀、心律與運動反應。",
            "D": "不一定高危險。年齡 65 歲以上是風險考量，但單獨年齡不是高危險分級的決定條件。",
        },
        "core": "心臟復健高危險重點是嚴重 LV dysfunction、複雜 arrhythmia 或運動誘發不穩定，而非單純年齡或手術史。",
        "key": "LVEF < 30% 屬冠心病復健高危險。",
        "summary": "心臟復健風險 -> EF < 30% 高危險",
        "back": "左心室功能嚴重下降代表運動中不穩定與事件風險較高。",
    },
    67: {
        "front": "congenital brachial plexus injury / Erb / Klumpke",
        "analysis": "本題問先天性臂神經叢受損何者正確。Erb palsy 是上幹 C5-C6 較常見；Klumpke palsy 是下幹 C8-T1 較少見。多數產傷性臂叢損傷可自然恢復良好。",
        "options": {
            "A": "錯誤。Erb palsy 是 upper plexus（C5-C6）損傷，不是下半部。",
            "B": "錯誤。Klumpke palsy 是 lower plexus（C8-T1）損傷，不是上半部。",
            "C": "錯誤。Erb palsy 比 Klumpke palsy 常見。",
            "D": "正確。許多產傷性 Erb 或 Klumpke palsy 可隨時間恢復，雖嚴重撕脫或恢復不佳者需專科評估。",
        },
        "core": "Erb = upper C5-C6；Klumpke = lower C8-T1；產傷性臂叢損傷多數預後良好。",
        "key": "Erb palsy 是上臂叢且較常見，Klumpke 是下臂叢。",
        "summary": "臂叢產傷 -> Erb upper，Klumpke lower，多數恢復佳",
        "back": "Erb 常呈 waiter tip posture；Klumpke 可有手內在肌無力與爪手。",
    },
    68: {
        "front": "kernicterus / athetoid cerebral palsy",
        "analysis": "本題問高膽紅素血症與哪型腦性麻痺關聯最高。未結合膽紅素沉積基底核可造成 kernicterus，典型後遺症是徐動型或舞蹈徐動型腦性麻痺。",
        "options": {
            "A": "不是最相關。痙攣型 CP 最常見，常與早產腦室周圍白質軟化、缺氧缺血等相關。",
            "B": "正確。高膽紅素造成 kernicterus 主要傷害 basal ganglia，與 athetoid/dyskinetic CP 關聯高。",
            "C": "不是最相關。低張型可見於多種中樞或肌肉疾病，但非高膽紅素典型後遺症。",
            "D": "不是最相關。失調型多與小腦相關病變有關。",
        },
        "core": "Kernicterus 傷害 basal ganglia，典型造成 athetoid cerebral palsy、聽損與眼動異常。",
        "key": "Hyperbilirubinemia 最相關的是徐動型腦性麻痺。",
        "summary": "高膽紅素 -> kernicterus -> athetoid CP",
        "back": "膽紅素沉積基底核會造成不自主動作與徐動型腦性麻痺。",
    },
    69: {
        "front": "foot drop / FES / deep peroneal nerve",
        "analysis": "本題問垂足 FES 主要刺激哪條神經。垂足是踝背屈不足，功能性電刺激常在擺盪期刺激腓神經分支，使脛前肌收縮，產生踝背屈。",
        "options": {
            "A": "錯誤。脛神經支配小腿後側肌群，主要造成蹠屈，不是矯正垂足的主要刺激目標。",
            "B": "正確。深腓神經支配 tibialis anterior 等踝背屈肌，刺激後可改善擺盪期足尖拖地。",
            "C": "錯誤。股神經支配股四頭肌，與踝背屈無直接關係。",
            "D": "錯誤。蹠神經支配足底內在肌，不能作為垂足 FES 的主要目標。",
        },
        "core": "垂足 FES 的目標是啟動踝背屈，主要刺激 deep peroneal nerve/tibialis anterior 功能。",
        "key": "垂足功能性電刺激主要刺激深腓神經。",
        "summary": "垂足 FES -> deep peroneal nerve",
        "back": "深腓神經支配脛前肌，刺激可在擺盪期產生足背屈。",
    },
    70: {
        "front": "apraxia / parietal lobe / dressing",
        "analysis": "本題問中風後肌力接近正常但不會穿衣，被診斷失用症，最可能位置。失用症是動作計畫或空間操作障礙，常與頂葉，尤其優勢半球或頂葉聯合區病變相關。",
        "options": {
            "A": "正確。頂葉負責感覺整合、空間與動作計畫，病變可造成 dressing apraxia 或 ideomotor apraxia。",
            "B": "較不符合。額葉病變可造成執行功能、動作啟動或 Broca 相關問題，但穿衣失用更偏頂葉。",
            "C": "較不符合。枕葉主要視覺處理，病變常造成視野缺損或視覺失認。",
            "D": "較不符合。顳葉與語言理解、記憶、聽覺處理相關，非穿衣失用最典型位置。",
        },
        "core": "失用症不是肌力不足，而是動作計畫與空間整合問題；頂葉是高頻定位。",
        "key": "穿衣失用症最常連到頂葉病灶。",
        "summary": "Apraxia -> parietal lobe",
        "back": "肌力接近正常但無法完成 learned movement，要想到 apraxia 與頂葉聯合區。",
    },
    71: {
        "front": "De Quervain tenosynovitis / APL / EPB",
        "analysis": "本題問 De Quervain 肌腱腱鞘炎是哪兩條肌腱。病灶位於第一伸肌隔間，包含 abductor pollicis longus 與 extensor pollicis brevis。",
        "options": {
            "A": "錯誤。伸拇短肌正確，但外展拇短肌是 thenar 肌群，不屬第一伸肌隔間。",
            "B": "錯誤。外展拇長肌正確，但伸拇長肌位於第三伸肌隔間，不是 De Quervain 主要病灶。",
            "C": "正確。伸拇短肌（EPB）與外展拇長肌（APL）是 De Quervain tenosynovitis 的典型兩條肌腱。",
            "D": "錯誤。伸拇長肌與外展拇短肌都不是典型組合。",
        },
        "core": "De Quervain = first dorsal compartment tenosynovitis = APL + EPB。",
        "key": "De Quervain 侵犯 APL 與 EPB。",
        "summary": "De Quervain -> APL + EPB",
        "back": "第一伸肌隔間包含外展拇長肌與伸拇短肌；Finkelstein test 可誘發疼痛。",
    },
    72: {
        "front": "thyroid eye disease imaging / extraocular muscle / orbital fat",
        "analysis": "本題問眼部影像診斷何者錯誤。甲狀腺眼病變可造成眼外肌肥大，也可造成眼眶脂肪增生或水腫，進而造成凸眼。",
        "options": {
            "A": "正確。眼眶腫塊鑑別包括腫瘤如淋巴瘤、視神經腫瘤，也包括血管性病灶。",
            "B": "正確。鼻竇炎或鼻竇腫瘤等眼眶外疾病可侵犯或壓迫眼眶，造成凸眼。",
            "C": "正確。甲狀腺眼病變造成眼外肌變大常為雙側，典型保留肌腱。",
            "D": "錯誤。甲狀腺眼病變不只影響眼外肌，也可造成眼眶脂肪增加、發炎水腫與容積增加。",
        },
        "core": "Thyroid eye disease 影像可見眼外肌肥大與 orbital fat expansion；兩者都可導致 proptosis。",
        "key": "甲狀腺眼病變會造成眼眶脂肪增大或水腫。",
        "summary": "甲狀腺眼病影像 -> 眼外肌肥大 + orbital fat expansion",
        "back": "TED 常雙側眼外肌肥大且可有眶脂肪增生，造成凸眼與壓迫性視神經病變。",
    },
    73: {
        "front": "OPLL / cervical CT / posterior longitudinal ligament",
        "analysis": "本題問頸椎 CT 第 3 至第 4 頸椎鈣化病灶診斷。若鈣化位於椎體後方、椎管前方，沿後縱韌帶走向，最符合後縱韌帶骨化（OPLL）。",
        "options": {
            "A": "較不符合。舊椎體骨折會有椎體高度改變、楔形變或骨折後變形，不是典型後方韌帶鈣化。",
            "B": "正確。OPLL 是 posterior longitudinal ligament ossification，常見於頸椎，可造成脊髓壓迫與頸椎狹窄。",
            "C": "較不符合。僵直性脊椎炎常有 syndesmophyte、竹節脊椎與薦髂關節炎，不是局部後縱韌帶骨化的典型描述。",
            "D": "較不符合。結核性脊椎椎間盤炎常見椎體破壞、椎間盤受侵與冷膿瘍，不是韌帶線狀鈣化。",
        },
        "core": "頸椎椎體後方沿後縱韌帶鈣化，要想到 OPLL，可導致 cervical myelopathy。",
        "key": "Cervical posterior longitudinal ligament ossification 是 OPLL。",
        "summary": "頸椎後方鈣化 -> OPLL",
        "back": "OPLL 常在頸椎造成椎管狹窄與脊髓壓迫，影像位於椎體後緣。",
    },
    74: {
        "front": "teratoma / pelvic X-ray / calcification teeth bone",
        "analysis": "本題問 18 歲女性急性下腹痛與腹部 X 光影像最可能診斷。畸胎瘤常含脂肪、鈣化、牙齒或骨樣成分；年輕女性急性腹痛也需擔心卵巢扭轉。",
        "options": {
            "A": "較不符合。右髂內動脈瘤可有骨盆鈣化影，但 18 歲女性急性下腹痛與典型含鈣化腫塊較不支持。",
            "B": "較不符合。骨盆腔發炎性疾病通常靠症狀、內診與超音波/CT，不會以牙齒或骨樣鈣化為典型 X 光線索。",
            "C": "正確。成熟囊性畸胎瘤可含牙齒、骨頭或鈣化，X 光可見鈣化結構，年輕女性常見。",
            "D": "較不符合。薦骨骨折會有骨折線與外傷史，不會呈現卵巢腫瘤樣鈣化。",
        },
        "core": "年輕女性骨盆腔含鈣化、牙齒或骨樣影像，典型想到卵巢成熟囊性畸胎瘤。",
        "key": "X 光看到骨盆腔牙齒/骨樣鈣化要想到 teratoma。",
        "summary": "年輕女性骨盆鈣化腫塊 -> teratoma",
        "back": "成熟囊性畸胎瘤可含外胚層組織，如毛髮、脂肪、牙齒與骨頭。",
    },
    75: {
        "front": "blunt eye trauma / hyphema / orbital compartment syndrome / globe rupture",
        "analysis": "本題問眼睛鈍傷何者最正確。前房出血可能阻塞房水排出或造成血球堵塞 trabecular meshwork，導致眼壓上升，是重要追蹤點。",
        "options": {
            "A": "不精確。眼球不能上看在鈍傷後常見於眼眶底 blowout fracture 造成下直肌嵌頓，也可能是神經問題，不能直接推第三對腦神經受傷。",
            "B": "正確。Hyphema 可造成眼壓升高、角膜血染與再出血風險，需避免劇烈活動並追蹤眼壓。",
            "C": "錯誤。Preseptal hemorrhage 位於眼眶隔前，通常不造成 orbital compartment syndrome；真正危險的是 retrobulbar hemorrhage。",
            "D": "錯誤。眼球破裂可能視力嚴重下降，但有時初期不一定明顯，不能以視力尚可排除 ruptured globe。",
        },
        "core": "鈍傷後 hyphema 要追蹤眼壓；retrobulbar hemorrhage 才是急性眼眶腔室症候群的典型原因。",
        "key": "前房出血可能造成眼壓升高。",
        "summary": "眼鈍傷 -> hyphema 可升眼壓，retrobulbar hemorrhage 才需緊急減壓",
        "back": "眼外傷若疑眼球破裂不可壓眼，需保護眼罩並緊急眼科處置。",
    },
    76: {
        "front": "adult lateral neck mass / thyroglossal duct cyst",
        "analysis": "本題問成年人頸部側面腫塊原因何者最罕見。成人側頸腫塊要高度懷疑惡性轉移或淋巴瘤，也可能是唾液腺腫瘤；甲狀舌管囊腫典型在中線。",
        "options": {
            "A": "可見。淋巴瘤常以頸部淋巴結腫大表現，成人側頸腫塊需列入鑑別。",
            "B": "可見。腮腺或下頷腺腫瘤可表現為側頸或下頷角附近腫塊。",
            "C": "最罕見。甲狀舌管囊腫典型位於頸部中線、舌骨附近，吞嚥或伸舌會移動，不是成人側頸腫塊常見原因。",
            "D": "可見。成人側頸淋巴結轉移需考慮上消化呼吸道或其他癌症轉移，包括消化道來源。",
        },
        "core": "成人側頸腫塊先排除惡性與轉移；甲狀舌管囊腫典型是中線病灶。",
        "key": "甲狀舌管囊腫通常是頸部中線腫塊，不是成人側頸腫塊常見原因。",
        "summary": "成人側頸腫塊 -> 惡性轉移/淋巴瘤常見；thyroglossal duct cyst 偏中線",
        "back": "成人新出現側頸腫塊要先把惡性淋巴結轉移放在重要鑑別。",
    },
    77: {
        "front": "RSI / head injury / ketamine / intracranial pressure",
        "analysis": "本題問頭部外傷 GCS 7、血壓很高、瞳孔不等大要 RSI 時何藥需特別小心。傳統考點認為 ketamine 可能增加腦血流與顱內壓，頭部外傷或顱壓升高需謹慎；現代觀點較細緻，但考題官方答案仍指 ketamine。",
        "options": {
            "A": "不是最需小心。Lidocaine 曾被用於插管前抑制顱壓反應，雖證據有限，但不是此題的禁忌重點。",
            "B": "正確。Ketamine 傳統上被認為可能升高 intracranial pressure；在疑似顱壓升高、瞳孔不等大的頭部外傷病人需特別小心。",
            "C": "相對適合。Etomidate 對血液動力學影響小，常用於不穩定病人 RSI；需注意腎上腺抑制但不是此題核心。",
            "D": "需注意低血壓但非此題答案。Propofol 可降低腦代謝與顱壓，但會造成低血壓，頭傷病人使用需維持腦灌流壓。",
        },
        "core": "頭部外傷 RSI 要兼顧顱內壓與腦灌流壓；傳統考點對 ketamine 升顱壓採謹慎態度。",
        "key": "疑似顱壓升高的頭部外傷 RSI，ketamine 在傳統考題中需特別小心。",
        "summary": "頭傷 RSI -> 傳統考點 ketamine 需慎用",
        "back": "頭傷插管要避免低血壓、缺氧與顱壓惡化；藥物選擇需看血壓與腦灌流。",
    },
    78: {
        "front": "confidentiality / medical record / truthful documentation",
        "analysis": "本題問病人要求醫師對丈夫保密且病歷不能記載時，醫師如何應對。醫師應維護病人隱私，不任意告知配偶；但病歷屬醫療照護與法律文件，必須誠實完整記載。",
        "options": {
            "A": "正確。醫師可承諾對丈夫保密，除非有法律或重大危害例外；但病歷仍需詳實記載，不能因病人要求而偽造或省略重要資訊。",
            "B": "錯誤。保密可以，但病歷不記載會違反病歷真實性與醫療專業義務。",
            "C": "錯誤。誠實原則不等於必須向丈夫揭露病人私密過去；醫師對病人有保密義務。",
            "D": "錯誤。丈夫一般沒有取得妻子既往婚育史的重大知情權，除非涉及明確重大危害或法定通報。",
        },
        "core": "保密與病歷真實可以並存：對第三人保密，但醫療紀錄需誠實完整。",
        "key": "醫師應保護病人隱私，但不能不實或故意省略病歷。",
        "summary": "醫療倫理 -> 對配偶保密，病歷仍需詳實記載",
        "back": "病人隱私不因婚姻關係自動讓配偶知情；病歷是專業與法律紀錄，需真實。",
    },
    79: {
        "front": "truth telling / autonomy / family request nondisclosure",
        "analysis": "本題問醫師拒絕家屬不要告知癌症報告的要求，是考量哪項倫理原則。病人有權知道自己的診斷與治療選項，醫師應尊重病人的知情與決策自主。",
        "options": {
            "A": "不是最佳。行善原則重視病人利益，但若以保護病人為由剝奪知情，可能造成 paternalism。",
            "B": "正確。尊重自主要求醫師向有決定能力的病人提供重要醫療資訊，讓病人能自行做決策。",
            "C": "不是最佳。不傷害原則可解釋家屬擔心衝擊，但不能作為常規隱瞞診斷的理由。",
            "D": "不是最佳。正義原則關注公平分配與公正對待，不是本題拒絕隱瞞的核心。",
        },
        "core": "癌症診斷告知的倫理核心是尊重病人自主與知情同意；家屬不能取代有能力病人的知情權。",
        "key": "拒絕家屬要求隱瞞病情，主要是尊重病人自主。",
        "summary": "病情告知 -> respect for autonomy",
        "back": "有決定能力的病人有權知道診斷與治療資訊，才能做自主選擇。",
    },
    80: {
        "front": "末期病人急救 / DNR / healthcare proxy / family consent",
        "analysis": "本題問末期病人意識不清且醫護認為死亡不可避免時，不施行急救的優先次序。應先查病人是否已有 DNR 意願書；若無或需確認，再查醫療委任代理人；最後才由家屬依法定程序同意。",
        "options": {
            "A": "正確。先尊重病人已簽署的 DNR 意願書，再查有無醫療委任代理人，最後才徵詢家屬同意，是最符合病人自主優先的順序。",
            "B": "錯誤。若先找家屬而跳過醫療委任代理人，會弱化病人事前指定代理人的效力。",
            "C": "錯誤。醫療委任代理人重要，但若病人已簽 DNR 意願書，應先以病人明示意願為最高優先。",
            "D": "錯誤。先代理人、再家屬、最後才查 DNR 會顛倒病人自主意願的優先性。",
        },
        "core": "末期病人急救決策優先尊重病人本人預立意願，其次是醫療委任代理人，再來才是家屬同意。",
        "key": "DNR 決策順序：先查病人意願書，再查醫療委任代理人，再徵求家屬同意。",
        "summary": "DNR 優先序 -> 意願書 > 醫療委任代理人 > 家屬同意",
        "back": "病人自主優先於家屬意見；意識不清時依預立意願與代理人制度處理。",
    },
}


def main():
    exam = json.loads(Path(SOURCE_FILE).read_text(encoding="utf-8-sig"))
    questions = exam["questions"]
    if len(questions) != 80:
        raise SystemExit(f"expected 80 questions, got {len(questions)}")
    missing = sorted(set(range(1, 81)) - set(ITEMS))
    if missing:
        raise SystemExit(f"missing items: {missing}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for start in range(1, 81, 10):
        end = start + 9
        updates = []
        for q in questions[start - 1 : end]:
            n = q["question_number"]
            item = ITEMS[n]
            updates.append(
                {
                    "question_id": q["id"],
                    "question_number": n,
                    "explanation": exp(item["analysis"], item["options"], item["core"]),
                    "key_point": item["key"],
                    "flashcard_front": item["front"],
                    "flashcard_back": item["back"],
                    "flashcard_summary": item["summary"],
                    "review_status": "ai_generated",
                    "explanation_model": "codex-high-quality-rewrite",
                    "explanation_generated_at": STAMP,
                    "manual_review_notes": item.get("notes", []),
                }
            )
        payload = {
            "source_file": SOURCE_FILE,
            "dataset_id": DATASET_ID,
            "range": {"start": start, "end": end},
            "updates": updates,
        }
        out = OUT_DIR / f"q{start:03d}-q{end:03d}.json"
        out.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {len(range(1, 81, 10))} update files to {OUT_DIR}")


if __name__ == "__main__":
    main()
