from __future__ import annotations

from dataclasses import dataclass
from urllib.parse import urlencode

MOEX_FILE_URL = "https://wwwq.moex.gov.tw/exam/wHandExamQandA_File.ashx"


@dataclass(frozen=True)
class MoexSubject:
    id: str
    year: str
    exam_code: str
    category_code: str
    subject_code: str
    title: str
    subject: str
    group: str
    has_correction: bool = False

    def url(self, kind: str) -> str:
        params = {
            "c": self.category_code,
            "code": self.exam_code,
            "q": "1",
            "s": self.subject_code,
            "t": kind,
        }
        return f"{MOEX_FILE_URL}?{urlencode(params)}"

    @property
    def question_url(self) -> str:
        return self.url("Q")

    @property
    def answer_url(self) -> str:
        return self.url("S")

    @property
    def correction_url(self) -> str:
        return self.url("M")


PHYSICIAN_115_FIRST: list[MoexSubject] = [
    MoexSubject(
        id="115-1-physician-medicine-1",
        year="115-1",
        exam_code="115020",
        category_code="301",
        subject_code="0101",
        title="115 年第一次醫師國考：醫學（一）",
        subject="medicine-1",
        group="醫師(一)",
        has_correction=True,
    ),
    MoexSubject(
        id="115-1-physician-medicine-2",
        year="115-1",
        exam_code="115020",
        category_code="301",
        subject_code="0102",
        title="115 年第一次醫師國考：醫學（二）",
        subject="medicine-2",
        group="醫師(一)",
    ),
    MoexSubject(
        id="115-1-physician-medicine-3",
        year="115-1",
        exam_code="115020",
        category_code="302",
        subject_code="0103",
        title="115 年第一次醫師國考：醫學（三）",
        subject="medicine-3",
        group="醫師(二)",
        has_correction=True,
    ),
    MoexSubject(
        id="115-1-physician-medicine-4",
        year="115-1",
        exam_code="115020",
        category_code="302",
        subject_code="0104",
        title="115 年第一次醫師國考：醫學（四）",
        subject="medicine-4",
        group="醫師(二)",
        has_correction=True,
    ),
    MoexSubject(
        id="115-1-physician-medicine-5",
        year="115-1",
        exam_code="115020",
        category_code="302",
        subject_code="0105",
        title="115 年第一次醫師國考：醫學（五）",
        subject="medicine-5",
        group="醫師(二)",
        has_correction=True,
    ),
    MoexSubject(
        id="115-1-physician-medicine-6",
        year="115-1",
        exam_code="115020",
        category_code="302",
        subject_code="0106",
        title="115 年第一次醫師國考：醫學（六）",
        subject="medicine-6",
        group="醫師(二)",
        has_correction=True,
    ),
]


PHYSICIAN_114_2: list[MoexSubject] = [
    MoexSubject(
        id='114-2-physician-medicine-1',
        year='114-2',
        exam_code='114090',
        category_code='301',
        subject_code='0101',
        title='114 年第二次醫師國考：醫學（一）',
        subject='medicine-1',
        group='醫師(一)',
        has_correction=True,
    ),
    MoexSubject(
        id='114-2-physician-medicine-2',
        year='114-2',
        exam_code='114090',
        category_code='301',
        subject_code='0102',
        title='114 年第二次醫師國考：醫學（二）',
        subject='medicine-2',
        group='醫師(一)',
        has_correction=True,
    ),
    MoexSubject(
        id='114-2-physician-medicine-3',
        year='114-2',
        exam_code='114070',
        category_code='302',
        subject_code='0101',
        title='114 年第二次醫師國考：醫學（三）',
        subject='medicine-3',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='114-2-physician-medicine-4',
        year='114-2',
        exam_code='114070',
        category_code='302',
        subject_code='0102',
        title='114 年第二次醫師國考：醫學（四）',
        subject='medicine-4',
        group='醫師(二)',
    ),
    MoexSubject(
        id='114-2-physician-medicine-5',
        year='114-2',
        exam_code='114070',
        category_code='302',
        subject_code='0103',
        title='114 年第二次醫師國考：醫學（五）',
        subject='medicine-5',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='114-2-physician-medicine-6',
        year='114-2',
        exam_code='114070',
        category_code='302',
        subject_code='0104',
        title='114 年第二次醫師國考：醫學（六）',
        subject='medicine-6',
        group='醫師(二)',
        has_correction=True,
    ),
]

PHYSICIAN_114_1: list[MoexSubject] = [
    MoexSubject(
        id='114-1-physician-medicine-1',
        year='114-1',
        exam_code='114020',
        category_code='301',
        subject_code='0101',
        title='114 年第一次醫師國考：醫學（一）',
        subject='medicine-1',
        group='醫師(一)',
        has_correction=True,
    ),
    MoexSubject(
        id='114-1-physician-medicine-2',
        year='114-1',
        exam_code='114020',
        category_code='301',
        subject_code='0102',
        title='114 年第一次醫師國考：醫學（二）',
        subject='medicine-2',
        group='醫師(一)',
        has_correction=True,
    ),
    MoexSubject(
        id='114-1-physician-medicine-3',
        year='114-1',
        exam_code='114020',
        category_code='302',
        subject_code='0103',
        title='114 年第一次醫師國考：醫學（三）',
        subject='medicine-3',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='114-1-physician-medicine-4',
        year='114-1',
        exam_code='114020',
        category_code='302',
        subject_code='0104',
        title='114 年第一次醫師國考：醫學（四）',
        subject='medicine-4',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='114-1-physician-medicine-5',
        year='114-1',
        exam_code='114020',
        category_code='302',
        subject_code='0105',
        title='114 年第一次醫師國考：醫學（五）',
        subject='medicine-5',
        group='醫師(二)',
    ),
    MoexSubject(
        id='114-1-physician-medicine-6',
        year='114-1',
        exam_code='114020',
        category_code='302',
        subject_code='0106',
        title='114 年第一次醫師國考：醫學（六）',
        subject='medicine-6',
        group='醫師(二)',
        has_correction=True,
    ),
]

PHYSICIAN_113_2: list[MoexSubject] = [
    MoexSubject(
        id='113-2-physician-medicine-1',
        year='113-2',
        exam_code='113090',
        category_code='301',
        subject_code='11',
        title='113 年第二次醫師國考：醫學（一）',
        subject='medicine-1',
        group='醫師(一)',
    ),
    MoexSubject(
        id='113-2-physician-medicine-2',
        year='113-2',
        exam_code='113090',
        category_code='301',
        subject_code='22',
        title='113 年第二次醫師國考：醫學（二）',
        subject='medicine-2',
        group='醫師(一)',
        has_correction=True,
    ),
    MoexSubject(
        id='113-2-physician-medicine-3',
        year='113-2',
        exam_code='113070',
        category_code='302',
        subject_code='11',
        title='113 年第二次醫師國考：醫學（三）',
        subject='medicine-3',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='113-2-physician-medicine-4',
        year='113-2',
        exam_code='113070',
        category_code='302',
        subject_code='22',
        title='113 年第二次醫師國考：醫學（四）',
        subject='medicine-4',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='113-2-physician-medicine-5',
        year='113-2',
        exam_code='113070',
        category_code='302',
        subject_code='33',
        title='113 年第二次醫師國考：醫學（五）',
        subject='medicine-5',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='113-2-physician-medicine-6',
        year='113-2',
        exam_code='113070',
        category_code='302',
        subject_code='44',
        title='113 年第二次醫師國考：醫學（六）',
        subject='medicine-6',
        group='醫師(二)',
    ),
]

PHYSICIAN_113_1: list[MoexSubject] = [
    MoexSubject(
        id='113-1-physician-medicine-1',
        year='113-1',
        exam_code='113020',
        category_code='301',
        subject_code='11',
        title='113 年第一次醫師國考：醫學（一）',
        subject='medicine-1',
        group='醫師(一)',
        has_correction=True,
    ),
    MoexSubject(
        id='113-1-physician-medicine-2',
        year='113-1',
        exam_code='113020',
        category_code='301',
        subject_code='22',
        title='113 年第一次醫師國考：醫學（二）',
        subject='medicine-2',
        group='醫師(一)',
    ),
    MoexSubject(
        id='113-1-physician-medicine-3',
        year='113-1',
        exam_code='113020',
        category_code='302',
        subject_code='11',
        title='113 年第一次醫師國考：醫學（三）',
        subject='medicine-3',
        group='醫師(二)',
    ),
    MoexSubject(
        id='113-1-physician-medicine-4',
        year='113-1',
        exam_code='113020',
        category_code='302',
        subject_code='22',
        title='113 年第一次醫師國考：醫學（四）',
        subject='medicine-4',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='113-1-physician-medicine-5',
        year='113-1',
        exam_code='113020',
        category_code='302',
        subject_code='33',
        title='113 年第一次醫師國考：醫學（五）',
        subject='medicine-5',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='113-1-physician-medicine-6',
        year='113-1',
        exam_code='113020',
        category_code='302',
        subject_code='44',
        title='113 年第一次醫師國考：醫學（六）',
        subject='medicine-6',
        group='醫師(二)',
    ),
]

PHYSICIAN_112_2: list[MoexSubject] = [
    MoexSubject(
        id='112-2-physician-medicine-1',
        year='112-2',
        exam_code='112100',
        category_code='301',
        subject_code='11',
        title='112 年第二次醫師國考：醫學（一）',
        subject='medicine-1',
        group='醫師(一)',
    ),
    MoexSubject(
        id='112-2-physician-medicine-2',
        year='112-2',
        exam_code='112100',
        category_code='301',
        subject_code='22',
        title='112 年第二次醫師國考：醫學（二）',
        subject='medicine-2',
        group='醫師(一)',
        has_correction=True,
    ),
    MoexSubject(
        id='112-2-physician-medicine-3',
        year='112-2',
        exam_code='112080',
        category_code='302',
        subject_code='11',
        title='112 年第二次醫師國考：醫學（三）',
        subject='medicine-3',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='112-2-physician-medicine-4',
        year='112-2',
        exam_code='112080',
        category_code='302',
        subject_code='22',
        title='112 年第二次醫師國考：醫學（四）',
        subject='medicine-4',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='112-2-physician-medicine-5',
        year='112-2',
        exam_code='112080',
        category_code='302',
        subject_code='33',
        title='112 年第二次醫師國考：醫學（五）',
        subject='medicine-5',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='112-2-physician-medicine-6',
        year='112-2',
        exam_code='112080',
        category_code='302',
        subject_code='44',
        title='112 年第二次醫師國考：醫學（六）',
        subject='medicine-6',
        group='醫師(二)',
        has_correction=True,
    ),
]

PHYSICIAN_112_1: list[MoexSubject] = [
    MoexSubject(
        id='112-1-physician-medicine-1',
        year='112-1',
        exam_code='112020',
        category_code='301',
        subject_code='11',
        title='112 年第一次醫師國考：醫學（一）',
        subject='medicine-1',
        group='醫師(一)',
        has_correction=True,
    ),
    MoexSubject(
        id='112-1-physician-medicine-2',
        year='112-1',
        exam_code='112020',
        category_code='301',
        subject_code='22',
        title='112 年第一次醫師國考：醫學（二）',
        subject='medicine-2',
        group='醫師(一)',
        has_correction=True,
    ),
    MoexSubject(
        id='112-1-physician-medicine-3',
        year='112-1',
        exam_code='112020',
        category_code='302',
        subject_code='11',
        title='112 年第一次醫師國考：醫學（三）',
        subject='medicine-3',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='112-1-physician-medicine-4',
        year='112-1',
        exam_code='112020',
        category_code='302',
        subject_code='22',
        title='112 年第一次醫師國考：醫學（四）',
        subject='medicine-4',
        group='醫師(二)',
    ),
    MoexSubject(
        id='112-1-physician-medicine-5',
        year='112-1',
        exam_code='112020',
        category_code='302',
        subject_code='33',
        title='112 年第一次醫師國考：醫學（五）',
        subject='medicine-5',
        group='醫師(二)',
    ),
    MoexSubject(
        id='112-1-physician-medicine-6',
        year='112-1',
        exam_code='112020',
        category_code='302',
        subject_code='44',
        title='112 年第一次醫師國考：醫學（六）',
        subject='medicine-6',
        group='醫師(二)',
    ),
]

PHYSICIAN_111_2: list[MoexSubject] = [
    MoexSubject(
        id='111-2-physician-medicine-1',
        year='111-2',
        exam_code='111100',
        category_code='301',
        subject_code='11',
        title='111 年第二次醫師國考：醫學（一）',
        subject='medicine-1',
        group='醫師(一)',
        has_correction=True,
    ),
    MoexSubject(
        id='111-2-physician-medicine-2',
        year='111-2',
        exam_code='111100',
        category_code='301',
        subject_code='22',
        title='111 年第二次醫師國考：醫學（二）',
        subject='medicine-2',
        group='醫師(一)',
        has_correction=True,
    ),
    MoexSubject(
        id='111-2-physician-medicine-3',
        year='111-2',
        exam_code='111080',
        category_code='302',
        subject_code='11',
        title='111 年第二次醫師國考：醫學（三）',
        subject='medicine-3',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='111-2-physician-medicine-4',
        year='111-2',
        exam_code='111080',
        category_code='302',
        subject_code='22',
        title='111 年第二次醫師國考：醫學（四）',
        subject='medicine-4',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='111-2-physician-medicine-5',
        year='111-2',
        exam_code='111080',
        category_code='302',
        subject_code='33',
        title='111 年第二次醫師國考：醫學（五）',
        subject='medicine-5',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='111-2-physician-medicine-6',
        year='111-2',
        exam_code='111080',
        category_code='302',
        subject_code='44',
        title='111 年第二次醫師國考：醫學（六）',
        subject='medicine-6',
        group='醫師(二)',
        has_correction=True,
    ),
]

PHYSICIAN_111_1: list[MoexSubject] = [
    MoexSubject(
        id='111-1-physician-medicine-1',
        year='111-1',
        exam_code='111020',
        category_code='301',
        subject_code='11',
        title='111 年第一次醫師國考：醫學（一）',
        subject='medicine-1',
        group='醫師(一)',
    ),
    MoexSubject(
        id='111-1-physician-medicine-2',
        year='111-1',
        exam_code='111020',
        category_code='301',
        subject_code='22',
        title='111 年第一次醫師國考：醫學（二）',
        subject='medicine-2',
        group='醫師(一)',
        has_correction=True,
    ),
    MoexSubject(
        id='111-1-physician-medicine-3',
        year='111-1',
        exam_code='111020',
        category_code='302',
        subject_code='11',
        title='111 年第一次醫師國考：醫學（三）',
        subject='medicine-3',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='111-1-physician-medicine-4',
        year='111-1',
        exam_code='111020',
        category_code='302',
        subject_code='22',
        title='111 年第一次醫師國考：醫學（四）',
        subject='medicine-4',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='111-1-physician-medicine-5',
        year='111-1',
        exam_code='111020',
        category_code='302',
        subject_code='33',
        title='111 年第一次醫師國考：醫學（五）',
        subject='medicine-5',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='111-1-physician-medicine-6',
        year='111-1',
        exam_code='111020',
        category_code='302',
        subject_code='44',
        title='111 年第一次醫師國考：醫學（六）',
        subject='medicine-6',
        group='醫師(二)',
        has_correction=True,
    ),
]

PHYSICIAN_110_2: list[MoexSubject] = [
    MoexSubject(
        id='110-2-physician-medicine-1',
        year='110-2',
        exam_code='110101',
        category_code='301',
        subject_code='11',
        title='110 年第二次醫師國考：醫學（一）',
        subject='medicine-1',
        group='醫師(一)',
        has_correction=True,
    ),
    MoexSubject(
        id='110-2-physician-medicine-2',
        year='110-2',
        exam_code='110101',
        category_code='301',
        subject_code='22',
        title='110 年第二次醫師國考：醫學（二）',
        subject='medicine-2',
        group='醫師(一)',
        has_correction=True,
    ),
    MoexSubject(
        id='110-2-physician-medicine-3',
        year='110-2',
        exam_code='110080',
        category_code='302',
        subject_code='11',
        title='110 年第二次醫師國考：醫學（三）',
        subject='medicine-3',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='110-2-physician-medicine-4',
        year='110-2',
        exam_code='110080',
        category_code='302',
        subject_code='22',
        title='110 年第二次醫師國考：醫學（四）',
        subject='medicine-4',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='110-2-physician-medicine-5',
        year='110-2',
        exam_code='110080',
        category_code='302',
        subject_code='33',
        title='110 年第二次醫師國考：醫學（五）',
        subject='medicine-5',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='110-2-physician-medicine-6',
        year='110-2',
        exam_code='110080',
        category_code='302',
        subject_code='44',
        title='110 年第二次醫師國考：醫學（六）',
        subject='medicine-6',
        group='醫師(二)',
    ),
]

PHYSICIAN_110_1: list[MoexSubject] = [
    MoexSubject(
        id='110-1-physician-medicine-1',
        year='110-1',
        exam_code='110020',
        category_code='301',
        subject_code='11',
        title='110 年第一次醫師國考：醫學（一）',
        subject='medicine-1',
        group='醫師(一)',
    ),
    MoexSubject(
        id='110-1-physician-medicine-2',
        year='110-1',
        exam_code='110020',
        category_code='301',
        subject_code='22',
        title='110 年第一次醫師國考：醫學（二）',
        subject='medicine-2',
        group='醫師(一)',
        has_correction=True,
    ),
    MoexSubject(
        id='110-1-physician-medicine-3',
        year='110-1',
        exam_code='110020',
        category_code='302',
        subject_code='11',
        title='110 年第一次醫師國考：醫學（三）',
        subject='medicine-3',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='110-1-physician-medicine-4',
        year='110-1',
        exam_code='110020',
        category_code='302',
        subject_code='22',
        title='110 年第一次醫師國考：醫學（四）',
        subject='medicine-4',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='110-1-physician-medicine-5',
        year='110-1',
        exam_code='110020',
        category_code='302',
        subject_code='33',
        title='110 年第一次醫師國考：醫學（五）',
        subject='medicine-5',
        group='醫師(二)',
    ),
    MoexSubject(
        id='110-1-physician-medicine-6',
        year='110-1',
        exam_code='110020',
        category_code='302',
        subject_code='44',
        title='110 年第一次醫師國考：醫學（六）',
        subject='medicine-6',
        group='醫師(二)',
    ),
]

PHYSICIAN_109_2: list[MoexSubject] = [
    MoexSubject(
        id='109-2-physician-medicine-1',
        year='109-2',
        exam_code='109100',
        category_code='301',
        subject_code='11',
        title='109 年第二次醫師國考：醫學（一）',
        subject='medicine-1',
        group='醫師(一)',
        has_correction=True,
    ),
    MoexSubject(
        id='109-2-physician-medicine-2',
        year='109-2',
        exam_code='109100',
        category_code='301',
        subject_code='22',
        title='109 年第二次醫師國考：醫學（二）',
        subject='medicine-2',
        group='醫師(一)',
        has_correction=True,
    ),
    MoexSubject(
        id='109-2-physician-medicine-3',
        year='109-2',
        exam_code='109080',
        category_code='302',
        subject_code='11',
        title='109 年第二次醫師國考：醫學（三）',
        subject='medicine-3',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='109-2-physician-medicine-4',
        year='109-2',
        exam_code='109080',
        category_code='302',
        subject_code='22',
        title='109 年第二次醫師國考：醫學（四）',
        subject='medicine-4',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='109-2-physician-medicine-5',
        year='109-2',
        exam_code='109080',
        category_code='302',
        subject_code='33',
        title='109 年第二次醫師國考：醫學（五）',
        subject='medicine-5',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='109-2-physician-medicine-6',
        year='109-2',
        exam_code='109080',
        category_code='302',
        subject_code='44',
        title='109 年第二次醫師國考：醫學（六）',
        subject='medicine-6',
        group='醫師(二)',
    ),
]

PHYSICIAN_109_1: list[MoexSubject] = [
    MoexSubject(
        id='109-1-physician-medicine-1',
        year='109-1',
        exam_code='109020',
        category_code='301',
        subject_code='11',
        title='109 年第一次醫師國考：醫學（一）',
        subject='medicine-1',
        group='醫師(一)',
        has_correction=True,
    ),
    MoexSubject(
        id='109-1-physician-medicine-2',
        year='109-1',
        exam_code='109020',
        category_code='301',
        subject_code='22',
        title='109 年第一次醫師國考：醫學（二）',
        subject='medicine-2',
        group='醫師(一)',
        has_correction=True,
    ),
    MoexSubject(
        id='109-1-physician-medicine-3',
        year='109-1',
        exam_code='109020',
        category_code='302',
        subject_code='11',
        title='109 年第一次醫師國考：醫學（三）',
        subject='medicine-3',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='109-1-physician-medicine-4',
        year='109-1',
        exam_code='109020',
        category_code='302',
        subject_code='22',
        title='109 年第一次醫師國考：醫學（四）',
        subject='medicine-4',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='109-1-physician-medicine-5',
        year='109-1',
        exam_code='109020',
        category_code='302',
        subject_code='33',
        title='109 年第一次醫師國考：醫學（五）',
        subject='medicine-5',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='109-1-physician-medicine-6',
        year='109-1',
        exam_code='109020',
        category_code='302',
        subject_code='44',
        title='109 年第一次醫師國考：醫學（六）',
        subject='medicine-6',
        group='醫師(二)',
        has_correction=True,
    ),
]

PHYSICIAN_108_2: list[MoexSubject] = [
    MoexSubject(
        id='108-2-physician-medicine-1',
        year='108-2',
        exam_code='108100',
        category_code='301',
        subject_code='11',
        title='108 年第二次醫師國考：醫學（一）',
        subject='medicine-1',
        group='醫師(一)',
    ),
    MoexSubject(
        id='108-2-physician-medicine-2',
        year='108-2',
        exam_code='108100',
        category_code='301',
        subject_code='22',
        title='108 年第二次醫師國考：醫學（二）',
        subject='medicine-2',
        group='醫師(一)',
        has_correction=True,
    ),
    MoexSubject(
        id='108-2-physician-medicine-3',
        year='108-2',
        exam_code='108080',
        category_code='302',
        subject_code='11',
        title='108 年第二次醫師國考：醫學（三）',
        subject='medicine-3',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='108-2-physician-medicine-4',
        year='108-2',
        exam_code='108080',
        category_code='302',
        subject_code='22',
        title='108 年第二次醫師國考：醫學（四）',
        subject='medicine-4',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='108-2-physician-medicine-5',
        year='108-2',
        exam_code='108080',
        category_code='302',
        subject_code='33',
        title='108 年第二次醫師國考：醫學（五）',
        subject='medicine-5',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='108-2-physician-medicine-6',
        year='108-2',
        exam_code='108080',
        category_code='302',
        subject_code='44',
        title='108 年第二次醫師國考：醫學（六）',
        subject='medicine-6',
        group='醫師(二)',
        has_correction=True,
    ),
]

PHYSICIAN_108_1: list[MoexSubject] = [
    MoexSubject(
        id='108-1-physician-medicine-1',
        year='108-1',
        exam_code='108030',
        category_code='301',
        subject_code='11',
        title='108 年第一次醫師國考：醫學（一）',
        subject='medicine-1',
        group='醫師(一)',
        has_correction=True,
    ),
    MoexSubject(
        id='108-1-physician-medicine-2',
        year='108-1',
        exam_code='108030',
        category_code='301',
        subject_code='22',
        title='108 年第一次醫師國考：醫學（二）',
        subject='medicine-2',
        group='醫師(一)',
        has_correction=True,
    ),
    MoexSubject(
        id='108-1-physician-medicine-3',
        year='108-1',
        exam_code='108030',
        category_code='302',
        subject_code='11',
        title='108 年第一次醫師國考：醫學（三）',
        subject='medicine-3',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='108-1-physician-medicine-4',
        year='108-1',
        exam_code='108030',
        category_code='302',
        subject_code='22',
        title='108 年第一次醫師國考：醫學（四）',
        subject='medicine-4',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='108-1-physician-medicine-5',
        year='108-1',
        exam_code='108030',
        category_code='302',
        subject_code='33',
        title='108 年第一次醫師國考：醫學（五）',
        subject='medicine-5',
        group='醫師(二)',
        has_correction=True,
    ),
    MoexSubject(
        id='108-1-physician-medicine-6',
        year='108-1',
        exam_code='108030',
        category_code='302',
        subject_code='44',
        title='108 年第一次醫師國考：醫學（六）',
        subject='medicine-6',
        group='醫師(二)',
        has_correction=True,
    ),
]


PRESETS = {
    "physician-115-first": PHYSICIAN_115_FIRST,
    "physician-114-second": PHYSICIAN_114_2,
    "physician-114-first": PHYSICIAN_114_1,
    "physician-113-second": PHYSICIAN_113_2,
    "physician-113-first": PHYSICIAN_113_1,
    "physician-112-second": PHYSICIAN_112_2,
    "physician-112-first": PHYSICIAN_112_1,
    "physician-111-second": PHYSICIAN_111_2,
    "physician-111-first": PHYSICIAN_111_1,
    "physician-110-second": PHYSICIAN_110_2,
    "physician-110-first": PHYSICIAN_110_1,
    "physician-109-second": PHYSICIAN_109_2,
    "physician-109-first": PHYSICIAN_109_1,
    "physician-108-second": PHYSICIAN_108_2,
    "physician-108-first": PHYSICIAN_108_1,
}

def get_preset(name: str) -> list[MoexSubject]:
    try:
        return PRESETS[name]
    except KeyError as exc:
        choices = ", ".join(sorted(PRESETS))
        raise ValueError(f"Unknown preset {name!r}. Choices: {choices}") from exc
